Added debug logging for table stats
ydb-platform/ydb pull request #10065
Opened 2024-10-03 16:39 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-04 08:07 UTC, ivanmorozov333 requested changes

2024-10-04 08:07 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
не надо копировать, если не собираемся логировать.

2024-10-04 08:07 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +        LOG_S_DEBUG("PortionStats updated, type " << (ui32)updateType << " pathId " << portionInfo.GetPathId() << " portion " << portionInfo.GetPortionId() << " size " << before.Bytes << "->" << afte
AFL_ макрос

2024-10-04 08:15 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
Так я же дальше логирую мемберы из before
Или отдельные мемеберы запоминать?

2024-10-04 08:34 UTC, ivanmorozov333 requested changes

2024-10-04 08:34 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    if (TlsActivationContext != nullptr) { // can be null in tests
эта проверка не нужна. в макросах она делается.

2024-10-04 08:34 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
не понимаю ответ. могу только повторить то что написал.

2024-10-04 08:42 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
В следующей строке контент модифицируется и Active будет возвращать другие значения, а еще строкой ниже происходит логирование, и там используется before

2024-10-04 11:54 UTC, ivanmorozov333 requested changes

2024-10-04 11:54 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
> +    static const char* UpdateName(EStatsUpdateType type) {
генеренными воспользуйся... через ya.make

2024-10-04 11:54 UTC, ivanmorozov333 commented on ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
> +    LOG_DEBUG_S(ctx, NKikimrServices::FLAT_TX_SCHEMESHARD,
тут, тоже, поменяй макрос

2024-10-04 11:54 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
ну придумай что-нибудь. если ты не логируешь, то это копирование тебе не нужно

2024-10-04 12:28 UTC, aavdonkin commented on ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
> +    LOG_DEBUG_S(ctx, NKikimrServices::FLAT_TX_SCHEMESHARD,
В schemeshard AFL_ макросы вообще не используются, а LOG_DEBUG_S прямо в этом бинарнике уже есть

2024-10-04 12:48 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
В смысле не логирую ? А в строке 66 "("before_size", before.Bytes") это что тогда?

2024-10-04 13:00 UTC, ivanmorozov333 requested changes

2024-10-04 13:00 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    auto before = Counters.Active();
1. ты логируешь в DEBUG mode
2. у тебя может быть не DEBUG mode логирования для компонента TX_COLUMNSHARD (почти всегда)
3. в этом случае, скопированные объекты не используются
4. не надо копировать объекты, если копии не используются

2024-10-07 08:21 UTC, ivanmorozov333 approved these changes

2024-10-07 08:23 UTC, merged