[docs] manual deployment refactoring
ydb-platform/ydb pull request #10078
Opened 2024-10-04 07:58 UTC by blinkov

### Changelog category 

* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

* Move out the legacy deploy/ folder content to devops/manual/ and reference/configuration/
* Initial content for reference/configuration/tls.md

2024-10-05 12:19 UTC, fomichev3000 requested changes

2024-10-05 12:19 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/tls.md
> +# Настройка TLS
Я бы для каждого раздела явно бы указал дефолтный порт. Вроде это ничего не стоит, но как-то читаешь и ближе к земле. И для IC, и для grpc, и для Kafka c Postgres

2024-10-05 12:19 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/tls.md
> +Пример включения TLS для LDAP через расширение протокола `StartTls`:
Я бы прямо поставил ссылку на https://ydb.tech/docs/ru/deploy/configuration/config#ldap-auth-config. Подробности читайте по этой ссылке

2024-10-05 12:19 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/tls.md
> +## Interconnect
Кажется, сейчас раздел можно и таким закоммитить, но давай явно запишем на эту страницу https://ydb.tech/docs/en/deploy/configuration/config добавить информацию по конфигурированию IC

2024-10-05 12:19 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/tls.md
> +{{ ydb-short-name }} открывает отдельный HTTP порт для работы [встроенного интерфейса](../../reference/embedded-ui/index.md), отображения [метрик](../../devops/manual/monitoring.md) и других вспомога
```suggestion
{{ ydb-short-name }} открывает отдельный HTTP порт для работы [встроенного интерфейса](../../reference/embedded-ui/index.md), отображения [метрик](../../devops/manual/monitoring.md) и других вспомогательных команд.
```

2024-10-05 12:19 UTC, fomichev3000 commented on ydb/docs/redirects.yaml
> +    to: /reference/configuration/index.md
Мне норм, что длинный документ с параметрами переезжает в Справка/Конфигурация, только я бы не делал этот длиннющий документ документом по умолчанию при нажатии на  Справка/Конфигурация. Я бы отдельный документ сделал. Ну или у тебя планы разбить этот документ на куски?

2024-10-07 02:13 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/tls.md
> +## Interconnect
YDBDOCS-859

2024-10-07 02:13 UTC, blinkov commented on ydb/docs/redirects.yaml
> +    to: /reference/configuration/index.md
> Ну или у тебя планы разбить этот документ на куски?

Да, это

2024-10-07 02:30 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/tls.md
> +# Настройка TLS
Сложность с этим в том, что насколько я понимаю глобально у нас нет дефолтных портов. Если у самого `ydbd` не указать порт для такого-то сервиса — он по умолчанию просто не запускается. Подобие дефолтов типа 2135 и 8765 возникают в различных скриптах обвязки и не факт, что везде одинаково.

Единственное известное мне исключение — PostgreSQL-совместимость почему-то запускается на 5432 даже если её не просили.

2024-10-07 02:33 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/tls.md
> +Пример включения TLS для LDAP через расширение протокола `StartTls`:
Изначально я её не добавил т.к. у этого контента по ссылке долг, английской версии нет, но ок — добавил пока только в русской.

2024-10-12 16:24 UTC, fomichev3000 approved these changes

2024-10-21 23:54 UTC, merged