Added a section about the JDBC driver
ydb-platform/ydb pull request #10147
Opened 2024-10-07 06:05 UTC by anton-bobkov

### Changelog category

* Documentation

### Additional information

Added a section about the JDBC driver

2024-10-07 08:41 UTC, blinkov requested changes

2024-10-07 08:41 UTC, blinkov commented on ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/properties.md
> +    Default value: `false`.
```suggestion
# JDBC driver properties

The JDBC driver for {{ ydb-short-name }} supports the following configuration properties, which can be specified in the [JDBC URL](#jdbc-url-examples) or passed via additional properties:

* `saFile` — service account key for authentication. The valid value is either the content of the JSON file or a file reference. {#saFile}

* `iamEndpoint` — custom IAM endpoint for authentication using a service account key.

* `token` — token value for authentication. The valid value is either the token content or a token file reference. {#token}

* `useMetadata` — indicates whether to use metadata authentication. Valid values are: {#useMetadata}

    - `true` — use metadata authentication.
    - `false` — do not use metadata authentication.

    Default value: `false`.
```

2024-10-07 08:41 UTC, blinkov commented on ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/properties.md
> +    Usually you indicate whether a connection is secure or not by using the `grpcs://` scheme for secure connections and `grpc://` for insecure connections in the JDBC URL.
```suggestion
    The primary way to indicate whether a connection is secure or not is by using the `grpcs://` scheme for secure connections and `grpc://` for insecure connections in the JDBC URL. This property allows overriding it.
```
I didn't check whether this is correct but it sounds like it.

2024-10-07 08:41 UTC, blinkov commented on ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/properties.md
> +    - `false` — do not enforce TLS.
```suggestion
* `metadataURL` — custom metadata endpoint.

* `localDatacenter` — the name of the data center local to the application being connected.

* `secureConnection` — indicates whether to use TLS. Valid values are:

    - `true` — enforce TLS.
    - `false` — do not enforce TLS.
```

2024-10-08 14:02 UTC, alex268 commented on ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/maven.md
> +    </dependency>
I think we can remove the section of shaded version. This version is preferable for standalone usage, like connection to YDB in IDEs

2024-10-09 06:21 UTC, blinkov submitted a review, later dismissed

2024-10-10 06:46 UTC, fomichev3000 approved these changes

2024-10-10 06:46 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/toc_p.yaml
> +- name: Языки и API
Меня смущает порядок пунктов в ToC в "Справка". Например, я бы предпочел, чтобы либо уж по алфавиту (но это не очень), либо по логике. По логике "YDB Native SDK" и "Языки и API" должны быть рядом

2024-10-10 06:46 UTC, merged