Force precompute for returning effect input
ydb-platform/ydb pull request #10231
Opened 2024-10-08 19:51 UTC by ssmike

### Changelog entry 

Force precompute on returning effect input

### Changelog category 
* Bugfix

2024-10-10 20:12 UTC, gridnevvvit submitted a review, later dismissed

2024-10-11 09:01 UTC, rvu1024 commented on ydb/library/yql/dq/opt/dq_opt_phy.cpp
> +    if (typeAnn->GetKind() != ETypeAnnotationKind::List && typeAnn->GetKind() != ETypeAnnotationKind::Optional) {
Тут точно Optional ожидаемый тип? Take не типизируется на Optional входе

2024-10-14 12:36 UTC, rvu1024 requested changes
см. выше

2024-10-21 08:34 UTC, ssmike commented on ydb/library/yql/dq/opt/dq_opt_phy.cpp
> +    if (typeAnn->GetKind() != ETypeAnnotationKind::List && typeAnn->GetKind() != ETypeAnnotationKind::Optional) {
Тут уверенности вообще не было, потому что в типизаторе используется хелпер GetSequentialType<...>(), а он при некотором наборе параметров Optional вполне себе принимает. Но раз говоришь значит примем на веру что тут List

2024-10-21 08:35 UTC, ssmike commented on ydb/library/yql/dq/opt/dq_opt_phy.cpp
> +    if (!typeAnn || typeAnn->GetKind() != ETypeAnnotationKind::Stream) {
Переделал на List и сделал проверку более специфичной чтобы покрыть наш конкретный кейс

2024-10-21 13:26 UTC, rvu1024 approved these changes

2024-10-22 05:29 UTC, merged