Added explanation of scrubbing
ydb-platform/ydb pull request #103
Opened 2022-07-23 12:33 UTC by MichaelMonashev

2022-08-01 11:58 UTC, the-ancient-1 requested changes

2022-08-01 11:58 UTC, the-ancient-1 commented on ydb/docs/ru/core/maintenance/manual/scrubbing.md
> +Scrubbing — это метод исправления ошибок, который периодически проверяет хранилище на наличие ошибок, а затем исправляет обнаруженные ошибки, используя избыточные данные.
Метод — это совокупность рациональных действий, которые необходимо предпринять, чтобы решить определённую задачу или достичь определённой цели. 

Scrubbing - не метод.

2022-08-01 12:30 UTC, MichaelMonashev commented on ydb/docs/ru/core/maintenance/manual/scrubbing.md
> +Scrubbing — это метод исправления ошибок, который периодически проверяет хранилище на наличие ошибок, а затем исправляет обнаруженные ошибки, используя избыточные данные.
А как написать лучше?

2022-10-17 09:12 UTC, kochub commented on ydb/docs/ru/core/maintenance/manual/scrubbing.md
> +Scrubbing — это метод исправления ошибок, который периодически проверяет хранилище на наличие ошибок, а затем исправляет обнаруженные ошибки, используя избыточные данные.
"Процесс исправления ошибок", кажется так более верно звучит

2023-01-20 15:08 UTC, closed without merging