Release node name on graceful shutdown (Issue #9734)
ydb-platform/ydb pull request #10367
Opened 2024-10-13 14:19 UTC by stanislav-shchetinin

### Changelog entry 

...

### Changelog category 

* Improvement

### Additional information

...

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +    if (graceful) {
Ты добавил флаг `EnableDecommissionNode`, но не обрабатываешь его.

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/mind/node_broker.cpp
> +    .UpdateToNull<T::SlotIndex>();
```suggestion
    db.Table<T>().Key(node.NodeId)
        .UpdateToNull<T::SlotIndex>();
```

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/mind/node_broker_impl.h
> +    void DbUpdateSlotIndexToNull(const TNodeInfo &node,
Может лучше `DbReleaseSlotIndex`?

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/mind/node_broker__decommission_node.cpp
> +#include <ydb/core/base/appdata.h>
Вроде это тут не используется.

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/mind/node_broker__decommission_node.cpp
> +        TString addr = rec.GetAddress();
Тут лишняя копия, можно без нее:
```suggestion
        const auto& addr = rec.GetAddress();
```

2024-10-14 09:21 UTC, CyberROFL commented on ydb/core/mind/node_broker__decommission_node.cpp
> +            if (Self->EnableDecomissionNode) {
А вот тут уже можно и не обрабатывать флаг.

2024-10-14 11:45 UTC, pixcc reviewed
Добавь, пожалуйста, какой-нибудь тестик в `node_broker_ut.cpp`, в котором будут посылаться `DecomissionRequest` в `NodeBroker` и проверяться логика обработки этого сообщения.

2024-10-14 11:45 UTC, pixcc commented on ydb/core/mind/node_broker__decommission_node.cpp
> +namespace NNodeBroker {
можно в новом коде писать вот так `NKikimr::NNodeBroker`

2024-10-14 11:45 UTC, pixcc commented on ydb/core/mind/node_broker.h
> +        EvDecommissionResponse,
От такого поедут идентификаторы типов сообщений. Не будет ли проблем при пересылке сообщений между нодами с разными версиями YDB?

2024-10-14 11:47 UTC, pixcc commented on ydb/core/mind/node_broker.cpp
> +void TNodeBroker::Handle(TEvNodeBroker::TEvDecommissionRequest::TPtr &ev,
Добавь, пожалуйста, поддержку в сенсоры запросов для нового типа сообщений. Смотри для примера `TEvExtendLeaseRequest`

2024-10-14 13:34 UTC, stanislav-shchetinin commented on ydb/core/driver_lib/run/run.cpp
> +        ActorSystem->Send(new IEventHandle(nodeBrokerPipe, {}, new NKikimr::NNodeBroker::TEvNodeBroker::TEvDecommissionRequest));
При обработке в транзакции я не использую дополнительные данные, только `Record` и `Sender`

2024-10-14 14:09 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +        ActorSystem->Send(new IEventHandle(nodeBrokerPipe, {}, new NKikimr::NNodeBroker::TEvNodeBroker::TEvDecommissionRequest));
> При обработке в транзакции я не использую дополнительные данные, только `Record` и `Sender`.
Нет же: https://github.com/ydb-platform/ydb/blob/092d8cb74605cf57ce1903c31d7e578440cae7cd/ydb/core/mind/node_broker__decommission_node.cpp#L43-L45

2024-10-14 14:10 UTC, CyberROFL commented on ydb/core/mind/node_broker.h
> +        EvDecommissionResponse,
Да, поедут. Спасибо, что заметил. Нужно добавить оба этих сообщения в конец enum-а.

2024-10-14 14:11 UTC, CyberROFL commented on ydb/core/protos/counters_node_broker.proto
> +    TXTYPE_DECOMMISSION_NODE = 7            [(TxTypeOpts) = {Name: "TTxDecommissionNode"}];
Можно назвать как есть — Gracefull shutdown.

2024-10-16 09:39 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.h
> +
Лишний дифф.

2024-10-16 09:39 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +        ActorSystem->Send(new IEventHandle(nodeBrokerPipe, {}, new TEvNodeBroker::TEvGracefulShutdownRequest));
Сообщение заполнишь?

2024-10-16 09:39 UTC, CyberROFL commented on ydb/core/mind/node_broker.cpp
> +    .UpdateToNull<T::SlotIndex>();
Поправишь?

2024-10-16 09:39 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +#include <ydb/core/base/appdata.h>
Не используется.

2024-10-16 09:39 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +        TString addr = rec.GetAddress();
Для чего тут делается копия host и addr?

2024-10-17 12:13 UTC, pixcc commented
Нажми, пожалуйста, на "Re-request review", когда можно будет еще раз посмотреть

<img width="345" alt="image" src="https://github.com/user-attachments/assets/3f5999e0-0f83-4147-9ca0-5b259d34f708">

2024-10-17 12:30 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +        TAutoPtr<TEvent> event = new TEvent;
Ты ведь в тесте создаешь сообщение и заполняешь его поля. Здесь нужно сделать аналогично.

2024-10-17 12:30 UTC, CyberROFL commented on ydb/core/mind/node_broker_ut.cpp
> +    TAutoPtr<TEvNodeBroker::TEvGracefulShutdownRequest> eventGracefulShutdown = new TEvNodeBroker::TEvGracefulShutdownRequest;
В новом коде лучше не использовать `TAutoPtr`, замени на `THolder`/`std::unique_ptr`.

2024-10-17 12:30 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +        auto &addr = rec.GetAddress();
`const`, ты ведь их не меняешь.

2024-10-17 12:30 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +namespace NKikimr::NNodeBroker {
```suggestion
#include <ydb/core/protos/counters_node_broker.pb.h>

namespace NKikimr::NNodeBroker {
```

2024-10-17 13:12 UTC, stanislav-shchetinin commented on ydb/core/driver_lib/run/run.cpp
> +        TAutoPtr<TEvent> event = new TEvent;
Да, я понимаю, как это сделать, но в тесте я беру случайные host, port, address, а здесь мне нужно взять конкретные и я не понимаю откуда мне их брать

2024-10-17 13:54 UTC, CyberROFL commented on ydb/core/protos/node_broker.proto
> +  optional string Host = 1;
Кстати, я только сейчас понял, что тут достаточно NodeId — идентификатора, которая нода получает нода при регистрации.

2024-10-18 15:10 UTC, stanislav-shchetinin commented on ydb/core/driver_lib/run/run.cpp
> +        auto& nodeInfo = runConfig.AppConfig.GetDynamicNodeConfig().GetNodeInfo();
Сделал проверку, что нода динамическая

2024-10-30 16:35 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +            ActorSystem->Send(new IEventHandle(nodeBrokerPipe, {}, event.Release()));
Для посылки сообщений через пайп у нас используется `NTabletPipe::SendData`, у которого под капотом, кроме конструирования `IEventHandle`, еще вызывается `Rewrite`:
https://github.com/ydb-platform/ydb/blob/d73903d7a6b91b26fa4f27688657d3ea4ae236f5/ydb/core/tablet/tablet_pipe_client.cpp#L746

2024-10-30 16:35 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +        return Error(TStatus::ERROR,
Не вижу смысла в отдельном методе, достаточно здесь позвать:
```cpp
Response->Record.MutableStatus()->SetCode(TStatus::ERROR);
Response->Record.MutableStatus()->SetReason(TStringBuilder() << "Cannot find node " << nodeId);
```

2024-10-30 16:35 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +        const auto& it = Self->Nodes.find(nodeId);
```suggestion
        const auto it = Self->Nodes.find(nodeId);
```

2024-10-30 16:35 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +        Response->Record.MutableStatus()->SetCode(TStatus::OK);
Тут ошибка. Вне зависимости от того, чем завершилась стадия `Execute` (возможно, ошибкой), статус перетирается на `OK`. Заполнение `Response` нужно унести в `Execute`, а здесь оставить только отправку.

2024-10-30 16:35 UTC, CyberROFL commented on ydb/core/mind/node_broker__graceful_shutdown.cpp
> +                    "Graceful Shutdown request from " << nodeId << " ");
Наверно, можно смержить.

2024-11-01 13:47 UTC, CyberROFL approved these changes, later dismissed
lgtm

2024-11-02 20:25 UTC, pixcc commented
Есть проблема, критичность которой надо обсудить. При перезапуске ноды (просто обычный рестарт) в теории сообщение `TEvGracefulShutdown` и `TEvRegisterNode` могут пореордериться. Это приведет к тому, что нода освободит `SlotIndex`, используемый ей прямо сейчас, и следующая запущенная нода заберет этот `SlotIndex`. И будет две разных ноды с одинаковым `SlotIndex`.

Эту проблему можно было бы решить с помощью `Cookie`, некоторой дополнительной информации, отправляемой вместе с запросом на регистрацию ноды. Этот `Cookie` будет позволять отличать, что сообщение `TEvGracefulShutdown` приходит от старой реинкарнации ноды и его нужно проигнорировать.

FYI @CyberROFL

2024-11-02 20:25 UTC, pixcc requested changes

2024-11-28 15:35 UTC, pixcc requested changes

2024-11-28 15:35 UTC, pixcc commented on ydb/core/driver_lib/run/run.cpp
> +
extra whitespace

2024-11-28 15:35 UTC, pixcc commented on ydb/core/protos/feature_flags.proto
> +    optional bool EnableSeparateDiskSpaceQuotas = 153 [default = false];
что-то лишнее

2024-11-28 15:35 UTC, pixcc commented on ydb/core/mind/node_broker_impl.h
> +    void DbUpdateNodeAuthorizedByCertificate(const TNodeInfo &node,
что-то лишнее

2024-11-28 16:35 UTC, pixcc commented on ydb/core/mind/node_broker.cpp
> +void TNodeBroker::DbReleaseSlotIndex(const TNodeInfo &node,
Нужно еще `node.SlotIndex` из памяти почистить

2024-11-28 17:52 UTC, pixcc approved these changes

2024-11-29 08:53 UTC, CyberROFL approved these changes

2024-11-29 09:07 UTC, merged