[WIP][RFC] Parse and pass streamlookup parameters
ydb-platform/ydb pull request #10381
Opened 2024-10-14 09:07 UTC by yumkam

### Changelog entry 

...

### Changelog category 

* Improvement
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-18 16:10 UTC, yumkam commented
Changed type for DqJoin and GraceJoinCore Flags from TCoAtomList to TCoNameValueTupleList
(this will break canonized tests)

2024-10-21 11:32 UTC, rvu1024 requested changes
Все Child(0) можно заменить на Head()

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/dq/opt/dq_opt_join.cpp
> +            } else if ( flag.Name().Value().AfterPrefix("Right", tail)) {
style: `if (flag`

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +            auto&& flag = *flags.Child(i);
Зачемм тут &&?

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +            if ( !EnsureTupleOfAtoms(flag, ctx) || !EnsureTupleMinSize(flag, 1, ctx))
style: `if (!`

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +            auto&& name = *flag.Child(TCoNameValueTuple::idx_Name);
зачем тут &&?

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +            if (name.IsAtom({"LeftAny", "RightAny"})) {
style: лишний перенос

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +                    YQL_ENSURE(flag.Ref().ChildrenSize() == 1);
Все YQL_ENSURE должны быть проверками в типизаторе. Здесь их уже не должно быть.
И там же, в типизаторе нужно провверить, что в настроках лежат числа и они в пределах допустимых лимитов

2024-10-21 11:32 UTC, rvu1024 commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +                    Y_DEBUG_ABORT("Impossible flag"); // should have been checked by dq_type_ann
ctx.AddError + return {}

2024-10-22 11:10 UTC, yumkam commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +            auto&& name = *flag.Child(TCoNameValueTuple::idx_Name);
`auto` нельзя, `const auto&` нельзя, остаётся выбор между `auto&` и `auto&&`

2024-10-23 13:37 UTC, yumkam commented on ydb/library/yql/core/yql_join.cpp
> +                    if (child->ChildrenSize() % 2 == 0) {
До EquiJoin список as is передаётся внутри `('forceStreamLookup [...])` как список. При трансляции в DqJoin список разбивается на пары передаётся в Flags (которые переделан со списка Atom на список NameValueTuple.
В аннотаторе типов DqJoin проверяется имена флагов на допустимость.
При трансформации в DqJoin в CnStreamLookup проверяется, что слева нет Any и справа есть Any (в CnStreamLookup нет произвольных флагов).
В аннотаторе типов CnStreamLookup проверяется, что Join -- LEFT, и значения параметров -- целые числа.

2024-10-23 13:40 UTC, yumkam commented
(Resolution of trivial conflict, tests canonization and adding test for parameters is delayed till final iteration)

2024-11-15 16:21 UTC, rvu1024 commented on ydb/library/yql/dq/opt/dq_opt_join.cpp
> +                    .Done());
.InitFrom(flag)

2024-11-15 16:51 UTC, rvu1024 approved these changes, later dismissed

2024-11-18 09:00 UTC, maximyurchuk requested changes
YQL правится в Аркадии, в gh же просто зеркало, надо нести правки в Аркадию

2024-11-20 12:37 UTC, yumkam commented
> YQL правится в Аркадии, в gh же просто зеркало, надо нести правки в Аркадию

Тут взаимозависимые изменения и в yql/ и в ydb/

2024-12-12 17:02 UTC, closed without merging

2024-12-12 17:03 UTC, yumkam commented
gh часть будет решена в https://github.com/ydb-platform/ydb/pull/12548