Added counters for local db tables loading times
ydb-platform/ydb pull request #10402
Opened 2024-10-14 12:39 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.h
> +class TLoadTimeSignals: public TCommonCountersOwner {
time + fail + success в отдельный класс. использовать его. агрегаторы только аллоцируют нужные экземпляры

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/columnshard_schema.h
> +                LOG_S_CRIT("Load: index counters next failed");
убрать логи

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/engine_logs.h
> +    NMonitoring::TDynamicCounters::TCounterPtr PortionsLoadingTimeCounter;
в отдельный класс все

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    TInstant start = TInstant::Now();
обернуть guard-ами

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/db_wrapper.cpp
> +        LOG_S_CRIT("Load: index columns is not ready");
убрать логи

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/insert_table/insert_table.cpp
> +    TInstant start = TInstant::Now();
guard

2024-10-21 14:22 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/tables_manager.cpp
> +            LOG_S_CRIT("Load: tables rowset is not ready");
убрать логи

2024-10-21 14:37 UTC, ivanmorozov333 approved these changes

2024-10-21 14:37 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/columnshard_schema.h
>      static bool IndexCounters_Load(NIceDb::TNiceDb& db, const std::function<void(ui32 id, ui64 value)>& callback) {
лучше в таких методах отдавать TConclusionStatus с message = значение тега для сигнала

2024-10-21 14:38 UTC, ivanmorozov333 requested changes
1

2024-10-22 16:30 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    ui64 columnsLoadingDuration;
зачем ты их наружу вытащил?? ну хочешь залогировать - сделай это внутри гарда...

2024-10-23 06:30 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +    ui64 columnsLoadingDuration;
Я хочу в одной строке залогировать

2024-10-23 09:35 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.h
> +class TLoadTimer {
логично порождать его из LoadTimeSignals

2024-10-23 09:35 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +            PortionsLoadingTimeCounters.AddLoadingFail();
в этом случае guard запишет неверное время

2024-10-23 09:35 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/tables_manager.cpp
> +    , TableLoadTimeCounters(std::make_unique<TLoadTimeSignals>("Tables"))
не надо хранить напрямую в TablesManager. продумай где сигналы должны лежать. они же и в ColumnsEngineLogs должны быть тоже

2024-10-23 09:46 UTC, aavdonkin commented on ydb/core/tx/columnshard/tables_manager.cpp
> +    , TableLoadTimeCounters(std::make_unique<TLoadTimeSignals>("Tables"))
Так загрузка же идет непосредственно в TTablesManager, они в нем нужны

2024-10-23 09:51 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +            PortionsLoadingTimeCounters.AddLoadingFail();
Почему? Там дальше return, вызовется деструктор

2024-10-23 13:31 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.h
> +    bool Failed = false;
почему это не в Guard??

2024-10-23 13:52 UTC, aavdonkin commented on ydb/core/tx/columnshard/counters/common_data.h
> +    bool Failed = false;
Failed не в Guard? Из TLoadTimeSignals нет доступа к TLoadTimer
А нужен он здесь чтобы правильный счетчик выбрать

2024-10-23 14:31 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +        NColumnShard::TLoadTimer timer = PortionsLoadingTimeCounters.StartGuard("portions_loading_time");
убери эту строку. у тебя она же, или аналогичная использовалась при создании PortionsLoadingTimeCounters

2024-10-23 14:31 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.h
> +class TLoadTimeSignals: public TCommonCountersOwner {
внеси guard внутрь класса и закрой методы от прямого вызова

2024-10-23 14:34 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
почему в этот класс не внести counters?

2024-10-23 14:58 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +        NColumnShard::TLoadTimer timer = PortionsLoadingTimeCounters.StartGuard("portions_loading_time");
В смысле? Это разные таймеры в разных скобках

2024-10-23 15:01 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
Потому что он порождается после того, как происходит загрузка где он нужен

2024-10-23 15:07 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.cpp
> +        NColumnShard::TLoadTimer timer = PortionsLoadingTimeCounters.StartGuard("portions_loading_time");
строку, в смысле "" название сигнала

2024-10-23 15:09 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
не понимаю. он const, он в конструкторе уже создан.

2024-10-23 15:15 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.cpp
> +    Failed = true;
валидация на повторный вызов

2024-10-23 15:40 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/counters/common_data.h
> +    TLoadTimer StartGuard(const TString& name) const {
убери отсюда входящий параметр

2024-10-23 15:52 UTC, aavdonkin commented on ydb/core/tx/columnshard/counters/common_data.h
> +    TLoadTimer StartGuard(const TString& name) const {
В смысле, а как его передавать? В конструкторе TLoadTimeSignals?

2024-10-23 17:01 UTC, aavdonkin commented on ydb/core/tx/columnshard/tables_manager.cpp
> +                timer.AddLoadingFail();
TTableInfo::InitFromDB всегда возвращает true, так что та ветка никогда не выполняется

2024-10-23 18:50 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
Он мембер в TColumnEngineForLogs, а TColumnEngineForLogs порождается после того как происходит загрузка, и до загрузки породить его нельзя

2024-10-24 06:05 UTC, ivanmorozov333 commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
а NColumnShard::TLoadTimeSignals PortionsLoadingTimeCounters; можно?

2024-10-24 07:34 UTC, aavdonkin commented on ydb/core/tx/columnshard/engines/column_engine_logs.h
>      const NColumnShard::TEngineLogsCounters SignalCounters;
Не понял вопроса

2024-10-24 10:21 UTC, ivanmorozov333 approved these changes

2024-10-24 12:17 UTC, merged