Enable output channel spilling only if task has two or more outputs
ydb-platform/ydb pull request #1043
Opened 2024-01-16 13:50 UTC by Darych

2024-01-16 14:39 UTC, rvu1024 requested changes
Как будет реагировать сейчас код на ситуацию, когда spilling service выключен, а в запросе ставят прагму dq.SpillingEngine="file"?

2024-01-16 14:39 UTC, rvu1024 commented on ydb/library/yql/providers/dq/api/protos/dqs.proto
> -    bool EnableSpilling = 17; // false
Нельзя простj так удалять - это протобуф используется для вызовов api. Нужно переносить в reserved

2024-01-17 17:17 UTC, Darych commented
> Как будет реагировать сейчас код на ситуацию, когда spilling service выключен, а в запросе ставят прагму dq.SpillingEngine="file"?

Если в запросе реально начнет применяться спиллинг, то запрос зависнет, потому что данные никогда не запишутся, а следовательно не прочитаются.

2024-01-22 09:25 UTC, Darych commented
> Как будет реагировать сейчас код на ситуацию, когда spilling service выключен, а в запросе ставят прагму dq.SpillingEngine="file"?

Добавил флажок для отслеживания Undelivered. Spilling actor будет следить за undelivered и в случае недоставки ответит EvError.

2024-01-22 17:05 UTC, lll-phill-lll commented
А теперь получается, что включение спиллинга не всегда включает спиллинг?

2024-01-24 07:26 UTC, Darych commented
> А теперь получается, что включение спиллинга не всегда включает спиллинг?

Для YDB пока еще всегда. Для обратной совместимости с прошлой версией.
В  DQ уже спиллинг в каналах будет происходить только когда из стейджа выходит больше одного канала.

2024-01-24 15:25 UTC, rvu1024 submitted a review, later dismissed

2024-01-26 14:20 UTC, gridnevvvit approved these changes

2024-01-29 09:40 UTC, rvu1024 approved these changes

2024-01-29 10:01 UTC, merged