Add PDisk/VSlot whiteboard states
ydb-platform/ydb pull request #10491
Opened 2024-10-16 10:22 UTC by mregrock

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-28 14:10 UTC, alexvru requested changes
Some minor comments and also fix ut_kqp test in core/sys_view, please.

2024-10-28 14:10 UTC, alexvru commented on ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
> +            TActorId NodeWardenServiceId = MakeBlobStorageNodeWardenID(VCtx->NodeId);
lowercase for local variable; also do we really need that variable?

2024-10-28 14:10 UTC, alexvru commented on ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
> +                         0,
you're sure about 0? this will overwrite any valid value during merge; we possibly would want std::optional<> here and skip this field in ctor

2024-10-28 14:10 UTC, alexvru commented on ydb/core/mind/bscontroller/disk_metrics.cpp
> +        for (auto& [vslotId, v] : Self->StaticVSlots) {
it would be great to persist these metrics too (and handle VDiskMetrics table for static groups all the way along)

2024-10-28 14:10 UTC, alexvru commented on ydb/core/sys_view/common/schema.h
> +        struct State : Column<13, NScheme::NTypeIds::Utf8> {};
it's better not to reuse 13 -- there is a commented line down here showing this value was reserved

2024-10-31 15:19 UTC, adameat requested changes, later dismissed

2024-10-31 15:19 UTC, adameat commented on ydb/core/protos/whiteboard_disk_states.proto
> +enum EFlag {
this is not a "disk status". this is a common status, shared by many parts of our system. it shouldn't be in "disk_states.proto"

2024-11-06 11:21 UTC, alexvru requested changes
Again, correct ut_kqp tests in sys_view.

2024-11-06 11:21 UTC, alexvru commented on ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
> +            , ReplMonGroup(VCtx->VDiskCounters, "subsystem", "state")
"state" for two groups? what for?

2024-11-08 11:55 UTC, alexvru approved these changes

2024-11-08 12:25 UTC, merged