generic lookup: pad queries to improve query cachability
ydb-platform/ydb pull request #10506
Opened 2024-10-16 12:24 UTC by yumkam

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-06 16:12 UTC, yumkam commented
Pros:
Short term: on worst case scenario (input transform each time receives unique number of keys), it reduces first-round time from 1.7ms to 0.5ms per key.
Long term: reduces number of cached queries on ydb up 100x times (from 1k to 10).
Cons:
Enlarges each query by padding.
And most likely there won't be requests with every possible number of keys per request (1...1000), it will be some stable number plus-minus few, so practical saving on number cached queries will be much lower.

2024-12-23 16:02 UTC, dorooleg requested changes

2024-12-23 16:02 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            for (ui32 nRequests = Request->size(); !IsPowerOf2(nRequests) && nRequests < MaxKeysInRequest; ++nRequests) {
Может сделать отсечку чтобы на слишком больших значениях уже таким не заниматься? Допустим приходит к нам 2^20+1 элемент всегда, а мы его будем расширять до 2^21. Выглядит как уже большой overhead на таких значениях. Либо же имеет смысл ограничивать шаг начиная с какой-то позиции. Например до 512 степенью двойки идти, а потом уже с шагом 512

2024-12-23 18:57 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            for (ui32 nRequests = Request->size(); !IsPowerOf2(nRequests) && nRequests < MaxKeysInRequest; ++nRequests) {
MaxKeysPerRequest ограничен 1k. Если бы оно было бы больше, тут категорически НЕЛЬЗЯ было бы идти инкрементами, и пользоваться только степенями двойки: иначе тут получается O(n^2) вместо O(n)

2024-12-24 11:00 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/ut/yql_generic_lookup_actor_ut.cpp
> +                            .Operand()
Проверяет что какой запрос (protobuf) выдаёт generic lookup в коннектор. На самом деле, тут получается некоторая хрупкость: то, какими ключами будет добивать generic lookup зависит от порядка ключей в хеш-таблице (что, очевидно, не специфицированно).
Можно добавить ключей в тесте до степени двойки, тогда добивания не будет, зато не будет проверятся собственно процесс добивания (и я в этом уже ловил баг).

2024-12-25 12:08 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            for (ui32 nRequests = Request->size(); !IsPowerOf2(nRequests) && nRequests < MaxKeysInRequest; ++nRequests) {
Cама модель не правильная кмк. Асимптотическая нотация не подходит, так-как тут уже важны константы. Дальше на самом деле важно смотреть на K_i - число ключей в каждом запросе. K_i вполне себе ограничено. Нужно еще учитывать на сколько дороже компиляция станет и на сколько дорого добивать такими фековыми ключами запрос постоянно. Затем размер кеша компиляции не бесконечный и из него вымываются значения. Мое предположение что начиная с какого момента будут очень редкие выбросы и тогда не имеет смысла добавлять накладных расходов на добивание фейковыми значениями как 2x, а достаточно уже взять несколько бакетов по x + k * bucket_size

Сейчас понятно самая тривиальная идея используется, но думаю тут есть что улучшить. Нужно реальных данных насемплировать и по ним посмотреть. Это на уровнее идеи)

2024-12-25 12:18 UTC, dorooleg requested changes

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +        void AddClause(NConnector::NApi::TPredicate_TDisjunction &disjunction,
`NConnector::NApi::TPredicate_TDisjunction` -> `NConnector::NApi::TPredicate::TDisjunction`

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
давай в getter вместо auto явный std::function напишем какой должен быть с типам. Иначе по сигнатуре не понятно что такое getter

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +        void AddClause(NConnector::NApi::TPredicate_TDisjunction &disjunction,
В других местах ниже аналогично

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
зачем вообще getter тут понадоиблся, не достаточно просто k аргументом передать?

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
columns -> countColumns

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                eq.mutable_left_value()->Setcolumn(TString(KeyType->GetMemberName(c)));
Setcolumn -> set_column по аналогии с другими mutable_ ...

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                eq.mutable_left_value()->Setcolumn(TString(KeyType->GetMemberName(c)));
И в других местах

2024-12-25 12:18 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            *disjunction.mutable_operands()->Add()->mutable_conjunction() = conjunction;
сразу можно ссылку на него взять выше:
```
NConnector::NApi::TPredicate::TConjunction& conjunction = *disjunction.mutable_operands()->Add()->mutable_conjunction();
```

2024-12-25 15:15 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
`std::function` не эквивалентен lambda (аллокации), lambda как lambda можно передать только через auto (ну, или `template<class>`)

2024-12-25 15:17 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
Было намерение для добивания использовать `NULL` (но натолкнулось на проблемы и не взлетело)

2024-12-25 15:38 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
IIRC, должно быть либо `countOfColumns`, либо `columnsCount`. Предпочёл последнее.

2024-12-25 15:56 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
И зачем тут такое переусложнение? function заверент тебе lambda внутрь себя

2024-12-25 15:58 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
Ну тут кажется повод вообще от lambda избавиться

2024-12-25 16:08 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            for (ui32 nRequests = Request->size(); !IsPowerOf2(nRequests) && nRequests < MaxKeysInRequest; ++nRequests) {
Ещё есть альтернатива:
Вместо `(k1 = ? AND k2 = ?) OR (...)` использовать `(k1,k2,...) IN ?`, где в? биндится к list of tuples. Никакого добивания, однократная компиляция, и минимальный размер запроса.
Cons: требует не вполне тривиальной доработки в коннекторе, апдейта формата протобуфов (сейчас поддерживается только `(k1 IN ?)` (т.е. один ключ)), и будет работать только на ydb (впрочем, можно зафолбечить на тот же AND OR, только внутри коннектора).

2024-12-25 16:15 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
Менее эффективно

2024-12-25 16:19 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
(не работает для не-nullable/Optional типов)

2024-12-26 19:23 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +            for (ui32 nRequests = Request->size(); !IsPowerOf2(nRequests) && nRequests < MaxKeysInRequest; ++nRequests) {
О, это вообще отличная мысль на самом деле

2024-12-28 07:32 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
Не до конца понял почему не работает. Такая запись же эквивалентна будет только без getter https://paste.yandex-team.ru/a40ec64b-697d-4326-82fb-700aca6f2eaf

2025-01-22 12:53 UTC, yumkam commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
Не вполне работает идея по передаче NULL вместо значений (для не-Optional нельзя передать в качестве значения NULL). Если идею с NULL совсем дропнуть, то можно и выкинуть лямбды.

2025-01-23 23:46 UTC, dorooleg approved these changes

2025-01-23 23:48 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                       ui32 columns, auto&& getter) {
lambda это же вызов функции если компилятор не заоптимизит. Почему это будет менее эффективнее?

2025-01-23 23:48 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
> +                AddClause(disjunction, KeyType->GetMembersCount(), [&k = k](auto c) {
А lambda здесь как с этим помогает?

2025-01-29 08:20 UTC, merged