More SQL features for Variant type
ydb-platform/ydb pull request #10577
Opened 2024-10-17 18:57 UTC by avevad

### Changelog entry 

More SQL features for Variant type

### Changelog category 

* New feature

### Additional information

...

2024-10-18 09:46 UTC, vitstn commented on ydb/library/yql/sql/v1/builtin.cpp
> +            {"variantitem", BuildNamedArgcBuiltinFactoryCallback<TCallNodeImpl>("VariantItem", 1, 1) },
Для VariantItem нужна предварительная обертка, которая реализует AutoMap и обрабатывает Null/Optional

типа SqlVariantItem

2024-10-18 09:47 UTC, vitstn commented on ydb/library/yql/sql/v1/builtin.cpp
> +            return new TCallNodeImpl(pos, "Visit", 1, -1, resultArgs);
тоже самое

2024-10-18 09:47 UTC, vitstn commented on ydb/library/yql/sql/v1/builtin.cpp
> +            if (mustUseNamed && *mustUseNamed) {
я не вижу случая сообщения об ошибке когда часть обработчиков именованные, а часть нет

2024-10-18 09:48 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +        if (IsNull(input->Head())) {
это лучше вынести в Sql версии, т.к. в этих функциях вход должен быть строгий Variant

2024-10-18 09:48 UTC, vitstn requested changes
!

2024-10-18 09:56 UTC, rvu1024 reviewed
Нужны тесты и документация (отдельным pr)

2024-11-06 09:30 UTC, avevad commented on ydb/library/yql/sql/v1/builtin.cpp
> +            return new TCallNodeImpl(pos, "Visit", 1, -1, resultArgs);
тут тоже

2024-11-06 09:30 UTC, avevad commented on ydb/library/yql/sql/v1/builtin.cpp
> +            if (mustUseNamed && *mustUseNamed) {
добавил проверку

2024-11-06 09:31 UTC, avevad commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +        if (IsNull(input->Head())) {
здесь вынес проверки в т.ч. которые уже были

2024-11-19 13:46 UTC, closed without merging