Block input for YT map operations
ydb-platform/ydb pull request #10587
Opened 2024-10-18 07:46 UTC by loochek

### Changelog entry 

Support of block input in map operations jobs (using Arrow input format provided by YT)

### Changelog category 

* Performance improvement

### Additional information
Can be enabled with `yt.JobBlockInput` pragma

2024-10-18 13:35 UTC, vitstn commented on ydb/library/yql/core/yql_opt_utils.cpp
> +bool CheckSupportedTypes(const TTypeAnnotationNode::TListType& typesToCheck, const TSet<TString>& supportedTypes, const TSet<NUdf::EDataSlot>& supportedDataTypes, std::function<void(const TString&)>
supported с точки зрения чего?

раз тип есть, он явно существует

2024-10-18 13:39 UTC, vitstn commented on ydb/library/yql/providers/common/codec/arrow/yql_codec_buf_input_stream.cpp
> +    auto outBuffer = ARROW_RESULT(arrow::AllocateBuffer(nbytes, Pool_));
см https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/public/udf/arrow/util.h#L105

не стоит сразу заливать нулями

2024-10-18 13:41 UTC, vitstn commented on ydb/library/yql/providers/common/codec/arrow/yql_codec_buf_input_stream.cpp
> +        return arrow::AllocateBuffer(0);
это контракт? почему например нельзя вернуть success result + nullptr?

2024-10-18 13:44 UTC, vitstn commented on ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_fuse.cpp
> +    if (auto blockInputSetting = NYql::GetSetting(outerMap.Settings().Ref(), EYtSettingType::BlockInput); blockInputSetting && blockInputSetting->ChildrenSize() == 2) {
непонятно зачем blockInputSetting->ChildrenSize() == 2

2024-10-18 13:49 UTC, vitstn commented on ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
> +protected:
почему не private?

2024-10-18 13:49 UTC, vitstn commented on ydb/library/yql/providers/common/codec/arrow/yql_codec_buf_input_stream.h
> +protected:
почему не private?

2024-10-18 13:51 UTC, vitstn commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +            blockInput = setting->ChildrenSize() == 2;
непонятно. если есть опция BlockInput, зачем еще что-то проверять в ноде?

2024-10-18 13:56 UTC, vitstn commented on ydb/library/yql/providers/yt/provider/yql_yt_block_input_filter.cpp
> +            if (meta->InferredScheme) {
кажется те же самые проверки атрибутов/схемы есть в области проверки чтения через dq снаружи
выглядит так что надо это вынести в функцию типа CanReadArrow(table), оно не связано только с block input в джобах

проверки типов могут быть разными (JobBlockInputSupportedTypes)

2024-10-18 13:57 UTC, vitstn commented on ydb/library/yql/tests/sql/suites/blocks/block_input_various_types.txt.attr
> +    "_yql_row_spec" = {
а зачем тут смесь sсhema и yql_row_spec? если есть sсhema, то row_spec не нужен

2024-10-18 13:58 UTC, vitstn commented on ydb/library/yql/tests/sql/suites/blocks/block_input_various_types.txt.attr
> +    "_yql_row_spec" = {
видимо это не typev3 с точки зрения YT

2024-10-18 13:59 UTC, vitstn commented on ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
> +            "uri": "https://{canondata_backend}/1784826/3996db18cd1613bfd08b5a66b2c91ca2981cd7d6/resource.tar.gz#test.test_blocks-date_equals--Peephole_/opt.yql"
что именно тут изменилось?

2024-10-18 14:00 UTC, vitstn requested changes
!

2024-10-21 11:38 UTC, loochek commented on ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_fuse.cpp
> +    if (auto blockInputSetting = NYql::GetSetting(outerMap.Settings().Ref(), EYtSettingType::BlockInput); blockInputSetting && blockInputSetting->ChildrenSize() == 2) {
Применять оптимизатор нельзя только если уже переписали YtMap в блочность, т.е. когда у blockInput есть аргумент. BlockInput без аргумента не препятствует оптимизациям и просто игнорируется/выкидывается.

Сделали так намеренно, чтобы оптимизации были приоритетнее блочности - все равно после оптимизаций запустится BlockInputFilter и пометит все заново.

Вообще это один из костылей для работы peephole в yqlrun - в реальном флоу такая ситуация произойти не может, поскольку переписывание в блочность запускается в exec трансформере в последнюю очередь

2024-10-21 11:47 UTC, loochek commented on ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
> +            "uri": "https://{canondata_backend}/1784826/3996db18cd1613bfd08b5a66b2c91ca2981cd7d6/resource.tar.gz#test.test_blocks-date_equals--Peephole_/opt.yql"
Изменений нет, поправил канонизацию

2024-10-21 12:02 UTC, loochek commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +            blockInput = setting->ChildrenSize() == 2;
Флаг работает так - сначала BlockInputFilter проверяет условия и проставляет флаги без аргумента на те YtMap, которые можно переписать в блочность. Затем на эти флаги смотрит BlockInput, который переписывает лямбды и добавляет аргумент. 

Соответственно, сам по себе флаг blockInput не означает, что YtMap переписан в блочный.

Разбили оптимизатор на две стадии, потому что по-другому не получалось добиться правильной работы в тестах Peephole

2024-10-22 14:30 UTC, vitstn commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +            blockInput = setting->ChildrenSize() == 2;
setting->ChildrenSize() == 2 размазанный по всему коду это нехорошо
 
как вариант может менять имя опции, если в одном случае данные есть, а в другом нет

2024-10-23 12:48 UTC, loochek commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +            blockInput = setting->ChildrenSize() == 2;
Сделал две разные опции

2024-10-23 16:23 UTC, vitstn approved these changes, later dismissed

2024-10-24 12:22 UTC, vitstn approved these changes

2024-10-24 12:22 UTC, merged