[log_backend] write tenant & cluster for UnifiedAgent log backend
ydb-platform/ydb pull request #10666
Opened 2024-10-21 12:29 UTC by shmel1k

### Changelog entry 

Added database & node_id for logging backend

### Changelog category 

* New feature
* Improvement

### Additional information

...

2024-10-21 17:28 UTC, Enjection requested changes

2024-10-21 17:54 UTC, shmel1k commented on ydb/core/driver_lib/run/run.cpp
> +    LogSettings->TenantName = runConfig.TenantName ? runConfig.TenantName : "";
fixed, missprint

2024-10-22 12:41 UTC, ijon approved these changes

2024-10-22 15:55 UTC, Enjection approved these changes

2024-10-22 16:41 UTC, merged