Mute ydb/core/blobstorage/ 4 tests
ydb-platform/ydb pull request #10687
Opened 2024-10-21 19:42 UTC by naspirato

### Changelog entry 
Mute:
ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.block42
ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.mirror3dc
ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.mirror3of4

 Owner: [TEAM:@ydb-platform/storage](https://github.com/orgs/ydb-platform/teams/storage)

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**

**Summary history:** in window 2024-10-21 
 Success rate **0%**
Pass:0 Fail:12 Mute:0 Skip:0

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=__in_ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.block42&full_name=__in_ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.mirror3dc&full_name=__in_ydb/core/blobstorage/ut_blobstorage/ut_osiris/Osiris.mirror3of4)

Mute 
ydb/core/blobstorage/ut_mirror3of4/Mirror3of4.ReplicationSmall

 Owner: [TEAM:@ydb-platform/storage](https://github.com/orgs/ydb-platform/teams/storage)

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**  

**Summary history:** in window 2024-10-20 - 2024-10-21 
 Success rate **86.36363636363636%**
Pass:19 Fail:3 Mute:0 Skip:0
### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-21 19:55 UTC, maximyurchuk approved these changes

2024-10-21 20:15 UTC, maximyurchuk approved these changes

2024-10-22 07:27 UTC, alexvru requested changes
Don't think this solves any problem.

2024-10-22 07:46 UTC, alexvru requested changes
Local runs of Osiris.* tests show 100% success rate.

2024-10-22 11:00 UTC, alexvru approved these changes

2024-10-22 11:00 UTC, merged