update hive ui reference
ydb-platform/ydb pull request #10749
Opened 2024-10-23 07:47 UTC by vporyadke

### Changelog entry 

update hive ui reference

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-10-23 07:59 UTC, vporyadke commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Triggers** - значения показателей, которые используются для принятия решения об автобалансировке. Каждый сопровождается цветовым индикатором: зелёный означает, что значение находится на приемлемо
тут надо будет иметь ссылку на описание из другого пр https://github.com/ydb-platform/ydb/pull/7413

2024-10-28 02:50 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Triggers** - значения показателей, которые используются для принятия решения об автобалансировке. Каждый сопровождается цветовым индикатором: зелёный означает, что значение находится на приемлемо
ставлю пока в драфт, т.к. зависит от этого другого PR в статусе драфт

2025-02-21 01:46 UTC, blinkov requested changes

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +Попасть на страницу Web-viewer Hive можно из вкладки Tablets в {{ ydb-short-name }} Monitoring.
```suggestion
Попасть на страницу Web-viewer Hive можно из вкладки Tablets в {{ ydb-short-name }} Embedded UI.
```

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* Статистика о числе запусков автобалансировки. Обнуляется при рестарте Hive.
```suggestion
* **Info**:
    * **Tenant** — тенант, за который отвечает Hive.
    * **Nodes** — количество узлов, подключённых к Hive.
    * **Tablets** — процентное и количественное соотношение поднятых таблеток к имеющимся.
    * **Boot Queue** — количество таблеток, которые находятся в очереди на запуск.
    * **Wait Queue** — количество таблеток, которые не имеют возможности подняться.
* **Totals** — суммарное потребление ресурсов таблетками (cnt, cpu, mem, net).
* **Variance** — среднеквадратическое отклонение потребления ресурсов (cnt, cpu, mem, net) между узлами.
* **Triggers** — значения показателей, которые используются для принятия решения об [автобалансировке](../../contributor/hive.md#autobalancing). Каждый сопровождается цветовым индикатором: зелёный означает, что значение находится на приемлемом уровне; жёлтый — что близко к порогу; красный — что значение превысило порог и сейчас должна быть запущена автобалансировка.
    * **Counter**, **CPU**, **Memory**, **Network** — дисбаланс в потреблении соответствующего ресурса между узлами.
    * **MaxUsage** — максимальное потребление ресурса на одном узле.
    * **Imbalance** — дисбаланс в распределении по узлам таблеток одного объекта. Применяется только для таблеток без метрик.
* Статистика о числе запусков автобалансировки. Обнуляется при рестарте Hive.
```

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +Попасть на страницу Web-viewer Hive можно из вкладки Tablets в {{ ydb-short-name }} Monitoring.
Чтобы этим всем пользоваться явно нужны какие-то права на кластере — написать какие, сослаться на то как их получить/выдать.

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Types** - распределение таблеток по их типу. С помощью нажатия на конкретный тип можно запретить запускать таблетки данного типа на конкретном узле. Нажатием на тип в верху таблицы можно установи
```suggestion
* **Types** — распределение таблеток по их типу. С помощью нажатия на конкретный тип можно запретить запускать таблетки данного типа на конкретном узле. Нажатием на тип вверху таблицы можно установить такой запрет на все узлы по умолчанию.
```
в остальных пунктах лучше тоже сделать тире вместо минуса + сделать консистентно в плане точки или точки с запятой в конце пункта

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Latest tablet moves** - последние 5 перемещённых таблеток.
```suggestion
## Balancer

При нажатии на кнопку **Balancer** появится окно со следующими элементами:

* **Run Balancer** - ручной запуск балансировки таблеток по узлам с заданным ограничением на число перемещений таблеток.
* **Rebalance ALL tablets FROM SCRATCH** - перезапуск сразу всех таблеток базы. Позволяет быстро получить равномерное распределение таблеток ценой кратковременной недоступности базы. Не рекомендуется к использованию в production-окружении.
* **Latest tablet moves** - последние 5 перемещённых таблеток.
```

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигур
```suggestion
## Settings

На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигурации {{ ydb-short-name }}](../../maintenance/manual/config-overview.md) и значение по умолчанию. Параметры, значения которых выставлены через интерфейс, выделены жирным. Выставленные через интерфейс значения имеют приоритет над значениями из конфигурации {{ ydb-short-name }}.
```

2025-02-21 01:46 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +Также на этой странице можно управлять тем, какие метрики учитыаются для каких типов таблеток.
```suggestion
Параметр | Формат | Описание
--- | --- | ---
MaxTabletsScheduled | Целое число | Максимальное число таблеток, одновременно находящихся в процессе старта на одном узле.
MaxBootBatchSize | Целое число | Максимальное число таблеток из очереди на запуск, обрабатываемых за раз.
DrainInflight | Целое число | Число таблеток, одновременно перезапускающихся в процессе Drain одного узла.
MinScatterToBalance | Вещественное число | Порог метрики Scatter для ресурсов CPU, Memory, Network. Имеет приоритет ниже, чем параметры ниже.
MinCPUScatterToBalance | Вещественное число | Порог метрики Scatter для ресурса CPU.
MinMemoryScatterToBalance | Вещественное число | Порог метрики Scatter для ресурса Memory.
MinNetworkScatterToBalance | Вещественное число | Порог метрики Scatter для ресурса Network.
MinCounterScatterToBalance | Вещественное число | Порог метрики Scatter для ресурса Counter.
MinNodeUsageToBalance | Вещественное число | Потребление ресурсов на узле ниже данного значения приравнивается к данному значению.
MaxNodeUsageToKick | Вещественное число | Порог потребления ресурсов на узле для запуска emergency-автобалансировки.
NodeUsageRangeToKick | Вещественное число | Автобалансировка считается нецелесообразной, если разница в уровне потребления ресурсов между узлами меньше этого значения.
ResourceChangeReactionPeriod | Целое число секунд | Частота обновления агрегированной статистики потребления ресурсов.
TabletKickCooldownPeriod | Целое число секунд | Минимальный период времени между перемещениями одной таблетки.
NodeSelectStrategy | Выбор из списка | Стратегия выбора узла для запуска таблетки. Возможные варианты: взвешенно-случайный выбор на основе потребления, выбор узла с минимальным потреблением, выбор случайного узла среди 7% узлов с наименьшим потреблением, выбор случайного узла.
SpreadNeighbours | вкл/выкл | Учитывать ли то, к какому объекту относятся таблетки, чтобы по возможности запускать таблетки одного объекта на разных узлах.
MaxResourceCPU | Целое число наносекунд | Максимальное потребление CPU на узле в секунду. Значение по умолчанию, используется только если узел не предоставляет значение при регистрации в Hive.
MaxResourceMemory | Целое число байт | Максимальное потребление памяти на узле. Значение по умолчанию, используется только если узел не предоставляет значение при регистрации в Hive.
MaxResourceNetwork | Целое число байт/секунду | Максимальное потребление полосы на узле. Значение по умолчанию, используется только если узел не предоставляет значение при регистрации в Hive.
MaxResourceCounter | Целое число наносекунд | Максимальное потребление виртуального ресурса Counter на узле.
DefaultUnitIOPS | Целое число | Значение по умолчанию для IOPS одного канала.
DefaultUnitThroughput | Целое число байт/секунду | Значение по умолчанию для потребления пропускной способности одним каналом.
DefaultUnitSize | Целое число байт | Значение по умолчанию для потребления места на дисках одним каналом.
StorageBalanceStrategy | Выбор из списка | Какой из параметров выше (IOPS, THROUGHPUT, SIZE) используется для распределения каналов таблеток по группам хранения. Вариант AUTO — использование того, чьё потребление максимально.
StorageSafeMode | вкл/выкл | Проверяется ли превышение максимального потребления ресурсов групп хранения.
StorageSelectStrategy | Выбор из списка | Стратегия выбора группы хранения для канала таблетки. Аналогично NodeSelectStrategy, с дополнительным вариантом [Round-robin](https://ru.wikipedia.org/wiki/Round-robin_(%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC)).
MinPeriodBetweenReassign | Целое число секунд | Минимальный период времени между переназначениями групп хранения для каналов одной таблетки.
MetricsWindowSize | Целое число миллисекунд | Размер окна, на котором агрегируются метрики потребления ресурсов таблетками.
ResourceOvercommitment | Вещественное число | Коэффициент переподписки на ресурсы узлов.
NodeBalanceStrategy | Выбор из списка | Стратегия выбора узла, с которого перевозятся таблетки при автобалансировке. Аналогично NodeSelectStrategy.
TabletBalanceStrategy | Выбор из списка | Стратегия выбора таблетки для перевоза при автобалансировке. Аналогично NodeSelectStrategy.
MinPeriodBetweenBalance | Вещественное число секунд | Минимальный период времени между двумя итерациями автобалансировки, не относится к emergency-балансировке.
BalancerInflight | Целое число | Число таблеток, одновременно перезапускающихся в процессе автобалансировки, не относится к emergency-балансировке.
MaxMovementsOnAutoBalancer | Целое число | Число перемещений таблеток за одну итерацию автобалансировки, не относится к emergency-балансировке.
ContinueAutoBalancer | вкл/выкл | При включении следующая итерация балансировки запускается, не дожидаясь, когда пройдёт ResourceChangeReactionPeriod.
MinPeriodBetweenEmergencyBalance | Вещественное число секунд | Аналогично MinPeriodBetweenBalance, но для emergency-балансировки.
EmergencyBalancerInflight | Целое число | Аналогично BalancerInflight, но для emergency-балансировки.
MaxMovementsOnEmergencyBalancer | Целое число | Аналогично MaxMovementsOnAutoBalancer, но для emergency-балансировки.
ContinueEmergencyBalancer | вкл/выкл | Аналогично ContinueAutoBalancer, но для emergency-балансировки.
CheckMoveExpediency | вкл/выкл | Производится ли проверка целесообразности перемещений таблеток.
SpaceUsagePenaltyThreshold | Вещественное число | При перевозе канала из-за кончающегося места в группе пессимизировать группы, в которых свободное место отличается во столько или менее раз от исходной группы.
SpaceUsagePenalty | Вещественное число | Коэффициент штрафа, описанного выше.
WarmUpBootWaitingPeriod | Целое число миллисекунд | Время ожидания старта всех известных узлов при старте базы.
MaxWarmUpPeriod | Целое число секунд | Максимальное время ожидания старта узлов при старте базы.
WarmUpEnabled | вкл/выкл | Дожидаться ли старта всех узлов при старте базы или запускать таблетки на первом подключившемся.
ObjectImbalanceToBalance | Вещественное число | Порог метрики дисбаланса таблеток одного объекта.
ChannelBalanceStrategy | Выбор из списка | Стратегия выбора канала для переназначения при балансировке каналов. Аналогично NodeSelectStrategy.
MaxChannelHistorySize | Целое число | Балансировка каналов не должна приводить к тому, чтобы размер истории канала превышал это значение.
StorageInfoRefreshFrequency | Целое число миллисекунд | Частота обновления информации о пулах хранения.
MinStorageScatterToBalance | Вещественное число | Порог метрики Scatter для групп хранения.
MinGroupUsageToBalance | Вещественное число | Потребление ресурсов группы хранения ниже данного значения приравнивается к данному значению.
StorageBalancerInflight | Целое число | Число таблеток, одновременно перезапускающихся во время балансировки каналов.
LessSystemTabletsMoves | вкл/выкл | Минимизация перемещения системных таблеток при автобалансировке.
BalancerIgnoreTabletTypes | Список типов таблеток, разделённый точкой с запятой | Типы таблеток, на которые не распространяется автобалансировка.

Также на этой странице можно управлять тем, какие метрики учитываются для каких типов таблеток.
```

2025-03-06 03:47 UTC, blinkov submitted a review, later dismissed

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +Попасть на страницу Web-viewer Hive можно по ссылке Developer UI из вкладки Tablets в {{ ydb-short-name }} UI. Для доступа к странице необходимо входить в список `monitoring_allowed_sids` в [конфигур
```suggestion
Web-viewer Hive предоставляет визуальный интерфейс работы с [Hive](../../concepts/glossary.md#hive).

Попасть на страницу Web-viewer Hive можно по ссылке Developer UI из вкладки Tablets в [Embedded UI](index.md). Для доступа к странице необходимо быть аутентифицированным как пользователь, входящий в список `monitoring_allowed_sids` в [конфигурации безопасности кластера](../configuration/index.md#security).
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Tenant** — тенант, за который отвечает Hive.
внести тенант в глоссарий https://ydb.tech/docs/ru/concepts/glossary и отсюда сослаться туда

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
>  Главная страница представляет информацию о распределении и потреблении ресурсов таблетками на каждой из нод представленной в виде таблицы.
`s/нод/узлов/g`

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Tenant** — тенант, за который отвечает Hive.
у нас вроде до сих пор существует понятие корневого Hive — что тут для него пишут?

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
>  Главная страница представляет информацию о распределении и потреблении ресурсов таблетками на каждой из нод представленной в виде таблицы.
в первом упоминании таблеток сослаться на глоссарий

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Nodes** — количество узлов, подключённых к Hive.
тут имеются ввиду только узлы базы данных или все узлы? уточнить и сослаться на https://ydb.tech/docs/ru/concepts/glossary#database-node или https://ydb.tech/docs/ru/concepts/glossary#node

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Tablets** — процентное и количественное соотношение поднятых таблеток к имеющимся.
чем отличаются поднятые и имеющиеся таблетки? поднятые = которые прямо сейчас работают на каком-то из узлов? имеющиеся = которые должны существовать, но возможно переезжают, не успели переподняться после падения узла и т.п.?

надо тут перефразировать чтобы ответы на такие вопросы были по тексту очевидны, вероятно методом явного перечисления возможных состояний таблетки и отсылкой к ним

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Wait Queue** — количество таблеток, которые не имеют возможности подняться.
хорошо б где-то завести список возможных причин такой невозможности и сослаться на него

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Totals** — суммарное потребление ресурсов таблетками (cnt, cpu, mem, net).
я какое-то время назад ревьюил подробную статью про эти ресурсы — сослаться на неё

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Variance** — среднеквадратическое отклонение потребления ресурсов (cnt, cpu, mem, net) между узлами.
```suggestion
* **Variance** — [среднеквадратическое отклонение](https://ru.wikipedia.org/wiki/Среднеквадратическое_отклонение) потребления ресурсов (cnt, cpu, mem, net) между узлами.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Triggers** — значения показателей, которые используются для принятия решения об [автобалансировке](../../contributor/hive.md#autobalancing). Каждый сопровождается цветовым индикатором: зелёный оз
```suggestion
* **Triggers** — значения показателей, которые используются для принятия решения об [автобалансировке](../../contributor/hive.md#autobalancing). Каждый сопровождается цветовым индикатором: зелёный означает, что значение находится на приемлемом уровне; жёлтый — что оно близко к порогу; красный — что значение превысило порог, и сейчас должна быть запущена автобалансировка.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +    * **Counter**, **CPU**, **Memory**, **Network** — дисбаланс в потреблении соответствующего ресурса между узлами.
не понятно что именно тут имеется ввиду без дисбалансом

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* Статистика о числе запусков автобалансировки. Обнуляется при рестарте Hive.
стоит досыпать пару слов о том, как понять когда был последний рестарт hive

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Types** — распределение таблеток по их типу. С помощью нажатия на конкретный тип можно запретить запускать таблетки данного типа на конкретном узле. Нажатием на тип в заголовке таблицы можно уста
```suggestion
* **Types** — распределение таблеток по их типу. С помощью нажатия на конкретный тип можно запретить запуск таблеток данного типа на конкретном узле. Нажатием на тип в заголовке таблицы можно установить такой запрет на все узлы по умолчанию.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Types** — распределение таблеток по их типу. С помощью нажатия на конкретный тип можно запретить запускать таблетки данного типа на конкретном узле. Нажатием на тип в заголовке таблицы можно уста
явно проговорить:

- распространяется ли запрет только на запуск новых таблеток или существующие тоже пытается расселить
- что происходит при запрете на всех узлах — таблетки такого типа совсем перестают запускаться?
- в любом случае такой запрет звучит как потенциально опасная операция — ярко предупредить об этом через `{% note warning %}`
- как такой запрет снять 
- куда смотреть чтоб видеть есть ли сейчас запрет
- если есть альтернативные способы делать то же самое, например через cli — упомянуть/сослаться о них

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Usage** — отнормированный доминантный ресурс.
при ревью статьи про автобалансировку вроде как выяснилось, что нет у нас доминантных ресурсов?

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +  * **cnt** — количество таблеток без потребления ресурсов.
что такое «таблетка без потребления ресурсов»?

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Active** — включение/отключение узла для перевоза таблеток на данный узел.
Это эквивалентно запрету на запуск таблеток всех типов (про который на 36 строке говорится)? Если да, то лучше явно это подсветить.

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Freeze** — запрет для таблеток подниматься на других узлах.
Каких таблеток? Видимо всех, которые сейчас на текущем узле работают? Явно проговорить.

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Drain** — плавный перевоз всех таблеток с узла.
Конкретнее описать на что влияет «плавность»

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Heavy tablets** — список таблеток, потребляющих значительное количество ресурсов.
для них вероятно есть какой-то порог — явно проговорить каков он

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Nodes** —  список узлов.
```suggestion
* **Nodes** — список узлов.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Groups** — список групп хранения для каждой таблетки.
на глоссарий сослаться про пулы и группы хранения

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Reassign Groups** — страница перераспределения групп хранения между таблетками.
ниже видимо есть разделы с более подробными описаниями этих страниц — досыпать ссылки на них, примерно так:
```suggestion
* [**Reassign Groups**](#reassign_groups) — страница перераспределения групп хранения между таблетками.
```
заодно будет понятно каких не хватает

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Channels** — диапазон каналов, для которых будет производиться балансировка.
ссылку на https://ydb.tech/docs/ru/concepts/glossary#channel

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Inflight** — количество одновременно переезжающих на другие группы таблеток.
```suggestion
* **Storage pool** — пул групп хранения для балансировки.
* **Storage group** — если предыдущий пункт не указан, можно указать отдельно только одну группу.
* **Type** — тип таблеток, для которых будет производиться балансировка.
* **Channels** — диапазон каналов, для которых будет производиться балансировка.
* **Percent** — процент от общего количества каналов таблеток, которые переедут в результате балансировки.
* **Inflight** — количество таблеток, одновременно переезжающих на другие группы.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигур
```suggestion
## Balancer

При нажатии на кнопку **Balancer** появится окно со следующими элементами:

* **Run Balancer** — ручной запуск балансировки таблеток по узлам с заданным ограничением на число перемещений таблеток.
* **Rebalance ALL tablets FROM SCRATCH** — перезапуск сразу всех таблеток базы. Позволяет быстро получить равномерное распределение таблеток ценой кратковременной недоступности базы. *Не рекомендуется к использованию в production-окружении.*
* **Latest tablet moves** — последние 5 перемещённых таблеток.

## Settings

На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигурации {{ ydb-short-name }}](../../maintenance/manual/config-overview.md) и значение по умолчанию. Параметры, значения которых выставлены через интерфейс, выделены полужирным шрифтом. Выставленные через интерфейс значения имеют приоритет над значениями из конфигурации {{ ydb-short-name }}. Внесении изменений в настройки через интерфейс не изменяет значения в конфигурации.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +- `RANDOM` — выбор случайного узла.
```suggestion
|| NodeSelectStrategy | Выбор из списка | Стратегия выбора узла для запуска таблетки. Возможные варианты:

- `WEIGHTED_RANDOM` — взвешенно-случайный выбор на основе потребления; 
- `EXACT_MIN` — выбор узла с минимальным потреблением;
- `RANDOM_MIN_7P` — выбор случайного узла среди 7% узлов с наименьшим потреблением;
- `RANDOM` — выбор случайного узла.
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +|| Параметр | Формат | Описание ||
Этой таблице место скорее в справке конфигурации https://github.com/ydb-platform/ydb/tree/main/ydb/docs/ru/core/reference/configuration (там legacy контент сейчас свален в index.md, а новый пишется в отдельных файлах одноимённых top-level секциям), а не по интерфейсу. А отсюда на справку по конфигурации ссылку просто дать + объяснить маппинг параметров из конфигурации на параметры из таблицы, вероятно тут просто snake_case из конфигурации конвертируется в CamelCase.

Также в самой таблице очень не хватает ещё колонки со значениями по умолчанию.

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +- `ROUND_ROBIN` - выбор группы внтури пула хранения по принципу [Round-robin](https://ru.wikipedia.org/wiki/Round-robin_(%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC)).
```suggestion
|| StorageSelectStrategy | Выбор из списка | Стратегия выбора группы хранения для канала таблетки. Возможные варианты:

- `WEIGHTED_RANDOM` — взвешенно-случайный выбор на основе потребления;
- `EXACT_MIN` — выбор группы с минимальным потреблением;
- `RANDOM_MIN_7P` — выбор случайной группы среди 7% групп с наименьшим потреблением;
- `RANDOM` — выбор случайной группы;
- `ROUND_ROBIN` - выбор группы внтури пула хранения по принципу [Round-robin](https://ru.wikipedia.org/wiki/Round-robin_(%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC)).
```

2025-03-06 03:47 UTC, blinkov commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +Также на этой странице можно управлять тем, какие метрики учитываются для каких типов таблеток.
как?

2025-03-12 09:50 UTC, vporyadke commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +* **Active** — включение/отключение узла для перевоза таблеток на данный узел.
Не вполне эквивалентно, потому что если например в базе ещё ни разу не создавали кезусов (или какой другой тип таблетки), то запрет по типам на него навесить нельзя, а запрет всего запретит и все будущие типы тоже.

2025-03-12 14:36 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| storage_balance_strategy | Перечисление | Выбор параметра используемого для распределения каналов таблеток по группам хранения. Вариант AUTO — использование того, чьё потребление максимально.Возмо
```suggestion
|| storage_balance_strategy | Перечисление | Выбор параметра используемого для распределения каналов таблеток по группам хранения. Вариант AUTO — использование того, чьё потребление максимально. Возможные варианты:

- `HIVE_STORAGE_BALANCE_STRATEGY_AUTO`;
- `HIVE_STORAGE_BALANCE_STRATEGY_IOPS`;
- `HIVE_STORAGE_BALANCE_STRATEGY_IOPS`;
- `HIVE_STORAGE_BALANCE_STRATEGY_SIZE`. ||
```

2025-03-12 14:36 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| continue_auto_balancer | вкл/выкл | При включении следующая итерация балансировки запускается, не дожидаясь окончания ResourceChangeReactionPeriod. ||
```suggestion
|| continue_auto_balancer | true/false | При включении следующая итерация балансировки запускается, не дожидаясь окончания ResourceChangeReactionPeriod. ||
```

2025-03-12 14:36 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| check_move_expediency | вкл/выкл | Проверка целесообразности перемещений таблеток. ||
```suggestion
|| check_move_expediency | true/false | Проверка целесообразности перемещений таблеток. ||
```

2025-03-12 14:36 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| default_tablet_limit | Вложенная секция | Ограничения на запуск таблеток различных типов на одном узле. Указывается в формате списка, где каждый элемент имеет поля type и max_count.
```suggestion
|| default_tablet_limit | Вложенная секция | Ограничения на запуск таблеток различных типов на одном узле. Указывается в формате списка, где каждый элемент имеет поля `type` и `max_count`.
```

2025-03-16 14:14 UTC, fomichev3000 requested changes
Я написал один комментарий, но в нем все...

2025-03-16 14:14 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +# Настройка Hive
Этот раздел точно должен начинаться с какой-то преамбулы. Сейчас это куча опций, которые мне куда писать? В корень yaml-файла? В какую-то секцию?

Я открыл эту статью и у меня возникло чувство возмущения... Я не понимаю, как пользователь, как мне этим всем пользоваться. 100500 настроек без объяснения и группировки делают меня несчастным. Дальше читать не стал...

2025-03-18 17:01 UTC, CyberROFL commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
> +На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигур
```suggestion
На странице **Settings** представлен список параметров конфигурации Hive, которыми можно управлять через интерфейс. Для каждого параметра указано три значения: текущее значение, значение из [конфигурации {{ ydb-short-name }}](../../maintenance/manual/config-overview.md) и значение по умолчанию. Параметры, значения которых выставлены через интерфейс, выделены полужирным шрифтом. Выставленные через интерфейс значения имеют приоритет над значениями из конфигурации {{ ydb-short-name }}. Внесение изменений в настройки через интерфейс не изменяет значения в конфигурации. С описанием параметров можно ознакомиться в [описании конфигурации](../configuration/hive.md).
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `warm_up_enabled` | WarmUpEnabled | true/false | Ожидание старта всех узлов при старте базы или запуск таблеток на первом подключившемся. | true ||
> Ожидание старта всех узлов при старте базы или запуск таблеток на первом подключившемся.

Нужно написать, что из этого происходит при значении `true`, а что — при `false`.

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `node_restarts_for_penalty` | NodeRestartsForPenalty | Целое число | Узлы получают понижение приоритета за такое количество рестартов на окне в `node_restart_watch_period`. | 3 ||
```suggestion
|| `node_restarts_for_penalty` | NodeRestartsForPenalty | Целое число | Количество рестартов на окне `node_restart_watch_period`, после которого узлы получают понижение приоритета. | 3 ||
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +- `HIVE_STORAGE_BALANCE_STRATEGY_IOPS`;
Дубликат.

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +- `HIVE_STORAGE_BALANCE_STRATEGY_SIZE`;
Лучше дать небольшую справку по каждому варианту и AUTO поместить в конец.

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `storage_pool_fresh_period` | StoragePoolFreshPeriod | Целое число миллисекунд | Информация о пулах хранения столько времени считается актуальной. | 60000 ||
```suggestion
|| `storage_pool_fresh_period` | StoragePoolFreshPeriod | Целое число миллисекунд | Периодичность обновления информации о пулах хранения. | 60000 ||
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `max_channel_history_size` |  MaxChannelHistorySize | Целое число | Балансировка каналов не должна приводить к тому, чтобы размер истории канала превышал это значение. | 200 ||
```suggestion
|| `max_channel_history_size` |  MaxChannelHistorySize | Целое число | Максимальный размер истории каналов. | 200 ||
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `space_usage_penalty_threshold` | SpaceUsagePenaltyThreshold | Вещественное число | При перевозе канала из-за кончающегося места в группе пессимизировать группы, в которых свободное место отличает
```suggestion
|| `space_usage_penalty_threshold` | SpaceUsagePenaltyThreshold | Вещественное число | Минимальное отношение свободного места в целевой группе к свободному месту в исходной группе, при котором целевая группа будет пессимизирована при перевозе канала. | 1.1 ||
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `node_usage_range_to_kick` | NodeUsageRangeToKick | Вещественное число | Автобалансировка считается нецелесообразной, если разница в уровне потребления ресурсов между узлами меньше этого значения.
```suggestion
|| `node_usage_range_to_kick` | NodeUsageRangeToKick | Вещественное число | Минимальная разница в уровне потребления ресурсов между узлами, ниже которой автобалансировка считается нецелесообразной. | 0.2 ||
```

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `object_imbalance_to_balance` | ObjectImbalanceToBalance | Вещественное число | Порог метрики дисбаланса таблеток одного объекта. | 0.02 ||
Вообще не понял.

2025-03-19 10:52 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `min_group_usage_to_balance` | MinGroupUsageToBalance | Вещественное число | Потребление ресурсов группы хранения ниже данного значения приравнивается к данному значению. | 0.1 ||
```suggestion
|| `min_group_usage_to_balance` | MinGroupUsageToBalance | Вещественное число | Порог потребления ресурсов группы хранения, ниже которого не запускается балансировка. | 0.1 ||
```

2025-03-19 11:43 UTC, CyberROFL commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
Нужно добавить в "Справка - Встроенный UI - Обзор".

2025-03-20 12:21 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| channel_balance_strategy | Перечисление | Стратегия выбора канала для переназначения при балансировке каналов. Возможные варианты:
Тут пропущено название параметра в Hive web-viewer

2025-03-20 12:21 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `target_tracking_cpumargin` | TargetTrackingCPUMargin | Вещественное число | Допустимое отклонение от целевого значения утилизации CPU при автоскейлинге | 0.1 ||
```suggestion
|| `target_tracking_cpumargin` | TargetTrackingCPUMargin | Вещественное число | Допустимое отклонение от целевого значения утилизации CPU при автоскейлинге. | 0.1 ||
```

2025-03-20 14:36 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|#
@anton-bobkov без {wide-content} выглядело лучше, имхо.

2025-03-20 14:42 UTC, CyberROFL reviewed
В целом lgtm.

2025-03-20 14:42 UTC, CyberROFL commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `continue_emergency_balancer` | ContinueEmergencyBalancer | true/false | Аналогично ContinueAutoBalancer, но для emergency-балансировки. | true ||
Тут ссылка то на название опции в конфиге, то в UI. Предлагаю выбрать что-то одно, например, опцию в конфиге.
```suggestion
|| `min_period_between_emergency_balance` | MinPeriodBetweenEmergencyBalance | Вещественное число секунд | Аналогично `min_period_between_balance`, но для emergency-балансировки. | 0.1 ||
|| `emergency_balancer_inflight` | EmergencyBalancerInfligh | Целое число | Аналогично `balancer_inflight`, но для emergency-балансировки. | 1 ||
|| `max_movements_on_emergency_balancer` | MaxMovementsOnEmergencyBalancer | Целое число | Аналогично `max_movements_on_auto_balancer`, но для emergency-балансировки. | 2 ||
|| `continue_emergency_balancer` | ContinueEmergencyBalancer | true/false | Аналогично `continue_auto_balancer`, но для emergency-балансировки. | true ||
```

2025-03-22 17:33 UTC, fomichev3000 requested changes
В целом почти нормально уже выглядит. Я написал много комментариев, но вроде бы они не очень сложно исправляются

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `min_period_between_balance` | MinPeriodBetweenBalance | Вещественное число секунд | Минимальный период времени между двумя итерациями автобалансировки. Не относится к emergency-балансировке. | 0.
совершенно не понятно, что такое "emergency-автобалансировка"

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `balancer_inflight` | BalancerInflight | Целое число | Число таблеток, одновременно перезапускающихся в процессе автобалансировки. Не относится к emergency-балансировке. | 1 ||
совершенно не понятно, что такое "emergency-автобалансировка"

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `max_movements_on_auto_balancer` | MaxMovementsOnAutoBalancer | Целое число | Число перемещений таблеток за одну итерацию автобалансировки. Не относится к emergency-балансировке. | 1 ||
совершенно не понятно, что такое "emergency-автобалансировка"

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `check_move_expediency` | CheckMoveExpediency | true/false | Проверка целесообразности перемещений таблеток. | true ||
Непонятное объяснение. Вообще я по умолчанию подразумеваю, что Hive должен проверять целесообразность перемещения таблеток. А если false поставить, то Hive goes wild??

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `balancer_ignore_tablet_types` | BalancerIgnoreTabletTypes | Список типов таблеток. При выставлении через Hive UI — разделённый точкой с запятой. | Типы таблеток, на которые не распространяется ав
Пепонятно как этот список задавать. Перечисления нет, примера нет

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +Эти опции регулируют сбор, агрегацию и нормировку [метрик потребления вычислительных ресурсов](../../contributor/hive.md#resources).
Я бы написал больше букв. Например, что-то вроде:
Hive собирает информацию о потребление ресурсов с узлов базы данных. Перечислил бы ресурсы, а дальше уже твои слова.

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `space_usage_penalty` | SpaceUsagePenalty | Вещественное число | Коэффициент штрафа, описанного выше. | 0.2 ||
Уф, здесь я уже не проглотил. Про штраф выше ничего не пишут

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +## Опции отслеживания перезапусков {#restarts}
перезапусков чего? надо явно написать

возможно стоит сделать 2 раздела и 2 таблицы -- для таблеток и для нод

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `node_restarts_for_penalty` | NodeRestartsForPenalty | Целое число | Количество рестартов на окне `node_restart_watch_period`, после которого узлы получают понижение приоритета. | 3 ||
А какой размер окна для нод? Такой же как для таблеток? Не понятно

Update: увидел. Тем правильнее на 2 раздела разделить

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `tablet_restarts_max_count` | — | Целое число | Количество рестартов на окне `tablet_restarts_period`, при превышении которого применяется пессимизация. | 2 ||
Я прочитал и не понял логику работы на текущих дефолтных настройках. Таблетка пессимизируется, когда 2 раза рестартовала на окне в 1000мс? Или на окне 3600 секунд? 
А значит и пользователь скорее не поймет

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/configuration/hive.md
> +## Прочее {#misc}
Возможно я бы вставил сюда плашку "Эта таблица содержит продвинутые настройки, которые в большинстве случаев не требуют изменения."
Ибо не понятны половина+ опций...

2025-03-22 17:33 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
>  При нажатии на кнопку **Reassign Groups** появится окно с параметрами для балансировки:
Давай опишем зачем вообще надо нажимать эту кнопку. И предупреждение сделаем

2025-03-26 00:51 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `tablet_restarts_max_count` | — | Целое число | Количество рестартов на окне `tablet_restarts_period`, при превышении которого применяется пессимизация. | 2 ||
я прочитал как «на окне в 1000мс»

2025-03-26 00:52 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/hive.md
> +## Прочее {#misc}
вообще её можно было б прям начало страницы перенести)

2025-03-26 04:56 UTC, fomichev3000 requested changes
Я посмотрел последний кормит, он не адресует все мои комментарии. Например, список таблеток я так и не вижу.
Надо последовательно адресовать список всех комментариев!

2025-03-26 08:20 UTC, vporyadke commented
> Я посмотрел последний кормит, он не адресует все мои комментарии. Например, список таблеток я так и не вижу. Надо последовательно адресовать список всех комментариев!

Я думал, что так и сделал. В частности про таблетки я написал перед примером

>В подсекциях `default_tablet_limit` и `default_tablet_preference` нужно указывать типы таблеток. Точные названия типов 
таблеток можно посмотреть, например, на вкладке Tablets в [YDB UI](../embedded-ui/ydb-monitoring.md).

Это наверное не идеальный ответ. Правильный ответ - список всех типов таблеток живёт в tablet_types.proto, кстати там же указаны числовые айдишники и можно при желании использовать их. Но отправлять читателя документации смотреть в .proto я всё-таки не хочу. Ты хотел увидеть прямо список из всех типов таблеток в документации? В теории его можно бы было выделить в глоссарии, но там всякие тонкие моменты, кого в него включать, кого нет: nbs'ные  и rtmr'ные таблетки наверное не нужно, а бывает ли у внешних польователей PersQueueReadBalancer или ReplicationController? Можно ли уже упоминать блобовницу и графшард?

2025-03-26 08:21 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `default_tablet_limit` | — | Вложенная секция | Ограничения на запуск таблеток различных типов на одном узле. Указывается в формате списка, где каждый элемент имеет поля `type` и `max_count`. | Пу
Как ты предалагал ниже, добавил в пример в конце. Про типы таблеток написал перед примером.

2025-03-26 08:23 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `system_category_id` | — | Целое число | При указании любого отличного от 0 числа, все координаторы и медиаторы по возможности запускаются в одном и том же датацентре. | 1 ||
Странное, всё так. Ничего тут с этим не делал.

2025-03-26 08:24 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `max_node_usage_to_kick` | MaxNodeUsageToKick | Вещественное число | Порог потребления ресурсов на узле для запуска emergency-автобалансировки. | 0.9 ||
Дописал пояснение перед блоком настроек

2025-03-26 08:24 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `min_period_between_balance` | MinPeriodBetweenBalance | Вещественное число секунд | Минимальный период времени между двумя итерациями автобалансировки. Не относится к emergency-балансировке. | 0.
Дописал пояснение перед блоком настроек

2025-03-26 08:24 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `balancer_inflight` | BalancerInflight | Целое число | Число таблеток, одновременно перезапускающихся в процессе автобалансировки. Не относится к emergency-балансировке. | 1 ||
Дописал пояснение перед блоком настроек

2025-03-26 08:25 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `max_movements_on_auto_balancer` | MaxMovementsOnAutoBalancer | Целое число | Число перемещений таблеток за одну итерацию автобалансировки. Не относится к emergency-балансировке. | 1 ||
Дописал пояснение перед блоком настроек

2025-03-26 08:25 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `balancer_ignore_tablet_types` | BalancerIgnoreTabletTypes | Список типов таблеток. При выставлении через Hive UI — разделённый точкой с запятой. | Типы таблеток, на которые не распространяется ав
Добавил пример после блока настроек

2025-03-26 08:26 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +## Опции отслеживания перезапусков {#restarts}
Разбил на два подраздела

2025-03-26 08:30 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `tablet_restarts_max_count` | — | Целое число | Количество рестартов на окне `tablet_restarts_period`, при превышении которого применяется пессимизация. | 2 ||
Да что там пользователь, тут и я могу [перепутать](https://github.com/ydb-platform/ydb/commit/24c2d115466b39dbf335636ab18aa92839c09401) :/

Дописал к окну 3600с пояснение, что оно для другого

>**Этот период используется только для статистики, передаваемой в HealthCheck.** |

2025-03-26 08:32 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +## Прочее {#misc}
Вставил эту плашку.

2025-03-26 08:33 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `node_restarts_for_penalty` | NodeRestartsForPenalty | Целое число | Количество рестартов на окне `node_restart_watch_period`, после которого узлы получают понижение приоритета. | 3 ||
Разбил на два подраздела

2025-03-26 08:36 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +* `HIVE_BOOT_STRATEGY_BALANCED` — при достижении лимита в `max_tablets_scheduled` на одном узле останавливает запуск новых таблеток на всех узлах.
Да, правда такая опция. Дописал пояснение

>Если при запуске большого количества таблеток один из узлов запускает таблетки чуть медленне других, то при использовании `HIVE_BOOT_STRATEGY_FAST` на этом узле будет запущено меньше таблеток, чем на остальных. При использовании `HIVE_BOOT_STRATEGY_BALANCED` в той же ситуации таблетки будут равномерно распределены по узлам, но их запуск займёт больше времени.

То есть смысл поведения в том, чтобы получать равномерное распределение таблеток

2025-03-26 10:24 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `boot_strategy` | — | Перечисление | Регулирует поведение при запуске большого числа таблеток. Возможные варианты:
Передвинул

2025-03-26 10:27 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|# {wide-content}
Пример добавил, почти со всеми опциями (скажем, странную system_category_id решил не трогать)

2025-03-26 10:27 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `min_counter_scatter_to_balance` | MinCounterScatterToBalance | Вещественное число | Порог метрики Scatter для ресурса Counter. | 0.02 ||
Добавил ссылку

2025-03-26 10:30 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `spread_neighbours` | SpreadNeighbours | true/false | Запуск таблеток одного объекта по возможности на разных узлах. | true ||
Добавил пояснение "(таблицы, топика)". На самом деле это касается вообще любого схемного объекта, у которого есть таблетки (даже БД - у неё есть координаторы, медиаторы, хайв и сс)

2025-03-26 10:31 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +Эти опции регулируют сбор, агрегацию и нормировку [метрик потребления вычислительных ресурсов](../../contributor/hive.md#resources).
Написал такие буквы, но вообще тут уже есть ссылка на страницу с описанием

2025-03-26 11:37 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `space_usage_penalty` | SpaceUsagePenalty | Вещественное число | Коэффициент штрафа, описанного выше. | 0.2 ||
Поправил формулировку и тут, и сверху

2025-03-26 11:39 UTC, vporyadke commented on ydb/docs/ru/core/reference/configuration/hive.md
> +|| `check_move_expediency` | CheckMoveExpediency | true/false | Проверка целесообразности перемещений таблеток. | true ||
Примерно так, да. Это добавляли ради того, чтобы выключить на какой-то базе, где хайв уходил в себя, пытаясь решить, что бы ему перевезти. Попробовал эту мотивацию отразить.

2025-03-26 11:44 UTC, vporyadke commented on ydb/docs/ru/core/reference/embedded-ui/hive.md
>  При нажатии на кнопку **Reassign Groups** появится окно с параметрами для балансировки:
Дописал про сценарий добавления групп

2025-03-26 17:58 UTC, fomichev3000 approved these changes

2025-03-26 17:58 UTC, fomichev3000 approved these changes

2025-03-27 01:28 UTC, merged