Fix syntax for Column Family
ydb-platform/ydb pull request #10781
Opened 2024-10-23 13:16 UTC by vlad-gogov

2024-10-23 13:54 UTC, azevaykin approved these changes, later dismissed

2024-10-24 09:05 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_translation.cpp
> +            to = BuildLiteralSmartString(ctx, stringValue);
BuildLiteralSmartString может вернуть nullptr и записать ошибку в контекст
по сути этой функции тогда надо вернуть false

2024-10-24 09:06 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_translation.cpp
> +            to = LiteralNumber(ctx, from.GetAlt_family_setting_value2().GetRule_integer1());
тоже самое, надо проверить результат на null

2024-10-24 09:08 UTC, vitstn commented on ydb/public/api/protos/ydb_table.proto
> +    optional sint32 compression_level = 5;
вообще говоря это breaking change
и неужели в публичном api в ненагруженной части важна эта микрооптимизация?
int32 понятен примерно всем

2024-10-24 09:10 UTC, vitstn requested changes
!

2024-10-24 12:37 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_translation.cpp
> +            if (literal->IsNull()) {
сам literal nullptr при ошибке

2024-10-24 12:37 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_translation.cpp
> +            if (literal->IsNull()) {
тоже самое

2024-10-25 10:18 UTC, vitstn approved these changes

2024-10-25 10:21 UTC, merged