Added time counter for local db precharge
ydb-platform/ydb pull request #10883
Opened 2024-10-25 08:30 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-28 12:21 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__init.cpp
> +            timer.AddLoadingFail();
Он зарепортится?

2024-10-28 12:38 UTC, aavdonkin commented on ydb/core/tx/columnshard/columnshard__init.cpp
> +            timer.AddLoadingFail();
Я проверил через curl, оба счетчика на месте

2024-10-28 14:16 UTC, vlad-gogov requested changes

2024-10-28 14:16 UTC, vlad-gogov commented on ydb/core/tx/columnshard/tables_manager.h
> +    friend class TTxInit;
Думаю, в этом случае лучше сделать отдельный метод/методы класса для нужного функционала.

2024-10-28 14:37 UTC, aavdonkin commented on ydb/core/tx/columnshard/tables_manager.h
> +    friend class TTxInit;
Я думал про это
Но в этом случае кто угодно сможет обращаться к мемберу, а так только нужный класс

2024-10-29 07:14 UTC, vlad-gogov commented on ydb/core/tx/columnshard/tables_manager.h
> +    friend class TTxInit;
Если будет нужно получить TLoadTimer в другом классе, то тогда придется добавить еще friend class, что думаю не очень хорошо, поэтому и предлагаю сделать const функцию, которая вызывает StartGuard у поля и возаращает TLoadTimer.

2024-10-29 09:48 UTC, vlad-gogov approved these changes

2024-10-29 09:49 UTC, merged