KIKIMR-19522 BTreeIndex Charge Keys
ydb-platform/ydb pull request #1102
Opened 2024-01-17 15:19 UTC by kunga

2024-01-19 10:03 UTC, kunga commented on ydb/core/tablet_flat/flat_part_charge_btree_index.h
> +    struct TNodeState : TBtreeIndexNode, TChild {
Так нормально, или лучше TBtreeIndexNode и TChild полями сделать?

2024-01-19 13:43 UTC, kunga commented on ydb/core/tablet_flat/flat_part_charge_range.cpp
> +                ready &= CreateCharge(env, *pos->Part, tags, includeHistory)->Do(firstRow, firstRow, keyDefaults, items, bytes);
Не понимаю как оно раньше работало..

2024-01-22 14:58 UTC, snaury requested changes

2024-01-22 14:58 UTC, snaury commented on ydb/core/tablet_flat/flat_part_charge_btree_index.h
> +        const auto iterateLevel = [&](std::function<bool(TNodeState& current, TRecIdx pos)> tryLoadNext) {
I would recommend making the argument `const auto& tryLoadNext` here. You are passing lambdas below, and packaging them into std::function may be expensive or even allocate memory depending on state size.

2024-01-22 14:58 UTC, snaury commented on ydb/core/tablet_flat/flat_part_charge_btree_index.h
> +        const auto iterateLevel = [&](std::function<bool(TNodeState& current, TRecIdx pos)> tryLoadNext) {
Use `const auto& tryLoadNext` here too.

2024-01-22 17:17 UTC, snaury approved these changes

2024-01-23 10:28 UTC, merged