Add ports info to Ansible initial dep article
ydb-platform/ydb pull request #11056
Opened 2024-10-29 12:36 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-10-30 08:56 UTC, blinkov requested changes, later dismissed

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  Запускается один `systemd unit` сторадж ноды (`ydbd-storage`), который задействует порты:
```suggestion
На каждом сервере кластера запускается по одному статическому узлу. В systemd он называется`ydbd-storage`. Статический узел принимает входящие соединения на следующих портах:
```

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  | `5432` | Порт используется для работы совместимости {{ ydb-short-name }} с PostgreSQL. |
```suggestion
  | 2135 | Порт для [основного API {{ ydb-short-name }}](../../reference/ydb-sdk/overview-grpc-api.md), основанного на защищённом [gRPC](https://grpc.io/) соединении поверх [TLS](../../reference/configuration/tls.md).               |
  | 19001 | Порт для [интерконнекта акторной системы {{ ydb-short-name }}](../../concepts/glossary.md#actor-system-interconnect). |
  | 8765 | HTTPS-порт для [встроенного интерфейса](../../reference/embedded-ui/index.md), отображения [метрик](../../devops/manual/monitoring.md) и других вспомогательных команд.                           |
  | 5432 | Порт для [режима совместимости с PostgreSQL](../../postgresql/intro.md). |
```

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  || `ydbd-database-a` | `2136`  | Порты для защищенного GRPCS-соединения (TLS).              ||
аналогично табличке выше убрать бэктики вокруг портов и проапдейтить описания

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  || Процесс           | Порт    | Описание                                                   ||
```suggestion
  || Название динамического узла           | Порт    | Описание                                                   ||
```

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  Запускаются несколько `systemd unit` файлов: `ydbd-database-a` и `ydbd-database-b` для обслуживания нескольких баз данных. Они задействуют порты:
```suggestion
По умолчанию при развёртывании кластера через Ansible на каждом сервере запускается по два динамических узла. В systemd они называются `ydbd-database-a` и `ydbd-database-b`. Они принимают входящие соединения на следующих портах:
```

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
>  {% cut "Подробное пошаговое описание установки {{ ydb-short-name }}" %}
Всю эту историю про порты снабдить отдельным подзаголовком, и видимо перенести следом **за** этот следующий cut с кучей подробностей.

2024-10-30 08:56 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
>  {% cut "Подробное пошаговое описание установки {{ ydb-short-name }}" %}
или хотя б объединить с абзацем на 252 строке, мол вот что у нас получилось

2024-10-30 14:21 UTC, Pseudolukian commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +  || `ydbd-database-a` | `2136`  | Порты для защищенного GRPCS-соединения (TLS).              ||
Сделано

2024-10-30 14:37 UTC, Pseudolukian commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
>  {% cut "Подробное пошаговое описание установки {{ ydb-short-name }}" %}
Поправил

2024-10-31 09:20 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +## Описание портов кластера {{ ydb-short-name }} {#ydb-cluster-ports}
```suggestion
## Подключение к кластеру {#cluster-connection}
```

2024-10-31 09:20 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/initial-deployment.md
> +В результате выполнения плейбука будет создан кластер {{ ydb-short-name }} (используются gRPC-порты 19001-19003 для интерконнекта акторной системы и порт 5432 для режима совместимости с PostgreSQL),
```suggestion
В результате выполнения плейбука будет создан кластер {{ ydb-short-name }}, на котором развёрнута база данных под названием `database`, а также пользователь с именем `root` и максимальными правами доступа. Работать с кластером можно с помощью {{ ydb-short-name }} [CLI](../../reference/ydb-cli/index.md), посылая API-вызовы на порт 2135, через [Embedded UI](../../reference/embedded-ui/index.md), который работает на порту 8765, а также в [режиме PostgreSQL-совместимости](../../postgresql/intro.md) через порт 5432. Также для подключения к Embedded UI можно настроить SSH-туннелирование. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb static node ip>`. После успешного установления соединения можно перейти по URL [localhost:8765](http://localhost:8765):
```

2024-11-06 07:21 UTC, fomichev3000 approved these changes

2024-11-06 07:21 UTC, merged