Optimize attribute fetch loop for source tables in YT
ydb-platform/ydb pull request #11073
Opened 2024-10-29 16:40 UTC by alephonea

Instead of two consecutive fetches, only fetch attributes once for all table paths.
Only when some paths are links, perform the second fetch.

2024-10-30 13:25 UTC, rvu1024 requested changes

2024-10-30 13:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +                    if (attrs.HasKey(YqlRowSpecAttribute)) {
опечатка - linkAttributes

2024-10-30 13:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +        TVector<TMaybe<NYT::TNode>> linkAttributes(tables.size());
Тут можно просто map/unordred_map<size_t, TNode> использовать. Тогда проверка на link будет просто проверкой на empty() этого мапа и проверки типа на L2493 уйдут

2024-10-31 16:52 UTC, alephonea commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +        TVector<TMaybe<NYT::TNode>> linkAttributes(tables.size());
Я так сделал, потому что в HashMap нельзя писать из колбека, а в vector, который предварительно поресайзили можно.
Заменил ручной подсчет числа непустых элементов на std::accumulate, и чуть подправил цикл прохода ниже

2024-11-06 10:08 UTC, rvu1024 approved these changes

2024-11-11 15:53 UTC, merged