Fix obliterate description
ydb-platform/ydb pull request #11221
Opened 2024-11-02 13:31 UTC by mregrock

### Changelog entry 

Replace obliterate description

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-11-07 05:57 UTC, fomichev3000 requested changes

2024-11-07 05:57 UTC, fomichev3000 commented on ydb/docs/ru/core/devops/manual/initial-deployment.md
> +2. Подготовьте диск к использованию встроенной в исполняемый файл `ydbd` командой:
Слово "форматирование" на подсознательном уровне означает "вы потеряете данные". А вот фраза "подготовьте диск" может не вызывать такую ассоциацию. Если хотите написать слово "подготовьте", то не забудьте написать, что данные на этом диске будут потеряны.

2024-11-12 02:56 UTC, blinkov commented on ydb/docs/en/core/devops/manual/initial-deployment.md
> +2. Clear the disk by this command built-in the `ydbd` executable:
Let's indeed add a `{% note warning %}` saying that the pre-existing data will be lost?

2024-11-15 04:44 UTC, blinkov commented on ydb/docs/en/core/devops/manual/initial-deployment.md
> +After executing the command, the data on the disk will be erased.
```suggestion
After executing this command, data on the disk will be erased.
```

2024-11-15 06:54 UTC, fomichev3000 approved these changes

2024-11-15 06:54 UTC, merged