[YQL-17474] Limit supported operation settings in hybrid execution
ydb-platform/ydb pull request #1132
Opened 2024-01-18 14:17 UTC by nepal

-  [YQL-17474] Limit supported operation settings in hybrid execution

2024-01-18 16:45 UTC, rvu1024 requested changes

2024-01-18 16:45 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_op_settings.h
> +constexpr auto DqOpSupportedSettings = EYtSettingType::Flow | EYtSettingType::JobCount | EYtSettingType::Limit | EYtSettingType::Ordered | EYtSettingType::ReduceBy | EYtSettingType::SortBy;
Список сильно не полный. Нужно расширять

2024-01-19 12:29 UTC, nepal commented on ydb/library/yql/providers/yt/provider/yql_yt_op_settings.h
> +constexpr auto DqOpSupportedSettings = EYtSettingType::Flow | EYtSettingType::JobCount | EYtSettingType::Limit | EYtSettingType::Ordered | EYtSettingType::ReduceBy | EYtSettingType::SortBy;
done

2024-01-19 12:42 UTC, rvu1024 approved these changes

2024-01-19 15:05 UTC, merged