Support CollectDiagnostics in DATA_QUERY/GENERIC_QUERY
ydb-platform/ydb pull request #11371
Opened 2024-11-07 12:08 UTC by shnikd

- **add include that comes transparently commit_hash:28a1feed886ff6f1fb586119dcdc433df011773b**
- **Untitled commit commit_hash:52fa2c5e2b0dd5a897e5e492b7fcf3b6eabdf9d0**
- **YT-22867: Change unfolding index API**
- **YT-22068: TError-ize statistics merge**
- **Intermediate changes commit_hash:afec429f28a760d2850a90d23b1a8f590aefa0d5**
- **YT-23050: Hazard pointers must not depend on logging commit_hash:6682ef6bfee76fd4751556ddd50fb3df4d771130**
- **YT: Support plain enum deserialization**
- **Intermediate changes commit_hash:95c0a3d97feffc9568fea8d8cf75e6971dd883bc**
- **[queues] YT-21996: Add background flush in producer client commit_hash:eb9dc1a7bc5c58cb2bb895771617230de998dc64**
- **Untitled commit commit_hash:e3d4f9d92d5e2ef511b78fa9da787e6a67bec265**
- **Intermediate changes commit_hash:ec2de59c841270f9f65ce794885833c6f4800a62**
- **Use lower case for TString methods Data, Size and Empty in extsearch, fintech, games, geobase, infra, ipreg, juggler, kernel, keyboard, laas, library, logbroker, logos, mail**
- **add include that comes transparently commit_hash:5be750ea1896b1ae8b1d395a4131341555dca8c9**
- **Intermediate changes commit_hash:93cf56fbe7125e68c2d1b9d57ae3ed8db0052605**
- **Support Android build for YT library commit_hash:a21164c621de657007dd5ba88024cf92cb5ba739**
- **Intermediate changes commit_hash:89646da3670c4ea2abe57002fae1fbf6cf2bfd21**
- **YT-23120: Fix waiting for slots in slot manager disabling commit_hash:1226dadb678edbd2ce2a006850fb9d8f009dac1f**
- **OpenSSL+quictls**
- **YT: Support DoAttributes in fluent yson builder commit_hash:bc040fe60da2c2ac38e9fa90f43169a08ccd32db**
- **Untitled commit commit_hash:3bb34c7656f9f425d9f9dbe140340f1d5b57586f**
- **[queues] YT-21996: Add Flush() in producer client commit_hash:27868d66efa2608a6ce4e074e1c2d6516b4c5590**
- **add include that comes transparently commit_hash:96d26ff6ad6f69272fc19ff157bb73013c3f8df7**
- **Intermediate changes commit_hash:0c8398a3ccea3051aa5a3484e6c741e13151a695**
- **YT-23122: Ping replication card residency cache during long polling commit_hash:c0a5fdf40615a88982a47b87a772293b506e6687**
- **add include that comes transparently commit_hash:7ec5bc6f7e85e5412ff6759b0d1bd52d1172a9c1**
- **Revert commit rXXXXXX, YT-22068: TError-ize statistics merge commit_hash:2c3a3fb41a7eb33305635fcf1c529880a3982728**
- **Revert "Update contrib/libs/curl to 8.10.1" to fix**
- **YT-21938: Introduce get_job_trace**
- **Provide sys/mman.h by the means of libc_compat**
- **Intermediate changes commit_hash:3ed72e620c7eace6c8edd510ac2324e8acfcfafb**
- **TAtomicObject::Transform may return a value commit_hash:d726b589eadfe0234b96c2e8d2ba90b4b7d267b0**
- **YT-23139: Change error code when there is no memory on http proxies commit_hash:9c61bc9e79a37c41ff8ceadaedd501a25d8fa447**
- **YT-11222, YT-21401: Add ACO to operation spec**
- **Cut default rpc heavy thread pool size 16 -> 6 commit_hash:278ab868e51dd3b0c95270f804545b7fac7c3888**
- **Style commit_hash:dcfcb4a11cdbfe607a4c2591f4005538a18a57f8**
- **Update binary black to 24.10.0 commit_hash:6b0f525ddaa513534f567494a482afdd2149b9b0**
- **Intermediate changes commit_hash:832e3683ad1b3c1089fec74bc325f641da0b442b**
- **Revert commit rXXXXXX, Cut default rpc heavy thread pool size 16 -> 6 commit_hash:1a94f1df693465d2510164c05df5a6cb43858ad8**
- **Extract string_builder commit_hash:1573c88f09db79bab2755c9c2c3ffd0bc219b2d2**
- **New version of the tld SKIP_CHECK SKIP_REVIEW commit_hash:88c0cdd1339b95fa5826e2ad3714c6ac63f5d6d9**
- **Automatic release build for ymake, os_ymake**
- **Exception in dart record to configure error**
- **[build] SDC metadata collection**
- **Style commit_hash:e267dc9b41e9291970d760657852a20f06fa8410**
- **Fix issues of rXXXXXX commit_hash:a0bfce6941dd82358c5eedb213dfa98543a5a6d0**
- **Automatic release build for test_tool, os_ya, ya_bin, os_test_tool**
- **Intermediate changes commit_hash:c7b424f51fc54aa5731f2bff20943a09dbe30095**
- **build/platform/lld: Drop clang14 support for ld64.lld**
- **Replay sql core (#10379)**
- **Refactored join conditions in CBO (#10366)**
- **Intermediate changes commit_hash:67a8b030334a9a3c9289af15dc533057f4f7ec01**
- **add include that comes transparently (#10374)**
- **YDB FQ: unmute connector tests (#10392)**
- **Replace codec to RAW if not specified (#10272)**
- **Add backup collection schema path item (#10252)**
- **Trim debug info in configs_dispatcher (#10364)**
- **feat: Supported Dapper documentation (#9964)**
- **Fix wrong columns order in sinks (#10338)**
- **Sink metrics & trace (#10397)**
- **Atomically update feature flags at runtime (#10281)**
- **Move atomic object to library/cpp/yt/threading**
- **mask set-cookie in http response (#10316)**
- **Fix sql flags for module resolver in query replay (#10405)**
- **Optimization of the `UpdateOffsetsInTransaction` calls (#10273)**
- **fix splitter condition to avoid split micro-chunks (#10375)**
- **Intermediate changes commit_hash:36c8231ac7d17ca0d196613bbe94471e663a2ac9**
- **Get rid of unnecessary code (#10410)**
- **ci: add antlr4 to github runner image (#10407)**
- **Yq 3724 Move no_pg_wrapper to fq (#10360)**
- **YT-23050: Make logger tolerant to logging during its own initialization commit_hash:e40178974c2ab0b3d9d3c40f4f80cd0d80f4681e**
- **YT-22307: Implement distributed write protocol (no signatures yet)**
- **YT-22451: Trivial: address comments commit_hash:3edd78537942491c387935cc9cc78c60a1494298**
- **Forbid forbidden erasure codecs for remote copy commit_hash:1f84c1dea9fb626ec9f657b96e3d695c0e65bdb0**
- **Add hint for compact Join (#10236)**
- **Remove TEST_CLASSPATH_VALUE which is never set to some nonempty value commit_hash:251f100d789e57861ed91af2b1318537a09af3c2**
- **TEST_CLASSPATH_MANAGED is removed from conf part commit_hash:2a36e49787ad1c13eeb1a5259f780cdf59550666**
- **refactoring tpch generator (#10414)**
- **Intermediate changes commit_hash:4e8eadf6c73fa235953f526fe034e5035339c16f**
- **YQ-3753 Shared reading: metadatafields (#10370)**
- **YQ-3753 Fix build (#10421)**
- **[refactoring] Do not include actorsystem.h into actor.h (#10394)**
- **redefine json_errdetail (#10420)**
- **Fix tpch generator (#10423)**
- **Small speedup tpcds generator (#10424)**
- **PDisk noop scheduler (#9332)**
- **YQ-3722 RD added messages accumulating (#10380)**
- **Do not try to collect extra sort columns if ORDER BY is ignored (#10417)**
- **Intermediate changes commit_hash:c3414e018009e194cdb2bd08f7333f9ebcbab9ce**
- **Automatic release build for test_tool, os_ya, ya_bin, os_test_tool**
- **Shared Cache Clock-Pro implementation  (#10063)**
- **Intermediate changes commit_hash:b4d87cdddfb809ce2f3c9dfd1142cf6e92a83cb7**
- **Add yt/yt/ytlib into YDB GH sync**
- **Enable postgresql tests with sanitizer (#10320)**
- **Collect and send backtraces for tx max/failed allocations in error message (#10419)**
- **YQ-3756 Shared reading: check buffer size in read_actor (#10418)**
- **Increase max decimal precision to 76 (decimal256)**
- **Throw error if manifests don't exist (#10396)**
- **add ydb2 schema, add some crazy types to render to json (#10443)**
- **Fix leak in TChunkReadPiece (#10442)**
- **Intermediate changes commit_hash:a9d505ad0eca8d52e322f9b3f5daaa1968f65b7b**
- **Revert commit rXXXXXX, Add yt/yt/ytlib into YDB GH sync**
- **dstool cluster balance add --storage-pool, --max-donors-per-pdisk and --sort-by={slots/space_ratio} (#10406)**
- **[ldap] Prohibit requests with empty password (#10399)**
- **[refactoring] Do not include grpc_request_proxy.h in each cpp (#10451)**
- **Fixed resolving of pg aggregation over state (#10441)**
- **YT-22307: Drop include dependency client -on-> ytlib commit_hash:ccc25ebeed4973b3f8f133835e308fad69589169**
- **Remove session from pool in case of BAD_SESSION... (#10437)**
- **Do not retry CLIENT_UNAUTHENTICATED & CLIENT_CALL_UNIMPLEMENTED (#10465)**
- **Intermediate changes commit_hash:fef742ad568d08fe1ef9b251d57df5255a44074f**
- **YQ-3535 RD supported optional columns as NULLs (#10452)**
-  [...]

2024-11-20 12:47 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    const TString& GetDiagnostics() const { return Diagnostics_; }
А у диагностик нет какого-то специфицированного формата? Это ок, что SDK отдает пользователю сырые байтики?

2024-11-20 16:50 UTC, shnikd commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    const TString& GetDiagnostics() const { return Diagnostics_; }
там лежит сериализованный json, в принципе мы уже сейчас для explain'а его отдаем https://github.com/ydb-platform/ydb/blob/main/ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp#L2182

2024-12-17 14:34 UTC, CyberROFL submitted a review, later dismissed
Изменения api — ок.

2024-12-18 02:29 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
> +    config.Opts->AddLongOption("collect-diagnostics", "Collects diagnostics and saves it to file")
А новая опция прошла саппорт?

2024-12-18 02:29 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
> +        TFileOutput file(TStringBuilder() << "diagnostics_" << TGUID::Create().AsGuidString() << ".txt");
А почему диагностику грузим в рандомный файл? Не лучше дать пользователю дать возможность указать путь до файла?

2024-12-23 12:46 UTC, CyberROFL commented on ydb/public/api/protos/ydb_table.proto
> -    bool collect_full_diagnostics = 8;
А как тут обеспечится обратная совместимость для клиентов?

2025-02-14 08:35 UTC, pnv1 commented on ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
> +        TFileOutput file(TStringBuilder() << DiagnosticsFile << ".json");
We usually do not change file names provided by user. Is it really necessary?
I think it's confusing. You provide a file name for the command but the file is actually created with another name...

2025-02-14 08:45 UTC, pnv1 approved these changes, later dismissed

2025-02-14 10:39 UTC, CyberROFL approved these changes, later dismissed
public api — ok

2025-02-14 11:16 UTC, Gazizonoki requested changes

2025-02-14 11:16 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
> +    // FLUENT_SETTING_DEFAULT_DEPRECATED(bool, CollectFullDiagnostics, false);
Это же ломает обратную совместимость. И зачем ставить FLUENT_SETTING_DEFAULT_DEPRECATED?

2025-02-14 11:16 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
> -    const std::string& GetDiagnostics() const { return *Diagnostics_; }
Это тоже ломает обратную совместимость

2025-02-14 11:16 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/query/stats.h
> +    std::optional<std::string> GetMeta() const;
GetMeta не понятное название. А имя такое согласовали?

2025-02-14 11:16 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
> +    const std::string GetMeta() const;
Почему метод в DataQueryResult? Они и так же уже есть в TQueryStats

2025-02-14 14:23 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
> +    //Deprecated. Use CollectQueryStats >= ECollectQueryStatsMode::Full to get QueryMeta in QueryStats
```suggestion
    // Deprecated. Use CollectQueryStats >= ECollectQueryStatsMode::Full to get QueryMeta in QueryStats
```

2025-02-14 14:23 UTC, Gazizonoki commented on ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
> +    std::optional<std::string> FakeDiagnostics_;
Это кажется еще хуже. Так хоть сборка сломалась бы, а тут мы втихую просто перестаем возвращать диагностику. Пусть SDK дальше возвращает ее честно

2025-02-14 14:23 UTC, Gazizonoki commented on ydb/public/sdk/cpp/src/client/table/impl/table_client.cpp
> -    request.set_collect_full_diagnostics(settings.CollectFullDiagnostics_);
То же самое, пусть флаг и дальше будем проставлять, просто разметим, что он deprecated

2025-02-14 15:09 UTC, Gazizonoki approved these changes, later dismissed
SDK LGTM

2025-02-14 15:22 UTC, Gazizonoki approved these changes

2025-02-14 16:15 UTC, pnv1 approved these changes
CLI - ok

2025-02-14 17:37 UTC, gridnevvvit commented on ydb/public/api/protos/ydb_query_stats.proto
> +    string query_meta = 8;
shipping this on behalf of the internal discussion

2025-02-14 17:37 UTC, gridnevvvit approved these changes

2025-02-14 18:08 UTC, merged