YQ RD enable LLVM in purecalc filters
ydb-platform/ydb pull request #11442
Opened 2024-11-10 15:24 UTC by GrigoriyPA

- **Update information about LoadActor management via CLI, YDBDOCS-877 (#10773)**
- **#9227 Support ANSI SQL syntax highlighting (#11233)**
- **#9227 Add YQL highlighting tests (#11234)**
- **Add ports info to Ansible initial dep article (#11056)**
- **Fix typos in BUILD.md and update "Install dependencies" section (#11213)**
- **[docs] improve topology.md based on feedback from #7690 (#10966)**
- **Set providers/common/pushdown owner to fq (#11301)**
- **YQ-3713 Shared reading: SqlIn predicate (#11132)**
- **YQ-3809 Shared reading: fix logging (#11175)**
- **ensure reads are sequential (#11280)**
- **Fix last/next in harness (#11311)**
- **Switch off the ColumnStatistics feature flag for tenant tests (#11297)**
- **YQ-3811 Shared reading: check the same consumer in all clients (#11205)**
- **Report IC session state to Node Whiteboard (#11310)**
- **Harness: fix start/stop (#11316)**
- **Async fetch portion data access info (#11246)**
- **fix normalizers for v1 migration chunks (#11308)**
- **Clarify the secondary indexes usage in the concepts article (#10855)**
- **Harness refactor 4 (explicit ssh_user param) (#11229)**
- **YQ-3822 Don't use connect() in retry_queue (#11292)**
- **Metrics for buffer actor (#11304)**
- **Harness refactor 5 (explicit binary path) (#11324)**
- **Use one shared data for the entire test. (#11281)**
- **Fix kqp test on spilling in selfjoin (#11254)**
- **Harness refactor 6 (remove yatest.common.get_param from harness) (#11328)**
- **Refactor harness 7 (less param_constants) (#11332)**
- **Fix param_constants.ssh_user (#11336)**
- **Use ReadRows for loading COUNT_MIN_SKETCH statistics (#10967)**
- **YDBDOCS-909: fix a table in ru topology.md (#11340)**
- **YQ RD support strings parsing in Json columns (#11331)**
- **rd reconnect has been supported (#11322)**
- **updated retry policy in fq proxy (#11271)**
- **Unmute stable tests (#11334)**
- **YQ-3820 Shared reading:  remove Y_ENSURE / add log message (#11337)**
- **Mute flaky tests (#11350)**
- **Disabling EnableColumnStatistics feature flag for test system view (#11347)**
- **Disable control_plane_storage ut under asan in PR (#11363)**
- **Fix flow control in run script actor (#11241)**
- **Huge defrag smooth linear threshold (#9825)**
- **remove unused stream profile event (#11366)**
- **Fix db param and show error message (#11361)**
- **Enabled column statistics by default (#10033)**
- **Vector index coordination: enable local kmeans case (#10497)**
- **Copy TS3Uploader to shared module (#11312)**
- **oidc add cookie logs (#11367)**
- **Multiple channels for external blobs (#10998)**
- **Temporary switch off canonization for tpch 1k+ (#11385)**
- **add network diagnostics columns to viewer/nodes handler (#11344)**
- **fix timeout in tenantinfo handler (#11384)**
- **Add a feature flag controlling separate disk space quotas accounting (#10936)**
- **Write changes using WriteTxId in consistent mode (#11374)**
- **EnableTempTables true (#11381)**
- **YQ RD optimized purecalc memory usage (#11394)**
- **Fix --metadata-fields name in docs (#11391)**
- **Force oldest locks into shard locks due to range limits (#11329)**
- **Timestamp topic options: parse in different formats, describe which timestamp is in option (#11387)**
- **Canonical results for tpcds s1 (#11402)**
- **fix waiting in test (#10626)**
- **optimize initializiton of allocation units (#10969)**
- **YQ-3832 RD supported COALESCE and IF pushdown (#11397)**
- **Unmute ydb_persqueue_public chunks (#11408)**
- **Fix read session correct close ut (#11407)**
- **Try to lsof, when fail to lock file (#11393)**
- **realign mvp core library with arcadia (#11401)**
- **Add PDisk/VSlot whiteboard states to sys_view (#10491)**
- **YQ-3824 Shared reading: fix `is not distinct from` with optional field  (#11378)**
- **ticket-parser: Add error message for log to TError struct of ticket parser (#11403)**
- **ticket parser: Add priority to access service requests (#11278)**
- **Fix arithmetic in tpcds queries and switch on checking answers for tpcds s1 (#11425)**
- **Incorrect label name (#11410)**
- **ldap: Return special error messages for write to log from ldap auth provider (#11404)**
- **Throw exception instead of calling exit(1) in TBasicServicesInitializer (#11422)**
- **Remove obsolete map from backpressure queue client (#11429)**
- **YQL: Load binaries from YT binary cache (#11295)**
- **Move balancer to batch pool (#11420)**
- **verify tasksSize == actorIds.size() has been changed to internal error (#11434)**
- **Fix `TMultiConstraintNode(): requirement Items_.size() failed` error (#11417)**
- **[yt provider] Fix column group calculation for YtCopy (#11435)**
- **[yt provider] Bypass YtCopy before YtLength (#11436)**
- **Enabled LLVM in purecalc filters**

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-10 15:46 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +        str << "PRAGMA config.flags(\"LLVM\", \"ON\");";
Давай еще перенос строки добавим

2024-11-13 07:16 UTC, kardymonds submitted a review, later dismissed

2024-11-13 12:00 UTC, dorooleg requested changes

2024-11-13 12:00 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/common.cpp
> +        TGuard<TMutex> guard(FactoriesMutex);
Может избавиться от этого mutex, сразу предсоздать две фабрики и использовать, тогда будет concurrent safe, но без mutex. Что думаешь?

2024-11-13 12:00 UTC, dorooleg commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> +                srcDesc.SetEnabledLLVM(false);
Он же и так false по умолчанию, это proto3

2024-11-13 16:11 UTC, dorooleg approved these changes

2024-11-13 16:12 UTC, merged