Docs: Compression for Column Table
ydb-platform/ydb pull request #11458
Opened 2024-11-11 08:24 UTC by vlad-gogov

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-11-15 04:26 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит кодек сжатия на `lz4`:
видимо в этом же PR надо удалить include со строки номер 5, т.к. там написано, что вся эта страница для колоночных таблиц не поддерживается

2024-11-15 04:27 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +Поле `DATA` поддерживается только для [строковых](../../../../concepts/datamodel/table.md#row-oriented-tables) таблиц.
такое лучше по месту где про эту настройку говорится, а не в начале, т.к. тут контекст ещё не понятен

2024-11-20 07:40 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +При помощи команды `ALTER FAMILY` можно изменить параметры группы колонок. Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит тип хранилища на `hdd` (поддержива
Несколько раз встречается фраза вида "поддерживается только для".

@blinkov , наверняка, у нас есть какой-то стиль оформления подобных примечаний?

2024-11-29 03:34 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +При помощи команды `ALTER FAMILY` можно изменить параметры группы колонок. Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит тип хранилища на `hdd` (поддержива
@azevaykin стандартный стиль оформления вон выше удаляется на строках 3-7.

Я б рекомендовал тут вместо текста сплошняком досыпать заголовков третьего уровня в духе «изменение типа хранилища» и «изменение уровня компрессии», а под ними добавить такие же типовые плашки через include.

2024-12-28 06:44 UTC, blinkov requested changes, later dismissed

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/en/core/_includes/codec_zstd_allow_for_olap_text.md
> +Codec `"zstd"` is supported only for [column-oriented](../concepts/datamodel/table.md#column-oriented-tables)
```suggestion
Codec `"zstd"` is supported only for [column-oriented](../concepts/datamodel/table.md#column-oriented-tables) tables.
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +* В колоночных таблицах поддерживаются группы колонок, но пока только используется для задания сжатия на колонках.
```suggestion
* В колоночных таблицах поддерживаются группы колонок, но пока это используется только для задания сжатия на колонках.
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит тип хранилища на `hdd`:
```suggestion
Приведённый ниже код для группы колонок `default` в таблице `series_with_families` сменит тип хранилища на `hdd`:
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит кодек сжатия на `lz4`:
```suggestion
Приведённый ниже код для группы колонок `default` в таблице `series_with_families` сменит кодек сжатия на `lz4`:
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Приведенный ниже код для группы колонок `default` в таблице `series_with_families` сменит уровень кодека сжатия, если он поддерживает различные уровни сжатия:
```suggestion
Приведённый ниже код для группы колонок `default` в таблице `series_with_families` сменит уровень кодека сжатия, если он поддерживает различные уровни сжатия:
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +* `DATA` — тип устройства хранения для данных колонок этой группы. Допустимые значения: `"ssd"`, `"rot"`.
```suggestion
Колонки одной таблицы можно объединять в группы, чтобы задать следующие параметры:

* `DATA` — тип устройства хранения для данных колонок этой группы. Допустимые значения: `"ssd"`, `"rot"`.
```

2024-12-28 06:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +В примерах ниже для создаваемых таблиц добавляется группа колонок `family_large` и устанавливается для колонки `series_info`, а также переопределяются параметры для группы `default`, которая по умолч
```suggestion
По умолчанию все колонки находятся в одной группе с именем `default`. При необходимости параметры этой группы тоже можно переопределить. В противном случае применяются предопределённые значения.

В примерах ниже для создаваемых таблиц добавляется группа колонок `family_large`, которая устанавливается для колонки `series_info`, а также переопределяются параметры для группы `default`, которая по умолчанию применяется ко всем остальным колонкам.
```

2025-01-19 07:54 UTC, fomichev3000 approved these changes

2025-01-19 07:54 UTC, merged