Update docker quick start section in docs
ydb-platform/ydb pull request #11485
Opened 2024-11-11 15:53 UTC by ggerlakh

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-15 04:05 UTC, blinkov commented on ydb/docs/en/core/quickstart.md
> +      {% endnote %}
```suggestion
To disable the `YDB_USE_IN_MEMORY_PDISKS` option when running a Docker container on a Mac with an Apple Silicon processor, it must emulate the x86_64 instruction set:

- With [colima](https://github.com/abiosoft/colima), use the `colima start --arch aarch64 --vm-type=vz --vz-rosetta` options.
- With [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/), install and enable Rosetta 2.
```

2024-11-15 12:08 UTC, ggerlakh commented on ydb/docs/en/core/quickstart.md
> +      {% endnote %}
Проправил и в ru и в en https://github.com/ydb-platform/ydb/pull/11485/commits/d2bf27c970eb484858dd1ba59298046863156e8b

2024-11-15 15:13 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      Чтобы отключить опцию YDB_USE_IN_MEMORY_PDISKS при запуске контейнера Docker на Mac с процессором Apple Silicon, он должен эмулировать набор инструкций x86_64:
```suggestion
      Чтобы отключить опцию `YDB_USE_IN_MEMORY_PDISKS` при запуске контейнера Docker на Mac с процессором Apple Silicon, он должен эмулировать набор инструкций x86_64:
```

2024-11-20 08:22 UTC, asmyasnikov submitted a review, later dismissed

2024-11-20 08:27 UTC, polRk commented on ydb/docs/en/core/quickstart.md
> +      - With [colima](https://github.com/abiosoft/colima), use the `colima start --arch aarch64 --vm-type=vz --vz-rosetta` options.
Working Colima template

```
# Architecture of the virtual machine (x86_64, aarch64, host).
#
# NOTE: value cannot be changed after virtual machine is created.
# Default: host
arch: host

# Virtual Machine type (qemu, vz)
# NOTE: this is macOS 13 only. For Linux and macOS <13.0, qemu is always used.
#
# vz is macOS virtualization framework and requires macOS 13
#
# NOTE: value cannot be changed after virtual machine is created.
# Default: qemu
vmType: vz

# Utilise rosetta for amd64 emulation (requires m1 mac and vmType `vz`)
# Default: false
rosetta: true

# Volume mount driver for the virtual machine (virtiofs, 9p, sshfs).
#
# virtiofs is limited to macOS and vmType `vz`. It is the fastest of the options.
#
# 9p is the recommended and the most stable option for vmType `qemu`.
#
# sshfs is faster than 9p but the least reliable of the options (when there are lots
# of concurrent reads or writes).
#
# NOTE: value cannot be changed after virtual machine is created.
# Default: virtiofs (for vz), sshfs (for qemu)
mountType: virtiofs

# Propagate inotify file events to the VM.
# NOTE: this is experimental.
mountInotify: false
```

2024-11-21 07:16 UTC, anton-bobkov requested changes

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      - С помощью [colima](https://github.com/abiosoft/colima) используйте параметры `colima start --arch aarch64 --vm-type=vz --vz-rosetta`.
```suggestion
      - С помощью [colima](https://github.com/abiosoft/colima) – используйте параметры `colima start --arch aarch64 --vm-type=vz --vz-rosetta`.
```

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      - С помощью [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/) установите и включите Rosetta 2.
```suggestion
      - С помощью [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/) – установите и включите Rosetta 2.
```

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/en/core/quickstart.md
> +      - With [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/), install and enable Rosetta 2.
```suggestion
      - With [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/) – install and enable Rosetta 2.
```

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/en/core/quickstart.md
> +      - With [colima](https://github.com/abiosoft/colima), use the `colima start --arch aarch64 --vm-type=vz --vz-rosetta` options.
```suggestion
      - With [colima](https://github.com/abiosoft/colima) – use the `colima start --arch aarch64 --vm-type=vz --vz-rosetta` options.
```

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/en/core/quickstart.md
> +      To disable the `YDB_USE_IN_MEMORY_PDISKS` option when running a Docker container on a Mac with an Apple Silicon processor, it must emulate the x86_64 instruction set:
```suggestion
      To disable the `YDB_USE_IN_MEMORY_PDISKS` option when running a Docker container on a Mac computer with Apple silicon, it must emulate the x86_64 instruction set:
```

2024-11-21 07:16 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      Чтобы отключить опцию `YDB_USE_IN_MEMORY_PDISKS` при запуске контейнера Docker на Mac с процессором Apple Silicon, он должен эмулировать набор инструкций x86_64:
```suggestion
      Чтобы отключить опцию `YDB_USE_IN_MEMORY_PDISKS` при запуске контейнера Docker на компьютере Mac с процессором Apple silicon, он должен эмулировать набор инструкций x86_64:
```

2024-11-27 08:45 UTC, anton-bobkov submitted a review, later dismissed

2024-11-27 08:45 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      - [colima](https://github.com/abiosoft/colima) используйте параметры `colima start --arch aarch64 --vm-type=vz --vz-rosetta`;
```suggestion
      - [colima](https://github.com/abiosoft/colima) c параметрами `colima start --arch aarch64 --vm-type=vz --vz-rosetta`;
```

2024-11-27 08:45 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      - [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/) установите и включите Rosetta 2.
```suggestion
      - [Docker Desktop](https://docs.docker.com/desktop/setup/install/mac-install/) с установленной и включённой Rosetta 2.
```

2024-11-27 09:54 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
>        Если контейнер успешно запустился, вы увидите его идентификатор. Контейнеру может потребоваться несколько минут для инициализации. База данных будет недоступна до окончания инициализации.
```suggestion
      Если контейнер успешно запустился, вы увидите его идентификатор. Контейнеру может потребоваться несколько секунд для инициализации. База данных будет недоступна до окончания инициализации.
```

2024-11-27 09:55 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      В настоящее время сохранение данных на диск поддерживается только на x86_64 процессорах. Чтобы отключить сохранение данных на диск и сделать все данные волатильными, хранящимися только в операт
```suggestion
      В настоящее время сохранение данных на диск поддерживается только на x86_64 процессорах. Чтобы отключить сохранение данных на диск и сделать все данные волатильными, хранящимися только в оперативной памяти, добавьте в команду запуска Docker-контейнера параметр `-e YDB_USE_IN_MEMORY_PDISKS=true`.
```

2024-11-27 09:57 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      Если вы не хотите отключать сохранение данных на диск при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64 с помощью одной из следующ
```suggestion
      Если вы не хотите отключать сохранение данных на диск при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64, используя технологию виртуализации rozetta:
```

2024-11-27 09:58 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      Если вы не хотите отключать сохранение данных на диск при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64 с помощью одной из следующ
Можно ссылкой сделать розетту

2024-11-27 12:39 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      В настоящее время сохранение данных на диск поддерживается только на x86_64 процессорах. Чтобы отключить сохранение данных на диск и сделать все данные волатильными, хранящимися только в операт
```suggestion
      В настоящее время сохранение данных на диск поддерживается только на x86_64 процессорах.
      Чтобы отключить сохранение данных на диск и сделать все данные волатильными, хранящимися только в оперативной памяти, добавьте в команду запуска Docker-контейнера параметр `-e YDB_USE_IN_MEMORY_PDISKS=true`.
```

2024-11-27 12:41 UTC, asmyasnikov commented on ydb/docs/ru/core/quickstart.md
> +      Если вы не хотите отключать сохранение данных на диск при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64, используя технологию вирт
```suggestion
      Альтернативно вы можете при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64, используя технологию виртуализации [Rosetta](https://support.apple.com/en-us/102527):
```

2024-11-29 06:31 UTC, fomichev3000 approved these changes, later dismissed

2024-12-02 11:11 UTC, anton-bobkov commented on ydb/docs/ru/core/quickstart.md
> +      В ином сучае, при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64, используя технологию виртуализации [Rosetta](https://support.appl
```suggestion
      В ином случае, при запуске контейнера Docker на Mac с процессором Apple Silicon, необходимо эмулировать набор инструкций x86_64, используя технологию виртуализации [Rosetta](https://support.apple.com/en-us/102527):
```

2024-12-03 07:29 UTC, blinkov approved these changes

2024-12-03 07:29 UTC, merged