Add changelog of YDB 23.3.17 release.
ydb-platform/ydb pull request #1153
Opened 2024-01-19 10:55 UTC by Pseudolukian

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-19 12:21 UTC, dcherednik requested changes

2024-01-19 12:21 UTC, dcherednik commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлено ошибочное разрешение совместимости между нестабильными версиями различных приложений.
```suggestion
* Исправлены проблемы совместимости с танком
```

2024-01-19 12:21 UTC, dcherednik commented on ydb/docs/ru/core/changelog-server.md
> +* Улучшена стабильность работы `segfault`, балансировщика и событий очереди загрузки в  `StateInit`.
```suggestion
* Исправлены проблемы влияющие на стабильность работы
```

2024-01-19 12:21 UTC, dcherednik commented on ydb/docs/ru/core/changelog-server.md
> +* Устранена перегрузка лога сообщениями от даташарда.
```suggestion
* Устранена излишнее логирование  даташарда. 
```

2024-01-19 12:21 UTC, dcherednik commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены «ленивые гистограммы» для grpc запросов.
```suggestion
* Добавлены гистограммы времени выполнения grpc запросов.
```

2024-01-19 12:21 UTC, dcherednik commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены ANSI-настройки для общего запроса.
```suggestion
* Добавлены ANSI-настройки для обобщенного интерфейса выполнения запроса
```

2024-01-19 12:41 UTC, Pseudolukian commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлено ошибочное разрешение совместимости между нестабильными версиями различных приложений.
Исправил

2024-01-19 12:42 UTC, Pseudolukian commented on ydb/docs/ru/core/changelog-server.md
> +* Улучшена стабильность работы `segfault`, балансировщика и событий очереди загрузки в  `StateInit`.
Учёл

2024-01-19 12:45 UTC, Pseudolukian commented on ydb/docs/ru/core/changelog-server.md
> +* Устранена перегрузка лога сообщениями от даташарда.
Учёл.

2024-01-22 12:01 UTC, antonkovalenko requested changes

2024-01-22 12:01 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлены проблемы влияющие на стабильность работы.
По-моему лишняя фраза

2024-01-22 12:04 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Fix `InFlightTxCount` become negative during `split/merge`.
```suggestion
* Fix `InFlightTxCount` metric becoming negative during datashard split and merge.
```

2024-01-22 12:05 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Various stability improvements (`segfault`, handle balancer and boot queue events in `StateInit`, data race when reporting issue counters, memory leak in TRopeArena).
split items in round brackets into separate bullet points

2024-01-22 12:05 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* CPU over utilization in case of numerous topic consumers.
```suggestion
* CPU overutilization in case of numerous topic consumers.
```

2024-01-22 12:06 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Fix import multiple converted csv columns.
isn't it about CLI?

2024-01-22 12:06 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Fix mem table merge when writing over committed deltas in tablets.
```suggestion
* Fix memtable merge when writing over committed deltas in tablets.
```

2024-01-22 12:07 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Fix mem table merge when writing over committed deltas in tablets.
it's not clear how severe this is — were merges before the fix leading to incorrect data stored and responded?

2024-01-22 12:09 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +**Features:**
why there are so many features on a minor release?

2024-01-22 12:11 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* DML logging.
is this about audit logging? and is it enabled by default?

2024-01-22 12:12 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Grpc KV api.
what about it?

2024-01-22 12:12 UTC, blinkov commented on ydb/docs/en/core/changelog-server.md
> +* Pqv0 support on server side.
what it is?

2024-09-17 04:51 UTC, blinkov commented
This seems to be added in some other PR: https://ydb.tech/docs/en/changelog-server#23-3

2024-09-17 04:51 UTC, closed without merging