Stop writing to column tables if quota is exceeded
ydb-platform/ydb pull request #11580
Opened 2024-11-13 17:51 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-25 04:32 UTC, zverevgeny requested changes

2024-11-25 08:57 UTC, aavdonkin commented on ydb/core/tx/schemeshard/olap/operations/create_store.cpp
> +                if (const ui64 subDomainPathId = context.SS->ResolvePathIdForDomain(txState->TargetPathId).LocalPathId) {
Точно не знаю, просто скопировал отсюда https://a.yandex-team.ru/arcadia/contrib/ydb/core/tx/schemeshard/schemeshard__operation_create_table.cpp?rev=r15380196#L223

2025-01-30 07:49 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
> +                ui64 subDomainPathId = record.GetSubDomainPathId();
Сначала нужно проверить на HasSubDomainPathId

2025-01-30 07:56 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    const bool OutOfSpace = false;
значение по-умолчанию тут лишнее. Без него мембер должен быть обязательно проинициализирован в конструкторе, что даёт больший контроль

2025-01-30 08:04 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +            Self->PersistSubDomainPathId(SchemeShardId, LocalPathId, txc);
Какой смысл выносить это в отдельную функцию?

2025-01-30 08:09 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +        if (Self->CurrentSchemeShardId == SchemeShardId &&
Зачем такая проверка. SubDomainPathId может поменяться в процессе жизни таблицы?

2025-01-30 08:11 UTC, zverevgeny commented on ydb/core/tx/schemeshard/olap/operations/create_store.cpp
> +                if (const ui64 subDomainPathId = context.SS->ResolvePathIdForDomain(txState->TargetPathId).LocalPathId) {
Там оно могло появиться по каким-то причинам, которые сейчас уже невозможны

2025-01-30 08:13 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
> +                if (subDomainPathId) {
чем нулевое значение отличается от отсутствующего?

2025-01-30 09:28 UTC, aavdonkin commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +            Self->PersistSubDomainPathId(SchemeShardId, LocalPathId, txc);
В DataShard сделано отдельной функцией, сделал тут также

2025-01-31 16:13 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__write.cpp
> +        AFL_WARN(NKikimrServices::TX_COLUMNSHARD)("event", "skip_writing")("reason", "quota_exceeded")("source", "dataevent");
Почему quota_exceeded? Тут же могут быть статусы, возвращенные. CheckOverloadedImmediate

2025-01-31 16:16 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__write.cpp
>          std::unique_ptr<NActors::IEventBase> result = NEvents::TDataEvents::TEvWriteResult::BuildError(
в TEvWriteResult есть оцпия STATUS_DISK_SPACE_EXHAUSTED = 10. Можно посмотреть в DS, какой они флаг возвращают при разных ошибках

2025-01-31 16:51 UTC, aavdonkin commented on ydb/core/tx/columnshard/columnshard__write.cpp
>          std::unique_ptr<NActors::IEventBase> result = NEvents::TDataEvents::TEvWriteResult::BuildError(
https://a.yandex-team.ru/arcadia/contrib/ydb/core/tx/datashard/check_write_unit.cpp?rev=r15804741#L68
Возвращает Overloaded

2025-01-31 18:09 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +        CurrentSchemeShardId != 0 &&
Возможен ли CurrentSchemeShardId равный 0? Как в этом случае будет искаться SubDomainPathId?

2025-01-31 18:14 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    AFL_DEBUG(NKikimrServices::TX_COLUMNSHARD)("event", "subdomain_found")("scheme_shard_id", msg->SchemeShardId)("local_path_id", msg->LocalPathId);
Это же разовое событие в жизни шарда, как я понял. Можно и на info уровне затрейсить

2025-01-31 18:27 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_impl.h
> +    std::optional<TPathId> SubDomainPathId;
Зачем сохранять полный TPathId? Идентификатор SchemeShard'a же уже есть  выше

2025-02-03 14:24 UTC, aavdonkin commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +        CurrentSchemeShardId != 0 &&
Я убрал условие и много тестов стало падать.

2025-02-05 08:02 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__write.cpp
> +    const auto returnFail = [&](const NColumnShard::ECumulativeCounters signalIndex, const EWriteFailReason reason, NKikimrTxColumnShard::EResultStatus resultStatus = NKikimrTxColumnShard::EResultSta
Предлагаю убрать параметр по-умолчанию. Кажется, лучше явно указывать статус

2025-02-05 08:05 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__write.cpp
>          std::unique_ptr<NActors::IEventBase> result = NEvents::TDataEvents::TEvWriteResult::BuildError(
На каналах - согласен. А при исчерпании квоты?

2025-02-05 08:07 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard__write.cpp
> +        if (outOfSpace) {
Выглядит нелогично. Почему тут, а не сразу после вычисления outOfSpace? Почему для  outOfSpace есть трейсинг, а для других причин нет?

2025-02-07 12:47 UTC, zverevgeny commented on ydb/core/tx/columnshard/loading/stages.cpp
> +    if (subDomainLocalPathId.has_value()) {
Зачем такое двухэтапное перекладывание?

2025-02-07 13:21 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    if (SubDomainPathId && msg->PathId.LocalPathId == *SubDomainPathId) {
Как мы можем получить это сообщение при неизвестном SubDomainPathId?

2025-02-11 18:25 UTC, dorooleg commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    if (!FindSubDomainPathIdActor &&
Меня смущает что в datashard более строгие проверки в этом месте. Например там проверяют соотвествие owner. https://a.yandex-team.ru/arcadia/contrib/ydb/core/tx/datashard/datashard_subdomain_path_id.cpp?blame=true&rev=r15878989#L20-23

Я бы предложил прояснить у snaury например этот момент с owner

2025-02-13 11:13 UTC, aavdonkin commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    if (!FindSubDomainPathIdActor &&
Вот по этому поводу с Женей договоритесь, проверка раньше была, я ее убрал

2025-02-13 11:16 UTC, aavdonkin commented on ydb/tests/functional/serverless/test_serverless.py
> +#        with pytest.raises(ydb.Overloaded, match=r'.*Cannot write data into shard.*'):
С другим issue тест не проходит

2025-02-13 11:18 UTC, aavdonkin commented on ydb/tests/functional/serverless/test_serverless.py
> +        'disabled_on_scheme_shard': False,
Потому что флаг определен тут https://a.yandex-team.ru/arcadia/contrib/ydb/core/protos/config.proto?rev=r15893648#L1790

2025-02-13 14:21 UTC, zverevgeny commented on ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
> +    if (!FindSubDomainPathIdActor &&
Саша, ты же тоже знаешь ответ. Код в даташарде - это последствия пережитой миграции, когда даташарды переносились в тенатный скимшард. Код был написан под эту миграцию и потом его никто не удалял. В новый код нет смысла это тянуть

2025-02-13 14:25 UTC, dorooleg commented on ydb/tests/functional/serverless/test_serverless.py
> +        'disabled_on_scheme_shard': False,
У меня тут больше организационный вопрос, какая стратегия добавления флагов? Кому как нравится так и раскидывают флаги или есть логическое объединение?

2025-02-13 15:42 UTC, aavdonkin commented on ydb/tests/functional/serverless/test_serverless.py
> +        'disabled_on_scheme_shard': False,
Этого я точно не знаю, флаг же добавлял не я, а он уже был

2025-02-18 10:39 UTC, dorooleg approved these changes, later dismissed

2025-02-20 10:15 UTC, zverevgeny commented
Нужно содержательно описание изменений

2025-02-20 12:07 UTC, zverevgeny commented on ydb/tests/functional/serverless/test_serverless.py
> +        'disabled_on_scheme_shard': False,
> У меня тут больше организационный вопрос, какая стратегия добавления флагов? Кому как нравится так и раскидывают флаги или есть логическое объединение?

При разработке новой фичи, её нужно всегда закрывать фиче флагом в TFeatureFlag.
Так что этот правильно было бы тоже положить в TFeatureFlag

2025-02-27 08:52 UTC, dorooleg submitted a review, later dismissed

2025-02-27 16:05 UTC, zverevgeny commented on ydb/core/tx/schemeshard/olap/operations/create_table.cpp
> +                const ui64 subDomainPathId = context.SS->ResolvePathIdForDomain(txState->TargetPathId).LocalPathId;
@ijon как на твой взгляд более правильно? Передавать явно или полагаться на резолв в шарде Код для резолва, всё равно, нужен

2025-02-28 18:06 UTC, ijon requested changes

2025-03-04 10:19 UTC, ijon requested changes

2025-03-04 10:19 UTC, ijon commented on ydb/core/tx/columnshard/columnshard.h
> +                ui64 txId, TString txBody, const ui32 flags = 0, ui64 subDomainPathId = 0)
`subDomainPathId` нужен как пара к `ssId`. Отдельно от `ssId` он не нужен. И оба они нужны только, если `txKind = NKikimrTxColumnShard::TX_KIND_SCHEMA`.

То есть варианты ctor `TEvProposeTransaction` для других `txKind` не должны принимать ни `subDomainPathId`, ни `ssId`.

2025-03-04 10:19 UTC, ijon commented on ydb/core/tx/columnshard/columnshard.h
> +                ui64 txId, TString txBody, const ui32 flags = 0, ui64 subDomainPathId = 0)
`ssId` и `subDomainPathId` есть нераздельная пара -- либо оба есть, либо обоих нет, default значений нет ни у того, ни у другого, в event добавляются одновременно оба.

Эта версия ctor должна принимать оба, без default, в event должны добавляться оба.

2025-03-04 10:19 UTC, ijon commented on ydb/core/tx/columnshard/columnshard.h
> +            ui64 txId, TString txBody, const TMessageSeqNo& seqNo, const NKikimrSubDomains::TProcessingParams& processingParams, const ui32 flags = 0, ui64 subDomainPathId = 0)
У `subDomainPathId` не должно быть default-значения.

2025-03-05 13:58 UTC, ijon approved these changes

2025-03-05 14:00 UTC, zverevgeny approved these changes

2025-03-05 14:00 UTC, merged