date data type formatting added
ydb-platform/ydb pull request #11608
Opened 2024-11-14 13:37 UTC by evanevanevanevannnn

### Changelog entry 

fix for [YQ-2950](https://st.yandex-team.ru/YQ-2950)

### Changelog category 

* Improvement

2024-11-14 21:55 UTC, dorooleg requested changes

2024-11-14 21:55 UTC, dorooleg commented on ydb/library/yql/providers/s3/provider/yql_s3_datasink_type_ann.cpp
> +                if (name == "data.date.format") {
Для parquet не дописана часть кода: https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.cpp#L557

2024-11-14 21:55 UTC, dorooleg commented on ydb/tests/fq/s3/test_format_settings/date/simple/test.parquet
Оказалось не удобным генерировать parquet файлы из вне. Посмотри в сторону этих тестов https://github.com/ydb-platform/ydb/blob/main/ydb/tests/fq/s3/test_format_setting.py#L1052 Это уже новые тесты которые удобно писать и читать

2024-11-14 21:55 UTC, dorooleg commented on ydb/library/yql/providers/pq/provider/yql_pq_datasource.cpp
> +        if (topicKeyParser.GetDateFormat()) {
А здесь для date нету общееизвестных форматов POSIX/ISO как для Timestamp?

2024-11-14 21:55 UTC, dorooleg commented on ydb/library/yql/udfs/common/clickhouse/client/src/IO/ReadHelpers.cpp
> +    auto ptr = strptime(buf.position(), format.c_str(), &input_tm);
А нету другой функции которая бы сразу date бы проверяла? А то потом идут различные преобразования + 1900. Там никаки overflow быть не может? Еще не понятно почему mon на 1 сдвигается

2024-11-14 21:55 UTC, dorooleg commented on ydb/library/yql/udfs/common/clickhouse/client/src/IO/ReadHelpers.h
> +    /// When the parameter is out of rule or out of range, Date32 uses 1925-01-01 as the default value (-DateLUT::instance().getDayNumOffsetEpoch(), -16436) and Date uses 1970-01-01.
А мы точно хотим такое поведение? Может тут ошибку нужно выдавать. В Datetime какое поведение сейчас?

2024-11-14 21:55 UTC, dorooleg commented on ydb/tests/fq/s3/test_format_setting.py
> +            INSERT INTO bindings.`{storage_sink_binding_name}`
Можешь попробовать прочитать то что записали и провалидировать результат?

2024-11-15 07:37 UTC, evanevanevanevannnn commented on ydb/tests/fq/s3/test_format_setting.py
> +            INSERT INTO bindings.`{storage_sink_binding_name}`
насколько я понимаю данные сравниваются с каноничными

2024-11-15 07:38 UTC, evanevanevanevannnn commented on ydb/library/yql/udfs/common/clickhouse/client/src/IO/ReadHelpers.h
> +    /// When the parameter is out of rule or out of range, Date32 uses 1925-01-01 as the default value (-DateLUT::instance().getDayNumOffsetEpoch(), -16436) and Date uses 1970-01-01.
в datetime не помню, но в этом же файле для date и date32 (просто без настроек формата) идентичное поведение

2024-11-15 07:40 UTC, evanevanevanevannnn commented on ydb/library/yql/udfs/common/clickhouse/client/src/IO/ReadHelpers.cpp
> +    auto ptr = strptime(buf.position(), format.c_str(), &input_tm);
не нашел функции, которая сразу в LocalDate/DayNum сможет распарсить согласно формату

преобразования такие потому что в struct tm нумерация месяцев с 0, а лет с 1900. а в LocalDate соответственно с единицы и нуля

2024-11-15 07:43 UTC, evanevanevanevannnn commented on ydb/library/yql/providers/pq/provider/yql_pq_datasource.cpp
> +        if (topicKeyParser.GetDateFormat()) {
POSIX/ISO для даты выглядят одинакого - %Y-%m-%d

по совместительству это совпадает с дефолтным парсингом, поэтому показалось бессмысленно добавлять несколько одинаковых форматов

2024-11-15 08:48 UTC, evanevanevanevannnn commented on ydb/library/yql/providers/s3/provider/yql_s3_datasink_type_ann.cpp
> +                if (name == "data.date.format") {
дописал

2024-11-15 16:16 UTC, dorooleg approved these changes

2024-11-15 19:39 UTC, merged