YQ-3847 RD support regexp pushdown
ydb-platform/ydb pull request #11626
Opened 2024-11-14 17:45 UTC by GrigoriyPA

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-14 18:17 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +    if (settings.IsEnabled(TSettings::EFeatureFlag::RegexpOperator) && TStringBuf(udf.MethodName()) == "Re2.Grep"sv) {
Делай быстрый return

2024-11-14 18:18 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
На самом деле тут пушдаунится удф, более общий механизм. Можем его поддержать в общем случае?

2024-11-14 18:18 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Списки надо передавать по ссылке. Амперсанд забыл?

2024-11-14 18:19 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +            // Expected exactly one argument
Ты же с двойкой сравниваешь. Это означает один или два аргумента?

2024-11-14 18:19 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +            // Expected non empty predicate
Тут не про предикат должно быть, а про runConfig

2024-11-14 18:24 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool CheckExpressionNodeForPushdown(const TExprBase& node, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Для консистентности я бы сделал одинаковые типы у аргументов. TExprBase/TExprNode давай выберем один тип?

2024-11-14 18:26 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
В этом месте просто происходит проверка, можно ли запушдаунить (ничего ценного кроме true/false по итогу не возвращается), в общем случае надо будет просто сюда дописать ещё Udf разных (по аналогии с этим if):
https://github.com/ydb-platform/ydb/blob/5c050215cea1300260e465b60a36ee936111c59b/ydb/library/yql/providers/common/pushdown/collection.cpp#L581

2024-11-14 18:27 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +            // Expected exactly one argument
Это означает один аргумент, так как первый children это сама udf)

2024-11-14 18:28 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +            // Expected non empty predicate
Окей, поправлю

2024-11-14 18:29 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool CheckExpressionNodeForPushdown(const TExprBase& node, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Эти типы приехали из основной функции:
https://github.com/ydb-platform/ydb/blob/5c050215cea1300260e465b60a36ee936111c59b/ydb/library/yql/providers/common/pushdown/collection.cpp#L652

Если менять, то придётся менять везде, точно нужно?

2024-11-14 18:32 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +    if (settings.IsEnabled(TSettings::EFeatureFlag::RegexpOperator) && TStringBuf(udf.MethodName()) == "Re2.Grep"sv) {
Тут была идея, что можно будет под первым if ещё дописывать, или пока лучше убрать этот внешний if?

2024-11-14 18:35 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Но флаг у тебя не про удф, а regexp. Нужно понять как его обобщить для всех ydb удф

2024-11-14 18:36 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool CheckExpressionNodeForPushdown(const TExprBase& node, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Как хочешь. Просто разные и похожие типы бросаются в глаза

2024-11-14 18:37 UTC, GrigoriyPA commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Я думал добавлять по флагу на каждую udf, но можно и сделать просто список имён поддерживаемых udf, чтобы не плодить флаги

2024-11-14 18:37 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +            // Expected exactly one argument
Не очевидно из кода. Ну да ладно

2024-11-14 18:37 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +    if (settings.IsEnabled(TSettings::EFeatureFlag::RegexpOperator) && TStringBuf(udf.MethodName()) == "Re2.Grep"sv) {
Тогда и так норм

2024-11-14 18:38 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/collection.cpp
> +bool UdfCanBePushed(const TCoUdf& udf, const TExprNode::TListType children, const TExprNode* lambdaArg, const TExprBase& lambdaBody, const TSettings& settings) {
Можно завести список разрешенных удф. В твоем случае это будет re2::grep

2024-11-14 18:41 UTC, uzhastik commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +        TExpression then_expression = 2;
Суффикс _expression у имен полей смущает. Вокруг не вижу такого нейминга. Нельзя без суффикса назвать?

2024-11-14 18:42 UTC, uzhastik commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +        TExpression then_expression = 2;
Хотя вот вижу         TArithmeticalExpression arithmetical_expression

но оно тоже выбивается из стиля соседей

2024-11-14 18:53 UTC, GrigoriyPA commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +        TExpression then_expression = 2;
Этот суффикс взял по аналогии отсюда:
https://github.com/ydb-platform/ydb/blob/5c050215cea1300260e465b60a36ee936111c59b/ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto#L395-L399

Могу в обоих местах поменять на then_value и else_value

2024-11-15 09:59 UTC, kardymonds submitted a review, later dismissed

2024-11-15 10:15 UTC, vitalyisaev2 requested changes

2024-11-15 10:15 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +// Expression with value (any type expression)
Можно уточню, что имеется в виду? м.б. `(value can be expression of any type)`?

2024-11-15 10:31 UTC, vitalyisaev2 requested changes

2024-11-15 10:31 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +// Predicate (exactly bool expression)
Этот комментарий тоже можно было бы чуть больше расписать, в духе "use this types only for ..."

2024-11-15 10:31 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +    // "IF($predicate, $then_expression, $else_expression)"
я бы сюда добавил конкретный пример запроса (ты в ТГ его приводил). Аналогично и для симметричного типа в `TPredicate`

2024-11-15 10:34 UTC, GrigoriyPA commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +// Expression with value (any type expression)
Да, это имелось ввиду, сейчас исправлю

2024-11-15 10:34 UTC, GrigoriyPA commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +    // "IF($predicate, $then_expression, $else_expression)"
Окей, допишу

2024-11-15 10:35 UTC, GrigoriyPA commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +// Predicate (exactly bool expression)
Заменю комментарий на `(use this types only for bool expressions)`

2024-11-15 10:42 UTC, vitalyisaev2 approved these changes

2024-11-15 19:05 UTC, dorooleg commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +                err << "expected exactly one argument for UDF Re2.Grep, but got: " << children.size() - 1;
for UDF function?

2024-11-15 19:05 UTC, dorooleg approved these changes

2024-11-15 20:13 UTC, GrigoriyPA commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +                err << "expected exactly one argument for UDF Re2.Grep, but got: " << children.size() - 1;
Потом исправлю, сейчас просто чеки добежали, выглядит не очень критично (этой ошибки пользователь не видит)

2024-11-15 20:13 UTC, merged