YQ-3869 RD added limit for parser buffer size
ydb-platform/ydb pull request #11627
Opened 2024-11-14 17:48 UTC by GrigoriyPA

- **YQL-19206: Move contrib/ydb/library/yql/tools/pg* to yql/essentials/tools/pg***
- **YT-21709: Support parent transactions in shuffle service commit_hash:2d3b5fbd4263578e773706ad3c401e3f605424da**
- **YT-23294: Recreate terminated federated clients**
- **YQL-19206: Move contrib/ydb/library/yql/tools/ to yql/essentials/tools/**
- **YT-23262: send all logs to file commit_hash:af0cfccef62a612208772fef9f0778b48ab16fda**
- **Move yql/udfs/examples/ to /yql/essentials YQL-19206 commit_hash:113d16e05a8df9e2b767e045adff661892f03ef1**
- **Cleanup utils/signals dependencies commit_hash:11028e9e13bad8c1fbed21ac7dac0634867b9aae**
- **YT-23303: Introduce IBoundedConcurrencyInvoker to postpone the usage of TTaggedInterface commit_hash:2b488e7fd8dc3193de4e1528fea5904a631ce6be**
- **Moved yql/public/decimal YQL-19206**
- **Moved yql/core/issue YQL-19206**
- **Moved yql/parser (w/o pg_wrapper) & yql/protos YQL-19206**
- **Moved yql/core/{credentials,file_storage,pg_ext,pg_settings,sql_types,url_lister/interface,url_preprocessing/interface,user_data} YQL-19206**
- **YT-22885: Refactor checked casts commit_hash:7f7600d332c3ddb5c8372e921bcba3b4fbed68f8**
- **Moved yql/public/udf YQL-19206**
- **YT-22885: Mark EWorkloadCategory::UserBatch as the unknown value commit_hash:421040e8ef380526af2d10fd7fb94c5a1d33b42d**
- **YT-22885: Mark EMultiplexingBand::Default as the unknown value commit_hash:4dccd3176558f66e56b2792b5899348cf382c100**
- **fix DEFAULT_JDK_VERSION macro commit_hash:adb862030ba6789e6f89c32f1284455c80523ada**
- **Intermediate changes commit_hash:930e763f0eed288461ef988c2ae9cc7d6cd6ab0c**
- **add ::element_type, .get() to smart pointers for better compatibility with std**
- **Add one more flag for emitting raw compiler command commit_hash:4efcaf7f1961121b1bc9b4aa81ec6d3a606d1d86**
- **Add per-band options for rpc bus connection parallelism**
- **New version of the tld SKIP_CHECK SKIP_REVIEW commit_hash:95cd91e635cd58d38f4e69396d9d6d2201f1946b**
- **YT-23122: Ping replication card residency cache during long polling. Trivial: address cosmetics commit_hash:cff5c3c98e26af991a486f95d353b78dfddb90b8**
- **Automatic release build for ymake, os_ymake**
- **Automatic release build for test_tool, ya_bin, os_ya, os_test_tool**
- **conf(TS_PROTO): USE_COMMON_GOOGLE_APIS and GENERATE_ENUM_SERIALIZATION support commit_hash:075ec32949fbb4ade99a9d4bcae8277def215b10**
- **YQL-19206: Move contrib/ydb/library/yql/tools/udf* to yql/essentials/tools/udf***
- **YT-21942: Adjustments to adaptive row count feature**
- **Fix codestyle commit_hash:4ee7ce0c078b8a895149d4020f0c3e7a1a5d8443**
- **[phoenix2] Do not serialize fields, whose InVersion filter does not match latest version commit_hash:9f8f12afe3d5ab1d3d6d4cfb597ddf02b1a98d57**
- **Intermediate changes commit_hash:106573bba02cd05283557959815f7eba87c491bd**
- **Intermediate changes commit_hash:bf7fd863f4c2257a633040a372a08b08265979a5**
- **Auto-deduce proto type in ToProto commit_hash:eb7865a6eb9af2cbae2d6b30f8027c74ad5a7f0a**
- **Intermediate changes commit_hash:1c8f88b066e72203285d006adc5b0d6fd77191f5**
- **Intermediate changes commit_hash:fa9cb13adebcd335794779a600c4d88ad1af00d4**
- **Add dependency on yql/essentials/public/result_format commit_hash:eab298355ae23e40ee62960d2c1a55bb35b7be3f**
- **Move yql/udfs/logs/ to /yql/essentials YQL-19206 commit_hash:7137f6ca04c4afa838eea547ba246547f4442724**
- **Fix "unexpected multicommand substitution" commit_hash:4bda7757107238220a00359914631ba9fc072294**
- **Fix "unexpected multicommand substitution" commit_hash:3c3ca729265d3ad1fed8fa482a15a160a461c75c**
- **Kickstart backoff executor commit_hash:f596bd134368bdf312eed4c5f3a9247fb3af9f65**
- **[libray/cpp/threading] Fix typo commit_hash:f76f3edfa160fba90d0f8d594211fa35c6eb6077**
- **Extracted core deps from yql/sql**
- **Update contrib/libs/nghttp2 to 1.64.0 commit_hash:229e82d21a5e93c864b79c5d00a5ce331f8ab3ef**
- **Cosmetics: CodeKeyCannotBeNan -> CodeKeyCannotBeNaN commit_hash:538657f4deee1537625022d71a8beb2485f0ab05**
- **Update YFM for ya make to latest version**
- **Fix incoming request profiling: increment counters even for non-accepted requests (2nd attempt) commit_hash:202ccff8f8d6833ffea6c63601d15c37c56d802a**
- **Fix serializing error's host commit_hash:e02881e5d901f7cba312d6859f9fc2bed5905e48**
- **Intermediate changes commit_hash:d313ff8d16f964d796106f71b9e2d65b0ea39f82**
- **Remove methods Data, Size, Empty from TString**
- **Remove forgotten feature switch: YMAKE_JAVA_TEST commit_hash:baacdf6da887ea8415dfcc2d6d7063388b7c7aee**
- **Moved yql/ast YQL-19206**
- **Update contrib/restricted/boost/asio to 1.81.0 commit_hash:831bd28098493bc44ccb221464203e928703d3f4**
- **NaN-safe comparison and hashing commit_hash:46d59ab3acbd313753d3e46f3a6f10a8ebc424d8**
- **Better diagnostics in AbortProcess(Silently|Dramatically) commit_hash:7bbc13afbd569ca9bb064aed656c12644fd2de96**
- **[unified-agent] add config endpoint to agent commit_hash:f617f0a99f254f9100cea5bb7c2adaa30ae2038d**
- **Intermediate changes commit_hash:6acc1b14a2c86ce4c930ba3a10be20ad289fb18d**
- **Prepare move yql/minikql YQL-19206**
- **Moved yql/minikql YQL-19206**
- **Revert commit rXXXXXX,Extract Go lib version from yo**
- **User-freindly error on pom.xml parse error in java macroses**
- **Delete temporary alias for clang-format config**
- **Intermediate changes commit_hash:8dfe46ba3b02673d0e6a35fdf824ab2c98255393**
- **Update contrib/restricted/boost/asio to 1.82.0 commit_hash:6f5e0002557289d16812809c88c0756d4775bd44**
- **YT-23266: Fix skip unknown fields commit_hash:74f3a55474c94110d8a379b1a2d2f75499ea737a**
- **Moved other yql/essentials libs YQL-19206**
- **Update YFM for ya make to latest version**
- **Move yql/udfs/test/ to /yql/essentials YQL-19206 commit_hash:cdc59617409c3a4fbd6d01670cae7cb39e979340**
- **Fix batch Invoke for suspendable invoker commit_hash:87fc98c02115686ae005e61f7a0c0076ed811ba7**
- **Extract TAsyncExpiringCache::Erase helper to always clear probation cookie commit_hash:84008f71594abd4c8cc1bf3cd0e2539ce2fafe4a**
- **add cryptopro to contrib commit_hash:4751d34075303cff480b8254768e3aa9d6d66e7d**
- **YT-23387: Sort jobs by task name commit_hash:eada58f1baf8c66541a6f4874a10034bd1a0632a**
- **Intermediate changes commit_hash:9bfb47a7e0e620e73e08f0615965c1dc9ce9d82d**
- **YT-23048: Fix data race in tls between the end of read/write and calls to IsIdle commit_hash:f0665a78b31b5c729b9cd09cfe30b33593e755a0**
- **Split ydb deps from providers/common/mkql YQL-19206**
- **Release mold #1**
- **Enable mold linker only under flag commit_hash:88f3c9f91eafb63005672effecfca95cd50444b5**
- **Intermediate changes commit_hash:60899e5485353c0a9944b5b350a809189ccab674**
- **Minimize dependency on YDB's TRope commit_hash:e3b74d6e744bd014dc1fa0f41053fe886f7f4a49**
- **Update contrib/restricted/boost/asio to 1.83.0 commit_hash:446591731b6d2e1a84e00faebd59f2706866b6e1**
- **Log ExpandApply commit_hash:9b64eca2089a7ed37bdbae5eb5dad6b8e7c87d8d**
- **Quantize large delays in Delayed Executor to reduce the number of wakeups commit_hash:ef8d1733d0190bbb4988a71171e0a22777ff28c8**
- **fix: duplicate peers block node_modules pack/unpack**
- **New version of the tld SKIP_CHECK SKIP_REVIEW commit_hash:ee52a32ff7f9601d2ea879be7d0bb07d0fe0f5b6**
- **Intermediate changes commit_hash:b029461eab3edbc697836a436c182ef54d9048a9**
- **Move yql/udfs/common/ to /yql/essentials YQL-19206**
- **YT-23262: initialize client with JoblessInitialize if user didn't commit_hash:439622e771e7b7010609aa9974e9b82dcb0163ca**
- **Import libraries 241108-0852**
- **wip**
- **[udf] Datetime::Format is not strict commit_hash:e7deb73902788e8e694c8da7719f9c7a4e77f698**
- **fix ci base image build**
- **manual merge**
- **Intermediate changes commit_hash:b75c4510058a45b92316d448f6ac2dc21963b920**
- **Support customization of TLockOps for TGuard in TConcurrentHashMap commit_hash:ea73897466c683c4f852d5c9b6eebee419e6b8ab**
- **Delete deleted**
- **fix**
- **ydb/library/yql/minikql fix**
- **ydb/library [...]

2024-11-14 18:26 UTC, uzhastik commented on ydb/core/fq/libs/config/protos/row_dispatcher.proto
> +    uint64 StaticBufferSize = 3;  // (number rows) * (number columns) limit, default 10^6 ~ 24 MiB
Связь между 10^6 и 24mib не ясна

2024-11-14 18:26 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +    const ui64 RowsOffset;  // ofset of first value
Опечатка в комментарии

2024-11-15 10:59 UTC, kardymonds approved these changes, later dismissed

2024-11-15 19:16 UTC, dorooleg requested changes

2024-11-15 19:16 UTC, dorooleg commented on ydb/core/fq/libs/config/protos/row_dispatcher.proto
> +    uint64 StaticBufferSize = 3;  // (number rows) * (number columns) limit, default 10^6
`StaticBufferItems`, Size как-то больше с байтами ассоцируется. А тут именно число элементов. Или `BufferCellCount`

2024-11-18 06:48 UTC, dorooleg approved these changes

2024-11-18 06:54 UTC, merged