Edited the Error Handling article
ydb-platform/ydb pull request #11695
Opened 2024-11-18 07:28 UTC by anton-bobkov

### Changelog category

* Documentation

### Additional information

Updated the Error handling article

2025-02-03 15:44 UTC, blinkov requested changes, later dismissed

2025-02-03 15:44 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/ydb-status-codes.md
> +Проанализировать подробное сообщение об ошибке и обратиться к разработчикам.
```suggestion
Запрос не поддерживается {{ ydb-short-name }}, либо потому, что обработка таких запросов ещё не реализована в данной версии {{ ydb-short-name }}, либо потому, что поддержка таких запросов не включена в конфигурации {{ ydb-short-name }}.

Исправьте запрос или включите поддержку подобных запросов в конфигурации {{ ydb-short-name }}.

<div class="tags_list">

## 400190: SESSION_BUSY {#session-busy}

{% include notitle [retryable-fastbackoff](./_includes/tags.md#retryable-fastbackoff) %}

</div>

Сессия занята.

Пересоздайте сессию.

<div class="tags_list">

## 400200: EXTERNAL_ERROR {#external-error}

{% include notitle [non-retryable](./_includes/tags.md#non-retryable) %}

</div>

Произошла ошибка во внешней системе, например, при обработке федеративного запроса или при импорте данных из внешнего источника.

Проанализируйте подробное сообщение об ошибке и обратитесь к разработчикам.
```

2025-02-03 15:44 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/ydb-status-codes.md
> +Проанализировать подробное сообщение об ошибке и обратиться к разработчикам.
проапрдейтить по аналогии с английской версией

2025-02-03 15:44 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/ydb-status-codes.md
> +[Questions and answers: Errors](../../faq/errors.md)
```suggestion
## Смотрите также

[{#T}](../../faq/errors.md)
```

2025-02-06 06:52 UTC, fomichev3000 approved these changes

2025-02-06 06:52 UTC, merged