Stock bench for Olap shards
ydb-platform/ydb pull request #11757
Opened 2024-11-19 14:20 UTC by nikvas0

### Changelog entry 

Allow running stock bench for Olap shards

### Changelog category 

* Improvement

2024-11-19 14:41 UTC, iddqdex requested changes

2024-11-19 14:56 UTC, nikvas0 commented on ydb/library/workload/stock/stock.cpp
> +        if (Params.TableType == "row") {
One of them uses secondary index.

2024-11-19 14:58 UTC, nikvas0 commented on ydb/library/workload/stock/stock.cpp
> +    if (Params.TableType == "row") {
One of them has not null keys (i'll rewrite it using std::format)

2024-11-20 12:44 UTC, iddqdex requested changes

2024-11-21 12:12 UTC, iddqdex approved these changes

2024-11-21 12:13 UTC, merged