Http restart query
ydb-platform/ydb pull request #11759
Opened 2024-11-19 15:27 UTC by what-the-fawk

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-20 11:10 UTC, dorooleg requested changes

2024-11-20 23:39 UTC, dorooleg requested changes

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/fq/libs/http_api_client/http_client.py
> +    def restart_query(
start_query

2024-11-20 23:39 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +        pass
лишний pass

2024-11-20 23:39 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +        c.wait_query_status(query_id, fq.QueryMeta.ABORTED_BY_USER)
Почему aborted_by_user, последний же start был

2024-11-20 23:39 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +            assert resp.status_code == 404s
404s, зачем s?

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            // новый тип события, по идее нужна новая фабрика
Комментарии должны быть на английском

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +    #define CheckTypedResponse(typedResponse, ResultType)                                                   \
Зачем макрос? Можно сделать функцию для этого?

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +class TRestartQueryRequest : public TGrpcCallWrapperBase {
TStartQueryRequest

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->set_state_load_mode(::FederatedQuery::StateLoadMode::FROM_LAST_CHECKPOINT);
Для аналитических запросов это будет работать?

2024-11-20 23:39 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->set_state_load_mode(::FederatedQuery::StateLoadMode::FROM_LAST_CHECKPOINT);
Давай тест сделаем

2024-11-22 18:05 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +    #define CheckTypedResponse(typedResponse, ResultType)                                                   \
Не понимаю, а где `this->Die()` и чем шаблонная функция не подходит? Чем макрос лучше в этом месте?

2024-11-22 18:07 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +        c.wait_query_status(query_id, fq.QueryMeta.ABORTED_BY_USER)
?

2024-11-22 18:17 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->set_state_load_mode(::FederatedQuery::StateLoadMode::FROM_LAST_CHECKPOINT);
А оно вообще работает? https://a.yandex-team.ru/arcadia/contrib/ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp?rev=r15375192#L768-770

2024-11-27 22:29 UTC, dorooleg commented on ydb/core/fq/libs/http_api_client/http_client.py
> +        response = self.session.get(
почему тут get? нужен post

2024-12-12 07:31 UTC, dorooleg requested changes

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +    void Bootstrap_wrapper(const TActorContext& ctx) override {
`Bootstrap_wrapper` -> `BootstrapWrapper` придерживайся общего стиля в файле

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/fq/libs/http_api_client/http_client.py
> +        idempotency_key: str | None = None,
request_id не хватает по аналогии с другими ручками

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +#include <thread>
Этот заголовочный файл точно нужен?

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +        if (!typedResponse->operation().result().template Is<TGrpcProtoResultType>()) {
почему тут изменения? Похоже на лишние пробелы в конце

2024-12-12 07:31 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +# import time
Лишняя строчка, нужно удалить

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +        TProtoStringType qid =  describeRequest->Getquery_id();
Вроде бы там есть про query_id, будет лакоинчнее выглядеть. Пример https://a.yandex-team.ru/arcadia/contrib/ydb/core/fq/libs/actors/rate_limiter_resources.cpp?rev=15513574#L76

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +        TIntrusivePtr<TGrpcRequestContextWrapper> requestContext = new TGrpcRequestContextWrapper(
`MakeIntrusive` вместо `new`

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            [query_id = std::move(qid), actorSystem = TActivationContext::ActorSystem()](const THttpRequestContext& requestContext, const TJsonSettings& jsonSettings, NProtoBuf::Message* resp, ui32 s
два разных стиля в коде `query_id` и ``qId`

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->Mutablecontent()->CopyFrom(describeResult->Getquery().content());
`*modifyRequest->mutable_content() = describeResult->query().content()`

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->set_allocated_disposition(nullptr);
можно убрать, он и так будет null

2024-12-12 07:31 UTC, dorooleg commented on ydb/core/public_http/fq_handlers.h
> +            modifyRequest->set_previous_revision(describeResult->Getquery().meta().Getlast_job_query_revision());
не та ревизия, нужно брать из query.meta()

2024-12-12 07:31 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +            # time.sleep(200)
Здесь тоже лишняя вместе с print("Starting")

2024-12-12 07:31 UTC, dorooleg commented on ydb/tests/fq/http_api/test_http_api.py
> +            # response2 = client.start_query(query_id)
а почему тут закоментированный код остался?

2024-12-13 10:43 UTC, what-the-fawk commented on ydb/core/public_http/fq_handlers.h
> +        TProtoStringType qid =  describeRequest->Getquery_id();
не нашел такого

2024-12-13 11:22 UTC, uzhastik commented on ydb/core/public_http/fq_handlers.h
> +#define TGrpcCallWrapperBase TGrpcCallWrapper<FederatedQuery::DescribeQueryRequest, FQHttp::GetQueryRequest, FederatedQuery::ModifyQueryResult, google::protobuf::Empty, FederatedQuery::ModifyQueryRes
давай уберем этот макрос. и на будущее - макросы обязательно именуем в верхнем регистре

2024-12-13 11:22 UTC, uzhastik commented on ydb/core/public_http/fq_handlers.h
> +        TProtoStringType query_id =  describeRequest->Getquery_id();
локальные переменные именуем в camelCasing:
```
TString queryId = ....;
```

2024-12-13 11:22 UTC, uzhastik commented on ydb/core/public_http/fq_handlers.h
> +            if(!typedResponse->operation().result().UnpackTo(&*describeResult)) {
после if ставим пробел

2024-12-13 11:22 UTC, uzhastik commented on ydb/core/public_http/fq_handlers.h
> +            actorSystem->Send(NGRpcService::CreateGRpcRequestProxyId(), std::move(factory)(std::move(requestContextModify)).release());
один std::move избыточен и вообще переменную factory вроде можно удалить

2024-12-13 11:22 UTC, uzhastik commented on ydb/core/public_http/http_service.cpp
> +            Router.RegisterHandler(HTTP_METHOD_POST, "/api/fq/v1/queries/{query_id}/start", CreateHttpHandler<TStartQueryRequest>());
давай согласованно назовем новый класс. уже есть TJsonStopQuery, новый класс можно назвать TJsonStartQuery

2024-12-13 11:22 UTC, uzhastik commented on ydb/tests/fq/http_api/test_http_api.py
> +            response = client.start_query(query_id)
нужно убедиться, что запрос повторно выполнился

2024-12-25 09:32 UTC, dorooleg approved these changes

2024-12-25 15:11 UTC, merged