Add deadline UTs for other Get variants
ydb-platform/ydb pull request #11780
Opened 2024-11-20 10:19 UTC by serbel324

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-26 17:42 UTC, alexvru requested changes

2024-11-26 17:42 UTC, alexvru commented on ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
> +        Schedule(TDuration::MilliSeconds(DsPutWakeupMs), new TKikimrEvents::TEvWakeup);
do we really need to wake up every 1 minute? to do what?

2024-11-26 17:42 UTC, alexvru commented on ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
> +        ScheduleWakeup();
there's no need to schedule anything if actor had passed away a line before

2024-11-26 17:42 UTC, alexvru commented on ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
> +                Schedule(deadline, new TKikimrEvents::TEvWakeup);
don't schedule for TInstant::Max()

2024-12-05 11:41 UTC, va-kuznecov commented on ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
> +    std::map<TInstant, ui64> PutDeadlineMasks;
https://en.cppreference.com/w/cpp/utility/bitset

```suggestion
    std::map<TInstant, std::bitset<MaxBatchedPutRequests>> PutDeadlineMasks;
```

2024-12-05 11:42 UTC, va-kuznecov commented on ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
> +    std::map<TInstant, ui64> PutDeadlineMasks;
please, don't add new asserts unless necessary

2024-12-05 14:19 UTC, va-kuznecov commented on ydb/core/blobstorage/ut_blobstorage/deadlines.cpp
> +    struct TTagPut {};
What are these Tags supposed to be used for?

You can create functions with the same naming system as well and get rid of the third(!) request type list of in this file

2024-12-12 07:24 UTC, alexvru submitted a review, later dismissed

2024-12-12 11:19 UTC, va-kuznecov requested changes

2024-12-12 11:19 UTC, va-kuznecov commented on ydb/core/blobstorage/ut_blobstorage/deadlines.cpp
> +        std::shared_ptr<TEnvironmentSetup> Env = nullptr;
```suggestion
        std::shared_ptr<TEnvironmentSetup> Env;
```

2024-12-12 11:19 UTC, va-kuznecov commented on ydb/core/blobstorage/ut_blobstorage/deadlines.cpp
> +        std::shared_ptr<TVDiskDelayEmulator> VDiskDelayEmulator = nullptr;
```suggestion
        std::shared_ptr<TVDiskDelayEmulator> VDiskDelayEmulator;
```

2024-12-13 13:46 UTC, va-kuznecov approved these changes

2024-12-13 13:47 UTC, merged