Update ydbops examples for CMS docs
ydb-platform/ydb pull request #11793
Opened 2024-11-20 12:10 UTC by pixcc

### Changelog category 

* Documentation (changelog entry is not required)

2024-11-21 06:15 UTC, anton-bobkov requested changes

2024-11-21 06:15 UTC, anton-bobkov commented on ydb/docs/en/core/devops/manual/maintenance-without-downtime.md
> +1) Create a maintenance task using the command:
```suggestion
1. Create a maintenance task using the command:
```

2024-11-21 06:15 UTC, anton-bobkov commented on ydb/docs/en/core/devops/manual/maintenance-without-downtime.md
> +3) Perform host maintenance while the lock is acquired.
```suggestion
3. Perform host maintenance while the lock is acquired.
```

2024-11-21 06:15 UTC, anton-bobkov commented on ydb/docs/ru/core/devops/manual/maintenance-without-downtime.md
> +Чтобы вывести хост для обслуживания можно воспользоваться следующим алгоритмом:
```suggestion
Чтобы вывести хост для обслуживания, выполните следующие шаги:
```

2024-11-21 06:15 UTC, anton-bobkov commented on ydb/docs/ru/core/devops/manual/maintenance-without-downtime.md
> +1) Cоздать задачу обслуживания с помощью команды:
```suggestion
1. Cоздать задачу обслуживания с помощью команды:
```

2024-11-25 06:26 UTC, fomichev3000 approved these changes

2024-11-25 06:26 UTC, fomichev3000 commented on ydb/docs/ru/core/devops/manual/maintenance-without-downtime.md
> +    $ ydbops maintenance complete --task-id=<id> --hosts=<fqdn>
Зачем одновременно указывать --task-id и --hosts? task-id же полностью определяет действие и хосты в том числе?

2024-11-25 11:10 UTC, pixcc commented on ydb/docs/ru/core/devops/manual/maintenance-without-downtime.md
> +    $ ydbops maintenance complete --task-id=<id> --hosts=<fqdn>
В данном случае указывать `--hosts` действительно избыточно. В общем случае, может быть несколько хостов в рамках одной задачи обслуживания. Передам Егору.

2024-11-25 11:17 UTC, anton-bobkov approved these changes

2024-11-25 11:17 UTC, merged