YDBDOCS-122: Новые метрики использования диска [Part 1]
ydb-platform/ydb pull request #11812
Opened 2024-11-20 16:32 UTC by galnat

### Changelog entry 
Added new metrics of storage consumption

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

2024-11-22 08:02 UTC, anton-bobkov requested changes

2024-11-22 08:02 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/observability/metrics/index.md
> +`resources.storage.topic.used_bytes`<br/>`IGAUGE`, байты  | Размер распределенного сетевого хранилища, используемого топиками. Равен сумме `topic.storage_bytes`.
Равен сумме `topic.storage_bytes` -- тут не понятно. Для суммы надо упомянуть несколько элементов.

2024-11-22 10:07 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/observability/metrics/index.md
> +`resources.storage.topic.used_bytes`<br/>`IGAUGE`, байты  | Размер распределенного сетевого хранилища, используемого топиками. Равен сумме `topic.storage_bytes`.
```suggestion
`resources.storage.topic.used_bytes`<br/>`IGAUGE`, байты  | Размер распределенного сетевого хранилища, используемого топиками. Равен сумме `topic.storage_bytes` всех топиков.
```

2024-11-25 06:30 UTC, fomichev3000 requested changes

2024-11-25 06:30 UTC, fomichev3000 commented on ydb/docs/en/core/reference/observability/metrics/index.md
> +| `resources.storage.topic.used_bytes`<br/>`IGAUGE`, bytes | The size of storage used by topics. |
В русской версии есть фраза "Равен сумме значений `topic.storage_bytes` всех топиков.", которая здесь отсутствует

2024-11-27 07:14 UTC, anton-bobkov requested changes

2024-11-27 11:31 UTC, fomichev3000 approved these changes

2024-11-27 12:13 UTC, anton-bobkov approved these changes

2024-11-27 15:24 UTC, merged