Change install instruction for ydb-dstool
ydb-platform/ydb pull request #11834
Opened 2024-11-21 09:55 UTC by kruall

### Changelog entry 

Change ydb-dstool from python package to bin

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-03 02:20 UTC, blinkov commented
waits for https://github.com/kruall/ydb/pull/1/files

2024-12-27 06:26 UTC, blinkov submitted a review, later dismissed

2024-12-27 06:26 UTC, blinkov commented on ydb/docs/en/core/reference/ydb-dstool/install.md
> +        The script will install the {{ ydb-short-name }} DSTool and add the executable file path to the `PATH` environment variable.
Technically, it adds to `PATH` the path to the folder containing the executable, not the executable's path.

2024-12-27 06:26 UTC, blinkov commented on ydb/docs/en/core/reference/ydb-dstool/install.md
> +    1. Specify whether to add the executable file path to the `PATH` environment variable:
```suggestion
    1. Specify whether to add `ydb-dstool` to the `PATH` environment variable:
```

2025-01-14 05:58 UTC, fomichev3000 requested changes

2025-01-14 05:58 UTC, fomichev3000 commented on ydb/docs/en/core/reference/ydb-dstool/_includes/unix_install_command.md
> +The script will install the {{ ydb-short-name }} DSTool. If the script is run from a `bash` or `zsh` shell, it will also add the `ydb-dstool` executable to the `PATH` environment variable. Otherwise,
Я, кстати, против ~/ydb-dstool/bin. На мой взгляд у ydb, dstool и ydbops должен быть один каталог ydb

2025-01-17 06:29 UTC, fomichev3000 approved these changes

2025-01-17 06:29 UTC, merged