YDB FQ: resolve logging groups into YDB tables
ydb-platform/ydb pull request #11904
Opened 2024-11-22 22:50 UTC by vitalyisaev2

### Changelog entry 

* YDB FQ: resolve logging groups into YDB tables

### Changelog category 

* New feature

### Additional information

...

2024-11-25 15:02 UTC, dorooleg requested changes

2024-11-25 15:03 UTC, dorooleg commented
Еще смущает ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp странно что в текущий интерфейс это не ложится. Выглядит так что вместо database_id нужно подсоавить folder_id и дальше общая магия заработает

2024-11-25 20:20 UTC, vitalyisaev2 commented on ydb/library/yql/providers/common/logging_resolver/logging_resolver.h
> +        struct TAuth {
> А почему сразу credentials provider не передать, странно structured token здесь видеть?

Честно говоря, мне сложно ответить на этот вопрос - так было сделано до меня. Знаю только, что `IDatabaseAsyncResolver` всегда [принимал](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h#L149) в себя [структурированные токены](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h#L84). А генерировали мы их испокон веку [в самом начале](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/provider/yql_generic_settings.cpp#L48) работы провайдера. Поэтому я просто сохраняю тут единообразный подход. Насколько я понимаю, credentials provider'ы прокидываются в read actor'ы из-за того, что чтение может быть потенциально бесконечным, но, кажется, что здесь (на этапе оптимизации) можно обойтись просто одним токеном, сгенерированным в самом начале, ведь от генерации до использования пройдут считанные мгновения.

2024-11-25 20:29 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_state.h
> +            Configuration->Init(gatewayConfig, databaseResolver, loggingResolver,  types->Credentials);
В `IDatabaseAsyncResolver`? Если только отдельный метод там сделать. Потому что пара параметров `(folder_id, log_group_name)` никак не ложится в структуру [`TDatabaseAuthMap`](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h#L147-L149). Зато в ней много других полей, [не релевантных](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h#L88-L96) для Cloud Logging. Поэтому я подумал, что лучше не впихивать в старый интерфейс то, что плохо впихивается, и просто завести отдельный класс для этого.

2024-11-26 07:17 UTC, dorooleg commented on ydb/library/yql/providers/generic/provider/yql_generic_state.h
> +            Configuration->Init(gatewayConfig, databaseResolver, loggingResolver,  types->Credentials);
`Protocol` вроде бы уже не для всех из списка актуален. `Tls` в теории тоже такая штука что не для всех может быть актуально, но хотя в наши дни уже менее вероятно. По поводу интерфейса `IDatabaseAsyncResolver` как вариант можно засериализовать `folder_id/log_group_name`, либо же расширить интерфейс, до map `{"folder_id": folder_id, "log_group_name": log_group_name}` и `{"database_id": database_id}`

2024-11-26 07:18 UTC, dorooleg commented on ydb/library/yql/providers/common/logging_resolver/logging_resolver.h
> +        struct TAuth {
Мотивацию понял)

2024-11-26 07:22 UTC, dorooleg commented
> > Еще смущает `ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp` странно что в текущий интерфейс это не ложится. Выглядит так что вместо database_id нужно подсоавить folder_id и дальше общая магия заработает
> 
> Почему я сделал отдельный интерфейс. `IDatabaseAsyncResolver::ResolveIds` не подходит по сигнатуре - нам надо ведь прокинуть `(folder_id, log_group_name)` пару в Cloud Logging API (см. тикет LOGGING-1706). Поэтому надо либо добавлять новый метод в этот класс, либо рефакторить имеющийся метод). Первое мне не очень хотелось делать, так как это убивает букву `S` в `SOLID`. Второе тоже - чтобы не переписывать все имеющиеся провайдеры :) ну и в результате рефакторинга интерфейс получится достаточно расфокусированным, т. к. у разных источников много своей специфики.
> 
> Кроме того, код актора [Database Resolver](https://github.com/ydb-platform/ydb/blob/main/ydb/core/fq/libs/actors/database_resolver.cpp) уже достаточно сложен, и хотелось сохранить его хотя бы в текущем состоянии, не добавляя кастомной логики, связанной с Cloud Logging. Ведь если сделать отдельный `ILoggingResolver`, то будет гораздо проще кастомизировать его поведение. Вот нам нужна ручка от Cloud Logging, но сейчас её нет - значит, мы можем сделать временную имплементацию, которая будет перебирать статически прописанные в конфиге инстансы YDB по round robin'у, и так далее.
> 
> Вообще я на эту тему (расширять старый класс или добавить новый) пытался с Серёгой посоветоваться, но он уже не ответил мне, в след. раз приду к тебе :) Но я могу и переписать, ты скажи как, мне не принципиально.

Меня смутило что после изменения `S` в `SOLID` развалился в самом трансформере. `ILoggingResolver` можно вполне использовать под интерфейсом Database Resolver. У меня здесь основное смущение что для добавления нового источника пришлось столько кода переделывать, раньше как-то проще они запихивались и кажется что `ILoggingResolver` в этом месте не сильно отличается от остальных :(

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
> +                            UnresolvedItems_[clusterName] = {
Почему чтения из разных логгрупп склеиваются? Похоже на багу

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
> +                        [this, clusterName, item, responseFuture](const NThreading::TFuture<ILoggingResolver::TResponse>&) mutable {
Хватать this-опасно. Нужно гарантировать время жизни объекта, иначе будут падения

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
> +                    YQL_CLOG(DEBUG, ProviderGeneric) << "total clusters to be resolved"
Нельзя ли внутри метода логировать? Пропилили мутные методы count, name в интерфейсе исключительно для логирования?

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
> +                    issues.AddIssues(future.GetValueSync());
Меня беспокоит GetValueSync. Это точно асинхронный подход?

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
> +                    issues.AddIssues(future.GetValueSync());
Тебе надо вернуть asyncFuture и доставать полученные данные в метод ApplyAsyncChanges

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +            if (clusterConfig.GetKind() == NConnector::NApi::EDataSourceKind::LOGGING) {
Подобный if я уже комментил, копипаста что ли?;)

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_settings.cpp
> +                                     const NYql::IDatabaseAsyncResolver::TPtr databaseResolver,
Амперсанды потерял. Проверь и в других местах

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_settings.h
> +                  const NYql::IDatabaseAsyncResolver::TPtr databaseResolver,
И тут амперсанды потерял при передаче TPtr

2024-11-26 12:14 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_state.h
> +            Configuration->Init(gatewayConfig, databaseResolver, loggingResolver,  types->Credentials);
Меня смущает, что в результате резолва есть еще tableName. Если реализация двух резольверов сильно не дублируется, то я пока бы так оставил, то есть пусть будет новый резолвер

2024-11-26 12:32 UTC, uzhastik commented on ydb/core/fq/libs/db_id_async_resolver_impl/mdb_endpoint_generator.cpp
> -
Бесполезные изменения: в одном файле добавил новую строчку перед return, в другом-удалил. Логики никакой не вижу ;)

2024-11-26 12:36 UTC, uzhastik commented on ydb/library/yql/providers/common/logging_resolver/logging_resolver.h
> +        struct TAuth {
А я не понял почему в двух резолверах разный tauth. Нет смысла сделать одинаково?

2024-12-09 15:59 UTC, closed without merging