YQ-3738 RD pass UV from filter to read actor
ydb-platform/ydb pull request #11940
Opened 2024-11-25 11:10 UTC by GrigoriyPA

- **fix normalization processing (#11583)**
- **Revert "YT block input fix for empty input" (#11624)**
- **Added a condition for the link to distributed-storage.md (#11611)**
- **Update docs for Variant builtins (#11296)**
- **Fix YQL udf/list docs (#11596)**
- **Fix obliterate description (#11221)**
- **Dockerfile oss (#11472)**
- **Support ALTER TABLE for adding PG types (#11630)**
- **fix test timeouts (#11623)**
- **Store flag AuthorizeByCertificate to local db of node broker (#11315)**
- **English documentation about LDAP interaction (#11223)**
- **Add new UT for IC memory consumption (#11546)**
- **CI codeowners for yql (#11619)**
- **fix clusterName and node_type in UA meta session (#11240)**
- **Restore legacy kv api again (#11604)**
- **Add direct conversion from Ydb::Value tuple to Cell in rpc_read_table (#11615)**
- **Change TODO comments about pg types in minikql (#11651)**
- **SQS: handle empty QueueUrl correctly (#11652)**
- **fix node checking (#11578)**
- **YQ-3859 Check semaphore generation in row dispatcher (#11572)**
- **Fix exporting CMake for darwin (#10865)**
- **Fix tsan race in actor quicksort benchmark (#11664)**
- **Repair portions and async proto parser (#11636)**
- **Abort TLogWrite requests properly (#11665)**
- **Use DEBUGINFO_LINES_ONLY param for ydbd binary in breakpad docker tag (#11671)**
- **async CA: remove unused code (#11628)**
- **Fix TComputeActorAsyncInputHelperSync destruction (#11476)**
- **switch on blancing checking (#11668)**
- **PopCount() => std::popcount() (#11669)**
- **format setting supported for date type (#11608)**
- **YQ-3847 RD support regexp pushdown (#11626)**
- **Return get_unique_path_for_current_test and some more (broken arcadia) (#11598)**
- **Refactoring parsing of nodes info response from cluster (#11681)**
- **Replace logical ids with 0 in canonized files as it is done in dq_file (#11683)**
- **fix container label in vdisk metrics for grafana dashboard (#10881)**
- **YQ-3869 RD added limit for parser buffer size (#11627)**
- **parse TTL syntax with tiering on KQP (#11613)**
- **Async transform for CTAS (#11656)**
- **Aggregate nodes memory stats for tenant (#11612)**
- **Fix excessive memory usage during index-only non-restoring TEvRange query execution (#11692)**
- **Update yqlrun UI script after YQL move (#11690)**
- **ChaCha AVX512 runtime dispatch improvement (#11230)**
- **Refactor Shared Cache configuration (#11567)**
- **Optimise Html App of PQ-table (#11667)**
- **Separate acceleration ICB settings for HDD and SSD (#11590)**
- **Prewarm more often (#11698)**
- **Remove obsolete readme from tests (#11697)**
- **fix filter usage for sequential assembling (#11687)**
- **Correct get schema validations (#11686)**
- **async CA: fq_diag/monitoring page: add input transform information (#11662)**
- **Fix incorrect counter of inflight requests for get_storage_channel_st… (#11702)**
- **YQ-3855 Add cookie to events RD <-> read_actor (#11562)**
- **move nullable control into data checker (#11685)**
- **Send datasize stats by channel along with total (#11675)**
- **YQL-18029: Make BinaryCacheFolder pragma cluster-specific (#11707)**
- **adjust grpc request latency buckets (#11713)**
- **YQ-3873 Add query id to error  (#11700)**
- **YQ-3834 Shared reading: add query id to logs (#11603)**
- **Support alter sequence restart with (#11447)**
- **prohibit creating secrets with duplicating names (#11680)**
- **YQ-3814 Add metrics to read_actor / topic_session (#11196)**
- **YQ-3883 Shared reading: fix logs/statistics (#11723)**
- **fix exception processing (#11728)**
- **Leak bs normalizer (#11682)**
- **Update breakpad dependencies for docker image (#11735)**
- **Add stop condition for kmeans (#11617)**
- **fix chunks reorder on loading (#11736)**
- **Datashard lock stats (#11731)**
- **Add tests for init queries in benchmarks (#11739)**
- **Resolve wildcards in muted_ya (#11717)**
- **YQ RD added brackets during pushdown (#11742)**
- **ChaCha AVX512 fix hotpath in XOR (#11699)**
- **Unmute stable tests (#11751)**
- **feat(kqp): add pragma for sequential reads (#11715)**
- **Mute unstable tests (#11753)**
- **preserve suid bit fix for old docker versions (#11714)**
- **Change conditions for enabling block input (#11600)**
- **Enable Column tables by default (#10906)**
- **Improve compute nodes database error message (#11750)**
- **Use query service in suite tests (#11618)**
- **Add DS Proxy deadline tests (#11749)**
- **Lock-free mailboxes with intrusive event lists (#11419)**
- **Support MoveSequence in schemeshard (#9772)**
- **Improve csv import, steps 1 & 2 (#11679)**
- **Added enable_antlr4_parser feature flag (#11764)**
- **Passed unboxed values from filter to read actor**

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-25 20:30 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/format_handler/common/common.h
> +    using TStatucCode = EId::StatusCode;
Typo

2024-12-09 15:56 UTC, dorooleg requested changes

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +    TDuration ParseAndFilterLatency;
Как-то странно видеть в ParserStatistic: `ParseAndFilterLatency` Это точно правильное место?

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +        ParserLatency = stat.ParserLatency != TDuration::Zero() ? stat.ParserLatency : ParserLatency;
А точно тут хочется последнюю запись брать? Что она будет показывать? Может `Max` нужно брать

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +    std::unordered_map<TString, TFormatHandlerStatistic> FormatHandlers;
А какие форматы тут будут?

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/format_handler/common/common.h
> +class TStatus {
Зачем еще один Status нужен? давай возьмем yql status

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/format_handler/filters/filters_set.cpp
> +class TTopicFiltersSet : public ITopicFiltersSet {
А точно тут нужен Set в конце? Может просто `TTopicFilters`? Чтобы не привызяываться к деталям как оно там хранится

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/format_handler/filters/purecalc_filter.h
> +class IPurecalcFilter : public TThrRefBase, public TNonCopyable {
А точно все эти интерфейсы уже имеют смысл, есть планы разные реализации запихивать?

2024-12-09 15:56 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    reserved 1;
При обновлениях обратная совместимость будет сохранена?

2024-12-09 15:56 UTC, dorooleg commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> -                sharedReading = sharedReading && (format == "json_each_row" || format == "raw");
Эм, а если csv_with_names будет, оно как будет работать? Есть ли возможность по старой дорожке пустить?

2024-12-09 15:59 UTC, dorooleg commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> +    DataUnpacker->UnpackBatch(MakeChunkedBuffer(std::move(messageBatch)), HolderFactory, parsedData);
Потом нужно будет про arrow подумать и через него батчами передавать. В этом ревью пойдет и так)

2024-12-09 16:10 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +        ParserLatency = stat.ParserLatency != TDuration::Zero() ? stat.ParserLatency : ParserLatency;
Это ведь статистика, которая будет агрегироваться в RowDispatcher, там я сделал как и раньше, последнюю запись:
https://github.com/ydb-platform/ydb/pull/11940/files#diff-007bbb6bed8fa631b15f0e9b144aeec2428186966226f908f79d379e2e0a4855L45

Мы берём самую актуальную запись, которая пришла из topic session, а уже в парсере я беру максимум:
https://github.com/ydb-platform/ydb/blob/624a55922b146f60341ed32a9ca00a94e5201ed5/ydb/core/fq/libs/row_dispatcher/format_handler/parsers/parser_base.cpp#L45-L47

2024-12-09 16:11 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +    std::unordered_map<TString, TFormatHandlerStatistic> FormatHandlers;
Пока тут будет только разбивка по json_each_row и raw, в будущем может быть ещё форматов добавим

2024-12-09 16:12 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/format_handler/common/common.h
> +class TStatus {
Где примерно его можно найти?

2024-12-09 16:13 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/format_handler/filters/filters_set.cpp
> +class TTopicFiltersSet : public ITopicFiltersSet {
На самом деле Set никакого внутри нету, это скорее совпадение. Окей, переименую в TTopicFilters

2024-12-09 16:16 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/format_handler/filters/purecalc_filter.h
> +class IPurecalcFilter : public TThrRefBase, public TNonCopyable {
Я добавил интерфейс вместо создания std::unique_ptr<TImpl>, как было раньше:
https://github.com/ydb-platform/ydb/blob/d917bcb1d7dfb27990422185c73940d7f248b73d/ydb/core/fq/libs/row_dispatcher/json_filter.h#L31

Кажется так просто проще писать (не надо объявления функций дважды дублировать), ну и так потенциально можно будет сделать два режима:
* Обычный фильтр
* По фича флагу фильтр в котором объединено много программ

2024-12-09 16:17 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    reserved 1;
По идее будут приходить пустые TEvMessage, по этому обратной совместимости скорее не будет (другие ноды со старым кодом должны подвиснуть, пока к ним приходят нулевые оффсеты)

2024-12-09 16:19 UTC, GrigoriyPA commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> -                sharedReading = sharedReading && (format == "json_each_row" || format == "raw");
Я перенёс эту проверку ниже:
https://github.com/ydb-platform/ydb/blob/624a55922b146f60341ed32a9ca00a94e5201ed5/ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp#L394-L396

В настройках PqSpurce уже должно лежать актуальное значение, так как на его основе отключается второй парсинг:
https://github.com/ydb-platform/ydb/pull/11940/files#diff-5e549d826ba598c1c0196134e16cdd8302c968bb0badb05af67cfcd667d15bb7R54-R58

2024-12-09 16:24 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    reserved 1;
При этом read акторам с новым кодом будет приходить пустое множество офсетов, они тоже должны подвиснуть, пока всё не обновится

2024-12-09 16:29 UTC, dorooleg commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> -                sharedReading = sharedReading && (format == "json_each_row" || format == "raw");
Наверное тогда этот вопрос не к этому ревью. Тут видимо нет никаких блокеров чтобы другие форматы вернуть как есть например: `csv_wtih_names`, `tsv_with_names`, но лучше в отдельном ревью про это подумать

2024-12-09 16:45 UTC, dorooleg commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> -                sharedReading = sharedReading && (format == "json_each_row" || format == "raw");
Тут же не сложно будет второй парсинг вернуть? По протоколу передать как raw, а потом CH парсер запустить

2024-12-09 16:47 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    reserved 1;
Страшная штука, ну может как нибудь переживем это

2024-12-09 16:52 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +    TDuration ParseAndFilterLatency;
Может как отедельное поле сбоку передавать? И отдельно разместить в общий handler statistic: https://github.com/ydb-platform/ydb/pull/11940/files/624a55922b146f60341ed32a9ca00a94e5201ed5#diff-007bbb6bed8fa631b15f0e9b144aeec2428186966226f908f79d379e2e0a4855R54

2024-12-09 20:01 UTC, GrigoriyPA commented on ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
> -                sharedReading = sharedReading && (format == "json_each_row" || format == "raw");
Да, можно так, а можно прямо в RD написать парсер, чтобы парсилось всего раз, определив нужные интерфейсы (например заиспользовать тот же CH парсер)

2024-12-10 06:05 UTC, kardymonds approved these changes, later dismissed

2024-12-10 08:00 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
> +    ui64 LastSendedNextMessageOffset = 0;
Окей

2024-12-10 08:28 UTC, GrigoriyPA commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    reserved 1;
Исправил в случае rollback, запросы остановятся с INTERNAL_ERROR

2024-12-10 08:51 UTC, swalrus1 requested changes

2024-12-10 08:51 UTC, swalrus1 commented on ydb/library/conclusion/generic/status.h
> +    template <class TErrorMessage>
Зачем здесь template аргумент?

2024-12-10 08:51 UTC, swalrus1 commented on ydb/library/conclusion/generic/status.h
> +    [[nodiscard]] virtual TString GetErrorString() const {
Не будет лучше определить вместо этого в обоих наследниках TConclusionStatusGenericImpl `TString DebugString() const` и использовать его в TConclusion, чтобы не делать класс виртуальным?

2024-12-10 08:51 UTC, swalrus1 commented on ydb/library/conclusion/generic/status.h
> +class TConclusionStatusIssueImpl : public TConclusionStatusGenericImpl<TStatus, StatusOk, DefaultError, NYql::TIssues, TConclusionStatusIssueImpl<TStatus, StatusOk, DefaultError>> {
Можно унести TConclusionStatusIssueImpl в `yql/`, чтобы не расширять зависимости library/conclusion?

2024-12-10 08:51 UTC, swalrus1 commented on ydb/library/conclusion/generic/result.h
> +            return TStatus::Success().GetErrorMessage();
Здесь не будет возвращаться ссылка на ErrorMessage, аллоцированное на стеке?

2024-12-10 12:56 UTC, kardymonds approved these changes

2024-12-10 13:12 UTC, dorooleg approved these changes

2024-12-10 14:02 UTC, swalrus1 approved these changes

2024-12-10 14:02 UTC, swalrus1 approved these changes

2024-12-10 14:13 UTC, merged