[CBO] user warning added if cbo didn't work
ydb-platform/ydb pull request #11950
Opened 2024-11-25 13:46 UTC by pashandor789

### Changelog category 

* Improvement

2024-11-26 11:18 UTC, pavelvelikhov commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
> +                        "Cost Based Optimizer didn't work: "
I don't like the text here, lets change it to:
"Cost Based Optimizer could not be applied to this query:"

2024-11-26 11:18 UTC, pavelvelikhov requested changes

2024-11-26 12:04 UTC, pavelvelikhov approved these changes, later dismissed

2024-11-26 12:16 UTC, Hor911 submitted a review, later dismissed

2024-11-26 12:41 UTC, nepal requested changes

2024-11-26 12:41 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_log.h
> +IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPhypDPTableSize, TExprContext* exprCtx = nullptr);
Вливаем после https://a.yandex-team.ru/review/7323101/details

2024-11-26 17:46 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_log.h
> +IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPhypDPTableSize, TExprContext* exprCtx = nullptr);
Точнее вот - https://github.com/ydb-platform/ydb/pull/12017

2024-11-26 20:45 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_log.h
> +IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPhypDPTableSize, TExprContext* exprCtx = nullptr);
Library Import влился. Вам надо поребейзится на свежий main. В этом месте код поменялся, но кстати ваша задача теперь проще решается - TExprContext в новом API приходит в фабрику оптимизатора

2024-11-26 20:53 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_log.h
> +IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPhypDPTableSize, TExprContext* exprCtx = nullptr);
Да, и я бы предложил передавать TExprContext обязательным аргументом (по ссылке). Во всех местах где эта функция используется, TExprContext& есть под рукой

2024-11-28 14:49 UTC, pavelvelikhov submitted a review, later dismissed

2024-11-28 14:58 UTC, nepal requested changes

2024-11-28 14:58 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.h
> -IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPccpDPTableSize);
Зачем тут передавать указатель? Во всех местах где эта функция используется контекст есть. А при текущем подходе потом будут проблемы с добавлением новых аргументов.

2024-11-28 14:58 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
> +            YqlIssue({}, TIssuesIds::DQ_OPTIMIZE_ERROR,
А более подходящего кода нет? Который warning, а не error

2024-11-28 15:03 UTC, pashandor789 commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
> +            YqlIssue({}, TIssuesIds::DQ_OPTIMIZE_ERROR,
нету.
добавить?

2024-11-28 15:04 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_log.h
> +IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPhypDPTableSize, TExprContext* exprCtx = nullptr);
TExprContext ctx; подойдет

2024-11-28 15:15 UTC, pashandor789 commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.h
> -IOptimizerNew* MakeNativeOptimizerNew(IProviderContext& ctx, const ui32 maxDPccpDPTableSize);
да просто в тестах там эта функция вызывается
думал, что TExprContext просто так не создать. ошибался.
переписал

2024-11-28 15:26 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
> +            YqlIssue({}, TIssuesIds::DQ_OPTIMIZE_ERROR,
Предлагаю потом добавить (в рамках отдельного PR в Аркадию)

2024-11-29 09:01 UTC, nepal approved these changes

2024-11-29 10:02 UTC, merged