YQ-3894 RD supported pushdown for SafeCast, ToBytes, FlatMap
ydb-platform/ydb pull request #12066
Opened 2024-11-27 15:48 UTC by GrigoriyPA

- Update flake8 binaries commit_hash:33644a2ad5fc56ac738869b46aa5d5e991c8ef9a
- Update YFM for ya make to latest version
- Fix YQL_UDF_YDB_TEST macro commit_hash:231818a85581b4c119ea310cb8ce8c47934f327b
- YT-23461: Support different columns in meta
- Intermediate changes commit_hash:c9890b6966b6c4d2d0cb13bda9b30004d232450e
- Added cluster field to TRichYPath
- Fix most Gradle proto builds
- Intermediate changes commit_hash:9085ddac9f80e60b5b938027d444ed98e80ef95a
- Sync EvaluteExpr execution (#11801)
- Sensor for number of shards within single BulkUpsert data (#11786)
- Accessors memory limit on background (#11816)
- contrib/libs/poco: Backport PR #2943 to fix -Wimplicit-const-int-float-conversion
- Migrate to STYLE_CPP (#11523)
- Column Family for ColumnTable (#9657)
- Extend TTL syntax to support tiers
- Update contrib/python/types-protobuf to 5.28.0.20240924 commit_hash:0a209dcd80a5c303e9cbc293056b422eb96242a1
- build: refresh Embedded UI (v6.36.1) (#11833)
- Fix issues in rXXXXXX
- Fix udfs path in tests runner (#11821)
- YQ-3888 Fix "session already exists" error (#11826)
- Intermediate changes commit_hash:3d8c36a9891955ab700f018337e599a271197819
- Make sure mailboxes in test actorsystems are in a locked state (#11837)
- YT-23542: Add local throttlers to distributed throttler member attributes. commit_hash:786aac617c6a994ba9f2f527bb6c64c55f48be29
- Stock bench for Olap shards (#11757)
- YQ-3892 fix data race in json filters (#11827)
- Fix blobstorage crypto module build for aarch64 (#11840)
- fix filter usage for partial reading (#11835)
- YT-23585: Fix race between Cancel and GetCanceledError in Canceler commit_hash:2c1b31d95037975cf4703cb90f81232f880a37e6
- YQ-3890 added per node partition limit (#11830)
- increase timeout on tpch 1000 (#11850)
- [arc][getopt]fix enforcment of RequiredArgument().DisableSpaceParse() commit_hash:9c2ada5b95be3f810d2750406d74d839bd2598ff
- YQ-3873 Add query id to error /  fix clang14 build (#11846)
- unmute stable tests (#11856)
- Intermediate changes commit_hash:50996f174ea1b659bc41e9f4e9f27328060af2ca
- Update YFM for ya make to latest version
- Fix proto with proto-libraries, refactor errorprone
- Fix blob recovery actor bug (#11857)
- YDB FQ: support Logging as an external data source (#11765)
- Fix filter pushdown over Aggregate with session/hopping window commit_hash:3d4989f7a92e9b330cd4b19f1850cdca544a1d64
- ListSample/ListSampleN/ListShuffle implementation commit_hash:987b10b398caa89eee8b94b33f9ea1dc74197223
- use yaml for table description instead yql (#11811)
- Enable -Wreturn-std-move commit_hash:c7f0699a8f585dc8140bded7a65b017808bebb38
- Release clang-format-18 #2
- Support ALTER SEQUENCE command
- Update contrib/libs/expat to 2.6.4 commit_hash:9a71f6b42bb4dd7cf1281e4b72c5da4a3c18a399
- Remove TRbTree and TAvlTree from forward declarations as they are not in util commit_hash:7f3c30234700758cc6218bdef0fa2e6862f2c32e
- Public TValuePackerTransport.IsBlock_ field commit_hash:1460634e062682d017761c493ba36122257278e9
- Update contrib/python/types-protobuf to 5.28.3.20241030 commit_hash:34dfb9be1465bd259bf2f5c90a3114542cd87d6d
- nots/*: Стабилизация trunk
- Add fallback to ssl port on ydb driver init (#11869)
- Intermediate changes commit_hash:e8f03143f071def87f56790176fbdc918784ed35
- Import libraries 241122-0919
- Signed Enumerate commit_hash:af73a3ea146e2eb6141cb19913e534d75ba573fd
- Improve csv import, step 3 (#11864)
- add subcodes to tx-proxy reply code counters (#11862)
- YT-22455: Introduce list jobs continuation token
- Extract schemeshard protos p.1 (#11803)
- Support configuring scale recommender policies in console (#11798)
- YDB Import 625 commit_hash:bbf24592c367fa158fbc53e041fe367374d0750e
- YT_DEFINE_GLOBAL for profilers commit_hash:c9f0f790039ceeef149366a14c9063025fbb1e0c
- Correct Rows count in MultiType Input Channels (#11859)
- Disable Y_ENSURE() for improper invariant
- ya style clang format. Braces style
- tempo fix for win (pybuild)
- Remove old restriction: keys with Uint8 column values >127 are currently prohibited (#11886)
- Revert "Support arbitrary chain set in huge blob keeper heap (#11566)" (#11891)
- YQ-3900 Fix ScheduleHeartbeat() if already connected (#11888)
- Intermediate changes commit_hash:d0db92345dc96a43a16424238c1eb2812040a13d
- Fix URL for transaction page of PQ tablet (#11900)
- Intermediate changes commit_hash:d3ad801a6e5fb7eb38c6c78286f53c3b165b87c2
- YT-23422: do not write command line into attributes of operations
- fix buffered stream interleaving for proto format commit_hash:66e6b75f97ea253ddbf4c97a180f9f971c59f93b
- Unify -Wno arguments generation commit_hash:33157feb41c65ab08e797adea3b0be5ed6e5bc3f
- Change priority for rule NonOptimalTableContent (#11625)
- Correct Rows count in Block Output Channels (#11893)
- Check custom error in xfail tests. Remove canonization from dq/hybrid tests
- Import libraries 241123-2111
- Check custom error in xfail tests. Remove canonization from dq/hybrid tests (#11910)
- YQL-19206 Fix YQL_PYTHON* macros commit_hash:efcdd5f8a76a33ea53572df5a214f2de61c7775f
- Change YQL_BASE_DIR
- Update docs for datetime udf (#11746)
- Remove REAL infix from huge blob size (#11916)
- Set position to state only if all data portions succesfully send (#11912)
- Fix and simplify logic with multiprocess TPC-* data generation (#11913)
- Unmute stable tests (#11924)
- validate dangerouse construction (#11873)
- Accept True in stability test (#11932)
- fix empty variable usage (#11926)
- Update ydbops examples for CMS docs (#11793)
- Drop yql fastcheck before move (#11937)
- Fix paths in uig.sh helper (#11939)
- Add new VDisk's cpu consumption metric (#11719)
- Removed S3 MaxReadSizePerQuery config (#11936)
- Switch on check canonical results for tpch 1k and 10k (#11951)
- Implemented --explain-ast param for ydb sql command (#11928)
- Add GRPC thread CPU time metric (#11772)
- Add backup incremental backup collection (#11870)
- Support arbitrary chain set in huge blob keeper heap (#11921)
- fix request shard count sensor (#11962)
- checkpointing vs abort: wait for completion before aborting (#11896)
- Revert "Support arbitrary chain set in huge blob keeper heap" (#11961)
- Consistency option (core part) (#11970)
- improve network diagnostics - add peer role filter (#11925)
- YQ-3880 Add metrics to pq read actor (#11871)
- Relative path to table in GRANT\REVOKE operation (#11906)
- Fix memory order for tracing control (#11949)
- Improve csv import, step 4 (#11907)
- YQ-3909 Shared reading: fix Ingress statistics (#11943)
- Supported pushdown for SafeCast, ToBytes, FlatMap

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-27 18:54 UTC, kardymonds approved these changes, later dismissed

2024-11-27 20:01 UTC, vitalyisaev2 requested changes

2024-11-27 20:01 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
> +        string type = 2;
Возможно, стоит подумать о том, чтобы применить тут Ydb.Type, но это не точно :)

2024-11-28 10:26 UTC, vitalyisaev2 approved these changes, later dismissed

2024-11-29 17:13 UTC, dorooleg approved these changes

2024-12-02 06:55 UTC, merged