Ping service
ydb-platform/ydb pull request #12100
Opened 2024-11-28 13:46 UTC by eivanov89

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-11-28 14:43 UTC, CyberROFL requested changes

2024-11-29 10:24 UTC, eivanov89 commented on ydb/core/grpc_services/rpc_ping.cpp
> +        if (!ctx.Send(MakeTxProxyID(), new TEvTxUserProxy::TEvAllocateTxId)) {
Мне кажется, что как раз хочется проверить именно с аллокацией. TxId сейчас аллоцируются по 5000. При наших нагрузках, они довольно быстро истощаются и достаточно часто (~раз в секунду в моём случае) ходим аллоцировать новый range (идём раньше истощения). Если пинговать 100-200 раз в секунду, то это не повлияет никак. Но если транзакций столько, что TxId всё время истощены, то ping это поймает.

2024-11-29 14:18 UTC, CyberROFL approved these changes, later dismissed

2024-11-29 14:34 UTC, snaury commented on ydb/core/grpc_services/rpc_ping.cpp
> +        if (!ctx.Send(MakeTxProxyID(), new TEvTxUserProxy::TEvAllocateTxId)) {
Я сначала тоже удивился, но потом подумал, и в tx proxy действительно всё так или иначе проходит через аллокацию, в этом смысле проверять работоспособность tx proxy действительно правильно через аллокацию TxId. С другой стороны там исторически раздельные плохие очереди, и AllocateTxId, так уж получилось, самый низкоприоритетный. Причём сам kqp этим запросом только недавно начал пользоваться, например в случае транзакций с топиками. Завёл про это https://github.com/ydb-platform/ydb/issues/12147

2024-11-29 17:03 UTC, CyberROFL approved these changes

2024-11-30 14:26 UTC, pnv1 commented
По части CLI - OK.
@Gazizonoki посмотри по части SDK

2024-11-30 14:26 UTC, pnv1 approved these changes

2024-11-30 14:26 UTC, merged