docs: publish YDB CLI 2.16.0 with release notes
ydb-platform/ydb pull request #12108
Opened 2024-11-28 16:10 UTC by galnat

### Changelog entry 
Publish YDB CLI 2.16.0 with release notes

### Changelog category 
* Documentation (changelog entry is not required)

2024-11-28 16:17 UTC, pnv1 approved these changes, later dismissed

2024-11-29 02:13 UTC, blinkov requested changes, later dismissed

2024-11-29 02:13 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Fixed a bug where restoring from a backup using --import-data could fail if the partitioning of the table was changed
```suggestion
* Fixed the progress bar in the `{{ ydb-cli }} workload import` command.
* Resolved an issue where restoring from a backup using the `--import-data` option could fail if the table's partitioning had changed.
```

2024-11-29 02:13 UTC, blinkov commented on ydb/docs/ru/core/changelog-cli.md
> +* В команду `ydb tools restore` добавлен вывод пути до места возникновения ошибки
```suggestion
* Увеличена пропускная способность команды `{{ ydb-cli }} import file csv` примерно в 3 раза.  
* Добавлена поддержка [stock-нагрузки](./reference/ydb-cli/commands/workload/stock.md) для [колоночных таблиц](./concepts/datamodel/table.md#column-oriented-tables).
* Реализована поддержка временных меток в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601) для команд `ydb topic`.  
* В команду `{{ ydb-cli }} sql` добавлена опция `--explain-ast`, которая выводит AST запроса.  
* Добавлена подсветка синтаксиса ANSI SQL в интерактивном режиме.  
* В команды `{{ ydb-cli }} workload tpch` и `{{ ydb-cli }} workload tpcds` добавлена поддержка синтаксиса PostgreSQL.  
* В команду `{{ ydb-cli }} workload tpcds run` добавлена опция `-c` для сравнения результата с ожидаемым значением и отображения различий.  
* В команды `{{ ydb-cli }} tools dump` и `{{ ydb-cli }} tools restore` добавлено логирование событий.  
* В команду `{{ ydb-cli }} tools restore` добавлено указание места возникновения ошибки.

### Изменения с потерей обратной совместимости

* В команде `{{ ydb-cli }} topic write` для опции `--codec` значение по умолчанию изменено на `RAW`.
```

2024-11-29 02:13 UTC, blinkov commented on ydb/docs/ru/core/changelog-cli.md
> +* Исправлена ошибка восстановления из резервной копии с использованием `--import-data`, если изменилось партиционирование таблицы.
```suggestion
* Исправлен progress bar для команды `ydb workload import`.
* Устранена ошибка восстановления из резервной копии с использованием опции `--import-data`, возникавшая при изменении партиционирования таблицы.
```

2024-11-29 07:26 UTC, polRk commented
Missing binary for linux/arm64

2024-12-02 13:11 UTC, fomichev3000 approved these changes

2024-12-02 13:11 UTC, merged