Add reference to YDB SQLAlchemy + Jupyter Notebook example
ydb-platform/ydb pull request #12132
Opened 2024-11-29 09:44 UTC by vgvoleg

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-03 02:14 UTC, blinkov requested changes, later dismissed

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +Jupyter Notebook - an open-source instrument that provides an ability to create a shareable document that combines computer code, plain language descriptions, data, rich visualizations like 3D models
```suggestion
# Work with {{ ydb-short-name }} from Jupyter Notebook

[Jupyter Notebook](https://jupyter.org) is an open-source tool for creating shareable documents that combine code, plain language descriptions, data, rich visualizations, and interactive controls.
```

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +Dialect [YDB-SQLAlchemy](https://github.com/ydb-platform/ydb-sqlalchemy/releases) allows to work with {{ ydb-short-name }} from instruments like:
```suggestion
The [ydb-sqlalchemy dialect](https://github.com/ydb-platform/ydb-sqlalchemy/releases) enables working with {{ ydb-short-name }} from tools such as:
```

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +2. [Jupyter Notebook](https://jupyter.org/install#jupyter-notebook)
```suggestion
2. [Jupyter Notebook](https://jupyter.org/install#jupyter-notebook) or a compatible hosted service
```

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +3. [Existing {{ ydb-short-name }}](https://ydb.tech/docs/ru/quickstart)
```suggestion
3. Existing {{ ydb-short-name }} cluster, a single-node one from [quickstart](../../quickstart.md) will suffice
4. Network connection between Jupyter Notebook and {{ ydb-short-name }}
```

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +Detailed example is available via [notebook](https://github.com/ydb-platform/ydb-sqlalchemy/blob/main/examples/jupyter_notebook/YDB%20SQLAlchemy%20%2B%20Jupyter%20Notebook%20Example.ipynb).
```suggestion
## Example

A detailed usage example is available as a [notebook](https://github.com/ydb-platform/ydb-sqlalchemy/blob/main/examples/jupyter_notebook/YDB%20SQLAlchemy%20%2B%20Jupyter%20Notebook%20Example.ipynb).```

2024-12-03 02:14 UTC, blinkov commented on ydb/docs/en/core/integrations/gui/jupyter.md
> +To launch example just open notebook and follow each cell.
```suggestion
To run the example, download the notebook file {% file src="https://raw.githubusercontent.com/ydb-platform/ydb-sqlalchemy/refs/heads/main/examples/jupyter_notebook/YDB%20SQLAlchemy%20%2B%20Jupyter%20Notebook%20Example.ipynb" name="YDB SQLAlchemy - Jupyter Notebook Example.ipynb" %}, open it in Jupyter, and follow each cell sequentially, executing code as necessary.
```

2024-12-08 14:10 UTC, fomichev3000 approved these changes

2024-12-08 14:10 UTC, merged