Draft: Update Superset docs after adding native driver support
ydb-platform/ydb pull request #12143
Opened 2024-11-29 13:25 UTC by vgvoleg

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

**DO NOT MERGE** until https://github.com/apache/superset/pull/31141 is merged.

2024-12-03 01:58 UTC, blinkov requested changes

2024-12-03 01:58 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +## Installation of needed dependencies
```suggestion
## Installation of dependencies
```

2024-12-03 01:58 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +Depending on Superset installation it is possible to do it several ways, refer to [official documentation](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-docker-image
```suggestion
To work with {{ ydb-short-name }} via Superset, you need to install the [ydb-sqlalchemy](https://pypi.org/project/ydb-sqlalchemy) driver.

The installation method depends on how Superset is set up. For detailed guidance, refer to the [official documentation](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-docker-images).
```

2024-12-03 01:58 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/_includes/toc-table.md
> +| [Apache Superset](https://superset.apache.org) | [YDB-SQLAlchemy](https://github.com/ydb-platform/ydb-sqlalchemy/releases) | [Instruction](../superset.md) |
```suggestion
| [Apache Superset](https://superset.apache.org) | [ydb-sqlalchemy](https://github.com/ydb-platform/ydb-sqlalchemy/releases) | [Instruction](../superset.md) |
```

2024-12-03 01:58 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +For additional info about configuration of {{ ydb-short-name }} connection, please refer to [YDB section on official documentation](https://superset.apache.org/docs/configuration/databases#ydb).
```suggestion
For more information about configuring a {{ ydb-short-name }} connection, refer to the [{{ ydb-short-name }} section in the official documentation](https://superset.apache.org/docs/configuration/databases#ydb).
```

2024-12-03 01:58 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +1. Enter the SQL query in the right section of the page. For example, `SELECT * FROM <ydb_table_name>`.
Given users are entering queries manually, they might still prefer to use the PostgreSQL dialect if they're more familiar with it. Let's keep both options documented?

2025-02-10 02:40 UTC, blinkov commented
@vgvoleg, do you intend to finish this?

2025-03-18 05:14 UTC, blinkov commented
@vgvoleg ping, do you intend to finish this?

2025-06-02 06:32 UTC, vgvoleg commented
we are waiting for the 5.0 release - it is still in progress.

2025-08-28 08:15 UTC, a-s-maslov commented on ydb/docs/ru/core/integrations/visualization/superset.md
>  Apache Superset — это современная платформа для анализа и визуализации данных.
добавить ссылку на сайт прямо здесь и чуть-чуть больше вводного текста про суперсет и про анализ данных в YDB через драйвер и про то, что будет в данной статье??

2025-08-28 08:15 UTC, a-s-maslov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +1. На первом шаге мастера выберите **YDB** из списка **Supported databases**.
написать доп предупреждение, что если вы не видите здесь YDB, значит драйвер не установлен корректно, сходите туда-то ?

2025-08-28 08:15 UTC, a-s-maslov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +    "ydb://{host}:{port}/{database_name}"
на скрине ниже написано просто YDB
тут либо совсем убрать либо например, "YDB local" (и соответственно поправить скрин)

2025-08-28 08:15 UTC, a-s-maslov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Для дополнительной информации о возможностях конфигурации соединения обратитесь к [разделу {{ ydb-short-name }} официальной документации](https://superset.apache.org/docs/configuration/databases#ydb)
наша документация должна быть полной, давай перенесем к себе все что нужно для конфигурации соединения
ссылка на внешнюю документацию тоже нужна, но для "есть еще и там"

2025-08-28 08:15 UTC, a-s-maslov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Чтобы создать подключение к {{ ydb-short-name }} из Apache Superset **версии ниже 5.0.0** с использованием сетевого протокола PostgreSQL, выполните следующие шаги:
давай выделим это прямо в отдельные подразделы (номерные) - оба способа подключения и сделаем к ним вводную, что можно подключаться так и так, но рекомендуем так.

2025-08-28 12:39 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +    "ydb://{host}:{port}/{database_name}"
ой, это лишнее затесалось в ру доку, уберу

2025-08-28 12:43 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Чтобы создать подключение к {{ ydb-short-name }} из Apache Superset **версии ниже 5.0.0** с использованием сетевого протокола PostgreSQL, выполните следующие шаги:
поправил

2025-08-28 12:43 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +    "ydb://{host}:{port}/{database_name}"
поправил

2025-08-28 12:43 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +1. На первом шаге мастера выберите **YDB** из списка **Supported databases**.
поправил

2025-08-28 12:43 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
>  Apache Superset — это современная платформа для анализа и визуализации данных.
поправил

2025-08-28 12:57 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Для дополнительной информации о возможностях конфигурации соединения обратитесь к [разделу {{ ydb-short-name }} официальной документации](https://superset.apache.org/docs/configuration/databases#ydb)
Добавил параметры аутентификации

2025-08-29 08:25 UTC, a-s-maslov reviewed
OK for me

2025-08-29 11:22 UTC, lopatinevgeny requested changes, later dismissed

2025-08-29 11:22 UTC, lopatinevgeny commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +В зависимости от инсталляции Superset сделать это можно разными способами, обратитесь к [официальной документации](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-dock
"сделать это" - что это?

2025-08-29 11:22 UTC, lopatinevgeny commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +1. На первом шаге мастера выберите **YDB** из списка **Supported databases**. Если опция **YDB** недоступна, удостоверьтесь что выполнены все шаги из [пререквизитов](#prerequisites).
```suggestion
1. На первом шаге мастера выберите **YDB** из списка **Supported databases**. Если опция **YDB** недоступна, проверьте, что  [установлены всё необходимое](#prerequisites).
```

2025-08-29 11:22 UTC, lopatinevgeny commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +    * **SQLAlchemy URI** — строка вида `ydb://{host}:{port}/{database_name}`, где **host** и **port** это часть [эндпоинта](../../concepts/connect.md#endpoint) кластера {{ ydb-short-name }}, к которо
```suggestion
    * **SQLAlchemy URI** — строка вида `ydb://{host}:{port}/{database_name}`, где **host** и **port** это соответствующие значения **host** и **port** из [эндпоинта](../../concepts/connect.md#endpoint) кластера {{ ydb-short-name }}, к которому осуществляется подключение, **database_name** - путь к [базе данных](../../concepts/glossary.md#database)
```

2025-08-29 11:34 UTC, vgvoleg commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +В зависимости от инсталляции Superset сделать это можно разными способами, обратитесь к [официальной документации](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-dock
установить драйвер, прошлое предложение же

2025-09-08 03:42 UTC, blinkov requested changes, later dismissed

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +1. Indeed, to provide additional security, you can specify credentials parameters in the `Secure Extra` field at `Advanced / Security` tab.
````suggestion
There are two ways to connect to {{ ydb-short-name }}:

1. Native connection using the SQLAlchemy driver (starting from version 5.0.0)
1. Connect using the PostgreSQL wire protocol

It is recommended to use a native connection whenever possible.

### Native connection using SQLAlchemy driver

To connect to {{ ydb-short-name }} from Apache Superset **version 5.0.0 and higher**, follow these steps:

1. In the Apache Superset toolbar, hover over **Settings** and select **Database Connections**.
1. Click the **+ DATABASE** button.

    The **Connect a database** wizard will appear.

1. In **Step 1** of the wizard, choose **YDB** from the **Supported databases** list. If the **YDB** option is not available, make sure that all the steps from [prerequisites](#prerequisites) are completed.
1. In **Step 2** of the wizard, enter the {{ ydb-short-name }} credentials in the corresponding fields:

    * **Display Name**. The {{ ydb-short-name }} connection name in Apache Superset.
    * **SQLAlchemy URI**. A string in the format `ydb://{host}:{port}/{database_name}`, where **host** and **port** are parts of the [endpoint](../../concepts/connect.md#endpoint) of the {{ ydb-short-name }} cluster to which the connection will be made, and **database_name** is the path to the [database](../../concepts/glossary.md#database).

    ![](_assets/superset-ydb-connection-details.png =400x)

1. To enhance security, you can specify credentials parameters in the **Secure Extra** field under the **Advanced / Security** tab.
````

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/_includes/toc-table.md
>  | [Grafana](https://grafana.com) | Полный| [Инструкция](../grafana.md) |
````suggestion
| [Apache Superset](https://superset.apache.org) | [ydb-sqlalchemy](https://github.com/ydb-platform/ydb-sqlalchemy/releases) | [Инструкция](../superset.md) |
| [DataLens](https://datalens.tech) | Полный | [Инструкция](../datalens.md) |
| [FineBI](https://intl.finebi.com) | Через [PostgreSQL-совместимость](../../../postgresql/intro.md) | [Инструкция](../finebi.md) |
| [Grafana](https://grafana.com) | Полный | [Инструкция](../grafana.md) |
````

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +1. Опцонально, с помощью поля `Secure Extra` во вкладке `Advanced / Security` возможно указать параметры аутентификации.
````suggestion
Подключение к {{ ydb-short-name }} доступно в двух вариантах:

1. Нативное подключение с помощью SQLAlchemy-драйвера (начиная с версии 5.0.0);
1. Подключение с использованием сетевого протокола PostgreSQL.

Рекомендуется использовать нативное подключение, когда это возможно.

### Нативное подключение с помощью SQLAlchemy-драйвера

Чтобы создать подключение к {{ ydb-short-name }} из Apache Superset **версии 5.0.0 и выше**, выполните следующие шаги:

1. В верхнем меню Apache Superset наведите курсор на **Settings** и выберите в выпадающем списке пункт **Database Connections**.
1. Нажмите кнопку **+ DATABASE**.

    Откроется окно мастера **Connect a database**.

1. На первом шаге мастера выберите **YDB** из списка **Supported databases**. Если опция **YDB** недоступна, убедитесь, что [установлены все необходимые компоненты](#prerequisites).
1. На втором шаге мастера введите данные для подключения к {{ ydb-short-name }} в следующие поля:

    * **Display Name** — наименование соединения с {{ ydb-short-name }} в Apache Superset;
    * **SQLAlchemy URI** — строка вида `ydb://{host}:{port}/{database_name}`, где **host** и **port** — соответствующие значения из [эндпоинта](../../concepts/connect.md#endpoint) кластера {{ ydb-short-name }}, **database_name** — путь к [базе данных](../../concepts/glossary.md#database).

    ![](_assets/superset-ydb-connection-details.png =400x)

1. Опционально, с помощью поля `Secure Extra` на вкладке `Advanced / Security` можно указать параметры аутентификации.
````

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +1. Native connection using sqlalchemy driver (starting from version 5.0.0)
I wanted to suggest adding a link to documentation about our integration with sqlalchemy, and it's not in https://ydb.tech/docs/en/integrations/orm/?version=main for some reason.

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +[Apache Superset](https://superset.apache.org/) is a modern data exploration and data visualization platform. This article will explain how to build visualizations on top of the data stored in YDB.
```suggestion
[Apache Superset](https://superset.apache.org/) is a modern data exploration and visualization platform. This article explains how to create visualizations using data stored in {{ ydb-short-name }}.
```

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +The installation method depends on how Superset is set up. For detailed guidance, refer to the [official documentation](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in
```suggestion
To connect to {{ ydb-short-name }} from Superset, install the [ydb-sqlalchemy](https://pypi.org/project/ydb-sqlalchemy) driver.

The installation method depends on your Superset setup. For detailed instructions, see the [official documentation](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-docker-images).
```

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +    * **HOST**. The [endpoint](https://ydb.tech/docs/en/concepts/connect#endpoint) of the {{ ydb-short-name }} cluster to which the connection will be made.
```suggestion
    * **HOST**. The [endpoint](../../concepts/connect.md#endpoint) of the {{ ydb-short-name }} cluster to connect to.
```

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +[Apache Superset](https://superset.apache.org/) — это современная платформа для анализа и визуализации данных. В данной статье будет рассказано, как строить визуализации поверх данных, хранящихся в Y
```suggestion
[Apache Superset](https://superset.apache.org/) — современная платформа для анализа и визуализации данных. В этой статье описано, как создавать визуализации на основе данных, хранящихся в {{ ydb-short-name }}.
```

2025-09-08 03:42 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +В зависимости от инсталляции Superset сделать это можно разными способами, обратитесь к [официальной документации](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-dock
```suggestion
Для работы с {{ ydb-short-name }} необходимо установить драйвер [ydb-sqlalchemy](https://pypi.org/project/ydb-sqlalchemy).

Способ установки зависит от способа развёртывания Superset. Дополнительную информацию см. в [официальной документации Superset](https://superset.apache.org/docs/configuration/databases/#installing-drivers-in-docker-images).
```

2025-09-10 08:19 UTC, fomichev3000 requested changes
А зачем стерли режим совместимости с Postgres? Я бы не стирал

2025-09-10 08:24 UTC, vgvoleg commented
> А зачем стерли режим совместимости с Postgres? Я бы не стирал

так не стирали же, оставили упоминание обоих методов

https://ydb-platform--ydb.viewer.diplodoc.com/en/integrations/visualization/superset?revision=pr-12143-74ddff08aaadcebf7b5e05aa6720427d51b987eb#connect-using-the-postgresql-wire-protocol

2025-09-17 06:22 UTC, fomichev3000 approved these changes

2025-09-17 06:22 UTC, merged