Backup changefeed configurations (tools dump)
ydb-platform/ydb pull request #12283
Opened 2024-12-04 12:39 UTC by stanislav-shchetinin

### Changelog entry

Added a backup of changefeeds when calling the tools dump command in the ydb cli

### Changelog category 

* New feature

### Additional information

Additionally, a SerializeTo method was implemented in the TChangefeedDescription class for Ydb::Table::ChangefeedDescription in the Table client of the YDB CPP SDK

2024-12-09 10:22 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/dump.h
> +    FLUENT_SETTING_DEFAULT(bool, RestoreChangefeed, true);
```suggestion
    FLUENT_SETTING_DEFAULT(bool, RestoreChangefeeds, true);
```

2024-12-09 10:22 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +        client.DescribeTopic(path).GetValueSync();
Нужно обернуть в RetryFunc и проверять статус.

2024-12-09 10:22 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/restore_impl.cpp
> +            if (IsOperationStarted(result.Status())) {
AlterTable AddChangefeed возвращается сразу статус, не операцию.

2024-12-09 10:22 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/restore_impl.cpp
> +        auto result = RestoreChangefeeds(dbPath, dumpedDesc);
В `dumpedDesc` не будет changefeed-ов. Их нужно листить как вложенные директории и конструировать их описание из changefeed_description.pb + topic_description.pb.

2024-12-09 14:45 UTC, CyberROFL requested changes

2024-12-09 14:45 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +
Лишняя пустая строка.

2024-12-09 14:45 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    auto desc = DescribeTable(driver, dirPath);
Можно не вызывать `DescribeTable` второй раз, а передать сюда результат предыдущего вызова из `BackupTable`.

2024-12-09 14:45 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    NYdb::NTopic::TTopicClient client(driver);
Добавь явный include и PEERDIR на ydb/public/sdk/cpp/client/ydb_topic.

2024-12-09 14:45 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    LOG_D("Write changefeed into " << folderPath.Child(fileName).GetPath().Quote());
Странно для метода с таким общим названием `WriteProtoToFile` видеть такую запись в лог. Нужно, наверно, параметризовать строчку для лога и пройтись по всем местам в файле, где зовется PrintToString + Write на вызов этой новой функции (лучше отдельным pr с рефакторингом).

2024-12-09 14:45 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +NTopic::TDescribeTopicResult GetTopicDescription(TDriver driver, const TString& path) {
Можно по аналогии с `DescribeTable` назвать `DescribeTopic`.

2024-12-09 17:03 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    LOG_D("Write changefeed into " << folderPath.Child(fileName).GetPath().Quote());
> лучше отдельным pr с рефакторингом

Вот тут тоже нужно поправить: https://github.com/search?q=repo%3Aydb-platform%2Fydb+PrintToString++path%3Aydb%2Flibrary%2Fbackup&type=code. Сделай, пожалуйста, это отдельным pr, а тут потом сделаешь rebase.

2024-12-09 17:03 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    return childFolderPath;
Это тоже можно отдельным pr немножко отрефакторить: https://github.com/ydb-platform/ydb/blob/c14675811c9df34cffc5d2cdb136ff4317adf488/ydb/library/backup/backup.cpp#L562

2024-12-10 18:36 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_table/table.cpp
> +void TChangefeedDescription::SerializeTo(Ydb::Table::ChangefeedDescription& proto) const {
У тебя с методом выше очень много общего кода, может вынести эту часть в шаблонную функцию?

2024-12-12 10:12 UTC, CyberROFL requested changes
Сделай rebase.

2024-12-12 10:12 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +#include <ydb/public/sdk/cpp/client/ydb_topic/include/client.h>
```suggestion
#include <ydb/public/sdk/cpp/client/ydb_topic/topic.h>
```

2024-12-12 13:12 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_table/table.cpp
> +template<typename ProtoType>
```suggestion
template<typename TProtoType>
```

2024-12-12 13:18 UTC, CyberROFL requested changes

2024-12-12 13:18 UTC, CyberROFL commented on ydb/public/sdk/cpp/client/ydb_table/table.h
> +    template<typename TProto>
```suggestion
    template <typename TProto>
```

2024-12-12 13:18 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    auto desc = DescribeTable(driver, dirPath);
Переоткрыл

2024-12-12 13:18 UTC, CyberROFL commented on ydb/public/sdk/cpp/client/ydb_table/table.cpp
> +template<typename ProtoType>
```suggestion
template <typename TProto>
```

2024-12-12 13:18 UTC, CyberROFL commented on ydb/public/sdk/cpp/client/ydb_table/table.cpp
> +        case EChangefeedMode::KeysOnly:
Нет смысла в этих изменениях.

2024-12-12 13:57 UTC, Gazizonoki submitted a review, later dismissed

2024-12-12 16:30 UTC, CyberROFL approved these changes

2024-12-12 16:32 UTC, Gazizonoki approved these changes

2024-12-12 17:27 UTC, merged