Add new UT in PDisk for TEvChunkWrite contract
ydb-platform/ydb pull request #12298
Opened 2024-12-04 18:54 UTC by va-kuznecov

### Changelog entry 

Fix PDisk didn't check TEvChunkWrite's offset and wrote data to with an unexpected offset. Add UT for that case.

### Changelog category 

* Bugfix 

### Additional information

...

2024-12-04 18:59 UTC, robdrynkin commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
> +                TBuffer x;
not needed

2024-12-04 19:55 UTC, SammyVimes requested changes
also TStrokaBackedUpParts is still used somewhere

2024-12-04 19:55 UTC, SammyVimes commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
> +                        Cerr << x.size();
Leftovers

2024-12-05 12:46 UTC, va-kuznecov commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
> +                TBuffer x;
fixed

2024-12-05 18:44 UTC, SammyVimes approved these changes

2024-12-06 09:53 UTC, merged