Add ydb cli replace and fetch storage config commands
ydb-platform/ydb pull request #12312
Opened 2024-12-05 10:52 UTC by mregrock

### Changelog entry 

Add ydb cli replace and fetch commands into ydb_cli

### Changelog category 

* New feature

### Additional information

...

2024-12-05 11:06 UTC, alexvru requested changes

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.h
> +#include <util/generic/string.h>
do you really need all these includes?

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.h
> +        TStatus&& status,
maybe one tab right, so it doesn't mix up with member initializers?

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.h
> +    class TImpl;
make it private

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.h
> +    std::shared_ptr<TImpl> Impl_;
std::unique_ptr, you're not sharing it with anyone else

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.cpp
> +
extra line

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.cpp
> +    const TString& config,
+tab; and your screen is wider than 80 chars, yeah? why not use it at full? at least 120/128 chars wide

2024-12-05 11:06 UTC, alexvru commented on ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.cpp
> +        Connections_->RunDeferred<Ydb::BSConfig::V1::BSConfigService, Ydb::BSConfig::FetchStorageConfigRequest, Ydb::BSConfig::FetchStorageConfigResponse>(
RunSimple fits better (I think so, but not completely sure)

2024-12-05 11:08 UTC, maximyurchuk commented on contrib/python/ydb/py3/ya.make
> +    ydb/storage_config.py
Это (contrib) прилетает из аркадии и должно правиться там

2024-12-06 08:37 UTC, alexvru approved these changes

2024-12-06 09:07 UTC, maximyurchuk approved these changes
Пробемные файлы были убраны

2024-12-06 09:31 UTC, pnv1 commented
Добавляются новые команда в CLI. Был ли саппорт на эту тему?

2024-12-06 10:29 UTC, mregrock commented
> Добавляются новые команда в CLI. Был ли саппорт на эту тему?

Саппорт был, команды аппрувнули

2024-12-06 12:13 UTC, pnv1 approved these changes

2024-12-06 12:42 UTC, merged