Async replication consistency levels
ydb-platform/ydb pull request #12365
Opened 2024-12-06 12:47 UTC by CyberROFL

### Changelog entry 

Described asynchronous replication's consistency levels.

### Changelog category 

* New feature

### Additional information

...

2024-12-08 13:55 UTC, fomichev3000 requested changes

2024-12-08 13:55 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +### Глобальная согласованность данных {#consistency-level-global}
Не хватает явного описания глобальной согласованности, а не метода имплементации. Я бы написал, что мы реплицируем набор таблиц. Данные в этим таблицах "проявляются" согласованно, как после применения набора изменений оригинальных таблиц в порядке Serializable (ну фразу лучше попонятнее написать)

2024-12-08 13:55 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `COMMIT_INTERVAL` — [периодичность фиксации изменений](../../../concepts/async-replication.md#commit-interval) в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601). Значение по умолчани
Не понятно, как COMMIT_INTERVAL связан с RESOLVED_TIMESTAMPS. Похоже, что это оно и есть. Только RESOLVED_TIMESTAMPS свойство changefeed, а COMMIT_INTERVAL свойство async repl. И async repl создает changefeed в котором устанавливает RESOLVED_TIMESTAMPS. Если это так, то я предлагаю так и написать в документации

2024-12-08 13:55 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +* `RESOLVED_TIMESTAMPS` — периодичность выгрузки [меток-барьеров](../../../../concepts/cdc.md#resolved-timestamps). Тип значения — `Interval`. По умолчанию выключено.
Оооочень смущает название RESOLVED_TIMESTAMPS. Фактически это поле типа Interval, а называется оно как будто имеет тип bool. Посмотри на VIRTUAL_TIMESTAMPS, которое bool.
И называется оно очень не понятно само по себе. Даже в документации оно описывается как barriers interval, если перевести на английский. Может так и назвать?

2024-12-09 17:09 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +* `RESOLVED_TIMESTAMPS` — периодичность выгрузки [меток-барьеров](../../../../concepts/cdc.md#resolved-timestamps). Тип значения — `Interval`. По умолчанию выключено.
Может `RESOLVED_TIMESTAMPS_INTERVAL`?

2024-12-09 18:54 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `COMMIT_INTERVAL` — [периодичность фиксации изменений](../../../concepts/async-replication.md#commit-interval) в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601). Значение по умолчани
Дописал в соседнем файле. Здесь хочется оставить короткие описания опций и ссылки на соответствующие разделы с более подробным описанием.

2024-12-10 06:06 UTC, fomichev3000 submitted a review, later dismissed

2025-06-23 15:29 UTC, fomichev3000 requested changes

2025-06-23 15:29 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +По умолчанию изменения фиксируются (коммитятся) не чаще, чем раз в 10 секунд. Периодичность фиксации изменений можно переопределить, указав опцию [COMMIT_INTERVAL](../yql/reference/syntax/create-asyn
"по умолчанию изменения фиксируются (коммитятся) не чаще, чем раз в 10 секунд"
Эта фраза грустная. Я сначала подумал, что ошибка, должно быть "не реже", как в батчинге. Но прочитал весь текст -- нет. 
По сути ты сейчас пользователю сказал [10sec, +infinity). Ну то есть "никогда" -- это возможное поведение. А ему не нужна такая система

2025-06-23 15:29 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +Периодичность фиксации изменений напрямую влияет на периодичность выгрузки барьеров в потоки изменений — значения параметров синхронизированы. Таким образом, обычно, изменения фиксируются с той же ча
Сразу возникает вопрос, а как отслеживать отставание?

2025-06-26 13:01 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +По умолчанию изменения фиксируются (коммитятся) не чаще, чем раз в 10 секунд. Периодичность фиксации изменений можно переопределить, указав опцию [COMMIT_INTERVAL](../yql/reference/syntax/create-asyn
Ну, на принимающей стороне невозможно "подпинывать" транзакции в источнике. Условно, отставание репликации — это `Max(CommitInterval, TxCompleteLag)`, где `TxCompleteLag` — это отставание выполнения транзакций в источнике.
Я не нашел в документации ничего про TxCompleteLag, поэтому предлагаю описать это отдельно: https://github.com/ydb-platform/ydb/issues/20236

2025-06-29 13:53 UTC, fomichev3000 approved these changes
Я ОКнул, но рекомендую принять мои изменения. На русском языке они полностью готовы

2025-06-29 13:53 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/cdc.md
> +Барьеры — записи "пустышки" (без данных об изменении или удалении) с [виртуальными метками времени](#virtual-timestamps), которые появляются в каждой партиции топика с заданной периодичностью. Барьер
Я бы не использовал слово "пустышки".  Лучше использовать "служебное сообщение"

2025-06-29 13:53 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +В данном режиме потоки изменений создаются с включенными [барьерами](cdc.md#barriers). Между барьерами данные буферизируются непосредственно на партициях объектов-реплик. При получении очередной порц
```suggestion
Для обеспечения глобальной согласованности данных необходимо создавать потоки изменений с включенными [барьерами](cdc.md#barriers). Между барьерами данные буферизируются непосредственно на партициях объектов-реплик. При получении очередной порции барьеров от всех топиков записанные изменения фиксируются и становятся доступными для чтения. При этом данные в приемнике оказываются согласованными на момент времени, указанном в барьере. Если считать, что на источнике барьеры создаются каждые 10 секунд, то в нормальном режиме приемник коммитит и публикует набор изменений от источника каждые 10 секунд.
```

2025-06-29 13:53 UTC, merged

2025-06-30 14:05 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/cdc.md
> +Барьеры — записи "пустышки" (без данных об изменении или удалении) с [виртуальными метками времени](#virtual-timestamps), которые появляются в каждой партиции топика с заданной периодичностью. Барьер
https://github.com/ydb-platform/ydb/pull/20387

2025-06-30 14:05 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +В данном режиме потоки изменений создаются с включенными [барьерами](cdc.md#barriers). Между барьерами данные буферизируются непосредственно на партициях объектов-реплик. При получении очередной порц
https://github.com/ydb-platform/ydb/pull/20387