new tiered_ttl mode in public TtlSettings
ydb-platform/ydb pull request #12405
Opened 2024-12-09 11:14 UTC by swalrus1

### Changelog entry 

...

### Changelog category 

* New feature

### Additional information

...

2024-12-17 12:31 UTC, asmyasnikov approved these changes

2024-12-18 04:52 UTC, vlad-gogov requested changes

2024-12-18 04:52 UTC, vlad-gogov commented on ydb/core/ydb_convert/table_settings.cpp
> +                            if (*columnUnit != mode.column_unit()) {
Вроде бы можно объединить два if в в один

2024-12-18 04:52 UTC, vlad-gogov commented on ydb/core/ydb_convert/table_settings.cpp
> +                    if (*columnName != tierColumnName) {
По аналогии с замечанием выше

2024-12-18 04:52 UTC, vlad-gogov commented on ydb/core/ydb_convert/table_settings.cpp
> +                    if (*expressionType != inTier.expression_case()) {
По аналогии с замечанием выше

2024-12-18 07:38 UTC, vlad-gogov approved these changes

2024-12-18 07:38 UTC, merged