less query id labels
ydb-platform/ydb pull request #12427
Opened 2024-12-09 16:38 UTC by uzhastik

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-10 07:13 UTC, dorooleg requested changes

2024-12-10 07:13 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        queryCounters.PublicCounters = publicCountersParent->GetSubgroup("query_id", queryIdLabel);
А почему публичные метрики поменялись. Пускай у пользователя остается как было, это же их шарды?

2024-12-10 07:13 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        queryCounters.RootCounters = rootCountersParent->GetSubgroup("query_id", queryIdLabel);
Похоже потерялся folder_id Без него же совсем все сожмется. Нужно добавить его к префиксу чтобы хотя бы фолдеры отличать между собой

2024-12-10 07:13 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +            if (task.query_type() == FederatedQuery::QueryContent::ANALYTICS) {
Еще хотели name квери тоже в метрики опускать для стриминга, так сможем алерты строить по таким запросам. Будем вбивать паттерн name"'*WATCHDOG*' по которому алерт построим

2024-12-10 21:10 UTC, uzhastik commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        queryCounters.RootCounters = rootCountersParent->GetSubgroup("query_id", queryIdLabel);
я его специально отсюда убрал, т.к. он есть в другой метке scope

2024-12-10 21:30 UTC, uzhastik commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        queryCounters.PublicCounters = publicCountersParent->GetSubgroup("query_id", queryIdLabel);
по тем же причинам - вероятность переполнения

2024-12-10 21:43 UTC, uzhastik commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +            if (task.query_type() == FederatedQuery::QueryContent::ANALYTICS) {
это сделаю

2024-12-13 13:05 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        queryCounters.PublicCounters = publicCountersParent->GetSubgroup("query_id", queryIdLabel);
Так это же в их власти, не хотят переполнение жмут ModifyQuery или увеличивают квоты. Иначе они в диагностике теряют

2024-12-13 14:35 UTC, dorooleg requested changes

2024-12-13 14:35 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +                queryIdLabel = "manual";
Для аналитики думаю тоже будет полезно query_name задавать, хоть как-то графики сможем строить

2024-12-13 14:35 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        } else {
`else if` немного вложенностей меньше станет

2024-12-13 14:35 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +            queryPublicCounters = queryPublicCounters->GetSubgroup("query_name", queryNameLabel);
Мне кажется для пользователей можно и обычные id отгружать, это же их собственные шарды. И там метрики не будут по хостам и прочего. Будет 6 метрик на запрос, не так много кмк. Старые будут помирать, но зато хотя бы пользователям будет удобно

2024-12-13 14:39 UTC, dorooleg requested changes

2024-12-13 14:39 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +        if (queryNameLabel) {
А как оно бдует работать с пустыми метками. query_name="*", как будут отображаться запросы без имени, как '-' или еще что-то?

2024-12-13 14:39 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +                // todo: sanitize query name
Нужно функцию Димы вызвать для sanitizer

2024-12-13 19:29 UTC, dorooleg commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +            queryPublicCounters = queryPublicCounters->GetSubgroup("query_name", queryNameLabel);
Хотя для аналитики же есть timeline, может тогда и не плохая идея сжать такие графики и для пользователей

2024-12-17 12:29 UTC, uzhastik commented on ydb/core/fq/libs/actors/pending_fetcher.cpp
> +            queryPublicCounters = queryPublicCounters->GetSubgroup("query_name", queryNameLabel);
оставил query_id

2024-12-17 14:33 UTC, dorooleg approved these changes

2024-12-17 14:33 UTC, merged