Refactoring ydb/library/backup/backup.cpp
ydb-platform/ydb pull request #12432
Opened 2024-12-09 17:23 UTC by stanislav-shchetinin

### Changelog entry
...

### Changelog category 

* Not for changelog

### Additional information

Added functions CreateDirectory and WriteProtoToFile, and created the FilesType enum.

2024-12-09 18:29 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> -static constexpr const char *SCHEME_FILE_NAME = "scheme.pb";
Тогда стоит выделить типы/названия файлов в общую библиотеку а-ля ydb/public/lib/ydb_cli/dump/files, чтобы и тут переиспользовать: https://github.com/ydb-platform/ydb/blob/9216a5ba62acecff59fe723c840b9c3edea78a38/ydb/public/lib/ydb_cli/dump/dump.cpp#L14-L17

2024-12-09 18:29 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +    "scheme.pb",
Смущает, что `FILE_NAME` и `OBJ_TYPE` могут разъехаться как с `FilesType`, так и между собой.
Лучше завести какой-нибудь контейнер, где ключ (или индекс) — это тип, а значение — структура:
```cpp
struct TFileInfo {
    TString FileName;
    TString LogObjectType;
};
```

2024-12-09 18:29 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +        auto tmpFile = TFile(folderPath.Child(FILE_NAME[INCOMPLETE_DATA]), CreateAlways | WrOnly);
А здесь лучше обращаться не к глобальному контейнеру, а сделать именованный метод:
```cpp
namespace NYdb::NDump::NFiles {

const TFileInfo& IncompleteData();
const TFileInfo& TableScheme();
...

}
```

А enum с типами файлов вообще спрятать в cpp, т.к. он нужен только для доступа по ключу внутри контейнера, доступ до самого контейнера сразу библиотеки не нужен, т.к. будут именованные методы.

2024-12-09 18:29 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +enum FilesType {
`EFilesTypes`.

2024-12-10 12:30 UTC, stanislav-shchetinin commented on ydb/library/backup/backup.cpp
> +        auto tmpFile = TFile(folderPath.Child(FILE_NAME[INCOMPLETE_DATA]), CreateAlways | WrOnly);
Я же в метод WriteProtoToFile передаю одним из параметров значение enum'а, значит мне нужно дать доступ к нему, а контейнер могу скрыть

2024-12-10 12:33 UTC, stanislav-shchetinin commented on ydb/library/backup/backup.cpp
> -static constexpr const char *SCHEME_FILE_NAME = "scheme.pb";
Не лучше ли в ydb/library/backup/files, т.к. WriteProtoToFile реализован там?

2024-12-10 18:51 UTC, CyberROFL commented on ydb/library/backup/backup.cpp
> +        auto tmpFile = TFile(folderPath.Child(FILE_NAME[INCOMPLETE_DATA]), CreateAlways | WrOnly);
Передавай в него `const TFileInfo&`.

2024-12-11 10:55 UTC, CyberROFL requested changes
А почему ты сразу не заиспользовал эту библиотеку?

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/ya.make
Наверно, всё-таки `files`. У тебя и namespace называется `NFiles`.

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/ya.make
> +    ydb/public/lib/ydb_cli/dump/util
Не вижу, чтобы что-то оттуда использовалось.

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/files.h
> +#include <util/folder/path.h>
Не используется в этом файле.

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/files.cpp
> +#include <util/system/file.h>
Не используется в этом файле.

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/files.cpp
> +    EMPTY
```suggestion
    EMPTY,
```

Чтобы при расширении списка не нужно было исправлять эту строчку.

2024-12-11 10:55 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/file/files.cpp
> +    {"empty_dir", "empty_dir"}
```suggestion
    {"empty_dir", "empty_dir"},
```

2024-12-11 13:04 UTC, CyberROFL requested changes

2024-12-11 13:04 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/dump.h
> +#include <ydb/public/lib/ydb_cli/dump/files/files.h>
Здесь ничего из этой библиотеки не используется.

2024-12-11 13:04 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/restore_impl.cpp
А вот в этом файле уже нужен `#include <ydb/public/lib/ydb_cli/dump/files/files.h>`.

2024-12-11 13:04 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/files/files.h
> +namespace NYdb::NBackup::NFiles {
```suggestion
namespace NYdb::NDump::NFiles {
```

2024-12-11 13:04 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/restore_impl.cpp
> +    if (IsFileExists(fsPath.Child(NBackup::NFiles::Incomplete().FileName))) {
Когда `NBackup` переименуешь в `NDump`, то тут и далее можно будет сократить до `NFiles::Incomplete()`.

2024-12-11 16:41 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/restore_impl.h
> +#include <ydb/public/lib/ydb_cli/dump/files/files.h>
Оно ведь используется не тут, а в restore_impl.cpp

2024-12-11 16:47 UTC, CyberROFL approved these changes

2024-12-11 17:02 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/dump/files/files.cpp
> +};
А зачем тут заводить енум и массив структур? Не проще сразу в функциях возвращать?

2024-12-11 17:09 UTC, stanislav-shchetinin commented on ydb/public/lib/ydb_cli/dump/files/files.cpp
> +};
Тогда по идее на каждый вызов будет новый объект создаваться

2024-12-11 17:10 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/dump/files/files.cpp
> +};
Удобно, когда всё в одном месте. Функции для удобства пользования библиотекой.

2024-12-11 17:27 UTC, Gazizonoki approved these changes

2024-12-11 17:27 UTC, merged