YQ-3836 improved metadata objects errors
ydb-platform/ydb pull request #12486
Opened 2024-12-11 08:24 UTC by GrigoriyPA

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-13 12:41 UTC, dorooleg requested changes

2024-12-13 12:41 UTC, dorooleg commented on ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
> +        case EActivityType::Create:
Это выглядит максимально странно теперь, нужно в двух местах теперь писать `EActivityType::Create`

2024-12-13 12:41 UTC, dorooleg commented on ydb/services/metadata/abstract/request_features.cpp
> +std::optional<TString> TFeaturesExtractor::ValidateResetFeatures() const {
Почему exception в этом месте не подходил?

2024-12-13 12:41 UTC, dorooleg commented on ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
> +TString GetOrEmpty(const NYql::TCreateObjectSettings& container, const TString& key) {
Похоже в этом ревью все намешалось:
1. Рефакторинг
2. Не печатать строчку кода в пользовательские ошибки
3. Изменение возвращаемых статусов

2024-12-23 11:09 UTC, GrigoriyPA commented on ydb/services/metadata/abstract/request_features.cpp
> +std::optional<TString> TFeaturesExtractor::ValidateResetFeatures() const {
Это было не очень консистентно с тем, как работает метод класса GetRemainedParamsString, через него достаётся ошибка, если были указаны лишние параметры:
https://github.com/ydb-platform/ydb/blob/9e617a40911fa1bde14607cac10b8e6759d1eacf/ydb/services/metadata/abstract/request_features.h#L29

Решил сделать аналогично для лишних параметров в блоке RESET (ну и кажется в metadata service чаще используется именно статус)

2024-12-23 11:11 UTC, GrigoriyPA commented on ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
> +TString GetOrEmpty(const NYql::TCreateObjectSettings& container, const TString& key) {
Да, рефакторинг я ещё хотел сделать, когда добавлял resource_pool, так как тогда вышло довольно много копипасты, сейчас её постарался убрать + убрал throw и большинства мест, чтобы не отловленное исключение мапилось в INTERNAL_ERROR, а в остальных местах явно бы прописывался статус ошибки

2024-12-25 16:10 UTC, dorooleg approved these changes

2024-12-27 06:18 UTC, merged