New UserDb
ydb-platform/ydb pull request #1251
Opened 2024-01-24 08:14 UTC by azevaykin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-24 08:30 UTC, snaury commented on ydb/core/tx/datashard/datashard_user_db.cpp
> +        Db.UpdateTx(localTableId, NTable::ERowOp::Upsert, key, ops, LockTxId);
Навскидку здесь баг, мы должны писать через UpdateTx также если VolatileTxId != 0.

2024-01-24 08:34 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
> -    const ui64& LockTxId;
Обрати внимание, что тут была ссылка на поле в другом классе, оно там как-то хитро мутировало в процессе работы.

2024-01-24 08:55 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
> -    const ui64& LockTxId;
Вроде нет ошибки, ничего хитрого тут
https://github.com/ydb-platform/ydb/pull/1251/files#diff-ac089152b6037eb7d26fe0b9d5122a7327661da54d34fcd82ce384b3f1e91d81L1222

2024-01-24 09:14 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.cpp
> +        Db.UpdateTx(localTableId, NTable::ERowOp::Upsert, key, ops, LockTxId);
[Поправил](https://github.com/ydb-platform/ydb/compare/3057def0a0c4b1a13cd3cfe2292b32535182fe64..e24e502ac99a89fa7fb502583801754236daf77b)

2024-01-25 08:41 UTC, snaury requested changes

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void AddWriteConflict(ui64 txId) const {
Насколько я вижу этот метод больше никто не вызывает.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void BreakWriteConflict(ui64 txId) {
Аналогично, этот локальный метод больше не вызывается.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckWriteConflicts(const TTableId& tableId, TArrayRef<const TCell> keyCells) {
Насколько я вижу этот метод сейчас вызывается только из EraseRow. На самом деле EraseRow ничем не отличается от UpdateRow кроме операции ERowOp, возможно стоит просто в UpdateRow добавить поддержку указания ERowOp? Тогда этот метод можно будет также убрать.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckReadDependency(ui64 txId) const {
Этот метод не используется.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckReadConflict(const TRowVersion& rowVersion) const {
Этот метод не используется.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void AddReadConflict(ui64 txId) const {
Этот метод не используется.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard_kqp_compute.h
> +    TKqpDatashardComputeContext(NDataShard::TDataShard* shard, TEngineHost& engineHost, NDataShard::TDataShardUserDb& userDb);
Минорное: смущает, что здесь зависимость и от engine host и от user db, точно ли нужны обе? А также в идеале на вход получать интерфейс, а не конкретную реализацию.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard_user_db.h
> +    void CommitChanges(const TTableId& tableId, ui64 lockId, const TRowVersion& writeVersion);
Метод в какой-то странной группе, ниже без отступа public и тоже что-то про коммиты. Также меня смущает обилие публичных методов в .h файле, которые не реализуют никакой интерфейс. Понятно, что сейчас они просто из engine host'а приехали, но в будущем хотелось бы какой-то интерфейсной логичности. Пока хотя бы сгруппировать методы по смыслу.

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard_user_db.cpp
> +                SetVolatileTxId(StepTxId.TxId);
Здесь нужно учитывать, что этот TxId может быть равен 0, и в этом случае нужно заказывать GlobalTxId...

2024-01-25 08:41 UTC, snaury commented on ydb/core/tx/datashard/datashard__engine_host.cpp
> +        Settings.KeyAccessSampler->AddSample(tableId, row);
Имхо семплинг и обновление счётчиков в user db тоже нужно.

2024-01-25 09:19 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
> +        Settings.KeyAccessSampler->AddSample(tableId, row);
[KeyAccessSampler](https://github.com/ydb-platform/ydb/pull/1251/commits/70ab76cd5be2b5b698c23b6006f0e9192ab82606)

2024-01-25 11:59 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
> +        Settings.KeyAccessSampler->AddSample(tableId, row);
[EngineHostCounters in UserDb](https://github.com/ydb-platform/ydb/pull/1251/commits/890de28d484bae2828a965fb224a26489b77ecac)

2024-01-25 12:06 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.h
> +    void CommitChanges(const TTableId& tableId, ui64 lockId, const TRowVersion& writeVersion);
Я старался собирать методы по смыслу. Немного переупорядочил. Если недостаточно, скажи.
32c3e9face3f018bb42f8075497e33256b2bcb8a

2024-01-25 14:16 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_kqp_compute.h
> +    TKqpDatashardComputeContext(NDataShard::TDataShard* shard, TEngineHost& engineHost, NDataShard::TDataShardUserDb& userDb);
[Убрал TEngineHost](https://github.com/ydb-platform/ydb/pull/1251/commits/2832198baacfd8e1cc94602e5d2b9ca8edb0eb5f)

2024-01-25 15:25 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.h
> +    YDB_READONLY(TStepOrder, StepTxId, TStepOrder(0, 0));
Реально используется только TxId. А значит туда нужно передавать GetGlobalTxId. В конструктор вместо step order передавать global tx id.

2024-01-25 15:39 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void BreakWriteConflict(ui64 txId) {
[Удалил метод](https://github.com/ydb-platform/ydb/pull/1251/commits/d8ee202fde13f5d83acaed69505e6d5f2ddfb18a)

2024-01-25 15:39 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void AddWriteConflict(ui64 txId) const {
[Удалил метод](https://github.com/ydb-platform/ydb/pull/1251/commits/d8ee202fde13f5d83acaed69505e6d5f2ddfb18a)

2024-01-25 15:40 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckReadDependency(ui64 txId) const {
[Удалил метод](https://github.com/ydb-platform/ydb/pull/1251/commits/d8ee202fde13f5d83acaed69505e6d5f2ddfb18a)

2024-01-25 15:40 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckReadConflict(const TRowVersion& rowVersion) const {
[Удалил метод](https://github.com/ydb-platform/ydb/pull/1251/commits/d8ee202fde13f5d83acaed69505e6d5f2ddfb18a)

2024-01-25 15:40 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void AddReadConflict(ui64 txId) const {
[Удалил метод](https://github.com/ydb-platform/ydb/pull/1251/commits/d8ee202fde13f5d83acaed69505e6d5f2ddfb18a)

2024-01-26 05:34 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.cpp
> +                SetVolatileTxId(StepTxId.TxId);
[GlobalTxId](https://github.com/ydb-platform/ydb/pull/1251/commits/420ec488992f1b401c42266ec91f5091230536b4)

2024-01-26 05:35 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.h
> +    YDB_READONLY(TStepOrder, StepTxId, TStepOrder(0, 0));
[GlobalTxId](https://github.com/ydb-platform/ydb/pull/1251/commits/420ec488992f1b401c42266ec91f5091230536b4)

2024-01-26 05:59 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__engine_host.cpp
>      void CheckWriteConflicts(const TTableId& tableId, TArrayRef<const TCell> keyCells) {
[EraseRow](https://github.com/ydb-platform/ydb/pull/1251/commits/48d0913645b854c5fad86a8121c49999701b587c)

2024-01-26 08:04 UTC, snaury requested changes

2024-01-26 08:25 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_user_db.cpp
> +    if (specUpdates.HasUpdates) {
Вынес в родительскую функцию

[Erase & Update fix](https://github.com/ydb-platform/ydb/pull/1251/commits/71fea13c1e396669a6d523f22eb154b5bc474452)

2024-01-26 08:50 UTC, snaury approved these changes

2024-01-26 10:29 UTC, merged