Run olap scenario tests on local ydb cluster
ydb-platform/ydb pull request #12512
Opened 2024-12-11 13:49 UTC by zverevgeny

### Changelog category 
* Not for changelog (changelog entry is not required)

2024-12-11 16:11 UTC, iddqdex requested changes
Мне не нравится идея затащить Harness кластер прямо в ydb_cluster. Конфигурация кластера может быть разная для разных тестов, передавать это сюдя будет неудобно. Буквально недавно я решал полностью аналогичную задачу для нагрузочных тестов, вот тут год, посмотри: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/functional/tpc/conftest.py

2024-12-11 16:16 UTC, iddqdex commented
Кроме предыдущего. Я бы разделил тесты, запускаемые локально и тесты, которые запускаются на кластере, эти множества могут не совпадать. Делил бы я их через запуск в разных ya.make c переиспользованием кода тестов. Примеры опять же из нагрузочных. Локально: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/functional/tpc/ya.make , на кластере: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/olap/load/ya.make

2024-12-11 16:24 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
И кстати, при таком старте не создается db, а без нее ydb работает странно. Например не создается таблетка статистики. Пример как стартовать есть в нагрузочных тестах выше.

2024-12-11 16:30 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +    ydb_endpoint = get_external_param('ydb-endpoint', "")
Обычно в питоне пишут что-то типа 
```
ydb_endpoint = get_external_param('ydb-endpoint', None)
```
А потом что-то типа 
```
if ydb_endpoint is not None:
    ...
```

2024-12-11 16:31 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
А где stop для кластера?

2024-12-11 16:57 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Я, конечно, допишу stop. А что бывает, если до stop не дойдёт выполнение? Кластера будут висеть вечно?

2024-12-11 21:09 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +    ydb_database = get_external_param('ydb-db', "/Root").lstrip('/')
Тут же некорректно кажется написано, если этот дефолт на случай "так называется база в KiKiMR(...)", надо явно спросить название у KiKiMR

2024-12-11 22:15 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Я думаю его убьет ya make в неопределенный момент времени (но не уверен)

2024-12-11 22:17 UTC, maximyurchuk commented on ydb/tests/olap/scenario/ya.make
> +    SIZE(MEDIUM)
Под asan и другими санитайзерами он тоже medium? Посмотри время исполнения в проверках плз, если >3 мин предлагаю для санитайзеров пометить как large

2024-12-11 22:41 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +                    raise "Double temporary cluster initialization attempt"
Я если честно не понял на какой это случай сделано

2024-12-12 05:44 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +                    raise "Double temporary cluster initialization attempt"
Проверка инварианта: сюда попадать не должны

2024-12-12 17:22 UTC, zverevgeny commented
> Мне не нравится идея затащить Harness кластер прямо в ydb_cluster. Конфигурация кластера может быть разная для разных тестов, передавать это сюдя будет неудобно. Буквально недавно я решал полностью аналогичную задачу для нагрузочных тестов, вот тут код, посмотри: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/functional/tpc/conftest.py

Тогда непонятна зона ответсвенности класса YdbCluster. Сейчас это "синглтон", предоставляющий доступ к какому-то реальному ydb кластеру. Правильно ли я понимаю, что ты предлагаешь разделить этот класс, по-сути, на два:

2024-12-12 19:37 UTC, zverevgeny commented
> Кроме предыдущего. Я бы разделил тесты, запускаемые локально и тесты, которые запускаются на кластере, эти множества могут не совпадать. Делил бы я их через запуск в разных ya.make c переиспользованием кода тестов. Примеры опять же из нагрузочных. Локально: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/functional/tpc/ya.make , на кластере: https://github.com/ydb-platform/ydb/blob/main/ydb/tests/olap/load/ya.make

Пока нет необходимости в разделении. Хотим уметь запускать все тесты и локально и на долгоживущем кластере.

2024-12-12 19:39 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +    ydb_database = get_external_param('ydb-db', "/Root").lstrip('/')
Поправил. Убрал странный дефолт

2024-12-12 19:40 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +    ydb_endpoint = get_external_param('ydb-endpoint', "")
Поправил

2024-12-12 19:43 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Довольно много тестов сейчас создают кластер именно таким способом. Если это некорректно, то нужно править их все. Можно создать тикет на это.

2024-12-12 19:53 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Ну конкретно на отсутствие таблетки со статистикой мы с Монстром наткнулись. Я не могу сказать, что ещё не создалось. Может и ничего критичного

2024-12-12 20:01 UTC, iddqdex commented
> Правильно ли я понимаю, что ты предлагаешь разделить этот класс, по-сути, на два:
> 1 - отвечающий за создание/существование самого кластера
> 2 - отвечающий за доступ к существующему (за счёт п.1) кластеру

Да, ты сформулировал лучше меня.
При этом класс из п.1 - это harness cluster,  а из п. 2 - существующий ydb_cluster

2024-12-13 03:23 UTC, zverevgeny commented
> > Правильно ли я понимаю, что ты предлагаешь разделить этот класс, по-сути, на два:
> > 1 - отвечающий за создание/существование самого кластера
> > 2 - отвечающий за доступ к существующему (за счёт п.1) кластеру
> 
> Да, ты сформулировал лучше меня. При этом класс из п.1 - это harness cluster, а из п. 2 - существующий ydb_cluster

Выделил п.1 в отдельный YdbClusterInstance

2024-12-13 03:29 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Не нашёл в текущей реализации хелперов, куда можно вставить stop, чтобы он гарантированно вызывался. Можно переписать все хелперы со статических классов на обычные инстансы, тогда можно будет останавливать в teardown_class. Но это требует больших изменений, чем этот PR.
Я в питоне не спец, если подскажетет, куда можно вставить stop, вставлю. 

Проверил, что при завершении запуска через ya test запущенный кластер тоже ydb завершается.

2024-12-14 17:36 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +            self._endpoint = "%s:%d" % (node.host, node.port)
Тут нужно указать схему, она по умолчанию grpcs. Надо явно прописать "grpc://"

2024-12-14 17:36 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +            if cls._ydb_cluster_instance is not None:
Эта логика сломает как минимум тесты ydb/tests/functional/tpc. Там создается кластер снаружи, присваиваются значение ydb_endpoint и ydb_database. Это логика создаст кластер заново с настройками по умолчанию, а тот останется не у дел.

2024-12-14 17:36 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +            cluster = YdbClusterInstance(cls.ydb_endpoint, cls.ydb_database)
Проблема осталась старая. Кластер всегда создается один и тот же, для разных тестов, без возможности настройки. Нельзя например для одного теста сделать кластер из 1 ноды, а для другого - из 5. Поэтому по прежнему считаю, что место этой логики - ближе к конкретному тесту, а не внутри этой библиотеки.

2024-12-14 17:36 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +class YdbClusterInstance:
Не очень понимаю, зачем вообще этот класс нужен. Он по сути своей обертка над KikiMR. Может его напрямую и использовать?

2024-12-15 06:35 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +            cluster = YdbClusterInstance(cls.ydb_endpoint, cls.ydb_database)
Так я так и хочу. Цель этого изменения запускать тесты на PR чеках на одном локальном кластере. Точно так же, как и они запускаются на одном внешнем кластре

2024-12-15 06:38 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +class YdbClusterInstance:
Этот классс инкапсулирует кластер, на котором запускаются тесты. И может представлять либо внешний долгоживущий кластер, либо временный, создаваемый на время запуска тестов

2024-12-15 06:44 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +            self._endpoint = "%s:%d" % (node.host, node.port)
Указал, но и со значением по-умолчанию тоже работало.

2024-12-15 06:53 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +            if cls._ydb_cluster_instance is not None:
Не сломает. YdbClusterInstance поддерживает оба варианта

2024-12-15 06:54 UTC, zverevgeny commented on ydb/tests/olap/lib/ydb_cluster.py
> +        cluster.start()
Сделал остановку с помощью atexit

2024-12-15 19:06 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +        atexit.register(self.__del__)
Это какое-то хакерство, предлагаю сделать явный метод stop

2024-12-15 19:20 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +            config = KikimrConfigGenerator(extra_feature_flags=[])
extra_feature_flags лишнее, оно скорее всего и так в дефолте пустое

2024-12-15 19:31 UTC, maximyurchuk commented on ydb/tests/olap/lib/ydb_cluster.py
> +            cluster = YdbClusterInstance(cls.ydb_endpoint, cls.ydb_database)
Мне кажется, цель этой правки: сделать так чтобы эти тесты запускались локально и в рамках проверок на ПР 

Этот ПР позволяет это сделать 

В чем вэлью запуска какого-нибудь `ydb/tests/olap/scenario/test_scheme_load.py` против настоящего кластера, я если честно не понимаю. Если кто-нибудь знает было бы круто узнать. С моей точки зрения все тесты в `ydb/tests/olap/scenario` должны быть исключительно локальными

2024-12-16 09:53 UTC, iddqdex commented on ydb/tests/olap/lib/ydb_cluster.py
> +    def reset(cls, ydb_endpoint, ydb_database):
Еще mon_port надо выставлять.

2024-12-16 09:54 UTC, maximyurchuk submitted a review, later dismissed

2024-12-16 11:29 UTC, maximyurchuk approved these changes

2024-12-16 12:23 UTC, iddqdex approved these changes

2024-12-16 12:29 UTC, merged