Added column tables in suite tests
ydb-platform/ydb pull request #12524
Opened 2024-12-11 15:24 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-12 11:16 UTC, zverevgeny commented on ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
> +        if (AppData()->ColumnShardConfig.GetAllowNullableColumnsInPK() || !NArrow::HasNulls(incomingBatch->column(incomingIdx))) {
Сделай, плиз, эту правку отдельным PR с ut, демонстриующим проблему и фиксмом. Там обсудим

2024-12-12 11:22 UTC, zverevgeny requested changes

2024-12-12 11:22 UTC, zverevgeny commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
Нужно ли для колононых таблиц отдельный кластер поднимать или лучше в одном кластере запускать тесты над CS и DS?
@maximyurchuk

2024-12-12 11:27 UTC, aavdonkin commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
На одном кластере придется в разные таблицы писать, это добавит сложности

2024-12-13 09:34 UTC, maximyurchuk commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
Что-то я озадачился

https://ideone.com/k5HdsY -- я насколько понимаю наследники будут иметь разные инстансы, поэтому вроде нет описанной проблемы 

Поэтому предлагаю проверить что у наследников свой инстанс `cls.cluster`

Отдельное поле заводить не стоит

2024-12-13 09:35 UTC, maximyurchuk commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
В общем не надо все поля дублировать плз

2024-12-13 09:38 UTC, maximyurchuk commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
Кроме того, сейчас количество тестов не увеличилось (с точки зрения pytest), а хотелось бы чтобы были отдельные тесты на колоночные таблицы

2024-12-13 09:53 UTC, aavdonkin commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
Там же всего один экземпляр BaseSuiteRunner остается
Я прямо в нем проверяю те же запросы но на колоночные таблицы
Если делать в том же инстансе, то придется у колоночных таблиц менять имя таблицы

2024-12-13 09:55 UTC, aavdonkin commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
> Кроме того, сейчас количество тестов не увеличилось (с точки зрения pytest), а хотелось бы чтобы были отдельные тесты на колоночные таблицы

С Женей договаривались сделать так как здесь

2024-12-15 07:19 UTC, zverevgeny commented on ydb/tests/functional/suite_tests/test_base.py
> +        cls.column_cluster = KiKiMR(
> Кроме того, сейчас количество тестов не увеличилось (с точки зрения pytest), а хотелось бы чтобы были отдельные тесты на колоночные таблицы

В этих тестах не должно быть различия в поведении между строчными и колоночными таблицами. Поясни, пожалуйста, зачем нужны два отдельных набора тестов на одно и то же? 
И кол-во тестов (с точки зрения pytest) - это какая-то неправильная метрика. Данный PR запускает проверку всех ранее написанных в этом тесте запросов поверх колоночных таблиц. А ты говоришь, что это плохо, т.к. не увеличивает кол-во тестов.

2025-04-09 10:52 UTC, closed without merging