[NOT YET FOR MERGE] parse and pass streamlookup parameters, YDB part
ydb-platform/ydb pull request #12548
Opened 2024-12-12 09:52 UTC by yumkam

[includes yql part, but it will disappear from resulting patch once merged on arc side; NOT FOR MERGE before that]

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-13 10:48 UTC, uzhastik commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +    if (!validateIntParam(cnStreamLookup.MaxCachedRows()))
не забывай про скобки

2024-12-13 10:48 UTC, uzhastik commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +        if (!TryFromString<ui64>(value.StringValue())) {
положи stringValue в переменную, чтобы дважды строку не строить в случае ошибки

2024-12-13 10:48 UTC, uzhastik commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +                } else if (name == "RightAny"sv) {
else избыточен

2024-12-13 10:48 UTC, uzhastik commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +        TExprNode::TPtr ttl = nullptr;
присваивание = nullptr избыточно

2024-12-13 10:48 UTC, uzhastik commented on yql/essentials/core/yql_join.cpp
> +        for (decltype(size) i = 1; i < size; ++i) {
у тебя же не шаблонный код, не мудри с decltype

2024-12-13 10:48 UTC, uzhastik commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +                if (!EnsureTupleOfAtoms(option, ctx) || !EnsureTupleMinSize(option, 1, ctx))
скобки не забывай ставить

2024-12-16 10:11 UTC, yumkam commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +                } else if (name == "RightAny"sv) {
Да, но, кмк, в случае исключающих альтернатив, использовать всегда `if () {} else if () {}` лучше для консистентности. Меняем/переносим `continue`, и, внезапно, надо менять и следующую строчку (или, хуже, забываем поменять).

2024-12-16 10:16 UTC, yumkam commented on yql/essentials/core/yql_join.cpp
> +        for (decltype(size) i = 1; i < size; ++i) {
Зато не нужно помнить `size` -- это `int`, `unsigned`, `ui32`, `ui64`, `size_t`,...

2024-12-16 10:32 UTC, yumkam commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +        if (!TryFromString<ui64>(value.StringValue())) {
Пофиксил, но оптимизация (маловероятной) обработки маловероятной обработки ошибок скорее вредна

2024-12-16 10:46 UTC, yumkam commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +            } else {
Аналогично. И тут похожий код в обеих ветках, одинаковое выравнивание упрощает сравнение

2024-12-23 08:00 UTC, rvu1024 submitted a review, later dismissed

2024-12-23 16:05 UTC, dorooleg commented on yql/essentials/core/yql_join.cpp
> +        for (decltype(size) i = 1; i < size; ++i) {
А хорошо бы помнить, иначе же overflow всякие можешь ловить

2024-12-23 16:23 UTC, dorooleg requested changes

2024-12-23 16:23 UTC, dorooleg commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheLimit(FromString<ui64>(streamLookup.MaxCachedRows().StringValue()));
Не похоже что эти настройки относятся к `TDqInputTransformLookupSettings`. Трансформеты это общая штука. Хотя бы в `TDqStreamLookupSource` если бы сгрупировали уже лучше бы было

2024-12-23 16:23 UTC, dorooleg commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheTtlSeconds(FromString<ui64>(streamLookup.TTL().StringValue()));
А сюда всегда гарантировано правильная строка прилетает или нет? Может тут exception вылететь?

Давай тестов добавим на не валидные параметры

2024-12-23 16:23 UTC, dorooleg commented on ydb/tests/fq/generic/streaming/test_join.py
>                              e.Data as data, u.id as lookup
Не хватает тестов на сами параметры

2024-12-23 16:23 UTC, dorooleg commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +    auto validateIntParam = [&ctx=ctx](auto&& value) {
Давай в отдельную функцию вынесем эту логику.

2024-12-23 16:23 UTC, dorooleg commented on ydb/library/yql/dq/type_ann/dq_type_ann.cpp
> +        if (input->ChildrenSize() > TDqJoin::idx_Options) {
на 506 строчке уже есть эта проверка

2024-12-23 16:23 UTC, dorooleg commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +        bool leftAny = false;
Можем опции в отдельную функцию завернуть чтобы проще было читать эту часть?

2024-12-23 18:50 UTC, yumkam commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheTtlSeconds(FromString<ui64>(streamLookup.TTL().StringValue()));
Гарантированно. Аннотатор проверяет `TryFromString`.

2024-12-24 09:02 UTC, yumkam commented on ydb/tests/fq/generic/streaming/test_join.py
>                              e.Data as data, u.id as lookup
Будут в `yql/essentials/tests/sql/suites/stream_lookup_join*`

2024-12-24 11:10 UTC, yumkam commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +        bool leftAny = false;
Вынес в ValidateSteamLookupFlags, но не уверен, что это улучшит читабельность

2024-12-24 11:12 UTC, yumkam commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheLimit(FromString<ui64>(streamLookup.MaxCachedRows().StringValue()));
Нет, это именно настройки streamlookup. 
```
    void TDqsExecutionPlanner::ConfigureInputTransformStreamLookup(const NNodes::TDqCnStreamLookup& streamLookup, const NNodes::TDqPhyStage& stage, ui32 inputIndex) {                          
```

2024-12-24 12:36 UTC, yumkam commented on yql/essentials/core/yql_join.cpp
> +        for (decltype(size) i = 1; i < size; ++i) {
Так наоборот: `decltype` не даёт сделать несогласованные типы, с которыми может быть overflow. Вот `auto` (=`ui64`) + `ui32` -- можно и словить.

2024-12-24 14:06 UTC, yumkam commented on ydb/tests/fq/generic/streaming/test_join.py
>                              e.Data as data, u.id as lookup
... и добавил  в интеграционный тест

2024-12-24 15:58 UTC, dorooleg commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheLimit(FromString<ui64>(streamLookup.MaxCachedRows().StringValue()));
https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/dq/proto/dq_tasks.proto?rev=r15598787#L187-189
Эти настройки на уровне трансформера настройки, а не streamlookup

2024-12-24 16:03 UTC, yumkam commented on ydb/library/yql/providers/dq/planner/execution_planner.cpp
> +        settings.SetCacheLimit(FromString<ui64>(streamLookup.MaxCachedRows().StringValue()));
TDqInputTransform*Lookup*Settings

2024-12-24 16:06 UTC, dorooleg commented on yql/essentials/core/yql_join.cpp
> +        for (decltype(size) i = 1; i < size; ++i) {
Ну пожалуй действительно в этом случае выровнятся типы. Но все равно не понятно почему такое переусложнение появилось. Тип же ChilderSize определен, почему понадобилось так мучаться с decltype?

2024-12-25 12:24 UTC, dorooleg commented on ydb/library/yql/providers/dq/opt/physical_optimize.cpp
> +        TExprNode::TPtr ttl;
Я думал ты и эту часть тоже в функцию вынесешь. Оставляю на твое усморение)

2024-12-25 12:24 UTC, dorooleg approved these changes

2024-12-27 12:59 UTC, rvu1024 approved these changes

2024-12-27 13:47 UTC, merged