Set default compression via CSConfig
ydb-platform/ydb pull request #12542
Opened 2024-12-12 06:14 UTC by vlad-gogov

### Changelog category

* New feature

2024-12-20 07:35 UTC, Enjection requested changes

2024-12-20 07:35 UTC, Enjection commented on ydb/core/config/validation/column_shard_config_validator.cpp
> +    }
Double check?

2024-12-20 07:38 UTC, Enjection submitted a review, later dismissed

2025-01-05 05:59 UTC, zverevgeny commented on ydb/core/config/validation/column_shard_config_validator.cpp
> +                                                  << "` is not support compression level";
does not support

2025-01-05 05:59 UTC, zverevgeny commented on ydb/core/config/validation/column_shard_config_validator.cpp
> +                                 << "` is not support compression level = " << std::to_string(columnShardConfig.GetDefaultCompressionLevel());
does not

2025-01-05 06:00 UTC, zverevgeny commented on ydb/core/config/validation/column_shard_config_validator.cpp
> +    EValidationResult validatePasswordComplexityResult = ValidateDefaultCompression(columnShardConfig, msg);
почему validatePasswordComplexityResult?

2025-01-05 06:01 UTC, zverevgeny commented on ydb/core/config/validation/column_shard_config_validator_ut/ya.make
> +YQL_LAST_ABI_VERSION()
кажется, это лишнее

2025-01-05 06:03 UTC, zverevgeny commented on ydb/core/config/validation/validators.h
> +EValidationResult ValidateColumnShardConfig(const NKikimrConfig::TColumnShardConfig& columnShardConfig, std::vector<TString>& msg);
выбивается из стиля соседних объявлений

2025-01-14 13:52 UTC, swalrus1 requested changes

2025-01-15 04:34 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +            return NArrow::TStatusValidator::GetValid(arrow::util::Codec::Create(codec, 1));
Create(codec) по умолчанию создает ZSTD с compression level равным 8

2025-01-15 04:39 UTC, vlad-gogov commented on ydb/core/base/appdata_fwd.h
> -    Y_ABORT_UNLESS(actorSystem);
У меня получилась ситация, HasAppData возвращает true, но AppData в нем нет, поэтому я не мог обратиться к конфигурации CS, падало на https://github.com/ydb-platform/ydb/blob/de2a1e3e2f1638a777dc7240759477a8a93334b3/ydb/core/base/appdata_fwd.h#L308 (переменная x была пустая), поэтому я подумал, что проверка HasAppData должна проверять наличие AppData

2025-01-15 07:35 UTC, swalrus1 commented on ydb/core/formats/arrow/serializer/native.h
> +            return NArrow::TStatusValidator::GetValid(arrow::util::Codec::Create(codec, 1));
А как ты это понял? Просто в коде arrow значением по умолчанию для ZSTD стоит 1: https://github.com/ydb-platform/ydb/blob/main/contrib/libs/apache/arrow/cpp/src/arrow/util/compression_internal.h#L73

2025-01-15 12:15 UTC, swalrus1 submitted a review, later dismissed

2025-01-16 13:23 UTC, zverevgeny commented on ydb/core/formats/arrow/serializer/native.h
> +        if (!HasAppData() && !AppData()->ColumnShardConfig.HasDefaultCompression()) {
Когда такое может быть? Давай лучше впишем в протобуфе значение по умолчанию

2025-01-16 13:29 UTC, CyberROFL commented on ydb/core/kqp/ut/common/columnshard.h
> +        YDB_ACCESSOR_DEF(std::optional<NKikimrSchemeOp::EColumnCodec>, CompressionType);
https://github.com/ydb-platform/ydb/blob/b40833909a29351baa2cbd151a23ebb10f9a601f/ydb/library/accessor/accessor.h#L149-L153

2025-01-16 13:29 UTC, CyberROFL commented on ydb/core/formats/arrow/serializer/utils.h
> +}  // namespace NKikimr::NArrow
Какое отношение этот дифф имеет к остальным изменениям? Если хочешь починить стайлгайд, сделай это отдельным pr.

2025-01-16 13:29 UTC, CyberROFL commented on ydb/core/base/appdata_fwd.h
> +           NActors::TlsActivationContext->ExecutorThread.ActorSystem->AppData<TAppData>();
```suggestion
    return !!NActors::TlsActivationContext
        && NActors::TlsActivationContext->ExecutorThread.ActorSystem
        && NActors::TlsActivationContext->ExecutorThread.ActorSystem->AppData<TAppData>();
```

2025-01-17 04:22 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +        if (!HasAppData() && !AppData()->ColumnShardConfig.HasDefaultCompression()) {
Не стал вписывать значения по умолчанию, потому что это усложнит проверку, так как не совсем понятно, когда задано значение по умолчанию, а когда его изменили в конфигурации. Пример: в конфигурации выставили сжатие LZ4, тогда уровень сжатия может быть "1" по умолчанию или если его выставил пользователь, такая пара значений не должна проходить валидацию. В протобуфе нельзя проверить, лежит ли там значение по умолчанию или его выставили.

2025-01-17 07:47 UTC, zverevgeny commented on ydb/core/formats/arrow/serializer/native.h
> -        options.codec = *arrow::util::Codec::Create(arrow::Compression::LZ4_FRAME);
Кажется, это также повлияет на первичную запись (до компакшна). Нужно у Вани уточнить в понедельник

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/base/appdata_fwd.h
> -    Y_ABORT_UNLESS(actorSystem);
а зачем убирать отсюда проверку? чтобы SEGFAULT ловить, если HasAppData не вызовут?

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/base/appdata_fwd.h
> -    Y_ABORT_UNLESS(x && x->Magic == TAppData::MagicTag);
аналогично

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/base/appdata_fwd.h
> -    Y_ABORT_UNLESS(actorSystem);
в какой ситуации может быть AppData не заполнен при наличии TlsActivationContext?

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> +        return NArrow::TStatusValidator::GetValid(arrow::util::Codec::Create(arrow::Compression::type::ZSTD, 1));
ZSTD/1 это что?

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.cpp
> +    auto codecPtrStatus = BuildCodec(codec.value_or(GetDefaultCompressionType()), level);
какое-то рассогласование логики - мы парсили в контексте того, что если что-то не заполнено, то берем из того объекта, в который парсим. а сейчас данные этого объекта перестали использоваться.

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> -        options.codec = *arrow::util::Codec::Create(arrow::Compression::LZ4_FRAME);
не повлияет. там используются GetFast/GetUncompressed явные

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> +        options.codec = GetDefaultCodec();
кажется, что две функции выше нигде не должны использоваться кроме как тут.

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> +        arrow::ipc::IpcWriteOptions options = BuildDefaultOptions();
вроде, и понятно зачем - но, кажется, что сейчас именно, не нужно так делать

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/utils.cpp
> +bool SupportsCompressionLevel(const NKikimrSchemeOp::EColumnCodec compression, const i32 compressionLevel) {
а где используется?

2025-01-23 08:50 UTC, ivanmorozov333 commented on ydb/core/tx/schemeshard/olap/column_families/schema.cpp
> +            if (!family->GetSerializerContainerOptional()->IsEqualTo(serializer)) {
а это проверка на что?

2025-01-23 08:59 UTC, vlad-gogov commented on ydb/core/base/appdata_fwd.h
> -    Y_ABORT_UNLESS(actorSystem);
HasAppData вызывается выше

2025-01-23 09:00 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/utils.cpp
> +bool SupportsCompressionLevel(const NKikimrSchemeOp::EColumnCodec compression, const i32 compressionLevel) {
Удалил

2025-01-23 09:03 UTC, vlad-gogov commented on ydb/core/tx/schemeshard/olap/column_families/schema.cpp
> +            if (!family->GetSerializerContainerOptional()->IsEqualTo(serializer)) {
Проверка сжатия в схемах (кодек и его уровень)

2025-01-23 09:07 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +        arrow::ipc::IpcWriteOptions options = BuildDefaultOptions();
После изменения сжатия в конфигурации будет использоваться старый, вместо нового

2025-01-23 09:09 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +        return NArrow::TStatusValidator::GetValid(arrow::util::Codec::Create(arrow::Compression::type::ZSTD, 1));
Сжатие по умолчанию, если его не задали в конфигурации CS

2025-01-23 09:53 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.cpp
> +    auto codecPtrStatus = BuildCodec(codec.value_or(GetDefaultCompressionType()), level);
Исправил, вернул как было

2025-01-23 10:01 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +        options.codec = GetDefaultCodec();
Исправил, убрал функцию и подставил строчку

2025-01-23 10:14 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> +        arrow::ipc::IpcWriteOptions options = BuildDefaultOptions();
в какой конфигурации?

2025-01-23 10:14 UTC, ivanmorozov333 commented on ydb/core/tx/schemeshard/olap/column_families/schema.cpp
> +            if (!family->GetSerializerContainerOptional()->IsEqualTo(serializer)) {
то есть, мы не можем менять сжатие в family?

2025-01-23 10:14 UTC, ivanmorozov333 commented on ydb/core/formats/arrow/serializer/native.h
> +        if (!HasAppData() && !AppData()->ColumnShardConfig.HasDefaultCompression()) {
поправь условие.
LZ4 по умолчанию

2025-01-23 13:47 UTC, vlad-gogov commented on ydb/core/formats/arrow/serializer/native.h
> +        if (!HasAppData() && !AppData()->ColumnShardConfig.HasDefaultCompression()) {
Вернул LZ4 по умолчанию и поправил условию.

2025-01-24 06:15 UTC, ivanmorozov333 approved these changes

2025-01-24 07:31 UTC, merged