Added column tables support in workload tests
ydb-platform/ydb pull request #12586
Opened 2024-12-12 17:28 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-12 18:37 UTC, zverevgeny requested changes
Заполни, плиз, комментарий к pr. В данном случае можно оставить not for changelog

2024-12-13 03:37 UTC, zverevgeny commented on ydb/library/workload/kv/kv.cpp
> +        opts.AddLongOption("column-tables", "Use column tables")
ydb workload tpch init --help
...
--store VAL              Storage type. Options: row, column, external-s3
Нужно придерживаться одного именования параметров в разных ворклоадах

2024-12-13 07:38 UTC, iddqdex commented on ydb/library/workload/kv/kv.cpp
> +        opts.AddLongOption("column-tables", "Use column tables")
Я полностью поддерживаю. Предлагаю использовать [вот этот енум](https://github.com/ydb-platform/ydb/blob/7a1a6828a38dd99a65468306586199735632db3f/ydb/library/workload/benchmark_base/workload.h#L16) и код который с ним связан, перетащив его в базовый класс [TWorkloadParams](https://github.com/ydb-platform/ydb/blob/7a1a6828a38dd99a65468306586199735632db3f/ydb/library/workload/abstract/workload_query_generator.h#L162).

2024-12-13 13:05 UTC, maximyurchuk commented on ydb/tests/functional/kv_workload/test_kv_workload.py
> +        cls.column_cluster = KiKiMR(KikimrConfigGenerator(
Я не понимаю зачем здесь два кластера создается. Зачем?

2024-12-13 13:07 UTC, maximyurchuk commented on ydb/tests/functional/kv_workload/test_kv_workload.py
> +    def RunTest(self, useColumns):
В питоне функции и аргументы именуются в другом стиле, посмотри по сосдним строчкам-файлам

2024-12-13 13:13 UTC, maximyurchuk commented on ydb/tests/functional/kv_workload/test_kv_workload.py
> +        argsx = [
А какая семантика у названия `argsx` ? Как будто артефакт дебага

2025-04-16 10:55 UTC, closed without merging