Add docs for Way
ydb-platform/ydb pull request #12606
Opened 2024-12-13 11:01 UTC by avevad

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-12-23 16:35 UTC, anton-bobkov commented on ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
> +Returns active field (active index) of a variant over struct (over tuple)
```suggestion
Returns an active field (active index) of a variant over the tuple structure.
```

2024-12-23 16:35 UTC, anton-bobkov commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
> +Возвращает активное поле (активный индекс) варианта поверх структуры (кортежа)
```suggestion
Возвращает активное поле (активный индекс) варианта поверх структуры (кортежа).
```

2024-12-23 17:56 UTC, fomichev3000 approved these changes

2024-12-23 17:56 UTC, merged

2024-12-24 21:17 UTC, rvu1024 requested changes

2024-12-24 21:17 UTC, rvu1024 commented on ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
> +VariantItem(Variant<key1: K1, key2: K2, ...>{Flags:AutoMap})->Utf8
Имя в сигнатуре неправильное

2024-12-24 21:17 UTC, rvu1024 commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
> +VariantItem(Variant<key1: K1, key2: K2, ...>{Flags:AutoMap})->Utf8
Имя в сигнатуре неправильное