add leaky bucket to request reporting
ydb-platform/ydb pull request #12677
Opened 2024-12-17 11:58 UTC by VPolka

### Changelog entry 

...

### Changelog category 

* Improvement

### Additional information

...

2024-12-20 15:41 UTC, va-kuznecov approved these changes

2024-12-20 15:41 UTC, va-kuznecov commented on ydb/core/blobstorage/dsproxy/dsproxy_request_reporting.cpp
> +    std::atomic<ui64> Level;
```suggestion
    std::atomic<i64> Level;
```

2024-12-20 15:42 UTC, va-kuznecov requested changes

2024-12-20 15:42 UTC, va-kuznecov commented on ydb/core/blobstorage/dsproxy/dsproxy_request_reporting.cpp
> +    std::atomic<ui64> Level;
```suggestion
    std::atomic<i64> Level;
```

2024-12-28 14:14 UTC, va-kuznecov approved these changes

2024-12-28 15:01 UTC, alexvru approved these changes

2024-12-29 10:09 UTC, merged