Database node authorization docs
ydb-platform/ydb pull request #12710
Opened 2024-12-18 09:16 UTC by zinal

### Changelog entry 

Added the documentation on proper setup of database node authorization as a pre-requisite for dynamic configuration support.

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. В кластере должна быть включена [авторизация узлов баз данных](../../reference/configuration/node_authorization.md) при их регистрации.
```suggestion
1. Включите в кластере [авторизацию узлов баз данных](../../reference/configuration/node_authorization.md) при их регистрации.
```

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Если ранее в кластере использовалось [управление конфигурацией через CMS](cms.md), то необходимо выгрузить существующие настройки в формате YAML. Для этого необходимо выполнить следующую команду:
```suggestion
1. Если ранее в кластере использовалось [управление конфигурацией через CMS](cms.md), то выгрузите существующие настройки в формате YAML. Для этого выполните следующую команду:
```

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Необходимо сформировать первоначальный файл динамической конфигурации:
```suggestion
1. Сформируйте первоначальный файл динамической конфигурации:
```

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Сформированный файл динамической конфигурации необходимо применить на кластер:
```suggestion
1. Примените сформированный файл динамической конфигурации на кластер:
```

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/node_authorization.md
> +1. На корневом уровне конфигурации добавить блок `client_certificate_authorization`, в которой указать требования к заполнению поля "Subject" доверенных сертификатов подключаемых узлов, например:
```suggestion
1. На корневом уровне конфигурации добавьте блок `client_certificate_authorization`, в котором укажите требования к заполнению поля "Subject" доверенных сертификатов подключаемых узлов, например:
```

2024-12-19 11:42 UTC, anton-bobkov commented on ydb/docs/ru/core/reference/configuration/node_authorization.md
> +1. В блок `domains_config / security_config` добавить элемент `register_dynamic_node_allowed_sids`, в котором указать список субъектов доступа, для которых разрешена регистрация узлов баз данных. По
```suggestion
1. В блок `domains_config / security_config` добавьте элемент `register_dynamic_node_allowed_sids`, в котором укажите список субъектов доступа, для которых разрешена регистрация узлов баз данных. По техническим причинам в этом списке также должен присутствовать субъект доступа `root@builtin`. Пример:
```

2024-12-23 13:44 UTC, molotkov-and commented on ydb/docs/ru/core/reference/configuration/node_authorization.md
> +# Авторизация узлов при регистрации в кластере
I think we need add information that client certificates is provided over command line parameters of dynamic node
```
--grpc-ca=/path/to/ca.crt
--grpc-cert=/path/to/client.crt
--grpc-key=/path/to/client.key
```

2025-01-14 03:16 UTC, blinkov requested changes

2025-01-14 03:16 UTC, blinkov commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +1. Add the block `client_certificate_authorization` at the root level, and define the requirements for the "Subject" field of trusted node certificates, for example:
```suggestion
## Enabling database node authentication and authorization

To enable mandatory database node authorization, add the following configuration blocks to the [static cluster configuration](./index.md) file:

1. At the root level, add the `client_certificate_authorization` block to define the requirements for the "Subject" field of trusted node certificates. For example:
```

2025-01-14 03:16 UTC, blinkov commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +    ```
Some final steps and conclusions seem to be missing. Like, shouldn't a cluster be rolling restarted after changing this configuration or something? Also, some steps to check that it's actually working as intended would be great, maybe showing something relevant in embedded UI, trying to add a node with a wrong CA/Subject and seeing that it fails, etc.

2025-01-14 03:16 UTC, blinkov commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +## Enabling TLS for gRPC and preparing node certificates
Also, the TLS certificate generation section of the initial deployment guide could be updated to include a link to these prerequisites, stating that if you intend to enable this feature, you'd better ensure that your certificates satisfy them from the beginning.

Or maybe the prerequisites could be an `{% include %}` file used both here and during the initial deployment, so the initial deployment instructions enable all this by default as they are supposed to produce a production-ready cluster (and this separate article will be just for migrating older clusters). But that's probably too complicated to do in one PR.

2025-01-14 03:16 UTC, blinkov commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +1. Add the `register_dynamic_node_allowed_sids` element to `domains_config / security_config` block, and list the desired list of subjects which are enabled for database node registration. For intern
```suggestion
    If the certificate is successfully verified and the components of the "Subject" field comply with the requirements defined in the `subject_terms` sub-block, the connection will be assigned the access subjects listed in the `member_groups` parameter. To distinguish these subjects from other user groups and accounts, their names typically have the `@cert` suffix.

1. Add the `register_dynamic_node_allowed_sids` element to the `domains_config / security_config` block, and list the subjects permitted for database node registration. For internal technical reasons, the list must include the `root@builtin` element. Example:
```

2025-01-14 06:57 UTC, zinal commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +The command line parameters for [starting database nodes](../../devops/manual/initial-deployment.md#start-dynnode) must be extended to include the options that set the paths to the trusted CA certifi
> Is it really a "must"? As far as I understand, the node shouldn't care how these settings are specified. It could be like three tabs with examples for CLI args, static yaml config file, and dynamic yaml config file.

Нет, тут есть ограничение.
Если мы ходим использовать динамическую конфигурацию, нам нужна уже работающая авторизация узлов.
Для работающей авторизации узлов нужно передать имена файлов сертификатов именно как опции командной строки, передача их в файле статической конфигурации тоже не работает.

2025-01-14 06:59 UTC, zinal commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +    --node-broker grpcs://<ydb3>:2135
> Meanwhile, they shouldn't be required if they were specified in `config.yaml` instead.

Может и не должны, но требуются.

2025-01-27 04:16 UTC, blinkov reviewed
@zinal do you intend to finish this?

2025-01-27 04:16 UTC, blinkov commented on ydb/docs/en/core/maintenance/manual/dynamic-config.md
> +Below is a more comprehensive example of a dynamic configuration that defines typical global parameters, as well as parameters specific to a particular database:
```suggestion
By default, the cluster configuration is assigned version 1. When applying a new configuration, the system compares the uploaded configuration's version with the value specified in the YAML file. If the versions match, the current version number is automatically incremented by one.

Below is a more comprehensive example of a dynamic configuration that defines typical global parameters as well as parameters specific to a particular database:
```

2025-01-29 04:26 UTC, zinal commented on ydb/docs/en/core/reference/configuration/node_authorization.md
> +    ```
Добавил

2025-01-31 10:19 UTC, blinkov submitted a review, later dismissed

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +    Пример команды для запуска узла базы данных, дополненной опциями с указанием путей к ключам и сертификатам TLS для протокола gRPC:
```suggestion
    | **Опция командной строки** | **Описание** |
    |----------------------------|--------------|
    | `--grpc-ca`                | Путь к файлу сертификатов доверенных центров сертификации `ca.crt`. |
    | `--grpc-cert`              | Путь к файлу сертификата узла `node.crt`. |
    | `--grpc-key`               | Путь к файлу секретного ключа узла `node.key`. |

    Пример команды для запуска узла базы данных с опциями, указывающими пути к ключам и сертификатам TLS для протокола gRPC:
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +1. В блок настроек аутентификации кластера `security_config` добавьте элемент `register_dynamic_node_allowed_sids`, в котором укажите список субъектов доступа, для которых разрешена регистрация узлов
```suggestion
    При необходимости добавьте другие проверки сертификатов [в соответствии с документацией](../../reference/configuration/node-authentication.md).

    В случае успешной проверки сертификата и соответствия компонентов поля "Subject" сертификата требованиям, установленным в блоке `subject_terms`, подключению будут присвоены субъекты доступа, перечисленные в параметре `member_groups`. Чтобы отделить такие субъекты доступа от других групп и учётных записей, к их наименованию добавляется суффикс `@cert`.

1. В блок настроек аутентификации кластера `security_config` добавьте элемент `register_dynamic_node_allowed_sids`, указав список субъектов доступа, которым разрешена регистрация узлов баз данных. По техническим причинам в этом списке также должен присутствовать субъект доступа `root@builtin`. Пример:
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +1. Выполните поэтапный перезапуск узлов баз данных кластера с помощью ydbops либо с использованием плейбука Ansible.
```suggestion
    Более подробная информация по настройке параметров аутентификации кластера приведена в [соответствующем разделе документации](../../reference/configuration/index.md#security-access-levels).

1. Обновите файлы статической конфигурации на всех узлах кластера вручную либо с помощью [плейбука Ansible](../ansible/update-config.md).

1. Выполните поэтапный перезапуск узлов хранения кластера [с помощью ydbops](../../reference/ydbops/rolling-restart-scenario.md) либо с использованием [плейбука Ansible](../ansible/restart.md).

1. Выполните поэтапный перезапуск узлов баз данных кластера с помощью ydbops либо с использованием плейбука Ansible.
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Если ранее в кластере использовалось [управление конфигурацией через CMS](cms.md), то выгрузите существующие настройки в формате YAML. Для этого выполните следующую команду:
```suggestion
## Подготовка к использованию динамической конфигурации {#preparation}

Перед началом использования динамической конфигурации в кластере необходимо провести подготовительные работы:

1. Включите в кластере [аутентификацию и авторизацию узлов баз данных](../../devops/manual/node-authorization.md).

1. Если ранее в кластере использовалось [управление конфигурацией через CMS](cms.md), выгрузите существующие настройки в формате YAML. Для этого выполните следующую команду:
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Примените сформированный файл динамической конфигурации на кластер:
```suggestion
    Предварительно необходимо получить токен аутентификации с помощью команды `ydb auth get-token`, аналогично [процедуре инициализации кластера](../../devops/manual/initial-deployment.md#initialize-cluster).

1. Сформируйте первоначальный файл динамической конфигурации:

   * Если ранее в CMS выполнялись настройки (экспортированные на предыдущем шаге), используйте полученный файл в качестве основы и:
      * добавьте секцию `metadata` по образцу из [примера конфигурации](#example);
      * в секцию `config` добавьте параметр `yaml_config_enabled: true`.
   * Если ранее настройки через CMS не выполнялись, используйте [минимальное наполнение](#example) файла динамической конфигурации.
   * Если в кластере используется шифрование [интерконнекта акторной системы](../../concepts/glossary.md#actor-system-interconnect), добавьте в секцию `config` соответствующие [настройки TLS для интерконнекта](../../reference/configuration/tls.md#interconnect).

1. Примените сформированный файл динамической конфигурации на кластер:
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +После включения поддержки динамической конфигурации в кластере {{ ydb-short-name }} устаревшая функция управления конфигурацией через CMS будет недоступна.
```suggestion
После включения поддержки динамической конфигурации в кластере {{ ydb-short-name }} устаревшая функция управления конфигурацией через CMS станет недоступной.
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +1. Если ранее в кластере использовалось [управление конфигурацией через CMS](cms.md), то выгрузите существующие настройки в формате YAML. Для этого выполните следующую команду:
там в соседнем PR появляется раздел по миграции с устаревших способов конфигурации — выглядит как-будто это скорее туда

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/maintenance/manual/dynamic-config.md
> +    # HYBRID || COMPUTE || STORAGE — тип ноды, для узлов БД всегда COMPUTE
```suggestion
    # HYBRID || COMPUTE || STORAGE — тип ноды, для узлов баз данных всегда COMPUTE
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/node-authentication.md
> +### Синтаксис
```suggestion
# Аутентификация узлов баз данных

Аутентификация узлов баз данных в кластере {{ ydb-short-name }} обеспечивает присвоение служебным подключениям между узлами кластера корректных идентификаторов защиты, или [SID](../../concepts/glossary.md#access-sid). Процесс аутентификации узлов баз данных относится к подключениям, использующим протокол gRPC и обеспечивающим выполнение функций регистрации узлов в кластере, а также доступа к конфигурационной информации. Присвоенные подключениям SID учитываются при проверке правил авторизации, действующих в отношении служебных gRPC-вызовов.

Настройки аутентификации узлов баз данных указываются в составе [статической конфигурации](./index.md) кластера.

## client_certificate_authorization — настройки аутентификации узлов

Этот раздел конфигурации управляет режимом аутентификации при подключении узлов баз данных и определяет требования к заполнению полей "Subject" и "Subject Alternative Name" сертификатов узлов, а также список присваиваемых идентификаторов защиты [SID](../../concepts/glossary.md#access-sid).

Поле "Subject" сертификата узла состоит из нескольких компонентов (например, `O` — организация, `OU` — подразделение в составе организации, `C` — страна, `CN` — имя собственное субъекта). Проверки могут быть настроены на соответствие одного или нескольких компонентов поля ожидаемым значениям.

Поле "Subject Alternative Name" сертификата узла представляет собой список сетевых имён или IP-адресов узлов. Проверка может быть настроена на соответствие сетевых имён в сертификате ожидаемым значениям.

### Синтаксис
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/node-authentication.md
> +Следующий фрагмент конфигурации включает аутентификацию узлов, и требует в поле "Subject" наличия компонента `O=YDB`. При успешной аутентификации подключению будет присвоен субъект доступа `registerN
```suggestion
Ключ | Описание
---- | ---
`request_client_certificate` | Требовать корректный клиентский сертификат для подключения узлов.<br/>Допустимые значения:<br/><ul><li>`false` — сертификат не требуется (применяется по умолчанию, если параметр не задан);</li><li>`true` — для подключения узлов требуется доверенный клиентский сертификат.</li></ul>
`default_group` | SID, присваиваемый всем подключениям с доверенным клиентским сертификатом, если нет явно заданных настроек в секции `client_certificate_definitions`.
`client_certificate_definitions` | Блок настроек требований к сертификатам узлов баз данных.
`member_groups` | Массив SID, присваиваемых подключениям, сертификаты которых соответствуют требованиям этого блока.
`require_same_issuer` | Требовать совпадение поля "Issuer" (наименование центра регистрации) для клиентского (узел базы данных) и серверного (узел хранения) сертификатов.<br/>Допустимые значения:<br/><ul><li>`true` — совпадение требуется (применяется по умолчанию, если параметр не задан);</li><li>`false` — совпадение не требуется (клиентский и серверный сертификаты могут быть выпущены разными центрами регистрации).</li></ul>
`subject_dns` | Допустимые значения поля "Subject Alternative Name" в виде массива полных значений (ключ `values`) или массива суффиксов значений (ключ `suffixes`). Проверка считается успешной при совпадении одного из значений поля с любым полным именем либо при соответствии любому указанному суффиксу.
`subject_terms` | Требования к заполнению компонентов поля "Subject". Указывается имя компонента (ключ `short_name`), а также набор полных значений (ключ `values`) или набор суффиксов значений (ключ `suffixes`). Проверка считается успешной, если для каждого проверяемого компонента поля "Subject" его значение соответствует одному из разрешённых полных значений либо одному из разрешённых суффиксов.

### Примеры

Следующий фрагмент конфигурации включает аутентификацию узлов и требует наличия в поле "Subject" компонента `O=YDB`. При успешной аутентификации подключению будет присвоен субъект доступа `registerNode@cert`.
```

2025-01-31 10:19 UTC, blinkov commented on ydb/docs/ru/core/reference/configuration/node-authentication.md
> +Следующий фрагмент конфигурации включает аутентификацию узлов, и требует в поле "Subject" наличия компонентов `OU=cluster1` и `O=YDB`. Дополнительно проверяется, что поле "Subject Alternative Name" с
```suggestion
Следующий фрагмент конфигурации включает аутентификацию узлов и требует наличия в поле "Subject" компонентов `OU=cluster1` и `O=YDB`. Дополнительно проверяется, что поле "Subject Alternative Name" содержит имя хоста, заканчивающееся на суффикс `.cluster1.ydb.company.net`. При успешной аутентификации подключению будет присвоен субъект доступа `registerNode@cert`.
```

2025-02-02 16:03 UTC, fomichev3000 requested changes

2025-02-02 16:03 UTC, fomichev3000 commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +3. Узел хранения проверяет заполнение поля "Subject" сертификата на соответствие  требованиям, устанавливаемым в статической конфигурации.
Нужна ссылка на требования

2025-02-02 16:03 UTC, fomichev3000 commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +4. При успешном прохождении перечисленных выше проверок подключение со стороны узла базы данных считается аутентифицированным, и ему присваивается специальный [SID](../../concepts/glossary.md#access-
уф, не очень понятно, что такое "специальный SID"

2025-02-02 16:03 UTC, fomichev3000 commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +5. Узел базы данных использует установленное gRPC-подключение для регистрации в составе кластера, а также для получения динамической конфигурации с использованием соответствующих служебных вызовов.
Кажется, важнее, что он получает nodeId с которым он дальше входит в кластер. Хотя вот эту фразу написал, и понял, что она неправильная... Но в целом все равно странно -- ценности в дин конфигурации для злоумышленника нет. Наоборот нужен акцент на том, почему безопасно далее получается войти в кластер

2025-02-03 16:37 UTC, zinal commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +3. Узел хранения проверяет заполнение поля "Subject" сертификата на соответствие  требованиям, устанавливаемым в статической конфигурации.
Добавил

2025-02-03 16:38 UTC, zinal commented on ydb/docs/ru/core/devops/manual/node-authorization.md
> +4. При успешном прохождении перечисленных выше проверок подключение со стороны узла базы данных считается аутентифицированным, и ему присваивается специальный [SID](../../concepts/glossary.md#access-
Дополнил формулировки - надеюсь, стало лучше

2025-02-28 09:39 UTC, fomichev3000 approved these changes

2025-02-28 09:40 UTC, merged