Release notes YDB Server 24.2.7
ydb-platform/ydb pull request #12729
Opened 2024-12-18 13:24 UTC by galnat

### Changelog entry 

Publish release notes for YDB Server 24.2.7

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

2024-12-18 15:22 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлено получение вложенных групп от LDAP-сервера, в LDAP-конфигурации улучшен парсинг хостов и добавлена настройка для отключения встроенной аутентификацию по логину и паролю.
Давайте добавим ссылку на доку про лдап?
https://ydb-platform--ydb.viewer.diplodoc.com/ru/concepts/auth#ldap-auth-provider

2024-12-18 15:22 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлена возможность аутентификации [динамических нод](./concepts/glossary#dynamic) по SSL-сертификату.
Ссылка на раздел "динамические узлы", а тут пишем "ноды". Предлагается использовать единые термины

2024-12-18 15:22 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* [Добавлено](https://github.com/ydb-platform/ydb-embedded-ui/pull/889) отображение текущей версии YDB UI.
я проверил 24-2, тут нет этой возможности(

2024-12-18 15:22 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* [Добавлена](https://github.com/ydb-platform/ydb-embedded-ui/issues/944) возможность сохранения запроса из редактора горячими клавишами.
я проверил 24-2, тут нет этой возможности(

2024-12-18 15:22 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* [Добавлена](https://github.com/ydb-platform/ydb-embedded-ui/pull/834) поддержка view.
она добавлена в UI, но на сервере выключена
>Views are disabled. Please contact your system administrator to enable the feature

я бы оставил этот пункт, ведь вью всё же можно включитьфиче флагом

2024-12-18 15:31 UTC, antonkovalenko requested changes

2024-12-18 15:31 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена [ошибка](https://github.com/ydb-platform/ydb/issues/6677), которая приводила к неработоспособности схемных операции при выполнении экспорта/бекапа больших баз, добавлением проверки на ра
Очень сложная фраза, я бы упросил

Добавлена проверка - начал бы так

2024-12-18 15:31 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлены](https://github.com/ydb-platform/ydb/pull/6461) [ошибки](https://github.com/ydb-platform/ydb/issues/6220), возникающие при изменении состояния [координатора](./concepts/glossary#tablet-
А вот есть ссылка прямо на координатор

https://ydb-platform--ydb.viewer.diplodoc.com/ru/concepts/glossary#coordinator

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/pull/6008) a bug where soft tablet transfer (drain) from a node could hang.
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/pull/6008) an issue that might cause soft tablet transfers (drain) from a node to hang.
```

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Resolved](https://github.com/ydb-platform/ydb/pull/6445) a problem where the interconnect proxy on a node without restarts would stop when adding another node to the cluster.
```suggestion
* [Resolved](https://github.com/ydb-platform/ydb/pull/6445) an issue with the interconnect proxy stopping on a node that is running without restarts. The issue occurred when adding another node to the cluster.
```

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/pull/6695) free memory accounting in the [interconnect](./concepts/glossary#actor-system-interconnect).
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/pull/6695) an issue with managing free memory in the [interconnect](./concepts/glossary#actor-system-interconnect).
```

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/issues/6398) handling of empty garbage collection requests on VDisk.
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/issues/6398) an issue with handling empty garbage collection requests on VDisk.
```

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/pull/5883) a bug where data created by newer versions of VDisk failed to load.
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/pull/5883) an issue with failing to load the data created by newer versions of VDisk.
```

2024-12-19 09:15 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/pull/5862) execution of `REPLACE INTO` queries with default values.
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/pull/5862) an issue with executing the `REPLACE INTO` queries with default values.
```

2024-12-20 07:15 UTC, fomichev3000 approved these changes

2024-12-20 09:43 UTC, anton-bobkov approved these changes

2024-12-20 09:48 UTC, galnat reviewed
Все поправила

2024-12-20 11:32 UTC, antonkovalenko approved these changes

2024-12-20 12:06 UTC, merged