Add ok and error request metrics
ydb-platform/ydb pull request #12738
Opened 2024-12-18 14:49 UTC by VPolka

### Changelog entry 

...

### Changelog category 

* Improvement

### Additional information

...

2025-02-14 14:03 UTC, alexvru requested changes

2025-02-14 14:03 UTC, alexvru commented on ydb/core/blobstorage/vdisk/common/vdisk_response.h
> +            TCommonHandleClass(ev.Record.GetHandleClass());
this does exactly nothing, as I suppose

2025-02-14 14:03 UTC, alexvru commented on ydb/core/blobstorage/vdisk/common/vdisk_response.h
> +    std::optional<NKikimrBlobStorage::EPutHandleClass> PutHandleClass;
std::variant<std::monostate, ...> ?

2025-02-14 14:03 UTC, alexvru commented on ydb/core/blobstorage/vdisk/common/vdisk_response.h
> +    template <>
why template<> ?

2025-02-14 14:07 UTC, alexvru requested changes

2025-02-14 14:07 UTC, alexvru commented on ydb/core/blobstorage/vdisk/common/vdisk_response.cpp
> +    using EnableFor = std::tuple<
not sure if it is a good idea to use tuple to describe a set of types

2025-02-14 14:07 UTC, alexvru commented on ydb/core/blobstorage/vdisk/common/vdisk_response.cpp
> +    for (const auto& item : record.GetItems()) {
spacing

2025-02-20 12:31 UTC, VPolka commented on ydb/core/blobstorage/vdisk/common/vdisk_response.cpp
> +    using EnableFor = std::tuple<
I made special template type for this

2025-02-20 12:34 UTC, VPolka commented on ydb/core/blobstorage/vdisk/common/vdisk_response.h
> +            TCommonHandleClass(ev.Record.GetHandleClass());
Can you provide more details on this issue please?
I did this because in some events HandleClass is in Record field, while in others it is not

2025-02-26 12:58 UTC, alexvru approved these changes

2025-02-26 16:31 UTC, merged