[RFC] [WIP] Fix FreeSpace accounting for DqAsyncInputBuffer
ydb-platform/ydb pull request #12744
Opened 2024-12-18 17:32 UTC by yumkam

It contains rows, not bytes, use them for GetFreeSpace accounting.

### Changelog entry 

...

### Changelog category 

* Bugfix 
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-23 17:07 UTC, dorooleg requested changes

2024-12-23 17:07 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
Я не понимаю зачем в случае batch.empty возвращать что-то отличное от 0. В этом случае обновиться статистика, но при этом на backpressure это никак не повлияет. Тут не правильная логика. GetAsyncInputData должен возвращает размер батча, а не то что в нутри transform накопилось или ожидает. Еще estimated row size не нужно их оценивать. Нужно их сразу посчитать на основе строчек

2024-12-23 17:08 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
Фактически до этого фикса backpressure совсем здесь не работало, теперь конечно лучше, но тоже не достаточно

2024-12-23 18:05 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
`usedSpace != 0 && batch.empty()` только сигнализирует, что "внутри transform что-то есть, но вернуть ещё не можем", и выставляет флаг Pending. На статистику это как раз не влияет (storedRows/Bytes обновляется только при `!batch.empty()`)

2024-12-23 18:18 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
Тут предполагается размер в байта. Но мы не знаем размер данных в байтах, всё что у нас есть -- число строчек и число колонок. Из этого мы получаем минимальную оценку. К этому мы добавляем ещё размер строчек слева.
А почему не строчек справа (из лукапа)? Строчки из лукапа могут быть пошаренные (и они к тому же гарантированно пошаренные с lru), так что мы их разумным образом учитывать не можем, и в расчёты не включаем.
Ещё мы не можем разумным (и дешёвым) способом оценить размер сложных типов, так что их тоже не учитываем

2024-12-23 18:47 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
Впрочем, better safe than sorry. Добавлю учёт строчек справа.

2024-12-25 12:26 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
> `usedSpace != 0 && batch.empty()` только сигнализирует, что "внутри transform что-то есть, но вернуть ещё не можем", и выставляет флаг Pending. На статистику это как раз не влияет (storedRows/Bytes обновляется только при `!batch.empty()`)

Ну тогда еще хуже на backpressure и статистику не влияет, тогда вообще смысла в этом нету

2024-12-25 12:30 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        return batch.empty() ? AwaitingQueue.size() : batch.RowCount() * EstimatedRowSize + extraSize;
Еще тут ошибка о возвращаемом значении из GetAsyncInputData. Он не должен оценивать то что находится внутри SLJ. Он должен вернуть размер именно batch. Это нужно для оценки данных которые внутри канала. Сами таски/sink/source внутри себя могут гигабайты еще держать это не проблема

2024-12-25 12:32 UTC, dorooleg requested changes

2024-12-25 12:32 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Тут нужно именно 0 вернуть. Это значение никуда не уйдет

2024-12-25 12:32 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
PayloadExtraSize считается по всему что внутри slj, а должен считаться только на batch.

2024-12-25 14:53 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Уйдёт: выставит флаг Pending, чекпоинтинг не начнётся. Иначе начнётся (и прошляпит данные внутри slj)

2024-12-25 14:58 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
данные в `batch` попадают из `ReadyQueue`, когда мы пополняем `ReadyQueue` мы добавляем `PayloadExtraSize`. На момент возвращения `batch` `ReadyQueue` пустая и мы обнулили `PayloadExtraSize`

2024-12-25 14:59 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
`AwaitingQueue` -- данные, которые в полёте -- не пополняют `PayloadExtraSize` и `ReadyQueue`

2024-12-25 15:49 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Можешь показать где на это логика завязана? Выглядит не правильным местом

2024-12-25 15:51 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
AwaitingQueue никак не должны фигурировать в ответе. GetAsyncInputData возвращает размемер batch. AwaitingQueue никак не связан с выходным размером батча

2024-12-25 16:32 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Проверка `IsPending`:
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/dq/actors/task_runner/task_runner_actor_local.cpp#L154
Выставление `IsPending`:
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/dq/runtime/dq_async_input.cpp#L36

Неочевидный момент (который пришлось повспоминать): почему IsPending eventually сотрётся: если он был выставлен, transform когда-то вернёт батч. После возвращения батча, transform опросят ещё раз, и тогда уже в нём точно будет пусто (ни данных, ни AwaitingQueue)

2024-12-25 18:15 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Там хитрость в том, что в `TaskRunner` есть ссылка на какую-то производную `TDqAsyncInputBuffer`. И в `TDqAsyncInputBuffer` не хранится ссылка на Transform, и для того, чтобы передать информацию о состоянии Transform приходится использовать такой непрямой путь: когда Transform опрашивается, то он возвращает специальное значение, Buffer получив результаты опроса со специальным значением взводит флажок, и TaskRunner может получить его значение.

2024-12-27 07:31 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
Финальная попытка решить задачу малой кровью.
Альтернатива -- поменять интерфейс `GetAsyncInputData`, чтобы он возвращал флаг Pending в явном виде (либо `std::variant<>`, либо `std::pair<size_t,bool>`). Потребует изменения всех провайдеров,  зато менее confusing.

2024-12-28 07:39 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
Проблема понятна, но тут много переписывать. Давай пока оставим как есть. Допиши в комментарий пожалуйста что в случае empty.batch можно любое число на самом деле отправить.

Я тут подумал что на самом деле оценку размера можно делать прямо из ydb. Там же protobuf прилетает, что если прямо размер протобафа прислать еще. Это уже будет хорошая оценка и для сложных типов. Фактически в pq_read_actor так оценка например и делается https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp?rev=r15624275#L309 И тогда вообще красота будет

Еще freeSpace тоже нужно будет учитывать. Пример https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp?rev=15624275#L302

2024-12-28 07:40 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            return AwaitingQueue.size();
Да, действительно хитрость в этом месте используется. Понятно, спасибо

2025-01-09 09:59 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
В последней итерации есть комментарий;
Проблема slj что 1) размер левой стороны сложно достать (он вычитывает UV из flow, там размер в протобуфах уже потерян); 2) размер вычитываемой правой стороны можно узнать из generic lookup, 3) ... но с правой стороны ещё есть кэш, и там взять размер вообще неоткуда

2025-01-17 14:17 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
В кеше можно размер рядом хранить. Для оценки размера данных

2025-01-17 14:17 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
С левой часть понятно, но хотя бы правую оценивать. ее вполне реально оценить

2025-01-22 12:07 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
Для правой части: во-первых, часть отдаётся из lru (размер неизвестен); во-вторых, то, что обновляется из базы -- получается батчём, и размер каждого индивидуального ключа не известен (так что мы не можем просто положить в lru рядышком размер)

2025-01-23 23:34 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
Код же не прибит. Ну пришел батч, из него можно достать размеры строчек и положить в lru https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto?rev=r15744952#L264 Вот тут все есть.

2025-01-23 23:43 UTC, dorooleg commented
Как первая оценка пойдет, нужно отдельный тикет в беклог создать чтобы оценивать лучше левую и правую часть

2025-01-23 23:43 UTC, dorooleg approved these changes

2025-01-27 11:14 UTC, yumkam commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
Там батч в arrow: https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto?rev=r15744952#L278

2025-01-27 11:16 UTC, dorooleg commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +            auto usedSpace = batch.RowCount() * MinimumRowSize + PayloadExtraSize;
> Там батч в arrow: https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto?rev=r15744952#L278

Нету разницы, он распаковывается потом в строчки. Можно по arrow оценить

2025-01-27 11:32 UTC, rvu1024 approved these changes

2025-01-27 12:55 UTC, merged