Translated the Troubleshooting section into Russian
ydb-platform/ydb pull request #12759
Opened 2024-12-19 08:12 UTC by anton-bobkov

### Changelog category

* Documentation

### Additional information

Added the Russian translation of the Troubleshooting section

2025-01-28 06:25 UTC, blinkov requested changes, later dismissed

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/system/system-clock-drift.md
> +
```suggestion
## Диагностика

Чтобы диагностировать расхождение в системном времени серверов {{ ydb-short-name }}, используйте следующие методы:

1. Используйте **Healthcheck** во [Встроенном UI](../../../../reference/embedded-ui/index.md):

    1. Во [Встроенном UI](../../../../reference/embedded-ui/index.md) перейдите на вкладку **Databases** и нажмите на наименование базы данных.

    1. На вкладке **Navigation** убедитесь, что требуемая база данных выбрана.

    1. Откройте вкладку **Diagnostics**.

    1. На вкладке **Info** нажмите на кнопку **Healthcheck**.

        Если кнопка **Healthcheck** отображает статус `MAINTENANCE REQUIRED`, возможно, в кластере {{ ydb-short-name }} возникли проблемы, например, расхождение системных часов. Все выявленные неполадки будут перечислены в разделе **DATABASE** под кнопкой **Healthcheck**.

    1. Чтобы увидеть диагностированные неполадки, раскройте раздел **DATABASE**.

        ![](_assets/healthcheck-clock-drift.png)

        Проблемы с расхождением системного времени отображаются в разделе `NODES_TIME_DIFFERENCE`.

    {% note info %}

    Для получения дополнительной информации см. [{#T}](../../../../reference/ydb-sdk/health-check-api.md)

    {% endnote %}
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/system/system-clock-drift.md
> +2. Убедитесь, что системные часы на всех серверах {{ ydb-short-name }} регулярно синхронизируются с помощью `timesyncd`, `ntpd`, `chrony` или аналогичного инструмента. Рекомендуется использовать один
```suggestion
1. Откройте страницу [Interconnect overview](../../../../reference/embedded-ui/interconnect-overview.md) во [Встроенном UI](../../../../reference/embedded-ui/index.md).

1. Используйте такие инструменты, как `pssh` или `ansible`, чтобы выполнить команду (например, `date +%s%N`) на всех узлах {{ ydb-short-name }} и отобразить значение системных часов.

    {% note warning %}

    На результаты будут влиять сетевые задержки между хостом, на котором запущены `pssh` или `ansible`, и хостами {{ ydb-short-name }}.

    {% endnote %}

    Если вы используете утилиты синхронизации времени, вы также можете запросить их статус вместо запроса текущих временных меток. Например, `timedatectl show-timesync --all`.

## Рекомендации

1. Вручную синхронизируйте системные часы серверов, на которых работают узлы {{ ydb-short-name }}. Например, используйте `pssh` или `ansible`, чтобы выполнить команду синхронизации часов на всех узлах.

2. Убедитесь, что системные часы на всех серверах {{ ydb-short-name }} регулярно синхронизируются с помощью `timesyncd`, `ntpd`, `chrony` или аналогичного инструмента. Рекомендуется использовать один и тот же источник времени для всех серверов в кластере {{ ydb-short-name }}.
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/system/toc_p.yaml
> +    - name: Расхождение значений системного времени
```suggestion
    - name: Расхождение системного времени
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/_includes/tablets-moved.md
> +        Откроется окно **Balancer**, в котором список недавно перемещённых таблеток отображается в секции **Latest tablet moves**.
```suggestion
1. Посмотрите, отображаются ли всплески на графике **Tablets moved by Hive** на панели мониторинга Grafana **[DB status](../../../../../reference/observability/metrics/grafana-dashboards.md#dbstatus)**.

    ![](../_assets/tablets-moved.png)

    На этой диаграмме отображаются данные о количестве таблеток, перемещаемых между узлами {{ ydb-short-name }} в секунду.

1. Проанализируйте статистику балансировщика Hive.

    1. Откройте [Встроенный UI](../../../../../reference/embedded-ui/index.md).

    1. Нажмите на ссылку **Developer UI** в правом верхнем углу Встроенного UI.

    1. В **Developer UI** перейдите на страницу **Tablets > Hive > App**.

        Проанализируйте статистику балансировщика в правом верхнем углу.

        ![cpu balancer](../_assets/cpu-balancer.jpg)

    1. Кроме того, чтобы просмотреть недавно перемещённые таблетки, нажмите на кнопку **Balancer**.

        Откроется окно **Balancer**, в котором список недавно перемещённых таблеток отображается в секции **Latest tablet moves**.
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/tablets-moved.md
> +    Для таблеток, которые используют ресурс **[count](*count)**, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы), с помощью метрики ObjectImbalance, аналогич
```suggestion
# Частые переезды таблеток между узлами

{{ ydb-short-name }} автоматически распределяет нагрузку, перемещая таблетки с перегруженных узлов на другие узлы. Этот процесс управляется компонентом [Hive](../../../../concepts/glossary.md#hive). Когда Hive перемещает таблетки, запросы, затрагивающие эти таблетки, могут выполняться дольше из-за ожидания инициализации таблетки на новом узле.

Для балансировки нагрузки между узлами {{ ydb-short-name }} учитывает использование следующих аппаратных ресурсов:

- процессор;
- оперативная память;
- сетевой трафик;
- [count](*count).

Балансировка выполняется автоматически в следующих случаях:

- **Дисбаланс потребления аппаратных ресурсов**

    Для оценки сбалансированности потребления аппаратных ресурсов {{ ydb-short-name }} использует метрику **scatter**, вычисляемую отдельно для каждого ресурса по формуле

    $Scatter = \frac {MaxUsage - MinUsage} {MaxUsage},$

    где:

    - $MaxUsage$ — максимум по потреблению данного ресурса среди всех узлов;
    - $MinUsage$ — минимум по потреблению данного ресурса среди всех узлов.

    Для нормирования потребления на каждом узле используется объём доступных ресурсов на узле, который может различаться между узлами. При низких нагрузках эта величина может сильно колебаться. Чтобы этого избежать, при вычислении **scatter** считается, что потребление ресурса не может быть ниже 30%. Если **scatter** превышает порог, запускается балансировка.

- **Перегруженность узла (по использованию процессора и памяти)**

    Hive запускает балансировку, если самый загруженный узел имеет загрузку больше 90%, а наименее загруженный — меньше 70%.

- **Неравномерное распределение конкретного объекта**

    Для таблеток, которые используют ресурс **[count](*count)**, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы), с помощью метрики ObjectImbalance, аналогичной описанной выше **scatter**. При рестартах узлов равномерность может нарушаться, и тогда запускается балансировка.
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/tablets-moved.md
> +[*count]: Count — фиктивный ресурс, используемый для равномерного распределения таблеток одного типа между узлами.
```suggestion
## Рекомендации

Измените настройки балансировщика Hive:

1. Откройте [Встроенный UI](../../../../reference/embedded-ui/index.md).

1. Нажмите на ссылку **Developer UI** в правом верхнем углу Встроенного UI.

1. В **Developer UI** перейдите на страницу **Tablets > Hive > App**.

    ![](_assets/hive-app.png)

1. Нажмите на **Settings**.

1. Чтобы снизить вероятность слишком частой балансировки, увеличьте следующие пороговые значения балансировщика Hive:

    #|
    || Параметр | Описание | Значение по умолчанию ||
    || MinCounterScatterToBalance
    | Пороговое значение для значения разброса ресурса counter. При достижении этого значения Hive начинает балансировать нагрузку
    | 0.02 ||
    || MinCPUScatterToBalance
    | Пороговое значение для значения разброса ресурса процессора. При достижении этого значения Hive начинает балансировать нагрузку
    | 0.5 ||
    || MinMemoryScatterToBalance
    | Пороговое значение для значения разброса ресурса оперативной памяти. При достижении этого значения Hive начинает балансировать нагрузку
    | 0.5 ||
    || MinNetworkScatterToBalance
    | Пороговое значение для значения разброса ресурса сетевого трафика. При достижении этого значения Hive начинает балансировать нагрузку
    | 0.5 ||
    || MaxNodeUsageToKick
    | Пороговое значение использования ресурсов узла {{ ydb-short-name }}. При достижении этого значения Hive начинает срочную балансировку
    | 0.9 ||
    || ObjectImbalanceToBalance
    | Пороговое значение метрики дисбаланса объекта базы данных
    | 0.02 ||
    |#

    {% note info %}

    В этих параметрах используются относительные значения, где 1.0 соответствует 100% и фактически отключает балансировку. Если общее значение аппаратных ресурсов может превышать 100%, скорректируйте значение настройки соответствующим образом.

    {% endnote %}

[*count]: Count — фиктивный ресурс, используемый для равномерного распределения таблеток одного типа между узлами.
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/ydb-updates.md
> +Кроме того, новая версия {{ ydb-short-name }} может обрабатывать запросы по-другому. Хотя производительность, как правило, повышается с каждым обновлением, в некоторых пограничных случаях производите
```suggestion
# Процедура последовательного перезапуска

Кластеры {{ ydb-short-name }} могут обновляться без простоев, поскольку обычно они содержат избыточные компоненты и поддерживает процедуру последовательного перезапуска. Чтобы обеспечить постоянную доступность данных, {{ ydb-short-name }} включает в себя систему управления кластером (CMS), которая отслеживает все сбои в работе и узлы, отключённые для обслуживания, например при перезапуске. CMS останавливает новые запросы на обслуживание, если они могут поставить под угрозу доступность данных.

Однако, даже если данные всегда доступны, перезапуск всех узлов за относительно короткий промежуток времени может оказать заметное влияние на общую производительность. Каждая [таблетка](../../../../concepts/glossary.md#tablet), которая выполнялась на перезапускаемом узле, будет запущена снова на другом узле. Перемещение таблетки между узлами требует времени и может повлиять на задержки запросов, связанных с ней. Смотрите рекомендации [по процедуре последовательного перезапуска](#rolling-restart).

Кроме того, новая версия {{ ydb-short-name }} может обрабатывать запросы по-другому. Хотя производительность, как правило, повышается с каждым обновлением, в некоторых пограничных случаях производительность может снижаться. Смотрите рекомендации [по производительности разных версий](#version-performance).
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/ydb-updates.md
> +Кластеры {{ ydb-short-name }} могут обновляться без простоев, поскольку {{ ydb-short-name }} обычно содержит избыточные компоненты и поддерживает процедуру последовательного перезапуска. Чтобы обеспе
cms лучше сослаться на глоссарий

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/ydb-updates.md
> +
```suggestion
## Диагностика

{% note warning %}

Диагностика последовательных перезапусков и обновлений {{ ydb-short-name }} основана только на вторичных признаках. Чтобы быть абсолютно уверенным в том, что происходит обновление или последовательный перезапуск узлов, обратитесь к администратору вашей базы данных.

{% endnote %}

Чтобы проверить, не обновляется ли {{ ydb-short-name }} кластер:

1. Откройте [Встроенный UI](../../../../reference/embedded-ui/index.md).

1. На вкладке **Nodes** проверьте, отличаются ли версии {{ ydb-short-name }} на узлах.

    Также проверьте, имеют ли узлы с новой версией {{ ydb-short-name }} более низкие значения времени с момента запуска (uptime).

    ![](_assets/updates.png)

{% note alert %}

Низкий uptime узла {{ ydb-short-name }} может также указывать на другие проблемы. Например, см. [{#T}](../hardware/insufficient-memory.md).

{% endnote %}
```

2025-01-28 06:25 UTC, blinkov commented on ydb/docs/ru/core/dev/troubleshooting/performance/ydb/ydb-updates.md
> +Сообщайте о любых выявленных проблемах с производительностью на  [GitHub {{ ydb-short-name }}](https://github.com/ydb-platform/ydb/issues/new). Предоставьте контекст и все детали, которые могут помоч
```suggestion
### В случае последовательного перезапуска {#rolling-restart}

Если из-за процесса последовательного перезапуска кластера {{ ydb-short-name }} задержки приложения вырастают выше критического уровня, подумайте о том, чтобы замедлить процесс перезапуска:

1. Если узлы перезапускаются группами, сократите размер групп, вплоть до одного узла за раз.

1. Разнесите во времени перезагрузки в каждом датацентре и/или серверной стойке.

1. Вставьте дополнительные паузы между перезагрузками.

### В случае отличий в работе разных версий {#version-performance}

Целью является как можно более раннее обнаружение негативного влияния новой версии {{ ydb-short-name }} на скорость выполнения определённых запросов в конкретной пользовательской нагрузке:

1. Просмотрите [список изменений {{ ydb-short-name }} сервера](../../../../changelog-server.md), обращая особое внимание на изменения, связанные с производительностью и относящиеся к вашей рабочей нагрузке.

1. Используйте выделенный кластер для тестирования {{ ydb-short-name }} под нагрузкой, которая настолько точно соответствует вашей рабочей нагрузке, насколько это возможно. Всегда сначала развёртывайте новую версию {{ ydb-short-name }} на таких кластерах, чтобы оценить влияние новой версии в тестовом окружении. Отслеживайте задержки как на стороне клиента, так и на стороне сервера, чтобы выявить любые потенциальные проблемы с производительностью.

1. Используйте канареечное развертывание (canary deployment), обновив сначала только один узел кластера и проанализировав любые изменения в его поведении. Если всё выглядит стабильно, постепенно распространите обновление на большее количество узлов, например, на всю серверную стойку или датацентр, и повторяйте проверки на наличие аномалий. Если возникнут какие-либо проблемы, немедленно вернитесь к предыдущей версии и попытайтесь воспроизвести проблему в тестовой среде.

Сообщайте о любых выявленных проблемах с производительностью на [GitHub {{ ydb-short-name }}](https://github.com/ydb-platform/ydb/issues/new). Предоставьте контекст и все детали, которые могут помочь воспроизвести проблему.
```

2025-01-29 06:43 UTC, fomichev3000 approved these changes

2025-01-29 10:06 UTC, merged