Docs: authorization
ydb-platform/ydb pull request #12771
Opened 2024-12-19 11:01 UTC by azevaykin

### Changelog entry 

Rewrite docs about authorization

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-23 11:55 UTC, anton-bobkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-user.md
> +  * Если опустить данную опцию — это эквивалентно `PASSWORD NULL`.
```suggestion
  Значение по умолчанию: `PASSWORD NULL`.
```

2024-12-23 11:55 UTC, anton-bobkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-user.md
> +возможность задать список пользователей через запятую: `DROP USER [IF EXISTS] user1,user2,user3`.
```suggestion
* `user_name` — имя удаляемого пользователя. Поддерживается возможность задать список пользователей через запятую: `DROP USER [IF EXISTS] user1,user2,user3`.
```

2024-12-23 11:55 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/terraform.md
> +* `password` - пароль для доступа к базе данных в случае использования аутентификации по [логину и паролю](../security/authentication.md#static-credentials)
```suggestion
* `user` - имя пользователя для доступа к базе данных в случае использования аутентификации по [логину и паролю](../security/authentication.md#static-credentials).
* `password` - пароль для доступа к базе данных в случае использования аутентификации по [логину и паролю](../security/authentication.md#static-credentials).
```

2024-12-23 12:17 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +* [{#T}](../yql/reference/syntax/create-user.md)
Пробовал, некрасиво выглядит.

2024-12-23 12:17 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +* [{#T}](../yql/reference/syntax/alter-user.md)
Пробовал, некрасиво выглядит.

2024-12-23 12:17 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +* [{#T}](../yql/reference/syntax/drop-user.md)
Пробовал, некрасиво выглядит.

2024-12-23 12:25 UTC, azevaykin commented on ydb/docs/ru/core/security/right.md
> +Это команды принимают названия прав в обоих стилях: "{{ ydb-short-name }} право.2 и "Ключевое слово YQL".
done

2024-12-24 11:56 UTC, ijon commented on ydb/docs/ru/core/security/authorization.md
> +* [Владелец](#owner)
Вообще, не хватает именно описания модели управления доступом в совокупности.

Что есть источники пользователей (auth-домены), откуда и приходят SID'ы пользователей. Что права/разрешения связаны со схемными объектами, а не с пользователями. Что SID это просто строка, записываемая в ACL правило на схемном объекте. И так далее.
Чтобы субъекты, объекты, права и действия были связаны воедино в одном месте.

2024-12-24 12:13 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +* [Владелец](#owner)
Проговорили, что в следующих версиях.

2024-12-24 12:29 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Субъект доступа идентифицируется SID (Security Identifier) в формате `"login@subsystem"`. Суффикс `subsystem` — это пространство имён, внутри которого гарантируется уникальность всех login.
d1f12e139ff9064793eaf3ce1a836f101beb64c0

2024-12-24 12:29 UTC, azevaykin commented on ydb/docs/ru/core/security/right.md
> +`ydb.generic.list` | `LIST` | Синоним `ydb.granular..describe_schema`
d1f12e139ff9064793eaf3ce1a836f101beb64c0

2024-12-24 12:29 UTC, azevaykin commented on ydb/docs/ru/core/reference/ydb-cli/_includes/commands.md
> -scheme permissions set-inheritance | Установка наследования разрешений
d1f12e139ff9064793eaf3ce1a836f101beb64c0

2024-12-24 21:56 UTC, ijon commented on ydb/docs/ru/core/security/group.md
> +Любого пользователя можно включить ту или иную группу доступа или исключить из неё. Как только пользователь включается в группу доступа, он получает все права на объекты базы данных, которые предоста
Не сказано, что в группу можно включать не только пользователей, но и другие группы. Без включения групп в группы, кстати, может быть трудно построить развесистые бизнес-роли. И встроенные группы ниже тоже построены на иерархии включений

2024-12-25 10:42 UTC, azevaykin commented on ydb/docs/ru/core/security/group.md
> +Любого пользователя можно включить ту или иную группу доступа или исключить из неё. Как только пользователь включается в группу доступа, он получает все права на объекты базы данных, которые предоста
0b47532e237676791bf1faeff0763f8fe3c99a9f

2024-12-27 10:09 UTC, blinkov requested changes

2024-12-27 10:09 UTC, blinkov commented on ydb/docs/ru/core/security/right.md
> +## Перечень прав
Кажется такая таблица уже где-то была, вероятно в справке по YQL — если так, то надо оставить у неё единственный источник правды (в разделе `reference/`), а из всех остальных мест сослаться.

2024-12-27 10:09 UTC, blinkov commented on ydb/docs/ru/core/security/toc_p.yaml
> +  href: right.md
В общем, я понял: этих двух статей просто не должно существовать. Они состоят из двух частей: первая половина с определениями, которой место в глоссарии, а вторая — со справкой по правам доступа, встроенным группам и т.п., которой место в справке.

А все разделы «Для такая-то роль» преднозначены для практических инструкций, например можно, собственно рассказать как мы рекомендуем конфигурировать аутентификацию+авторизацию в типовых сценариях. Сначала объяснить целевую картину, а потом привести конкретные примеры команд как её добиться, пригодных для копирования в терминал.

2024-12-27 10:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-user.md
> +* `user_name` — имя удаляемого пользователя. Поддерживается возможность задать список пользователей через запятую: `DROP USER [IF EXISTS] user1,user2,user3`.
```suggestion
* `user_name` — имя удаляемого пользователя. Поддерживается возможность задать список пользователей через запятую, например: `DROP USER user1, user2, user3;`.
```

2024-12-27 10:37 UTC, azevaykin commented on ydb/docs/ru/core/security/authentication.md
> +Под клиентом аутентификации понимается SDK или CLI.
Это точно чуть позже, в отдельных PR.

2024-12-27 10:43 UTC, azevaykin commented on ydb/docs/ru/core/security/group.md
> +Ниже показано, как группы наследуют разрешения друг друга. Например, в `DATA-WRITERS` входят все разрешения `DATA-READERS`:
Точно красиво будет смотреться точка в конце коротких фраз в таблице?

2024-12-27 10:48 UTC, azevaykin commented on ydb/docs/ru/core/security/right.md
> +## Перечень прав
Да, это в GRANT и REVOKE есть. Дедуплицирую.

2024-12-28 06:35 UTC, fomichev3000 requested changes

2024-12-28 06:35 UTC, fomichev3000 commented on ydb/docs/ru/core/security/authentication.md
> +Под клиентом аутентификации понимается [SDK](../reference/ydb-sdk/index.md) или [CLI](../reference/ydb-cli/index.md).
ИМХО под клиентом аутентификации понимается любой, кто дергает grpc или http. Это может быть grpccurl и curl, соответственно

2024-12-28 06:35 UTC, fomichev3000 commented on ydb/docs/ru/core/security/authentication.md
> +* Анонимная аутентификация — включена по умолчанию и доступна сразу после [установки кластера](../devops/index.md).
Я полагаю порядок должен быть другой у пунктов:
1. анонимная
2. user/password
3. LDAP
4. Сторонний IAM провайдер

2024-12-28 09:08 UTC, azevaykin commented on ydb/docs/ru/core/security/authentication.md
> +Под клиентом аутентификации понимается [SDK](../reference/ydb-sdk/index.md) или [CLI](../reference/ydb-cli/index.md).
c09a4f8aa9bd0c47931ca2c2a68a7f8c08d6fcf5

2024-12-28 09:08 UTC, azevaykin commented on ydb/docs/ru/core/security/authentication.md
> +* Анонимная аутентификация — включена по умолчанию и доступна сразу после [установки кластера](../devops/index.md).
c09a4f8aa9bd0c47931ca2c2a68a7f8c08d6fcf5

2024-12-28 12:50 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Субъект доступа идентифицируется SID (Security Identifier) в формате `"login@subsystem"`. Суффикс `subsystem` — это пространство имён, внутри которого гарантируется уникальность всех login.
Проговорили, что SID = Security Identifier
И правильно говорить User SID и Group SID

Примеры [тут](https://a.yandex-team.ru/arcadia/contrib/ydb/library/aclib/aclib.h?rev=r15598787#L79): 
```cpp
TString UserSID;
TVector<TString> GroupSIDs;
TSID GetUserSID() const;
TVector<TSID> GetGroupSIDs() const;
void AddGroupSID(const TSID& groupSID);
void SetGroupSIDs(const TVector<TString>& groupSIDs);
```

2024-12-28 12:51 UTC, azevaykin commented on ydb/docs/ru/core/security/right.md
> +## Перечень прав
a0c39968fdb69731c452bd867e64f6dc7baedad5

2024-12-30 11:29 UTC, azevaykin commented on ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
> +`--timeout ms` - технологический параметр, задающий таймаут на отклик сервера. Для наших операций не критичен и здесь мы его не применяем.
40012b0f7adf6ac96da432f85b01a15891ac6662

2024-12-30 11:29 UTC, azevaykin commented on ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
> +`--timeout ms` - технологический параметр, задающий таймаут на отклик сервера. Для наших операций не критичен и здесь мы его не применяем.
40012b0f7adf6ac96da432f85b01a15891ac6662

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
> +В текущей версии {{ ydb }} есть ограничение, что только непосредственно текущий владелец схемного объекта может сменить владельца.
Не понял вопрос.
Есть текущий владелец (пользователь или группа) и только он может сменить владельца.

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
> +Команда `set-inheritance` позволяет установить наследование разрешений для схемного объекта.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authentication.md
> +* Анонимная аутентификация — включена по умолчанию и доступна сразу после [установки кластера](../devops/index.md).
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +{{ ydb-short-name }} позволяет работать с пользователями из разных каталогов и систем, и они отличаются с использованием суффикса.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Ограничений по количеству пользователей в группе нет. Группа доступа может быть пустой, когда в неё не входит ни один пользователь.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +У каждого такого объекта есть список разрешений — ACL (Access Control List) — он хранит все предоставленные пользователям и группам права на объект.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/group.md
> +![groups](../_assets/groups.svg)
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/right.md
> +Обладание правом в {{ ydb-short-name }} даёт возможность выполнять определённые операции в кластере или базе данных.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2024-12-30 12:00 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Ограничений по количеству пользователей в группе нет. Группа доступа может быть пустой, когда в неё не входит ни один пользователь.
f8c57f4d227fa929d14d425b04a10aa3f6d7b24f

2025-01-10 15:36 UTC, azevaykin commented on ydb/docs/ru/core/security/group.md
> +## Основные понятия
93cbfa2a6d1145cc5b21e9e001f92cd9d23babfc

2025-01-10 15:41 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Авторизация в {{ ydb-short-name }} основана на понятиях:
Скопировал в глоссарий. Лучше тут тоже оставить для гладкости чтения.
002bc0e28b15146339cf63956d46ebc32d7e7f01

2025-01-10 15:44 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Подробнее о правах и их полный перечень: [{#T}](right.md).
93cbfa2a6d1145cc5b21e9e001f92cd9d23babfc

2025-01-10 15:50 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +У каждого объекта доступа есть владелец, в том числе у кластера в целом и каждой базы данных.  Владельцем объекта по умолчанию становится субъект доступа, создавший объект.
69c10469f594eaf925c09fb5d97c95717cca38c4

2025-01-10 15:50 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Пример команды chown:
69c10469f594eaf925c09fb5d97c95717cca38c4

2025-01-10 15:51 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Права в {{ ydb-short-name }} выдаются на объекты доступа (узлы дерева директорий).
69c10469f594eaf925c09fb5d97c95717cca38c4

2025-01-10 16:02 UTC, azevaykin commented on ydb/docs/ru/core/security/authentication.md
> +Логин пользователя может содержать только строчные буквы латинского алфавита и цифры.
175af5c3213920f1b37a0b895dea18349a9e36d8

2025-01-10 16:02 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Суффикс `@<subsystem>` идентифицирует "источник пользователя" или "auth-домен", внутри которых гарантируется уникальность всех `login`. Например, в случае интеграции с LDAP, имена пользователей будут
175af5c3213920f1b37a0b895dea18349a9e36d8

2025-01-10 16:02 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Директории организованы в иерархическую структуру объектов схемы и вложенных в них объектов: баз данных, таблиц, представлений, топиков. Директории могут содержать поддиректории, и такая вложенность
175af5c3213920f1b37a0b895dea18349a9e36d8

2025-01-10 16:02 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Независимо от метода аутентификации, авторизация всегда выполняется на стороне {{ ydb-short-name }} на основе хранящейся в ней информацию об объектах и правах доступа. Права доступа определяют набор
175af5c3213920f1b37a0b895dea18349a9e36d8

2025-01-10 17:12 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Пример использования команды GRANT:
f3834b72d5dee2eddfb9aace62cf3a90309e083a

2025-01-10 17:12 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Группа пользователей - именованное множество пользователей, предназначенное для упрощения контроля доступа.
f3834b72d5dee2eddfb9aace62cf3a90309e083a

2025-01-10 17:12 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +Отдельно выделяется пользователь `root`. Он создается при [первоначальной установке кластера](../devops/manual/initial-deployment#initialize-cluster), в ходе которой ему нужно сразу [установить парол
f3834b72d5dee2eddfb9aace62cf3a90309e083a

2025-01-13 06:14 UTC, blinkov submitted a review, later dismissed

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/security/authorization.md
> +Авторизация в {{ ydb-short-name }} основана на понятиях:
Не-не, копипасту в доке нельзя. Оно уже разъехалось и будет дальше только сильнее разъезжаться. Кто не в первый раз с безопасностью в СУБД работает в целом терминология и так будет понятна и это только кучу лишнего текста проскролливать, а новеньким в любом случае стоит с терминологией в целом познакомиться в глоссарии прежде чем в такие темы погружаться.

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/security/authorization.md
> +Авторизация в {{ ydb-short-name }} основана на понятиях:
Контент в разделах «Для такая-то роль» должен быть практичным, отсюда люди должны уходить с рекомендованным образом настроенной авторизацией, а не чуть расширенной по сравнению с глоссарием теорией.

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/security/authorization.md
> +* [Владелец](#owner)
А можно ссылку/номер тикета или issue сюда прикопать для истории?

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/security/authorization.md
> +Независимо от метода [аутентификации](https://ru.wikipedia.org/wiki/Аутентификация), [авторизация](https://ru.wikipedia.org/wiki/Авторизация) всегда выполняется на стороне {{ ydb-short-name }} на осн
```suggestion
Независимо от метода [аутентификации](https://ru.wikipedia.org/wiki/Аутентификация), [авторизация](https://ru.wikipedia.org/wiki/Авторизация) всегда выполняется на серверной стороне {{ ydb-short-name }} на основе хранящейся в ней информации об объектах и правах доступа. Права доступа определяют набор доступных для выполнения операций.
```

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/security/authorization.md
> +### Группа {#group}
Это тоже надо в глоссарий. Особенно что пользователей и групп пользователей там нет — большое историческое упущение.

2025-01-13 06:14 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/permissions/permissions_list.md
> +Права `ydb.database.connect`, `ydb.granular.describe_schema`, `ydb.granular.select_row`, `ydb.granular.update_row` необходимо рассматривать как слои прав.
Про слои на словах как-то не понятно. Похоже тут нужна картинка с графом зависимостей по аналогии с builtin_groups.svg для встроенных групп.

2025-01-13 08:54 UTC, azevaykin commented on ydb/docs/ru/core/security/authorization.md
> +* [Владелец](#owner)
YDBDOCS-979

2025-01-13 09:03 UTC, azevaykin commented on ydb/docs/ru/core/concepts/glossary.md
> +Более подробно об [авторизации](../security/authentication.md).
Префикс `access-` - нормально.

2025-01-15 02:51 UTC, blinkov commented on ydb/docs/ru/core/security/authentication.md
> +Анонимная аутентификация включена по умолчанию и доступна сразу после [установки кластера](../devops/index.md)
```suggestion
```
В общем, ещё подумал и кажется эту строку лучше просто удалить. Предыдущая предупреждает, что лучше не пользоваться, а чуть ниже — какой настройкой это контролируется.
Пытаться объяснить где что по умолчанию только запутывает.

2025-01-15 08:41 UTC, fomichev3000 requested changes

2025-01-15 09:47 UTC, azevaykin commented on ydb/docs/ru/core/concepts/glossary.md
> +**Объект доступа** или **access object** при [авторизации](../security/authorization.md) — сущность, для которой настраиваются права и ограничения доступа. В {{ ydb-short-name }} объектами доступа яв
Ввел понятие "объект схемы"

6450e86423e7e97d3989ee96617e7fc0f24a8435

2025-01-15 10:37 UTC, blinkov commented on ydb/docs/ru/core/concepts/glossary.md
> +**Объект доступа** или **access object** при [авторизации](../security/authorization.md) — сущность, для которой настраиваются права и ограничения доступа. В {{ ydb-short-name }} объектами доступа яв
@azevaykin его стоит сделать отдельным термином с заголовком и из определения директории и других релевантных мест на этот заголовок ссылаться

2025-01-15 11:21 UTC, azevaykin commented on ydb/docs/ru/core/concepts/glossary.md
> +**Объект доступа** или **access object** при [авторизации](../security/authorization.md) — сущность, для которой настраиваются права и ограничения доступа. В {{ ydb-short-name }} объектами доступа яв
@blinkov вынес в отдельный термин: 11484efa2fb8fff20fc424759ed3f62e1a6f6fa5

2025-01-15 13:32 UTC, fomichev3000 approved these changes

2025-01-15 13:32 UTC, merged