YQ-3988 Add stop session reason
ydb-platform/ydb pull request #12839
Opened 2024-12-20 12:50 UTC by kardymonds

### Changelog entry 

...

### Changelog category 
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-24 06:31 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    enum StopReason {
Добавил E

2024-12-24 16:02 UTC, GrigoriyPA submitted a review, later dismissed

2024-12-24 16:09 UTC, dorooleg requested changes

2024-12-24 16:09 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
> +    // TODO: not working GrabEdgeEvent()
А точно этот комментарий нужен?

2024-12-24 16:09 UTC, dorooleg commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> -        SendStopSession(ev->Sender, partitionId, ev->Cookie);
Не до конца понимаю почему нельзя было послать новый generation. Который сейчас в dq_pq_rd_read_actor и по нему в row_dispatcher все старые поудалять?

2025-01-09 05:56 UTC, kardymonds commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> -        SendStopSession(ev->Sender, partitionId, ev->Cookie);
Предположим что клиент в RD не удалился (сообщение не дошло и т.п.). 
Далее может быть 2 случая когда read_actor переподключается к RD (предположим одна партиция):
1. read_actor идет к тому же RD. RD на StartSession видит бОльший generation и пересоздает клиента, 
2. read_actor идет к другому же RD (координатор сменился и раздал другое распределение). Теперь read_actor о старом RD ничего не знает. В старом RD сессия жива и RD периодически посылает heartbeat. read_actor (на heartbeat) отвечает StopSession при этом проставляя невалидный SeqNo (он и не знает какой нужен т.к. сессия удалена).

Эту проблему можно решить по другому, например на StopSession не проверять SeqNo.

2025-01-16 14:28 UTC, dorooleg commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> -        SendStopSession(ev->Sender, partitionId, ev->Cookie);
В моем понимании все эти не совместимости должны решаться через пинги в обе стороны и seq no. Так а если не проверять seq no на stop session как ты поймешь что он только для старой сессии?

2025-01-17 14:13 UTC, dorooleg commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> -        SendStopSession(ev->Sender, partitionId, ev->Cookie);
Ладно согласен на это ревью, но предложил бы подумать как через seq no везде такие случаи обрабатывать

2025-01-17 14:13 UTC, dorooleg submitted a review, later dismissed

2025-01-20 07:21 UTC, kardymonds commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> -        SendStopSession(ev->Sender, partitionId, ev->Cookie);
Переделал: Heartbeat (+ ответ на него TEvNoSession) ходят теперь без проверки seqNo,

2025-01-20 10:19 UTC, dorooleg approved these changes

2025-01-20 10:22 UTC, merged