use canonized storage path as tier id
ydb-platform/ydb pull request #12833
Opened 2024-12-20 12:22 UTC by swalrus1

### Changelog entry 

Canonize storage path in CS Tiers

### Changelog category 

* Bugfix 

### Additional information

...

2025-01-09 17:11 UTC, fexolm approved these changes

2025-01-16 11:25 UTC, vlad-gogov requested changes

2025-01-16 11:25 UTC, vlad-gogov commented on ydb/core/kqp/ut/olap/tiering_ut.cpp
> +        TestHelper->SetTiering("/Root/olapStore/olapTable", "Root/tier1", "timestamp");
Хотелось бы тест, который работал проверял работу в двух режима, где ставится "/" и нет.

2025-01-16 11:25 UTC, vlad-gogov commented on ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.h
> +        sb << "storage=" << (ExternalStorageId ? ExternalStorageId->GetConfigPath() : "") << ";duration=" << EvictDuration << ";column=" << EvictColumnName
По старой логике, как я понимаю, писался бы __DELETE, поэтому хотелось бы сохранить предыдущий вывод

2025-01-16 11:25 UTC, vlad-gogov commented on ydb/core/tx/tiering/manager.h
> +        NTiers::TExternalStorageId TierId;
Почему убрал YDB_READONLY_DEF?

2025-01-16 12:05 UTC, vlad-gogov approved these changes

2025-01-16 13:25 UTC, merged