Export changefeed's configuration to s3
ydb-platform/ydb pull request #12882
Opened 2024-12-23 13:35 UTC by stanislav-shchetinin

### Changelog entry

Export changefeed's configuration to s3

### Changelog category

* New feature

### Additional information

...

2024-12-24 12:45 UTC, CyberROFL requested changes
Тебе же не `NKikimrSchemeOp::TPersQueueGroupDescription` нужно положить в резервную копию, а `changefeed_description.pb` и `topic_description.pb`. Так же, как в бэкапах на локальную фс.

2024-12-24 12:45 UTC, CyberROFL commented on ydb/core/tx/datashard/backup_restore_traits.h
> +    return Sprintf("%s/persqueue_description.pb", objKeyPattern.c_str());
В бэкапах на файловую систему нет такого файла. Мы же согласовали `changefeed_description.pb` и `topic_description.pb`.

2024-12-24 12:45 UTC, CyberROFL commented on ydb/core/protos/flat_scheme_op.proto
> +    repeated TPathDescription PersQueue = 16; // for further restore
```suggestion
    repeated TPathDescription PersQueues = 16; // for further restore
```

т.к. `repeated`.

2024-12-26 18:22 UTC, CyberROFL requested changes
Ye;

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/protos/flat_scheme_op.proto
> +    repeated TPathDescription PersQueue = 17; // for further restore
```suggestion
    repeated TPathDescription ChangefeedUnderlyingTopics = 17; // for further restore
```
Чтобы было понятно будущим поколениям.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +        Cerr << "srcD: " << sourceDescription.DebugString() << Endl;
Дебажную печать нужно не забыть убрать перед коммитом.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +        for (const auto& x : cdcDesc) {
```suggestion
        for (const auto& x : sourceDescription.GetTable().GetCdcStreams()) {
```

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +        auto cdcDesc = sourceDescription.GetTable().GetCdcStreams();
Этот код должен быть внутри ветки `if (sourceDescription.HasTable())`.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +            auto cdcPathDesc =  GetDescription(ss, pathId);
```suggestion
            auto cdcPathDesc = GetDescription(ss, TPathId::FromProto(x.GetPathId()));
```

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +                    *newPersQueue = GetDescription(ss, pathId);
```suggestion
                    *task.AddPersQueue() = GetDescription(ss, TPathId(child.GetSchemeshardId(), child.GetPathId()));
```

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +        Cerr << "tsz: " << task.GetPersQueue().size() << Endl;
Дебажная печать.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3.h
> +struct TChangefeedExportDescriptions {
Это надо унести максимально близко к месту использования и не светить тут зависимости на ydb/public/api.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_common.h
> +Ydb::Topic::DescribeTopicResult GenYdbDescribeTopicResult(
Договорились в личке, что конвертация описания топика из приватного в публичный формат должна жить в ydb/core/ydb_convert. Этот рефакторинг нужно выложить отдельным pr.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    TVector <TChangefeedExportDescriptions> changefeedsExportDescs(changefeedsCount);
Лучше reserve + push_back/emplace_back.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    const int changefeedsCount = changefeeds.SpaceUsedExcludingSelf();
Что вернет функция `SpaceUsedExcludingSelf`?

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    FillChangefeedDescription(descTableResult, Task.GetTable().GetTable());
Нужно выделить функцию конвертация описания changefeed и звать её. Что-то вроде:
```cpp
void FillChangefeedDescription(Ydb::Table::ChangefeedDescription& out, const NKikimrSchemeOp::TCdcStreamDescription& in);
```

Тоже отдельным pr.

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    const TVector<TChangefeedExportDescriptions> ChangefeedsExportDescs;
```suggestion
    const TVector<TChangefeedExportDescriptions> Changefeeds;
```

2024-12-26 18:22 UTC, CyberROFL commented on ydb/core/protos/flat_scheme_op.proto
> +    repeated TPathDescription PersQueue = 17; // for further restore
Нужно еще не забыть по аналогии вот с этим:
https://github.com/ydb-platform/ydb/blob/aa12ad5be3743bb6113524e310a9de7f369e690c/ydb/core/tx/schemeshard/schemeshard__operation_create_backup.cpp#L47

Занулять это новое поле. Это нужно, чтобы схема таблицы и changefeed-ов попадала только на первый (нулевой) шард таблицы, т.к. только он выгружает её в S3. Остальным она не нужна. Это сэкономит память и сеть.

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/extstorage_usage_config.h
> +        return TStringBuilder() << ObjectKeyPattern << '/'<< changefeedName << "/" << NBackupRestoreTraits::TopicKeySuffix();
```suggestion
        return TStringBuilder() << ObjectKeyPattern << '/'<< changefeedName << '/' << NBackupRestoreTraits::TopicKeySuffix();
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/extstorage_usage_config.h
> +        return TStringBuilder() << ObjectKeyPattern << '/' << changefeedName << "/" << NBackupRestoreTraits::ChangefeedKeySuffix();
```suggestion
        return TStringBuilder() << ObjectKeyPattern << '/' << changefeedName << '/' << NBackupRestoreTraits::ChangefeedKeySuffix();
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    TVector <TChangefeedExportDescriptions> changefeedsExportDescs;
Можно, наверно, просто `changefeeds`. У тебя оно и внутри загрузчика называется `Changefeeds`.

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +        changefeedsExportDescs.emplace_back(changefeedDesc, topic);
```suggestion
        Ydb::Table::ChangefeedDescription changefeed;
        const auto& cdcStream = cdcStreams.at(i);
        FillChangefeedDescription(changefeed, cdcStream);

        Ydb::Topic::DescribeTopicResult topic;
        const auto& pq = persQueuesTPathDesc.at(i);
        Ydb::StatusIds::StatusCode status;
        TString error;
        FillTopicDescription(topic, pq.GetPersQueueGroup(), pq.GetSelf(), cdcStream.GetName(), status, error);

        changefeedsExportDescs.emplace_back(changefeed, topic);
```

Общий совет: объявлять переменные поближе к месту использования. Еще я предлагаю немного сократить названия переменных.

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    const auto& persQueuesTPathDesc = Task.GetChangefeedUnderlyingTopics();
```suggestion
    const auto& persQueues = Task.GetChangefeedUnderlyingTopics();
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    template<typename T>
```suggestion
    template <typename T>
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    void PutDescription(const google::protobuf::Message& desc, const TString& key, TString& checksum, T stateFunc) {
А для загрузки схемы таблицы можно эту же функцию переиспользовать? (можно отдельным pr)

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +        return Changefeeds[IndexExportedChangefeed].ChangefeedDescription.Getname();
```suggestion
    const TString& GetCurrentChangefeedName() const {
        return Changefeeds.at(IndexExportedChangefeed).ChangefeedDescription.GetName();
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +        , Changefeeds(GenChangefeeds())
```suggestion
            : Count(count)
            , S3Mock(s3Mock)
            , Changefeeds(GenChangefeeds())
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +        const TVector<TString>& GetChangefeeds() {
```suggestion
        const TVector<TString>& GetChangefeeds() const {
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +        static TString GenChangefeedName(const ui64 num) {
```suggestion
        static TString GenChangefeedName(const ui64 num) {
```

2025-01-16 09:14 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +    Y_UNIT_TEST(Changefeeds) {
Стоит еще добавить тест с ребутами (можно отдельно).

2025-01-16 10:47 UTC, stanislav-shchetinin commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +        return Changefeeds[IndexExportedChangefeed].ChangefeedDescription.Getname();
У `Ydb::Table::ChangefeedDescription` нету метода  `GetName()`

2025-01-16 10:50 UTC, stanislav-shchetinin commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +        return Changefeeds[IndexExportedChangefeed].ChangefeedDescription.Getname();
```

2025-01-16 10:51 UTC, stanislav-shchetinin commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +        return Changefeeds[IndexExportedChangefeed].ChangefeedDescription.Getname();
``` cpp
error: no member named 'GetName' in 'Ydb::Table::ChangefeedDescription'; did you mean 'Getname'?
  247 |         return Changefeeds.at(IndexExportedChangefeed).ChangefeedDescription.GetName();
      |                                                                              ^~~~~~~
      |                                                                              Getname
```

2025-01-16 11:46 UTC, pixcc requested changes

2025-01-16 11:46 UTC, pixcc commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +                UNIT_ASSERT(changefeed);
Еще неплохо было бы проверить контент файла

2025-01-16 11:46 UTC, pixcc commented on ydb/core/tx/datashard/export_s3_uploader.cpp
> +    TVector<TChangefeedExportDescriptions> Changefeeds;
const?

2025-01-16 11:57 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +                    }
Обе функции возвращают `TPathDescription`. Просто одна заполняет `SetTableDescriptionOptions`, а вторая `SetChangefeedDescriptionOptions`. Но второй набор на самом деле должен называться:
- `SetTopicDescriptionOptions `;
- `GetTopicDescription `.

2025-01-16 13:44 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +    opts.SetShowPrivateTable(true);
Для changefeed-ов не работает без этого флага? Вообще должно.

2025-01-16 13:44 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +                UNIT_ASSERT_VALUES_EQUAL(*changefeed, Sprintf("name: \"update_feed%d\"\nmode: MODE_UPDATES\nformat: FORMAT_JSON\nstate: STATE_ENABLED\n", i));
```suggestion
                UNIT_ASSERT_VALUES_EQUAL(*changefeed, Sprintf(R"(
name: "update_feed%d"
mode: MODE_UPDATES
format: FORMAT_JSON
state: STATE_ENABLED
)", i));
```

2025-01-16 14:04 UTC, stanislav-shchetinin commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +    opts.SetShowPrivateTable(true);
Я изначально как раз с changefeed'ами баг поймал, у них в пути есть `Table`. Запустил тест без этой опции - он валится.

2025-01-16 14:06 UTC, stanislav-shchetinin commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +                UNIT_ASSERT_VALUES_EQUAL(*changefeed, Sprintf("name: \"update_feed%d\"\nmode: MODE_UPDATES\nformat: FORMAT_JSON\nstate: STATE_ENABLED\n", i));
Работает только так:
``` cpp
UNIT_ASSERT_VALUES_EQUAL(*changefeed, Sprintf(R"(name: "update_feed%d"
mode: MODE_UPDATES
format: FORMAT_JSON
state: STATE_ENABLED
)", i));
```

2025-01-16 14:08 UTC, CyberROFL approved these changes, later dismissed

2025-01-16 14:53 UTC, pixcc commented on ydb/core/tx/schemeshard/ut_export/ut_export.cpp
> +                auto* topic = S3Mock.GetData().FindPtr(changefeedDir + "/topic_description.pb");
Ну раз уж добавил для `changefeed` проверку контента, то для топика тоже можно для единообразия.

2025-01-20 08:33 UTC, pixcc approved these changes

2025-01-20 09:14 UTC, CyberROFL approved these changes

2025-01-20 10:14 UTC, merged