Update docs for Digest
ydb-platform/ydb pull request #12889
Opened 2024-12-23 14:59 UTC by avevad

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-12-27 04:38 UTC, blinkov requested changes, later dismissed

2024-12-27 04:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
> +Функции для видов хешей, которые поддерживают значение-параметр seed/init, принимают его опциональным именованным аргументом `Init`.
Seed является вполне устоявшимся термином конкретно для такого, а Init — слишком общее слово. Я бы рекомендовал переименовать это всё в Seed, а Init не использовать.

2024-12-27 04:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
> +Функции для видов хешей, которые поддерживают значение-параметр seed/init, принимают его опциональным именованным аргументом `Init`.
Плюс этого абзаца нет в английской версии.

2024-12-27 07:53 UTC, avevad commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
> +Функции для видов хешей, которые поддерживают значение-параметр seed/init, принимают его опциональным именованным аргументом `Init`.
Дописал

2025-01-13 02:25 UTC, blinkov commented on ydb/docs/en/core/yql/reference/yql-core/udf/list/digest.md
> +The functions for the hashes which support init/seed parameter, accept its value in the optional named argument `Init`.
```suggestion
The functions for the hashes that support the initialization parameter (seed) accept its value in the optional named argument named `Init`.
```

2025-01-13 02:26 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
> +Функции для видов хешей, которые поддерживают значение-параметр seed/init, принимают его опциональным именованным аргументом `Init`.
```suggestion
Функции для видов хешей, которые поддерживают значение-параметр для инициализации (seed), принимают его опциональным именованным аргументом `Init`.
```

2025-01-13 05:55 UTC, fomichev3000 approved these changes

2025-01-13 05:55 UTC, merged