[docs] add 24.3.11.13 to releases page
ydb-platform/ydb pull request #12912
Opened 2024-12-24 11:10 UTC by shmel1k

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-24 12:29 UTC, anton-bobkov commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлено отображение топа запросов по потреблению CPU за последний час.
```suggestion
* Добавлено отображение перечня запросов с максимальным потреблением CPU за последний час.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Enabled modification of retention periods for CDC topics.
```suggestion
* Added support for changing retention periods in CDC topics.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* **_(Experimental)_** Added support for [VIEW](https://ydb.tech/docs/ru/concepts/datamodel/view).
```suggestion
* **_(Experimental)_** Added support for [views](https://ydb.tech/docs/ru/concepts/datamodel/view).
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* **_(Experimental)_** Introduced an [auto-partitioning mode](./concepts/topic#autopartitioning) for topics, where partitions can dynamically split based on load while preserving message read-order a
```suggestion
* **_(Experimental)_** Added an [auto-partitioning mode](./concepts/topic#autopartitioning) for topics, where partitions can dynamically split based on load while preserving message read-order and exactly-once guarantees. [Instructions](https://ydb.tech/docs/ru/yql/reference/syntax/alter-topic#autopartitioning) are provided for managing this mode.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Supported creation and [display](https://github.com/ydb-platform/ydb-embedded-ui/issues/782) of asynchronous replication instances.
```suggestion
* Added support for creating and [viewing information on](https://github.com/ydb-platform/ydb-embedded-ui/issues/782) asynchronous replication instances.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Added](https://github.com/ydb-platform/ydb-embedded-ui/issues/929) an indication for [auto-increment columns](./yql/reference/types/serial).
```suggestion
* [Added](https://github.com/ydb-platform/ydb-embedded-ui/issues/929) an indicator for [auto-increment columns](./yql/reference/types/serial).
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Introduced](https://github.com/ydb-platform/ydb-embedded-ui/pull/1438) a page with information about [tablets](./concepts/glossary#tablet).
```suggestion
* [Added](https://github.com/ydb-platform/ydb-embedded-ui/pull/1438) a page with information about [tablets](./concepts/glossary#tablet).
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Implemented](https://github.com/ydb-platform/ydb-embedded-ui/pull/1218) a setting to add tracing to all queries and display tracing results.
```suggestion
* [Added](https://github.com/ydb-platform/ydb-embedded-ui/pull/1218) a setting to trace all queries and display tracing results.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Introduced](https://github.com/ydb-platform/ydb-embedded-ui/pull/1291) a row limit setting for query editor output and a notification when results exceed the limit.
```suggestion
* [Added](https://github.com/ydb-platform/ydb-embedded-ui/pull/1291) a row limit setting for query editor output and a notification when results exceed the limit.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Added display of top CPU-consuming queries over the last hour.
```suggestion
* Added an option to display top CPU-consuming queries over the last hour.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Enabled search on the history and saved queries pages.
```suggestion
* Added a UI control to search the history and saved queries pages.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Introduced](https://github.com/ydb-platform/ydb-embedded-ui/issues/944) a shortcut to save queries from the editor.
```suggestion
* [Added](https://github.com/ydb-platform/ydb-embedded-ui/issues/944) a shortcut to save queries in the editor.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Supported InterruptInheritance ACL and improved visualization of active ACLs.
```suggestion
* Added support for InterruptInheritance ACL and improved visualization of active ACLs.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Introduced functionality to enable/disable experimental database features.
```suggestion
* Added support for enabling/disabling experimental database features.
```

2024-12-24 14:30 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* [Fixed](https://github.com/ydb-platform/ydb/pull/9509) a hang during the initial scan of CDC when the table is frequently updated.
```suggestion
* [Fixed](https://github.com/ydb-platform/ydb/pull/9509) an issue with an initial scan freezing during CDC when the table is frequently updated.
```

2024-12-24 15:19 UTC, CyberROFL reviewed
ru changelog — lgtm

2024-12-25 11:21 UTC, anton-bobkov submitted a review, later dismissed

2024-12-25 18:12 UTC, antonkovalenko requested changes

2024-12-25 18:12 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен просмотр сессий, установленных с базой данных, с помощью запроса.
А это системное предствление разве не описано? Я не нашёл. Это хороший повод привлечь gvit, уточню

Я бы фразу написал так:

Добавлено системное представление, позволяющее получить информацию о сессиях, установленных с БД, с помошью запроса.

2024-12-25 18:12 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлена поддержка константных значений для колонок по умолчанию.
Добавлена поддержка константных значений для колонок по умолчанию.

Если можно, давайте напишем как

Добавлена поддержка константных значений по умолчанию для колонок таблиц.

если там только для строковых (а скорее так и есть), надо так и написат, что только для строковых

2024-12-25 18:12 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлена возможность изменить период хранения в CDC топиках.
Тут бы ссылку на описание этой возможности или, если этот альтер не описан, на саму фичу cdc

2024-12-25 18:12 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* **_(Экспериментально)_** Добавлен режим [автопартиционирования](./concepts/topic#autopartitioning) топиков, в котором топики могут разбивать партиции в зависимости от нагрузки с сохранением гаранти
Фраза про инструкцию выглядит странно, ведь ни про одну другую фичу мы не призываем пользоваться инструкцией

2024-12-25 18:12 UTC, antonkovalenko commented on ydb/docs/ru/core/changelog-server.md
> +* [Добавлена](https://github.com/ydb-platform/ydb-embedded-ui/pull/1229) вкладка с информацией об экспериментальной функциональности базы данных.
Если это про фиче-флаги, то я бы написал, что добавлена вклада с информацией о состоянии настроек включения экспериментальной функциональности

2024-12-25 18:55 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Initial version of the workload manager was implemented. It allows to create resource pools with CPU, memory and active queries count limits. Resource classifiers was implemented to assign queries
```suggestion
* Initial version of the workload manager was implemented. It allows to create resource pools with CPU, memory and active queries count limits. Resource classifiers were implemented to assign queries to specific resource pool.
```

2024-12-25 19:16 UTC, galnat commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен [стоимостной оптимизатор](./concepts/optimizer#stoimostnoj-optimizator-zaprosov) для сложных запросов к колоночным таблицам, который рассматривает большое количество альтернативных планов
Мы про OLAP хотим в 24.4 писать, поэтому я бы не стала добавлять пока.

2024-12-25 19:17 UTC, galnat commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен просмотр сессий, установленных с базой данных, с помощью запроса.
Документация нет, issue я завела https://github.com/ydb-platform/ydb/issues/12995

2024-12-26 07:35 UTC, anton-bobkov commented on ydb/docs/en/core/changelog-server.md
> +* Added system view that allows you to get information about sessions installed from the database using a query.
```suggestion
* Added a system view with information about sessions installed from the database using a query.
```

2024-12-26 07:40 UTC, anton-bobkov approved these changes, later dismissed

2024-12-26 17:54 UTC, fomichev3000 requested changes

2024-12-26 17:54 UTC, fomichev3000 commented on ydb/docs/en/core/changelog-server.md
> +* Added a [cost-based optimizer](./concepts/optimizer#cost-based-query-optimizer) for complex queries on columnar tables. The cost-based optimizer considers a large number of alternative execution pl
по умолчанию выключен?

2024-12-26 17:54 UTC, fomichev3000 commented on ydb/docs/en/core/changelog-server.md
> +* Added delivery of [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) statistics for [columnar tables](./concepts/datamodel/table#column-oriented-tables) to the query analyze
вообще она выключена и не работает AFAIK

2024-12-26 17:54 UTC, fomichev3000 commented on ydb/docs/en/core/changelog-server.md
> +* Initial version of the workload manager was implemented. It allows to create resource pools with CPU, memory and active queries count limits. Resource classifiers were implemented to assign queries
AFAIK тоже выключено

2024-12-26 17:54 UTC, fomichev3000 commented on ydb/docs/en/core/changelog-server.md
> +* Added support for changing record retention periods in [CDC]((./concepts/cdc)) topics.
я бы подвинул запись, чтобы сгруппировать с остальными строками про CDC

2024-12-26 17:54 UTC, fomichev3000 commented on ydb/docs/en/core/changelog-server.md
> +* **_(Experimental)_** Added an [auto-partitioning mode](./concepts/topic#autopartitioning) for topics, where partitions can dynamically split based on load while preserving message read-order and ex
А вот тут и ниже я удивлен. Автопаритионинг топиков гораздо менее экспериментальная штука, чем Workload manager и статистика.
Ниже про транзакции аналогично. В общем я бы поревьювил это "экспериментальное"

2024-12-27 06:53 UTC, azevaykin commented on ydb/docs/en/core/changelog-server.md
> +* Added delivery of [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) statistics for [columnar tables](./concepts/datamodel/table#column-oriented-tables) to the query analyze
Она выключена фиче флагом и разработка поставлена на паузу.

2024-12-27 07:38 UTC, galnat commented on ydb/docs/en/core/changelog-server.md
> +* Added delivery of [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) statistics for [columnar tables](./concepts/datamodel/table#column-oriented-tables) to the query analyze
@azevaykin Саш, а есть инструкция, как включить фиче флаг для нее? Готовы заявить о ней в этой версии как об экспериментальной?

2024-12-27 07:44 UTC, azevaykin commented on ydb/docs/en/core/changelog-server.md
> +* Added delivery of [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) statistics for [columnar tables](./concepts/datamodel/table#column-oriented-tables) to the query analyze
Недавно обнаружили, что тут явно недоделано. Но у команды сейчас фокус сменился. Поэтому лучше убрать из changelog.

https://github.com/ydb-platform/ydb/blob/4081b1fbb054156672e4c42b96015ff08cec2ac2/ydb/core/tx/columnshard/columnshard__statistics.cpp#L15

2024-12-27 08:04 UTC, pavelvelikhov commented on ydb/docs/en/core/changelog-server.md
> +* Added a [cost-based optimizer](./concepts/optimizer#cost-based-query-optimizer) for complex queries on columnar tables. The cost-based optimizer considers a large number of alternative execution pl
По умолчанию на уровень 2 выставлен: оптимизатор включается на запросах где присутствует хоть одна колоночная таблица
https://ydb.tech/docs/ru/yql/reference/syntax/pragma#costbasedoptimizationlevel

2024-12-27 12:48 UTC, galnat commented on ydb/docs/en/core/changelog-server.md
> +* Added a [cost-based optimizer](./concepts/optimizer#cost-based-query-optimizer) for complex queries on columnar tables. The cost-based optimizer considers a large number of alternative execution pl
Про строковые таблицы решили не писать, для запросов, в которых есть колоночные таблицы, оставили.

2024-12-27 12:49 UTC, galnat commented on ydb/docs/en/core/changelog-server.md
> +* **_(Experimental)_** Added an [auto-partitioning mode](./concepts/topic#autopartitioning) for topics, where partitions can dynamically split based on load while preserving message read-order and ex
Поревьювили с Сергеем, Евгением и Алексеем, обновила.

2024-12-27 13:09 UTC, anton-bobkov commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлено системное представление, позволяющее получить информацию о сессиях, установленных с базой данных, с помошью запроса.
```suggestion
* Добавлено системное представление, позволяющее получить информацию о сессиях, установленных с базой данных, с помощью запроса.
```

2024-12-27 13:12 UTC, anton-bobkov approved these changes, later dismissed

2024-12-27 18:31 UTC, fomichev3000 requested changes

2024-12-27 18:31 UTC, fomichev3000 commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен [стоимостной оптимизатор](./concepts/optimizer#stoimostnoj-optimizator-zaprosov) для сложных запросов, где участвуют [колоночные таблицы](./concepts/glossary#column-oriented-table). Оптими
Давай этот пункт поместим в раздел Экспериментально. Я обсудил с Пучиным

2024-12-27 18:50 UTC, galnat commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен [стоимостной оптимизатор](./concepts/optimizer#stoimostnoj-optimizator-zaprosov) для сложных запросов, где участвуют [колоночные таблицы](./concepts/glossary#column-oriented-table). Оптими
Done

2024-12-27 19:24 UTC, fomichev3000 approved these changes

2024-12-27 19:38 UTC, antonkovalenko approved these changes

2024-12-27 19:38 UTC, merged