JsonDocument support added
ydb-platform/ydb pull request #1306
Opened 2024-01-25 13:46 UTC by aakulaga-ydb

- YQL-15844 fix getting view by symlink (#928)
- Introduce blobsan (#941)
- Fix persqueue ut (#940)
- Allow UPDATE ON, UPSERT with partial set of input... (#894)
- Library import 7 (#937)
- Unsupported database type (DataStreams) by 403 http error (#930)
- Remove TEvColumnShard::TEvRead (#927)
- fix upsert overwriting non-default values (#926)
- fix missed check for usedIndexes. (#947)
- Mute some flaky tests (#949)
- Forgotten OwnerId in EvWrite (#945)
- Tests: Replace EvProposeTransaction with EvWrite (#932)
- Run OnTieringModified only once on tablet initialization (#951)
- add missing backtick (#959)
- TTableId fix (#958)
- Fix for full join when keys for both sides are identical (#948)
- ci: build docker local-ydb docker image using ya make (#934)
- Mute some flaky tests (#962)
- sprintf -> snprintf replacement inside ydb code (#952)
- Create CODEOWNERS (#943)
- make it possible to stop Hive subactors through web ui KIKIMR-20645 (#810)
- Add forgotten file (#969)
- Return --global to git authorship guideline (#963)
- lock for different client versions usage (#961)
- basic statistics bugfixes KIKIMR-18323 (#915)
- cancel previous Build Documentation on the same PR (#967)
- Copy locks in observer & SingleObserver (#973)
- alter table request for metadata modifications (#974)
- added article about goose into docs (#811)
- update roadmap
- Report correct status on overloaded errors in read table KIKIMR-17778 (#946)
- Fixed cardinality estimation bug in CBO (#975)
- cleanup portions store (#971)
- EOperationKind::WriteTx (#976)
- Explicitely restict TCL statements in QueryService. (KIKIMR-16294) (#980)
- usage chunked merge by optional and usage full-batches-merge for norm… (#972)
- Auto stash before merge of "main" and "origin/main" (#985)
- Fix python test style (#867)
- Cancel previous jobs on re-push changes from PR branch (#983)
- Fix a misprint
- Scale screenshot images in goose article (#982)
- Fix StageDurationUs (#984)
- Mute some flaky tests (#994)
- KIKIMR-20714 Удаляем LongTxService в тестах (#970)
- fix test withno appdata (#991)
- Kv tracing ut (#992)
- YQL-17388: fix use-after-free bug in TPgResolvedMultiCall::TListValue::TIterator (#955)
- Mute flaky KqpOlapScheme.TenThousandColumns (#1002)
- enable FieldSubsetEnableMultiusage in experimental config (#1003)
- add colors in cli and fix minor bugs (#1007)
- KIKIMR-20727: Распозновать, как запакован JsonDocument при BulkUpsert (#1008)
- Bugfix: Remove TActiveTransaction from TExecutionUnit.OpsInFly on cancel (#935)
- use iostream instead of printf (#977)
- disable warmup for root hive (#954)
- fix statestorage link (#953)
- Fix WITH statement for INDEX (#1010)
- Create PULL_REQUEST_TEMPLATE.md (#999)
- [docs] Add kafka-api global version (#702)
- Disable coordinator if no ingress tasks (#472)
- Pushdown some unary operators. (#957)
- Mute some flaky tests (#1031)
- add test for describe table store (#1030)
- fix test KIKIMR-20747 (#1020)
- Enable volatile transactions by default KIKIMR-20731 (#993)
- support basic stats for column tables (#1014)
- fix case removed column for stats usage (#1025)
- YQL-17430: Fix dependencies for hybrid (#1021)
- update feature flags for postgres docker (#1040)
- Fix plan tests & improve plan signatures for sources/sinks (#1041)
- rewrite upsert for columns with defaults (#1035)
- Added keyvalue load actor config example (#1045)
- YQ Connector: YQ-2768 fix integration tests (#1028)
- [yql] Don't compare pg-type sort with yt. Enable result check (YQL-17399, YQL-17381) (#1039)
- Set default values for InitialAllocation parameteres (#1012)
- Can read date32 as PostgreSQL date from arrow (#1046)
- Added a link to embedded ui roadmap (#1017)
- remove pdisk -> pg_parser dependency (#1036)
- YQ-2730: use docker-compose random port mapping in connector integration tests (#978)
- YQL-16252, YQL-16623: Support search_path (#788)
- YDB-966 tls incomplete transfer (#1024)
- YDBDOCS-557: add a missing redirect (#592)
- Fix uninitialized value in log settings (#1048)
- [docs] YDBDOCS-98: mention Sentinel in selfheal.md (#434)
- fix double lock (#483)
- [docs] YDBDOCS-230: update primitive types restrictions (#435)
- YDBDOCS-223: add missing backticks to "config.md" (#1072)
- Create pr_labels.yaml (#1033)
- ci: add more details to PR comment about build and tests (#1054)
- Change token in pr_labels.yaml workflow (#1080)
- Revert "Disable coordinator if no ingress tasks (#472)" (#1083)
- More strict DqReplicateType ann. Fix pushing LMap/HasItems to stage (#1057)
- SplitStageOnDqReplicate -> false (#1068)
- Unified test cases naming schema for ydb/library/yql/providers/generic/connector/tests (#1058)
- Safe topic reader KIKIMR-20673 (#1078)
- fix build (#1082)
- fix stats for splitting (#1079)
- Make test actorsystem actor id globaly unique (#1081)
- fix(kqp): pass right table filter through stream index lookup join (#1034)
- test commit (#996)
- KIKIMR-19522 BTreeIndex Iter Remove single run optimization (#995)
- general steps for data fetching (#1088)
- Mute some flaky tests (#1101)
- YQ-2744: add tpc bucket option for ydb workload tpch (#1098)
- Allow partial column set in case of insert (#1056)
- refactor(kqp): remove unused pragmas (#1052)
- YQL-17493: Wrap returned YQL-typed columns with ToPg (#1059)
- add limits for simultaneous compaction (#1096)
- Add block reader over file (#1097)
- Fix possible node crash in case of unavaliable response (#1107)
- Implemented RemoteTopicReader KIKIMR-20306 (#1093)
- Library import 8 (#1074)
- Enchanced VDisk & PDisk traces (#864)
- Fix typo in TPC-DS query (#1125)
- Skip empty description in pr_labels.yaml workflow (#1117)
- YQ-2630: fix and support detalization for v1 (#1016)
- KIKIMR-20009: fix race condition on blobs removing (#1118)
- Add result checking function in arrow_ut.cpp (#1109)
- YDB-2321 Refactor IP UDF to use supported ipmath library (#618)
- Add GLOBAL for udf service files (#1106)
- (refactoring) Move TSchemeCacheHelpers to core/tx/scheme_cache KIKIMR-20673 (#1123)
- YQL-16252, YQL-16623: fix set_config (#1121)
- Report status for static group (#1116)
- KIKIMR-20714: Удаляем LongTxService grpc (#1124)
- fix namings (#1131)
- fix use-after-free in TDummySnapshotContext IGNIETFERRO-2059 (#667)
- [YQL-17474] Expand PartitionByKeys with constant keys via YtMap. Do not fuse ops with JobCount setting (#1122)
- YDB-1060 viewer nodes handler add missing sort (#1134)
- KIKIMR-18397 HC node restarts issue (#1111)
- Fix dates in TPC-DS/YQL-syntax (#1138)
- Add missing includes (#986)
- fix format (#987)
- Fix rebinding allocator (#1023)
- YQL-17553: Fix RPC reader data loss (#1114)
- KIKIMR-19671 Refactoring of IWorkloadQueryGenerator and TWorkloadFactory (#1103)
- YQL-16218 tests dict in tables for sqlin (#1075)
- KIKIMR-20778: Тест на лаг обновления данных через bulk_upsert  (#1143)
- Enable remote cache client decompression (#1141)
- Release notes ydb cli 2 8 0 (#1050)
- Make MVCC always enabled and no longer optional KIKIMR-20802 (#1127)
- Unify test case naming in ydb/library/yql/providers/generic/connector/tests (#1110)
- Improve checkResult fun in arrow_ut.cpp (#1135)
- Accounted for HullHugeBlobChunkAllocator in canondata (#1146)
- (refactoring) IChangeRecord KIKIMR-20673 (#1142)
- S3 storage class workaround for minio (#1148)
- Rename values of ServerlessComputeResourcesMode enum KIKIMR-20642 (#1094)
- fix missing breaks (#1139)
- make storage balancer automatically triggered KIKIMR-20672 (#1018)
- use policies for memory prediction on compaction (#1130)
- YQL-17542 not initially acqured mode in TScopedAlloc (#1099)
- YQ-2356: integration tests for yq through generic provider (#988)
- remove unnecesary sleep in tests (#1092)
- Enable SELECT from views (#795)
- KIKIMR-20378: Enable IAM BulkAuthorization (#911)
- use splitter for abstract data chunks. not columns only (#1147)
- external table content has been decoded for viewer (#1055)
- [YQL-17474] Limit supported operation settings in hybrid execution (#1132)
- F [...]

2024-01-25 14:29 UTC, aakulaga-ydb commented
YQL-17658 fix

2024-01-26 08:27 UTC, rvu1024 requested changes

2024-01-26 08:27 UTC, rvu1024 commented on ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
>          case NUdf::EDataSlot::Utf8:
Надо убрать default из этого switch, что бы компилятор ловил появление новых типов

2024-01-26 08:27 UTC, rvu1024 commented on ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
>          case NUdf::EDataSlot::Utf8:
Зачем одинаковый код по разными case?  `res.IsString = true; break;` можно один раз написать сразу для нескольких типов

2024-01-27 15:56 UTC, aakulaga-ydb commented on ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
>          case NUdf::EDataSlot::Utf8:
Там как раз в момент появления новых типов в default срабатывает проверка.  Типы там динамически передаются в виде списка типов колонок.

2024-01-30 10:43 UTC, rvu1024 approved these changes

2024-01-30 10:44 UTC, merged