Refactoring FillTopicDescription
ydb-platform/ydb pull request #13077
Opened 2024-12-27 10:26 UTC by stanislav-shchetinin

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-12-27 13:08 UTC, CyberROFL requested changes

2024-12-27 13:08 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +   const NKikimrSchemeOp::TPersQueueGroupDescription& in) {
```suggestion
void FillTopicDescription(Ydb::Topic::DescribeTopicResult& out,
    const NKikimrSchemeOp::TPersQueueGroupDescription& in)
{
```

2024-12-27 13:08 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +   const NKikimrSchemeOp::TPersQueueGroupDescription& in) {
Или
```suggestion
void FillTopicDescription(Ydb::Topic::DescribeTopicResult& out, const NKikimrSchemeOp::TPersQueueGroupDescription& in) {
```

2024-12-27 13:08 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
> -        }
Это куда потерялось?

2024-12-27 13:08 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>          if (local || pqConfig.GetTopicsAreFirstClassCitizen()) {
Это почему тут осталось?

2024-12-27 13:08 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>          for (const auto& consumer : config.GetConsumers()) {
Почему это не целиком переехало в функцию, а пришлось делать 2 прохода?

2025-01-10 13:01 UTC, stanislav-shchetinin commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>          if (local || pqConfig.GetTopicsAreFirstClassCitizen()) {
Мне же нужен ActorContext, чтобы получить pqConfig

2025-01-10 13:06 UTC, stanislav-shchetinin commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>          for (const auto& consumer : config.GetConsumers()) {
В первом проходе я заполняю консьюмера, во втором вызываю FillConsumerProto, который зависит от pqConfig

2025-01-10 13:41 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.h
> +    const NKikimrPQ::TPQTabletConfig::TConsumer& in);
Для `NKikimrPQ::TPQTabletConfig::TConsumer` тоже работает forward declaration:
```cpp
namespace NKikimrPQ {
    class TPQTabletConfig_TConsumer;
}
```

2025-01-10 13:41 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +#include <ydb/public/api/protos/ydb_table.pb.h>
```suggestion
#include <ydb/core/protos/flat_scheme_op.pb.h>
#include <ydb/library/persqueue/topic_parser_public/topic_parser.h>
#include <ydb/public/api/protos/ydb_table.pb.h>
```

2025-01-10 13:41 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>      const auto& pqConfig = AppData(ctx)->PQConfig;
Почему содержимое этой функции не целиком переехало в ydb_convert?

2025-01-10 13:41 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
>          if (local || pqConfig.GetTopicsAreFirstClassCitizen()) {
Код конвертации целиком должен переехать. `AppData()->PQConfig` работает и без акторного контекста, а если бы не работало, передал бы его через аргумент.

2025-01-14 18:27 UTC, CyberROFL requested changes

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/ya.make
> +    ydb/public/lib/operation_id/protos
Откуда взялись эти зависимости?

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.h
> +    struct TActorContext;
А на это можно было и не делать, потому что от него зависит чуть ли не весь код YDB. Но раз сделал, пусть остается.

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +bool FillConsumer(Ydb::Topic::Consumer* rr, const NKikimrPQ::TPQTabletConfig::TConsumer& consumer,
Я не очень понимаю, для чего нужна эта перегрузка. Если для `ConvertOldConsumerName(const TString& consumer, const TActorContext& ctx)`, то там рядом есть `ConvertOldConsumerName(const TString& consumer, const NKikimrPQ::TPQConfig& pqConfig)`, а `pqConfig` можно достать из `AppData()->PQConfig`.

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +bool FillConsumer(Ydb::Topic::Consumer *rr, const NKikimrPQ::TPQTabletConfig::TConsumer& consumer,
Оставь только эту функцию без всяких перегрузок.

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +    bool EnableTopicSplitMerge, NYql::TIssue& issue, const TActorContext& ctx, const TString& consumer = "", bool includeStats = false, bool includeLocation = false) {
Можно обойтись без зависимости от `TActorContext`.

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +    const NKikimrPQ::TPQConfig& pqConfig, const NKikimrSchemeOp::TDirEntry &fromDirEntry, const TMaybe<TString>& cdcName,
`const NKikimrPQ::TPQConfig& pqConfig` можно достатать в теле функции из `AppData()`. Зачем передавать его в аргументах?

2025-01-14 18:27 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
> +        }
Почему здесь понадобилась `else` ветка?

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +    bool EnableTopicSplitMerge, NYql::TIssue& issue, const TActorContext& ctx, const TString& consumer = "", bool includeStats = false, bool includeLocation = false) {
`EnableTopicSplitMerge` можно достать из `AppData()`.

2025-01-14 18:27 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.cpp
> +                found = true;
Форматирование поехало.
А вообще, логику про поиск консьюмера необязательно тащить в функцию конвертации, её можно оставить в исходном месте. Тогда функция сильно упростится и `issue` не надо будет в аргументах передавать.

2025-01-15 11:51 UTC, CyberROFL requested changes

2025-01-15 11:51 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.h
> +    struct TActorContext;
Это теперь лишнее.

2025-01-15 11:51 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.h
> +bool FillConsumer(Ydb::Topic::Consumer& rr, const NKikimrPQ::TPQTabletConfig_TConsumer& consumer, Ydb::StatusIds_StatusCode& status, TString& error);
```suggestion
bool FillConsumer(Ydb::Topic::Consumer& out, const NKikimrPQ::TPQTabletConfig_TConsumer& in, Ydb::StatusIds_StatusCode& status, TString& error);
```

Более понятный и консистентный нейминг.

2025-01-15 11:51 UTC, CyberROFL commented on ydb/core/ydb_convert/topic_description.h
> +    Ydb::StatusIds_StatusCode& status, TString& error);
```suggestion
bool FillTopicDescription(Ydb::Topic::DescribeTopicResult& out, const NKikimrSchemeOp::TPersQueueGroupDescription& inDesc,
    const NKikimrSchemeOp::TDirEntry& inDirEntry, const TMaybe<TString>& cdcName,
    Ydb::StatusIds_StatusCode& status, TString& error);
```

2025-01-15 11:51 UTC, CyberROFL commented on ydb/services/persqueue_v1/actors/schema_actors.cpp
> +                found = true;
Тут можно сразу останавливаться. Конвертацию-то уже сделали заранее, а здесь только ищем.

2025-01-15 14:43 UTC, CyberROFL approved these changes

2025-01-15 14:59 UTC, qyryq approved these changes

2025-01-15 16:23 UTC, merged