Parallel local kmeans for construction non-root vector index levels
ydb-platform/ydb pull request #13086
Opened 2024-12-27 12:11 UTC by MBkkt

### Changelog category

* Not for changelog (changelog entry is not required)

### Additional information

TODO

2025-01-13 16:15 UTC, gridnevvvit submitted a review, later dismissed

2025-01-13 16:33 UTC, CyberROFL reviewed
schemeshard — lgtm

2025-01-13 16:33 UTC, CyberROFL approved these changes, later dismissed

2025-01-14 06:54 UTC, azevaykin requested changes

2025-01-14 06:54 UTC, azevaykin commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +    void PersistKMeansState(TTransactionContext& txc, TIndexBuildInfo& buildInfo) {
Нужен тест на прерывание построения индекса и последующее возобновление

2025-01-14 06:54 UTC, azevaykin commented on ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
> +                    WITH (distance=cosine, vector_type="uint8", vector_dimension=2, levels=2, clusters=2);
Минорное: никак не проверить, что именно `levels=2, clusters=2` применились?

2025-01-17 11:51 UTC, MBkkt commented on ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
> +                    WITH (distance=cosine, vector_type="uint8", vector_dimension=2, levels=2, clusters=2);
У нас к сожалению нет нормального доступа к private таблицам.
Это на самом деле в целом неудобно, думаю нужно подумать над тем чтобы такой read-only доступ дать.
Но видимо в отдельном пр

2025-01-17 12:04 UTC, azevaykin commented on ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
> +                    WITH (distance=cosine, vector_type="uint8", vector_dimension=2, levels=2, clusters=2);
Это не то?
https://github.com/ydb-platform/ydb/blob/d132260996759d4c9d46636056476c763bde8fd5/ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp#L638

2025-01-17 12:15 UTC, MBkkt commented on ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
> +                    WITH (distance=cosine, vector_type="uint8", vector_dimension=2, levels=2, clusters=2);
Тут достают партишн таблицы, в нашем случае (мало ключей) это 1 шард

2025-01-17 17:42 UTC, MBkkt commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +    void PersistKMeansState(TTransactionContext& txc, TIndexBuildInfo& buildInfo) {
Добавил

2025-01-20 13:33 UTC, azevaykin approved these changes, later dismissed

2025-01-20 14:15 UTC, CyberROFL commented on ydb/core/tx/schemeshard/ut_index_build_reboots/ya.make
> +    TAG(ya:fat)
1) Тогда можно полность убрать ветвление. 2) LARGE тесты не запускаются прекоммитно.

2025-01-20 14:29 UTC, MBkkt commented on ydb/core/tx/schemeshard/ut_index_build_reboots/ya.make
> +    TAG(ya:fat)
2) А есть идеи как сделать чтобы тест запускался и при этом чтобы успевал проходить?
Локально что-то вроде 20 минут работал если правильно помню

2025-01-20 22:44 UTC, gridnevvvit approved these changes, later dismissed

2025-01-21 05:59 UTC, azevaykin commented on ydb/core/tx/schemeshard/ut_index_build_reboots/ya.make
> +    TAG(ya:fat)
Поддерживаю, было бы здорово уместиться в MEDIUM тест

2025-01-21 12:43 UTC, CyberROFL approved these changes

2025-01-21 20:45 UTC, merged