Publish YDB CLI 2.18.0
ydb-platform/ydb pull request #13104
Opened 2024-12-27 18:21 UTC by asmyasnikov

### Changelog entry 

Publish YDB CLI 2.18.0 with Release Notes

### Changelog category 

* Documentation (changelog entry is not required)

2024-12-28 06:19 UTC, blinkov submitted a review, later dismissed

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +  * Statistics from Column Shards (Rows and Bytes)
```suggestion
* Query plan and statistics provide additional information:
  * Expression and attributes added to various operator properties (e.g., `GroupBy`)
  * Per-operator statistics (Rows)
  * Statistics for [column-oriented tables](./concepts/datamodel/table.md#column-oriented-tables) (Rows and Bytes)
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +  * Statistics from Column Shards (Rows and Bytes)
Clarify what those Rows and Bytes mean. Probably rows processed for operators and rows/bytes read from column shards, but I had to guess that.

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Fixed a bug where `ydb workload * run` command could crash in `--dry-run` mode.
```suggestion
* Fixed a bug where the `ydb workload * run` command could crash in `--dry-run` mode.
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Replaced option `--query-settings` by `--query-prefix` one in `ydb workload <workload> run`.
```suggestion
* Added support for views in local backups: `ydb tools dump` and `ydb tools restore`. Views are backed up as `CREATE VIEW` queries saved in the `create_view.sql` files, which can be executed to recreate the original views.
* Replaced the `--query-settings` option with `--query-prefix` in `ydb workload <workload> run`.
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Added support for views in local backups: `ydb tools dump` and `ydb tools restore`. Views are backed up as `CREATE VIEW` queries saved in the `create_view.sql` files, which can be executed to recre
Was there a PR adding this to the actual documentation for these commands?

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Replaced option `--query-settings` by `--query-prefix` one in `ydb workload <workload> run`.
This needs to be marked as a backward-incompatible change if it doesn't support the old name anymore.

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +Also now you can load test YDB topics, using wide transactions that span over all partitions in the topic. This works both in write and in end-to-end workload scenarios.
```suggestion
* Added new options to `ydb workload topic`: `--tx-commit-interval` and `--tx-commit-messages`, allowing you to specify the commit interval in milliseconds or by the number of messages written.
* Added support for load testing [{{ ydb-short-name }} topics](./concepts/topic.md) using wide transactions that span all partitions in the topic. This works in both write and end-to-end workload scenarios.
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +Also now you can load test YDB topics, using wide transactions that span over all partitions in the topic. This works both in write and in end-to-end workload scenarios.
Needs a link to documentation on how to run this workload.

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Use QueryService by default (`--executer generic`) in `ydb workload kv` and `ydb workload stock` commands
```suggestion
* The `ydb import file csv` command now saves import progress. Relaunching the import command will continue from the row where it was interrupted.
* In the `ydb workload kv` and `ydb workload stock` commands, the default value of the `--executer` option has been changed to `generic`, which makes them no longer rely on the legacy query execution infrastructure.
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Made `--consumer` flag in `ydb topic read` command optional. Now if this flag is not specified, reading is performed in no-consumer mode. In this mode partition IDs should be specified with `--part
```suggestion
* Replaced the CSV format with Parquet for filling tables in `ydb workload` benchmarks.
* Made the `--consumer` flag in the `ydb topic read` command optional. If this flag is not specified, reading is performed in no-consumer mode. In this mode, partition IDs must be specified with the `--partition-ids` option.
```

2024-12-28 06:19 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Added `ydb admin cluster bootstrap` command to bootstrap automatically configured cluster
```suggestion
* Fixed a bug in `ydb import file csv` where multiple columns with escaped quotes in the same row were parsed incorrectly.
* Truncated query results output in benchmarks.
* Added the `ydb admin cluster bootstrap` command to bootstrap an automatically configured cluster.
```

2024-12-28 06:31 UTC, blinkov commented on ydb/docs/en/core/changelog-cli.md
> +* Added `ydb admin cluster bootstrap` command to bootstrap automatically configured cluster
Afaik, this command would work only with a server built from main or 25.1+

2024-12-28 13:23 UTC, galnat commented on ydb/docs/en/core/changelog-cli.md
> +* Added `ydb admin cluster bootstrap` command to bootstrap automatically configured cluster
Саша Рутковский говорит, что должно уже сейчас работать.

2024-12-28 14:38 UTC, anton-bobkov approved these changes, later dismissed

2024-12-28 17:08 UTC, fomichev3000 requested changes

2024-12-28 17:08 UTC, fomichev3000 commented on ydb/docs/ru/core/changelog-cli.md
> +* Добавлена команда `ydb admin cluster bootstrap` для автоматической первоначальной настройки кластера.
Она не работает. Я бы исключил...

2024-12-28 17:33 UTC, galnat commented on ydb/docs/ru/core/changelog-cli.md
> +* Добавлена команда `ydb admin cluster bootstrap` для автоматической первоначальной настройки кластера.
Убрала

2024-12-28 17:35 UTC, fomichev3000 approved these changes

2024-12-29 10:26 UTC, pnv1 approved these changes

2024-12-29 10:26 UTC, merged