Audit log for ModifyScheme::ESchemeOpAlterLogin
ydb-platform/ydb pull request #13108
Opened 2024-12-28 08:55 UTC by andrewstalin

### Changelog entry

An entry in the audit log is generated in a special operation

### Changelog category

* Not for changelog (changelog entry is not required)

### Additional information

2025-01-13 08:26 UTC, azevaykin commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_login.cpp
> +            AuditLogModifySchemeTransaction(Transaction, result->Record, context.SS, context.PeerName, userSID, sanitizedToken, ui64(txId), additionalParts);
Раньше такого события аудита в данном месте не было. 
Тест будет?

2025-01-13 10:33 UTC, andrewstalin commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_login.cpp
> +            AuditLogModifySchemeTransaction(Transaction, result->Record, context.SS, context.PeerName, userSID, sanitizedToken, ui64(txId), additionalParts);
На это есть уже тест. Я просто перенес запись из https://github.com/ydb-platform/ydb/blob/main/ydb/core/tx/schemeshard/schemeshard__operation.cpp#L447 в https://github.com/ydb-platform/ydb/blob/main/ydb/core/tx/schemeshard/schemeshard__operation.cpp#L117

2025-01-14 06:22 UTC, azevaykin submitted a review, later dismissed

2025-01-17 19:39 UTC, ijon requested changes

2025-01-17 19:39 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_audit_log.h
> +#include <ydb/core/protos/flat_tx_scheme.pb.h>
`NKikimrScheme::EStatus` could be forward declared as:
```c++
namespace NKikimrScheme {
enum EStatus : int;
}

2025-01-20 08:27 UTC, ijon approved these changes

2025-01-20 08:53 UTC, merged