[YQ-1997] OR REPLACE grammar support for EXTERNAL DATA SOURCE and EXTERNAL TABLE
ydb-platform/ydb pull request #1318
Opened 2024-01-25 15:37 UTC by Alnen

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-29 10:02 UTC, UgnineSirdis requested changes

2024-01-29 10:02 UTC, UgnineSirdis commented on ydb/core/kqp/gateway/utils/scheme_helpers.cpp
> +                                       bool isReplace,
`replaceIfExists`

2024-01-29 15:20 UTC, UgnineSirdis requested changes

2024-01-29 15:20 UTC, UgnineSirdis commented on ydb/core/protos/flat_scheme_op.proto
> +    optional bool ReplaceIfExists = 9;
This field has no sense for describe operation. It's worth to write comment about it.

2024-01-29 15:20 UTC, UgnineSirdis commented on ydb/library/yql/sql/v1/format/sql_format.cpp
> +        Visit(msg.GetBlock4());
We need to add tests for this new behaviour to `ydb/library/yql/sql/v1/format/sql_format_ut.cpp`

2024-01-29 15:21 UTC, Alnen commented on ydb/services/metadata/abstract/parsing.h
> +Y_HAS_MEMBER(IsReplace); // for create
Fixed

2024-01-29 15:21 UTC, Alnen commented on ydb/library/yql/sql/v1/node.h
> +        bool existingOk, bool isReplace, std::map<TString, TDeferredAtom>&& features, const TObjectOperatorContext& context);
Fixed

2024-01-29 15:21 UTC, Alnen commented on ydb/library/yql/sql/v1/object_processing.h
> +    bool IsReplace = false;
Fixed

2024-01-29 15:23 UTC, Alnen commented on ydb/library/yql/sql/v1/query.cpp
> +    const bool IsReplace;
Fix

2024-01-29 15:23 UTC, Alnen commented on ydb/library/yql/sql/v1/query.cpp
> +TNodePtr BuildCreateTable(TPosition pos, const TTableRef& tr, bool existingOk, bool isReplace, const TCreateTableParameters& params, TScopedStatePtr scoped)
Fix

2024-01-29 15:23 UTC, Alnen commented on ydb/library/yql/sql/v1/query.cpp
> +    bool existingOk, bool isReplace, std::map<TString, TDeferredAtom>&& features, const TObjectOperatorContext& context) {
Fixed

2024-01-29 15:23 UTC, Alnen commented on ydb/library/yql/sql/v1/source.h
> +    TNodePtr BuildCreateTable(TPosition pos, const TTableRef& tr, bool existingOk, bool isReplace, const TCreateTableParameters& params, TScopedStatePtr scoped);
Fixed

2024-01-29 15:24 UTC, Alnen commented on ydb/library/yql/sql/v1/sql_query.cpp
> +            bool isReplace = false;
Fixed

2024-01-29 15:24 UTC, Alnen commented on ydb/library/yql/sql/v1/sql_query.cpp
> +            bool isReplace = false;
Fixed

2024-01-29 15:25 UTC, Alnen commented on ydb/core/kqp/provider/yql_kikimr_gateway.h
> +    virtual NThreading::TFuture<TGenericResult> CreateTable(TKikimrTableMetadataPtr metadata, bool createDir, bool existingOk = false, bool isReplace = false) = 0;
Fixed

2024-01-29 15:25 UTC, Alnen commented on ydb/core/kqp/provider/yql_kikimr_expr_nodes.json
> +                {"Index": 14, "Name": "IsReplace", "Type":  "TCoAtom"}
Fixed

2024-01-29 15:25 UTC, Alnen commented on ydb/core/kqp/provider/yql_kikimr_exec.cpp
> +            bool isReplace = (maybeCreate.IsReplace().Cast().Value() == "1");
Fixed

2024-01-29 15:25 UTC, Alnen commented on ydb/core/kqp/provider/yql_kikimr_datasink.cpp
> +                    auto isReplace = (settings.Mode.Cast().Value() == "create_or_replace");
Fixed

2024-01-29 15:25 UTC, Alnen commented on ydb/core/kqp/host/kqp_gateway_proxy.cpp
> +    TFuture<TGenericResult> CreateTable(TKikimrTableMetadataPtr metadata, bool createDir, bool existingOk, bool isReplace) override {
Fixed

2024-01-29 15:39 UTC, nepal requested changes

2024-01-29 15:39 UTC, nepal commented on ydb/library/yql/sql/v1/sql_query.cpp
> +                Context().Error(GetPos(rule.GetBlock2().GetToken1()))
Please add test for this in sql_ut.cpp

2024-01-30 09:44 UTC, UgnineSirdis approved these changes

2024-01-30 09:59 UTC, nepal approved these changes
sql part lgtm

2024-01-30 11:32 UTC, merged