Table partition writer skeleton KIKIMR-20673
ydb-platform/ydb pull request #1322
Opened 2024-01-25 16:42 UTC by CyberROFL

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-25 18:53 UTC, Enjection requested changes

2024-01-25 18:53 UTC, Enjection commented on ydb/core/tx/replication/service/json_change_record.cpp
> +}
Almost the same code with different semantics. In the first case we overwrite cells vector in the second case we append. It's confusing.

2024-01-25 21:36 UTC, CyberROFL commented on ydb/core/tx/replication/service/json_change_record.cpp
> +}
В первом случае мы итерируемся по индексам: по компонентам ключа, по типам ключевых столбцов и, для единообразия, по ячейкам.

А во втором индексов нет, итерируемся по словарю.

2024-01-26 09:25 UTC, Enjection approved these changes

2024-01-26 09:33 UTC, merged