add_terraform_description_for_ydb
ydb-platform/ydb pull request #1328
Opened 2024-01-25 22:15 UTC by sourcecd

* Add terraform description for ydb resources

2024-02-12 06:52 UTC, blinkov requested changes

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +С помощью Terraform можно создавать, удалять и изменять следующие объекты {{ ydb-short-name }}:
```suggestion
С помощью [Terraform](https://www.terraform.io/) можно создавать, удалять и изменять следующие объекты внутри кластера {{ ydb-short-name }}:
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +На данный момент провайдер находится на стадии разработки и его функциональность будет расширяться
```suggestion
На данный момент {{ ydb-short-name }} провайдер для Terraform находится на стадии разработки и его функциональность будет расширяться.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +{% note info %}
```suggestion
{% note warning %}
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Чтобы начать работать с Terraform для {{ ydb-short-name }}, установите и настройте [Terraform provider for {{ ydb-short-name }}](https://github.com/ydb-platform/terraform-provider-ydb/).
и сам Terraform видимо тоже нужно заранее установить? дать ссылку на инструкцию

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +{% note warning %}
Плюс в том пункте, где будет про развёртывание БД, можно сказать, что если вы развернули БД в Yandex Cloud, то аналогичная функциональность доступна и в terraform провайдере самого Yandex Cloud, со ссылкой куда-то в район https://cloud.yandex.ru/ru/docs/ydb/terraform/intro

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +      token = ""
видимо этот токен предполагается заполнить — объяснить где именно его брать в зависимости от способа установки кластера

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +### Соединение с БД {#connection_string}
```suggestion
### Соединение с базой данных (БД) {#connection_string}
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `token` - указывается токен доступа к БД, если он необходим.
Его же выше в провайдере указывали? его надо переопределять или как?

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - алиас к первому пункту `connection_string` используется при создании/изменении топиков.
не понятно при чём тут топики

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Если на сервере {{ ydb-short-name }} не включена авторизация, то в конфиге БД [config.yaml](../deploy/configuration/config.md) нужно указать:
какой-то мелкий нюанс во вводной части, в идеале переделать бы сам код, чтобы так не надо было делать

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +    connection_string = "grpc(s)://HOST:PORT/?database=/database/path" # в примерах ниже мы поместим в переменную tf
что в данном контексте означает «поместим в переменную»?

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +    path = "path/to/table"
не понятно нужен ли тут полный путь или относительно корня database

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `connection_string` — строка соединения.
явно написать откуда берётся, если не указана

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `column` — (обязательный) свойства колонки (см. аргумент [column](#column)).
точно ли «аргумент» является тут правильным термином? больше похоже на ресурс или объект

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `primary_key` — (обязательный) [первичный ключ](../yql/reference/syntax/create_table.md#columns) таблицы, содержит список колонок первичного ключа.
```suggestion
* `primary_key` — (обязательный) [первичный ключ](../yql/reference/syntax/create_table.md#columns) таблицы, содержит упорядоченный список имён колонок первичного ключа.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `attributes` — (необязательный) атрибуты таблицы.
нет примера что в них писать + какой-то доки по атрибутам в целом

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `key_bloom_filter` — (необязательный) (true|false) использовать [фильтра Блума для первичного ключа](../concepts/datamodel/table.md#bloom-filter).
написать true или false по умолчанию

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки.
как указывать нетривиальные типы вроде контейнеров или decimal?

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `family` — (необязательный) свойства группы колонок (см. аргумент [family](#family)).
наверное не свойства, а её имя?

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_size_enabled` — (необязательный) включение автопартиционирования по размеру (bool), по умолчанию - включено.
неконсистентно описаны такие настройки, выше оно называлось true или false, и значение по умолчанию тоже по-другому обозначалось

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_load` — (необязательный) включение [автопартицирования по нагрузке](../concepts/datamodel/table.md#auto_partitioning_by_load).
не написано что по умолчанию

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Изменение TTL производится через удаление и последующее создание.
типа дважды terraform apply надо делать? или что имеется ввиду?

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `unit` — (необязательный) задается в случае, если колонка с ttl имеет числовой тип. Поддерживаемые значения:
надо где-то написать какой вообще ассортимент типов данных колонок поддерживается и для каких этот unit нужен, а для каких — нет

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Для работы с индексом таблицы используется ресурс `ydb_table_index`.
досыпать ссылку на доку по вторичным индексам

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) тип индекса [global_sync | global_async](../yql/reference/syntax/create_table#secondary_index).
```suggestion
* `type` — (обязательный) тип индекса [global_sync | global_async](../yql/reference/syntax/create_table.md#secondary_index).
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `columns` — (обязательный) колонки в индексе.
```suggestion
* `columns` — (обязательный) упорядоченный список имён колонок, участвующий в индексе.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `cover` — (обязательный) колонки для покрывающего индекса.
```suggestion
* `cover` — (обязательный) список дополнительных колонок для покрывающего индекса.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Аргумент `consumer` описывает [читателя](../best_practices/cdc#read) потока изменений.
```suggestion
Аргумент `consumer` описывает [читателя](../best_practices/cdc.md#read) потока изменений.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `starting_message_timestamp_ms` — (необязательный) временная метка в формате [UNIX timestamp](https://ru.wikipedia.org/wiki/Unix-время), с которой читатель начнет читать данные.
unix timestamp чаще в секундах, а в названии настройки суффикс, намекающий на миллисекунды — явно написать какая единица измерения ожидается

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +  token = ""
странно, что token и connection string не рядом задаются — вряд ли один токен когда-либо сможет подходить разным кластерам

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +  token = ""
как указывать логин-пароль, если на кластере такая аутентификация, а не по токенам? (выглядит самым ходовым сценарием для open-source кластера)

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `read_replicas_settings` — (необязательный) настройки [репликации](../concepts/datamodel/table.md#read_only_replicas).
```suggestion
* `read_replicas_settings` — (необязательный) настройки [реплик для чтения](../concepts/datamodel/table.md#read_only_replicas).
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Описание [топиков](../concepts/topic.md)
Для работы с [топиками](../concepts/topic.md) используется ресурс `ydb_topic`.

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Топик не может быть создан в корне БД, нужно указать хотя бы один каталог в имени топика.
```suggestion
{% note info %}

Топик не может быть создан в корне БД, нужно указать хотя бы один каталог в имени топика.

{% endnote %}
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Топик не может быть создан в корне БД, нужно указать хотя бы один каталог в имени топика.
что произойдёт, если таки попытаться создать топик в корне? написать об этом

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `retention_period_ms` - время хранения данных, значение по умолчанию - `86400000` миллисекунд.
```suggestion
* `retention_period_ms` - длительность хранения данных в миллисекундах, значение по умолчанию - `86400000` (сутки).
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `supported_codecs` - поддерживаемые кодировки сжатия данных, значение по умолчанию - `"gzip", "raw", "zstd"` (всего 3 типа кодеков).
```suggestion
* `supported_codecs` - поддерживаемые кодеки сжатия данных, значение по умолчанию - `"gzip", "raw", "zstd"`.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `supported_codecs` - поддерживаемые кодировки сжатия данных, по умолчанию - `"gzip", "raw", "zstd"` (всего 3 типа кодеков).
```suggestion
* `supported_codecs` - поддерживаемые кодировки сжатия данных, по умолчанию - `"gzip", "raw", "zstd"`.
```

2024-02-12 06:52 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `starting_message_timestamp_ms` - временная метка в формате UNIX timestamp, с которой читатель начнёт читать данные, по умаолчанию - 0, то есть с начала поставки.
см. выше

2024-02-14 12:34 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +Чтобы начать работать с Terraform для {{ ydb-short-name }}, установите и настройте [Terraform provider for {{ ydb-short-name }}](https://github.com/ydb-platform/terraform-provider-ydb/).
fixed

2024-02-14 12:37 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +Топик не может быть создан в корне БД, нужно указать хотя бы один каталог в имени топика.
будет ошибка

2024-02-14 13:58 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +{% note warning %}
fixed...

2024-02-14 16:15 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +Если на сервере {{ ydb-short-name }} не включена авторизация, то в конфиге БД [config.yaml](../deploy/configuration/config.md) нужно указать:
завел тикет на авторов

2024-02-26 15:15 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +      token = ""
описал

2024-02-26 15:29 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +    path = "path/to/table"
добавил коментарий

2024-02-26 15:30 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +  token = ""
добавил в код провайдера поддержку статик кредов

2024-02-26 15:32 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +  token = ""
как это, я со своим токеном хожу в разные кластеры прода, ребята заводят таблицы в зональных базах с одним и тем же токеном iam, iam обычно един. (как пример)

2024-02-26 15:34 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +  token = ""
да и просто connection string может к разным базам в кластере применяться

2024-02-26 15:50 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `unit` — (необязательный) задается в случае, если колонка с ttl имеет числовой тип. Поддерживаемые значения:
добавил ссылку на числовые типы

2024-02-26 15:59 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `column` — (обязательный) свойства колонки (см. аргумент [column](#column)).
кажется норм, https://developer.hashicorp.com/terraform/language/resources/syntax#resource-arguments - аргументы ресурса

2024-02-27 11:19 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +Изменение TTL производится через удаление и последующее создание.
убрал это, только вводит в заблуждение

2024-02-27 11:20 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - алиас к первому пункту `connection_string` используется при создании/изменении топиков.
у топиков по другому исторически называется ednpoint - database_endpoint

2024-02-27 13:18 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `family` — (необязательный) свойства группы колонок (см. аргумент [family](#family)).
done

2024-02-27 13:21 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_load` — (необязательный) включение [автопартицирования по нагрузке](../concepts/datamodel/table.md#auto_partitioning_by_load).
умолчания есть в ссылках

2024-02-27 13:25 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_size_enabled` — (необязательный) включение автопартиционирования по размеру (bool), по умолчанию - включено.
не понял, про что именно речь

2024-02-27 14:24 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_load` — (необязательный) включение [автопартицирования по нагрузке](../concepts/datamodel/table.md#auto_partitioning_by_load).
дописал

2024-02-27 14:54 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `key_bloom_filter` — (необязательный) (true|false) использовать [фильтра Блума для первичного ключа](../concepts/datamodel/table.md#bloom-filter).
fixed

2024-02-27 15:01 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `auto_partitioning_by_size_enabled` — (необязательный) включение автопартиционирования по размеру (bool), по умолчанию - включено.
добавил больше деталей

2024-02-27 15:10 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `token` - указывается токен доступа к БД, если он необходим.
fixed

2024-02-27 16:58 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `attributes` — (необязательный) атрибуты таблицы.
убрал, это случайно попало, это для cli и sdk

2024-02-27 17:45 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - алиас к первому пункту `connection_string` используется при создании/изменении топиков.
подправил немного это место

2024-02-27 17:46 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +    connection_string = "grpc(s)://HOST:PORT/?database=/database/path" # в примерах ниже мы поместим в переменную tf
убрал, это сбивает с толку, сделал отдельную note info

2024-02-27 17:47 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `connection_string` — строка соединения.
подправил

2024-02-27 17:54 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки.
на вход принимается string и передается в YQL exec, если yql поддерживает тип, то он применится.

2024-02-27 18:03 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки.
но про конейнерные типы сразу написано в документации, что они не могут быть типами колонок

2024-02-27 18:04 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки.
decimal есть же в описании по ссылке

2024-02-27 18:09 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки.
чуть больше информации добавил

2024-03-06 04:29 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +2. Создать БД (описано в п.1 для соответствующего типа развертывания кластера)
```suggestion
2. Создать базу данных (описано в п.1 для соответствующего типа развертывания кластера)
```

2024-03-06 04:31 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +      path    = "/PATH_TO_HOME/.terraform.d/plugins"
а `~`, `$HOME` или относительный путь тут точно нельзя, чтоб ничего не надо было руками заменять?

2024-03-06 04:32 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +3. Настроить `~/.terraformrc`, добавив в секцию `provider_installation` (если такая секция уже есть, то в текущую) следующее содержание:
```suggestion
3. Добавить провайдер в `~/.terraformrc`, дописав в секцию `provider_installation` следующее содержание (если такой секции ещё не было, то создать):
```

2024-03-06 04:33 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +    ```tf
вероятно стоит вокруг добавить саму секцию provider_installation, чтоб можно было скопипастить целиком, если её ещё нет

2024-03-06 04:34 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +4. Далее настраиваем сам {{ ydb-short-name }} провайдер для работы:
не написано куда это дописывать, тоже в `~/.terraformrc`?

2024-03-06 04:35 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - используется при работе с ресурсом [топиков](#topic_resource) (аналог `connection_string` при работе с ресурсами таблиц).
может ещё не поздно сделать консистентное название?

2024-03-06 04:36 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +Если требуется, пользователь может передавать строку соединения с БД стандартными средствами Terraform - через variables
```suggestion
Если требуется, пользователь может передавать строку соединения с БД стандартными средствами Terraform - через [variables](https://developer.hashicorp.com/terraform/language/values/variables).
```

2024-03-06 04:37 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +если вы используете создание ресурсов `ydb_table_changefeed` или `ydb_topic`.
```suggestion
Если вы используете создание ресурсов `ydb_table_changefeed` или `ydb_topic` и на сервере {{ ydb-short-name }} не включена авторизация, то в конфиге БД [config.yaml](../deploy/configuration/config.md) нужно указать:

```yaml
...
pqconfig:
  require_credentials_in_new_protocol: false
  check_acl: false
```

если .
```

2024-03-06 04:38 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +### Построчная таблица (поколоночные пока не доступны) {#ydb-table}
```suggestion
### Построчная таблица {#ydb-table}

{% note info %}

Работа с поколоночными таблицами через Terraform пока не доступна.

{% endnote %}

```

2024-03-06 04:39 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +  Подробнее про параметры и их значения по умолчанию написано по ссылкам выше.
```suggestion
Подробнее про параметры и их значения по умолчанию написано по ссылкам выше.
```

2024-03-06 04:40 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `expire_interval` — (обязательный) интервал в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601) (например P1D продолжительность длиной 1 сутки (24 часа)).
```suggestion
* `expire_interval` — (обязательный) интервал в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601) (например, `P1D` — интервал длиной в 1 сутки, то есть 24 часа).
```

2024-03-06 04:41 UTC, blinkov commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - (обязательный) полный путь до базы данных, например: `"grpcs://example.com:2135/?database=/Root/testdb0"` аналог `connection_string` для таблиц.
```suggestion
* `database_endpoint` - (обязательный) полный путь до базы данных, например: `"grpcs://example.com:2135/?database=/Root/testdb0"`; аналог `connection_string` для таблиц.
```

2024-03-06 12:54 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +* `database_endpoint` - используется при работе с ресурсом [топиков](#topic_resource) (аналог `connection_string` при работе с ресурсами таблиц).
К сожалению, эти названия уже используются пользовтелями, а сделать миграцию в наших уловиях не представляется возможным

2024-03-06 13:58 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +      path    = "/PATH_TO_HOME/.terraform.d/plugins"
К сожалению, терраформ в этом месте не умеет раскрывать переменные, принимает только абсолютный путь.

2024-03-06 15:09 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +4. Далее настраиваем сам {{ ydb-short-name }} провайдер для работы:
дописал

2024-03-06 15:09 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +    ```tf
ага, поправил.

2024-03-07 06:28 UTC, fomichev3000 requested changes

2024-03-07 06:28 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +### Построчная таблица {#ydb-table}
"Построчная" -> "Строковая"
"Поколоночная" -> "Колоночная"

2024-03-07 06:28 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +2. Собрать провайдер, выполнив `make local-build`
Что-то куцая секция. Вообще надо явно оформить команду отдельной строкой, чтобы ее скопировать можно было. Написать, что вам нужен make, go и еще что-нибудь )

2024-03-07 06:28 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +## Использование Terraform провайдера {{ ydb-short-name }} {#work-with-tf}
Вообще в статье не хватает глобального примера запуска TF, чтобы все получилось

2024-03-07 13:02 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +## Использование Terraform провайдера {{ ydb-short-name }} {#work-with-tf}
что имеется ввиду, какой-то tf файл в который максимально свалено всех ресурсов для демонстрации?

2024-03-07 13:42 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +## Использование Terraform провайдера {{ ydb-short-name }} {#work-with-tf}
> что имеется ввиду, какой-то tf файл в который максимально свалено всех ресурсов для демонстрации?

что имеется ввиду, какой-то tf файл в который максимально свалено всех ресурсов для демонстрации?

2024-03-07 13:43 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +## Использование Terraform провайдера {{ ydb-short-name }} {#work-with-tf}
> Вообще в статье не хватает глобального примера запуска TF, чтобы все получилось

что имеется ввиду, какой-то tf файл в который максимально свалено всех ресурсов для демонстрации?

2024-03-11 10:15 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +## Использование Terraform провайдера {{ ydb-short-name }} {#work-with-tf}
да. Чтобы можно было пройтись по нему и получить финальный результат, например, создана таблица с индексом

2024-03-24 20:58 UTC, fomichev3000 approved these changes
Давай я ОКну merge, а то я затянул, но я написал две прямо проблемы-проблемы, которые надо поправить. Можно отдельным коммитом.

2024-03-24 20:58 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +  table_path        = ydb_table.table.path
Выглядит так, что это не работающий пример. Я бы предложил сделать его работающим, чтобы можно было сделать copy/paste.

Дополнительно я бы прямо скрипт написал в духе
$ terraform init
$ terraform validate
$ terraform apply

И еще я бы написал как назвать файл, например main.tf. Сорри, я не специалист по tf, пришлось изучать сторонние источники, но у меня получилось

2024-03-24 20:58 UTC, fomichev3000 commented on ydb/docs/ru/core/db/terraform.md
> +# Управление {{ ydb-short-name }} с помощью Terraform
Я попробовал воспользоваться tf, и удивительно наступил на следующую проблему. Я создавал таблицу и индекс. После первого apply я получил ошибку создания индекса. Второй запуск оказался успешным, хотя файл я не менял.

Мой main.tf
https://paste.yandex-team.ru/284d7433-5f1f-4d8a-b188-8e3cfbe4687b

Лог запуска
https://paste.yandex-team.ru/c46ae419-4bfd-4829-a12b-9ecba5e002a5

2024-03-24 23:29 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +  table_path        = ydb_table.table.path
Ок, допишу. Думалось, что пользователь умеет обращаться с тераформом и описывать, как им пользоваться не должно входить в эту инструкцию.

2024-03-25 10:49 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +# Управление {{ ydb-short-name }} с помощью Terraform
Я посмотрел, выглядит, как баг в ydb, заведу тикет

2024-03-25 11:01 UTC, blinkov approved these changes

2024-03-25 11:01 UTC, merged

2024-03-25 11:25 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +# Управление {{ ydb-short-name }} с помощью Terraform
Хотя нет, не баг, дело в следующем:

при создании индекса нужно или ссылаться на ресурс создания таблицы:
%%
...
resource "ydb_table_index" "table_index" {
  table_path        = ydb_table.table.path #- вот так
  connection_string = var.db-connect
  name              = "my_index"
  type              = "global_sync"
  columns           = ["a", "b"]

  depends_on = [ydb_table.table]
}
%%

Или можно явно поставить депенденс:

%%
resource "ydb_table_index" "table_index" {
  table_path        = "terraform/table"
  connection_string = var.db-connect
  name              = "my_index"
  type              = "global_sync"
  columns           = ["a", "b"]

  depends_on = [ydb_table.table] #- вот так
}
%%

2024-03-25 13:15 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +# Управление {{ ydb-short-name }} с помощью Terraform
дополнил в новом pr

2024-03-25 13:15 UTC, sourcecd commented on ydb/docs/ru/core/db/terraform.md
> +  table_path        = ydb_table.table.path
дополнил в новом pr