Tracing documentation
ydb-platform/ydb pull request #1331
Opened 2024-01-26 08:27 UTC by domwst

### Changelog entry 

Tracing documentation

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-01-29 05:36 UTC, blinkov commented on ydb/docs/ru/core/administration/tracing/external-traces.md
> +    {% endnote %}
```suggestion
{% note warning %}

Для каждого типа запросов соответствующий контроллер в Immediate Control Board ноды появляется только после того, как к ноде был сделан запрос этого типа через gRPC.

 {% endnote %}
```

2024-02-19 06:48 UTC, fomichev3000 requested changes

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Для настройки трейсинга добавьте в конфигурацию (`cluster.yaml`) следующую секцию:
Это первый и единственный раздел про трассировку YDB. Я бы добавил вступление про трассировку вообще.
* предпложение зачем нужна трассировка
* ссылка на то, где с трассировкой можно подробнее ознкомиться (внешний ресурс)
* мы поддерживаем open tracing? написать про это

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +      collector_url: grpc://collector.ru:4317
collector.ru -- это странно. Примеры ИМХО принято приводить с example.com

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +      max_burst: 2
вообще начало странно выглядит. Огромный пример, неужели его весь надо добавлять? Я бы сформулировал минимальный конфиг

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Uploader – локальный для узла компонент, как следствие, описанные ограничения применяются к каждому узлу отдельно, а не ко всему кластеру вцелом.
"в целом"

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +### External throttling
Не сказано, является ли секция обязательной. Если не обязательна, то какое поведение по умолчанию? Могу я вообще выключить external throttling.

Как в open telemetry называется "external throttling"?

2024-02-19 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Данная секция контролирует сэмплирование запросов в формате аналогичном `external_throttling`, каждое правило имеет два дополнительные поля:
аналогичном -- обычно ссылка на секцию ставится

2024-02-28 08:20 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Для настройки трейсинга добавьте в конфигурацию (`cluster.yaml`) следующую секцию:
* Написал небольшое введение про трассировку
* Добавил ссылку на соответствующий раздел opentelemetry
* В следующей секции про минимальную настройку написал, что коллектор должен быть OTEL-совместимым

2024-02-28 08:20 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +      collector_url: grpc://collector.ru:4317
Заменил на example.com

2024-02-28 08:21 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Uploader – локальный для узла компонент, как следствие, описанные ограничения применяются к каждому узлу отдельно, а не ко всему кластеру вцелом.
Исправил

2024-02-28 08:21 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Данная секция контролирует сэмплирование запросов в формате аналогичном `external_throttling`, каждое правило имеет два дополнительные поля:
Добавил

2024-02-28 08:21 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +      max_burst: 2
Добавил в начало секцию "минимальная конфигурация"

2024-02-28 08:24 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +### External throttling
Описал поведение по умолчанию. В open telemetry нет такого понятия, как throttling – только sampling

2024-03-01 08:30 UTC, fomichev3000 requested changes

2024-03-01 08:30 UTC, fomichev3000 commented on ydb/docs/ru/core/administration/tracing/external-traces.md
> +# Передача внешнего trace-id в {{ ydb-short-name }}
Не понятно из этого документа, мы трассируем любой внеший trace id? Как-то ограниченно?
На мой взгляд странно видеть в документации про трейсинг 2 статьи, одну общую, вторую про внешний трейсинг... Как-то не очень логично для меня... 
И очень странно, что про внешний трейсинг в одной статье, а про его настройку в другой... не логично же

2024-03-05 06:27 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/external-traces.md
> +# Передача внешнего trace-id в {{ ydb-short-name }}
Логика тут такая: первая статья описывает трассировку с точки зрения администратора, вторая описывает трассировку с точки зрения разработчика. Наверное стоит тут сделать отсылку к ограничениям на внешние трассы и написать

2024-03-06 10:44 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Больше про трассировку вы можете прочитать в разделе [observability primer](https://opentelemetry.io/docs/concepts/observability-primer/) сайта opentelemetry.
Перенес этот абзац в заметку в начало статьи

2024-03-06 10:44 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +При данной насиройке никакие запросы не сэмплируются, все запросы с [внешним trace-id](./external-traces.md) трассируются.
Исправил, спасибо

2024-03-06 10:45 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +Пример более детальной настройки приведен ниже:
Добавил в соответствующие секции краткое описание

2024-03-06 10:45 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/setup.md
> +При отсутсвии секции `external_throttling`, все запросы с внешним trace-id будут трассироваться.
Спасибо, исправил

2024-03-06 10:46 UTC, domwst commented on ydb/docs/ru/core/administration/tracing/external-traces.md
> +# Передача внешнего trace-id в {{ ydb-short-name }}
Добавил в статью про передачу trace-id примечание о том, что могут трассироваться не все запросы

2024-04-04 06:46 UTC, fomichev3000 approved these changes

2024-04-04 06:51 UTC, merged