resolves #1346
ydb-platform/ydb pull request #1347
Opened 2024-01-26 13:20 UTC by qrort

### Changelog entry 

Add stripped version of yql/tools/mrrun to opensource repo

### Changelog category 

* Not for changelog (changelog entry is not required)

2024-01-26 13:41 UTC, qrort commented
There are failed tests in the ones I added, but they fail in the private repo as well. Maybe we need to just remove them idk

2024-01-26 14:35 UTC, rvu1024 requested changes
Не увидел тут точки расширения downloaders

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/clone_operation.py
Это не нужно. Я-специфика

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/build.cmd
Не нужно и не актуально

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/gateways.conf
Конфиг не нужно сюда коммитить. Тут много внутренней специфики и вообще у нас отдельная папка для конфигов

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/query.sql
это не надо коммитить

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/mrrun.cpp
> +        TString(StatProviderName),
это выпилить

2024-01-26 14:35 UTC, rvu1024 commented on ydb/library/yql/tools/mrrun/fs.conf
Не нужно коммитить. Для конфигов отдельная папка

2024-01-29 10:25 UTC, qrort commented on ydb/library/yql/tools/mrrun/mrrun.cpp
> +        TString(StatProviderName),
Убрал все, связанное с provider_load. ClusterMapping оставил

2024-01-29 13:42 UTC, rvu1024 approved these changes

2024-01-29 13:50 UTC, merged