Manage releases docs
ydb-platform/ydb pull request #1351
Opened 2024-01-26 15:34 UTC by alexv-smirnov

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-26 18:04 UTC, shmel1k submitted a review, later dismissed

2024-01-28 16:37 UTC, mvgorbunov approved these changes, later dismissed

2024-01-30 14:59 UTC, fomichev3000 requested changes

2024-01-30 14:59 UTC, fomichev3000 commented on ydb/docs/ru/core/development/manage-releases.md
> +На базе исходного коде из репозитория YDB разрабатываются два продукта с независимыми релизными циклами:
коде -> кода

2024-01-30 14:59 UTC, fomichev3000 commented on ydb/docs/ru/core/development/manage-releases.md
> +- [Интерфейс командной строки YDB (CLI)](#cli)
еще dstool

2024-01-30 14:59 UTC, fomichev3000 commented on ydb/docs/ru/core/development/manage-releases.md
> +Расписание релизов сервера YDB включает в себя 4 мажорных релиза ежегодно, поэтому релиз `YY.1` является первым, а `YY.4` - последним в году `YY`. Количество минорных релизов не является постоянным и
Я бы написал, что "приблизительно" 4 релиза в год. Не MUST

2024-01-30 14:59 UTC, fomichev3000 commented on ydb/docs/ru/core/development/manage-releases.md
> +Расписание релизов сервера YDB включает в себя 4 мажорных релиза ежегодно, поэтому релиз `YY.1` является первым, а `YY.4` - последним в году `YY`. Количество минорных релизов не является постоянным и
одного мажорного -> одного года

2024-01-31 12:09 UTC, alexv-smirnov commented on ydb/docs/ru/core/development/manage-releases.md
> +- [Интерфейс командной строки YDB (CLI)](#cli)
Давай дальше добавим, иначе я не скоро добавлю доку по обновлению релизов YDB в Аркадии.

2024-01-31 12:17 UTC, alexv-smirnov commented on ydb/docs/ru/core/development/manage-releases.md
> +Расписание релизов сервера YDB включает в себя 4 мажорных релиза ежегодно, поэтому релиз `YY.1` является первым, а `YY.4` - последним в году `YY`. Количество минорных релизов не является постоянным и
1. Fixed
2. In fact, it's really not about minors per year, but minors per major. Made it more clear.

2024-02-01 08:15 UTC, fomichev3000 approved these changes, later dismissed

2024-02-02 06:25 UTC, blinkov requested changes

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +YDB server release schedule typically includes 4 major releases for each year, so the release `YY.1` is the first one, and `YY.4` is the last one for a year `YY`. Number of minor releases is not fixe
```suggestion
{{ ydb-short-name }} server version consists of three numbers separated by dots:

1. The last two digits of calendar year of the release
2. Major release ordinal number in a given year
3. Minor release ordinal number for a given major release

Thus, {{ ydb-short-name }} server major version is a combination of the first two numbers (for example, `23.3`), and the full version is a combination of all three (for example, `23.3.5`).
{{ ydb-short-name }} server release schedule typically includes 4 major releases per year, so the release `YY.1` is the first one, and `YY.4` is the last one for a year `YY`. The number of minor releases is not fixed, and may vary from one major release to another.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +Release testing is iterative. Each iteration starts by assigning a tag to a commit on the release branch, specifying a minor version to be tested. For instance, the minor version tag `23.3.5` marks a
```suggestion
Release testing is iterative. Each iteration starts by assigning a tag to a commit on the release branch, specifying a minor version to be tested. For example, the minor version tag `23.3.5` marks a 5th testing iteration for the major release `23.3`.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +A tag can be considered as either 'candidate' or 'stable'. Initially, a first tag is assigned to the release branch right after its creation, and this tag is considered as 'candidate'.
```suggestion
A tag can be considered to be either "candidate" or "stable". Initially, the first tag is created in the release branch right after its creation. This tag is considered as "candidate".
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +During a testing iteration, code from release branches undergo the extensive testing including deployment on the UAT/prestable and production environments of the principal users. To perform such test
```suggestion
During a testing iteration, code from release branches undergoes an extensive testing including deployment on [UAT](https://en.wikipedia.org/wiki/Acceptance_testing), prestable, and production environments of companies using YDB. To perform such testing, YDB code from a GitHub release tag is imported into the corporate context of a given user, following its internal policies and standards. Then it's built, deployed to the necessary environments, and thoroughly tested.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +Based on a list of problems, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) decides if the minor release can be promoted to stable, or a new testing iteration must be star
```suggestion
Based on a list of uncovered problems, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) decides if the current minor release can be promoted to be called "stable", or a new testing iteration must be started over with a new minor release tag. In fact, as soon as a critical problem is discovered during testing, developers fix it in the `main` branch, and backport changes to the release branch right away. So, by the time testing iteration finishes, there will be a new tag and a new testing iteration if there are some new commits on top of the current tag.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +If testing iteration proves the quality of a minor release, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the release notes, and publishes the release on the Git
```suggestion
If testing iteration proves the quality of a minor release, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-server.md), and publishes the YDB server release on both the [GitHub Releases](https://github.com/ydb-platform/ydb/releases) and [Downloads](../downloads.md#ydb-server) pages, therefore declaring it as "stable".
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +YDB CLI version comprise of three numbers separated by a dot character. First number is a major version (currently `2`), second is the minor, and the third is a patch number. For instance, `2.8.0` is
```suggestion
{{ ydb-short-name }} CLI version consists of three numbers separated by dots:

1. Major release ordinal number (currently, `2`)
2. Minor release ordinal number for a given major release
3. Patch number

For example, `2.8.0` is the 2nd major release, 8th minor, without additional patches.
{{ ydb-short-name }} CLI version comprise of three numbers separated by a dot character. First number is a major version (currently `2`), second is the minor, and the third is a patch number. For instance, `2.8.0` is the 2nd major, 8th minor, without patches.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +There's no schedule for the YDB CLI minor releases, a new release comes as soon as we have some new valuable functionality. Initially, every new minor release has `0` as a patch number. If there are
```suggestion
There's no schedule for the {{ ydb-short-name }} CLI minor releases, a new release comes as soon as there's some new valuable functionality. Initially, every new minor release has `0` as a patch number. If there are critical bugs found in that version, or some minor part of functionality did not catch it as planned, a patch can be released, incrementing only the patch number, like it was for `2.1.1`.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +Tags for YDB CLI are assigned on the trunk (`main`) branch by a member of the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) after running tests for some revision. To distingu
```suggestion
Tags for {{ ydb-short-name }} CLI are assigned on the `main` branch by a member of the [{{ ydb-short-name }} Release team](https://github.com/orgs/ydb-platform/teams/release) after running tests for some revision. To distinguish from the {{ ydb-short-name }} server tags, {{ ydb-short-name }} CLI tags have a `CLI_` prefix before the version number, for example [CLI_2.8.0](https://github.com/ydb-platform/ydb/tree/CLI_2.8.0).
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +To declare a YDB CLI tag as stable, a member of the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the release notes, and publishes the release on the GitHub [Release
```suggestion
To declare a {{ ydb-short-name }} CLI tag as stable, a member of the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-cli.md), and publishes the release on the [GitHub Releases](https://github.com/ydb-platform/ydb/releases) and [Downloads](../downloads.md#ydb-cli) pages.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +# Manage YDB releases
```suggestion
# Manage {{ ydb-short-name }} releases
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +- [YDB command-line interface (CLI)](#cli)
```suggestion
- [{{ ydb-short-name }} server](#server)
- [{{ ydb-short-name }} command-line interface (CLI)](#cli)
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +## YDB server release cycle {#server}
```suggestion
## {{ ydb-short-name }} server release cycle {#server}
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +YDB maintains compatibility between major versions to ensure a cluster can operate while its nodes run two adjacent major versions of the YDB server executable. You may refer the [Updating YDB](../ad
```suggestion
{{ ydb-short-name }} maintains compatibility between major versions to ensure a cluster can operate while its nodes run two adjacent major versions of the YDB server executable. You may refer the [Updating {{ ydb-short-name }}](../administration/upgrade.md) article to learn more about the cluster upgrade procedure.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +Given the above compatibility target, major releases go in pairs, with odd numbers mostly adding new functionality switched off by feature flags, and even numbers enabling that functionality.
```suggestion
Given the above compatibility target, major releases go in pairs: releases with odd numbers mostly add new functionality switched off by feature flags, while releases with even numbers enable that functionality.
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +## YDB CLI (Command-Line Interface) release cycle {#cli}
```suggestion
## {{ ydb-short-name }} CLI (Command-Line Interface) release cycle {#cli}
```

2024-02-02 06:25 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +In general, release cycle for YDB CLI is much simpler and shorter than for the server, producing more frequent releases.
```suggestion
In general, release cycle for {{ ydb-short-name }} CLI is much simpler and shorter than for the server, producing more frequent releases.
```

2024-02-02 11:04 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +All major version releases, both odd and even, go through the comprehensive testing process producing a number of minor versions. Each minor version is created by tagging a relevant commit of the rel
```suggestion
All major version releases, both odd and even, go through the comprehensive testing process producing a number of minor versions. Each minor version is created by tagging a relevant commit of the release branch with a full version number. So, there can be tags `24.1.1`, `24.1.2` etc. on the `stable-24-1` branch. As soon as a minor version proves its quality, we consider it as stable, and register a Release on GitHub linked to its tag, add it to [downloads](../downloads/index.md#ydb-server) and [changelog](../changelog-server.md) documentation pages, etc. Thus, there can be more that one stable release for a major version.
```

2024-02-02 11:04 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +If testing iteration proves the quality of a minor release, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-server.md), and publis
```suggestion
If testing iteration proves the quality of a minor release, the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-server.md), and publishes the YDB server release on both the [GitHub Releases](https://github.com/ydb-platform/ydb/releases) and [Downloads](../downloads/index.md#ydb-server) pages, therefore declaring it as "stable".
```

2024-02-02 11:38 UTC, blinkov commented on ydb/docs/en/core/development/manage-releases.md
> +To declare a {{ ydb-short-name }} CLI tag as stable, a member of the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-cli.md), and publ
```suggestion
To declare a {{ ydb-short-name }} CLI tag as stable, a member of the [YDB Release team](https://github.com/orgs/ydb-platform/teams/release) prepares the [release notes](../changelog-cli.md), and publishes the release on the [GitHub Releases](https://github.com/ydb-platform/ydb/releases) and [Downloads](../downloads/index.md#ydb-cli) pages.
```

2024-02-12 11:10 UTC, blinkov requested changes

2024-02-12 11:10 UTC, blinkov commented on ydb/docs/ru/core/development/manage-releases.md
> +Основываясь на перечне выявленных проблем, [релизная команда {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) решает, можно ли повысить статус минорного релиза до стабильного
```suggestion
Основываясь на перечне выявленных проблем, [релизная команда {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) решает, можно ли повысить статус минорного релиза до стабильного, или необходимо запустить новую итерацию тестирования с новым тегом минорного релиза. Фактически, как только во время тестирования обнаруживается критическая проблема, разработчики исправляют ее в `main` и сразу же мержат изменения в релизную ветку. Таким образом, к моменту завершения тестирования, если в релизной ветке есть какие-либо коммиты поверх текущего тега, это означает что последует новый тег и новая итерация тестирования.
```

2024-02-12 11:10 UTC, blinkov commented on ydb/docs/ru/core/development/manage-releases.md
> +3. Номер патча
```suggestion
1. Порядковый номер мажорной версия (в настоящее время "2");
2. Порядковый номер минорной версии для заданной мажорной;
3. Номер патча.
```

2024-02-12 11:10 UTC, blinkov commented on ydb/docs/ru/core/development/manage-releases.md
> +Теги для {{ ydb-short-name }} CLI назначаются в транке (ветка `main`) участником [релизной команды {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) после запуска тестов для н
```suggestion
Теги для {{ ydb-short-name }} CLI назначаются в транке (ветка `main`) участником [релизной команды {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) после запуска тестов для некоторой ревизии. Чтобы отличаться от тегов сервера {{ ydb-short-name }}, теги CLI {{ ydb-short-name }} содержат префикс `CLI_` перед номером версии, например [CLI_2.8.0](https://github.com/ydb-platform/ydb/tree/CLI_2.8.0).
```

2024-02-12 11:10 UTC, blinkov commented on ydb/docs/ru/core/development/manage-releases.md
> +Чтобы объявить тег {{ ydb-short-name }} CLI стабильным, участник [релизной команды {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) готовит [перечень изменений](../changelog-
```suggestion
Чтобы объявить тег {{ ydb-short-name }} CLI стабильным, участник [релизной команды {{ ydb-short-name }}](https://github.com/orgs/ydb-platform/teams/release) готовит [перечень изменений](../changelog-cli.md), и публикует релиз на странице GitHub [Releases](https://github.com/ydb-platform/ydb/releases) и в разделе [Загрузки](../downloads/index.md#ydb-cli) документации.
```

2024-02-12 11:56 UTC, blinkov approved these changes, later dismissed

2024-02-12 14:50 UTC, merged