YQ-2417 show ast in case of compilation error
ydb-platform/ydb pull request #1353
Opened 2024-01-26 16:30 UTC by GrigoriyPA

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-30 11:24 UTC, UgnineSirdis requested changes

2024-01-30 11:24 UTC, UgnineSirdis commented on ydb/core/kqp/host/kqp_host.cpp
> +            prepareResult.PreparingQuery->MutablePhysicalQuery()->SetQueryAst(KqpExprToPrettyString(*GetExprRoot(), ExprCtx));
Here is this file in FillResult there is line: 
`prepareResult.QueryAst = prepareResult.PreparingQuery->GetPhysicalQuery().GetQueryAst();`
Why don't we do the same in this function?

2024-01-30 11:24 UTC, UgnineSirdis commented on ydb/core/kqp/host/kqp_host_impl.h
> +    virtual void FillPartialResult(TResult&) const {}
Can we use FillResult, but check status in it?

2024-01-30 11:24 UTC, UgnineSirdis commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +    void FillPreparedQuery(std::unique_ptr<NKikimrKqp::TPreparedQuery> preparingQuery, NKikimrKqp::EQueryType queryType) {
We fill `KqpCompileResult` in this function. Maybe it's better to name it `FillCompileResult`?

2024-01-30 11:24 UTC, UgnineSirdis commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +                KqpCompileResult->Ast = AstResult->Ast;
Can we do it in else branch (in case of `status != Ydb::StatusIds::SUCCESS`)?

2024-02-13 09:42 UTC, Hor911 approved these changes

2024-02-13 10:24 UTC, UgnineSirdis approved these changes

2024-02-13 10:51 UTC, merged