Add new article: Run YDB cluster in cloud.
ydb-platform/ydb pull request #1355
Opened 2024-01-26 17:13 UTC by Pseudolukian

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-01-29 02:45 UTC, blinkov commented on ydb/docs/ru/core/deploy/toc_i.yaml
> +- name: Развертывание кластера с помощью Ansible и Terraform
давай подвинем это в quickstart следом за k8s

2024-01-29 02:48 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Подключитесь по SSH к виртуальной машине, с которой будет осуществляться установка YDB (инсталляционная машина (по умолчанию имеет название ydb-install-vm)) и установите/обновите необходимые пакеты и
* откуда взять эту виртуальную машину? и почему не работать просто локально с ноутбука?
* какие к ней требования, по командам ниже выглядит, что как минимум нужна Ubuntu/Debian
* нет заголовока

2024-01-29 02:48 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +* `sudo apt install ansible` – установка Ansible.
ниже используется git — вероятно его тоже надо установить

2024-01-29 02:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Скачайте репозиторий с готовыми плейбуками для установки YDB на кластер – `git clone https://github.com/ydb-platform/ydb-ansible.git`. Будут скачены: роли, плейбуки, make файлы и докер-файл для запус
```suggestion
Скачайте репозиторий с готовыми Ansible плейбуками для установки YDB на кластер – `git clone https://github.com/ydb-platform/ydb-ansible.git`. Этот репозиторий содержит роли, плейбуки, make файлы и докер-файл для запуска Ansible в контейнере. 
```

2024-01-29 02:52 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +* `python3 --version`и `pip3 --version` – проверка версий Python и пакетного менеджера pip:
непонятно зачем установку начинать с проверки версий того, что ещё даже не пытались установить

2024-01-29 02:53 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Выполните команду `ansible --version`, чтобы убедиться в том, что Ansible использует ядро не ниже версии 2.15.2 – это требование исполнения плейбуков YDB:
по умолчание слово «ядро» ассоциируется с ядром Linux, это может запутать

2024-01-29 02:55 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +1. Выполнить команду `ansible-galaxy collection install git+https://github.com/ydb-platform/ydb-ansible.git,refactor-use-collections` для установки `ydb_platform.ydb` и `community.general` коллекций
совсем не очевидно что это и зачем

2024-01-29 02:56 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +2. Заменить стандартный путь, указанный в опции `collections_paths` группы `default` в конфигурационном файле `ansible.cfg` на актуальный путь коллекций Ansible из вывода предыдущей команды: `/home/u
как узнать этот путь, если он получился другим в зависимости от ОС и видимо имени пользовать?

2024-01-29 02:57 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Основная рабочая директория в скаченном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории, необходимые для работы Ansible:
нет там такой директории:
```
➜  ydb-ansible git:(main) pwd
/home/blinkov/ydb-ansible
➜  ydb-ansible git:(main) ls -1 | grep exam
ansible-examples.txt
hosts.example
➜  ydb-ansible git:(main)
```

2024-01-29 03:01 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +3. Скопируйте приватную часть SSH-ключа пользователя, под которым подключается Ansible в директорию `examples/9-nodes-mirror-3-dc/files`. Этот же ключ используется для подключения по SSH к инсталляци
как понять под каким пользователем подключается Ansible? как скопировать? как случайно не испортить на нём ограничения доступа?

2024-01-29 03:01 UTC, blinkov commented on ydb/docs/ru/core/deploy/toc_i.yaml
> +- name: Развертывание кластера с помощью Ansible и Terraform
и пока оно выглядит скорее как чисто про Ansible, без Terraform

2024-01-29 03:02 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Трафик между нодами имеет TLS-шифрование, поэтому для каждой ноды генерируется свой набор сертификатов безопасности скриптом `examples/9-nodes-mirror-3-dc/files/ydb-ca-update.sh`. Скрипт поместит гот
тут предлагается запустить этот скрипт без аргументов или что?

2024-01-29 03:03 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Для поддержания консистентности версий YDB на всех нодах – используется единый источник установки (путь до скачанного архива YDB), который указывается в переменной `ydb_archive` инвентаризационного ф
убрать «документации ydb.tech» — мы и так в ней находимся

2024-01-29 03:04 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_pass
```suggestion
Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_password_file.txt` содержат пароль для root пользователя YDB. Инвентаризационный файл `99-inventory-vault.yaml` зашифрован. Для изменения дефолтного пароля – укажите новый пароль в файле `/examples/9-nodes-mirror-3-dc/ansible_vault_password_file.txt`,  продублируйте его в файле `/examples/9-nodes-mirror-3-dc/inventory/99-inventory-vault.yaml` в формате:
```

2024-01-29 03:09 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +{% include [ansible-ydb-install](./_includes/ansible-ydb-install.md) %}
давай вместо include вперемешку сделаем две статьи:
1) как задеплоить кластер на произвольные сервера через Ansible
2) как правильно настроить виртуалки через terraform, в конце получаем список хостов и предлагаем перейти с ними к статье (1)

2024-01-29 03:10 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* В случае использования Яндекс Облака потребуются повышенные лимиты на количество vCPU виртуальных машин, общий объём SSD-дисков и количество всех публичных IP-адресов в частном облаке.
ссылки на инструкции по установке всего этого

2024-01-29 03:11 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Инструкция описывает развёртывание кластера {{ ydb-short-name }} с помощью Terraform и его конфигурирование через Ansible. Кластер развертывается на девяти виртуальных машинах, имеет тип избыточности
* к чему это «обычно стойки» — в облаке это не актуально
* FQDN лучше сделать ссылкой на вики, а не тут расписывать

2024-01-29 03:12 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Скачать Terraform проект для автоматического создания инфраструктуры в Яндекс облаке можно из GitHub репозитория [YDB](https://github.com/ydb-platform/ydb-terraform/), а Ansible проект скачать можно
https://github.com/ydb-platform/ydb-terraform/ — 404

2024-02-05 04:50 UTC, blinkov requested changes

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/toc_i.yaml
> +  href: ydb-ansible-cluster/ansible-ydb-cluster.md
никто этот текст тут не найдёт (сам три минуты искал в превью...), давай подвинем в getting_started/ansible.md

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В инструкции изложен процесс развертывания {{ ydb-short-name }} кластера на группе серверов с помощью Ansible. Минимальное количество серверов в кластере – восемь штук для модели избыточности `block-
h1 заголовка нет

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для работы с плейбуками на локальной (промежуточной или инсталляционной) машине понадобится:
* судя по `apt update` ниже — на ней тоже должна быть Ubuntu или может Debian, надо это обозначить с указанием допустимого диапазона версия
* и ещё git тоже нужен

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Скачайте репозиторий командой `git clone https://github.com/ydb-platform/ydb-ansible.git`.
уже ж скачали выше, на 15 строке?

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Создайте директорию, куда будет скачен репозиторий с плейбуками Ansible и создано виртуальное окружения – `mkdir <project name>`.
легко не заметить, что это две разные директории и непонятно где они должны находиться относительно друг друга — пососедству или одна внутри другой

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Менеджер виртуальных окружений Python pipenv.
какие версии нужны?

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Создайте виртуальное окружение командой `pipenv --python /usr/bin/python3`. Команда создаст виртуальное окружение с Python3 версии, установленной в системе. Если `pipenv` не установлен, выполните к
установка так легко не прошла, пришлось патчить `$PATH` из-за:

>   WARNING: The script virtualenv is installed in '/home/blinkov/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Перейдите в директорию `/examples/9-nodes-mirror-3-dc` и установите необходимые пакеты внутрь виртуального окружения командой `pipenv install -r requitements.txt`.
```suggestion
* Перейдите в директорию `cd examples/9-nodes-mirror-3-dc` и установите необходимые пакеты внутрь виртуального окружения командой `pipenv install -r requirements.txt`.
```

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Основная рабочая директория в скаченном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории:
```suggestion
Основная рабочая директория в скачанном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории:
```

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* `setup_playbook.yaml` – плейбук, который запускает роли установки и настройки {{ ydb-short-name }} на кластере. Роли располагаются в директории `/roles` (верхний уровень скаченного репозитория).
```suggestion
* `setup_playbook.yaml` – плейбук, который запускает роли установки и настройки {{ ydb-short-name }} на кластере. Роли располагаются в директории `../../roles` (в корне скачанного репозитория).
```

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +    + `99-inventory-vault.yaml` – зашифрованный инвентаризационный файл для безопасной доставки пароля root пользователя YDB;
то есть там в open-souce репозитории лежит какой-то дефолтный пароль?

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +  Installing 'ydb_platform.ydb:0.0.1' to '/Users/pseudolukian/.ansible/collections/ansible_collections/ydb_platform/ydb'
```suggestion
  Installing 'ydb_platform.ydb:0.0.1' to '/home/example/.ansible/collections/ansible_collections/ydb_platform/ydb'
```

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +4. Скопируйте приватную часть SSH-ключа для доступа к серверам кластера {{ ydb-short-name }} в директорию `examples/9-nodes-mirror-3-dc/files`.
как именно? какое имя файла? и почему оно вообще из `~/.ssh` не может его взять?

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* OS: Ubuntu 18+, Debian 9+.
```suggestion
**Серверы должны соответствовать следующим системным требованиям** (на каждый сервер):
* 16 CPU (рассчитывается исходя из утилизации 8 CPU сторадж нодой и 8 CPU динамической нодой).
* 8 GB RAM (рекомендуемый минимальный объем RAM).
* Основной диск для операционной системы.
* Дополнительный SSD-диск размером от 120 GB для хранения данных.
* Доступ по SSH.
* Сетевая связность до остальных машин в кластере.
* OS: Ubuntu 18+, Debian 9+.
```

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +{% note info %}
где-то в этих краях стоит порекламировать соседнюю статью про Terraform — мол если готового подходящего железа у вас ещё нет, то его можно вот так вот развернуть и затем вернуться к этой статье

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
непонятно зачем тут отсылки к инструкциям про managed service for ydb, а не просто виртуалки — в них лишние шаги предлагают делать

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
не хватает готовой для копипасты команды git clone

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +Для проверки синтаксиса и логики развертывания инфраструктуры в облаке – выполните команду `terraform plan`. На этом этапе будет создана виртуальная карта реализации сценария создания ресурсов в обла
сходу `terraform plan` не заработал, просит сначала `terraform init`

2024-02-05 04:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +Для проверки синтаксиса и логики развертывания инфраструктуры в облаке – выполните команду `terraform plan`. На этом этапе будет создана виртуальная карта реализации сценария создания ресурсов в обла
![Screenshot 2024-02-05 at 11 48 48](https://github.com/ydb-platform/ydb/assets/623861/21a6abfe-4610-4658-bc40-70e3e15e87d4)

2024-02-05 05:30 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +Для проверки синтаксиса и логики развертывания инфраструктуры в облаке – выполните команду `terraform plan`. На этом этапе будет создана виртуальная карта реализации сценария создания ресурсов в обла
как оказалось оно не умеет брать данные сервисного аккаунта из настроек `yc`

2024-02-05 05:40 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
❗ в `ydb-terraform` все 9 машин создаются в одной зоне доступности вместо трёх разных

2024-02-05 05:49 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
вот такое ещё вылазит почему-то:

> │ Error: Error while requesting API to create DnsRecordSet: server-request-id = ecaf1265-8491-45fd-bb68-8d1b021a3dd2 server-trace-id = 27aae44c7a25298d:8a05f2445f059b76:27aae44c7a25298d:1 client-request-id = 60f8fb67-aec9-44f9-9d2b-fd1dfebdc8ef client-trace-id = 04f54387-8e52-498a-9335-1b2bb04ff34f rpc error: code = FailedPrecondition desc = Some of added RecordSets already exist: {name: static-node-6.ydb-cluster.com.; type: A}
> │
> │   with yandex_dns_recordset.ydb-static-nodes-fqdn[5],
> │   on main.tf line 82, in resource "yandex_dns_recordset" "ydb-static-nodes-fqdn":
> │   82: resource "yandex_dns_recordset" "ydb-static-nodes-fqdn" {

2024-02-05 05:58 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +### Проверка доступности виртуальных машин между собой { #vm-network-check }
не хватает следующего шага с описанием как попасть на этот самый инсталляционный хост: почему-то в файл hosts попал только он, но не остальные хосты, с которыми как раз нужен файл для прохождения инструкции по ansible, а правильно составлять ssh команду пришлось вручную

либо возможно совсем выпилить этот десятый хост и предлагать ставить ansible туда же, где до этого был установлен terraform

2024-02-05 06:02 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +* Подключение к подсети `default-ru-central1-a`.
в каждом облаке своя сеть с таким названием, а в конфиге указывается id, а не название из-за чего лезут Permission denied пока не найдёшь и не подставишь свои id

2024-02-05 06:03 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +* [Сервисный аккаунт](https://cloud.yandex.ru/ru/docs/iam/concepts/users/service-accounts) с ролями: `vpc.admin`, `resource-manager.admin`, `compute.admin`, `admin`.
просто `admin` оказалось достаточно, вероятно нужен либо он, либо три остальных

2024-02-05 06:04 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +        - Количество всех публичных IP-адресов – 15 (стандартное значение 8)
а зачем? в создавшихся виртуалках только у одной был публичный IP

2024-02-05 06:05 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +* Увеличенные [лимиты](https://cloud.yandex.ru/ru/docs/vpc/concepts/limits) частного облака:
что имеется ввиду под «частным» облаком? ассоциируется с https://en.wikipedia.org/wiki/Private_cloud_computing_infrastructure, но явно речь не про то

2024-02-05 06:10 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +          static-node-1.ydb-cluster.com:
стоит сделать так, чтобы список хостов один раз указывался, а не N

2024-02-05 06:12 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_pass
```suggestion
Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_password_file.txt` содержат пароль для root пользователя YDB. Инвентаризационный файл `99-inventory-vault.yaml` зашифрован. Для изменения дефолтного пароля – укажите новый пароль в файле `/examples/9-nodes-mirror-3-dc/ansible_vault_password_file.txt`,  продублируйте его в файле `/examples/9-nodes-mirror-3-dc/inventory/99-inventory-vault.yaml` в формате:
```

2024-02-05 06:14 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +  Запустите скрипт `examples/9-nodes-mirror-3-dc/files/ydb-ca-update.sh`. Скрипт сгенерирует наборы сертификатов для TLS-шифрования трафика между YDB нодами и поместит их в поддиректорию `examples/9-
скрипт завис на этапе `** Generating CA key`

2024-02-05 06:20 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_pass
предлагаю дропнуть дефолтный пароль и заставлять обязательно придумывать новый

2024-02-05 06:27 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +По умолчанию конфигурационный файл YDB и Ansible проект настроены на создание кластера из девяти серверов с моделью избыточности `mirror-3-dc`. Если требуется создать кластер из восьми серверов с тип
а почему не сделать рядом подпапку в `examples`, чтоб не заставлять в ручную что-то править?

сейчас оно звучит как-будто можно сначала задеплоить `mirror-3-dc`, потом проделать эти шаги и магически кластер сконвертируется в `block-4-2`, но это явно не так

2024-02-05 06:27 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука `setup_playbook.yaml` (стандартная поставка) будет создан кластер YDB, обладающий следующими свойствами:
не вижу команду, которая его выполнит

2024-02-05 06:31 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Основная рабочая директория в скаченном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории:
ещё там лежат какие-то левые Dockerfile и Makefile, которые видимо стоит удалить

2024-02-05 06:33 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука `setup_playbook.yaml` (стандартная поставка) будет создан кластер YDB, обладающий следующими свойствами:
нашел, сходу не завелась:
```
✗ ansible-playbook setup_playbook.yaml
Using /home/blinkov/ydb-ansible/examples/9-nodes-mirror-3-dc/ansible.cfg as config file
ERROR! the role 'ydb_platform.ydb.packages' was not found in /home/blinkov/ydb-ansible/examples/9-nodes-mirror-3-dc/roles:/home/blinkov/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/blinkov/ydb-ansible/examples/9-nodes-mirror-3-dc

The error appears to be in '/home/blinkov/ydb-ansible/examples/9-nodes-mirror-3-dc/setup_playbook.yaml': line 6, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      ansible.builtin.import_role:
        name: ydb_platform.ydb.packages
              ^ here
```

2024-02-05 07:45 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука `setup_playbook.yaml` (стандартная поставка) будет создан кластер YDB, обладающий следующими свойствами:
починить ^^^ помогло удаление настройки `collections_paths` из ansible.cfg

2024-02-05 09:30 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +1. Роль `packages` настраивает репозитории, управляет предпочтениями и конфигурациями APT, а также исправляет неконфигурированные пакеты и устанавливает необходимые программные пакеты в зависимости о
![Screenshot 2024-02-05 at 16 30 10](https://github.com/ydb-platform/ydb/assets/623861/13705fb4-51c5-40d0-81f8-434cedf27df2)

2024-02-05 12:59 UTC, katidisergei commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
Предлагаю вписать последовательность
sudo apt update
sudo apt upgrade
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible-core 

иначе, если сделать просто sudo apt install ansible ставится вот такая версия ansible:
ansible 2.10.8,  что не соответствует минимальному требованию в ansible [core 2.16.2]

2024-02-05 13:21 UTC, katidisergei commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
Вот эьтот блок кода пробует прописать хосты в DNS еще раз. Скажи пжл. Есть ли выход на автора кода что бы понять логику работы?

#resource "yandex_dns_recordset" "ydb-static-nodes-fqdn" {
#  count = length(yandex_compute_instance.ydb-static-nodes.*.id)
#
#  zone_id = yandex_dns_zone.ydb-claster-dns-private.id
#  name    = "static-node-${count.index + 1}"
#  type    = "A"
#  ttl     = 300
#  data    = [yandex_compute_instance.ydb-static-nodes[count.index].network_interface[0].ip_address]
#}

2024-02-05 13:25 UTC, katidisergei commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +        - Количество всех публичных IP-адресов – 15 (стандартное значение 8)
Здесь лучше сделать отсылку на системные требования, т.к. в тестовой конфигурации vCPU можно сделать 20, памяти 40 Gb, 200 GB SSD, 800 GB HDD

2024-02-05 14:05 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Сетевая связность машин в кластере.
как оказалось, нужен ещё доступ в интернет ради `apt`

2024-02-05 14:20 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Root пользователь YDB с назначением ему пароля доступа к БД.
в реальности имя пользователя не с заглавной буквы

2024-02-05 14:22 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Тестовая база `test` в домене `Root`.
она вроде как называется `/Root/database` по умолчанию, а не test

2024-02-05 14:23 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для безопасного подключения к мониторингу можно воспользоваться SSH-туннелированием. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb
не помешает инструкция как соединяться через CLI и SDK, оказалось довольно нетривиально: `ydb -d /Root/database -e grpcs://node-2.ydb-cluster.com:2135 --ca-file ~/ydb-ansible/examples/9-nodes-mirror-3-dc/files/CA/certs/ca.crt --user root --password-file ~/ydb-ansible/examples/9-nodes-mirror-3-dc/ansible_vault_password_file yql -s 'select 1;'`

2024-02-05 14:24 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Проверить работоспособность созданного кластера тестовой нагрузкой можно с помощью [YDB SDK](../../reference/ydb-sdk/index.md), в котором есть инструменты создания тестовых нагрузок.
разве были? `ydb workload` в CLI было б логичнее

2024-02-05 15:03 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для безопасного подключения к мониторингу можно воспользоваться SSH-туннелированием. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb
в embedded ui:

1) не работает аутентификация
![photo_2024-02-05 22 01 53](https://github.com/ydb-platform/ydb/assets/623861/3a6027ee-f189-4656-8879-d4478dcfde1b)

2) пишут, что кластер сразу в деградированном состоянии
![Screenshot 2024-02-05 at 21 58 56](https://github.com/ydb-platform/ydb/assets/623861/c58c9a5b-013d-4be8-b143-f47f658b63bd)

2024-02-05 15:45 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +* 8 GB RAM (рекомендуемый минимальный объем RAM).
в `ydb-terraform` по умолчанию приезжает 2 ядра и 4 гб памяти, чего оказывается недостаточным, а 16 ядер на 8 гб памяти конфигурация не доступна — пришлось сделать 16 ядер 16 гб

2024-02-05 15:46 UTC, blinkov commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Доступ к мониторингу на 8765 порту.
нужен раздел про то, где логи `ydbd` искать

2024-02-06 11:20 UTC, katidisergei commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для безопасного подключения к мониторингу можно воспользоваться SSH-туннелированием. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb
в оригинальном документе не совсем верно указаны порты
"ssh -L 87654:localhost:8654 -i <ssh private key> <user>@<first ydb static node ip>"

2024-02-07 12:22 UTC, katidisergei commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +### Проверка доступности виртуальных машин между собой { #vm-network-check }
Предлагаю добавить серийные консоли к ВМ, это бывает удобно
 в main.tf  в блок metadata

  metadata = {
    ssh-keys = "ubuntu:${file(var.ssh_key_pub_path)}"
    serial-port-enable = 1  # добавить этот пункт
  }

2024-02-07 16:39 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/toc_i.yaml
> +- name: Развертывание кластера с помощью Ansible и Terraform
Перенёс

2024-02-07 16:40 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Подключитесь по SSH к виртуальной машине, с которой будет осуществляться установка YDB (инсталляционная машина (по умолчанию имеет название ydb-install-vm)) и установите/обновите необходимые пакеты и
Поправил

2024-02-07 16:40 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +* `sudo apt install ansible` – установка Ansible.
Переделал всю инструкцию по установке

2024-02-07 16:41 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Скачайте репозиторий с готовыми плейбуками для установки YDB на кластер – `git clone https://github.com/ydb-platform/ydb-ansible.git`. Будут скачены: роли, плейбуки, make файлы и докер-файл для запус
Учёл

2024-02-07 16:42 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Выполните команду `ansible --version`, чтобы убедиться в том, что Ansible использует ядро не ниже версии 2.15.2 – это требование исполнения плейбуков YDB:
Переписал это место

2024-02-07 16:42 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +1. Выполнить команду `ansible-galaxy collection install git+https://github.com/ydb-platform/ydb-ansible.git,refactor-use-collections` для установки `ydb_platform.ydb` и `community.general` коллекций
Убрал и переписав это место

2024-02-07 16:43 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +2. Заменить стандартный путь, указанный в опции `collections_paths` группы `default` в конфигурационном файле `ansible.cfg` на актуальный путь коллекций Ansible из вывода предыдущей команды: `/home/u
Тоже переписал

2024-02-07 16:43 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Основная рабочая директория в скаченном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории, необходимые для работы Ansible:
Переписал

2024-02-07 16:44 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Трафик между нодами имеет TLS-шифрование, поэтому для каждой ноды генерируется свой набор сертификатов безопасности скриптом `examples/9-nodes-mirror-3-dc/files/ydb-ca-update.sh`. Скрипт поместит гот
Переписал

2024-02-07 16:44 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Для поддержания консистентности версий YDB на всех нодах – используется единый источник установки (путь до скачанного архива YDB), который указывается в переменной `ydb_archive` инвентаризационного ф
Переделал

2024-02-07 16:44 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_pass
Убрал ошибочный бэктик

2024-02-07 16:45 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Инструкция описывает развёртывание кластера {{ ydb-short-name }} с помощью Terraform и его конфигурирование через Ansible. Кластер развертывается на девяти виртуальных машинах, имеет тип избыточности
Переписал

2024-02-07 16:46 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/toc_i.yaml
> +  href: ydb-ansible-cluster/ansible-ydb-cluster.md
Подвинул

2024-02-07 16:46 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В инструкции изложен процесс развертывания {{ ydb-short-name }} кластера на группе серверов с помощью Ansible. Минимальное количество серверов в кластере – восемь штук для модели избыточности `block-
Указал h1

2024-02-07 16:47 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для работы с плейбуками на локальной (промежуточной или инсталляционной) машине понадобится:
Указал требуемые ОС

2024-02-07 16:47 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Скачайте репозиторий командой `git clone https://github.com/ydb-platform/ydb-ansible.git`.
Переписал

2024-02-12 05:35 UTC, blinkov requested changes

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/repo-tree.md
> +│   ├── setup_playbook.yaml #Плейбук, который запускает роли установки и настройки {{ ydb-short-name }} на кластере.
проверить работает ли вообще `{{ ydb-short-name }}` внутри блока с кодом, и если да, то заменить соседние упоминания `{{ ydb-short-name }}` на YDB, а если нет — наоборот

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +Установите и настройте Terraform, следуя инструкциям: [Установка и настройка Terraform](https://cloud.yandex.ru/ru/docs/ydb/terraform/install#terraform-install-on-dif-os), [Получение данных для аутен
ссылаться надо на доку compute, а не managed service for ydb — мы ведь просто виртуалки тут создаём

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +* 8 GB RAM (рекомендуемый минимальный объем RAM).
в [ansible-ydb-cluster.md](https://github.com/ydb-platform/ydb/pull/1355/files#diff-16f586ab0b594c6d07f2c4193050566f3815fe0d4fa020e3b3c93d0789692528) написано, что 16 Gb  RAM — сделать консистентно

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +* Платформа Intel `Broadwell`.
так почему самые старые процессоры?

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +* Подключение к подсети `default-ru-central1-a`.
каждая виртуалка должна быть подключена в подсеть в своей az, а не все в `a`

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +Десятая виртуальная машина – это инсталяционная машина, с которой производится установка YDB на остальные девять виртуальных машин. Все машины подключены к одной подсети и находятся в единой внутренн
Кстати, я этой десятой машиной в итоге не пользовался и запускал ansible оттуда же, откуда terraform. DNS зона всё равно норм работала.

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/terraform-install.md
> +Количество виртуальных машин и их свойства задаются группой переменных `Static node setup zone` в файле `terraform.tvars`. Количество создаваемых виртуальных машин привязано к типу избыточности: девя
про block-4-2 тоже видимо стоит тут написать, раз в текущей версии они наравне?

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +* [Сервисный аккаунт](https://cloud.yandex.ru/ru/docs/iam/concepts/users/service-accounts) с ролями: `vpc.admin`, `resource-manager.admin`, `compute.admin`, `admin`.
просто роли admin было достаточно, скорее всего на самом деле нужен либо просто admin, либо остальные три

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +* Авторизованный ключ и API-ключ для работы Terraform с Яндекс Облаком.
ссылку на доку где их брать

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +        - Общий объём SSD-дисков – 1700 ГБ (стандартное значение 1000 ГБ)
наверное именно сетевых дисков?

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +Для проверки синтаксиса и логики развертывания инфраструктуры в облаке – выполните команду `terraform plan`. На этом этапе будет создана виртуальная карта реализации сценария создания ресурсов в обла
```suggestion
Для проверки синтаксиса и логики развертывания инфраструктуры в облаке – выполните команду `terraform plan`. На этом этапе будет создана виртуальная карта реализации сценария создания ресурсов в облаке. Далее выполните команду `terraform apply`, чтобы создать реальные ресурсы в облаке. При первом запуске команды будет установлен провайдер, а потом выполнен сценарий создания ресурсов в облаке.
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В инструкции изложен процесс развертывания {{ ydb-short-name }} кластера на группе серверов с помощью Ansible. YDB может быть развернут на любом желаемом количестве серверов, но минимальное количеств
```suggestion
В инструкции изложен процесс развертывания {{ ydb-short-name }} кластера на группе серверов с помощью [Ansible](https://www.ansible.com/). Кластер {{ ydb-short-name }} может быть развернут на произвольном количестве серверов, но для обеспечения отказоустойчивости их необходимо минимум 8 для модели избыточности `block-4-2` или 9 для модели избыточности `mirror-3-dc`. О моделях избыточности можно узнать из статьи [{#T}](../../cluster/topology.md).
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В процессе эксплуатации кластер может быть [расширен](../../maintenance/manual/cluster_expansion.md) без приостановки доступа пользователей к базам данных.
не ссылаемся на ручную инструкцию из инструкций по Ansible, надо будет писать отдельную статью про то как расширять через Ansible

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Дополнительный сетевой SSD-диск размером 120 GB (не может быть меньшего размера – требования инсталляции YDB).
```suggestion
* Дополнительный SSD-диск размером от 120 GB.
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +  * Проверьте версию Ansible core – `ansible --version`
как проверить версию python тоже стоит написать

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Вне зависимости от вида создаваемого кластера (восемь серверов – `8-nodes-block-4-2` или девять серверов – `9-nodes-mirror-3-dc`) основные параметра установки и настройки YDB содержатся в инвентариза
```suggestion
Вне зависимости от топологии создаваемого кластера (восемь серверов – `8-nodes-block-4-2` или девять серверов – `9-nodes-mirror-3-dc`) основные параметра установки и настройки YDB содержатся в инвентаризационном файле `50-inventory.yaml`, который расположен в директории `<cluster model>/inventory/`.
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` не требуется. Далее можно изменить стандартный пароль root пользователя YDB, который содержится в зашифрованном инвентаризационном
удалить дефолтный пароль из репозитория и заставить читателя всегда его придумывать/генерировать заново

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +После изменения инвентаризационных файлов можно переходить к подготовке конфигурационного файла YDB.
```suggestion
После изменения инвентаризационных файлов можно переходить к подготовке конфигурационного файла {{ ydb-short-name }}.
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +1. Создайте копию директории с готовым примером. Если кластер должен состоять из серверов, число которых кратно трём (12,15,18 и т.д.), то стоит клонировать директорию `9-nodes-mirror-3-dc`, так как
Перепутаны причинно-следственные связи: если у вас кластер в трёх ДЦ/AZ, то нужно использовать за основу mirror-3-dc и желательно добавлять сервера в каждом ДЦ/AZ равномерно, из-за чего получается рекомендуемые шаг увеличения в три сервера (по одному в каждой зоне доступности).

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +4. Внесите изменения в конфигурационный файл YDB в соответствии с инструкцией [{#T}](#ydb-config-prepare).
в этой инструкции по ссылке только про замену 8/9 захардкоженных FQDN на актуальные, но не про что нужно дописывать/менять, когда серверов больше

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для выполнения сценария установки YDB необходимо запустить плейбук командой `ansible-playbook setup_playbook.yaml`, который располагается в каждой из директорий готовых шаблонов в [репозитории](https
какой-то неплавный переход от предыдущего раздела: он как раз заканчивается на запуске ansible-playbook, а тут снова к этому шагу возвращаются и с дополнительными деталями

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Последовательность выполнение ролей и их краткое описание:
выглядит как копипаста откуда-то — я этот текст уже комментировал, вероятно стоит заменить на include

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука будет создан кластер YDB, на котором развернута тестовая база данных – `database`, создан `root` пользователь и настроен доступ к web консоли на порту 8765. Для подкл
```suggestion
В результате выполнения плейбука будет создан кластер {{ ydb-short-name }}, на котором развернута тестовая база данных – `database`, создан `root` пользователь с максимальными правами доступа и запущен Embedded UI на порту 8765. Для подключения к Embedded UI можно настроить SSH-туннелирование. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb static node ip>`. После успешной установки соединения можно перейти по URL [localhost:8765](http://localhost:8765):
```

2024-02-12 05:35 UTC, blinkov commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +После успешного создания кластера YDB проверить его состояние с помощью web консоли – [http://localhost:8765/monitoring/cluster/tenants](http://localhost:8765/monitoring/cluster/tenants):
```suggestion
После успешного создания кластера {{ ydb-short-name }} проверить его состояние с помощью Embedded UI – [http://localhost:8765/monitoring/cluster/tenants](http://localhost:8765/monitoring/cluster/tenants):
```

2024-02-12 09:55 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/ansible-install-steps.md
> +  * `setup apt repositories` – настройка репозиториев apt из заданного списка.
Дал ссылку

2024-02-12 09:55 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/ansible-install-steps.md
> +  * `install packages` – установка пакетов apt с учетом заданных параметров и времени валидности кеша.
Указал список пакетов и дал ссылки на наборы пакетов в репе.

2024-02-12 09:58 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/ansible-install-steps.md
> +2. Роль `system` Задачи:
Поправил.

2024-02-12 10:31 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/_includes/ansible-install-steps.md
> +  * `format drives confirmation block` – блок задач по форматированию дисков и прерывания выполнения плейбука в случае отказа пользователя от подтверждения. В терминал будет выведен запрос на подтвер
Поправил

2024-02-12 11:34 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для выполнения сценария установки YDB необходимо запустить плейбук командой `ansible-playbook setup_playbook.yaml`, который располагается в каждой из директорий готовых шаблонов в [репозитории](https
Согласен. Удалил дубль.

2024-02-12 11:37 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Последовательность выполнение ролей и их краткое описание:
Не, копипасты нет. Вероятно он тебе просто запомнился :)

2024-02-12 11:38 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука будет создан кластер YDB, на котором развернута тестовая база данных – `database`, создан `root` пользователь и настроен доступ к web консоли на порту 8765. Для подкл
Исправил

2024-02-12 11:41 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +После успешного создания кластера YDB проверить его состояние с помощью web консоли – [http://localhost:8765/monitoring/cluster/tenants](http://localhost:8765/monitoring/cluster/tenants):
Поправил

2024-02-12 11:56 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/ydb-ansible-cluster/ansible-ydb-cluster.md
> +4. Внесите изменения в конфигурационный файл YDB в соответствии с инструкцией [{#T}](#ydb-config-prepare).
Переписал readme внутри репы с примерами.

2024-02-12 12:02 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Тестовая база `test` в домене `Root`.
Ты прав. Исправил

2024-02-12 12:04 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
Учёл.

2024-02-12 12:05 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +1. Роль `packages` настраивает репозитории, управляет предпочтениями и конфигурациями APT, а также исправляет неконфигурированные пакеты и устанавливает необходимые программные пакеты в зависимости о
Указал, что нужен выход в инет.

2024-02-12 12:06 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Сетевая связность машин в кластере.
Ага, уточнил.

2024-02-12 12:06 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Основная рабочая директория в скаченном репозитории – это `examples/9-nodes-mirror-3-dc`. В ней находятся следующие файлы и поддиректории:
Удалил.

2024-02-12 12:06 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +В результате выполнения плейбука `setup_playbook.yaml` (стандартная поставка) будет создан кластер YDB, обладающий следующими свойствами:
Убрал collections_paths.

2024-02-12 12:07 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +По умолчанию конфигурационный файл YDB и Ansible проект настроены на создание кластера из девяти серверов с моделью избыточности `mirror-3-dc`. Если требуется создать кластер из восьми серверов с тип
Переписал

2024-02-12 12:08 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +  Запустите скрипт `examples/9-nodes-mirror-3-dc/files/ydb-ca-update.sh`. Скрипт сгенерирует наборы сертификатов для TLS-шифрования трафика между YDB нодами и поместит их в поддиректорию `examples/9-
Странно. Я гонял десяток раз этот скрипт и ни разу у меня не было проблем с ним. Может ты запускаешь скрипт из под юзера, у которого недостаточно прав для работы с директориями или файлами?

2024-02-12 12:09 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Изменения других секций конфигурационного файла `50-inventory.yaml` и настроек не требуется. Инвентаризационный файл `99-inventory-vault.yaml` и файл `/examples/9-nodes-mirror-3-dc/ansible_vault_pass
Учёл и поправил

2024-02-12 12:10 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/yc-terraform-prepare.md
> +* Увеличенные [лимиты](https://cloud.yandex.ru/ru/docs/vpc/concepts/limits) частного облака:
Убрал

2024-02-12 13:08 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/terraform-install.md
> +* 8 GB RAM (рекомендуемый минимальный объем RAM).
Учёл

2024-02-12 13:09 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* Доступ к мониторингу на 8765 порту.
Не стал раскрывать этот аспект. Логи не читаемы и ничего пользователю не дадут.

2024-02-13 21:26 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +* `python3 --version`и `pip3 --version` – проверка версий Python и пакетного менеджера pip:
Поправил

2024-02-13 21:27 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Скачать Terraform проект для автоматического создания инфраструктуры в Яндекс облаке можно из GitHub репозитория [YDB](https://github.com/ydb-platform/ydb-terraform/), а Ansible проект скачать можно
Поправил

2024-02-13 21:27 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +* В случае использования Яндекс Облака потребуются повышенные лимиты на количество vCPU виртуальных машин, общий объём SSD-дисков и количество всех публичных IP-адресов в частном облаке.
Убрал это всё из инструкции

2024-02-13 21:28 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +{% include [ansible-ydb-install](./_includes/ansible-ydb-install.md) %}
Переписал всё

2024-02-14 13:32 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Для безопасного подключения к мониторингу можно воспользоваться SSH-туннелированием. Для этого на локальной машине выполните команду `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first ydb
Это было из-за недостатка ресурсов. Terraform теперь выдаёт 16 CPU, 16 GB RAM и 200 GB SSD.

2024-02-14 13:34 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/ansible-ydb-cluster.md
> +Проверить работоспособность созданного кластера тестовой нагрузкой можно с помощью [YDB SDK](../../reference/ydb-sdk/index.md), в котором есть инструменты создания тестовых нагрузок.
Дописал раздел про тестовую нагрузку.

2024-02-14 13:35 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/ydb-ansible-cluster/_includes/ansible-ydb-install.md
> +3. Скопируйте приватную часть SSH-ключа пользователя, под которым подключается Ansible в директорию `examples/9-nodes-mirror-3-dc/files`. Этот же ключ используется для подключения по SSH к инсталляци
Дополнил.

2024-02-19 03:22 UTC, blinkov commented on ydb/docs/ru/core/toc_i.yaml
> +  - name: Развертывание кластера с помощью Ansible
```suggestion
  - name: Ansible
```

2024-02-19 03:49 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +`... параметры запуска подключения к БД ... workload kv init --init-upserts 1000 --cols 4`. Будет создана тестовая таблица `kv_test`, состоящая из 4 столбцов и 1000 строк. Проверь, что таблица `kv_te
это место хорошо бы переделать на профили https://ydb.tech/docs/en/reference/ydb-cli/profile/activate , чтоб не было `...параметры запуска подключения к БД...`

2024-02-19 12:47 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +`... параметры запуска подключения к БД ... workload kv init --init-upserts 1000 --cols 4`. Будет создана тестовая таблица `kv_test`, состоящая из 4 столбцов и 1000 строк. Проверь, что таблица `kv_te
Переделал

2024-02-19 12:47 UTC, Pseudolukian commented on ydb/docs/ru/core/toc_i.yaml
> +  - name: Развертывание кластера с помощью Ansible
Поправил

2024-02-19 15:46 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +--password-file /home/ubuntu/home/ydb_cluster/ansible_vault_password_file
странные пути, кажется надо вернуть предыдущее состояние этих строк

2024-02-19 15:47 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +* `config profile create` – команда создания профиля подключения. Задаётся имя профиля.
ссылку на более подробную доку бы

2024-02-19 15:48 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
>  * `--ca-file` – путь к корневому сертификату для подключения к базе по `grpcs`. Сертификат создаётся скриптом `ydb-ca-update.sh` в директории `TLS` и располагается по пути `TLS/CA/certs/`.
...относительно корня репозитория ydb-ansible-examples

2024-02-20 09:15 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +--password-file /home/ubuntu/home/ydb_cluster/ansible_vault_password_file
Исаправил

2024-02-20 09:53 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +* `config profile create` – команда создания профиля подключения. Задаётся имя профиля.
Дал ссыпь.

2024-02-20 09:54 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +Проверить создался ли профиль можно командой `./ydb config profile list` – будет выведен список профилей. После создания профиля, его нужно активировать командой `ydb config profile activate <profile
Поправил

2024-02-20 10:04 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
>  * `--ca-file` – путь к корневому сертификату для подключения к базе по `grpcs`. Сертификат создаётся скриптом `ydb-ca-update.sh` в директории `TLS` и располагается по пути `TLS/CA/certs/`.
уточнил

2024-03-07 08:09 UTC, blinkov requested changes

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +  * `ydb_tls_dir` – specify the current path part (`/files/CA/certs/<date_time create certs>`) to the security certificates after they have been generated by the `ydb-ca-update.sh` script.
```suggestion
  * `ydb_tls_dir` – specify the current path part (`/files/CA/certs/<date-time-create-certs>`) to the security certificates after they have been generated by the `ydb-ca-update.sh` script.
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +No changes to other sections of the `50-inventory.yaml` configuration file are required. Next, you can change the standard YDB root user password contained in the encrypted inventory file `99-invento
```suggestion
No changes to other sections of the `50-inventory.yaml` configuration file are necessary. Next, you can change the standard {{ ydb-short-name }} root user password contained in the encrypted inventory file `99-inventory-vault.yaml` and in the file `ansible_vault_password_file.txt`. To change the password – specify the new password in the `ansible_vault_password_file.txt` file and duplicate it in the `99-inventory-vault.yaml` file in the format:
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +The default {{ ydb-short-name }} configuration file already includes almost all the necessary settings for deploying the cluster. You need to replace the standard FQDNs of hosts with the current FQDN
```suggestion
The default {{ ydb-short-name }} configuration file already includes almost all the necessary settings for deploying the cluster. You need to replace the standard FQDNs of hosts with the current FQDNs in the `hosts` and `blob_storage_config` sections, as well as paths to block devices if they are different:
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +The rest of the sections and settings in the configuration file remain unchanged.
```suggestion
The rest of the sections and settings in the configuration file can remain unchanged.
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +The minimum number of servers in a {{ ydb-short-name }} cluster is eight servers for the `block-4-2` redundancy model and nine servers for the `mirror-3-dc` redundancy model.
```suggestion
The minimum number of servers in a {{ ydb-short-name }} cluster is eight servers for the `block-4-2` redundancy model and nine servers for the `mirror-3-dc` redundancy model.

In `mirror-3-dc` servers should be distributed across three availability zones or datacenters as evenly as possible.
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +{% cut "Detailed step-by-step installation description for {{ ydb-short-name }}" %}
```suggestion
{% cut "Detailed step-by-step installation process description" %}
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +As a result of executing the playbook, a {{ ydb-short-name }} cluster will be created, with a test database – `database`, a `root` user with maximum access rights created, and Embedded UI running on
```suggestion
As a result of executing the playbook, a {{ ydb-short-name }} cluster will be created, with a test database named `database`, a `root` user with maximum access rights created, and [Embedded UI](../../../maintenance/embedded_monitoring/index.md) running on port 8765. To connect to the Embedded UI, you can set up SSH tunneling. For this, execute the command `ssh -L 8765:localhost:8765 -i <ssh private key> <user>@<first-ydb-static-node-ip>` on your local machine. After successfully establishing the connection, you can navigate to the URL [localhost:8765](http://localhost:8765):
```

2024-03-07 08:09 UTC, blinkov commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
> +ydb -d /Root/database \
```suggestion
./ydb -d /Root/database \
```

2024-03-07 11:03 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +  + `system_timezone`: USA/<regioan_name>
```suggestion
  + `system_timezone`: USA/<region_name>
```

2024-03-07 11:04 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +Для других облачных провайдеров процесс настройки NTP-серверов имеет свои особенности. О том как настраивается синхронизация времени на виртуальных машинах Azure можно прочесть в [данной](https://lea
давай сделаем это табами вместо списка, а также Azure и Alibaba наравне с AWS/YC

2024-03-07 11:05 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +Для других облачных провайдеров процесс настройки NTP-серверов имеет свои особенности. О том как настраивается синхронизация времени на виртуальных машинах Azure можно прочесть в [данной](https://lea
плюс эта часть явно потерялась в английской версии — надо видимо полностью перепроверить, что языки совпадают

2024-03-10 20:16 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +Для других облачных провайдеров процесс настройки NTP-серверов имеет свои особенности. О том как настраивается синхронизация времени на виртуальных машинах Azure можно прочесть в [данной](https://lea
Сделано.

2024-03-10 21:00 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
> +Для других облачных провайдеров процесс настройки NTP-серверов имеет свои особенности. О том как настраивается синхронизация времени на виртуальных машинах Azure можно прочесть в [данной](https://lea
добавив и перепроверил.

2024-03-10 21:17 UTC, Pseudolukian commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible-install-steps.md
> +The role will install the following packages in the system: atop, bash-completion, bind9-host, ca-certificates, curl, dnsutils, gdisk, iperf, iptables, jq, logrotate, lsof, nvme-cli, procps, python3-
Дал ссылки на списки пакетов.

2024-03-10 21:25 UTC, Pseudolukian commented on ydb/docs/en/core/getting_started/_includes/ansible/ansible-install-steps.md
> +    + `assert required variables are defined` - Asserts that the number of NTP servers (`system_ntp_servers`) is more than one if the `system_ntp_servers` variable is defined.
Написал, что будет.

2024-03-11 03:21 UTC, blinkov commented on ydb/docs/en/core/toc_i.yaml
> +  - name: Deploying {{ ydb-short-name }} cluster with Ansible
```suggestion
  - name: Ansible
```

2024-03-11 07:02 UTC, fomichev3000 submitted a review, later dismissed

2024-03-11 07:03 UTC, blinkov submitted a review, later dismissed

2024-03-12 01:24 UTC, blinkov approved these changes

2024-03-12 01:24 UTC, merged