YQ-2803 Exception checking in checkpoint storages
ydb-platform/ydb pull request #1540
Opened 2024-02-02 07:28 UTC by kardymonds

### Changelog entry 

### Changelog category 
* Not for changelog (changelog entry is not required)

### Additional information

2024-02-02 15:31 UTC, uzhastik requested changes

2024-02-05 06:10 UTC, kardymonds commented on ydb/core/fq/libs/ydb/ydb.cpp
> +                issues.AddIssue(CurrentExceptionMessage());
Added text "StatusToIssues failed"

2024-02-05 06:10 UTC, kardymonds commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +            try {
ok, used

2024-02-05 06:10 UTC, kardymonds commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +                    return TCreateCheckpointResult(TString(), std::move(issues));
ok, fixed

2024-02-05 14:30 UTC, uzhastik commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +            return std::make_pair(std::move(result->Size), std::move(future.GetValue()));
везде вместо GetValue предлагают использовать ExtractValue, чтобы делался мув и не было копий

2024-02-06 05:29 UTC, kardymonds commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +            return std::make_pair(std::move(result->Size), std::move(future.GetValue()));
У Apply() сигнатура должна быть ...(const TFuture<T>&>()) ([future.h](https://github.com/ydb-platform/ydb/blob/main/library/cpp/threading/future/core/future.h#L56)), а  ExtractValue не констатная. Поэтому так не получается

2024-02-07 08:38 UTC, uzhastik commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +            return std::make_pair(std::move(result->Size), std::move(future.GetValue()));
тогда давай убирать бесполезные std::move. в этой строке их две штуки, как я понимаю

2024-02-07 08:38 UTC, uzhastik commented on ydb/core/fq/libs/ydb/ut/ydb_ut.cpp
> +};
; лишняя

2024-02-07 14:10 UTC, kardymonds commented on ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
> +            return std::make_pair(std::move(result->Size), std::move(future.GetValue()));
Убрал лишние std::move

2024-02-07 14:27 UTC, uzhastik approved these changes

2024-02-08 04:57 UTC, merged