YQ-2549 Move yds integration tests to github
ydb-platform/ydb pull request #1592
Opened 2024-02-05 14:01 UTC by kardymonds

### Changelog entry 

...

### Changelog category 
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-02-06 07:36 UTC, kardymonds commented on ydb/tests/fq/kikimr/test_recovery_match_recognize.py
> +#!/usr/bin/env python
From https://a.yandex-team.ru/arcadia/kikimr/yq/tests/kikimr/test_recovery_match_recognize.py

2024-02-06 07:36 UTC, kardymonds commented on ydb/tests/fq/kikimr/test_recovery_mz.py
> +#!/usr/bin/env python
From https://a.yandex-team.ru/arcadia/kikimr/yq/tests/kikimr/test_recovery_mz.py

2024-02-06 10:23 UTC, kardymonds commented on ydb/tests/fq/kikimr/test_recovery.py
> +#!/usr/bin/env python
From https://a.yandex-team.ru/arcadia/kikimr/yq/tests/kikimr/test_recovery.py

2024-02-06 11:40 UTC, uzhastik requested changes

2024-02-06 11:40 UTC, uzhastik commented on ydb/tests/fq/ya.make
> +    kikimr
давайте как-нибудь поприятнее назовем папку

2024-02-06 13:09 UTC, kardymonds commented on ydb/tests/fq/ya.make
> +    kikimr
moved to yds/

2024-02-07 08:40 UTC, uzhastik approved these changes

2024-02-07 10:34 UTC, merged