YQL-17425 parallel for
ydb-platform/ydb pull request #1650
Opened 2024-02-06 21:35 UTC by vitstn

- Last 25 queries of TPC-DS (#668)
- YQ-2628: add connections option for streaming queries (#579)
- KIKIMR-19521 BTreeIndex Bugfix index size (#671)
- WriteRow out of space (#665)
- YQL-17087: Add channel spilling to dq pipe communication (#612)
- KIKIMR-20521: Add UseVDisksBalancing feature flag (#523)
- KIKIMR-20522: Tests for vdisks balancing (#531)
- Library import 2 (#639)
- Revert "Workload TPC-C init" (#529)
- Consistent debug (#652)
- YQL-17250: Add operation name in fallback message (#627)
- Moved TSpan::Link(TraceId) implementation to .cpp (#674)
- [yql] Fix result diff in dq_file tests (YQL-17386, YQL-17404, YQL-17402, YQL-17405) (#676)
- Add BsCostTracker and advanced cost metrics, KIKIMR-17759 (#600)
- Import libs 3 (#679)
- added tests (#647)
- Refactoring - optimize parameters of CreatePartitionWriter (#669)
- YQL-15941 avoid llvm version pinning where possible (#677)
- Ignore empty metrics in in-progress stats. Try-catch in-progress stats conversion. (#633)
- KIKIMR-19521 BTreeIndex Fix SchemeShard Verify (#655)
- CREATE / DROP VIEW queries support (#656)
- Mute postgresql* tests (#675)
- KIKIMR-20042 Fix of TSpan abort outside of actor system (#630)
- [YQL-17338] disable cast warning from integral types to float types (#690)
- Fix constrains after expand PartitionsByKeys. (#685)
- KIKIMR-20533 Forward traceparent header to KV-tablet (#689)
- Add TPC-DS Q56 (#692)
- YQ-2628: Print stats on final status log (#563)
- get status polling has been fixed YQ-2667 (#620)
- YDB_ACCESSORs (#672)
- Remove TabletId from TValidatedDataTx (#683)
- Removed useless includes (#621)
- YQ-2560: add YDB data_source (#693)
- YQL-9517: RPC Arrow reader YT column converters (#599)
- [yql] gateway extension contains only additional settings (#700)
- Update cost model (#697)
- Use Source Name as name, drop unused index (#701)
- Revert "KIKIMR-20522: Tests for vdisks balancing (#531)" (#706)
- Refuse empty query text (#708)
- KIKIMR-19671 Add RemovePathRecursive function (#680)
- buffered writing for columnshards (#686)
- KIKIMR-20042 Partially implemented PDisk tracing (#574)
- Rename op -> writeOp (#715)
- KIKIMR-19522 BTreeIndex Precharge Simplification (#682)
- YQL-15941 no_llvm versions of purecalc and embedded (#707)
- YQ-2670 switch generic tests to docker compose (#691)
- Start tablets in object domain KIKIMR-20271 (#705)
- KIKIMR-20150: fix and improve flaky test (#713)
- ActorSystem fix typo (#638)
- KQP computation pattern cache serialized program (#634)
- ActorSystem should continue use std atomic (#643)
- ActorSystem memlog use std atomic (#644)
- ActorSystem interrupter use std atomic (#645)
- ActorSystem cpu load log use std atomic (#646)
- Add QueryService coverage for kqp_perf_ut.(KIKIMR-16294) (#721)
- fix tests TopicPeriodicStat* (#717)
- use adaptive timeouts and persistent node count in hive warmup KIKIMR-20551 (#624)
- [YQL-17103] Basic support of pg types in predicate extractor library (#709)
- Add discovery mutator for underlay (#566)
- YQ-2628: add RECURSE_FOR_TESTS (#718)
- YQ-2704 TCheckpointStorage failed on log (#594)
- Keep Issue fields after censorship (#714)
- KIKIMR-20150: remove the test from the mute list (#726)
- Ability for ydb-cli to write request results as arrow parquet (#673)
- YQL-17385 fix tests (#730)
- (refactoring) Inline TChangeRecordBuilder's methods (#734)
- fix broken pg autoparam unit test
- remove a hard error in formatter when CASE wih no ELSE (#723)
- fix (#736)
- fix tests (#735)
- Add PG provider to pgrun (#732)
- use statistics aggregator for basic statistics KIKIMR-18323 (#623)
- YQL-17286: Fix sublink in projection, which has no external deps (#684)
- init (#738)
- generic query for load actor (#512)
- Switch ticket_parser auth clients to HTSwap mailbox type (#670)
- Remove msgbus trace service (deprecated and unused) (#687)
- Remove node identifier (deprecated) (#688)
- Session actor perf (#724)
- YDB-2345 HC time difference message (#741)
- YQ-2651 use ChildPtr instead of ChildRef (#488)
- ut_read_iterator + EvWrite (#742)
- Fixed TItem in-place creation under clang14 (#752)
- Common TChangeRecord in ydb/core/change_exchange (#737)
- Add library increment script (#760)
- Added import s3 to directory (#678)
- Support IF NOT EXISTS/IF EXISTS for tables, external tables and external data sources (#694)
- normalize test (#759)
- Import libs 4 (#758)
- Incremented YDB CLI version to 2.8.0 (#762)
- [yt provider] Don't omit YtMerge with KeepSorted setting (YQL-17413) (#755)
- YDBDOCS-559 add parquet format to docs (#761)
- style has been fixed (#763)
- add monitoring info for tables_manager (#764)
- to change the configuration, skip the step CALCULATING (#743)
- Add ring activation queue (#695)
- Fix poller compatibility mode KIKIMR-20604 (#765)
- ci: new config for ya tests muting (#601)
- Move size checks to the parse phase (#767)
- Add TPC-DS Queries (Postgres variant) (#771)
- YQL-17087. Fix work with actor system in case of async compute actors. (#757)
- Implement double/int -> pg numeric conversion YQL-16767 (#727)
- YQ Connector: YQ-2323: remove Golang implementaion from YDB (#772)
- Untie Keep/DoNotKeep flags from blackboard KIKIMR-20527 (#773)
- graph backend KIKIMR-18277 (#745)
- Predictable test: order select result YQL-17397 (#776)
- [yql] Fix query cache for UDFs (YQL-17478) (#778)
- KIKIMR-20522: Tests for vdisks balancing 2 (#751)
- Revert "Session actor perf (#724)" (#782)
- Enable APPLE_LOCAL_SDK, disable USE_OPENSOURCE_TEST_TOOL (#777)
- [hybrid] Substitute prev operation tables in peephole. Move FillSecureParams after peephole (YQL-17473) (#769)
- EvWrite locks (#774)
- Fix missed root/ya on library import (#784)
- unused-but-set-variable fix (#789)
- Russian translation for GitHub dev docs (#790)
- Introduce strategy test KIKIMR-20527 (#779)
- Revert "KQP computation pattern cache serialized program (#634)" (#750)
- self holder has been added YQ-2588 (#783)
- Use optimize_for = CODE_SIZE in sql protobuf (#794)
- Fail when reading parquets with complex types (#785)
- Predictable test: order dicts YQL-17384 (#793)
- Sys view full for columnshards (#786)
- Add docs for fluent-bit (#541)
- Do not skip index update if index has non equatable types as data column. (#787)
- Sync config documentation with implementation (#797)
- Enhance monitoring for serverless tenants in Hive KIKIMR-19289 (#710)
- Add feature flag for exclusive dynamic nodes KIKIMR-20562 (#748)
- Add default copy assignment operator (#733)
- LOGBROKER-8840: add CreateTopics endpoint to KafkaAPI (#747)
- Better test result normalization YQL-17397 (#804)
- Exclude google.proto.Struct from validator (#800)
- additional memory monitoring (#798)
- YQL-16218 fix SqlIn for tuples (#801)
- YDB-2101 storage handler added check usage when out-of-space filter (#658)
- Prepare Development section for override in customized docs (#814)
- symlinks (#816)
- KIKIMR-19522 BTreeIndex Precharge RowId (#754)
- YQL-17485 initial version of splitter for generated pb files from grammar (#791)
- fix DqReplicate expansion (#818)
- KIKIMR-20597 Implemented tvm authentication for wilson uploader (#768)
- [cfg-test] Move experimental features to separate config (YQL-17455) (#805)
- statistic requests fix (#813)
- fix tests (#820)
- Implement returning list for KiWrite/UpdateTable KIKIMR-18531
- KIKIMR-20530 Datashard tracing enhancements (#746)
- ci: warn if no tests reports found (#807)
- Added stage and local inputs for JSON plans (#699)
- Fix rebase in docs (#825)
- Fix literal rewrite rule for predicate pushdown (#809)
- Fix OLAP stats (#766)
- KIKIMR-20380: min max portion keys validation (#822)
- add compatibility for old upsert nodes (#826)
- fix http tests to wait for port binding (#835)
- [YQL-17389] Normalize dq_file tests
- add pg types to TQueryPlan (#828)
- improve normalization (#827)
- YDB-1713/hotkeys (#830)
- suppress unnecessaryVERIFY which could rise on downgrade scenario (#840)
- Remove deps on non existing folder (#844)
- YQL-16896 [...]

2024-02-07 14:23 UTC, rvu1024 requested changes
Не хватате документации

2024-02-07 14:23 UTC, rvu1024 commented on ydb/library/yql/core/services/yql_eval_expr.cpp
> +                        types.EvaluateParallelForLimit << ", got: " << itemsCount));
`limit` вместо `types.EvaluateParallelForLimit`?

2024-02-07 14:27 UTC, vitstn commented on ydb/library/yql/core/services/yql_eval_expr.cpp
> +                        types.EvaluateParallelForLimit << ", got: " << itemsCount));
это другое место кода, про раскрытие subquery - они всегда в ширину, тут используется другой лимит.

переменной limit тут нет

2024-02-07 18:15 UTC, nepal requested changes

2024-02-07 19:50 UTC, vitstn commented
> Не хватает документации

я всегда делаю ее в отдельном PR, т.к. она под другими набором людей для проверки

2024-02-07 20:45 UTC, nepal approved these changes

2024-02-08 11:35 UTC, rvu1024 approved these changes

2024-02-08 11:35 UTC, merged