EvWrite Prepare
ydb-platform/ydb pull request #1658
Opened 2024-02-07 10:55 UTC by azevaykin

### Changelog entry 

Prepared EvWrite with a coordinator

### Changelog category 

* Experimental feature

### Additional information

...

2024-02-07 13:34 UTC, snaury requested changes

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/datashard_ut_write.cpp
> +    const TString etalonTableState3 = "key = 0, value = 1\nkey = 2, value = 3\nkey = 4, value = 5\n";
Не надо русской транслитерации. Назови "expectedTableState".

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +        KqpLocks = std::make_unique<NKikimrDataEvents::TKqpLocks>(record.GetLocks());
А зачем здесь дополнительная аллокация? Его ведь не надо потом никуда переносить с изменением владельца? Думаю будет лучше сделать это std::optional полем.

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +            }
Конец if'а куда-то улетел по пробелам.

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/finalize_plan_tx_unit.cpp
> +        if (auto dataTx = tx->GetDataTx()) {
Мелкое: тут возникает лишний плюс/минус к рефкаунту, возьми ссылку вместо копии по значению.

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/operation.h
> +};
А зачем здесь перевод строки, который отличается от других тегов ниже?

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +    TIntrusivePtr<TEventSerializedData> buffer = new TEventSerializedData(txBody, {});
Тут кажется есть проблема. Я перепроверил, и в зависимости от того есть Payload или нет, в TSerializationInfo будет выставлен (или нет) флаг IsExtendedFormat. Здесь ты конструируешь TEventSerializedData всегда в старом формате без payload'ов, соответственно после десериализации никаких payload'ов не будет и протобуф скорее всего даже не распарсится.

2024-02-07 13:34 UTC, snaury commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +    Ev.Reset(static_cast<NActors::TEventHandle<NKikimr::NEvents::TDataEvents::TEvWrite>*>(new IEventHandle(NEvents::TDataEvents::EvWrite, 0, {}, GetTarget(), buffer, GetCookie(), nullptr, GetTraceId(
Кстати, а если у нас Sender/Cookie кладутся в Target/Cookie, то зачем нам вообще TEventHandle долго хранить?

2024-02-07 14:23 UTC, azevaykin commented on ydb/core/tx/datashard/ut_common/datashard_ut_common.h
> +void SendPlanStep(Tests::TServer::TPtr server, ui64 tabletId, ui64 stepId, ui64 txId);
нужно использовать TEvProposeTransaction  из ydb/core/tx/tx.h

2024-02-08 06:07 UTC, azevaykin commented on ydb/core/tx/datashard/finalize_plan_write_unit.cpp
> +class TFinalizeWriteTxPlanUnit: public TExecutionUnit {
Удалил в a3bedff8de919257ddc3bb459ddaf60e4f395192

2024-02-08 06:43 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +        KqpLocks = std::make_unique<NKikimrDataEvents::TKqpLocks>(record.GetLocks());
5e880de6d2940fbdffd0c1a3838d77b8ef734a46

2024-02-08 07:38 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +    TIntrusivePtr<TEventSerializedData> buffer = new TEventSerializedData(txBody, {});
bb04d4687b16bca91e89972383cb70dce15c7ebf

Добавил флаг IsExtendedFormat.

Попробовал отключать DataTxCache, исполнение сюда заходит, десериализация проходит успешно.

2024-02-08 08:19 UTC, azevaykin commented
Нужно реализовать метод TWriteOperation::OnStopping по аналогии с TActiveTransaction

https://github.com/ydb-platform/ydb/pull/1680

Для распределенных транзакций EvWrite пока не слать уведомление TEvProposeTransactionRestart


И тут не нужно слать TEvProposeTransactionRestart отправляется для EvWrite

https://github.com/ydb-platform/ydb/blob/bb04d4687b16bca91e89972383cb70dce15c7ebf/ydb/core/tx/datashard/datashard_pipeline.cpp#L1180

2024-02-09 09:02 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +    TIntrusivePtr<TEventSerializedData> buffer = new TEventSerializedData(txBody, {});
Сделал передачу IsExtendedFormat через отдельный protobuf
692ee68cf5870db4e7becfa4c5d850f859737af1

2024-02-09 09:04 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_write_operation.cpp
> +    Ev.Reset(static_cast<NActors::TEventHandle<NKikimr::NEvents::TDataEvents::TEvWrite>*>(new IEventHandle(NEvents::TDataEvents::EvWrite, 0, {}, GetTarget(), buffer, GetCookie(), nullptr, GetTraceId(
c26f0a5b4041b6f7691f4fc48b39f6b5b81d11c3

Храню теперь std::unique_ptr<NEvents::TDataEvents::TEvWrite>

2024-02-09 10:25 UTC, snaury commented on ydb/core/protos/tx_datashard.proto
> +    optional string TxBody = 1;
В протобуфе string это utf8, ты наверное хотел bytes. По названию наверное EventData лучше подойдёт.

2024-02-09 10:38 UTC, azevaykin commented on ydb/core/protos/tx_datashard.proto
> +    optional string TxBody = 1;
21304f2f7fa5a243b8a8ba0f4a3c213d2641e6ea

2024-02-09 10:44 UTC, azevaykin commented on ydb/core/protos/tx_datashard.proto
> +    optional string TxBody = 1;
Также переименовал сообщение в TSerializedEvent

2024-02-09 11:02 UTC, azevaykin commented on ydb/core/tx/datashard/ut_common/datashard_ut_common.h
> +void SendPlanStep(Tests::TServer::TPtr server, ui64 tabletId, ui64 stepId, ui64 txId);
720e6eccb8ee396239747f163ae19fd76d25aca3

2024-02-09 11:02 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_ut_write.cpp
> +            SendPlanStep(server, shard, stepId, txId);
720e6eccb8ee396239747f163ae19fd76d25aca3

2024-02-12 16:31 UTC, snaury requested changes

2024-02-12 16:31 UTC, snaury commented on ydb/core/tx/datashard/datashard_trans_queue.cpp
> +                static_cast<TOperation::TPtr>(MakeIntrusive<TWriteOperation>(info, Self->TabletID())) :
А что такое `static_cast` в intrusive ptr? На вид что-то очень странное, если честно. Я бы предложил это в какой-то отдельный метод вынести, со switch'ем.

2024-02-13 08:08 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_trans_queue.cpp
> +                static_cast<TOperation::TPtr>(MakeIntrusive<TWriteOperation>(info, Self->TabletID())) :
ab9f41549e715af6687f184ae29b54ff708534e6

2024-02-13 08:09 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_pipeline.cpp
> +        TValidatedDataTx::TPtr dataTx = std::dynamic_pointer_cast<TValidatedDataTx>(baseTx);
10149496a4fea262524e858e8506bd2b924713ec

2024-02-13 08:09 UTC, azevaykin commented on ydb/core/tx/datashard/datashard_kqp.cpp
> +    const NKikimrDataEvents::TKqpLocks* kqpLocks, const NKqp::TKqpTasksRunner* tasksRunner, ui64 tabletId)
1eb47f8c526fa2ef07a91cc470abcd1e7a3db5af

2024-02-13 08:09 UTC, azevaykin commented on ydb/core/tx/datashard/complete_data_tx_unit.cpp
> +    Y_VERIFY_S(tx || writeOp, "cannot cast operation of kind " << op->GetKind());
cf14a70dbb15c6db659befebc91a4f5efb5721a5

2024-02-13 08:31 UTC, snaury commented on ydb/core/tx/datashard/write_unit.cpp
> +        ctx.Send(op->GetTarget(), writeOp->ReleaseWriteResult().release(), 0, op->GetCookie());
Проверь, что в случае immediate write в finish propose не отправляется второй ответ?

2024-02-13 08:33 UTC, snaury commented on ydb/core/tx/datashard/complete_data_tx_unit.cpp
> +                DataShard.SendResult(ctx, result, op->GetTarget(), op->GetStep(), op->GetTxId());
У нас ответ на распределённую транзакцию отдаётся отсюда, и обрати внимание что происходит это через SendResult (там есть дополнительная логика про волатильные коммиты).

2024-02-13 13:10 UTC, azevaykin commented on ydb/core/tx/datashard/write_unit.cpp
> +        ctx.Send(op->GetTarget(), writeOp->ReleaseWriteResult().release(), 0, op->GetCookie());
5f7fab936605fe842638da6d143769b43484d0ff

2024-02-14 08:15 UTC, snaury requested changes

2024-02-14 08:15 UTC, snaury commented on ydb/core/tx/datashard/datashard__write.cpp
> +TOperation::TPtr EvWrite::Convertor::MakeOperation(EOperationKind kind, const TBasicOpInfo& info, ui64 tabletId) {
А что такое EvWrite и Convertor? Если неймспейс, то должен начинаться на N, если класс, то на T.

2024-02-14 08:37 UTC, azevaykin commented on ydb/core/tx/datashard/complete_write_unit.cpp
> +    TOutputOpData::TResultPtr &result = op->Result();
2991ba6cbd8277cc3a2de97560aa4d298768ddf4

2024-02-14 08:44 UTC, azevaykin commented on ydb/core/tx/datashard/datashard__write.cpp
> +TOperation::TPtr EvWrite::Convertor::MakeOperation(EOperationKind kind, const TBasicOpInfo& info, ui64 tabletId) {
46b95e4c392443ebb22e91735cfc3f0b5e020f9b

2024-02-14 08:57 UTC, snaury approved these changes

2024-02-14 10:56 UTC, merged