Refactor config transformations
ydb-platform/ydb pull request #1787
Opened 2024-02-11 17:53 UTC by Enjection

### Changelog entry 

- reimplement config transformations
- add some ut

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-02-12 15:36 UTC, CyberROFL requested changes

2024-02-12 15:36 UTC, CyberROFL commented on ydb/library/yaml_config/deprecated/yaml_config_parser.cpp
Это похоже на простое перемещение, но отображается как добавление файла.
Если действительно имеет место быть перемещение, то можно сделать это предварительно в отдельном pr (без изменений в коде).

2024-02-12 15:37 UTC, CyberROFL commented
Рекомендуется разбить на несколько герметичных pr:
- Перемещение в deprecated.
- Вынос в отдельные файлы часте конфига.
- Собственно само изменение.
- etc.

2024-02-12 15:39 UTC, CyberROFL commented on ydb/library/yaml_config/deprecated/yaml_config_parser.h
> +#include <ydb/core/protos/config.pb.h>
Тут вообще ад.

2024-02-13 12:53 UTC, Enjection commented on ydb/library/yaml_config/serde.cpp
serialize_deserialize, поправил

2024-02-13 12:53 UTC, Enjection commented on ydb/library/yaml_config/deprecated/yaml_config_parser.cpp
Поправил отдельным пуллриком

2024-02-13 12:53 UTC, Enjection commented on ydb/library/yaml_config/tools/dump_ds_init/main.cpp
> +#include <ydb/library/yaml_config/deprecated/yaml_config_parser.h>
Прошёлся там где меняю -- поправил

2024-02-13 12:56 UTC, Enjection commented on ydb/library/yaml_config/tools/dump_ds_init/main.cpp
> +    if (argc == 2 && TString("--deprecated") == argv[1]) {
Не вижу смысла тащить для микро-утилиты. Других опций не будет никогда, эту тоже потом уберём после обкатки нового парсера. Фактически сейчас это тулинг для нахождения возможных расхождений.

2024-02-13 13:21 UTC, CyberROFL requested changes

2024-02-13 13:21 UTC, CyberROFL commented on ydb/library/yaml_config/ut_transform/test_transform.py
> +        return results
Эта функция повторяется много раз, отличается только `--deprecated` и  `suffix=".ds_init"`. Нельзя избавиться от копи-пасты?

2024-02-13 13:21 UTC, CyberROFL commented on ydb/library/yaml_config/yaml_config_parser.cpp
> +            {"FlatHive", 1},
В этом файле много таких констант. Можно их поместить повыше/в отдельный файл и сделать статическими?

2024-02-13 13:26 UTC, Enjection commented on ydb/library/yaml_config/ut_transform/test_transform.py
> +        return results
По-идее pytest тесты можно параметризировать, но я не помню как. Потом разберусь и поправлю. В отдельных тестах оно по двум причинам - ограничение по времени исполнения теста и отдельная canondata

2024-02-13 18:46 UTC, CyberROFL approved these changes, later dismissed

2024-02-13 18:46 UTC, CyberROFL commented on ydb/library/yaml_config/core_constants.h
> +    std::pair{TString{"IoExecutor"}, TString{"IO"}},
Можно явно не специфицировать `std::pair`.

2024-02-13 18:46 UTC, CyberROFL commented on ydb/library/yaml_config/core_constants.h
> +constexpr inline TStringBuf DEFAULT_ROOT_USERNAME = "root";
inline-константы... ну, такое.

2024-02-13 18:59 UTC, Enjection commented on ydb/library/yaml_config/core_constants.h
> +constexpr inline TStringBuf DEFAULT_ROOT_USERNAME = "root";
constexpr же implicitly inline, разве нет?

2024-02-14 07:45 UTC, shmel1k approved these changes

2024-02-14 07:50 UTC, merged