YQ-2549 Checkpointing in match_recognize
ydb-platform/ydb pull request #1860
Opened 2024-02-12 15:51 UTC by kardymonds

### Changelog entry 

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-02-15 09:58 UTC, uzhastik requested changes

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
> +        {
скобочку открываем на той же строке, где слово if

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
> +
лишняя пустая строка в начале двух методов Load

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
> +                (pair.first)->second->Load(serializer);
(pair.first) - зачем тут скобки?

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
> +            for (size_t i = 0; i < partitionsSize; ++i) {
предлагаю сделать Partitions.reserve(partitionsSize)
переменную partitionsSize предлагаю переименовать в partitionsCount

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
> +        TOutputSerializer serializer(SerializerContext);
давай напишем коммент почему поле HasReadyOutput не упаковывается. я так понимаю, что его содержимое выводится из Partitions и контейнер выполняет роль кеша

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_list.h
> +            for (size_t i = 0; i < size; ++i) {
предлагаю сделать Storage.reserve(....)

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +                else
давай везде использовать фигурные скобки

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +                }
else пишем на той же строке, где и закрывающая фигурная скобка

2024-02-15 09:58 UTC, uzhastik commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_save_load.h
> +    {
скобку надо поднять выше и const по возможности навесить

2024-02-19 13:37 UTC, zverevgeny commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +    using TTransitions = std::vector<TNfaTransition, TMKQLAllocator<TNfaTransition>>;
Граф переходов - это статическая когфигурация, которая строится по SQL запросу. Его нет большого смысла сохранять. Нужно ли уметь проверять, что он не изменился при перезапуске

2024-02-20 08:53 UTC, kardymonds commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +    using TTransitions = std::vector<TNfaTransition, TMKQLAllocator<TNfaTransition>>;
Я не понял лучше что делать: 
- граф переходов не сохранять и строить заново при восстановлении,
- сохранять/восстанавливать и проверять что он не изменился при перезапуске (видимо сравнить восстановленный и заново построенный?).
Или что-то другое имелось ввиду?

2024-02-21 08:01 UTC, zverevgeny commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +    using TTransitions = std::vector<TNfaTransition, TMKQLAllocator<TNfaTransition>>;
Пожалуй, на данном этапе будет лучше сохранять и при восстановлении сравнивать, что он не отличается от заново построенного

2024-02-21 14:15 UTC, kardymonds commented on ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
> +    using TTransitions = std::vector<TNfaTransition, TMKQLAllocator<TNfaTransition>>;
Добавил проверку - сохраняю TNfaTransitionGraph один раз (в TStateForInterleavedPartitions), при ресторе проверяю что не изменилось.

2024-03-04 10:49 UTC, uzhastik approved these changes

2024-03-04 12:28 UTC, zverevgeny approved these changes

2024-03-04 12:28 UTC, merged