Wilson parallel upload
ydb-platform/ydb pull request #1875
Opened 2024-02-13 06:44 UTC by domwst

### Implemented parallel upload in wilson

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-02-14 09:19 UTC, domwst commented on ydb/library/actors/wilson/wilson_uploader.cpp
> +                if (Spans.empty()) {
Should we also limit upload parallelism?

2024-02-20 09:03 UTC, alexvru requested changes

2024-02-20 09:03 UTC, alexvru commented on ydb/library/actors/wilson/wilson_uploader.cpp
> +                    ScheduleWakeup(TDuration::MilliSeconds(100));
by the way, how will this work with a big rate of spans?
may be we need to run another thread polling CQ and sending messages to the uploader?

2024-02-20 09:03 UTC, alexvru commented on ydb/library/actors/wilson/wilson_uploader.cpp
> +                    auto node = static_cast<TExportRequestData*>(tag);
smart pointer

2024-02-20 09:04 UTC, domwst commented on ydb/core/protos/config.proto
> +        // maximum batch export requests being run simultaneously
In requests. Each request exports one batch

2024-02-20 12:08 UTC, domwst commented on ydb/core/protos/config.proto
> +        // maximum batch export requests being run simultaneously
Renamed to MaxExportRequestsInflight

2024-02-20 12:09 UTC, domwst commented on ydb/library/actors/wilson/wilson_uploader.cpp
> +                    ALOG_WARN(WILSON_SERVICE_ID, "max_span_export_inflight should be greater than 0, channing to 1");
Fixed

2024-02-20 14:01 UTC, alexvru approved these changes

2024-02-20 14:02 UTC, merged