Add docs for YDB Federated Query + Connector deployment
ydb-platform/ydb pull request #1895
Opened 2024-02-13 15:30 UTC by vitalyisaev2

### Changelog entry 

* Add docs for YDB Federated Query + Connector deployment

### Changelog category 

* Documentation (changelog entry is not required)

2024-02-13 15:35 UTC, SloNN commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
а зачем ты в концепциях сразу пишешь про дополнительный сервис, это не деталь реализации? в концепциях были основные определения, тут не про администрирование

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +Для организации шифрованных соединений между YDB и `fq-connector-go` создайте пару TLS-ключей и примонтируйте папку с ключами в контейнер, а также включите соответствующие настройки в секции конфигур
как создать?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +В случае, если внешние источники данных используют TLS-шифрование, причем TLS-ключи для них выпущены Certificate Authority, не входящим в перечень доверенных, необходимо добавить корневой сертификат
как проверить, что они не доверенны?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +  log_level: DEBUG
по умолчанию нужно, чтобы пользователи DEBUG включали?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +| `pprof_server` | Опциональная секция. Заполняется, если требуется запуск встроенного профилировщика Go. |
зачем мне это?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +| `paging.bytes_per_page` | Количество байт в одном блоке. |
есть какие-то рекомендации?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +    image: ghcr.io/ydb-platform/local-ydb:nightly
мне нужно взять ночную сборку?

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +CREATE OBJECT pg_local_password (TYPE SECRET) WITH (value = password);
стоит дописать, что это пароль из PG

2024-02-13 15:40 UTC, SloNN commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +О дополнительных опциях запуска коннектора можно узнать [здесь](../../../deploy/federated_query/connector.md#fq-connector-go-launch). В качестве внешнего источника данных можно использовать любое хра
можно узнать не "здесь", а в "инструкции по запуску чего-то" или "расширенных настройках".

2024-02-14 10:42 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
Перенёс эту информацию в отдельный файл в этом же разделе. Этот файл вернул в исходное состояние.

2024-02-14 10:46 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +Для запуска `fq-connector-go` используйте официальный [Docker-образ](https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go). Подготовьте конфигурационный файл [по образцу]({#
Есть готовый, просто он не совсем production-ready (там нет TLS). Но на всякий случай дополнил эту инструкций примером, когда контейнер запускается с дефолтным конфигом - чтобы всё работало из коробки.

2024-02-14 10:49 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +Для организации шифрованных соединений между YDB и `fq-connector-go` создайте пару TLS-ключей и примонтируйте папку с ключами в контейнер, а также включите соответствующие настройки в секции конфигур
Добавил ссылку на https://ydb.tech/docs/ru/deploy/manual/deploy-ydb-on-premises#tls-certificates. Справедливости ради, даже там нет ответа на вопрос "как создать", даются только характеристики того, что именно надо создать. Думаю, что расчёт идёт на то, что пользователь совсем уж базовые вещи сможет сделать сам.

2024-02-14 10:50 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +  log_level: DEBUG
поменял на INFO

2024-02-14 10:50 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +| `pprof_server` | Опциональная секция. Заполняется, если требуется запуск встроенного профилировщика Go. |
убрал

2024-02-14 10:50 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/federated_query/connector.md
> +| `paging.bytes_per_page` | Количество байт в одном блоке. |
Да, добавил

2024-02-14 10:51 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +    image: ghcr.io/ydb-platform/local-ydb:nightly
На данный момент - да, именно так. У нас с образами пока что зоопарк.

2024-02-14 10:51 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +CREATE OBJECT pg_local_password (TYPE SECRET) WITH (value = password);
прокомментировал все аргументы команды

2024-02-14 10:51 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +О дополнительных опциях запуска коннектора можно узнать [здесь](../../../deploy/federated_query/connector.md#fq-connector-go-launch). В качестве внешнего источника данных можно использовать любое хра
сделал

2024-02-14 11:48 UTC, SloNN commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
посмотрел другие документы в разделе "концепции", там нигде нет архитектуры. а почему ты именно в этот раздел хочешь про архитектуру дописать?

2024-02-14 14:56 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
Потому что на [главной странице](https://ydb.tech/docs/ru/) с документацией именно раздел "Концепции" позиционируется как место, где можно узнать о том, "как устроена YDB". Ни одного другого более подходящего раздела я не вижу. Конфигурация? нет, эти чисто концептуальные картинки не про конфигурацию. Обслуживание? тоже нет, или только отчасти. Мониторинг? Точно нет.

Может быть, есть раздел про архитектуру YDB, но он глубоко запрятан - найти его не смог.

2024-02-14 15:00 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
Могу сюда перенести https://ydb.tech/docs/ru/concepts/cluster/

2024-02-16 07:29 UTC, blinkov requested changes

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `metrics_server` | Опциональная секция. Заполняется, если требуется выгрузка статистики сервиса через отдельный сервис. |
не очевидно что в данном контексте значат оба слова «сервис»: вероятно первое вероятно сам коннектор, а второй — какой-то внешний мониторинг?

если так, то первое заменить на коннектор, а второе где-то отдельно описать и отсюда дать ссылку

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `metrics_server.endpoint.host` | Сетевой интерфейс, на котором запускается слушающий сокет сервера статистики. |
По идее сетевой интерфейс — эт то, что `ifconfig` выдаёт, т.е. `lo`, `eth0` и т.п. А тут видимо хостнейм или ip указывается?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `paging.bytes_per_page` | Количество байт в одном блоке. Рекомендуемые значения - от 4 до 8 МиБ, максимальное значение - 48 МиБ. |
вероятно не просто количество, а максимальное количество? или оно и правда мусором добивает до этого размера?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `paging.prefetch_queue_capacity` | Количество заранее вычитываемых блоков данных, которые хранятся в адресном пространстве коннектора до обращения YDB за очередным блоком данных. В некоторых сценар
про потребление памяти возможно стоит отдельно написать, т.к. предыдущая настройка на него тоже явно влияет + не понятно от чего зависит количество этих очередей (она всегда одна глобальная, или может на каждый запрос, источник или обращающийся к коннектору сервер YDB)

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +Мы будем исходить из того, что процесс {{ ydb-short-name }}, опционально разворачиваемый коннектор и внешний источник данных размещены на разных физических или виртуальных серверах (в том числе в кон
убрать «мы» + из этой формулировки не понятно обязательно ли нужны дополнительные серверы, а также как вообще рекомендуется делать

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +1. Выполните шаги инструкции по развертыванию {{ ydb-short-name }} до [подготовки конфигурационных файлов](./deploy-ydb-on-premises.md#config) включительно.
дописать что делать при развёртывании не вручную, а через k8s и ansible

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                use_ssl: true             # флаг, включающий шифрование соединений
файлик с CA наверное ещё надо куда-то указать?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                  value: "true"
если мы рекомендуем так делать, то лучше это всё сделать дефолтами, а не заставлять копипастить большой конфиг

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развёрнут коннектор
как указать несколько, если хочется больше одного для отказоустойчивости?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развёрнут коннектор
как указать, если для разных источников нужно ходить в разные коннекторы?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +        enable_external_data_sources: true
если это ещё не production ready фича, то добавить в начало всех страниц плашку с предупреждением про это

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +1. Продолжайте развертывание {{ ydb-short-name }} по [инструкции](./deploy-ydb-federated-query.md).
ссылка как-будто на эту же страницу ведёт?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-on-premises.md
> +Описанная выше процедура установки предусматривает развертывание {{ ydb-short-name }} в стандартном защищенном режиме.
какая-то оффтопная правка

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +В данном разделе мы рассмотрим пример тестовой инсталляции {{ ydb-full-name }}, сконфигурированной для выполнения [федеративных запросов](../../../concepts/federated_query/index.md) к внешним источни
выпилить «мы»

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. Откройте в браузере [страницу](http://localhost:8765/monitoring/tenant?schema=%2Flocal&name=%2Flocal) с веб-интерфейсом базы данных `/local` локально развёрнутого инстанса {{ ydb-short-name }}. В
этот пункт не сложится, если запускать докер не на ноутбуке, а где-то на удалённом сервере — явно расписать что делать в обоих случаях

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +        LOCATION="fq-example-postgresql:5432",      # сетевой адрес источника (в данном случае соответствует имени контейнера)
а там не хостнейм должен быть? с чего такое название зарезолвится правильно?

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL Script` и нажмите кнопку `Run`. Запрос должен завершиться успешно.
возможно стоит подсказать как аналогичные этому селектору манипуляции делать хотя б в CLI

2024-02-16 07:29 UTC, blinkov commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL - QueryService` и нажмите кнопку `Run`. На экране появятся данные таблицы, созданной во внешнем источнике несколькими шагами ран
как-будто недописанным выглядит — как минимум сказать что в итоге получается и что с такой конструкцией делать дальше

также можно добавить пример по-сложнее и сказать пару слов про то, как оно работает, например, в `select sum(col2) from example where id < 5` — кто будет делать фильтрацию и суммирование, YDB или PostgreSQL?

2024-02-16 09:53 UTC, uzhastik commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL Script` и нажмите кнопку `Run`. Запрос должен завершиться успешно.
можно заметку написать, что запустить федеративный запрос через ydb cli сейчас невозможно. такая возможность появится в будущем.

2024-02-16 09:53 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между YDB и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также
тут, действительно, можно уточнить, что именно делать с ключами. важно подчеркнуть, что соединение несимметрично, то есть не просто "между YDB и коннектором", а "от YDB до коннектора". в этом случае на клиентскую сторону одни сертификаты надо класть, а на принимающую сторону (коннектор) - другие.

2024-02-16 09:53 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +1. Выполните шаги инструкции по развертыванию {{ ydb-short-name }} до [подготовки конфигурационных файлов](./deploy-ydb-on-premises.md#config) включительно.
у нас нет рецептов для k8s/ansible, только для ручной установки и именно под этот сценарий есть запросы от внешнего клиента. можно какую-то сноску на этот счет написать, например, в настоящий момент рецептов запустить коннектор в k8s/ansible нет и мы планируем добавить их в будущем.

2024-02-16 09:53 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развёрнут коннектор
это должно решаться внешними средствами, например, днс балансировкой или выделенными балансировщиками, типа NLB облака или k8s. можно это в доке написать тоже.в конфиге поддерживается только один ендпойнт

2024-02-16 09:53 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развёрнут коннектор
пока никак. это планируется сделать в будущем

2024-02-16 10:05 UTC, uzhastik requested changes

2024-02-16 10:05 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `logger.log_level` | Уровень логгирования. Допустимые значения: `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`. |
```suggestion
| `logger.log_level` | Уровень логирования. Допустимые значения: `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`. |
```

2024-02-16 10:07 UTC, uzhastik commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL - QueryService` и нажмите кнопку `Run`. На экране появятся данные таблицы, созданной во внешнем источнике несколькими шагами ран
расписывать семантику запросов в данном месте кажется неуместно

2024-02-16 11:38 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +# Aрхитектура федеративных запросов
упомянул

2024-02-16 11:42 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
Должно уметь работать с любым S3. Убрал {{objstorage-full-name}} в этом PR, другие статьи пока не трогал.

2024-02-16 11:42 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +Некоторые источники данных, такие как [S3 ({{objstorage-full-name}})](s3), поддерживаются {{ ydb-full-name }} нативно, тогда как для работы с другими (например, реляционными СУБД) потребуется примене
Спасибо, да, дописал введение.

2024-02-16 11:42 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +* Конвертация данных, извлечённых из внешних источников, в колоночное представление в формате [Arrow IPC Stream](https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-streams), поддержива
fixed

2024-02-16 11:43 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +| Источник | Поддержка |
fixed

2024-02-16 11:44 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +* PostgreSQL
поправил

2024-02-16 11:44 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для запуска коннектора используйте официальный [Docker-образ](https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go). Он уже содержит [конфигурационный файл](https://github.c
поправил

2024-02-16 11:45 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +На порту 50051 публичного сетевого интерфейса вашего хоста запустится слушающий сокет GRPC-сервиса коннектора. В дальнейшем {{ ydb-short-name }} должно будет установить соединение именно с этим сетев
поправил

2024-02-16 11:48 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Актуальный пример конфигурационного файла сервиса `fq-connector-go` можно найти в [репозитории](https://github.com/ydb-platform/fq-connector-go/blob/main/examples/config.prod.txt).
какого плана прогон ты предлагаешь? ты хочешь, чтобы пользователи видели и писали yaml конфиги, а мы перед подкладыванием своим демонам прогоняли proto2yaml ?

2024-02-16 13:25 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между YDB и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также
С нашей стороны тут обнаружился небольшой недоимплемент со стороны YDB, который  всё же трудно будет починить в рамках этого PR: https://st.yandex-team.ru/YQ-2880. Я могу предложить убрать сейчас фрагмент про настройку TLS в Коннекторе, а потом добавить её отдельным PRом.

2024-02-16 13:25 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между YDB и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также
добавил

2024-02-19 10:38 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    -v /path/to/config.txt:/usr/local/etc/fq-connector-go.conf
Переименовал.

2024-02-19 10:39 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Актуальный пример конфигурационного файла сервиса `fq-connector-go` можно найти в [репозитории](https://github.com/ydb-platform/fq-connector-go/blob/main/examples/config.prod.txt).
Добавили одновременную поддержку конфигов и в prototxt, и в yaml. Теперь везде ссылки на примеры конфигов с yaml.

2024-02-19 10:39 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `logger` | Опциональная секция. Содержит настройки логирования. |
дописал

2024-02-19 10:45 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `metrics_server` | Опциональная секция. Заполняется, если требуется выгрузка статистики сервиса через отдельный сервис. |
Да, речь о встроенном в процесс отдельном HTTP сервере на отдельном порту. С него можно забирать статистику. Но мы это умеем делать только в формате Solomon. Думаю, что документировать это не надо, так как Solomon всё равно не в OSS (?).

Поставил задачу на поддержку Prometheus https://st.yandex-team.ru/YQ-2887, секцию конфига убрал.

2024-02-19 11:46 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `metrics_server.endpoint.host` | Сетевой интерфейс, на котором запускается слушающий сокет сервера статистики. |
поправил в секции выше

2024-02-19 12:11 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `paging.bytes_per_page` | Количество байт в одном блоке. Рекомендуемые значения - от 4 до 8 МиБ, максимальное значение - 48 МиБ. |
да, максимальное, поправил

2024-02-19 12:11 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `paging.prefetch_queue_capacity` | Количество заранее вычитываемых блоков данных, которые хранятся в адресном пространстве коннектора до обращения YDB за очередным блоком данных. В некоторых сценар
Добавил деталей в ячейку с `paging`.

2024-02-19 13:59 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +Мы будем исходить из того, что процесс {{ ydb-short-name }}, опционально разворачиваемый коннектор и внешний источник данных размещены на разных физических или виртуальных серверах (в том числе в кон
Расписал варианты установки

2024-02-19 14:00 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                use_ssl: true             # флаг, включающий шифрование соединений
Будет сделано в https://st.yandex-team.ru/YQ-2880. Предлагаю документацию поправить отдельно после него.

2024-02-19 14:07 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                  value: "true"
Здесь ситуация такая:
1.  `UseNativeProtocolForClickHouse` действительно было лишним. Убрал
2.  Необходимость в указании `DateTimeFormat=string` в этом конфиге, отпадёт, как только будет сделан https://st.yandex-team.ru/YQL-16838, поэтому не хотелось бы менять в коде дефолт с тем, чтобы вскоре менять его обратно.
3. `UsePredicatePushdown` очень молодая и не слишком протестированная фича - по дефолту такие фичи отключаются. Но поскольку она очень востребованна клиентами, хочется дать им возможность на неё посмотреть.

2024-02-19 14:07 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развёрнут коннектор
дописал в примечании

2024-02-19 14:17 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +        enable_external_data_sources: true
fixed

2024-02-19 14:17 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +1. Продолжайте развертывание {{ ydb-short-name }} по [инструкции](./deploy-ydb-federated-query.md).
fixed

2024-02-19 14:19 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-on-premises.md
> +Описанная выше процедура установки предусматривает развертывание {{ ydb-short-name }} в стандартном защищенном режиме.
Вернул как было, но, кмк, нам надо опеределиться, используем мы "ё" или нет. Я сам за букву "ё", но в большинстве других мест в слове "развертывание" её не было.

2024-02-19 14:34 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +В данном разделе мы рассмотрим пример тестовой инсталляции {{ ydb-full-name }}, сконфигурированной для выполнения [федеративных запросов](../../../concepts/federated_query/index.md) к внешним источни
готово

2024-02-19 14:36 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +        LOCATION="fq-example-postgresql:5432",      # сетевой адрес источника (в данном случае соответствует имени контейнера)
Ресолвинг обеспечивается средствами Docker. И ещё я его поменял на более лаконичное `postgresql:5432`.

2024-02-19 15:00 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +1. Выполните шаги инструкции по развертыванию {{ ydb-short-name }} до [подготовки конфигурационных файлов](./deploy-ydb-on-premises.md#config) включительно.
Добавил примечание

2024-02-19 15:17 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL Script` и нажмите кнопку `Run`. Запрос должен завершиться успешно.
добавил примечание

2024-02-19 15:18 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. Откройте в браузере [страницу](http://localhost:8765/monitoring/tenant?schema=%2Flocal&name=%2Flocal) с веб-интерфейсом базы данных `/local` локально развёрнутого инстанса {{ ydb-short-name }}. В
Слегка коряво получилось, но переписал

2024-02-19 15:27 UTC, vitalyisaev2 commented on ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
> +1. В селекторе типов запросов внизу страницы выберите `Query type: YQL - QueryService` и нажмите кнопку `Run`. На экране появятся данные таблицы, созданной во внешнем источнике несколькими шагами ран
> как минимум сказать что в итоге получается и что с такой конструкцией делать дальше

Добавил небольшой абзац в конце, в котором подвёл итоги

2024-02-20 02:40 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Данная функциональность находится в режиме "Preview".
fyi мы тут вчера договорились такое называть experimental,  а не preview — но наверное потом отдельным PR всё переделаем

2024-02-20 02:41 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Коннектор `fq-connector-go` реализован на языке Go; его исходный код размещён на [Github](https://github.com/ydb-platform/fq-connector-go). Он обеспечивает доступ к следующим источникам данных:
```suggestion
Коннектор `fq-connector-go` реализован на языке Go; его исходный код размещён на [GitHub](https://github.com/ydb-platform/fq-connector-go). Он обеспечивает доступ к следующим источникам данных:
```

2024-02-20 02:42 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между YDB и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также
```suggestion
Для организации шифрованных соединений между {{ ydb-short-name }} и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также пропишите пути до публичного и приватного ключа в секции конфигурационного файла `connector_server.tls.cert` и `connector_server.tls.key` соответственно:
```

2024-02-20 02:44 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Новый образ можно использовать для развертывания сервиса с помощью команд, приведённых выше.
сюда б ещё пример `docker build` и явно написать, что это Dockerfile

2024-02-20 02:48 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +| `paging` | Опциональная секция. Содержит настройки алгоритма разбиения извлекаемого из источника потока данных на Arrow-блоки. На каждый запрос в коннекторе создаётся очередь из заранее подготовлен
```suggestion
| `paging` | Опциональная секция. Содержит настройки алгоритма разбиения извлекаемого из источника потока данных на Arrow-блоки. На каждый запрос в коннекторе создаётся очередь из заранее подготовленных к отправке на сторону {{ ydb-short-name }} блоков данных. Аллокации Arrow-блоков формируют наиболее существенный вклад в потребление оперативной памяти процессом `fq-connector-go`. Минимальный объём памяти, необходимый коннектору для работы, можно приблизительно оценить по формуле $Mem = 2 \cdot Requests \cdot BPP \cdot PQC$, где $Requests$ — количество одновременно выполняемых запросов, $BPP$ ‚ параметр `paging.bytes_per_page`, а $PQC$  — параметр `paging.prefetch_queue_capacity`. |
```

2024-02-20 02:50 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +{{ ydb-short-name }} и внешние источники данных в варианте production-инсталляции должны разворачиваться, очевидно, на разных физических или виртуальных серверах, в том числе в облаках. Коннектор, в
```suggestion
{{ ydb-short-name }} и внешние источники данных в варианте production-инсталляции должны разворачиваться на разных физических или виртуальных серверах, в том числе в облаках. Коннектор, в случае, если его использование необходимо для доступа к требуемому источнику данных, может быть развернут согласно следующим схемам:
```

2024-02-20 07:50 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Данная функциональность находится в режиме "Preview".
Во всех страницах, которые менял в этом PR, поправил на Experimental

2024-02-26 07:32 UTC, fomichev3000 requested changes

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +| [S3](https://aws.amazon.com/ru/s3/) | Нативная |
Я бы поменял "Нативная" -> "Встроенная (в ydbd)"

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +# Aрхитектура федеративных запросов
Архитектура поддержки федеративных запросов
или
Архитектура выполнения федеративных запросов

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/index.md
>  - [ClickHouse](clickhouse.md).
Не хватает ссылки на Архитектуру

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +
Мне кажется, что в целом статья "Архитектура" выглядит несколько странно для пользователей. Есть явный перекос в сторону коннекторов, что объясняется позицией автора :)

Я бы дописал еще раздел, про то external data source, external table. Пусть и короткий, зато логично будет смотреться.

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +{{ ydb-short-name }} и внешние источники данных в варианте production-инсталляции должны разворачиваться на разных физических или виртуальных серверах, в том числе в облаках. Коннектор, в случае, есл
развертываться или разворачиваться?

В статье и так и этак

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +* На отдельном от {{ ydb-short-name }} физическом или виртуальном сервере.
Я пожалуй, строго против требования наличия docker для коннектора. Почему нельзя добавить возможность развернуть через бинарник?

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развернут коннектор
Мне кажется, что очень опасная вещь. Она кажется простой, но на практике не будет работать.

Пусть у тебя кластер ydb на 3 дин ноды. Скорее всего ты и 3 коннектора захочешь? ну или 2+, не один же. Какой endpoint указывать? Как балансировать? Что делать, когда машина с коннектором сломалась. Поверь, это сложно. Почему бы не сделать просто localhost?

2024-02-26 07:32 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между {{ ydb-short-name }} и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в к
Если будет localhost, то возможно и не нужно будет использовать TLS?

2024-02-29 15:15 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между {{ ydb-short-name }} и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в к
да, указал, что по умолчанию TLS не нужен

2024-02-29 15:16 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    host: connector_host  # имя хоста, где развернут коннектор
Переделал и картинку тоже перерисовал

2024-02-29 15:18 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +* На отдельном от {{ ydb-short-name }} физическом или виртуальном сервере.
Теперь собираем на github релизы в виде tar.gz наряду с докер-образами.

https://github.com/ydb-platform/fq-connector-go/releases

В документации всё расписал в соседнем файле

2024-02-29 15:19 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +{{ ydb-short-name }} и внешние источники данных в варианте production-инсталляции должны разворачиваться на разных физических или виртуальных серверах, в том числе в облаках. Коннектор, в случае, есл
поправил

2024-02-29 15:19 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +
Добавил два абзаца про внешние источники данных и таблицы.

2024-02-29 15:20 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/index.md
>  - [ClickHouse](clickhouse.md).
извини, не совсем понял, на какой раздел не хватает ссылки? на архитектуру системы обработки Federated Query ссылка есть

2024-02-29 15:20 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +# Aрхитектура федеративных запросов
поправил

2024-02-29 15:20 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +| [S3](https://aws.amazon.com/ru/s3/) | Нативная |
Готово

2024-03-03 20:09 UTC, fomichev3000 requested changes

2024-03-03 20:09 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    port: 50051                     # номер порта для слушающего сокета коннектора
меня чутка порт смущает, может выбрать ближе к 2136?

2024-03-03 20:09 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    sudo cp fq-connector-go /usr/local/bin
Ой, прям не надо sudo... Почему мы не кладем connector рядом с ydbd?

Эту секцию надо бы эксплуатации показать.

2024-03-04 09:08 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/index.md
> +Федеративные запросы - это способ получать информацию из различных источников данных без необходимости переноса данных этих источников внутрь {{ ydb-full-name }}. Федеративные запросы поддерживают вз
fixed

2024-03-04 09:08 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/architecture.md
> +Ключевым элементом системы обработки федеративных запросов {{ ydb-full-name }} является понятие [внешнего источника данных](../datamodel/external_data_source.md) (external data source). В качестве та
fixed

2024-03-04 10:45 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    port: 50051                     # номер порта для слушающего сокета коннектора
Посоветовались с @ArtemTrofimushkin и остановились на 2130.

2024-03-04 10:52 UTC, uzhastik commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    port: 50051                     # номер порта для слушающего сокета коннектора
предлагаю порт 2138

2024-03-04 11:35 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
> +                    port: 50051                     # номер порта для слушающего сокета коннектора
> предлагаю порт 2138

не получится, так как есть реальные инсталляции, где этот порт уже занят `ydbd`

2024-03-04 11:49 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    sudo cp fq-connector-go /usr/local/bin
> Почему мы не кладем connector рядом с ydbd?

Теперь кладём, заменил все пути (в том числе внутри Dockerfile) на `/opt/ydb/...`.


> Ой, прям не надо sudo... 

Боюсь, без sudo никак не обойтись. В инструкции по ydbd on-prem sudo используется многократно:

https://ydb.tech/docs/ru/deploy/manual/deploy-ydb-on-premises#install-binaries

2024-03-05 07:35 UTC, artgromov approved these changes

2024-03-05 07:40 UTC, artgromov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    sudo cp fq-connector-go /usr/local/bin
Да, лучше всего в /opt/ydb/bin - мы там держим все бинарники.

Без sudo, к сожалению, никак, если мы хотим складывать в /opt/ydb и защищать содержимое этих директорий от изменений "левыми" пользователями.

2024-03-06 04:48 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    sudo cp fq-connector-go /usr/local/bin
@vitalyisaev2 переделаешь на /opt/ydb/bin?

2024-03-06 06:37 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/index.md
>  - [ClickHouse](clickhouse.md).
так, вроде все есть, игнорируй плиз коммент

2024-03-06 06:44 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +    sudo cp fq-connector-go /usr/local/bin
@blinkov да, в актуальной версии уже так: https://github.com/ydb-platform/ydb/pull/1895/files#diff-bb984d64c1000ee26d3fa58aa365d1955431f388f9e623ce06d2a1c581205aefR39

2024-03-06 06:48 UTC, uzhastik approved these changes

2024-03-06 07:03 UTC, fomichev3000 approved these changes

2024-03-06 07:05 UTC, vitalyisaev2 commented on ydb/docs/ru/core/deploy/manual/connector.md
> +Для организации шифрованных соединений между YDB и коннектором [подготовьте пару TLS-ключей](../manual/deploy-ydb-on-premises.md#tls-certificates) и примонтируйте папку с ключами в контейнер, а также
В этом PR расписал всё про TLS максимально подробно. В том числе появилось поле для файла CA.

2024-03-06 07:19 UTC, blinkov approved these changes

2024-03-06 07:20 UTC, merged