Add useful astdiff output
ydb-platform/ydb pull request #1914
Opened 2024-02-14 10:57 UTC by fedor-miron

Example astdiff output for failed test before:
```
est results differ from canonical:
test_result[0]: files content differs:
'contrib/ydb/library/yql/tools/astdiff/astdiff' has finished unexpectedly with rc = 5
stdout:

stderr:
Programs are not equal!
Node '' in /home/fedor-miron/arcadia/canondata_storage/1925821/f619130b1d3bec8c0a80cec04d3cef4c455b9619/resource/test.test_Aggregation-Level_4-Debug_/opt.yql at [100:10] has 1 children.
Node '' in /home/fedor-miron/.ya/build/build_root/2pbu/000046/canon_tmpwdF2m0/opt.yql at [100:10] has 2 children.
Log: /home/fedor-miron/arcadia/contrib/ydb/library/yql/tests/s-expressions/yt_native_file/part2/test-results/pytest/chunk0/testing_out_stuff/test.py.test.Aggregation-Level_4-Debug.log
```
astdiff output with this PR:
```
fail] test.py::test[Aggregation-Level_4-Debug] [default-linux-x86_64-debug] (27.97s)
Test results differ from canonical:
test_result[0]: files content differs:
''contrib/ydb/library/yql/tools/astdiff/astdiff' has finished unexpectedly with rc = 5
stdout:

stderr:
Programs are not equal!
Node '' in /tmp/astdiff/old.yql at [100:10] has 1 children.
#267 [List]
 #266 [List]
  #265 [Atom] <strict>
Node '' in /tmp/astdiff/new.yql at [100:10] has 2 children.
#269 [List]
 #266 [List]
  #265 [Atom] <blocks>
 #268 [List]
  #267 [Atom] <strict>

File diff:
--- /tmp/astdiff/old.yql        2024-02-14 13:31:44.294472842 +0300
+++ /tmp/astdiff/new.yql        2024-02-14 13:31:44.294472842 +0300
@@ -41,7 +41,7 @@
   (return (FlatMap $92 (lambda '($98) (block '(
     (let $99 '((DataType 'Uint32) '"" '1))
     (let $100 (CallableType '() '((OptionalType (DataType 'Timestamp))) $99))
-    (let $101 (Udf '"DateTime2.FromSeconds" (Void) (VoidType) '"" $100 (VoidType) '"" '('('"strict"))))
+    (let $101 (Udf '"DateTime2.FromSeconds" (Void) (VoidType) '"" $100 (VoidType) '"" '('('"blocks") '('"strict"))))
     (return (Just (AsStruct '('"assignment_id" (Member $98 $28)) '('"date" (SafeCast (Apply $1...'
```

2024-02-14 14:47 UTC, fedor-miron commented on ydb/library/yql/tools/astdiff/astdiff.cpp
> +    TShellCommand cmd("diff", {"-u", oldPath, newPath});
fixed

2024-03-25 11:08 UTC, vitstn commented on ydb/library/yql/tools/astdiff/astdiff.cpp
> +    const auto differBinary = NResource::Find("/differ");
please don't inject an executable binary as resource

2024-03-27 08:15 UTC, rvu1024 requested changes

2024-03-27 08:15 UTC, rvu1024 commented on ydb/library/yql/tools/astdiff/astdiff.cpp
> +            Cerr << "Node '" << rootOne->Content() << "' in " << oldAstTempPath << " at [" << rootOnePos.Row << ":" << rootOnePos.Column << "] has " << rootOne->ChildrenSize() << " children." << Endl
Почему oldAstTempPath, а не fileOne?

2024-03-27 08:15 UTC, rvu1024 commented on ydb/library/yql/tools/astdiff/ya.make
> +    library/cpp/resource
это уже лишнее

2024-03-27 08:15 UTC, rvu1024 commented on ydb/library/yql/tools/astdiff/astdiff.cpp
> +#include <util/system/shellcommand.h>
это уже лишнее

2024-03-27 08:47 UTC, fedor-miron commented on ydb/library/yql/tools/astdiff/astdiff.cpp
> +            Cerr << "Node '" << rootOne->Content() << "' in " << oldAstTempPath << " at [" << rootOnePos.Row << ":" << rootOnePos.Column << "] has " << rootOne->ChildrenSize() << " children." << Endl
потому что fileOne это путь, который подчищается после завершения теста `home/fedor-miron/arcadia/canondata_storage/1925821/f619130b1d3bec8c0a80cec04d3cef4c455b9619/resource/test.test_Aggregation-Level_4-Debug_/opt.yql`, наверху пример

2024-03-29 14:07 UTC, rvu1024 approved these changes

2024-03-29 15:42 UTC, merged