Rate parameter
ydb-platform/ydb pull request #1995
Opened 2024-02-16 07:27 UTC by azevaykin

### Changelog entry 

New parameter --rate in YDB Cli: total rate for all threads (transactions or requests per second).

### Changelog category 

* New feature

### Additional information

...

2024-02-16 07:52 UTC, blinkov requested changes

2024-02-16 07:52 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
> +`--rate <значение>` | - | Суммарная скорость всех потоков, транзакций в сек. Значение по умолчанию: 0 (не ограничена).
```suggestion
`--rate <значение>` | - | Суммарная частота запросов всех потоков, в транзакциях в секунду. Значение по умолчанию: 0 (не ограничена).
```

2024-02-16 07:52 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/workload-kv.md
> +`--rate <значение>` | - | Суммарная скорость всех потоков, запросов в сек. Значение по умолчанию: 0 (не ограничена).
```suggestion
`--rate <значение>` | - | Суммарная частота запросов всех потоков, в транзакциях в секунду Значение по умолчанию: 0 (не ограничена).
```

2024-02-16 17:55 UTC, fomichev3000 approved these changes

2024-02-19 10:13 UTC, blinkov approved these changes

2024-02-19 10:13 UTC, merged