switch pq provider to topic api
ydb-platform/ydb pull request #2045
Opened 2024-02-17 13:16 UTC by uzhastik

### Changelog entry 

Switch pq provider to Topic API

### Changelog category 

* Improvement

### Additional information

...

2024-02-18 09:36 UTC, UgnineSirdis requested changes

2024-02-18 09:36 UTC, UgnineSirdis commented on ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
> +        Y_UNUSED(RangesMode);
So it's better to remove this class member. It was a temporary crutch as far as I remember

2024-02-18 09:36 UTC, UgnineSirdis commented on ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
> +        TReadyBatch(TMaybe<TInstant> watermark, ui32 dataCapacity): Watermark(watermark){
It is still not formatted according to our coding style :)

2024-02-19 15:00 UTC, uzhastik commented on ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
> +        TReadyBatch(TMaybe<TInstant> watermark, ui32 dataCapacity): Watermark(watermark){
бубубу!

2024-02-21 10:01 UTC, alexnick88 submitted a review, later dismissed

2024-02-21 10:34 UTC, UgnineSirdis approved these changes, later dismissed

2024-02-21 11:20 UTC, UgnineSirdis approved these changes

2024-02-21 13:41 UTC, merged