Add Russian CMS docs YDBDOCS-124
ydb-platform/ydb pull request #2097
Opened 2024-02-20 09:53 UTC by pixcc

### Changelog category 
* Documentation (changelog entry is not required)

### Additional information

Документация для таблетки CMS на русском языке.

2024-02-20 12:29 UTC, CyberROFL requested changes

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/manual/replace_hardware.md
> +# Замена оборудования {#replace_hardware}
```suggestion
# Замена оборудования {#replace-hardware}
```

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/manual/replace_hardware.md
> +Перед заменой нужно убедиться, что процесс ydb можно [остановить](../maintenance-without-outages.md#restart-or-stop-node).
```suggestion
Перед заменой нужно убедиться, что процесс {{ ydb-short-name }} можно [остановить](../maintenance-without-outages.md#restart-or-stop-node).
```

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В промышленных эксплуатациях кластер {{ ydb-short-name }} состоит из серверов с дисками. На сервере запускается один [статический узел](../cluster/topology.md), работающий с дисками, и несколько [дин
> эксплуатациях

инсталляциях?

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В промышленных эксплуатациях кластер {{ ydb-short-name }} состоит из серверов с дисками. На сервере запускается один [статический узел](../cluster/topology.md), работающий с дисками, и несколько [дин
> ../cluster/topology.md

а там нет якорей про статические и динамические узлы?

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +- Остановки слишком большого количества узлов в кластере в целом.
Непонятно, почему это опасно.

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера.
```suggestion
Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*.
```

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Во время проведения работ, разрешенных CMS, в кластере могут произойти поломки, из-за которых доступность кластера станет под угрозой. Рекомендуется в срочном порядке завершить работы по обслуживанию
> станет

окажется?

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Он называется *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](../concepts/cluster/_includes/common_scheme_ydb/tablets.md#tablets), доступной через gRPC API и CLI. В CMS
В api у нас нигде не упоминаются "запросы с просьбой" и "разрешения". Может, придерживаться той же терминологии?

2024-02-20 12:29 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +- *Force restart* — принудительный режим доступности, модель отказа игнорируется.
Стоит взять значения из public api.

2024-02-21 07:37 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В промышленных эксплуатациях кластер {{ ydb-short-name }} состоит из серверов с дисками. На сервере запускается один [статический узел](../cluster/topology.md), работающий с дисками, и несколько [дин
Нет, там впринципе одна небольшая страничка в первых двух предложениях которой о статических и динамических узлах

2024-02-21 13:13 UTC, CyberROFL requested changes

2024-02-21 13:13 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +- Недостатка вычислительных ресурсов в следствии остановки слишком большого количества динамических узлов.
```suggestion
- Недостатка вычислительных ресурсов вследствие остановки слишком большого количества динамических узлов.
```

2024-02-21 13:13 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной таблетки, доступной
Раньше тут была ссылка на слове "таблетка". Почему её больше нет?

2024-02-21 13:13 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной таблетки, доступной
> и попросить в ней CMS взять эксклюзивные блокировки

Может лучше так:
> и указать в ней CMS взятие эксклюзивных блокировок

?

2024-02-21 13:13 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной таблетки, доступной
> Компоненты, на которых

Компоненты, на которые

2024-02-21 14:43 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной таблетки, доступной
Поменял на "указать в ней CMS взять". Твой вариант я, если честно, не понял. Мы же указываем CMS что делать.

2024-02-21 14:47 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной таблетки, доступной
Поменял почти на это

> в CMS и указать в ней взятие эксклюзивных блокировок

2024-02-21 16:48 UTC, CyberROFL requested changes

2024-02-21 16:48 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](../concep
> Компоненты, на которые взяты блокировки считаются

Компоненты, на которые взяты блокировки, считаются

2024-02-21 16:48 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Если в момент запроса действие выполнить нельзя, CMS сообщает причину и время, когда стоит обновить задачу, и переводит действие в статус *ожидания*. При обновлении задачи CMS повторно пытается выпол
> и переводит действие в статус *ожидания*

и переводит действие в состояние *ожидания*?

2024-02-21 16:48 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +*Задача обслуживания* — представляет собой набор действий, которые пользователь просит выполнить CMS для возможности проведения безопасного обслуживания. Например, одним из действий является взятие э
> *Задача обслуживания* — представляет собой набор действий

Я бы еще "действий" выделил.

2024-02-21 16:48 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Если работы по обслуживанию кластера продолжают проводиться после завершения действий, то это расценивается как поломка в кластере.
Наверно, стоит уточнить, что не любые работы по обслуживанию кластера, а именно те, которые затрагивают узел/сервер из завершенного действия.

2024-02-21 16:48 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Задачи по обслуживанию не удаляются автоматически. На данный момент завершенные действия автоматически удаляются из задачи.
"На данный момент" точно нужно писать?

2024-02-22 09:52 UTC, CyberROFL submitted a review, later dismissed

2024-02-27 09:33 UTC, CyberROFL requested changes

2024-02-27 09:33 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](../concep
> gRPC API

пока у нас нет cli, может хотя бы ссылку на апи дать?

2024-02-27 09:33 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +*Задача обслуживания* — представляет собой набор *действий*, которые пользователь просит выполнить CMS для возможности проведения безопасного обслуживания. Единственным поддерживаемым действием являе
> Единственным поддерживаемым действием является взятие эксклюзивной блокировки на компонент кластера — узел или сервер.

Список предлагается расширять, стоит в документации это тоже предсмотреть. Например, так:
```
Поддерживаемые действия:
- Взятие эксклюзивной блокировки на компонент кластера — узел или сервер.
```

2024-02-27 10:57 UTC, CyberROFL submitted a review, later dismissed

2024-03-15 03:31 UTC, blinkov requested changes, later dismissed

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Чтобы избежать этого, в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](../concep
```suggestion
Для избежания таких ситуаций в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](../concepts/cluster/_includes/common_scheme_ydb/tablets.md#tablets), доступной через [gRPC API](https://github.com/ydb-platform/ydb/blob/main/ydb/public/api/grpc/draft/ydb_maintenance_v1.proto). В CMS можно согласовать проведение работ с кластером. Для этого необходимо создать [задачу обслуживания](#maintenance-task) в CMS и указать в ней взятие эксклюзивных блокировок на компоненты кластера (например, узлы или сервера), которые будут задействованы в обслуживании. Компоненты, на которые взяты блокировки, считаются недоступными с точки зрения CMS, и их можно безопасно обслуживать. CMS [проверит](#check-actionability-algorithm) текущее состояние кластера и возьмет блокировки, только если работы соответствуют ограничениям [режима доступности](#availability-mode) и [лимитам недоступности узлов](#cluster-and-tenant-limits).
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Во время проведения работ, согласованных CMS, в кластере могут произойти поломки, из-за которых доступность кластера окажется под угрозой. Рекомендуется в срочном порядке завершить работы по обслужив
```suggestion
Во время проведения работ, согласованных в CMS, в кластере могут произойти поломки, из-за которых доступность кластера окажется под угрозой. В этом случае рекомендуется в срочном порядке завершить работы по обслуживанию, если это поможет снизить риск потери доступности.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +*Задача обслуживания* — представляет собой набор *действий*, которые пользователь просит выполнить CMS для возможности проведения безопасного обслуживания.
```suggestion
*Задача обслуживания* представляет собой набор действий, которые пользователь просит выполнить CMS для проверки возможности проведения безопасного обслуживания.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Если в момент запроса действие выполнить нельзя, CMS сообщает причину и время, когда стоит обновить задачу, и переводит действие в состояние *ожидания*. При обновлении задачи CMS повторно пытается вы
тут и в соседних местах хорошо б в скобках написать как это состояние называется в ответе CMS

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +- **Force** — принудительный режим, модель отказа игнорируется.
```suggestion
- **Force** — принудительный режим, модель отказа игнорируется. Не рекомендуется к использованию.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +У задачи обслуживания можно указать приоритет. Меньшее значение означает больший приоритет.
```suggestion
У задачи обслуживания можно указать приоритет. Меньшее значение означает более высокий приоритет.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Таким образом действия задачи не могут быть выполнены, пока все конфликтующие действия из задач с большим приоритетом не будут завершены. Задачи с одинаковым приоритетом не имеют преимущества друг пе
```suggestion
Таким образом, действия задачи не могут быть выполнены, пока все конфликтующие действия из задач с большим приоритетом не будут завершены. Задачи с одинаковым приоритетом не имеют преимущества друг перед другом.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В конфигурации CMS можно настроить лимит количества недоступных узлов для базы данных (тенанта) или для кластера в целом. Поддерживаются относительные и абсолютные лимиты.
```suggestion
В конфигурации CMS можно настроить лимит на количество недоступных узлов для базы данных (тенанта) или для кластера в целом. Поддерживаются относительные и абсолютные лимиты.
```

2024-03-15 03:31 UTC, blinkov commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +По умолчанию допускается не более `10%` недоступных узлов для каждой базы данных и кластера в целом.
```suggestion
По умолчанию допускается не более 10% недоступных узлов для каждой базы данных и кластера в целом.
```

2024-03-18 11:17 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +*Задача обслуживания* — представляет собой набор *действий*, которые пользователь просит выполнить CMS для возможности проведения безопасного обслуживания.
Действие - это же тоже термин, которым оперирует CMS API

2024-03-23 13:57 UTC, fomichev3000 requested changes

2024-03-23 13:57 UTC, fomichev3000 commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +- Превышения модели отказа затронутых [групп хранения](../concepts/_includes/databases/storage_groups.md#storage-groups).
Странная ссылка. Попробуй на нее кликнуть. Я бы сослался на https://ydb.tech/docs/ru/concepts/databases#storage-groups

2024-03-23 13:57 UTC, fomichev3000 commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В промышленных инсталляциях кластер {{ ydb-short-name }} состоит из серверов с дисками. На сервере запускается один [статический узел](../cluster/topology.md), работающий с дисками, и несколько [дина
Это не совсем так. Например в облаках на одной VM запускается обычно одна дин нода. Для сторадж узла тоже будет выделена своя VM. На мой взгляд абзац не закончен. Какая мысль должна появиться у пользователя после прочтения? В общем чего-то не хватает

2024-03-23 13:57 UTC, fomichev3000 commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Для избежания таких ситуаций в {{ ydb-short-name }} есть встроенный компонент, который следит за состоянием кластера — *Cluster Management System (CMS)*. CMS реализован в виде системной [таблетки](..
На мой взгляд после первого предложения не хватает вот такого текста:

"CMS позволяет ответить на вопрос можно ли безопасно вывести сервер или VM, на котором работает компонент YDB, в обслуживание."

2024-03-23 13:57 UTC, fomichev3000 commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +# Обслуживание кластера без потери доступности
На мой взгляд документация фатально не дописана. Что я имею ввиду? Концепции понятно. А теперь представь, что я пользователь, как мне воспользоваться этой CMS? Как мне взять блокировку? Как мне посмотреть, какие блокировки взяты. Очень-очень нужна практичность.

Знаю, что Егор Тарасов пишет утилиту ydbops, которая как раз будет позволять рестартовать кластер. При этом для рестарта брать блокировку в CMS. Кажется, стоит к нему же сходить, и убедиться, что будет команда вывести ноду для обслуживания. 
Дополнительно я бы сослался на gprc public api для CMS (это легко).
Дополнительно я бы описал CMS UI или сослался бы на него.

2024-04-18 13:27 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +В промышленных инсталляциях кластер {{ ydb-short-name }} состоит из серверов с дисками. На сервере запускается один [статический узел](../cluster/topology.md), работающий с дисками, и несколько [дина
Изначально планировал абзацем показать как связаны узлы, серверы, диски. Решил убрать, чтобы не усложнять статью деталями развертывания.

2024-04-18 13:39 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +# Обслуживание кластера без потери доступности
Добавил примеры из ydbops и сослался на gRPC Public API протофайлы.

2024-04-18 19:08 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +## Кластерные и тенантные лимиты недоступности узлов {#cluster-and-tenant-limits}
"Кластерные" и "тенантные" как-то не очень звучит... Может оставить просто:
```suggestion
## Лимиты недоступности узлов {#cluster-and-tenant-limits}
```
?

2024-04-18 19:08 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Функциональность ожидается в ближайших версиях ydbops.
Как-то странно видеть "функциональность в разработке" и тут же пример конкретной команды)

2024-04-18 19:08 UTC, CyberROFL commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +При выполнении этой команды ydbops возьмет эксклюзивную блокировку на узел в CMS.
В команде --host, а в тексте "узел". Все-таки, хост или узел?

2024-04-19 06:34 UTC, fomichev3000 approved these changes, later dismissed

2024-04-19 09:44 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +Функциональность ожидается в ближайших версиях ydbops.
Я взял пример команды отсюда - https://github.com/ydb-platform/ydbops/issues/2

Если внешний вид команды поменяется, то доку можно будет легко поправить. Я напишу в этот issue, чтобы не забыть.

2024-04-19 09:48 UTC, pixcc commented on ydb/docs/ru/core/maintenance/maintenance-without-outages.md
> +При выполнении этой команды ydbops возьмет эксклюзивную блокировку на узел в CMS.
Аргумент не я придумал, возможно аргумент может принимать и хост, и узел. Я пока что написал только узел, т.к. команда `ydbops node maintenance`

2024-04-19 09:56 UTC, CyberROFL submitted a review, later dismissed

2024-04-19 14:46 UTC, CyberROFL approved these changes

2024-04-19 15:05 UTC, blinkov approved these changes

2024-04-19 15:06 UTC, merged