YQ-2068 remove unused IFunctionRegistry from compute actors
ydb-platform/ydb pull request #2230
Opened 2024-02-26 04:14 UTC by zverevgeny

### Changelog category 

* Not for changelog (changelog entry is not required)

2024-02-26 07:41 UTC, rvu1024 requested changes

2024-02-26 07:41 UTC, rvu1024 commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
> +                auto collectStatsLevel = StatsModeToCollectStatsLevel(RuntimeSettings.StatsMode);
style

2024-02-26 07:41 UTC, rvu1024 commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
> +                for (ui32 i = 0; i < Task.InputsSize(); ++i) {
style

2024-02-26 07:41 UTC, rvu1024 commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
> +                                auto result = InputTransformsMap.emplace(
style

2024-02-27 14:21 UTC, zverevgeny commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
> +                for (ui32 i = 0; i < Task.InputsSize(); ++i) {
fixed

2024-04-18 10:27 UTC, gridnevvvit approved these changes

2024-04-18 13:55 UTC, rvu1024 approved these changes

2024-04-18 13:55 UTC, merged