YQ-2863: local FQ gRPC call draft
ydb-platform/ydb pull request #2278
Opened 2024-02-27 14:18 UTC by EgorkaZ

### Changelog entry 

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

2024-03-12 13:14 UTC, dorooleg requested changes

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/local_rpc/local_rpc.h
> +        RaiseIssue(NYql::TIssue(TStringBuilder() << "grpc code: " << code << ", msg: " << msg << " (" << details << ")"));
а точно тут нужны изменения? context не хватит?

2024-03-12 13:14 UTC, dorooleg commented on ydb/services/fq/ydb_over_fq.cpp
> +    Limiter_ = limiter;
А TGrpcService тут не получается запереиспользовать?

2024-03-12 13:14 UTC, dorooleg commented on ydb/services/ydb/ydb_table.h
> +    using TBase = TGrpcServiceBase<Ydb::Table::V1::TableService>;
а где этот TBase используется?

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/local_grpc_context.h
> +#pragma once
Этот же контекст выглядит достаточно общим. Мы можем вынести его рядом с другими контекстами, чтобы другие разработчики могли легко его найти?

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +            ctx.Schedule(TDuration::Seconds(3), CreateStatusRequest());
Давай сюда экспоненциальные ретраи сделаем. Иначе на коротких запросах можем тупить в этом месте

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +        constexpr i64 RowsLimit = 333;
А почему такой лимит не обычный выбран?

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +            // TODO: validate columns
А точно это нужно здесь делать? В каких случаях могут быть проблемы?

2024-03-12 13:14 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +    TActorId GrpcProxyId_;
Предлагаю одинаковые названия держать чтобы легче было грепать потом `GRpcRequestProxyId_`

2024-03-12 13:25 UTC, EgorkaZ commented on ydb/core/grpc_services/fq_permissions.md
> +## Current state
Ох, он даже скорее мне был нужен, чтобы осознать ~~тленность бытия~~ происходящее во всех этих интерфейсах. Я плохо понимаю, куда это счастье можно пристроить, особенно при том, что оно правда вряд ли будет поддерживаться

2024-03-12 13:28 UTC, EgorkaZ commented on ydb/core/grpc_services/grpc_request_proxy.cpp
> +        if (AllowYdbRequestsWithoutDatabase && !Databases.contains(requestBaseCtx->GetDatabaseName().GetOrElse(""))) {
Да. Нам всё ещё нужно, чтобы пользователь как-то обозначил свой scope. Если хотим поддержать сохранить неизменным sdk (в чём вроде как вся цель псевдо-сервисов) и пользовательский код, я не придумал, куда нам ещё его пристроить

2024-03-12 13:32 UTC, EgorkaZ commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +        constexpr i64 RowsLimit = 333;
В основном для тестирования, поменяю

2024-03-12 13:33 UTC, EgorkaZ commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +            // TODO: validate columns
Беда в том, что я не знаю. Боюсь того, что может поменяться порядок колонок для разных ответов. Либо в коде копаться, либо знающих людей допытывать, потому TODO

2024-03-13 13:04 UTC, EgorkaZ commented on ydb/core/driver_lib/run/run.cpp
> +            if (!hasTableService && !hasSchemeService) {
Кажется плохим состояние, когда частично работаем как настоящий сервис, частично — как ложный, потому решил склеить. Про отключаемость — хороший вопрос, возможно стоит завести сервис в конфиге

2024-03-13 13:18 UTC, uzhastik commented on ydb/core/driver_lib/run/run.cpp
> +            if (!hasTableService && !hasSchemeService) {
tableService же отключен, если включен yq. если мы его включаем, то это равносильно включению прокси для yq
вроде текущих флагов достаточно

2024-03-13 13:52 UTC, uzhastik commented on ydb/core/grpc_services/fq_permissions.md
> +## Current state
этот файл лучше удалить

2024-03-14 11:39 UTC, EgorkaZ commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +            // TODO: validate columns
Пишут, что действительно должно быть ок, уберу TODO

2024-03-14 11:45 UTC, EgorkaZ commented on ydb/services/fq/ydb_over_fq.cpp
> +    Limiter_ = limiter;
Это как раз общая база для новой пары сервисов. Какой-то общей на всех в коде не нашёл

2024-03-14 16:42 UTC, dorooleg approved these changes

2024-03-15 11:09 UTC, merged