Fixed iterator invalidation in graph shard
ydb-platform/ydb pull request #2395
Opened 2024-03-02 09:16 UTC by domwst

### Fixed iterator invalidation in graph shard 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-03-02 09:16 UTC, domwst commented on ydb/core/graph/ut/graph_ut.cpp
> +            UNIT_ASSERT_VALUES_EQUAL(response->Record.TimeSize(), 25);
Not sure if this is indeed desired behaviour

2024-03-04 09:08 UTC, adameat requested changes

2024-03-04 09:08 UTC, adameat commented on ydb/core/graph/shard/backends.cpp
> +    const TInstant itStopTs = itStop->Timestamp;
isn't it equal to endTimestamp?

2024-03-04 09:10 UTC, adameat approved these changes

2024-03-04 09:13 UTC, merged