Configurable PDisk chunk color limits
ydb-platform/ydb pull request #2409
Opened 2024-03-04 09:00 UTC by SammyVimes

* Improvement

2024-03-04 12:57 UTC, va-kuznecov commented on ydb/core/mind/bscontroller/config.cpp
> +                if (prev.PDiskConfig != cur.PDiskConfig) {
а как он сравнивает кофиги?

2024-03-04 12:57 UTC, va-kuznecov commented on ydb/core/protos/blobstorage_pdisk_config.proto
> +    optional uint32 CyanLimit = 2002;
без комментариев очень сложно понять, что это значит и какие значения сюда можно писать, какие единицы измерения

2024-03-04 12:57 UTC, va-kuznecov commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_color_limits.h
> +    static TColorLimits MakeChunkLimits(i64 cyan = 130) {
```suggestion
    static TColorLimits MakeChunkLimits(i64 cyan) {
```

мне кажется дефолт тут лишний, так как используется функция в одном месте и там всегда указывается аргумент

2024-03-04 20:09 UTC, SammyVimes commented on ydb/core/mind/bscontroller/config.cpp
> +                if (prev.PDiskConfig != cur.PDiskConfig) {
They are `TStrings`, so it is a simple string comparison.

2024-03-04 20:12 UTC, SammyVimes commented on ydb/core/protos/blobstorage_pdisk_config.proto
> +    optional uint32 CyanLimit = 2002;
I agree, I actually wanted to consult on this matter, because I fear there is no good name for our color setting.

2024-08-28 15:34 UTC, va-kuznecov reviewed
LGTM

2024-08-28 18:17 UTC, the-ancient-1 requested changes

2024-08-28 18:17 UTC, the-ancient-1 commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_color_limits.h
> +        i64 yellow = cyan / 130.0 * 80;
если в результате округления произойдет погрешность и старое значение будет отличаться от нового на 1, то во время выкатки релиза мы получим кластер в котором часть машин будет иметь один лимит (посчитанный старым кодом) а часть машин другой лимит (посчитанный новым кодом). При этом величина заполненности сообщаемая в hive может отличаться, в результате hive должен будет увозить таблетки с пожелтевшего диска на более свободный по характеристике заполненность, которая окажется рассогласована с цветным флагом, после чего хайв снова должен будет перевозить таблетку. Такое уже было, когда хайв возил таблетки между несколькими пожелтевшими группами. Тут необходимо избежать изменения значений цветных лимитов при смене версии кода. Вероятно, следует использовать целочисленную математику (сначала умножать потом делить), тогда погрешность при значении 130 возникать не будет.

2024-08-29 09:12 UTC, SammyVimes commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_color_limits.h
> +        i64 yellow = cyan / 130.0 * 80;
Поправил

2024-08-29 16:09 UTC, the-ancient-1 submitted a review, later dismissed
LGTM

2024-08-30 10:44 UTC, va-kuznecov approved these changes

2024-08-30 13:25 UTC, merged