Added prompt and --force flag in ydb config profile replace command
ydb-platform/ydb pull request #262
Opened 2023-06-14 16:51 UTC by Gazizonoki

2023-06-14 17:26 UTC, pnv1 requested changes

2023-06-14 17:26 UTC, pnv1 commented on ydb/public/lib/ydb_cli/commands/ydb_profile.cpp
> +            : TCommandProfileCommon("replace", {}, "Deletes profile and creates a new with the same name")
`Deletes profile and creates a new one with the same name and new property values from provided options. If no options are provided, a profile will be replaced with an empty one`
Not sure about the last sentence so its up to you

2023-06-14 17:26 UTC, pnv1 commented on ydb/public/lib/ydb_cli/commands/ydb_profile.cpp
> +            Cout << "Profile data will be permanently removed. Continue? (y/n): ";
`Current profile will be replaced with a new one. All current profile data will be lost. Continue?`

Otherwise its sounds too dangerous

2023-06-14 17:26 UTC, pnv1 commented on ydb/public/lib/ydb_cli/commands/ydb_profile.cpp
> +                return EXIT_SUCCESS;
It won't be success I guess...

2023-06-14 17:51 UTC, pnv1 approved these changes

2023-06-15 12:22 UTC, alexv-smirnov approved these changes

2023-06-16 16:34 UTC, closed without merging