YQL-17766 Fix decimal incompatibility between yqlrun and yt
ydb-platform/ydb pull request #2631
Opened 2024-03-11 16:25 UTC by kinash-varvara

* Bugfix

2024-03-11 19:40 UTC, resetius commented on ydb/library/yql/providers/common/codec/yql_codec.cpp
> +                memcpy(tmpBuf, &data128, 16);
Can we remove this line? Looks like nonsense.

2024-03-13 11:08 UTC, resetius approved these changes

2024-03-13 12:53 UTC, resetius requested changes
Please check build

2024-03-13 13:07 UTC, rvu1024 requested changes

2024-03-13 13:07 UTC, rvu1024 commented on ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
> +            WriteYsonContainerValue(type, NativeYtTypeFlags_, value, Buf_);
здесь 0 нужно передавать. Если бы NativeYtTypeFlags_ != 0, то мы ушли в первую ветку функции

2024-03-13 13:29 UTC, kinash-varvara commented on ydb/library/yql/providers/common/codec/yql_codec.cpp
> +    return ParseYsonValue(holderFactory, NYT::NodeToYsonString(node, NYson::EYsonFormat::Binary), type, false, err, false);
false конвертируется в 0 ведь. может тогда лучше этот флаг сделать bool а не ui64(по аналогии с IsTableFormat)?

2024-03-13 13:54 UTC, rvu1024 commented on ydb/library/yql/providers/common/codec/yql_codec.cpp
> +    return ParseYsonValue(holderFactory, NYT::NodeToYsonString(node, NYson::EYsonFormat::Binary), type, false, err, false);
Не нужно неявных преобрахований. Если аргумент имеет тип ui64, то нужно передавать туда 0, а не false. Иначе это путает.
Менять тип флага не надо. Это битовая маска

2024-03-13 14:01 UTC, rvu1024 requested changes

2024-03-13 14:01 UTC, rvu1024 commented on ydb/library/yql/providers/common/codec/yql_codec.cpp
> +                        return NUdf::TUnboxedValuePod(res);
В UnboxedValue нужно возвращать 128-битное число для decimal.

2024-03-13 14:01 UTC, rvu1024 commented on ydb/library/yql/providers/common/codec/yql_codec.cpp
Нужен ut на decimal. Он должен покрывать чтение/запись и покрывать три варианта precision для разных размерностей представления

2024-03-29 13:05 UTC, resetius approved these changes, later dismissed

2024-04-02 23:45 UTC, resetius commented
@rvu1024 is it Ok to change the signature of `WriteYsonContainerValue` here ?
arg `nativeYtTypeFlags` is always 0

2024-04-02 23:52 UTC, resetius commented
@kinash-varvara TYtCodegenCodec.TestReadContainerRow crashed. The reason: signarure of ReadYsonContainerValue was changed.

2024-04-03 16:15 UTC, rvu1024 approved these changes

2024-04-03 16:16 UTC, merged