Support copy sequence in schemeshard
ydb-platform/ydb pull request #2693
Opened 2024-03-13 10:21 UTC by shnikd

- **fix windows build (#2167)**
- **fix throwing exceptions on incorrect error message construction (#2160)**
- **clean TUnifiedBlobId. prepare for use TLogoBlobId only (#2171)**
- **Generate bindings (#2187)**
- **[YQL-17789] Pull ReplicateScalars through WideMap and DqPhyStage boundary (#2159)**
- **allow free arguments in FormatCode (#2153)**
- **YQL-17729, YQL-17588: module & UDF resolver in pgrun (#2175)**
- **split methods for stages execute/complete usage in case modification (#2166)**
- **Support storage quorum when applying configuration (#2173)**
- **Query service execute script parameters (#2193)**
- **actors for saving/loading of per-column statistics (#2195)**
- **Disable partial Sorted constraints (#2194)**
- **fix build clang14 (#2199)**
- **YQL-17315: PG regression tests' deps (#2154)**
- **lower time difference issues from red to orange (#2197)**
- **fix blobstorage build clang14 (#2202)**
- **Import from S3: check error is retriable KIKIMR-21102 (#2198)**
- **YDB-1066 Added healthcheck RED issue for no pools in database (#2098)**
- **YDB-1453 added CORS headers to healthcheck handler (#2174)**
- **fix style tests (#2206)**
- **CMake14 build (#2207)**
- **partitioning has been fixed YQ-2789 (#1538)**
- **Fix memory usage for heavy normalizers (#2204)**
- **fix bug with table (#1998)**
- **YQL-17315: PG test table deps, part 2 (#2209)**
- **resolves #2078: sort YdbResults via ColumnHints (#2210)**
- **external table content has been decoded for viewer KIKIMR-18798 (#1281)**
- **Fix typo (#2214)**
- **Make queries 36,70,86 pg-compatible (#2215)**
- **fix incorrect tests implementation (#2212)**
- **Base transaction class for all propose operations (#2208)**
- **Fix TzTimestamp wrong encoding (YQL-17920) (#2222)**
- **[PG Syntax] Added ydb pragma support (#2225)**
- **Test for ALTER TABLE RENAME TO (doesn't work yet) (#2228)**
- **Pass VDisk burst threshold in config, fix TBucketQuoter bug (#2165)**
- **YT YQL plugin; Fix configs parsing (#2093)**
- **Add shared thread logic to harmonizer (#1767)**
- **parquet DateTime insert has been supported YQ-2570 (#1410)**
- **YQ-2786 partly unmute tests fq s3 (#2143)**
- **Handle NOT Ready GetOperationResponse for Scripts (#1479)**
- **LOGBROKER-8953: change 400 to 503 status for Unavailable in http_proxy (#2130)**
- **Dynamic listing mass fix (#1913)**
- **VERIFY that created ingress is not empty (#2233)**
- **Added database to request discriminator (#2221)**
- **Implemented tracing for bulk row upsert (#2218)**
- **fixes #2201: remove obsolete ENSURE (#2216)**
- **ci: run relwithdebinfo and debug with build-preset labels too (#2245)**
- **Reading with a guarantee in case of autoscaling (#2128)**
- **Fix missing ToFlow in dict join (#2189)**
- **REST Monitoring API Support for CPU Load Control (#2229)**
- **Base flow for EvWrite with locks (#2234)**
- **Implemented tracing sampling by db (#2220)**
- **persqueue: add WRITE_ERROR_PARTITION_INACTIVE status code (#2241)**
- **KIKIMR-20543: ddl+dml in query service (#1444)**
- **Volatile transaction support in EvWrite (#2196)**
- **persqueue: extract common ut code, rename to autoscaling (#2255)**
- **New volatile EvWrite tests (#2253)**
- **Add TMPDIR to reducer and mapper enviroment (#2248)**
- **change large serializable test configuration (#2244)**
- **BTreeIndex Stats Visit top nodes only (#2177)**
- **add fullscan metric (#2192)**
- **resolves #1917: fix, add, unmute pgwire tests (#2213)**
- **YQ-2862 Add partition id to log (#2251)**
- **support search_path in SET too (#2261)**
- **YQ-2068 extract TTypeBuilder from TProgramBuilder to get rid of dependency on IFunctionRegistry (#2224)**
- **Fix partition helpers (#2281)**
- **Initial commit**
- **Fix copy table**
- **Fixes**
- **Fixes**
- **Fixes**
- **Fixes**
- **Fixes**
- **Fixes**
- **Initial commit**
- **Add copy**

2024-03-13 14:51 UTC, snaury commented on ydb/core/protos/flat_scheme_op.proto
> +    optional string CopyFromSequence = 11; // for copy sequence
Что-то мне прям не нравится такое поле CopyFrom. Потому что оно в Description'е не имеет никакого смысла, оно не описывает sequence. Лучше не засорять `TSequenceDescription` операциями, а сделать прям отдельное сообщение под `CopySequence`, в котором будет `CopyFrom`. И сделать чтобы для `CopySequence` указывается `Sequence` с описанием нового sequence который нужно создать и `CopySequence` с настройками копирования, типа откуда копировать.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        FreezeSequenceResult = ev->Get()->Record;
Нельзя сохранять это только в памяти. Более того, у тебя должен быть персистентный барьер, т.е. должен быть state типа FreezeSrcSequence, где мы отправляем TEvFreezeSequence, получаем результат, обязательно *персистим его*, и там же персистентно переходим в состояние RestoreSequences. И нужно сделать соответствующие значения в `TX_STATE_STATE_ENUM`. У тебя сейчас могут быть очень страшные гонки, когда несколько инстансов schemeshard'а могут несколько раз отправлять и freeze и restore, и в каком состоянии всё в итоге окажется - очень сложно будет понять. Здесь прям напрашиваются очень серьёзные тесты с ребутами.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        for (const auto& shardIdxProto : sequenceInfo->Sharding.GetSequenceShards()) {
Нужно отправлять не во все шарды, а только в тот где сейчас живёт src sequence.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        if (RestoredSequences > 1 && txState->ShardsInProgress.empty()) {
У тебя по этому условию всё может навечно зациклиться. Потому что повторный restore будет отвечать `SEQUENCE_ALREADY_ACTIVE`, а ты считаешь успехом только `SUCCESS`.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            context.OnComplete.BindMsgToPipe(OperationId, tabletId, txState->SourcePathId, event.Release());
Я кстати нигде не вижу UnbindMsgFromPipe, то есть сообщение будет на любых дисконнектах отправляться снова и снова, даже когда его уже не ожидают.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +                txState->TargetPathId, FreezeSequenceResult);
Восстанавливать оба sequence'а можно параллельно.

2024-03-13 14:51 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            auto event = MakeHolder<NSequenceShard::TEvSequenceShard::TEvFreezeSequence>(txState->SourcePathId);
А зачем мы вообще делаем freeze для src, если оно никаким образом не синхронизировано с копированием? Давай добавим запрос `TEvGetSequence`, результат такой неразрушающей операции можно будет и не персистить тогда.

Но сейчас оно кажется не будет правильно работать, потому что в процессе копирования таблиц CopySequence подоперации запускаются параллельно, и я не вижу никаких барьеров, которые бы синхронизировали восстановление sequence'ов строго после завершения копирования, и freeze до начала копирования. Если делать без freeze, то всё-равно должен быть барьер, и get + restore должен быть строго после завершения копирования. Я правда плохо понимаю как работают барьеры, из того что находится "RenamePathBarrier" - похоже синхронизирует дропы во время переименования таблиц. Вобщем барьеры явно очень нужны, и восстановление скопированного sequence'а должно быть обязательно после копирования таблицы.

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            ++shardsToCreate;
Выглядит как мёртвый код. Учитывая, что мы копируем sequence, у нас обязан быть хотя бы один sequence shard в базе.

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            sequenceShard = *domainInfo->GetSequenceShards().begin();
Учти, это это хеш таблица, и ты здесь можешь выбрать другой SequenceShard, не тот же самый что в оригинале. Я думаю проще всего было бы брать последний шард в `srcInfo->Sharding`, это то где sequence живёт прямо сейчас (в будущем предполагается, что они могут перемещаться между шардами во время балансировки), и копию создавать там же. Тогда с точки зрения транзакции действительно в tx state будет только один SequenceShard. Иначе нужно определять какой шард src, а какой dst.

2024-03-20 15:30 UTC, snaury commented on ydb/core/protos/tx_sequenceshard.proto
> +        bool Frozen = 10;
Имхо здесь можно без optional, потому что по умолчанию всегда false и никогда не поменяется.

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        });
Ты выше обрабатываешь `TEvCreateSequenceResult`, соответственно здесь он должен быть в ignore.

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            if (tabletId == InvalidTabletId) {
Если это тот же sequenceshard, что и src, то это условие лишнее. Мы не можем скопировать то, чего ещё не создали, а значит и таблетка должна уже существовать.

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_table.cpp
> +}
Кирпич в конце файла :)

2024-03-20 15:30 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +}
Кирпич в конце файла :)

2024-03-20 15:30 UTC, snaury commented on ydb/core/protos/flat_scheme_op.proto
> +    optional TSequenceDescription Sequence = 2;
Вообще выше уже есть поле Sequence. В TModifyScheme можно выставить и Sequence и CopySequence поля.

2024-03-20 16:41 UTC, ijon requested changes

2024-03-20 16:41 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +                // Treat all other replies as unexpected and spurious
Остальные ответы это что-то неизвестное или `TEvCreateSequenceResult::PIPE_OUTDATED` -- есть гарантия, что после таких ответов, и без каких бы то ни было действий/перепосылок со стороны schemeshard'а, sequenceshard затем пришлёт положительный ответ?

2024-03-20 16:41 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            TEvHive::TEvCreateTabletReply::EventType,
Здесь не нужен явный ignore `TEvHive::TEvCreateTabletReply`.

Таблетка создаётся в CreateParts, правильный `TEvHive::TEvCreateTabletReply` обрабатывается тогда же. Операция не может перейти к ConfigureParts, пока не отработает CreateParts. ConfigureParts явно глушит возможное "дребезжание" `TEvHive::TEvCreateTabletReply` (из-за рестартов всего что можно), но последующие state'ы это уже обычно не делают.
 
Spurious события, которые могут быть вызваны state'ом, обычно явно глушатся следующим state'ом, но не далее -- все последующие state'ы в своих ignore-списках все предыдущие события не повторяют.

2024-03-20 16:41 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            TEvHive::TEvCreateTabletReply::EventType,
Здесь не нужен явный ignore `TEvHive::TEvCreateTabletReply`.

2024-03-20 16:41 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +            TEvPrivate::TEvOperationPlan::EventType,
Здесь не нужны явные ignore `TEvHive::TEvCreateTabletReply` и `TEvPrivate::TEvOperationPlan`.

2024-03-21 08:17 UTC, snaury reviewed
В целом более-менее LGTM, но пусть ещё @ijon посмотрит.

2024-03-21 08:17 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        auto protoSequenceShard = *srcSequence->Sharding.GetSequenceShards().rbegin();
Обычно есть метод `back()`, который возвращает ссылку на последний элемент. Кроме того `auto` копирует протобуф, а тебе эта копия здесь не нужна, лучше `const auto&` ссылку сделать.

2024-03-21 08:20 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +                // Treat all other replies as unexpected and spurious
Имхо остальные ответы вряд ли имеют значение. Если там будет PIPE_OUTDATED, то мы по идее отправили новый запрос, и старый ответ не интересен. Я больше волнуюсь про то место где у тебя происходит get src и restore dst, вот там какие-нибудь повторы и гонки могут жизнь подпортить. В идеале было бы неплохо написать на копирование тест с ребутами, причём после завершения такого копирования проверять, что nextval действительно работает и возвращает ожидаемое значение.

2024-03-21 11:21 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +                // Treat all other replies as unexpected and spurious
Добавил проверку NextVal в TSequenceReboots::CopyTableWithSequence

2024-03-21 11:30 UTC, ijon submitted a review, later dismissed

2024-03-21 15:16 UTC, snaury commented on ydb/core/tx/schemeshard/ut_sequence_reboots/ut_sequence_reboots.cpp
> +            TestLs(runtime, "/MyRoot/copy/myseq", TDescribeOptionsBuilder().SetShowPrivateTable(true), NLs::PathExist);
Имхо TestLs также нужно выполнять в неактивной зоне.

2024-03-22 10:44 UTC, ijon approved these changes

2024-03-22 10:44 UTC, merged