YQ-2918: add processing speed statistics to logs
ydb-platform/ydb pull request #2720
Opened 2024-03-13 15:04 UTC by EgorkaZ

### Changelog entry 

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

2024-03-15 10:41 UTC, dorooleg requested changes

2024-03-15 10:41 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/internal/utils.cpp
> +    PrintSpeeds(builder, statistics.Stats);
Нужно две чиселки печатать. Одна скорость по статистике, а другая скорость на все выполнение query. Полное время выполнения query можно из query.meta достать

2024-03-15 10:41 UTC, dorooleg commented on ydb/core/fq/libs/compute/common/utils.cpp
> +static_assert(TDurationParser("41us").ParseDuration() == TDuration::MicroSeconds(41));
А это можем в _ut вынести чтобы не смешивать с реализацией?

2024-03-15 10:41 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/internal/utils.cpp
> +        builder << ", \"" << statName << postfix << "\": " << speed;
размерность бы к скорости дописать bytes/sec

2024-03-15 11:38 UTC, uzhastik approved these changes, later dismissed

2024-03-18 10:22 UTC, EgorkaZ commented on ydb/core/fq/libs/control_plane_storage/internal/utils.cpp
> +    PrintSpeeds(builder, statistics.Stats);
Времени выполнения по статистике нет в v2, сейчас вычисляется из времени начала в `job.meta()`. Вторая чиселка из `CpuTimeUs` в статистике: считаем скорость per cpu

2024-03-18 10:26 UTC, EgorkaZ commented on ydb/core/fq/libs/control_plane_storage/internal/utils.cpp
> +        builder << ", \"" << statName << postfix << "\": " << speed;
У нас и так названия полей выглядят как `IngressBytesPerSecond` / `IngressBytesPerCpuPerSecond`, плюс тут печаетется жсон, проще жить, когда его не надо дополнительно парсить

2024-03-18 12:01 UTC, dorooleg approved these changes

2024-03-18 12:25 UTC, merged