Add/terraform start
ydb-platform/ydb pull request #2725
Opened 2024-03-13 17:24 UTC by Pseudolukian

### Changelog category 
* Documentation (changelog entry is not required)

2024-03-18 07:42 UTC, blinkov requested changes

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +# Управление инфраструктурой и {{ ydb-short-name }} с помощью Terraform
```suggestion
# Разворачивание инфраструктуры для кластера {{ ydb-short-name }} с помощью Terraform

Существует три рекомендованных способа разворачивать кластера {{ ydb-short-name }} для production использования: c помощью [Ansible](ansible.md), [Kubernetes](kubernetes.md) или [вручную](../deploy/index.md). Если вариант с Kubernetes практически самодостаточен, то для вариантов с Ansible и вручную для старта нужен ssh доступ на необходимое количество правильно сконфигурированных серверов или виртуальных машин. В данной статье описывается как можно создать и сконфигурировать необходимый для кластера {{ ydb-short-name }} набор виртуальных машин в различных облачных провайдерах.
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +**Terraform** – это программное обеспечение с открытым исходным кодом от компании [HashiCorp](https://www.hashicorp.com) для управления инфраструктурой по модели "инфраструктура как код" (Infrastruct
```suggestion
**[Terraform](https://www.terraform.io/)** – это программное обеспечение с открытым исходным кодом для управления инфраструктурой по модели "инфраструктура как код" (Infrastructure as Code). Такой же подход используется в Ansible, в системе управления конфигурациями. Terraform и Ansible работают на разных уровнях: Terraform управляет инфраструктурой, а Ansible настраивает окружения на ВМ:
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +Блоки могут располагаться друг за другом в одном файле и быть независимыми, могут ссылать друг на друга и быть зависимыми, могут вкладываться друг в друга. Основные типы блоков:
```suggestion
Блоки могут располагаться друг за другом в одном файле и быть независимыми, могут ссылать друг на друга и быть зависимыми, а также могут вкладываться друг в друга.

Основные типы блоков:
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +* `resource` – блок инициализация ресурса инфраструктуры (ВМ, сеть, подсеть, диск, DNS-зона и т.д).
```suggestion
* `resource` – блок инициализация ресурса инфраструктуры (ВМ, сеть, подсеть, диск, DNS-зона и т.д.);
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +* `provider` – блок инициализация провайдера, версии API и данных для аутентификации.
```suggestion
* `provider` – блок инициализация провайдера, версии API и данных для аутентификации;
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +* `module` – логическая группировка ресурсов, которые можно переиспользовать несколько раз в рамках одного или разных проектов.
```suggestion
* `data` – переменная для запроса данных от внешних облачных ресурсов, не представленных в создаваемой инфраструктуре;
* `module` – логическая группировка ресурсов, которые можно переиспользовать несколько раз в рамках одного или разных проектов;
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +* `security` – модуль управления группами безопасности.
```suggestion
* `vpc` – модуль управления облачной сетью и подсетями;
* `dns` – модуль управления DNS-зоной и DNS-записями;
* `security` – модуль управления группами безопасности;
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +  }
```suggestion
  }
}
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +    path    = "/Applications/
Во-первых, выглядит как что-то MacOS-специфичное. Во-вторых, кавычка как-будто не закрыта. Оно вообще нужно?

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +С помощью Yandex Cloud провайдера можно не только создавать инфраструктуру для дальнейшего развертывания на ней YDB кластера с помощью [Ansible](./ansible.md), но и управлять [serverless или dedicate
это было б логичнее внутрь include'а yc.md перенести

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Создайте [аккаунт](https://console.aws.amazon.com) в AWS и пополните баланс на сумму достаточную для работы 9 ВМ. Рассчитать стоимость содержания инфраструктуры можно с помощью [калькулятора](https:/
```suggestion
Создайте [аккаунт](https://console.aws.amazon.com) в AWS и пополните баланс на сумму, достаточную для работы 9 ВМ. Рассчитать примерную стоимость содержания инфраструктуры в зависимости от региона и прочих обстоятельств можно с помощью [калькулятора](https://calculator.aws/#/createCalculator/ec2-enhancement).
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +* Скопируйте значение полей `Access key` и `Secret access key`.
```suggestion
* Скопируйте значения полей `Access key` и `Secret access key`.
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Установите [AWS CLI](https://aws.amazon.com/cli/) и выполните команду `aws configure`. Ввести значения полей `Access key` и `Secret access key` сохраненные ранее. Отредактируйте файлы `~/.aws/credent
```suggestion
Установите [AWS CLI](https://aws.amazon.com/cli/) и выполните команду `aws configure`. Введите значения полей `Access key` и `Secret access key` сохраненные ранее. Отредактируйте файлы `~/.aws/credentials` и `~/.aws/config` следующим образом:
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Перейдите в директорию `aws`, в скаченном репозитории и отредактируйте следующие переменные в файле `variable.tf`:
```suggestion
Перейдите в директорию `aws` в скачанном репозитории и отредактируйте следующие переменные в файле `variable.tf`:
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +* `terraform init` (повторное выполнение) – создание ресурсов в облаке.
```suggestion
* `terraform apply` (повторное выполнение) – создание ресурсов в облаке. 
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Далее используются команды `terraform plan`, `terraform init` и `terraform destroy` (уничтожение созданной инфраструктуры).
```suggestion
Далее используются команды `terraform plan`, `terraform apply` и, при необходимости уничтожения созданной инфраструктуры, `terraform destroy`.
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/azure.md
> +Создайте [аккаунт](https://portal.azure.com/#home) в Azure и пополните [счёт](https://portal.azure.com/#view/Microsoft_Azure_GTM/ModernBillingMenuBlade/~/BillingAccounts) аккаунта на сумму достаточну
```suggestion
Создайте [аккаунт](https://portal.azure.com/#home) в Azure и пополните [счёт](https://portal.azure.com/#view/Microsoft_Azure_GTM/ModernBillingMenuBlade/~/BillingAccounts) аккаунта на сумму, достаточную для работы девяти ВМ. Рассчитать примерную стоимость содержания инфраструктуры в зависимости от региона и прочих обстоятельств можно с помощью [калькулятора](https://azure.com/e/26977c150e854617a888fb3a7d1a399d).
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/gcp.md
> +1. Зарегистрируйтесь в Google Cloud console и [создайте](https://console.cloud.google.com/projectselector2/home) проект.
тут стиль оформления списком, а в соседних провайдерах абзацами — сделать единообразно

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/gcp.md
> +3. Активируйте [платежный аккаунт](https://console.cloud.google.com/billing/manage) и пополните его средствами для запуска девяти ВМ. Рассчитать стоимость можно в [калькуляторе](https://cloud.google.
```suggestion
3. Активируйте [платежный аккаунт](https://console.cloud.google.com/billing/manage) и пополните его средствами для запуска девяти ВМ. Рассчитать примерную стоимость содержания инфраструктуры в зависимости от региона и прочих обстоятельств можно с помощью [калькуляторе](https://cloud.google.com/products/calculator). 
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/gcp.md
> +6. Перейдите в поддиректорию `.../google-cloud-sdk/bin` и выполните команду `./gcloud compute regions list` для получения списка доступных регионов.
что троеточие тут значит?

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/gcp.md
> +4. Актируйте [Compute Engine API](https://console.cloud.google.com/apis/api/compute.googleapis.com/metrics) и [Cloud DNS API](https://console.cloud.google.com/apis/api/dns.googleapis.com/metrics).
```suggestion
4. Активируйте [Compute Engine API](https://console.cloud.google.com/apis/api/compute.googleapis.com/metrics) и [Cloud DNS API](https://console.cloud.google.com/apis/api/dns.googleapis.com/metrics).
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/azure.md
> +Аутентификация в провайдере Azure для Terraform осуществляется через CLI. Скачать, установить и настроить Azure CLI можно, следуя [этой](https://learn.microsoft.com/ru-ru/cli/azure/install-azure-cli)
что именно предполагается делать с ssh-keygen?

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/azure.md
> +* `auth_location` – название региона, где будет развернута инфраструктура. Список доступных регионов в зависимости от подписки можно получить командой `az account list-locations | grep "displayName"`
displayName — наверное человекочитаемое название? указывать в конфиге его надо или какой-то идентификатор?

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/azure.md
> +Значение остальных переменных можно оставить без изменения. Находясь в корневой директории Terraform сценария, выполните команду `terraform init` – будет установлен Terraform провайдер и инициализиро
рассказ про эту часть отличается от AWS выше, например про destroy нет — хорошо б единообразно сделать

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/gcp.md
> +1. Зарегистрируйтесь в Google Cloud console и [создайте](https://console.cloud.google.com/projectselector2/home) проект.
```suggestion
1. Зарегистрируйтесь в Google Cloud Сonsole и [создайте](https://console.cloud.google.com/projectselector2/home) проект.
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Создайте [аккаунт](https://console.aws.amazon.com) в AWS и пополните баланс на сумму достаточную для работы 9 ВМ. Рассчитать стоимость содержания инфраструктуры можно с помощью [калькулятора](https:/
тут и в аналогичных местах про другие провайдеры речь про 9 машин — надо видимо сделать сразу раздвоение инструкции на 9 машин в трёх AZ для кросс-ДЦ кластера и 8 машин в одной AZ для одно-ДЦ кластера, и явно про это говорить

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +## Создание инфраструктуры в AWS для развертывания {{ ydb-short-name }} кластера
прежде чем перейти к инструкциям надо рассказать какая топология кластера в них разворачивается и какая конфигурация ВМ/дисков

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/terraform.md
> +Конфигурация настройки окружения ВМ описывается в YAML формате, а инфраструктурный код пишется на [HCL](https://github.com/hashicorp/hcl) (язык разметки, разработанный HashiCorp). Основной логической
```suggestion
Конфигурация настройки окружения ВМ описывается в YAML формате, а инфраструктурный код пишется на [HCL](https://github.com/hashicorp/hcl) (язык конфигурации Terraform). Основной логической единицей записи в HCL является "блок". Блок состоит из ключевого слова, идентифицирующего его тип, названия и фигурных скобок, обозначающих тело блока. Например, так может выглядеть блок управления виртуальным сервером в AWS: 
```

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/yc.md
> +6. Настроить окружение AWS CLI:
а зачем тут AWS CLI в инструкции про YC?

2024-03-18 07:42 UTC, blinkov commented on ydb/docs/ru/core/getting_started/_includes/terraform/yc.md
> +* `terraform init` (повторный вызов) – создание ресурсов в облаке.
снова отличается эта часть

2024-03-18 08:58 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/terraform.md
> +## Создание инфраструктуры в AWS для развертывания {{ ydb-short-name }} кластера
Сделано.

2024-03-28 15:51 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/terraform/aws.md
> +Создайте [аккаунт](https://console.aws.amazon.com) в AWS и пополните баланс на сумму достаточную для работы 9 ВМ. Рассчитать стоимость содержания инфраструктуры можно с помощью [калькулятора](https:/
Пускай пока будет на 9 машин.

2024-03-28 15:53 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/terraform/yc.md
> +6. Настроить окружение AWS CLI:
Да, ты прав. Тут это не нужно.

2024-03-28 15:54 UTC, Pseudolukian commented on ydb/docs/ru/core/getting_started/_includes/terraform/yc.md
> +* `terraform init` (повторный вызов) – создание ресурсов в облаке.
Привел к единообразию.

2024-03-29 07:19 UTC, blinkov commented
Superseded by #3148

2024-03-29 07:19 UTC, closed without merging