YQL-17364: predicate pushdown for right side of left join. Resolves #2523
ydb-platform/ydb pull request #2964
Opened 2024-03-19 17:02 UTC by qrort

### Changelog entry 

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-03-19 18:12 UTC, qrort commented on ydb/library/yql/core/common_opt/yql_flatmap_over_join.cpp
> +    const bool isStrict = IsStrict(predicate);
Нужна консультация вот тут

2024-04-04 13:20 UTC, nepal requested changes
Нужны тесты в ydb/library/yql/tests/sql/suites/join/

2024-04-11 17:14 UTC, nepal requested changes

2024-04-11 17:14 UTC, nepal commented on ydb/library/yql/tests/sql/suites/join/left_join_right_pushdown_nested_right-off.cfg
> +providers dq
Зачем эти файлы -off?

2024-04-11 17:14 UTC, nepal commented on ydb/library/yql/sql/v1/context.h
> +        bool PragmaRightSidePushdownForLeftJoin = false;
Хочу другое название  FilterPushdownOverJoinOptionalSide - в будущем это будет применимо к full/exclusion join

2024-04-11 17:14 UTC, nepal commented on ydb/library/yql/ast/yql_expr.cpp
> +    settings.AllowFreeArgs = true;
Это ненужно

2024-04-11 17:14 UTC, nepal commented on ydb/library/yql/core/yql_join.h
> +std::pair<TExprNode::TPtr, TExprNode::TPtr> IsRightSideForLeftJoin(const TExprNode::TPtr& joinTree, const TJoinLabels& labels, ui32 inputIndex, const TExprNode::TPtr& parent = nullptr);
Чем не подходит первая функция? И точно ли она должна быть в этом файле - будет ли ее кто-то использовать вне твоего оптимизатора?

2024-04-11 17:14 UTC, nepal commented on ydb/library/yql/core/common_opt/yql_flatmap_over_join.cpp
> +    auto leftJoinTree = ctx.ShallowCopy(*leftJoinTreePtr);
Слишком часто используется ctx.ShallowCopy. Эту функцию очень редко когда надо использовать

2024-04-19 14:35 UTC, qrort commented on ydb/library/yql/tests/sql/suites/join/left_join_right_pushdown_nested_right-off.cfg
> +providers dq
Сделал по аналогии с другими тестами. видимо какая-то прагма выключается

2024-05-13 11:07 UTC, nepal requested changes

2024-05-14 14:17 UTC, qrort commented on ydb/library/yql/core/common_opt/yql_flatmap_over_join.cpp
> +                                            .Callable(1, "Null")
Переделал на Nothing (Member type)

2024-05-15 16:29 UTC, nepal submitted a review, later dismissed

2024-05-17 14:55 UTC, nepal approved these changes

2024-05-20 09:21 UTC, merged