Migrating from antlr3 to antlr4
ydb-platform/ydb pull request #2977
Opened 2024-03-19 23:46 UTC by OrlovPavel

### Changelog entry 

Grammar fix. Wrote some .stg to generate protobuf with antlr4 in the same format as at antlr3. Not tested with code yet.

### Changelog category 

* New feature
* Experimental feature

### Additional information

...

2024-03-25 15:16 UTC, dcherednik commented
Hi. Is you code ready to be compiled and run tests?

2024-06-29 09:39 UTC, nepal requested changes

2024-06-29 09:39 UTC, nepal commented on build/scripts/configure_file.py
> +            value = value.replace("#BACKSLASH#", "\\\\")
А зачем это нужно?

2024-06-29 09:39 UTC, nepal commented on ydb/library/yql/parser/proto_ast/gen/jsonpath/ya.make
> +        GLOBAL contrib/libs/antlr4_cpp_runtime/include
Почему здесь нужно добавлять antlr4 runtime, а для 3 этого не требовалось?

2024-06-29 09:39 UTC, nepal commented on ydb/library/yql/parser/proto_ast/gen/v1/epilogue.cmake
> +  ${CMAKE_SOURCE_DIR}/ydb/library/yql/sql/v1/SQLv4.g.in
Нейминг неудачный - грамматика у нас по прежнему имеет версию 1, просто в antlr4 синтаксисе. Лучше SQLv1_antlr4 или что-то в этом духе

2024-06-29 09:39 UTC, nepal commented on ydb/library/yql/sql/v1/sql.cpp
> +using namespace NSQLv4Generated;
В целом, мне этот PR нравится. Самое серьезное замечание такое.
Хотелось бы, чтобы возможность использования antlr4 грамматики была бы оформлена в виде feature флага. Примерно как это сделано с AnsiLexer. Т.е. antlr4 не заменяет сразу antlr3, мы должны иметь возможность переключаться между имплементациями:
1) для того чтобы выключить фичу на проде при возникновении проблем
2) чтобы сделать кросс валидацию двух парсеров на исторических запросах (на успешных запросах выходное аст должно совпадать

2024-06-29 19:53 UTC, OrlovPavel commented on build/scripts/configure_file.py
> +            value = value.replace("#BACKSLASH#", "\\\\")
В общем для разных версий грамматик (ansi и обычная) при сборке прокидывается переменная @GRAMMAR_STRING_CORE_DOUBLE@.
Для обычной версии там содержится следующее значение: 
```
~(QUOTE_SINGLE | BACKSLASH) | (BACKSLASH .)
```
Но в antlr4 нельзя брать дополнение для множества токенов, поэтому правило перепишется так:
```
~(["\\]) | (BACKSLASH .)
```
Но когда я пытаюсь в ya.make его прокинуть, то происходит неведомая мне хрень, а именно не вводятся слеши и кавычка.  Я так понял что введенная мной строка в ya.make идет на вход этому скрипту в аргументах вызова, я по всякому пытался заэкранировать, не получилось. Поэтому я в ya.make прокидываю такое:
 ```
 SET(GRAMMAR_STRING_CORE_DOUBLE "\"~([#DOUBLE_QUOTE##BACKSLASH#]) | (BACKSLASH .)\"")
 ```
И уже в скрипте костыльно вставляю нужные значения.
Если предложите способ нормально прокинуть слеш и кавычку, буду рад избавиться от этого костыля в скрипте.

2024-06-29 20:02 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/gen/jsonpath/ya.make
> +        GLOBAL contrib/libs/antlr4_cpp_runtime/include
Если честно, не помню наверняка, но кажется тут проблема была с тем что сборка не видела определений функций/классов рантайма

2024-06-29 20:13 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/gen/jsonpath/ya.make
> +        GLOBAL contrib/libs/antlr4_cpp_runtime/include
вспомнил: в antlr4_cpp_runtime были вложенные папки с файлами, которые инклудили внешние файлы. То есть путь как раз указывался относительно antlr4_cpp_runtime/include
В 3 такого не было, потому что там все свалено в одну папку

2024-06-29 20:48 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/gen/jsonpath/ya.make
> +        GLOBAL contrib/libs/antlr4_cpp_runtime/include
возможно я накосячил со сборкой как раз тут, потому что в yql/parser/proto_ast забыл в PEERDIR указать antlr4_cpp_runtime

2024-07-01 11:31 UTC, asmyasnikov commented on contrib/libs/antlr4_cpp_runtime/src/atn/HashUtils.h
кажется наличие каких-либо файлов в contrib - будет противоречить нашей бюрократии
contrib'ы должны 1-к-1 быть из яндексовой монорепы

2024-07-01 11:32 UTC, asmyasnikov commented on contrib/libs/antlr4_cpp_runtime/src/atn/HashUtils.h
Нельзя ли эти unitl перенести куда-то вовне contrib?

2024-07-01 11:32 UTC, asmyasnikov commented on contrib/libs/antlr4_cpp_runtime/src/tree/xpath/XPathLexer.g4
аналогично замечание/предложение по файлам в contrib

2024-07-01 11:33 UTC, asmyasnikov commented on contrib/libs/antlr4_cpp_runtime/src/atn/HashUtils.h
@nepal @vitstn провалидируйте меня плиз

2024-08-19 19:42 UTC, nepal requested changes

2024-08-19 19:42 UTC, nepal commented on ydb/library/yql/parser/proto_ast/proto_ast.h
> +        TString getTokenName(size_t type) const {
По аркадийному стилю методы класса называются с заглавной буквы

2024-08-19 19:42 UTC, nepal commented on ydb/library/yql/sql/v1/SQLv1.g.in
> +sql_query: sql_stmt_list | PRAGMA ANSI DIGITS ansi_sql_stmt_list;
Давайте эти изменения для совместимости с antlr4 закоммитим отдельным PR как мы раньше делали.

2024-08-19 19:42 UTC, nepal commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            switch (unifiedToken(token.GetId(), Context().Settings.Antlr4Parser)) {
Мне не очень нравится реализация unifiedToken. Во первых, тут везде доступен TContext Ctx, в котором есть информация каким парсером мы пользуемся. Я так понимаю для токенов antlr4/antlr3 есть взаимно однозначное соответствие и поэтому хотелось бы ссылаться только на какое-то универсальное имя
```
switch (TokenId(token.GetId()) {
.... case SQLv1Tokens::TOKEN_NOT:
}
```
TokenId - метод TTranslation

2024-08-19 19:43 UTC, nepal commented on ydb/library/yql/parser/proto_ast/gen/v0/ya.make
> +    GLOBAL contrib/libs/antlr4_cpp_runtime/src
А зачем в v0 нужны какие-либо изменения?

2024-08-22 22:31 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/gen/ya.make
> +    v1_antlr4
antlr4 сейчас генерит ровно тот же протобаф, так что нет смысла генерить код для работы со структурой AST еще и на antlr4. Да и к тому же затруднительно, по идее будут конфликты имен при сборке. В целом можно добавить v1_proto_split_antlr4, но везде все равно инклудить код из v1v1_proto_split

2024-08-22 22:33 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg.in
> +/*
Cpp.stg взял и модифицировал отсюда https://github.com/antlr/antlr4/blob/v4.11.1/tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
Java.stg тоже тут, но он целиком переделан под генерацию протобафа (просто в antlr4 нельзя передавать stg, у которых имя не как из официального репозитория) https://github.com/antlr/antlr4/blob/v4.11.1/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

2024-08-22 22:35 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/format/sql_format.cpp
> +    // ANTLR4-MIGRATION: just change SQLv1 to SQLv1Antlr4
да, запускал так и сяк, тесты проходят. В целом синтаксис лексера такой же остался, так что эта функция так же парсит лексемы

2024-08-22 23:09 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            switch (unifiedToken(token.GetId(), Context().Settings.Antlr4Parser)) {
С универсальным именем проблемка - в лексерах antlr3 и antlr4 разные порядки токенов в лексере (1 скрин - antlr3, тут по алфавиту, в antlr4 в порядке объявления в грамматике)
<img width="698" alt="Снимок экрана 2024-08-23 в 01 57 47" src="https://github.com/user-attachments/assets/c8fb43f0-a5d1-435b-8a12-78d0a8e0095e">
<img width="730" alt="Снимок экрана 2024-08-23 в 01 58 17" src="https://github.com/user-attachments/assets/822763a1-673f-483b-9203-e19131f19dde">
Причем порядок зашит в java код antlr, чем .stg его никак не проконтроллировать (в шаблон прилетает уже готовый список токенов). Я тут долго думал, как лучше сделать, в итоге это показалось самым оптимальным решением, исходя из моих ресурсов.
Щас еще подумал, можно распарсить грамматику, достать все токены, и через сортировку получить мапинг айдишников, и но на это нужно будет выделить время. Как лучше всего распарсить получить содержимое грамматики в рантайме, через `Y_ENSURE(NResource::FindExact(...`?

2024-08-23 00:11 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/SQLv1.g.in
> +sql_query: sql_stmt_list | PRAGMA ANSI DIGITS ansi_sql_stmt_list;
https://github.com/ydb-platform/ydb/pull/8186 - эти изменения не затрагивают код yql если что, только грамматика as is

2024-08-27 11:43 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            switch (unifiedToken(token.GetId(), Context().Settings.Antlr4Parser)) {
Вопрос не про номер токенов, код их не использует. А про то, как оно используется в коде 

>поэтому хотелось бы ссылаться только на какое-то универсальное имя

2024-08-27 11:56 UTC, nepal commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            switch (unifiedToken(token.GetId(), Context().Settings.Antlr4Parser)) {
Предлагается сделать некий препроцессорный макрос который по общему имени токена типа CONNECT вернет пару айдишников: std::make_pair(SQLv1Lexer::CONNECT, SQLv1LexerTokens::TOKEN_CONNECT);
И дальше будет функция UnifiedToken которая по этой паре возвращает первый или второй id в зависимости от текущей настройки useAntlr4 в Ctx

2024-08-27 11:58 UTC, vitstn commented on ydb/library/yql/sql/v1/format/sql_format_ut.cpp
> +        settings.Antlr4Parser = true;
нужно сделать 2 сьюта с одинаковым набором тестов - один с antlr3, другой с antlr4

2024-08-27 11:59 UTC, vitstn commented on ydb/library/yql/sql/v1/lexer/ya.make
> +    ydb/library/yql/parser/proto_ast/gen/v1_ansi_antlr4
нужен proto_split вариант для antl4 вариантов protobuf, иначе очень медленная компиляция

2024-08-28 22:41 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/format/sql_format_ut.cpp
> +        settings.Antlr4Parser = true;
done

2024-08-28 22:46 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            switch (unifiedToken(token.GetId(), Context().Settings.Antlr4Parser)) {
Здесь вроде навел красоту, посмотрите, плиз. Но как бы UnifiedToken осталась той же, в case стейтменте должен быть constexpr, поэтому туда нельзя пропихнуть что-то, что зависит от useAntlr4 в Ctx, это не вычислимо в compile time

2024-08-30 14:43 UTC, vitstn commented on ydb/library/yql/parser/proto_ast/gen/ya.make
> +    v1_antlr4
нее, без разбиения код крайне медленно собирается (до 15 минут)
оба, antlr3 и antlr4 должны входить в sql парсер в поспличенном виде.

оно не вызывает никаких конфликтов, просто дробит большие .h/.cpp файлы на меньшие

2024-08-30 14:44 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_query.cpp
> +                    (UnifiedToken(rule.GetBlock4().GetToken1().GetId()) == ANTLR3_TOKEN(IF) &&
это невозможно поддерживать
нужно сделать макрос, который сам проверяет на тот или другой токен

2024-09-02 09:34 UTC, vitstn commented on ydb/library/yql/sql/v1/format/sql_format_ut_antlr4.cpp
> +    Y_UNIT_TEST(GrantPermissions) {
Не надо тут делать копию всего файла. Нужно было в sql_format_ut.cpp сделать 2 сьюта - один на antlr3 опции гоняется, другой на antlr4.

2024-09-02 09:39 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            case ANTLR3_TOKEN(LESS):
CHECK_TOKEN

2024-09-02 09:49 UTC, nepal commented on ydb/library/yql/sql/v1/sql_expression.cpp
> +            case ANTLR3_TOKEN(LESS):
Да
1) везде использовать if (CHECK_TOKEN) вместо case
2) предлагаю переименовать CHECK_TOKEN -> IS_TOKEN (непонятно что мы там проверяем в токене)

2024-09-02 19:11 UTC, OrlovPavel commented on ydb/library/yql/parser/proto_ast/gen/ya.make
> +    v1_antlr4
Еще раз, здесь есть такая сборка в папочке v1_proto_split_antlr4, просто она генерит ровно тот же код (!) что и текущий v1_proto_split, потому что на antlr4 генерится ровно та же .proto схема что и на antlr3. Я подписал комментом, что когда будете закапывать antlr4, просто поменяйте v1_proto_split на v1_proto_split_antlr4 везде и все, все будет работать, локально проверял. Щас генерить тот же код по два раза смысла не вижу

2024-09-04 14:24 UTC, nepal approved these changes

2024-09-04 14:43 UTC, asmyasnikov approved these changes

2024-09-04 14:48 UTC, maximyurchuk approved these changes

2024-09-04 14:56 UTC, fomichev3000 approved these changes

2024-09-04 14:57 UTC, merged