Support sequences backup with current value
ydb-platform/ydb pull request #3089
Opened 2024-03-22 12:56 UTC by shnikd

- **Intermediate changes**
- **[build] Very basic ROSMSG_LIBRARY implementation**
- **Update contrib/python/MarkupSafe/py3 to 2.1.5 c95a7bd6addacfa0dd622f5719405eccc20c4f9d**
- **Disable VMS-specific include 6564a7a5fe05ac710cc53b10e5f84f8abfc3282d**
- **Disable VMS-specific includes 66d95dd207fc74603ea1ede079236c2ffdfb0962**
- **Update contrib/restricted/abseil-cpp-tstring to 20240116.1 64836c9ee655ebce1111df73240a57173e324fbd**
- **Disable VMS-specific includes bf43b0733be8e25edb2cae010fffc7aa15f192f2**
- **Disable VMS-specific include 9be65ee4c604482641d7219b1923056002dbe557**
- **Restore vxworks.yml in unused directory, move stl-to-microsoft-stl.yml there ee3320b4f4fa139860d1f4e739bfcfaea63fa81a**
- **Intermediate changes**
- **External build system generator release 79**
- **Intermediate changes**
- **Revert commit rXXXXXX, External build system generator release 79 bee13caec5ff36f539d9a6dbebef6bb927be2b53**
- **Enable perf trampoline 9ea3344aaff84779f6f3eea0c3cfb785c49857a7**
- **Remove empty resolving of VMS-specific includes 0983a1c6d37304d05284e57d9dd2943bfd69c1fc**
- **Sync contrib/tools/python3 layout with upstream**
- **Automatic release build for ymake, os_ymake**
- **Intermediate changes**
- **New version of the tld SKIP_CHECK SKIP_REVIEW 76faaa2be1a95a3ba117ecb4d48e22eac0360f99**
- **Remove generated cmake export a77fe1f94bbaae95032bf35372e78452d3c82d62**
- **Intermediate changes**
- **Restore external build system generator release 79**
- **YT-21001: FiberContext::BeforeSwitch is now properly inlined**
- **Disable OS/2-specific includes e21b66cb2289e5105bdf9ce752b5c3e9be219720**
- **Intermediate changes**
- **Move empty macro definition for generic _SRC 7fa177d028e57853c2a3fb87ccbb50d30b0be280**
- **Testdep attribute for dependency to test (from test or from module) 44019bde8cdb78f2629f869e7ff10637b7b6d72c**
- **Intermediate changes**
- **Drop support for CUDA 10.1 149e3a68203cb3ceee7973c8ff6b90b77865a478**
- **Curl lib fix from https://github.com/curl/curl/pull/12633**
- **Disable OS/2-specific includes f5b4da0f22a2a1fa5790298ebe33ad52c5edf6dd**
- **Disable OS/2-specific includes eef0f71ed8d928bf5c681a10238054e4e681d149**
- **feat yamake: use json for choosing config for ruff linter 38f291cca1eb7eea40d55a4ce5e4048caaf89372**
- **External build system generator release 80**
- **get rid of six faeb2c69960c197db9fc9c5d0696d6dc0ce3d74a**
- **Use global ns for TFlags e2d4d0cc183a95092f8a3924a5992ba09b6dc670**
- **Remove JDK 19 support from Arcadia Tier 0, remove build configuration for JDK c6a795a78f562c87f8d5cb8f4368c9aae260d88b**
- **Cleanup Nebius scraps d7075afada477cdc78d0290bb6816149776960fe**
- **Stop resolving OS/2-specific includes into nothing b28e4a0e6d846860a7bc859603c914959d3f37f1**
- **Intermediate changes**
- **Remove empty resolving of ghostscript headers 835ec1d00a7a4bb8df26d2ffe7398613170308d1**
- **Disable gnutls includes as we do not build anything against gnutls 4aa18b964a97b3ef71bf2b10f761ef6d54a2ed1b**
- **Intermediate changes**
- **Update contrib/libs/expat to 2.6.0 fc2141441ca875a02bd88f7848e5c71f5aa291c9**
- **Intermediate changes**
- **Automatic release build for ya_bin3, os_ya, ya_bin, test_tool, os_test_tool_3, test_tool3**
- **fix ruff: cache workaround ab4d963587a138f7006ed415c33a2dc8c35a75d8**
- **Intermediate changes**
- **feat ruff: add ruff to style tests aeba57eadc612011e5a96b4b7b10a2a53241fc90**
- **Bump nvcc standard from c++14 to c++17 23d94513fcce0bb86893603e21c9ebe3371449e4**
- **Intermediate changes**
- **--allow-unsupported-compiler in CMake builds as well. cf3c73bf342badefc42ab0534406f91757b2191e**
- **Bump nvcc standard from c++14 to c++17 in CMake build as well. b1699a2ea485dcc5ef5eadd888508c49c5659e46**
- **[build/scripts/cat.py] Fixed py23 compat**
- **Update NVIDIA CUTLASS to 3.4.0 69d9dd965f224dde72833bd81cb092ad362633ea**
- **Intermediate changes**
- **Fix case when 'arc export' not set executable bit**
- **Remove dead code 126c0cfa83378569f6fcef85a64a147009117de2**
- **Intermediate changes**
- **Update libcxx to llvmorg-17.0.6**
- **Generate more sysincls for libcxx beabd8a4b5f3d5c7121be41d46ecef01e59fb04a**
- **Automatic release build for ymake, os_ymake**
- **Remove empty resolving of gnutls includes 091fdecb2d190083296fb2cbcc59ab8588f08238**
- **Intermediate changes**
- **Try to re-enable tcmalloc with sandboxing b823b6f10cfce76810e81f5c4a3167bc1abb7726**
- **Refactor with_kotlin(c) from bool to flags**
- **Automatic release build for ya_bin3, ya_bin, os_ya, test_tool, os_test_tool_3, test_tool3**
- **Intermediate changes**
- **New version of the tld SKIP_CHECK SKIP_REVIEW 5383f45f0d7fadf7fe1f72830869c4caa770749b**
- **Disable Solaris-specific includes 6d29fb9ac3025811a6d0c5b1d5ec6a09f6c5ab20**
- **fix windows build (#2167)**
- **fix throwing exceptions on incorrect error message construction (#2160)**
- **clean TUnifiedBlobId. prepare for use TLogoBlobId only (#2171)**
- **Generate bindings (#2187)**
- **[YQL-17789] Pull ReplicateScalars through WideMap and DqPhyStage boundary (#2159)**
- **allow free arguments in FormatCode (#2153)**
- **Disable Solaris-specific includes a83bc72d0ef12e761de9aa4b197f744d0e6eff02**
- **YQL-17729, YQL-17588: module & UDF resolver in pgrun (#2175)**
- **Weekday Generation From Civil Second**
- **split methods for stages execute/complete usage in case modification (#2166)**
- **Support storage quorum when applying configuration (#2173)**
- **Query service execute script parameters (#2193)**
- **[build] Add support for -DUSE_SYSTEM_PYTHON=3.12 () dcae461cba9f97679c7bd5b3e34c42ac0d58bfed**
- **actors for saving/loading of per-column statistics (#2195)**
- **Disable partial Sorted constraints (#2194)**
- **fix build clang14 (#2199)**
- **YQL-17315: PG regression tests' deps (#2154)**
- **Intermediate changes**
- **Update jdk11 to jdk-11.0.21+9 with tzdata2024a fa66344de8e9d0b487bd88412f508eb926d0e9cf**
- **lower time difference issues from red to orange (#2197)**
- **Intermediate changes**
- **Revert commit rXXXXXX, Update jdk11 to jdk-11.0.21+9 with tzdata2024a 2df32fd11edec909afc8dc67a188ca41c1f4c013**
- **fix blobstorage build clang14 (#2202)**
- **Import from S3: check error is retriable KIKIMR-21102 (#2198)**
- **YDB-1066 Added healthcheck RED issue for no pools in database (#2098)**
- **YDB-1453 added CORS headers to healthcheck handler (#2174)**
- **fix style tests (#2206)**
- **chore: add gcc-arm-none-eabi-10.3-2021.10 (also for arch armv5te & cpu arm968e-s) 7842519b34c6d72b2e0cb11e60456cf2513bc6d6**
- **CMake14 build (#2207)**
- **partitioning has been fixed YQ-2789 (#1538)**
- **Fix memory usage for heavy normalizers (#2204)**
- **YDB Import 569 32a3bf6b3ca0706c3644c01a7d0885db6cdb2fc3**
- **fix bug with table (#1998)**
- **YQL-17315: PG test table deps, part 2 (#2209)**
- **resolves #2078: sort YdbResults via ColumnHints (#2210)**
- **tasklet/api/_.proto => tasklet/v1/api/_.proto 4be874c62873a2d7ef498a33d9fe2d339748cb61**
- **external table content has been decoded for viewer KIKIMR-18798 (#1281)**
- **Fix typo (#2214)**
- **Make queries 36,70,86 pg-compatible (#2215)**
- **Add logg for string that was not parsed.**
- **Disable Solaris-specific includes e7c11f991664180895c1df3f22fc2b706accca67**
- **Disable Solaris-specific includes 4d7a5caf7339d32a0f45a35e4ec158c4f2bb9ce8**
- **fix incorrect tests implementation (#2212)**
- **Base transaction class for all propose operations (#2208)**
- **Intermediate changes**
- **Remove unnecessary patch**
- **Remove unused patch from contrib/tools/python3**
- **Disable Solaris-specific includes 9212dd8d85380149b5945c3b5c8f73210e8e25ca**
- **Intermediate changes**
- **Disable Solaris-specific includes 4f153b26762c99335ff9614130e0b7511138685b**
- **New version of the tld SKIP_CHECK SKIP_REVIEW 7f74579a194296c8b3e8c263bfd3d35de08cce9d**
- **Fix TzTimestamp wrong encoding (YQL-17920) (#2222)**
- **Intermediate changes**
- **Automatic release build for ymake, os_ymake**
- **[PG Syntax] Added ydb pragma support ( [...]

2024-03-22 13:21 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        descr.SetStartValue(GetSequenceResult.GetNextValue());
I think I said it already, that you can't store current values in the schema. Current sequence value is data, not schema. When you describe table before backing up, then backup and restore, you should see the same describe table result as you did before backing up.

2024-03-22 14:51 UTC, ijon requested changes

2024-03-22 14:51 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
> +        task.MutableTable()->CopyFrom(exportDescription);
Для чего изменение? -- казалось бы, добавление sequence в бекап не должно никак менять общий flow бекапа.

2024-03-22 15:19 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        descr.SetOverflowed(overflowed);
А кстати написал как оно должно работать (с учётом того как работает postgres), перепроверил, а внезапно сейчас работает не так. Я видимо пытался сделать чтобы там всегда было NextUsed == false, а учитывая что это фактически аналог is_called, это значение на самом деле очень важно с точки зрения всяких lastval/currval, и похоже нужно исправлять.

2024-03-25 10:47 UTC, snaury commented on ydb/core/protos/tx_sequenceshard.proto
> +    oneof OptionalSetVal {
Во первых для полей вида `TSetVal` не нужно optional, они уже всегда optional. Во вторых этот oneof был workaround'ом для старого proto3, где нельзя было писать optional. Так что тут нужно просто писать `TSetVal SetVal = 11` и в коде проверять через `HasSetVal`.

2024-03-25 10:47 UTC, snaury commented on ydb/public/api/protos/ydb_table.proto
> +message SetVal {
Давай перенесём внутрь `SequenceDescription`.

2024-03-25 10:47 UTC, snaury commented on ydb/core/protos/flat_scheme_op.proto
> +message TSetVal {
Имхо лучше унести внутрь `TSequenceDescription`.

2024-03-25 10:47 UTC, snaury commented on ydb/core/protos/tx_sequenceshard.proto
> +message TSetVal {
Имхо лучше унести внутрь `TEvCreateSequence`.

2024-03-25 10:47 UTC, snaury commented on ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
> +        auto* setValMsg = descr.MutableSetVal();
Насколько я вижу здесь меняется `sequenceInfo->Description`. Но это данные sequence'а, они могут постоянно меняться, их нельзя сохранять в схеме! Нужно это поле заполнять в специальной форме дескрайма (например когда делаем import), которая сходит за текущими значениями и вернёт их.

2024-03-28 09:29 UTC, snaury reviewed
Думаю LGTM. Из совсем мелкого меня смущает, что ReturnSetVal будет возвращать не текущее значение sequence'а, а какое-то там старое, которое делали во время его создания, но это не публичное апи и потому не важно. В будущем кому-нибудь нужно будет сделать возможно получения правильного текущего set_val в публичном апи, чтобы правильно бекапить таблицы с sequence'ами можно было не только на сервере, но и локально в файлики, но точно не в этом pr.

2024-03-29 12:35 UTC, ijon approved these changes

2024-03-29 13:01 UTC, merged