add support for yql resources in arrow blocks
ydb-platform/ydb pull request #3116
Opened 2024-03-25 06:57 UTC by fedor-miron

### Changelog entry 

Added support for YQL resources in Arrow blocks. Add managed buffer for types with non-trivial destructors

### Changelog category 

* Improvement

2024-03-25 17:34 UTC, vitstn commented on ydb/library/yql/minikql/mkql_type_builder.cpp
> +    static const bool ImplementedForResources = false;
Unclear semantic of such flag

2024-03-25 17:38 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/block_builder.h
> +    std::unique_ptr<TTypedBufferBuilder<TLayout>> DataBuilder;
destructor should call destructor of UV in DataBuilder

2024-03-25 17:39 UTC, nepal requested changes, later dismissed

2024-03-25 17:39 UTC, nepal commented on ydb/library/yql/public/udf/arrow/block_builder.h
>  class TFixedSizeArrayBuilder final : public TArrayBuilderBase {
Мне кажется надо сделать отдельный билдер для ресурсов. Как минимум новый билдер должен деструкторы звать

2024-03-25 17:40 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/block_builder.h
> +    using TBuilder = TFixedSizeArrayBuilder<TUnboxedValue, Nullable,
please use distinct class TResourceArrayBuilder - it has too many differences to POD builder

2024-03-25 17:55 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/block_item.h
> +    inline TStringRef GetEmbeddedStringRef() const {
I don't see any constructor that can initialize such state: EMarkers::Embedded. BlockItem(TStringRef value) sets EMarkers::String

2024-03-26 09:19 UTC, fedor-miron commented on ydb/library/yql/public/udf/arrow/block_builder.h
>  class TFixedSizeArrayBuilder final : public TArrayBuilderBase {
Деструкторы зовет ManagedBuffer здесь https://github.com/ydb-platform/ydb/pull/3116/files#diff-e636d2a5068525a81197ad5b1595c3716f92f9109aada6a0e27a834b9694da54R114
Билдеру не нужно звать деструкторы

2024-03-26 18:37 UTC, fedor-miron commented
Все поправил

2024-03-27 18:53 UTC, vitstn approved these changes, later dismissed

2024-03-29 09:41 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_block_reader.cpp
> +        if (item.IsEmbedded()) {
resource can be a StringValue too

2024-03-29 09:41 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_block_reader.cpp
> +        if (value.IsEmbedded()) {
the same

2024-03-29 14:40 UTC, nepal approved these changes, later dismissed
LGTM

2024-03-29 17:07 UTC, vitstn approved these changes

2024-03-29 18:04 UTC, merged