Ru documentation for automatic secondary indices usage
ydb-platform/ydb pull request #3131
Opened 2024-03-25 12:29 UTC by ssmike

### Changelog category 

* Documentation

2024-03-25 12:36 UTC, gridnevvvit commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +На данный момент механизм является экспериментальным и доступен только после включения в конфигурации базы.
как включить будет описано? стоит занести в warn секцию. как предупреждение

2024-03-25 12:44 UTC, ssmike commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +На данный момент механизм является экспериментальным и доступен только после включения в конфигурации базы.
Да, я пока не нашел доку про нашу конфигурацию в целом чтобы сделать ссылку

2024-03-26 06:49 UTC, blinkov requested changes

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/secondary_indexes.md
> +Однако, реализован [экспериментальный механизм](../index_choosing.md) принимающий решение о использовании индексов.
а зачем про него отдельная статья вместо рассказа прямо тут?

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +Однако популярные базы данных как правило предоставляют возможность автоматического использования индексов в запросах исходя из определенной некоторым образом оптимальности результирующего плана выпо
Эта историческая справка подходит скорее для формата анонса в блоге, а не документации.

Тут должен быть более по существу рассказ о текущем состоянии, мол по умолчанию в YDB вторичные индексы не используются и надо либо явно указывать индекс так-то, либо включить такую-то экспериментальную настройку для выбора автоматически.

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +## Алгоритм выбора
Рассказ про «под капотом» вынести в отдельную статью для любознательных и контрибьюторов.

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +На данный момент механизм является экспериментальным и доступен только после включения в конфигурации базы.
Полной справки по настройкам на данный момент и правда не существует, но не смотря на это всё же важно указать какую нужно менять именно тут.

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +Ранее YDB требовал явного указания вторичного индекса для использования в запросе.
```suggestion
Ранее {{ ydb-short-name }} требовал явного указания вторичного индекса для использования в запросе.
```
здесь и ниже по аналогии

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +## Алгоритм выбора
Плюс ниже скорее просто описание проблематики, а не конкретного реализованного алгоритма. Тут бы какая-то структура текста не помешала, условно:
1. Введение с обзором проблематики
2. Подготовительные шаги, которые нужны для принятия решения
3. Метрики, которые используются для принятия решения
4. Сам алгоритм (последовательность шагов) по которым принимается решение

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +select * from `Table` where (Key1, Key2, Key3) < ($param1, $param2, $param3) and (Key1, Key2) > ($param4, $param5)
в примерах ключевые слова обычно делают в CAPS LOCK

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +<!-- При этом накладываются дополнительные ограничения на способы требующие джойна с основной таблицей -- рассматриваются только точечные чтения. -->
не понятно почему эта фраза в комментарии

2024-03-26 06:49 UTC, blinkov commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +оптимизатор определит что чтение может производиться в диапазоне
тире пишется как «—», а не два минуса

2024-03-26 15:40 UTC, ssmike commented on ydb/docs/ru/core/best_practices/_includes/index_choosing.md
> +оптимизатор определит что чтение может производиться в диапазоне
Мой редактор маркдауна счтал что два минуса это тире. Исправлю. А существует редактор именно для yfm?

2024-04-23 10:02 UTC, blinkov commented
@ssmike, when can we expect the next iteration? Also, it needs to be merged with `main`.

2024-05-23 05:16 UTC, blinkov commented
@ssmike, ping

2024-08-08 10:34 UTC, blinkov requested changes
Т.к. содержательных вопросов пока много сам текст ещё не вычитывал.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +Включение данного механизма производится с помощью [настройки в table_service_config](https://github.com/ydb-platform/ydb/blob/main/ydb/core/protos/table_service_config.proto#L268)
Я бы ожидал ещё какой-то способ включать-выключать на лету через `PRAGMA` и подобное — он существует или только через явное указание `VIEW`?

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +SELECT * FROM `Table` VIEW PRIMARY KEY
Этот кусок частично повторяет https://ydb.tech/docs/ru/dev/secondary-indexes#use, причём про `VIEW PRIMARY KEY` там нет. Предлагаю чтобы не дублироваться дописать про `VIEW PRIMARY KEY` в старый текст, а автоматический выбор индекса сделать разделом в secondary-indexes.md вместо отдельной статьи. В этом случае примеры можно убрать под `{% cut %}`, чтобы не раздувать основной текст.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +YDB на данный момент не умеет оценивать оптимальность плана выполнения ввиду отсутствия статистик данных, и автоматический выбор делается исключительно исходя из текста запроса. Оптимальность для кон
Насколько я понимаю первая версия cost-based optimizer на финишной прямой, там как раз собираются и используются статистики по данным, и скоро про неё тоже будет дока. Хорошо бы тут какую-то согласованную позицию выработать, мол cost based optimizer есть, но в выборе индексов пока не участвует, или вроде того. 

@pavelvelikhov @spuchin @gridnevvvit как думаете тут лучше написать?

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +Для явного указания чтения без индексов
Первичный ключ — тоже по сути индекс, лучше не забывать уточнять где речь именно про вторичные.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +Способы чтения ранжируются между собой в соответствии с критерием 2, при равенстве с критерием 3 и дополнительно учитывается критерий 1.
Фальш-старт с примерами: раз уж следом есть большой раздел с примерами — лучше это туда.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +     Fk2 String,
Fk звучит как аббревиатура от `FOREIGN KEY`, которых у нас пока нет, я бы рекомендовал не давать ложных надежд и переименовал условно в `SecondaryKey1`.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +Выбор способа чтения происходит во время оптимизации запроса при определении диапазона(ов) строк, которые необходимо прочитать (predicate pushdown). Индексы, как и основная таблица представляют из се
При виде фразы «выбор способа чтения» представляется скорее что-то в духе выбора между read, epoll и io_uring, а тут всё же про выбор индексных таблиц как-будто.

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +1. Необходимость дополнительного чтения из основной таблицы -- в индексе могут присутствовать все нужные для запроса колонки. В этом случае дополнительные чтения необязательны.
Это не звучит как алгоритм, что заявлено в заголовке. Это скорее список вещей, на которые этот алгоритм смотрит. От описания алгоритма я бы примерно такого стиля изложения ожидал:

1. Если существует вторичный индекс, в котором присутствуют все нужные для запроса колонки, то запрос выполняется посредством чтения из этого индекса без использования основной таблицы. Если таких индексов существует несколько, то какой использовать выбирается так-то.
2. ...

Либо если так подробно описать слишком сложно, то хотя б раздел переименовать без использования «алгоритм».

2024-08-08 10:34 UTC, blinkov commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +Включение данного механизма производится с помощью [настройки в table_service_config](https://github.com/ydb-platform/ydb/blob/main/ydb/core/protos/table_service_config.proto#L268)
Плюс тут первым делом нужен `{% note %}`, что фича экспериментальная, а также явно написать название настройки, чтоб не заставлять людей кликать и втыкать в протобуф.

2024-08-22 16:48 UTC, spuchin commented on ydb/docs/ru/core/dev/automatic-index-choosing.md
> +YDB на данный момент не умеет оценивать оптимальность плана выполнения ввиду отсутствия статистик данных, и автоматический выбор делается исключительно исходя из текста запроса. Оптимальность для кон
Я бы просто написал что в YDB сейчас выбор индекса делается на основе rule-based подхода, не вдаваясь в подробности почему.

2024-08-26 08:40 UTC, ssmike commented
@blinkov ping

2024-09-03 03:50 UTC, blinkov submitted a review, later dismissed

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +{% endnote %}
```suggestion
### Автоматическое использование индексов при выборке

{% note warning %}

Данный механизм является экспериментальным и по умолчанию пока выключен. Его включение производится с помощью [настройки `index_auto_choose_mode` в `table_service_config`](https://github.com/ydb-platform/ydb/blob/main/ydb/core/protos/table_service_config.proto#L268).

{% endnote %}
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Данный механизм является экспериментальным и по умолчанию пока выключен. Включение данного механизма производится с помощью [настройки index_auto_choose_mode в table_service_config](https://github.co
А на query service эта настройка будет влиять? Сейчас вся дока в процессе переписывания на него.

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Явное указание секции `VIEW` имеет приоритет над решением оптимизатора о использовании вторичных индексов. То есть запрос
Сейчас есть параллельно открытый PR про оптимизатор запросов в целом https://github.com/ydb-platform/ydb/pull/8522 — хорошо б не забыть их потом скрестить.

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Для явного указания чтения с использованием primary key следует использовать следующую конструкцию:
```suggestion
Для явного указания чтения с использованием первичного ключа следует использовать следующую конструкцию:
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Выбор индекса используемого для чтения происходит во время оптимизации запроса при определении диапазона(ов) строк, которые необходимо прочитать (predicate pushdown). Индексы, как и основная таблица
```suggestion
Выбор индекса используемого для чтения происходит во время оптимизации запроса при определении диапазонов строк, которые необходимо прочитать (predicate pushdown). Индексы, как и основная таблица представляют из себя набор строк упорядоченных по набору ключевых колонок.
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Выбор между чтениями с использованием индекса и c использованием primary key происходит на основе следующих метрик:
```suggestion
Выбор между чтениями с использованием индекса и c использованием первичного ключа происходит на основе следующих метрик:
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +1. Необходимость дополнительного чтения из основной таблицы — в индексе могут присутствовать все нужные для запроса колонки. В этом случае дополнительные чтения необязательны.
```suggestion
1. Необходимость дополнительного чтения из основной таблицы. Если в индексе присутствуют все нужные для запроса колонки, то дополнительные чтения не требуются.
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +2. Длина точечного префикса предиката для ключа соответствующей таблицы. То есть, предикат ограничивает некоторый набор колонок являющихся первыми компонентами ключа точечными условиями: =, in, is nu
```suggestion
2. Длина точечного префикса предиката для ключа соответствующей таблицы. То есть, предикат ограничивает некоторый набор колонок являющихся первыми компонентами ключа точечными условиями: `=`, `IN`, `IS NULL`. Здесь приоритет отдается индексам, для которых зафиксированы все индексируемые колонки или основной таблице если точечным является первичный ключ целиком.
```

2024-09-03 03:50 UTC, blinkov commented on ydb/public/lib/ydb_cli/commands/ydb_workload.cpp
> +            .PoolId("default")
выглядит несвязанным изменением

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +3. Количество использованных колонок в границах диапазона для чтения. В следующем запросе к таблице Table с первичным ключом (Key1, Key2, Key3)
https://github.com/ydb-platform/ydb/pull/3131#discussion_r1709148027 — не исправлено

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +CREATE TABLE `/Root/Table` (
Зачем тут абсолютный путь с `/Root`?

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +```
дописать yql после бектиков, чтобы подсветка синтаксиса включилась

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +`SELECT * FROM Table WHERE Key = $p1 and SubKey1 = $p2 And SubKey2 = $p2` - При выборе скана основной таблицы используется все 3 колонки `[Key, Fk1, Fk2], длина точечного префикса 3. Индекс должен не
```suggestion
`SELECT * FROM Table WHERE Key = $p1 and SubKey1 = $p2 And SubKey2 = $p2` — При выборе скана основной таблицы используется все 3 колонки `[Key, Fk1, Fk2]`, длина точечного префикса 3. Индекс не будет использоваться.`
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +`SELECT * FROM Table WHERE Key = $p1 and SubKey2 = $p2` - при выборе любого индекса используется 1 колонка, точечный префикс также не более 1 при любом варианте выбора индекса. Индекс должен не испол
```suggestion
`SELECT * FROM Table WHERE Key = $p1 and SubKey2 = $p2` - при выборе любого индекса используется 1 колонка, точечный префикс также не более 1 при любом варианте выбора индекса. Индекс не будет использоваться.
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +`SELECT * FROM Table WHERE Key >= $p1 and SubKey1 = $p2 And SubKey2 = $p3` - при выборе индекса должен быть выбран Index12, так как при его выборе в получающемся диапазоне [[Fk1; Fk2; Key], [Fk1; Fk2
```suggestion
`SELECT * FROM Table WHERE Key >= $p1 and SubKey1 = $p2 And SubKey2 = $p3` - при выборе индекса должен быть выбран Index12, так как при его выборе в получающемся диапазоне `[[Fk1; Fk2; Key], [Fk1; Fk2])` проекция на первые две колонки является точечной. Длина точечного префикса — 2, использовано 3 колонки.
```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +`SELECT * FROM Table WHERE SubKey1 = $p1 and SubKey2 > $p2` длина точечного префикса для Index12 — 1, использованы 2 колонки. Автовыбираем Index12. Выражение для диапазона `(($p1; $p2), ($p1)]`.
Этим всем примерам структуру бы какую-то придать, например:

```markdown
### Точечное чтение по первому подключу и условие на второй

* **Запрос:** `SELECT ...`
* **Используемый индекс:** `Index42`
* **Причина:** длина точечного префикса...

```

2024-09-03 03:50 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +`SELECT * FROM Table WHERE SubKey1 = $p1 and SubKey2 > $p2` длина точечного префикса для Index12 — 1, использованы 2 колонки. Автовыбираем Index12. Выражение для диапазона `(($p1; $p2), ($p1)]`.
И аккуратно перепроверить на непотерявшиеся бэктики, длинное тире — вместо минуса и т.п.

2024-09-12 10:38 UTC, ssmike commented
ping @blinkov

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Явное указание секции `VIEW` имеет приоритет над решением оптимизатора о использовании вторичных индексов. То есть запрос
```suggestion
Явное указание секции `VIEW` имеет приоритет над решением оптимизатора о использовании вторичных индексов. То есть запрос

```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +гарантированно будет производить выборку с использованием индекса `Index`.
```suggestion

гарантированно будет производить выборку с использованием индекса `Index`.
```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Для явного указания чтения с использованием первичного ключа следует использовать следующую конструкцию:
```suggestion
Для явного указания чтения с использованием первичного ключа следует использовать следующую конструкцию:

```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +#### Критерии выбора вторичного индекса
```suggestion

#### Критерии выбора вторичного индекса

```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +Выбор между чтениями с использованием индекса и c использованием первичного ключа происходит на основе следующих метрик:
```suggestion
Выбор между чтениями с использованием индекса и c использованием первичного ключа происходит на основе следующих метрик:

```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +3. Количество использованных колонок в границах диапазона для чтения. В следующем запросе к таблице Table с первичным ключом (Key1, Key2, Key3)
```suggestion
3. Количество использованных колонок в границах диапазона для чтения. В следующем запросе к таблице Table с первичным ключом (Key1, Key2, Key3)

```

2024-09-20 02:17 UTC, blinkov commented on ydb/docs/ru/core/dev/secondary-indexes.md
> +чтение будет производиться в диапазоне `(($param4, $param5), ($param1, $param2, $param3))` и таким образом количество использованных колонок будет равно 3. Аналогично 2 здесь отдается предпочтение ин
```suggestion

чтение будет производиться в диапазоне `(($param4, $param5), ($param1, $param2, $param3))` и таким образом количество использованных колонок будет равно 3. Аналогично 2 здесь отдается предпочтение индексам для которых использованы все индексируемые колонки.
```

2024-09-20 07:27 UTC, fomichev3000 approved these changes

2024-09-20 07:27 UTC, merged