YQ-2738 add integration tests for YT in KQP
ydb-platform/ydb pull request #3150
Opened 2024-03-26 08:51 UTC by GrigoriyPA

- feat contrib: aiogram 3
- Get rid of 'ya tool ymake_python3'
- Prototype of ya ide gradle handler
- Up tld list
- Revert
- External build system generator release 75
- Update YT white list
- Remove navi_serializable feature
- Added point to msku_uploader to trace skus
- automation of go yamake update
- YDB Import 546
- update taxitool rev. 13268634
- 
- Update contrib/python/types-protobuf to 4.24.0.20240106
- Update build documentations for rXXXXXX
- 
- 
- Automatic release build for ymake, os_ymake
- Fix error in TArrayRef constructor for a container: Elements with a different size should not be accepted even if they are convertible to TArrayRef value type.
- Specialize iterator_traits for TIpAddressRange iterator
- [domscheme] Move runtime.h into a separate library
- Enable SA1019 rule for psp namespace
- - Release new version of ytyndexer
- Use `CUDA_ARCHITECTURES` flag to prune architectures
- Update link to GTEST macro documentation
- YDB Import 548
- fix bank-applications: remove bank-forms usage
- Update ytyndexer to sbr:5704224018
- Stop using svn in canonization tests
- Add GEN_FBS
- bug contrib/grpc: fix races between retries and cancellation
- New version of the tld SKIP_CHECK SKIP_REVIEW
- add x/image/draw to arcadia
- Fix separator in CUDA_ARCHITECTURES
- update taxitool rev. 13288386
- Flake8 migrations clean up
- YDB Import 550
- Automatic release build for ya_bin3, ya_bin, os_ya, test_tool, os_test_tool_3, test_tool3
- Update gdb
- Update contrib/libs/zlib to 1.3.1
- YDB Import 551 KIKIMR-1
- update taxitool rev. 13295145
- feat yamake: add ruff wrapper and ya make macro
- Update contrib/python/Jinja2/py3 to 3.1.3
- erm: Add new version for `@yatool/prebuilder`: `0.5.1` and set `0.5.1` as default
- add fff-team poject to list of isolated projects
- feat(nots-bootstrap): take v10 build resources into use
- YDB Import 552
- Intermediate changes
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Introduce TEnumIndexedArray as a refurbished version of TEnumIndexedVector
- Get rid of go 1.20 support
- Update contrib/restricted/abseil-cpp to 20240116.0
- Intermediate changes
- Fill ENVIRONMENT for CMake projects from ENV() macroses
- Intermediate changes
- Update gdb pretty printers
- Intermediate changes
- Update libcxx to 02 June 2023 185b81e034ba60081023b6e59504dfffb560f3e3 (llvmorg-16.0.5)
- Automatic release build for ya_bin3, os_ya, ya_bin, test_tool, os_test_tool_3, test_tool3
- Update contrib/libs/opentelemetry-proto to 1.1.0
- Intermediate changes
- [util] TSystemError: print raw error code along with the message
- Intermediate changes
- Update golang to 1.21.6
- Intermediate changes
- Switch -w to -Wno-everything on C with GNU compilers
- Support wide strings (and string_views) in Out<> / IOutputStream
- remove -Wno-unused-but-set-variable
- Intermediate changes
- Drop TEnumIndexedVector
- Intermediate changes
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Intermediate changes
- Automatic release build for ymake, os_ymake
- Export module headers to cmake
- Fix bugs in CUDA libs pruning
- Move enum_indexed_array from misc to containers
- Intermediate changes
- Enum serialization cmake build fix
- Update vendor/github.com/envoyproxy/go-control-plane to 0.12.0
- Extract log4j version to a variable
- remove -Wno-implicit-int
- [library/cpp/yt] fix peerdir
- Set -mno-outline-atomics for modern versions of CLang and GCC to avoid unresolved symbols linking errors on arm64.,. Fix #2527
- Remove trailing whitespace
- Set conan os.version setting from CMAKE_OSX_DEPLOYMENT_TARGET..
- Intermediate changes
- Add missed #include <type_traits>
- Fix boost asio config
- Intermediate changes
- Update libcxxrt to 2023-10-11 03c83f5a57be8c5b1a29a68de5638744f17d28ba
- Fix fail with pydebug in tf (old)
- Add target and extra_targets, remove unused Targets_, recanonize tests
- Intermediate changes
- External build system generator release 76
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Intermediate changes
- sprintf -> snprintf as it is deprecated on macOS..
- Fix sprintf deprecation warnings on newer macOS SDK
- Fix deprecated pod type in llvm / libcxxabi
- Intermediate changes
- Remove targets, use target/extra_targets
- Automatic release build for ya_bin3, os_ya, ya_bin, test_tool, os_test_tool_3, test_tool3
- 
- Mark methods as const
- Intermediate changes
- cc contrib/grpc: unify one of the patches with how upstream fixed the issue
- Intermediate changes
- 
- Artifacts from bucket and some refactoring
- YDB Import 559
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Intermediate changes
- Remove empty glibtop headers resolving
- Fix reimport for contrib/libs/cxxsupp/libcxxrt
- Move android sysincls to where they belong
- Get rid of empty cuda/include resolving
- check lifetime bounds of  values returned from String's c_str(), data() methods
- 
- Move macOS-specific sysincls to where they belong
- Remove empty resolving for X11/ includes
- Remove empty resolving for Eigen/Array
- Intermediate changes
- TMaybe Monadic operations
- Intermediate changes
- Update contrib/libs/libidn to 1.42
- Add glfw 3.3.9 to contrib
- Bump CUDA -> 11.4 and cuDNN -> 8.0.5
- Intermediate changes
- Update vendor/go.opentelemetry.io/otel to 1.22.0
- Update contrib/libs/libunwind to 18.1.0-rc1
- Intermediate changes
- Update boost/asio and boost/process to 1.70.0
- Fix: add input file as MAIN_DEPENDENCY in Cython call..
- Update contrib/python/MarkupSafe/py3 to 2.1.4
- Intermediate changes
- Fix bug after rXXXXXX
- Disable non-existing macOS include
- yamaker: Disable tr1/ and ext/ includes by default
- Update contrib/libs/re2 to 2024-02-01
- Move macOS-specific sysincls to where they belong
- Disable ext/ and tr1/ headers resolving
- Remove empty resolving of tr1/ and ext/ includes
- Intermediate changes
- Support nonstandard 'ar' versions
- Intermediate changes
- Update contrib/restricted/boost/asio to 1.71.0
- Disable empty doc/ includes resolving
- Remove windows-specific headers resolving from unsorted.yml
- Disable empty resolving of zzip-[1-5].h headers
- Disable empty resolving of libgit2-specific includes
- Remove empty math_constants.h resolving from unsorted.yml
- Clarify wrl headers resolution
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Remove unused -ish.h headers resolving
- Move windows-specific sysincls to windows.yml
- Intermediate changes
- Remove various unused sysincls from unsorted.yml
- 
- Automatic release build for ymake, os_ymake
- Intermediate changes
- Remove unused MX_FORMULAS() macro support
- Update contrib/libs/nghttp2 to 1.59.0
- Intermediate changes
- 
- PR from branch users/prettyboy/release-ya-bin-after-fix-mapping
- Intermediate changes
- TThread::SetName sets thread name on android
- Intermediate changes
- Update yfm-docs for ya make to Build time: 9.706ms
- Intermediate changes
- Upload new jdk-21.0.2+13 + tzdata 2024a
- Update contrib/libs/lzma to 5.4.6
- Intermediate changes
- fix prometheus_decoder ConsumeCounter
- Disable QNX-specific includes in contrib/libs/lzma
- Intermediate changes
- Remove empty resolving of QNX-specific headers
- Intermediate changes
- Upload new jdk-17.0.10+7 + tzdata 2024a
- Update yfm-docs for ya make to Build time: 9.883ms
- Disable non-existing include in contrib/libs/openldap
- Update tzinfo 2024a
- Intermediate changes
- Update yfm-docs for ya make to Build time: 10.003ms
- Intermediate changes
- llvm16 targets
- Update libcxxrt to 2024-02-04 39f76d286ffa70e15ae45632fe3fa5ea96cd46e4
- contrib/restricted/boost: Remove empty resolving of auld stl headers
- Intermediate changes
- Update Python 3 to 3.11.8
- Intermediate changes
- Update contrib/python/types-protobuf to 4.24.0.20240129
- Intermediate changes
- Disable non-existing include in contrib/libs/lzma
- Intermediate changes
- Always return string for cuda architectures
- Remove all remaining checks of auto CUDA support for PPC64 / MacOS
- New version of the tld SKIP_CHECK SKIP_REVIEW
- Intermediate changes
- Disable empty resol [...]

2024-03-29 09:41 UTC, uzhastik commented on ydb/tests/tools/kqprun/ya.make
> -PEERDIR(
полезные же пирдиры. нельзя их сохранить?

2024-03-29 12:55 UTC, GrigoriyPA commented on ydb/tests/tools/kqprun/ya.make
> -PEERDIR(
Они мешают подключать udf из [стандартных udf_deps](https://github.com/ydb-platform/ydb/blob/9c0752fce13dada369b311e77eb882f1bb7dfa00/ydb/library/yql/tests/sql/file_common.py#L94) для yql тестов, так как дублируются. Надо чтобы kqprun собирался без них

2024-04-03 12:25 UTC, rvu1024 requested changes

2024-04-03 12:25 UTC, rvu1024 commented on ydb/library/yql/tests/sql/file_common.py
>      if provider not in get_supported_providers(config):
Этот кусок не относится к sql_query. Стоит оформить как отдельную функцию

2024-04-03 12:25 UTC, rvu1024 commented on ydb/library/yql/tests/sql/kqp_yt_file.py
> +    'action/eval_pragma',  # ATOM evaluation is not supported in YDB queries
Вообще, такие вещи у нас делаются через задание провайдера в .cfg файле. Можно расширить этот механизм через негативные провайдеры. Например `!providers` будет задавать exclusion list. Тогда все эти исключения просто пропишутся в cfg файлах

2024-04-15 10:30 UTC, rvu1024 submitted a review, later dismissed

2024-04-19 08:15 UTC, Hor911 submitted a review, later dismissed

2024-04-19 09:16 UTC, rvu1024 approved these changes

2024-04-19 09:43 UTC, merged