[CB] Add simple s3_writer implementation
ydb-platform/ydb pull request #3152
Opened 2024-03-26 09:16 UTC by Enjection

### Changelog entry 

- add simple s3_writer implementation

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-03-26 19:23 UTC, CyberROFL requested changes

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/wrappers/s3_storage_config.cpp
> +    Aws::Client::ClientConfiguration config;
Сделай, пожалуйста, предварительный рефакторинг, чтобы этот код не повторялся в третий раз.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/worker.h
> +            S3_ERROR,
Наверно, лучше здесь завести что-то типа `std::variant<TSuccess, TGenericError, TS3Error>`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.h
> +#include <ydb/core/wrappers/s3_storage_config.h>
```suggestion
#include <ydb/core/base/defs.h>
#include <ydb/core/wrappers/s3_storage_config.h>

#include <util/generic/string.h>
```

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.h
> +IActor* CreateS3Writer(NWrappers::IExternalStorageConfig::TPtr&&  s3Settings, const TString& tableName, const TString& writerName);
Лишний пробел перед `s3Settings`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        }
Не очень понял для чего это перекладывание.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        TString key = Sprintf("part.%ld.%s.jsonl", ev->Get()->Records[0].Offset, WriterName.c_str());
`const`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        RequestInFlight = std::make_unique<TS3Request>(request, buffer);
Почему не `std::move(request)` и `std::move(buffer)`?

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        Send(S3Client, new TEvExternalStorage::TEvPutObjectRequest(RequestInFlight->Request, TString(RequestInFlight->Buffer)));
`RequestInFlight->Buffer` — это ведь уже `TString`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        TString buffer = Sprintf(R"({"table_name":"%s","writer_name":"%s","finished":%s})", TableName.c_str(), WriterName.c_str(), Finished ? "true" : "false");
Тут что-то адское. Лучше сконструировать нормальный json и сериализовать его в буфер.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        TString key = Sprintf("writer.%s.json", WriterName.c_str());
`const`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        if (!ev->Get()->Records) {
Возможно, следует сразу в протоколе предусмотреть `TEvFinish`?

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        const TString& writerName)
Что такое "writer name"?

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        CB_LOG_D("HandleScheme TEvExternalStorage::TEvPutObjectResponse"
Копипаста. Что такое `HandleScheme`?)
По идее тут можно написать `CB_LOG_D("Handle " << ev->Get()->ToString());`.

2024-03-26 19:23 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        }
Вот так было бы понятнее:
```suggestion
        if (!IdentityWritten) {
            IdentityWritten = true;
            Send(Worker, new TEvWorker::TEvHandshake());
        } else if (!Finished) {
            Send(Worker, new TEvWorker::TEvPoll());
        } else {
            Send(Worker, new TEvWorker::TEvGone(TEvWorker::TEvGone::DONE));
        }
```

2024-03-27 20:44 UTC, Enjection commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        Send(S3Client, new TEvExternalStorage::TEvPutObjectRequest(RequestInFlight->Request, TString(RequestInFlight->Buffer)));
Он ожидает rvalue, поэтому явное копирование.

2024-03-28 07:37 UTC, Enjection commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        const TString& writerName)
Произвольная строка (де-факто хочу сделать base58 encoded uuid4). Нужна для протокола, что бы при пересоздании можно было понять дописан стрим или нет и т.п. Может потом ещё уберу.

2024-03-28 07:44 UTC, Enjection commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        if (!ev->Get()->Records) {
Возможно, пока решил не добавлять дополнительное сообщение. Пустой ответ на TEvPoll == EOF.

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/worker.h
> +            S3_ERROR,
Напиши в этом месте TODO/FIXME, а то потеряется.

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        TString buffer = buf.Str();
Почему не просто [WriteJson](https://github.com/ydb-platform/ydb/blob/main/library/cpp/json/json_writer.h#L194)?

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +#include <ydb/library/actors/core/actor_bootstrapped.h>
Копи-паста: не вижу, чтобы что-то из этого использовалось.

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +#include <util/generic/map.h>
Не используется.

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +#include <util/string/join.h>
Не используется.

2024-03-28 09:26 UTC, CyberROFL commented on ydb/core/tx/replication/service/s3_writer.cpp
> +        const TString key = Sprintf("writer.%s.json", WriterName.c_str());
Возможно, стоит унести все билдеры ключей для S3 в одно место, чтобы они не были раскиданы по коду. Что-нибудь типа:
```cpp
class TS3KeyBuilder {
public:
  explicit TS3KeyBuilder(const TString& writerName);
  TString IdentityKey() const;
  TString PartKey(int partNumber) const;
};
```

2024-03-28 10:32 UTC, CyberROFL submitted a review, later dismissed

2024-03-28 12:34 UTC, CyberROFL approved these changes

2024-03-28 15:49 UTC, merged