KIKIMR-16347: introduce basic "SELECT version();" support
ydb-platform/ydb pull request #3231
Opened 2024-03-28 06:07 UTC by blinkov

### Changelog entry 

Support for `SELECT version();` query, which returns a string describing the version of the current process that parsed it.

### Changelog category 

* New feature

2024-05-15 16:49 UTC, spuchin commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
А есть понимание что именно будет выдавать snvversions'овский GetBranch на наших сборках?

2024-05-16 08:16 UTC, blinkov commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
@spuchin в GitHub там что-то типа `refs/heads/main`, из-за чего ниже вырезается всё что до последнего слеша. Внутри по идее должна быть похожая конструкция с самым полезным компонентом в конце.

2024-05-16 09:27 UTC, spuchin commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
Давай переформулирую вопрос, что конкретно будет отдаваться на продакшн кластерах, например на наших сборках из stable-24-1?

2024-05-16 13:05 UTC, blinkov commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
По текущей схеме релизов по идее вот так должно получаться:
```bash
$ LD_LIBRARY_PATH=/opt/ydb/lib /opt/ydb/bin/ydbd -V | grep Branch | sed -e 's|.*/||g'
23.3.17
```
Но при завершении переезда на GitHub туда может начать что-то другое приезжать. Я не настолько в курсе как оно будет устроено, чтоб заранее предсказать.

2024-05-19 18:46 UTC, spuchin commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
Сам builtin в любом случае нужен, предлагаю мерджить и постестировать на докерах, собранных нашим "стандартным" способом.

2024-05-19 18:46 UTC, spuchin submitted a review, later dismissed

2024-06-13 16:41 UTC, vitstn commented on ydb/library/yql/sql/v1/builtin.cpp
> +        const TString branch(GetBranch());
нельзя раскрывать такое в парсере. разные pipeline могут это делать по разному, в peephole/runtime

2024-06-13 16:42 UTC, vitstn commented on ydb/library/yql/sql/v1/builtin.cpp
> +#include <library/cpp/svnversion/svnversion.h>
уберите эту зависимость. Нужен нормальный callable, с типизацией и реализацией в peehole/runtime

2024-06-14 13:25 UTC, nepal requested changes

2024-06-14 13:25 UTC, nepal commented on ydb/library/yql/sql/v1/builtin.cpp
> +            {"version", BuildSimpleBuiltinFactoryCallback<TVersion>()},
Лучше вот так написать
`{"version", BuildNamedArgcBuiltinFactoryCallback<TCallNodeImpl>("Version", 0, 0) },`
Тогда TVersion не понадобится

2024-06-14 13:25 UTC, nepal commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +    if (node->IsCallable("Version")) {
Тут If не нужен - ExpandVersion гарантированно вызовется только для Version
И лучше добавить трейс
        YQL_CLOG(DEBUG, CorePeepHole) << "Expand Version";

2024-06-14 13:25 UTC, nepal commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +
Лишняя пустая строка

2024-06-14 13:25 UTC, nepal commented on ydb/library/yql/sql/v1/sql_ut.cpp
> +
Этот юнит тест лишний - он ничего особенного не тестирует по сравнению с файловым тестом

2024-06-14 14:41 UTC, nepal approved these changes

2024-06-14 16:38 UTC, vitstn approved these changes

2024-06-14 17:01 UTC, merged