Fix TABLESAMPLE SYSTEM crashing DQ/hybrid
ydb-platform/ydb pull request #3261
Opened 2024-03-28 15:02 UTC by avevad

### Changelog entry 

Fix TABLESAMPLE SYSTEM crashing DQ/hybrid

### Changelog category 

* Bugfix

2024-03-28 17:29 UTC, rvu1024 requested changes

2024-03-28 17:29 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                    return false;
Надо AddInfo добавить

2024-03-29 19:14 UTC, avevad commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                    return false;
сделал

2024-04-01 12:18 UTC, rvu1024 requested changes

2024-04-01 12:18 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                    AddInfo(ctx, "ReadTable with system sampling", skipIssues);
просто "system sampling"

2024-04-01 12:29 UTC, avevad commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                    AddInfo(ctx, "ReadTable with system sampling", skipIssues);
готово

2024-04-01 14:52 UTC, rvu1024 approved these changes

2024-04-01 16:17 UTC, merged