Add reason for pending action in maintenance public API
ydb-platform/ydb pull request #3289
Opened 2024-03-29 10:03 UTC by pixcc

### Changelog entry 

Add reason for pending action in maintenance public API

### Changelog category 

* Improvement

2024-03-29 10:31 UTC, CyberROFL requested changes

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +    struct TTryToLockResult {
Сделай лучше нормальным классом, чтобы не лезть в его потроха, а вызывать методы `IsSuccess()`, `GetReason()` и т.п.

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/cluster_info.h
> +    NKikimrCms::TStatus::EReasonType ReasonType = NKikimrCms::TStatus::REASON_TYPE_UNSPECIFIED;
Можно выделить `Reason` и `ReasonType` в отдельный класс и переиспользовать его. Например:
```cpp
class TReason {
public:
    explicit TReason(const TString& reason, NKikimrCms::TStatus::EReasonType type);
    const TString& DebugString() const;
    NKikimrCms::TStatus::EReasonType GetType() const;
};
```

И можно сразу предсмотреть конструктор `TErrorInfo` от `code` и `TReason`.

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +    virtual NKikimrCms::TStatus::EReasonType DisabledNodesLimitReachedReasonType() const {
Имхо, надо оставить `TClusterLimitsCounter`. Так будет семантичнее.

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/node_checkers.cpp
> +    : isSuccess(isSuccess) {}
```suggestion
INodesChecker::TTryToLockResult::TTryToLockResult(bool isSuccess) 
    : isSuccess(isSuccess)
{}
```

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/cms.cpp
> +    if (auto result = ClusterInfo->ClusterNodes->TryToLockNode(node.NodeId, opts.AvailabilityMode); !result.isSuccess) {
У тебя в соседних строках по-разному написан похожий код.

2024-03-29 10:31 UTC, CyberROFL commented on ydb/core/cms/api_adapters.cpp
> +            switch (cmsAction.GetStatus().GetReasonType()) {
Сделай плз по аналогии отдельную функцию `ConvertReason()`.

2024-04-01 19:11 UTC, pixcc commented on ydb/core/cms/node_checkers.h
> +    struct TTryToLockResult {
Удалил эту структуру

2024-05-07 13:45 UTC, pixcc commented on ydb/core/cms/cms.cpp
> +                // schedule nothing
Нужно ли нам ничего не шедулить на ошибки? Тем самым по-сути мы удаляем scheduled actions из таски.

2024-05-08 12:05 UTC, pixcc commented on ydb/core/cms/cms_tx_load_state.cpp
> +            parser.AllowUnknownField(true);
По поводу совместимости:

- Новая версия сервера начинает генерировать данные в новом поле и сохраняет его в локальную базу
- Старая версия сервера при прочтении данных из локальной базы полностью проигнорирует новое поле (даже не будет сохранено в Unknown Field Set). Если старая версия перезапишет данные (при `refresh`) в локальной базе, то новая версия их сможет прочитать.
- Старый клиент (например, `ydbd -s ... restart`) может получить новые данные от нового сервера. В таком случае данные будут в Unknown Field Set. Так как клиент выводит на экран DebugString протобуфа, то пользователь может увидеть, что ему пришли неизвестные поля, но не сможет их интерпретировать.

2024-05-13 10:22 UTC, pixcc commented on ydb/core/cms/cms_tx_load_state.cpp
> +            parser.AllowUnknownField(true);
И стоит эти строчки вмерджить в предыдущий стейбл.

2024-05-13 17:23 UTC, CyberROFL requested changes

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/error_info.h
> +    EType Type = EType::UNSPECIFIED;
`const`.

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/error_info.h
> +    TString GetMessage() const {
```suggestion
    const TString& GetMessage() const {
```

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/error_info.h
> +        UNSPECIFIED = NKikimrCms::TAction::STATUS_UNSPECIFIED,
Имхо, не стоит тащить сюда зависимость на протобуф. Лучше написать комментарий, что соответствует такой-то enum-у из протобуфа и сделать явную функцию конвертации в cpp-файле.

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +        {}
Здесь и в других местах поехала верстка:
```suggestion
        TTryToLockResult(bool isSuccess, const TReason &reason)
            : IsSuccess_(isSuccess)
            , Reason(reason)
        {}
```

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +        TReason GetReason() const {
```suggestion
        const TReason& GetReason() const {
```

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +        TReason Reason;
`const`.

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/node_checkers.cpp
> +            return TTryToLockResult::Fail(reason);
Здесь и в других местах: `const` либо сразу передавать в конструктор.

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/node_checkers.h
> +        static TTryToLockResult Fail(const TReason &reason) {
Ещё было бы удобно передавать сюда сразу тип и сообщение:
```cpp
static TTryToLockResult Fail(TReason::EType type, const TString& msg);
static TTryToLockResult Fail(const TString& msg);
```

Чтобы можно было писать так:
```cpp
return TTryToLockResult::Fail(<type>, "foobar");
return TTryToLockResult::Fail("foobar");
```

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/erasure_checkers.cpp
> +        error.Reason = TReason(TStringBuilder() << vdisk.PrettyItemName() << " has missing info for " << pdisk.PrettyItemName());
Имеет смысл сделать неявный конструктор `TReason(const TString& msg)`?

2024-05-13 17:23 UTC, CyberROFL commented on ydb/core/cms/cms_impl.h
> +        const TActionOptions &opts,
Не очень понятен смысл этих изменений. По крайней мере, это точно не нужно делать в рамках этого pr, лучше — отдельно.

2024-10-01 10:36 UTC, pixcc commented on ydb/core/cms/node_checkers.cpp
> +            return TTryToLockResult::Fail(reason);
Убрал класс

2024-10-01 10:37 UTC, pixcc commented on ydb/core/cms/error_info.h
> +    EType Type = EType::UNSPECIFIED;
Не могу сделать `const`, объекту нужен оператор присваивания

2024-10-01 10:38 UTC, pixcc commented on ydb/core/cms/error_info.h
> +    TString GetMessage() const {
Не могу сделать `const`, объекту нужен оператор присваивания

2024-10-01 10:38 UTC, pixcc commented on ydb/core/cms/node_checkers.h
> +        TReason GetReason() const {
Убрал класс

2024-10-01 10:44 UTC, pixcc commented on ydb/core/cms/cms.cpp
> +                // schedule nothing
Оставил как было раньше.

2024-10-01 10:53 UTC, pixcc commented
# How it works?

## `Partial permissions mode = true`
Issues for all failed actions are collected

## `Partial permissions mode = false`
Issue only for first failed action is collected

2024-10-01 14:12 UTC, CyberROFL commented on ydb/core/cms/cms.cpp
> +    std::vector<TAction> actions(request.GetActions().begin(), request.GetActions().end());
оО а без копии нельзя обойтись?

2024-10-01 14:12 UTC, CyberROFL commented on ydb/core/cms/error_info.h
> +    TString GetMessage() const {
Я так и не понял, почему нельзя сделать `const TString& GetMessage() const`?

2024-10-02 09:59 UTC, CyberROFL approved these changes

2024-10-02 10:09 UTC, merged