Provide slot names for ui
ydb-platform/ydb pull request #3294
Opened 2024-03-29 10:49 UTC by pixcc

### Changelog category 

* Not for changelog (changelog entry is not required)

2024-04-01 09:18 UTC, CyberROFL requested changes

2024-04-01 09:18 UTC, CyberROFL commented on ydb/core/driver_lib/run/run.cpp
> +        AppData->SlotName = runConfig.AppConfig.GetDynamicNodeConfig().GetNodeInfo().GetSlotName();
`HasSlotName()` не надо проверять?

2024-04-01 09:18 UTC, CyberROFL commented on ydb/core/mind/hive/tx__register_node.cpp
> +            db.Table<Schema::Node>().Key(nodeId).Update<Schema::Node::Statistics>(node.Statistics);
Можно ещё так:
```suggestion
db.Table<Schema::Node>().Key(nodeId).Update(
    NIceDb::TUpdate<Schema::Node::Local>(Local),
    NIceDb::TUpdate<Schema::Node::ServicedDomains>(servicedDomains),
    NIceDb::TUpdate<Schema::Node::Statistics>(node.Statistics)
);
```

2024-04-01 09:18 UTC, CyberROFL commented on ydb/core/mind/hive/tx__register_node.cpp
> +            TString slotName = Record.GetSlotName();
```suggestion
            const TString slotName = Record.GetSlotName();
```

2024-04-03 10:04 UTC, CyberROFL commented on ydb/core/driver_lib/run/kikimr_services_initializers.cpp
> -
Это же лишний и ненужный дифф. По крайней мере он не имеет отношения к теме pr.

2024-04-03 10:04 UTC, CyberROFL commented on ydb/core/mind/local.cpp
> +        if (!slotName.Empty()) {
Можно в одну строку:
```suggestion
        if (const TString& slotName = AppData(ctx)->SlotName; !slotName.Empty()) {
```

2024-04-03 10:12 UTC, CyberROFL commented on ydb/core/tablet/node_whiteboard.cpp
> +        if (!slotName.Empty()) {
Тогда уж и тут поправь :)
```suggestion 
        if (const TString& slotName = AppData(ctx)->SlotName; !slotName.Empty()) {
```

2024-04-03 10:13 UTC, CyberROFL submitted a review, later dismissed

2024-04-03 12:23 UTC, vporyadke commented on ydb/core/mind/hive/tx__register_node.cpp
> +            node.LastSeenServicedDomains = node.ServicedDomains;
extra whitespace at the end of string

2024-04-03 12:26 UTC, vporyadke approved these changes

2024-04-04 15:09 UTC, merged