YQL-18117: Implement block tz date
ydb-platform/ydb pull request #3366
Opened 2024-04-01 17:21 UTC by fedor-miron

### Changelog entry 

### Changelog category 

* Improvement
 
### Additional information

2024-04-03 09:52 UTC, nepal requested changes

2024-04-03 09:52 UTC, nepal commented on ydb/library/yql/minikql/computation/mkql_block_transport.cpp
> +        ythrow yexception() << "Serializer not implemented for block resources";
Тут копипаст. И это место надо имплементить, иначе запросы в DQ будут падать

2024-04-03 09:52 UTC, nepal commented on ydb/library/yql/minikql/computation/mkql_block_transport.cpp
> +        ythrow yexception() << "Deserializer not implemented for block resources";
Аналогично

2024-04-03 09:52 UTC, nepal commented on ydb/library/yql/minikql/datetime/datetime.h
> +    ui8 Reserved[2];
мы не хотим написать static_assert что TTMStorage имеет ожидаемый sizeof()?

2024-04-03 09:52 UTC, nepal commented on ydb/library/yql/providers/yt/comp_nodes/dq/arrow_converter.cpp
> +        ythrow yexception() << "Yson reader not implemented for block tz dates";
Тоже надо реализовать - иначе мы не сможем прочитать блочную колонку из YT

2024-04-03 13:29 UTC, vitstn commented on ydb/library/yql/minikql/mkql_type_builder.h
> +        return arrow::uint64();
тут нужен constexpr (slot == NUdf::EDataSlot::TzTimestamp), чтобы можно было развивать код

2024-04-13 22:26 UTC, fedor-miron commented on ydb/library/yql/minikql/datetime/datetime.h
> +    ui8 Reserved[2];
https://github.com/ydb-platform/ydb/blob/001466a9d5c9915c7db18f6e2aa91e2b0ae949fc/ydb/library/yql/minikql/datetime/datetime.h#L152
он уже есть

2024-04-22 13:59 UTC, nepal requested changes

2024-04-22 13:59 UTC, nepal commented on ydb/library/yql/minikql/computation/mkql_block_transport.cpp
> +class TTzDateBlockSerializer final : public TTupleBlockSerializerBase<Nullable, TTupleBlockSerializer<Nullable>> {
Не хватает тестов на Tz* в https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/minikql/computation/mkql_computation_node_pack_ut.cpp#L630

2024-04-22 13:59 UTC, nepal commented on ydb/library/yql/providers/yt/comp_nodes/dq/arrow_converter.cpp
> +class TYsonTzDateBlockReader final : public IYsonBlockReaderWithNativeFlag<Native> {
Тут тоже тесты нужны с реальным ытем

2024-04-28 11:01 UTC, nepal requested changes

2024-05-22 12:01 UTC, nepal commented on ydb/library/yql/minikql/computation/mkql_block_transport.cpp
> -private:
Этот класс теперь используется в качестве мембера

2024-05-22 12:01 UTC, nepal approved these changes

2024-05-22 22:50 UTC, merged