Add limit for LLVM node count
ydb-platform/ydb pull request #3435
Opened 2024-04-03 12:40 UTC by avevad

### Changelog entry 

Add configuration pragma for LLVM node count limit

### Changelog category 

* Improvement

### Additional information

...

2024-04-04 12:38 UTC, rvu1024 requested changes

2024-04-04 12:38 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +                job->SetOptLLVM(execCtx->Options_.Config()->LLVMNodeCountLimit.Get(execCtx->Cluster_).GetOrElse(DEFAULT_LLVM_NODE_COUNT_LIMIT) >= nodeCount ? execCtx->Options_.OptLLVM() : "OFF");
Нужно поменять прямо в execCtx->Options_.OptLLVM(), иначе функция execCtx->EstimateLLVMMem() ниже зедерет память в операции не смотря на то, что LLVM отключен

2024-04-07 14:19 UTC, avevad commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +                job->SetOptLLVM(execCtx->Options_.Config()->LLVMNodeCountLimit.Get(execCtx->Cluster_).GetOrElse(DEFAULT_LLVM_NODE_COUNT_LIMIT) >= nodeCount ? execCtx->Options_.OptLLVM() : "OFF");
да, точно
сделал

2024-04-09 15:25 UTC, rvu1024 approved these changes

2024-04-09 15:32 UTC, merged