docs(ydb): translate query plan documentation
ydb-platform/ydb pull request #3442
Opened 2024-04-03 13:07 UTC by ulya-sidorina

2024-04-26 15:09 UTC, blinkov requested changes, later dismissed

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Combine two data sources (subqueries or tables), join strategy is specified in the operation description.
```suggestion
Combine two data sources (subqueries or tables) by keys. The join strategy is specified in the operation description.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Sorting rows with specified limit.
```suggestion
Partial rows sorting with a specified limit.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Returns first N elements that are less or equal to the N+1 element if the entire sequence were sorted.
```suggestion
Returns the first N elements that are less or equal to the N+1 element if the entire sequence were sorted.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Union the results of two or more subqueries into one set.
```suggestion
Concatenate the results of two or more subqueries into a single row set.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Iterates through a given set of rows, typically use a [precompute](#precompute) as an argument.
```suggestion
Iterates through a given set of rows. Typically uses a [precompute](#precompute) as an argument.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Partitioning by key typically use a [precompute](#precompute).
```suggestion
Partitioning by key. Typically uses a [precompute](#precompute).
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Each stage is executed as a certain number of tasks. For example, a reading stage may be executed in N tasks, where N is the number of table shards. Method of transferring data between stages depends
```suggestion
Each stage is executed as a certain number of tasks. For example, a reading stage may be executed in N tasks, where N is the number of table shards. The method of transferring data between stages depends on the type of connection. Below is a description of different connections.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +A special case of `UnionAll`, the results of the producer stage are sorted by a specified set of columns and merged result also is sorted.
```suggestion
This is a special case of `UnionAll`. The results of the producer stage are sorted by a specified set of columns and merged into a result that is also sorted.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Implements 1-to-1 relationships between tasks of stages, the producer stage and consumer stage should have the same number of tasks.
```suggestion
Implements 1-to-1 relationships between tasks of stages, the producer and consumer stages should have the same number of tasks.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Sends the results of producer stage tasks to consumer stage tasks based on a certain rule for specified columns. The rule is defined in the code, but the list of columns is specified in connection.
```suggestion
Sends the results of producer stage tasks to consumer stage tasks based on a certain rule for specified columns. The rule is defined in the code, but the list of columns is specified in the connection.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +Stages that depend on precomputes should be executed after the precompute have been completed.
```suggestion
Stages that depend on precomputes should be executed after the precompute has been completed.
```

2024-04-26 15:09 UTC, blinkov commented on ydb/docs/en/core/dba/query-plans-optimization.md
> +# Query plans optimization
This branch needs to be merged with `main`, as this folder no longer exists.

2024-05-03 03:32 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +GroupBy | columns used for aggregation
```suggestion
GroupBy | columns or expressions used for aggregation
```

2024-05-03 03:34 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +TopSortBy | columns used for sorting
```suggestion
SortBy | columns or expressions used for sorting

#### TopSort
Partial rows sorting with a specified limit.

Attribute | Description
--- | ---
TopSortBy | columns or expressions used for sorting
```

2024-05-03 03:35 UTC, blinkov commented on ydb/docs/en/core/yql/query_plans.md
> +TopBy | columns by which the first N rows will be taken
```suggestion
TopBy | columns or expressions by which the first N rows will be taken
```

2024-05-03 06:53 UTC, fomichev3000 approved these changes

2024-05-03 06:53 UTC, merged