Add pragma for YT option 'expiration_timeout'
ydb-platform/ydb pull request #3451
Opened 2024-04-03 15:51 UTC by avevad

### Changelog entry 

Add pragma yt.ExpirationTimeout for YT option 'expiration_timeout'

### Changelog category 

* Improvement

### Additional information

...

2024-04-04 13:52 UTC, rvu1024 requested changes, later dismissed
Здесь надо просто существующую прагму ExpirationInterval переделать, а не вводить новую

2024-04-08 14:28 UTC, vitstn approved these changes

2024-04-08 14:57 UTC, merged

2024-04-08 18:23 UTC, rvu1024 commented on ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
> -            ExpirationInterval.Clear();
Это не нужно было удалять. ExpirationDeadline и ExpirationInterval взаимоисключающие прагмы. Они не должны одновременно работать

2024-04-08 18:23 UTC, rvu1024 commented on ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
> -            ExpirationDeadline.Clear();
аналогично

2024-04-08 18:23 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> -            } else if (interval || isDuration) {
здесь тоже нужно оставить ветку else if по той же причине

2024-04-09 12:50 UTC, avevad commented on ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
> -            ExpirationInterval.Clear();
Сделал их не взаимоисключающими чтобы дать пользователю возможность одновременно удалять табличку в фиксированный момент времени и после истечения какого то промежутка бездействия (если таблицу не трогали, например, неделю)