Temporary Table -> Temporary Directory
ydb-platform/ydb pull request #3557
Opened 2024-04-08 12:07 UTC by nikvas0

### Changelog entry 

use temporary dirs instead of temporary tables

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-04-12 13:45 UTC, shnikd requested changes

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    const auto primaryTxId = GetCachedTxId(ctx);
А зачем тут отдельно выделять txId для всей директории, может тут достаточно мапы txId->pathId

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    for (const auto& tablePathId : traverseResult.Tables) {
У нас же может не оказаться таблиц в директории (пользователь сам дропнул), и тогда операция навсегда перейдет в состояние Running?

2024-04-12 13:45 UTC, shnikd commented on ydb/core/kqp/common/simple/temp_tables.cpp
> +    const auto temporaryStoragePrefix = Database + "/.tmp/sessions/" + SessionId + "/";
JoinPath({Database, ".tmp", "sessions", SessionId})?

2024-04-12 13:45 UTC, shnikd commented on ydb/core/protos/flat_scheme_op.proto
> +    optional NActorsProto.TActorId OwnerActorId = 16;
Возможно тут нужен отдельный флаг Temporary и TempDirOwnerActorId аналогично с временными таблицами, учитывая что поле Owner уже есть

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard_impl.h
> +    THashMap<TTxId, TBackgroundCleaningState> BackgroundCleaningTxs;
Эти две хеш мапы не подчищаются, с этим и до этого был баг видимо

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
>      switch (record.GetStatus()) {
Если придет ошибка по одной из таблиц, а по остальным например еще ничего не пришло, то ты заново запустишь удаление, и получится, что BackgroundCleaning обновляется неправильно

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard_schema.h
> +        struct OwnerActorId :          Column<17, NScheme::NTypeIds::String> {};
Тоже самое

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard_schema.h
> +        struct OwnerActorId :          Column<17, NScheme::NTypeIds::String> {};
Аналогично с временными таблицами, возможно, нужно добавить отдельный флаг IsTemporary

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    TTraverseResult Traverse(const TString& workingDir, const TString& name, TSchemeShard* schemeShard) {
Возможно стоит добавить возможность рекурсивного удаления директории как операцию в Schemeshard, чтобы эту логику дважды не повторять, тем более тут уже возникают какие-то неприятные гонки
@ijon думаю может подсказать насколько сложно это сделать

2024-04-12 13:45 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard_path_element.h
> +    TActorId OwnerActorId;
Тут наверное тоже лучше добавить отдельный флаг IsTemporary

2024-04-12 13:53 UTC, nikvas0 commented on ydb/core/protos/flat_scheme_op.proto
> +    optional NActorsProto.TActorId OwnerActorId = 16;
Здесь пустое значение OwnerActorId <=> Temporary = false, так что скорее не нужно

2024-04-15 08:55 UTC, nikvas0 commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    const auto primaryTxId = GetCachedTxId(ctx);
fixed

2024-04-15 08:55 UTC, nikvas0 commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    for (const auto& tablePathId : traverseResult.Tables) {
fixed

2024-04-15 08:55 UTC, nikvas0 commented on ydb/core/kqp/common/simple/temp_tables.cpp
> +    const auto temporaryStoragePrefix = Database + "/.tmp/sessions/" + SessionId + "/";
fixed

2024-04-15 08:55 UTC, nikvas0 commented on ydb/core/tx/schemeshard/schemeshard_impl.h
> +    THashMap<TTxId, TBackgroundCleaningState> BackgroundCleaningTxs;
fixed

2024-04-15 08:55 UTC, nikvas0 commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
>      switch (record.GetStatus()) {
fixed

2024-04-15 12:25 UTC, shnikd requested changes

2024-04-15 12:25 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    const auto pathId = BackgroundCleaningTxToDirPathId.at(txId);
Тут же может не быть такого ключа, так как долетают старые сообщения, которые были например до ретрая по ошибке.

2024-04-15 12:25 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    const auto& state = BackgroundCleaningState.at(pathId);
Тут тоже может не существовать такого ключа

2024-04-15 12:40 UTC, nikvas0 commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +    const auto& state = BackgroundCleaningState.at(pathId);
Ключ всегда будет. Он вызывается только из методов, где это уже проверили.

2024-04-15 12:59 UTC, shnikd requested changes

2024-04-16 00:09 UTC, shnikd requested changes

2024-04-16 00:09 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +        return;
Ну кст, такого исполнения кажется быть не может, получается к нам прилетел результат какой-то предыдущей попытки, но мы должны были ее подчистить, это скорее код неправильно работает тогда

2024-04-16 00:09 UTC, shnikd commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +        return;
Тут тоже не может быть такого исполнения

2024-04-16 10:10 UTC, nikvas0 commented on ydb/core/tx/schemeshard/ut_background_cleaning/ut_background_cleaning.cpp
done

2024-04-17 08:21 UTC, shnikd commented
В целом мне кажется ок, но тут достаточно много изменений в schemeshard, поэтому пусть еще @ijon посмотрит

2024-04-17 08:22 UTC, shnikd submitted a review, later dismissed

2024-04-19 19:01 UTC, ijon requested changes
Посмотрел частично, будет продолжение.
Главные проблемы:
- видимый в результатах describe OwnerActorId, ненужный в путях
- временная директория, незащищённая от создания там произвольных объектов, и рекурсивное удаление временной директории, не учитывающее возможность наличия таких непредусмотренных объектов

2024-04-22 10:44 UTC, nikvas0 commented on ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
> +        Sleep(TDuration::Seconds(1));
Здесь не получится без sleep, так это скорее функциональные тесты, проверяющие ydb целиком, а не unit.
Вообще, в тестах ydb/core/kqp/ut/service/kqp* много sleep.

2024-04-22 10:47 UTC, nikvas0 commented on ydb/core/kqp/session_actor/kqp_temp_tables_manager.cpp
> +            EvRemoveDirResult
Консистентно с названиями операций
NKikimrSchemeOp::EOperationType::ESchemeOpDropTable
NKikimrSchemeOp::EOperationType::ESchemeOpRmDir

2024-04-23 09:57 UTC, nikvas0 commented on ydb/core/kqp/common/simple/temp_tables.cpp
> +        JoinPath({Database, ".tmp", "sessions", SessionId})) + "/";
done

2024-04-23 09:58 UTC, nikvas0 commented on ydb/core/protos/flat_scheme_op.proto
> +    optional NActorsProto.TActorId OwnerActorId = 2;
done

2024-04-23 09:58 UTC, nikvas0 commented on ydb/core/protos/flat_scheme_op.proto
> +    reserved 65; // deprecated TempTableOwnerActorId
done

2024-04-23 09:58 UTC, nikvas0 commented on ydb/core/protos/flat_scheme_op.proto
> +    optional NActorsProto.TActorId OwnerActorId = 16;
done

2024-04-23 09:58 UTC, nikvas0 commented on ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
> +        struct TEvMakeDirResult : public TEventLocal<TEvMakeDirResult, EEv::EvMakeDirResult> {
done

2024-05-14 12:06 UTC, ijon requested changes

2024-05-14 12:06 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__operation_mkdir.cpp
> +            }
Для директорий надо проверять только путь родителя:
1. чтобы не создать невременную директорию во временной зоне
2. чтобы не создать корень временной зоны во временной зоне
3. чтобы не создать временную директорию не во временной зоне

2024-05-15 08:26 UTC, ijon requested changes

2024-05-15 08:26 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +        const auto txId = GetCachedTxId(ctx);
`GetCachedTxId()` might return `InvalidTxId` -- for example, in the case when there are more then 100 items in `ObjectsToDrop`, cache will deplete on 101+ items.

Loop should check returned `txId` and stop when there is no tx-id work with.

2024-05-15 08:26 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
> +        const auto txId = GetCachedTxId(ctx);
Same comment: `GetCachedTxId()` could potentially return `InvalidTxId`.

2024-05-20 09:22 UTC, nikvas0 commented on ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
> +                    tableDesc->SetName(GetCreateTempTablePath(Database, SessionId, JoinPath({tableDesc->GetPath(), tableDesc->GetName()})));
Оно заполняется раньше при построении схемного запроса. Этот же код обычные таблицы создает.
Но добавлю assertы, хуже от них не будет.

2024-06-21 13:01 UTC, ijon approved these changes

2024-06-21 13:16 UTC, merged