YQL-18154: Don't skip hybrid for empty keyFilter
ydb-platform/ydb pull request #3604
Opened 2024-04-09 14:13 UTC by mxkovalev

2024-04-12 08:30 UTC, rvu1024 requested changes

2024-04-12 08:30 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_hybrid.cpp
> +        if (HasSettingsExcept(settings, DqReadSupportedSettings | EYtSettingType::KeyFilter2)) {
Надо включить в DqReadSupportedSettings

2024-04-15 08:51 UTC, mxkovalev commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_hybrid.cpp
> +        if (HasSettingsExcept(settings, DqReadSupportedSettings | EYtSettingType::KeyFilter2)) {
Поправил

2024-04-17 08:56 UTC, rvu1024 approved these changes

2024-04-17 08:56 UTC, merged