cut local db history
ydb-platform/ydb pull request #3611
Opened 2024-04-09 16:05 UTC by vporyadke

### Changelog entry 

cut non-needed entries from tablet storage history

### Changelog category 

* Improvement

### Additional information

...

2024-04-16 08:20 UTC, snaury requested changes, later dismissed
Насколько я вижу SeenBlob не вызывается для большого кол-ва потенциальных блобов, которые есть, но не загружаются на старте:

* Блобы со снепшотами, и возможно с коммитами, т.к. их может грузить системная часть во время восстановления лога
* В коммитах могут быть References, которые не грузятся (например потому что таблицу дропнули и нам грузить метаданные от её sst больше не нужно), но влияют на восстанавливаемость лога, их все нужно учитывать
* Блобы могут не грузиться, т.к. они уже есть в кеше (например follower -> leader промоушен), кроме того они могут грузиться через интерфейс ILoadBlob, а также неявным образом через shared cache
* Так называемые "внешние блобы" вообще не грузятся и не компактятся, но при этом могут быть разбросаны по самым разным каналам и поколениям, имхо после загрузки нужно проходить по всем page collection'ам всех sst и учитывать все входящие туда блобы
* Таблетка может одалживать блобы, такие sst с точки зрения таблетки находятся в дропнутых таблицах (и в итоге такие блобы почти нигде не фигурируют), а их удаление контролируется через borrow logic, нужно также учитывать все блобы, которые удерживает borrow logic
* Таблетка может не грузить какие-то sst потому что они в "холодных" таблицах, по таким таблицам мы вообще не можем определить из каких блобов они состоят, и нужно иметь какую-то защиты, что если мы не знаем полной картины, то и делать cut history не имеем права. Это частично пересекается с дропнутой (но ещё не заснепшоченной) таблицей. Нужно где-то контролировать этот флаг "есть потенциально неизвестные блобы", и в каких-то случаях дожидаться подверждённого снепшота и успешного gc, а в каких-то (как холодные таблицы) не гасить ничего пока таблицу не дропнут, и не произойдёт подверждённый снепшот с успешным gc.

Ещё минорное, сейчас не учитывается 0 канал, в котором локальная база не делает gc (его делает системная часть с использованием hard barrier'ов). Тут видимо нужно как-то решить, кооперируемся ли мы с gc системной части, и делаем cut history после успешного gc, либо делаем cut history по 0 каналу из системной части. Я в принципе склоняюсь к тому чтобы 0 канал обрезался в системной части, так что тут можно в этом плане ничего не делать, но просто на всякий случай упоминаю.

2024-04-16 08:20 UTC, snaury commented on ydb/core/tablet_flat/flat_executor.cpp
> +            OwnerCtx().Send(Launcher, ev.Release());
Мне кажется отправлять TEvCutTabletHistory сразу после загрузки не безопасно. Имхо нужно как-минимум сначала сделать gc во всех этих каналах, чтобы барьер успешно подвинулся как-минимум в последнюю entry по каждому каналу, и возможно чтобы этот факт также заперсистился. Иначе я опасаюсь ситуации, когда у нас по данным есть необходимость делать gc в каких-то поколениях канала (например ставить там DoNotKeep на блобы), а у таблетки в этом поколении уже дырка и она даже не знает в какую группу отправлять запрос.

2024-06-05 09:12 UTC, snaury reviewed
Что если у таблицы включены группы колонок, и в истории есть блобы во 2 канале от sst где часть данных в этой группе колонок, мы случайно не удалим этим блобы? Что если у таблицы включены "средние" (не "внешние") блобы во 2 канале и в таблице есть большие строки, которые сохранились во 2 канале, мы их случайно не удалим обрезав историю? Хорошо бы на такие кейсы тесты написать, например что вот у нас есть кейс с неправильным удалением блобов, у тебя тест падает, ты исправляешь код - начинает работать правильно.

2024-06-05 09:15 UTC, snaury commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +            for (const auto& [_, room] : table.Rooms) {
Во первых ColdBorrow - это данные, которые одолжены у другой таблетки, они не локальные и по идее не могут лежать в каналах этой таблетки. Во вторых подозрительно, что ты используешь Rooms в текущих настройках таблицы. Текущие настройки таблицы могут не иметь никакого отношения к ранее записанным sst, потому что могли быть записаны до недавнего альтера.

2024-06-05 09:26 UTC, snaury commented on ydb/core/tablet_flat/flat_executor.cpp
> +            OwnerCtx().Send(Launcher, ev.Release());
В последнем патче этот пункт кажется не исправлен, там ведь всё ещё может быть очередь DoNotKeep'ов в канал, но мы сразу после первого же снепшота можем отправить cut history на этот канал?

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_boot_loans.h
все одолженные блобы грузятся тут

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor.cpp
запускаем удаление после успешного снапшота

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
references могут не грузиться, так что отдельно проход по ним

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
обычная загрузка блобов

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
первый блоб в page collection - остальные естественно в тех же поколении+группе

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
после загрузки таблицы проходим по всем партам

2025-10-31 16:51 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
...а если есть холодные, то не режем, не можем быть уверены, что видели всё

2025-11-01 13:07 UTC, CyberROFL reviewed
Я посмотрел, но попрошу посмотреть ещё @snaury и @kunga. Ну и это надо мощно протестировать.

2026-04-03 08:51 UTC, CyberROFL reviewed
Нужно закрыть открытые обсуждения и починить сборку.

2026-04-06 12:48 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_gclogic.cpp
> +        }
Сделано так, чтобы не проставлялось в случае пустого множества вырезаемой истории

2026-04-06 15:29 UTC, CyberROFL commented on ydb/core/tablet_flat/flat_executor_bootlogic.h
Наверно, это можно удалить?

2026-04-06 15:29 UTC, CyberROFL commented on ydb/core/tablet_flat/flat_executor_gclogic_ut.cpp
Я бы на этот классик побольше тестов с краевыми случаями написал. LLM в помощь.

2026-04-08 12:26 UTC, CyberROFL reviewed
Остались незакрытые обсуждения. Закрой их и перепризови.

2026-04-09 10:52 UTC, CyberROFL submitted a review, later dismissed
Я готов шипнуть, но надо еще попросить посмотреть @ydb-platform/datashard.
И я бы превентивно пообщался с LLM и, возможно, написал побольше тестов в flat_executor_ut.cpp.

2026-04-15 16:31 UTC, pixcc commented on ydb/core/tablet_flat/flat_executor_gclogic.cpp
> +        auto historyToCut = HistoryCutter.GetHistoryToCut(channelId);
тут что-то форматирование поехало

2026-04-15 17:25 UTC, pixcc commented on ydb/core/tablet_flat/flat_executor_gclogic.cpp
> +                channel.SendCollectGarbageEntry(ctx, {}, {}, TabletStorageInfo->TabletID, channelId, historyEntry->GroupID, Generation, true, TGCTime{(historyEntry + 1)->FromGeneration, Max<ui32>()})
А если GroupID встретится в следующих записях из historyToCut после текущей, то блобы оттуда не будут удаляться?

Как будто не хватает тестов на повторяющиеся GroupID в разных записях истории.

2026-04-15 17:25 UTC, pixcc commented on ydb/core/tablet_flat/flat_executor_gclogic.h
> +        return result;
Какую-то бы гарантию, что никто случайно не модифицирует исходный вектор истории (например, когда-то в будущем в новом коде). А-то будут неприятные проезды из-за реаллокаций.

2026-04-17 10:28 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_gclogic.h
> +        return result;
Это ж TabletStorageInfo. Оно присылается хайвом и в течении жизни таблетки не меняется.

2026-04-17 10:29 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_gclogic.cpp
> +                channel.SendCollectGarbageEntry(ctx, {}, {}, TabletStorageInfo->TabletID, channelId, historyEntry->GroupID, Generation, true, TGCTime{(historyEntry + 1)->FromGeneration, Max<ui32>()})
Для этого поколение указывается. Добавил ео проверку в тест + поправил краевой кейс

2026-04-28 11:11 UTC, CyberROFL commented
@lex007in ждем ревью.

2026-06-03 00:10 UTC, lex007in commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +    SeenBlob(fetch.PageCollection->Label());
Bundle состоит из нескольких PageCollection (и каждый обычно в отдельном канале, один из которых основной, в котором индексы и остальное, а в других данные не-основных family). И кажется, во время boot предзагружаются данные только основного канала. Поэтому, кажется, здесь не все PageCollection пройдут.

Вижу тут два варианта:
1. делать SeenBlob для всех PageCollection.Label в Bundle, найденных в снапшоте (возможно даже для всех блоб id, найденых в снапшоте вызывать SeenBlob на всякий случай?).
2. уже после того, как собрали таблицы проходиться по всем партам и PageCollection в них (у тебя уже частично это есть в ExtractState, но там только для внешних Blobs)

2026-06-03 00:10 UTC, lex007in commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +        for (const auto& part : Result_->Database->GetTableParts(tableId)) {
Вот здесь, наверное, можно скастить к TPartStore типа как тут: https://github.com/ydb-platform/ydb/blob/main/ydb/core/tablet_flat/flat_executor.cpp#L3530 и пройтись по всем PageCollection.

2026-06-03 00:10 UTC, lex007in commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +            for (const auto& [_, room] : table.Rooms) {
Если есть ColdParts, то по сути все текущие каналы помечаем как Uncertain, правильно понял логику? А для чего это так?

2026-06-03 00:10 UTC, lex007in commented on ydb/core/tablet_flat/flat_executor_gclogic.cpp
> +                channel.SendCollectGarbageEntry(ctx, {}, {}, TabletStorageInfo->TabletID, channelId, historyEntry->GroupID, Generation, true, TGCTime{(historyEntry + 1)->FromGeneration - 1, Max<ui32>
Может, посылание хардбарриера под фичафлаг унести, на всякий случай?

2026-06-08 16:31 UTC, CyberROFL reviewed
Не забудь, пожалуйста, потом закрыть открытые обсуждения (исправлением или комментарием).

2026-07-08 14:30 UTC, vporyadke commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +            for (const auto& [_, room] : table.Rooms) {
Считаем, что c ними корректно посчитать историю не можем. По факту они, насколько я понимаю, нужны для бекапов, а им всё равно никакую историю резать не надо.

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet_flat/flat_executor_bootlogic.cpp
> +            }
Этот цикл надо перенести до проверки наличия part->Blobs (строчка 335 `if (!part || !part->Blobs) {`).
В part->Blobs содержатся external блобы, их может не быть (в большинстве случаев не будет, так как extблобы выключены по умолчанию). Но pageCollection всё ещё может быть несколько (например, при нескольких column family, которые включены по умолчанию)

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
Думаю, тут можно бы TWriteSource::GcLogChannel поставить.

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
Кажется, тут надо бы ещё WantCutHistoryAfterGc = false выставить.

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
Хм, а в 0 канале может быть что-то кроме коммитов?
И вообще, эта функция вроде же для всех новых коммитов вызываются, которые в текущем поколении. Кажется, достаточно только при старте, как и в tablet_flat (или просто добавить при старте текущее поколение в seen).

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
А не достаточно одного раза после старта?

2026-07-10 00:55 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
Мне кажется, можно было бы как-то проще сделать: у нас же в 0 канале только коммиты, по идее все коммиты до подтверждённого снапшота можно почистить (но тут надо убедиться, точно ли так).

2026-07-10 15:11 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
> +    SeenBlobForCutHistory(logid);
Это тоже кажется не нужно, можно где-то на старте в HistoryCutter либо KnownGeneration как-то прокинуть, либо нулевой коммит (ну, его logoblobId)

2026-07-10 15:11 UTC, lex007in commented on ydb/core/tablet/tablet_sys.cpp
> +            WantCutHistoryAfterGc = true;
Можно было бы вообще при EnableCutHistor не выставлять тут WantCutHistoryAfterGc, было бы менльше вызовов)

2026-07-10 16:06 UTC, lex007in approved these changes

2026-07-10 20:11 UTC, merged