First iteration of Logstash plugin docs
ydb-platform/ydb pull request #3646
Opened 2024-04-10 15:03 UTC by alex268

### Changelog category 
* Documentation (changelog entry is not required)

2024-04-26 10:41 UTC, blinkov requested changes

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +* Storage Plugin для сохранения данных в таблице ([строчной](../concepts/datamodel/table.md#strokovye-tablicy) или [колоночной](../concepts/datamodel/table.md#column-tables)) {{ ydb-short-name }}
```suggestion
* Storage Plugin для сохранения данных в [строчной](../concepts/datamodel/table.md#strokovye-tablicy) или [колоночной](../concepts/datamodel/table.md#column-tables) таблице {{ ydb-short-name }};
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +* Output Topic Pluing для отправки данных в [топик](../concepts/topic.md) {{ ydb-short-name }}
```suggestion
* Input Topic Plugin для чтение данных из {{ ydb-short-name }} [топика](../concepts/topic.md) ;
* Output Topic Plugin для отправки данных в {{ ydb-short-name }} [топик](../concepts/topic.md).
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Плагины можно [собрать](https://github.com/ydb-platform/ydb-logstash-plugins/blob/main/BUILD.md) самостоятельно из исходного кода либо воспользовать готовыми [сборками](https://github.com/ydb-platfor
```suggestion
Плагины можно [собрать](https://github.com/ydb-platform/ydb-logstash-plugins/blob/main/BUILD.md) самостоятельно из исходного кода, либо воспользоваться готовыми [сборками](https://github.com/ydb-platform/ydb-logstash-plugins/releases) под две последнии версии Logstash.
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +path-to-logstash/bin/logstash-plugin install /path/to/logstash-plugin.gem
```suggestion
<path-to-logstash>/bin/logstash-plugin install </path/to/logstash-plugin.gem>
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +path-to-logstash/bin/logstash-plugin list
```suggestion
<path-to-logstash>/bin/logstash-plugin list
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Проверить что плагин установлен можно командой
```suggestion
Проверить, что плагин установлен, можно командой
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Которая выведет список всех установленных плагинов
```suggestion
Эта команда выведет список всех установленных плагинов, в котором можно найти интересующие.
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Данный плагин позволяет перенаправить поток данных из Logstash в таблицу {{ ydb-short-name }} для дальнешего анализа. Для этого удобно использовать [колоночные таблицы](../concepts/datamodel/table.md
```suggestion
Данный плагин позволяет перенаправить поток данных из Logstash в таблицу {{ ydb-short-name }} для дальнешего анализа. Для этого рекомендуется использовать [колоночные таблицы](../concepts/datamodel/table.md#column-tables), оптимизированные для аналитических запросов.
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +В выбранной базе данных {{ ydb-short-name }} мы можем создать новуб колоночную таблицу с нужными нами колонками. Ограничения накладываются на количество и тип колонок главного ключа - это обязательно
```suggestion
В выбранной базе данных {{ ydb-short-name }} мы можем создать новую колоночную таблицу с нужной схемой данных. Ограничения накладываются на количество и тип колонок первичного ключа — это обязательно должна быть одна колонка с типом `Text`, так как именно такой идентификатор используется в Logstash.
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +         `rec_id` -- Главный ключ всегда должен состоять из одной колонки идентификатора
```suggestion
         `rec_id` -- Первичный ключ всегда должен состоять только из колонки идентификатора
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +path-to-logstash/bin/logstash-plugin install /path/to/logstash-plugin.gem
хорошо бы досыпать конкретных команд как это всё установить с чистого листа на пустом сервере

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Для настройки плагина мы должен добавить секцию `ydb_storage_plugin` в раздел `output` файла конфигурации [Logstash](https://www.elastic.co/guide/en/logstash/current/configuration.html). Здесь указан
```suggestion
Для настройки плагина необходимо добавить секцию `ydb_storage_plugin` в раздел `output` файла конфигурации [Logstash](https://www.elastic.co/guide/en/logstash/current/configuration.html). Здесь указаны только специфичные для данного плагина опции. Об опциях подключения к {{ ydb-short-name }} можно прочитать в разделе [Конфигурация подключения плагинов к  {{ ydb-short-name }}](#konfiguraciya-podklyucheniya-plaginov-k-ydb).
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +    ...                                                  # Опции подключения к {{ ydb-short-name }}
внутри кода переменные вроде не подставлялись

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Для проверки работоспособности плагина можно добавить возможность отправки сообщений в Logstash через http (добавив плагин `http` в секцию `input`)
```suggestion
Для проверки работоспособности плагина можно добавить возможность отправки сообщений в Logstash через http (добавив плагин `http` в секцию `input`):
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Затем можно отправить тестовое сообщение
```suggestion
Затем можно отправить тестовое сообщение:
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +и убедиться что данное сообщение записано в таблицу
```suggestion
И убедиться что данное сообщение записано в таблицу:
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +SELECT * FROM `logstash_demo`;
добавить что эта и предыдущая команда должна вернуть + как именно предлагается выполнять запрос

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +    columns => "message, Text, user, Text, level, Int32" # Список колонок и их типов.
выглядит очень странно: почему между колонками и типами одинаковые разделители?

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +
недописано

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, все остальные параметры опцион
ссылку на доку про аутентификацию

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, все остальные параметры опцион
```suggestion
Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, а все остальные параметры опциональны и задают режим аутентификации. Если ни один из них не указан, то будет использоваться анонимная аутентфикация.
```

2024-04-26 10:41 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +<ydb_plugin> {
угловые скобки вокруг всех placeholder нарисовать, а не только этого

2024-05-23 05:03 UTC, blinkov requested changes

2024-05-23 05:03 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, а все остальные параметры опци
```suggestion
Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, а все остальные параметры опциональны и позволяют задать [режим аутентификации](../concepts/auth.md). Если ни один из них не указан, то будет использоваться анонимная аутентификация.
```

2024-05-23 05:03 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +    sa_key_file => "/path/to/key.json"
```suggestion
    token_auth => "<token_value>"
    # Путь до файла со значением токена аутентификации (режим Access Token)
    token_file => "</path/to/token/file>"
    # Путь до ключа сервисного аккаунта (режим Service Account Key)
    sa_key_file => "</path/to/key.json>"
```

2024-06-10 03:59 UTC, blinkov requested changes, later dismissed

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +This section presents the description of plugins which may be used for connect {{ ydb-short-name }} and Logstash - a free and open server-side data processing pipeline.
```suggestion
This section describes the integration options between {{ ydb-short-name }} and Logstash, a server-side data collection and processing pipeline.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +[Logstash](https://www.elastic.co/logstash) dynamically ingests, transforms, and ships your data regardless of format or complexity. A Logstash pipeline can contains different types of plugins - inpu
```suggestion
[Logstash](https://www.elastic.co/logstash) dynamically ingests, transforms, and ships data regardless of format or complexity. A Logstash pipeline can contain different types of plugins: input, output, and filter. The {{ ydb-short-name }} Logstash plugins repository is hosted on [GitHub](https://github.com/ydb-platform/ydb-logstash-plugins) and contains the following plugins:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +* Output Topic Plugin for sending Logstash events tp {{ ydb-short-name }} [topic](../concepts/topic.md).
```suggestion
* **Storage Plugin** for persisting Logstash events in [row-oriented](../concepts/datamodel/table.md#row-orineted_table) or [column-oriented](../concepts/datamodel/table.md#olap-data-types) {{ ydb-short-name }} tables.
* **Input Topic Plugin** for reading Logstash events from {{ ydb-short-name }} [topics](../concepts/topic.md).
* **Output Topic Plugin** for sending Logstash events to {{ ydb-short-name }} [topics](../concepts/topic.md).
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> + You can [build](https://github.com/ydb-platform/ydb-logstash-plugins/blob/main/BUILD.md) plugins yourself from sources or download pre-builded [artifacts](https://github.com/ydb-platform/ydb-logstas
```suggestion
These plugins can be [built](https://github.com/ydb-platform/ydb-logstash-plugins/blob/main/BUILD.md) from the source code or downloaded as pre-built [artifacts](https://github.com/ydb-platform/ydb-logstash-plugins/releases) for the two latest versions of Logstash.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Further code snippets use a placeholder `<path-to-logstash>`, which must be replaced by the path to installed Logstash.
```suggestion
Further code snippets use the placeholder `<path-to-logstash>`, which must be replaced by a path to a directory with installed Logstash.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Any Logstash plugin may be installed by execution of command
```suggestion
Execute the following command to install any Logstash plugin:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Check that the plugin is installed
```suggestion
Check that the plugin has been installed:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +The command will return a list of all installed plugins and this list must contain the name of installed plugin.
```suggestion
The command will return a list of all installed plugins, which must contain the plugin's name.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +All plugins use the same set of parameters for configure connection to {{ ydb-short-name }}. This set contains only one required parameter `connection_string`, others parameters are optional and allo
```suggestion
All plugins use the same set of parameters to configure the connection to {{ ydb-short-name }}. This set contains only one required parameter, `connection_string`. Other parameters are optional and allow configuring [an authentication mode](../concepts/auth.md). An anonymous mode will be used if the configuration doesn't contain any of these parameters.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    # Database connection string contains schema, hostname, port and database path
```suggestion
    # Database connection string contains a schema, hostname, port, and database path
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    # Authentication token (for using Access Token mode)
```suggestion
    # Authentication token (for using "Access Token" mode)
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    # Authentication token file path (for using Access Token mode)
```suggestion
    # Authentication token file path (for using the "Access Token" mode)
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    # Service account key file path (for using Service Account Key mode)
```suggestion
    # Service account key file path (for using the "Service Account Key" mode)
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    # Flag to use metadata authentication service (for using Metadata mode)
```suggestion
    # Flag to use metadata authentication service (for using the "Metadata" mode)
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +This plugin allows to store the Logstash events stream in {{ ydb-short-name }} tables for further analysis. This is especially useful with [column tables](../concepts/datamodel/table.md#column-tables
```suggestion
This plugin allows storing the Logstash events stream in {{ ydb-short-name }} tables for further analysis. This is especially useful with [column-oriented tables](../concepts/datamodel/table.md#column-tables) optimized for handling Online Analytical Processing (OLAP) requests. Every [field](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html) of a Logstash event will be stored in a column with a corresponding name. Fields that do not match any column will be ignored.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +The plugin configuration is making by adding `ydb_storage` block in `output` section of Logstash pipeline [config file](https://www.elastic.co/guide/en/logstash/current/configuration.html). The plugi
```suggestion
The plugin configuration is done by adding a `ydb_storage` block in the `output` section of the Logstash pipeline [config file](https://www.elastic.co/guide/en/logstash/current/configuration.html). The plugin supports the standard set of [connection parameters](#configure-ydb-connection) and a few additional options:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +* `timestamp_column` — optional name of column which the plugin will use for storing the timestamp of event
```suggestion
* `table_name` — the required name of the destination table.
* `uuid_column` — the optional name of the column that the plugin will use for storing an auto-generated identifier.
* `timestamp_column` — the optional name of the column that the plugin will use for storing the event's timestamp.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +The Storage plugin doesn't check if the logstash event has correct and unique values for the table primary keys. It uses [bulk upsert method](../dev/batch-upload.md) for storing in {{ ydb-short-name
```suggestion
The Storage plugin doesn't check if the Logstash event has correct and unique values for the table's primary key. It uses the [bulk upsert method](../dev/batch-upload.md) for storing data in {{ ydb-short-name }}, and if multiple events have the same primary keys, they will overwrite each other. The primary key is recommended to contain those event fields that will be present in every event and can uniquely identify each event. If no such set of fields exists, add an extra column to the primary key and fill it with a random value using the `uuid_column` parameter.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +### Example of usage
```suggestion
### Usage example
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Let's create a new column-based table in any existing {{ ydb-short-name }} database with the columns we need. For a primary key we will use a random value generated by the plugin.
```suggestion
Create a new column-oriented table with the necessary columns in any existing {{ ydb-short-name }} database. For example, the table below uses a random value generated by the plugin.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For activation of plugin we can add `ydb_storage` block in `output` section of Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally let's add
```suggestion
To activate the plugin, add the `ydb_storage` block in the `output` section of the Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally, add the `http` block in the `input` section for creating test messages via HTTP requests:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For applying the changes we need to restart `Logstash`.
```suggestion
To apply these changes, restart Logstash.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Then we can sent a few test messages:
```suggestion
#### Send test messages
Send a few test messages:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Now we can check that all sent messages are written in the table. Let's execute query (for work with the column-based table we must use [ScanQuery mode](../reference/ydb-cli/commands/scan-query.md)):
```suggestion
#### Check that the messages are stored in {{ ydb-short-name }} 

To check that all sent messages are written to the table, execute the following query using [ScanQuery mode](../reference/ydb-cli/commands/scan-query.md)):
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +and we will get a list of written events:
```suggestion
The query will return a list of written events:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +
```suggestion
## {{ ydb-short-name }} Topic Input Plugin

This plugin allows reading messages from {{ ydb-short-name }} [topics](../concepts/topic.md) and transforming them into `Logstash` events.

```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +The plugin configuration is making by adding `ydb_topic` block to the `input` section of Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html).The plugin sup
```suggestion
The plugin configuration is done by adding a `ydb_topic` block to the `input` section of the Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). The plugin supports the standard set of [connection parameters](#configure-ydb-connection) and a few additional options:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +* `schema` — optional mode of the processing of the {{ ydb-short-name }} events. By default the plugin reads and sent the message as binary data, but if you specify `JSON` mode - every message will b
```suggestion
* `topic_path` — the required full path of the topic for reading.
* `consumer_name` — the required name of the topic [consumer](../concepts/topic.md#consumer).
* `schema` — optional mode for processing {{ ydb-short-name }} events. By default, the plugin reads and sends messages as binary data, but if you specify the `JSON` mode, each message will be parsed as a JSON object.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +### Example of usage
```suggestion
### Usage example
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Let's create a topic and a consumer in any existing {{ ydb-short-name }} database:
```suggestion
Create a topic and add a consumer to it in any existing {{ ydb-short-name }} database:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For the plugin activation we can add `ydb_topic` block in `input` section of Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally let's add `s
```suggestion
To activate the plugin, add the `ydb_topic` block in the `input` section of the Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally, add the `stdout` plugin in the `output` section for logging all `Logstash` events:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    connection_string => "grpc://localhost:2136/local" # Connection string to {{ ydb-short-name }}
```suggestion
    connection_string => "grpc://localhost:2136/local" # {{ ydb-short-name }} connection string
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    consumer_name => "logstash-consumer"               # The name of the consumer
```suggestion
    consumer_name => "logstash-consumer"               # The consumer name
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    codec => rubydebug
It needs a comment, preferably with a link to the list of available codecs.

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For applying the changes we need to restart `Logstash`.
```suggestion
To apply these changes, restart Logstash.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Then we can send a few test messages:
```suggestion
Send a few test messages to the topic:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +The plugin `stdout` allows to see the messages in `Logstash` logs:
```suggestion
#### Check if Logstash processed the messages

The `stdout` plugin writes the messages to the Logstash logs:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +This plugin allows to write `Logstash` event to the {{ ydb-short-name }} [topic](../concepts/topic.md).
```suggestion
This plugin allows writing `Logstash` events to a {{ ydb-short-name }} [topic](../concepts/topic.md).
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +* `topic_path` — required the full path of the topic for writing.
```suggestion
The plugin configuration is done by adding a `ydb_topic` block to the `output` section of the Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). The plugin supports the standard set of [connection parameters](#configure-ydb-connection) and a few additional options:

* `topic_path` — the required full path of the topic for writing.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +### Example of usage
```suggestion
### Usage example
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +#### Creating a topic
```suggestion
#### Create a topic
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +#### Creation a topic
```suggestion
#### Create a topic
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Let's create a topic in any existing {{ ydb-short-name }} database:
```suggestion
Create a topic in any existing {{ ydb-short-name }} database:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For the plugin activation we can add `ydb_topic` block in `output` section of Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally let's add `
```suggestion
To activate the plugin, add the `ydb_topic` block in the `output` section of the Logstash pipeline [config](https://www.elastic.co/guide/en/logstash/current/configuration.html). Additionally, add the `http` block in the `input` section for creating test messages via HTTP requests:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    connection_string => "grpc://localhost:2136/local" # Connection string to {{ ydb-short-name }}
```suggestion
    connection_string => "grpc://localhost:2136/local" # {{ ydb-short-name }} connection string
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    port => 9876 # You can specify any free port
```suggestion
    port => 9876 # Any free port
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    port => 9876 # You can specify any free port
```suggestion
    port => 9876 # Any free port
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    connection_string => "..."    # connection string to  {{ ydb-short-name }}
```suggestion
    connection_string => "..."    # {{ ydb-short-name }} connection string
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    timestamp_column => "ts"      # the key for storing the event timestamp
```suggestion
    timestamp_column => "ts"      # the column for storing the event timestamp
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +    uuid_column => "uuid"         # the primary key column with random uuid
```suggestion
    uuid_column => "uuid"         # the primary key column with a random UUID
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +For applying the changes we need to restart `Logstash`.
```suggestion
To apply these changes, restart Logstash.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +Let's send a test message via `http` plugin:
```suggestion
Send a test message via the `http` plugin:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +We get `ok` if the message sending is successful.
```suggestion
The command returns `ok` if the message has been sent successfully.
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +We can check that the plugin wrote the message to the topic successful with reading this message by CLI:
```suggestion
Check that the plugin wrote the message to the topic successfully by reading this message via CLI:
```

2024-06-10 03:59 UTC, blinkov commented on ydb/docs/en/core/integrations/logstash.md
> +And there will be a content of the message:
```suggestion
The latter command will return the message content:
```

2024-06-12 16:16 UTC, fomichev3000 requested changes, later dismissed

2024-06-12 16:16 UTC, fomichev3000 commented on ydb/docs/ru/core/integrations/logstash.md
> +[Logstash](https://www.elastic.co/logstash) – инструмент сбора, фильтрации и нормализации логов. Данный продукт позволяет динамически получать, фильтровать и доставлять данные независимо от их формат
производитЬся -> производится

2024-06-12 16:16 UTC, fomichev3000 commented on ydb/docs/ru/core/integrations/logstash.md
> +Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, а все остальные параметры опци
"Среди этих параметров только `connection_string` обязателен" -> "Среди этих параметров обязателен только `connection_string`"

2024-06-13 02:53 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +[Logstash](https://www.elastic.co/logstash) – инструмент сбора, фильтрации и нормализации логов. Данный продукт позволяет динамически получать, фильтровать и доставлять данные независимо от их формат
```suggestion
[Logstash](https://www.elastic.co/logstash) – инструмент сбора, фильтрации и нормализации логов. Данный продукт позволяет динамически получать, фильтровать и доставлять данные независимо от их формата и сложности. Конфигурация системы производится с помощью плагинов различных типов - input, output и filter. Набор Logstash плагинов для работы с {{ ydb-short-name }} располагается в репозитории [ydb-logstash-plugins](https://github.com/ydb-platform/ydb-logstash-plugins):
```

2024-06-13 02:56 UTC, blinkov commented on ydb/docs/ru/core/integrations/logstash.md
> +Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров только `connection_string` обязателен, а все остальные параметры опци
```suggestion
Все плагины используют одни и те же параметры для настройки подключения к базе данных {{ ydb-short-name }}. Среди этих параметров обязателен только `connection_string`, а все остальные параметры опциональны и позволяют задать [режим аутентификации](../concepts/auth.md). Если ни один из них не указан, то будет использоваться анонимная аутентификация.
```

2024-06-13 02:57 UTC, blinkov approved these changes

2024-06-13 03:00 UTC, merged