Add support for <timestamp=...> in YT paths
ydb-platform/ydb pull request #3699
Opened 2024-04-12 10:56 UTC by avevad

### Changelog entry 

Add support for <timestamp=...> in YT paths

### Changelog category 

* New feature

### Additional information

...

2024-04-15 09:57 UTC, rvu1024 requested changes

2024-04-15 09:57 UTC, rvu1024 commented on ydb/library/yql/providers/yt/expr_nodes/yql_yt_expr_nodes.json
> +                {"Index": 4, "Name": "Timestamp", "Type": "TCoUint64"}
Нужно использовать TExprBase, что бы задавать `Void` для путей без timestamp

2024-04-15 09:57 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp
>                  .Done();
Используй здесь InitFrom(path)

2024-04-15 09:57 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
> +
Тут надо переделать проверку с учетом возможного `Void`

2024-04-15 09:57 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
> +    .Build();
Void, если Timestamp = Nothing

2024-04-15 14:19 UTC, avevad commented on ydb/library/yql/providers/yt/expr_nodes/yql_yt_expr_nodes.json
> +                {"Index": 4, "Name": "Timestamp", "Type": "TCoUint64"}
сделал

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
> +            node.ChildrenSize()));
EnsureMinMaxArgsCount

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/lib/yt_helpers.cpp
> +            throw yexception() << "Unsupported rich YPath attribute: '" << attr << "'";
`Unsupported YPath attribute:`

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
> +    }
EnsureAtom

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
> +            .Value(*AdditionalAttributes)
`, TNodeFlags::MultilineContent`

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/lib/yt_helpers.cpp
> +    CheckRichYPathAttrs(attrsNode);
здесь не нужно чекать

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.h
> +#include <ydb/library/yql/core/expr_nodes/yql_expr_nodes.h>
кажется лишним

2024-04-18 14:42 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/lib/yt_helpers.cpp
> +}
Надо исключить тут columns и ranges - мы их отдельно храним

2024-04-19 09:38 UTC, rvu1024 approved these changes

2024-04-19 13:23 UTC, merged