For YT tables, provide table's key into TOptimizerStatistics
ydb-platform/ydb pull request #3754
Opened 2024-04-15 16:36 UTC by alephonea

Use that key in CBO cost function IsPKJoin()

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-04-16 15:03 UTC, rvu1024 requested changes

2024-04-16 15:03 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +                    statInfo->PrimaryKey = GetPrimaryKey(attrs);
Информация о сортировке уже присутствует в _yql_row_spec. Нужно ее брать от туда, а не читать schema повторно

2024-04-18 13:22 UTC, alephonea commented on ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
> +                    statInfo->PrimaryKey = GetPrimaryKey(attrs);
Done

2024-04-18 13:22 UTC, alephonea commented on ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
> +                auto tableStat = TYtTableBaseInfo::GetStat(section.Paths().Item(0).Table());
Done

2024-04-19 13:50 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
> +            if (section.Paths().Size() == 1) {
Почему только для одной таблицы?
Вообще, можно взять констрейнт сортировке на узле section. Если он есть, то это гарантирует, что все таблицы в секции отсортированны по одинаковому префиксу. Префикс можно взять из констрейнта

2024-04-22 16:36 UTC, rvu1024 requested changes

2024-04-22 16:36 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
> +        if (ExprCtx.IsConstraintEnabled<TSortedConstraintNode>()) {
Это лишняя проверка. Констрейнта и так не будет на узле, если он отключен

2024-04-22 16:36 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
> +    TExprContext& ExprCtx;
Становится не нужным, если убрать излишнюю проверку

2024-04-22 16:36 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.cpp
> +    YQL_CLOG(ERROR, ProviderYt) << "IsPKJoin true";
debug выдача?

2024-04-22 16:36 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
> +                }
Неправильно интерпретируется содержимое констрейнта. Простой вариант можно посмотреть здесь https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/yt/opt/yql_yt_key_selector.cpp#L104.
Если хочется учесть все варианты сортировки (они могут возникать из-за алаисов колонок), то стоит посмотреть на https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/yt/provider/yql_yt_physical_optimize.cpp#L1152

2024-09-25 10:40 UTC, closed without merging