YQ-2863: add StreamExecuteScanQuery and DeleteSession for ydb_over_fq
ydb-platform/ydb pull request #3787
Opened 2024-04-16 14:55 UTC by EgorkaZ

### Changelog entry 

...

### Changelog category 

* Improvement

### Additional information

...

2024-04-17 12:20 UTC, dorooleg requested changes

2024-04-17 12:20 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/rpc_base.h
>  protected:
Давай эту функцию один раз только вызывать как это сделано в https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp?rev=13871339#L40

2024-04-17 12:20 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/rpc_base.h
> +        Y_PROTOBUF_SUPPRESS_NODISCARD response.SerializeToString(&serialized);
А мы можем в issues отослать ошибку в этом случае?

2024-04-17 12:20 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/execute_data_query.cpp
> +        Y_PROTOBUF_SUPPRESS_NODISCARD response.SerializeToString(&respSerialized);
тут тоже нужно ошибку репортить

2024-04-18 13:50 UTC, dorooleg commented on ydb/core/grpc_services/ydb_over_fq/rpc_base.h
> +#define SRC_LOG_T(s, ...) LOG_TRACE_S(ctx, NKikimrServices::FQ_INTERNAL_SERVICE, LogCtx(__VA_ARGS__) << s)
Не очевидно конечно что query id в конце дописывается) И вызов LogCtx на каждое логирование остался. Можно его один раз в строку записать и использовать?

2024-04-18 15:17 UTC, EgorkaZ commented on ydb/core/grpc_services/ydb_over_fq/rpc_base.h
> +#define SRC_LOG_T(s, ...) LOG_TRACE_S(ctx, NKikimrServices::FQ_INTERNAL_SERVICE, LogCtx(__VA_ARGS__) << s)
Постоянный префикс запишу, опциональный с `queryId` всё-таки оставлю на откуп функции. Копирование из `StringBuilder`' а в `StringBuilder` уберу

2024-04-18 15:29 UTC, dorooleg approved these changes

2024-04-19 10:16 UTC, merged