Check alter version only for ss applyIf
ydb-platform/ydb pull request #3823
Opened 2024-04-17 13:10 UTC by niksaveliev

- Intermediate changes
- Add `-Clause-LBNL` 8bb6f4febc15de33fe0d0ec2d815e44ded809be8
- Fix tidy graph generation d73e9d9d44959cde8441e9d1fca4068504282b2e
- Intermediate changes
- YT-20426: Support shared write locks on rpc proxy 3204feb9fdc0206822f63b61749f4622c4398afb
- Set empty default value to platforms 83fbdf1b24e11682d645ebddc398c3b197443ec1
- Export CRoaring to YDB 6678dec27164a5072c9d59a374c825a579fb27a8
- Fix address resolver configuration
- Add missing arm intrinsic (used in contrib/libs/eigen) 6b6130be7b24c4bac7ece7d8661de59e1cd0cd55
- YT-19625: Better lag calculation for chaos nodes 24176d3c6131c680513bec67ac4412e5717e3ac2
- Improve generated cmake disclamer e9f415115eeddf99b539fd8f1864c3a1f122cf6d
- Intermediate changes
- delete obsolete multimodule YQL_UDF_YDB 880ebb40cc315f82a6cab1da37691784ef9219a6
- Remove unusued fields
- Intermediate changes
- YT: Apply aliasing rules in CreateClientImpl
- Rebuild clang-format with ttl=inf 66fb9b2206429eca139f47eefe9d79b58a447a5b
- Use same configs in ya style and style-tests 853c2293128f6f534d97c1a5c97204e1f72868cf
- Fix preedirs  yt/cpp/mapreduce/library/table_schema
- New version of the tld SKIP_CHECK SKIP_REVIEW 885af1f4dbd3971fa148db453793b3bcba86ea06
- Revert commit rXXXXXX, delete obsolete multimodule YQL_UDF_YDB ea2f74d8d807ed70418e46163aaff06363beca94
- Do not drop adincls in ya make opensource build because of cmake export replacements a118aa391374ee757d795d5237e28fb8cf1e74fe
- Intermediate changes
- Update asm in jacoco
- Intermediate changes
- YDB Import 592 c6406a6fe091e307711ab90b789a786479e74a3a
- YT-21402: Fibers Refactoring pt.1: Introduce FunctionView to use it as AfterSwitch and improved registry algorithm
- YT-21472: Disable slot manager if layer cache disabled 9cfa8a698bc7b54a4c21e77846419a417ca66eea
- Intermediate changes
- Add THttpServerOutput::ContentBytesWritten 042561a12173d74b7f904c5e5b4c2a89c148015f
- Intermediate changes
- New version of the tld SKIP_CHECK SKIP_REVIEW ed46af53587fda3122e7fdad8c6f60ef76e66e0e
- Master connection config fix YT-20418
- YT-18503: Mirror Cypress Tx to Sequoia Ground e6d585180289325f8082f42f85a60478194ba266
- fix test YdbLogStore.LogTable (#3535)
- Import libraries 240408-0819
- Allow customize wall-e provider (#3515)
- YQL-18095: Disable plan check for join_left_sample test (#3500)
- KIKIMR-18545: do not set not_null for default values (#3512)
- resource manager to control execution units (#3239)
- YQ-3011 fix parquet type validation (#3502)
- TFederatedWriteSession: take into account AllowFallback setting; use retry policy (#3460)
- patches for zabbix and wiki (#2912)
- Moving kikimr_slice to github (#3549)
- Fix offset processing in DecompressToSparseBitmap (#3534)
- fix array access for merge on kqp (#3540)
- Support new datetime types in range. (#3539)
- [Configs] Add basic audit for yaml configs (#3531)
- Reading for autoscale (old sdk, intermediate) (#3490)
- Add forgotten arg in ydbd_slice (#3556)
- Support ListFromRange for bigdates (#3514)
- fix local db downsampling (#3487)
- Add pragma for YT option 'expiration_timeout' (#3451)
- Added event attribute to DSProxy.* spans (#3509)
- Right column order when block read (#3545)
- Add `REQUIREMENTS(cpu:all)` to the top level of every ya.make in `ydb/library/yql/providers/generic/connector/tests` (#3520)
- The grpc stream must be finished in case of grpc proxy emmited YDB error (#3560)
- BTreeIndex Add GroupDataSize (#3478)
- run pr-check on all branches contains -stable- (#3578)
- Fix hive scheme tests (#3576)
- [Pretty Table] Fixed bug (#3513)
- optimize counters construction (reusage now) (#3574)
- use sequential read for data copy (#3555)
- Enable Timestamp64/Interval64 as PK. (#3581)
- TFederatedWriteSession: Wait for messages to be sent in Close method (#3409)
- Support of dates & uuid in FromPg (#3568)
- Add compaction logs (#3475)
- fix partition counter value (#3579)
- Reorder read_balancer.h and use collections from stl (#3563)
- Builder for new datetime types. (#3583)
- Added blob_id attributes to VDisk spans (#3570)
- Optimized TPC-H Q4 (#3582)
- Remove unnecessary abort when periodic table stats are received from "deleted" shard (#3567)
- statistics aggregator logic of table scanning (#3492)
- Topic's supported codecs was changed while changing partitions count (#3577)
- Fixed multiple inputs to aggeregate in Simplified JSON (#3566)
- ybdb_slice improvements (#3585)
- one cycle for processing transactions, writing operations and promoting offsets (#3546)
- [import] fix whitespace (#3596)
- add TValueBuilderBase::Date32, Datetime64, Timestamp64 and Interavl64… (#3589)
- ydb_topic: split write messages on different codecs (#3428)
- Fix flake8 warning in arcadia tests (#3454)
- by default keep drained nodes down until they restart (#2975)
- Fix ThrottlingException raising in YMQ when doing GetQueueUrl with drained queue list budget (#3600)
- Add limit for LLVM node count (#3435)
- Add single-thread tests for mpmc ring queue (#3601)
- Allow uig.sh to load yql udfs outside ydb tree (#3550)
- DQ gateways fixes (#3610)
- [Liquibase]: documentation for the Ydb Dialect of Liquibase (#2606)
- [Configs] Make yaml config page first at CMS (#3532)
- YQ-2068 Introduce stream lookup input transform in passthrough(no lookup) mode (#3507)
- Fix flake8 in ydbd_slice (#3612)
- fix scanner deadlock and memory overhead usage (#3614)
- add arrow check when parse TOlapColumnAdd (#3599)
- YQ-3010 Check fields count and types in raw format (s3 and pq) (#3352)
- Report PQ SDK Errors to user (#2855)
- fix tpch column types (#3562)
- ci: save logs for all test types into logsdir for failed tests (#3247)
- tests canonization (#3558)
- drop mute for clickbench tests (#3625)
- Fix enum convert. (#3624)
- Fix not piped processes in ydbd_slice (#3626)
- Bigdate fix multiplication and integer overflows (#3401)
- Reorder Q11 like CBO (#3592)
- Support part size limit in case of request via kqp proxy service (#3609)
- More self-contained dq comp_node (#3605)
- Fix static group status calculation logic (#3627)
- split huge tests file (#3629)
- [backups] fix windows build (#3628)
- YQ-3036 Update ttl on query modify  (#3554)
- RoundDown/RoundUp for bigdates (#3615)
- Added pg type category into result type format (#3618)
- Add basic multithread tests fot MPMCRingQueue (#3631)
- Mute `ydb/library/yql/providers/generic/connector/tests` (#3642)
- Add mvp to github (#3622)
- Use NO_BUILD_IF instead of empty library (relates YQL-17642), take II (#3580)
-  added QuotaStorage to tenantinfo response (#3463)
- Add analytical and operational nodes (#3077)
- add signals and logging (#3639)
- Add metrics for TMPMCRingQueue (#3643)
- Warning on join hints for cross join (#3644)
- [YQL-18053] Fix optimizer bugs uncovered by Struct support in block mode (#3647)
- Fixed ignoring --timeout option (#3648)
- Fix race (#3649)
- add  [[fallthrough]] (#3551)
- enable pgwire logging for pg-expirement (#3590)
- Git ignore .clangd files (#3216)
- Check .attr files too (#3655)
- improve/fix schema snapshot test (#3661)
- checkpoint hangup has been fixed (#3658)
- do not check explicit sources every cleanup (#3638)
- write to topic in transaction (#3650)
- test TxUsage.WriteTopic is broken (#3668)
- Add new datetime ctors. (#3660)
- Reading for autoscaling (oldSDK, dedn't start reading from EndOffset) (#3623)
- Fix for empty name in rpc (#3670)
- use security printer (#3603)
- Add more tests for TMPMCRingQueue (#3663)
- YQL-17167: Add Spilling support to Sort operator (#3339)
- Remove total timeout to be 15 min default (#3675)
- fix(kqp): pass column order to KqpIndexLookupJoin (#3654)
- Yql-17175 add spiller adapter for gracejoin spilling (#3652)
- cloud id has been fixed (#3544)
- Support configuration updates via distconf InvokeOnRoot (#3679)
- YQ-2068 make IsPresortSupported const (#3657)
- Unordered mode in result provider (#3666)
- Support create sequence (#3662)
- Add TxCompleteLag signal (#3588)
- Fix IAM layout (#1623)
- Fix UB [...]

2024-04-17 13:12 UTC, niksaveliev commented on ydb/core/tx/schemeshard/schemeshard_impl.cpp
> +                switch(path.Base()->PathType) {
Если такой вариант реализации ОК, то разверну здесь остальные casr

2024-04-26 10:16 UTC, ijon requested changes

2024-04-26 10:16 UTC, ijon commented on ydb/core/protos/flat_scheme_op.proto
> +    optional bool CheckGeneralVersion = 4 [default = true];
Я бы инвертировал флаг: `CheckTypeSpecificVersion` или `CheckEntityVersion` c default-значением false.
В понимании, что есть схемная сущность со своей версией (entity-version), а есть path, через которую эта сущность становится видима. Path и entity связаны, но не совпадают. У пути своя path-version, включающая entity-version. В общем случае работа с сущностями идёт в терминах путей, проверять надо path-version. И в базовой логике не должно быть никаких сомнений.

Для этого кажется лучше, чтобы флага "проверь общую (или path-version)" не было -- лучше иметь флаг "а сейчас не так как всегда, проверь специфику".

2024-05-24 09:08 UTC, ijon approved these changes

2024-05-24 12:18 UTC, merged