Support varying types in  LHS and RHS of IN operator
ydb-platform/ydb pull request #3828
Opened 2024-04-17 14:05 UTC by marsaly79

### Changelog entry 

IN operator with different types of LHS and items in RHS is supported.

### Changelog category 

* Improvement

### Additional information

...

2024-04-24 14:54 UTC, vitstn requested changes

2024-04-24 14:54 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
> +            .Callable("Fold")
нужно явно написать цепочку PgOr

2024-04-24 14:54 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
> +            .Callable("Fold")
или ToPg(Or(FromPg(pred1), FromPg(pred2)...))

2024-04-24 14:54 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
> +                elemsOfType.items.push_back(ctx.Expr.ShallowCopy(input->Head()));
ShallowCopy никогда не нужен

2024-04-24 14:54 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
>  IGraphTransformer::TStatus PgInWrapper(const TExprNode::TPtr& input, TExprNode::TPtr& output, TContext& ctx) {
Не нужен совсем PgInStrict 

lhs in (rhs1,rhs2,rhs3...)

1. если типы rhs разные то все приводится и распадается на Or-ы от PgIn при необходимости (если сразу нет общего типа)
2. если все типы равные то заканчиваем типизацию

в переписывании в SqlIn получаем SqlIn (AsList(rhs1,...),lhs)

2024-04-25 11:06 UTC, marsaly79 commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
> +            .Callable("Fold")
Чем плох вариант с Fold? Он всё равно развернётся в цепочку Or-ов

2024-04-25 11:07 UTC, marsaly79 commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
> +                elemsOfType.items.push_back(ctx.Expr.ShallowCopy(input->Head()));
Каков тогда канонический способ сделать копию экспрноды?

2024-04-25 11:12 UTC, marsaly79 commented on ydb/library/yql/core/type_ann/type_ann_pg.cpp
>  IGraphTransformer::TStatus PgInWrapper(const TExprNode::TPtr& input, TExprNode::TPtr& output, TContext& ctx) {
Если попытаться обойтись без PgInStrict, мы после развала на Or-ы будем снова типизировать PgIn и для каждого PgIn будем вызывать дорогой алгоритм вывода общего типа. Это пессимизация

2024-05-30 09:50 UTC, vitstn approved these changes

2024-05-30 10:49 UTC, merged