add draft backups interface
ydb-platform/ydb pull request #3873
Opened 2024-04-18 11:36 UTC by Enjection

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-04-22 19:20 UTC, CyberROFL commented on ydb/public/api/grpc/draft/ydb_backup_v1.proto
> +  rpc ListBackupCollections(ListBackupCollectionsRequest) returns (ListBackupCollectionsResponse) {}
Даже в драфте комментарии бы помогли. Чем fetch отличается от list?

2024-04-22 19:20 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    repeated string path = 1;
```suggestion
    repeated string paths = 1;
```

2024-04-22 19:20 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    repeated BackupCollection backup_collection = 2;
C операциями мы работаем не так: *Response возвращает _только_ объект операции, а все подробности в Operation.result и/или Operation.metadata.

2024-04-22 19:20 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    /*required*/ string uuid = 1;
Если поле required, то можно его аннотировать соответствующим тегом.

2024-04-23 10:54 UTC, CyberROFL requested changes

2024-04-23 10:54 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    repeated BackupCollection backup_collection = 1;
```suggestion
    repeated BackupCollection backup_collections = 1;
```

2024-04-23 10:54 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    repeated BackupCollection backup_collection = 1;
```suggestion
    repeated BackupCollection backup_collections = 1;
```

2024-04-23 10:54 UTC, CyberROFL commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    string description = 2;
Нужно лимитировать размер этого поля?

2024-04-23 10:55 UTC, Enjection commented on ydb/public/api/protos/draft/ydb_backup.proto
> +    string description = 2;
Пока не вижу смысла, когда api буду финализировать сделаю.

2024-04-23 10:57 UTC, CyberROFL approved these changes

2024-04-23 13:18 UTC, merged