Add StaticFold builtin to reduce over tuples and structs
ydb-platform/ydb pull request #3893
Opened 2024-04-18 14:17 UTC by avevad

### Changelog entry 

Add StaticFold builtin to reduce over tuples and structs

### Changelog category 

* New feature

### Additional information

...

2024-04-18 14:26 UTC, nepal requested changes, later dismissed

2024-04-18 14:26 UTC, nepal commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +        Functions["StaticFold"] = &StaticFoldWrapper<true>;
Это плохая практика делать функцию темплейтной. Они минимально различаются между собой. Ты просто таким образом раздуваешь код. Внутри функции есть возможность различить какую нону мы типизируем по input->Content()

2024-04-18 15:47 UTC, avevad commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +        Functions["StaticFold"] = &StaticFoldWrapper<true>;
справедливо, поправил

2024-04-18 17:42 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +    IGraphTransformer::TStatus StaticFoldWrapper(const TExprNode::TPtr& input, TExprNode::TPtr& output, TContext& ctx) {
need tests

2024-04-18 17:53 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +            result = input->ChildPtr(1);
это initialValue, а не result

2024-04-23 16:09 UTC, vitstn approved these changes

2024-04-23 18:54 UTC, merged