Get rid of unneccessary std::move
ydb-platform/ydb pull request #3901
Opened 2024-04-18 17:59 UTC by yumkam

Fixes #1246

XXX COMPLETELY UNTESTED XXX

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

WIP, not even compile-tested (out of resources); have not touched
```
Bar foo(..., Bar && res,...) {
....
    return std::move(res);
}
```

2024-05-07 06:40 UTC, uzhastik commented
Все же много лишних зачисток. Давайте внимательнее менять код, тем более, что его фиг оттестируешь

2024-05-07 06:40 UTC, uzhastik requested changes

2024-05-07 06:40 UTC, uzhastik commented on ydb/core/formats/arrow/program.cpp
> -        return std::move(datum);
А тут вроде нужен мув

2024-05-07 06:40 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_actor.h
> -        return std::move(result);
Тут нужен мув, тк тип переменной не совпадает с типом результата функции

2024-05-07 08:23 UTC, yumkam commented on ydb/core/formats/arrow/program.cpp
> -        return std::move(datum);
Всё, что делает `std::move` -- кастует к r-value. `datum` уже r-value.
Вообще, при возврате локальных переменных и параметров они всегда неявно кастуются к x-value, и либо попадают под NRVO, либо результат тот же, что и у `return std::move()`. Иначе NRVO нельзя было бы использовать (это опциональная оптимизация, если бы неявного каста не было бы -- при не-срабатывании получалась бы пессимизация).
(Важно не спутать с кейсами `return std::move(member)` или `return std::move(localVariable.foobar)` -- для них `std::move` нужен)
Feel free to correct.

2024-05-07 13:33 UTC, yumkam commented on ydb/core/fq/libs/control_plane_storage/request_actor.h
> -        return std::move(result);
См. выше. NRVO тут, конечно, не будет, так что уборка `std::move()` ничего не улучшает, но и не ухудшает: в любом случае локальная переменная неявно скастуется с x-value, и будет применён move-constructor для результирующего типа (`TBasicString(TBasicString &&)`).

2024-05-07 16:18 UTC, uzhastik commented on ydb/core/formats/arrow/program.cpp
> -        return std::move(datum);
datum не rvalue в выражении return datum. Чтобы мувнулся надо написать std::move, тк переменная не является автоматической

2024-05-07 16:20 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_actor.h
> -        return std::move(result);
Ты неправ. Std::move в данном случае гарантирует мув строки и не надо надеяться на необязательный nrvo

2024-05-07 17:47 UTC, yumkam commented on ydb/core/fq/libs/control_plane_storage/request_actor.h
> -        return std::move(result);
Проверил -- я был неправ (в обоих случаях) :-|
Thanks!

2024-06-13 04:35 UTC, k-morozov commented on ydb/core/formats/arrow/program.cpp
> -        return std::move(datum);
> А тут вроде нужен мув

Чтобы оптимизация сработала типы должны совпадать, а тут разные типы: arrow::Result<arrow::Datum> и arrow::Datum.

2025-01-18 21:21 UTC, closed without merging