Improve build time for YT provider
ydb-platform/ydb pull request #3930
Opened 2024-04-19 12:05 UTC by alephonea

yql_yt_physical_optimize.cpp took ~150s to compile, much longer than all other compilation units. 
Break it down into multiple compile units to compile them in parallel.

2024-04-26 14:37 UTC, resetius approved these changes, later dismissed

2024-04-26 14:53 UTC, rvu1024 requested changes

2024-04-26 14:53 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TCoLambda MakeJobLambda(TCoLambda lambda, bool useFlow, TExprContext& ctx) const
Почему это не в helper?
И это вполне можно убрать в cpp, сделав две специализации

2024-04-26 14:53 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybe<bool> CanFuseLambdas(const TCoLambda& innerLambda, const TCoLambda& outerLambda, TExprContext& ctx) const {
реализацию стоит унести в cpp

2024-04-26 14:53 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybeNode<TExprBase> LMap(TExprBase node, TExprContext& ctx) const {
реализацию стоит унести в yql_transform_map_reduce.cpp добавив две специализации шаблона

2024-04-26 14:53 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybeNode<TExprBase> Sort(TExprBase node, TExprContext& ctx) const {
Аналогично - реализацию унести в yql_transform_sort.cpp добавив две специализации шаблона

2024-05-13 23:28 UTC, alephonea commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybeNode<TExprBase> LMap(TExprBase node, TExprContext& ctx) const {
Перенес в yql_yt_transformer.cpp
Оставил шаблонную функцию без специализаций, поскольку она вызывается только из того же .cpp файла

2024-05-13 23:29 UTC, alephonea commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybeNode<TExprBase> Sort(TExprBase node, TExprContext& ctx) const {
Аналогично, перенес в yql_yt_transformer.cpp

2024-05-13 23:29 UTC, alephonea commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TMaybe<bool> CanFuseLambdas(const TCoLambda& innerLambda, const TCoLambda& outerLambda, TExprContext& ctx) const {
Done.

2024-05-13 23:30 UTC, alephonea commented on ydb/library/yql/providers/yt/provider/yql_yt_transformer.h
> +    TCoLambda MakeJobLambda(TCoLambda lambda, bool useFlow, TExprContext& ctx) const
Перенес в yql_yt_transformer_lambda.cpp две специализации.

2024-05-17 16:36 UTC, rvu1024 submitted a review, later dismissed

2024-05-24 11:01 UTC, rvu1024 approved these changes

2024-05-24 15:10 UTC, merged