Optimize Coalesce(Just(...) ...) on peephole final stage.
ydb-platform/ydb pull request #3957
Opened 2024-04-20 07:44 UTC by Tony-Romanov

2024-04-22 09:25 UTC, nepal requested changes

2024-04-22 09:25 UTC, nepal commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +    if (const auto& input = node->Head(); input.IsCallable("If") && input.ChildrenSize() == 3U &&
Тут тоже надо проверить что   в coalesce 2 чилда.
Проще в начале фции написать
if (node->ChildrenSize() != 2) return node;

2024-04-22 10:14 UTC, Tony-Romanov commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +    if (const auto& input = node->Head(); input.IsCallable("If") && input.ChildrenSize() == 3U &&
Не нужно.  Это в любм случае будет работать правильно даже если у Coalesce больше чилдов.

2024-04-23 17:37 UTC, nepal commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +    if (const auto& input = node->Head(); input.IsCallable("If") && input.ChildrenSize() == 3U &&
Да, точно

2024-04-23 17:37 UTC, nepal approved these changes

2024-04-23 17:37 UTC, merged