YQ-3116 Add restoring issues to query status
ydb-platform/ydb pull request #3977
Opened 2024-04-22 09:30 UTC by kardymonds

### Changelog entry 

...

### Changelog category 
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-04-23 06:41 UTC, dorooleg approved these changes, later dismissed

2024-04-26 12:24 UTC, UgnineSirdis requested changes

2024-04-26 12:24 UTC, UgnineSirdis commented on ydb/core/fq/libs/checkpointing/checkpoint_coordinator.cpp
> +        auto msg = TStringBuilder() << "Can't restore: " << statusName << ", " << record.GetIssues();
It is not good in common to have multiline string with issues in log. There is special logging method in TIssues, that is better to use here: https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/public/issue/yql_issue.h#L320

But these issues should be subissues in checkpoint coordinator error message and TEvDqFailure

2024-05-16 15:08 UTC, UgnineSirdis approved these changes

2024-05-17 05:56 UTC, merged