Add docs for StaticFold
ydb-platform/ydb pull request #4048
Opened 2024-04-23 15:34 UTC by avevad

### Changelog entry 

Add docs for StaticFold

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-04-23 21:46 UTC, nepal requested changes

2024-04-23 21:46 UTC, nepal commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +Статическая свертка структуры или кортежа.
Надо написать в каком порядке осуществляется свертка (т.е. что значит фраза "следующий элемент").
Если для тапла это более менее понятно, то для структуры - совсем не очевидно. У нас в документации написано, что структура - это набор именованный полей. Нигде не говорится как эти поля упорядочены.

2024-04-24 00:39 UTC, blinkov requested changes, later dismissed

2024-04-24 00:39 UTC, blinkov commented on ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +- `initLambda` - _(StaticFold1)_ lambda that produces initial fold state by first element
```suggestion
- `initVal` - _(for StaticFold)_ initial fold state
- `initLambda` - _(for StaticFold1)_ lambda that produces initial fold state from the first element
```

2024-04-24 00:39 UTC, blinkov commented on ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +`StaticFold1(<||>, $f0, $f)` is Null
```suggestion

`StaticFold1(<||>, $f0, $f)` returns `NULL`.
```

2024-04-24 00:39 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +`StaticFold1(<||>, $f0, $f)` вернет Null
```suggestion

`StaticFold1(<||>, $f0, $f)` вернет `NULL`.
```

2024-04-24 00:39 UTC, blinkov commented on ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +- `updateLambda` - lambda that produces the new state (arguments are the next element and the previous state)
```suggestion
- `updateLambda` - lambda that produces the new state (arguments are the next element and the previous state)
```

2024-04-24 07:39 UTC, avevad commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +Статическая свертка структуры или кортежа.
Кажется, мы не гарантируем никакой порядок, так и написать?

2024-04-24 08:07 UTC, avevad commented on ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/staticfold.md
> +Статическая свертка структуры или кортежа.
Дописал про гарантию порядка для кортежей и про ее отсутствие для структур.

2024-04-24 12:07 UTC, nepal approved these changes

2024-04-24 18:03 UTC, fomichev3000 approved these changes

2024-04-24 18:03 UTC, merged