YQ-2824: implement basis for type inference for CSV and TSV
ydb-platform/ydb pull request #4071
Opened 2024-04-24 12:25 UTC by EgorkaZ

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/s3_fetcher.cpp
> +        bool badHttp = result.Content.HttpResponseCode / 100 == 4 || result.Content.HttpResponseCode / 100 == 5;
добавь const, подели на 100 один раз, а не два

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    case arrow::Type::NA:
такой маппинг должен быть согласован с подобным маппингом в логике парсинга данных. допиши коммент об этом и дай ссылку на код. где такой маппинг прописан. в частности, хорошо бы поддержать pg типы, т.к. парсить мы их уже умеем

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    case arrow::Type::NA:
все кейсы в огромном switch надо покрыть тестами

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +        resType.set_type_id(Ydb::Type::INTERVAL);
в yql поддерживаются только фиксированные в микросекундах интервалы. месяцы - не фиксированы по времени

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    case arrow::Type::LIST: { // TODO: is ok?
у нас парсинг не поддерживает контейнеры. вывод типов тоже не должен поддерживать

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/ya.make
> +    library/cpp/lwtrace/protos
эта либа точно используется?

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/ut/ya.make
> +    ydb/core/tablet
лишние пирдиры. бери только те. что используются в исходнике с тестами

2024-05-03 11:18 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/ya.make
> +    ydb/library/yql/providers/s3/credentials
этот пирдир точно нужен? где-то есть прямой инклюд оттуда в текущую  либу?

2024-05-03 15:53 UTC, EgorkaZ commented on ydb/core/external_sources/object_storage/inference/ut/ya.make
> +    ydb/core/tablet
Пытался до этого, попытался снова - тяжело. Есть хедер `ydb/core/util/testactorsys.h`, и он для линковки за собой тянет `ydb/core/tablet` и `ydb/core/tx/scheme_board`. Если их добавить в `ydb/core/util/ya.make`, где он лежит, то случится цикл зависимостей. Не нашёл варианта лучше, чем притащить сюда. По-хорошему, наверное, надо как-то правильно перетащить `ydb/core/util/testactorsys.h`, но не в этом ПРе

2024-05-03 17:59 UTC, uzhastik commented on ydb/core/external_sources/object_storage/inference/ut/ya.make
> +    ydb/core/tablet
Если циклы мешают, то оставь так

2024-05-31 10:21 UTC, dorooleg requested changes

2024-05-31 10:21 UTC, dorooleg commented on ydb/public/lib/ydb_cli/commands/tpch.cpp
> +    TString partitioning = ", AUTO_PARTITIONING_MIN_PARTITIONS_COUNT";
Похоже это в другое ревью нужно вынести, наверное случайно сюда попало

2024-05-31 10:21 UTC, dorooleg commented on ydb/library/yql/providers/common/http_gateway/yql_http_default_retry_policy.h
> +#include <contrib/libs/curl/include/curl/curl.h>
А это у тебя локально выстрелило?

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        if (std::holds_alternative<NAuth::TAws>(meta->Auth)) {
А остальные auth где обрабатываются?

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        // <void(NThreading::TPromise<TResult>, TResponse&&)
А этот комментарий нужен еще?

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +            if (result.GetValue().Success()) {
result.GetValue() можно в отдельную переменную выделить и использовать ниже

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +            Cout << "Response successful" << Endl;
Cout тут лишний, в логи лучше писать если нужно

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        auto schemaToMetadata = [meta](NThreading::TPromise<TMetadataResult> metaPromise, NObjectStorage::TEvInferredFileSchema&& response) {
а почему ее в акторе не объявить? Или тут планируется потом расширение в это месте?

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage/events.h
> +    EvBegin, // TODO: where to start from?
эти эвенты локальные и приватные, можно в ES_PRIVATE

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        auto format = meta->Attributes.FindPtr("format");
Тут похоже еще сжатие не учитывается. Можно в отдельном ревью поддержать

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        return true;
Тут под фича флаг хотели это вынести. По умолчанию выключен

2024-05-31 10:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/ut/arrow_inference.cpp
> +#include <library/cpp/testing/gtest/gtest.h>
к таким файлам еще _ut дописывают обычно

2024-05-31 12:40 UTC, EgorkaZ commented on ydb/library/yql/providers/common/http_gateway/yql_http_default_retry_policy.h
> +#include <contrib/libs/curl/include/curl/curl.h>
Кажется, да. 

Вообще, вне contrib/ не вижу, чтобы ещё где-то было `<curl/curl.h>`

2024-06-03 16:41 UTC, EgorkaZ commented on ydb/core/external_sources/object_storage.cpp
> +        if (std::holds_alternative<NAuth::TAws>(meta->Auth)) {
Service account добавил. None обрабатывать не нужно, остальное не поддерживает eternal source

2024-06-05 16:26 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/design.md
> +# Inferencinator design
А точно это нужно, обычно такие документы на wiki храним или в отдельном разделе для design доков?

2024-06-06 12:39 UTC, dorooleg submitted a review, later dismissed

2024-06-07 09:01 UTC, dorooleg approved these changes

2024-06-07 13:04 UTC, merged