[configs] Add draft config controller tablet
ydb-platform/ydb pull request #4103
Opened 2024-04-25 11:03 UTC by Enjection

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-04-25 16:35 UTC, CyberROFL requested changes

2024-04-26 09:31 UTC, Enjection commented on ydb/core/tx/schemeshard/schemeshard__sync_update_tenants.cpp
> +        }
Сделаю отдельно, тут protobuf, без макроса или куска моего плагина удобно непереписать функцией.

2024-04-26 09:36 UTC, Enjection commented on ydb/core/protos/tablet.proto
> +        BackupControllerTablet = 42;
Потому что, вероятно, будет BackupControllerService на ноде + BCT имхо звучит лучше. У нас уже есть вещи по названию которых нельзя понять что это (e.g. Local) так что предпочту иметь суффикс Tablet.

2024-04-26 09:39 UTC, Enjection commented on ydb/core/backup/tablet_impl.h
> +    void OnDetach(const TActorContext& ctx) override {
В случае скелета таблетки не вижу проблемы, дальше с усложнением логики разделю.

2024-04-26 09:51 UTC, CyberROFL commented on ydb/core/protos/tablet.proto
> +        BackupControllerTablet = 42;
Положи в разные неймспейсы. Дублировать таблетку в названии таблетки не нужно.

2024-04-26 09:58 UTC, CyberROFL requested changes

2024-04-26 09:58 UTC, CyberROFL commented on ydb/core/backup/tx_init.h
Перенеси в .cpp

2024-04-26 10:07 UTC, CyberROFL requested changes

2024-04-26 10:07 UTC, CyberROFL commented on ydb/core/backup/tablet_impl.h
> +#include <ydb/core/tablet_flat/flat_cxx_database.h>
Можно сразу отсортировать как надо.

2024-04-26 10:22 UTC, CyberROFL commented on ydb/core/backup/tablet_impl.h
> +#include <ydb/core/tablet_flat/flat_cxx_database.h>
И не только в этом файле.

2024-04-26 11:06 UTC, CyberROFL commented
Подсвечу, что меня смущает/не нравится:
* Дублирование слова "таблетка" в названии таблетки.
* Код таблетки в .h файле.

Если это смущает только меня, то от меня ОК.

2024-04-26 12:19 UTC, snaury commented on ydb/core/backup/tablet.h
Возможно стоит таблетку положить в директорию `ydb/core/backup/controller`? Наверняка ещё чего-нибудь про бекапы захотим положить в `ydb/core/backup`.

2024-05-02 09:41 UTC, CyberROFL approved these changes

2024-05-02 10:05 UTC, merged