YQ-3000 fixed count for YT provider in KQP
ydb-platform/ydb pull request #4175
Opened 2024-04-27 10:37 UTC by GrigoriyPA

- Intermediate changes
- Automatic release build for flake8_linter
- Intermediate changes
- Delete unused code facb7e05dedadb100bf32110c1d404b3a71e1781
- Intermediate changes
- PR from branch users/denvr/YT-21293_fork_python3_only_source8
- Use AsciiEqualsIgnoreCase, remove bicycle 05bf28fe4eb31cec383104614cfd06d51d5c6a72
- added bufbuild 1.30.0 into vendor e3239236fb9352805620cbc09bf87fc3470b93bc
- Intermediate changes
- Allow skipping gofmt only in selected paths 3b605aec23b075e3524747f5c0c1e9ea65cb4040
- Disable pre-c++17 usage of std::unexpected() term c74a40a5f5d03e835ac33b3ae1f023c910694875
- Intermediate changes
- [yt/cpp/mapreduce] YT-21405: Don't ignore backoff and pass actual exception in Retry()
- Ya ide gradle integration with Arcadia plugin be1c0c90893924292d2dfd3dca3846f3ac35ad05
- Intermediate changes
- Pass exact versions to -Wl,-platform_version
- Use lld-link for target-platform windows ab842fb2190e76244be2cf4d1b0e266ef141a5a1
- Intermediate changes
- Set TJournalWriterOptions::EnableChunkPreallocation to true by default 15d1766a117f040cefaa3cc19a7384dbb4547787
- Update contrib/libs/nghttp2 to 1.61.0 c8173cbc05a2b3d63ed112bca0c19bfcd3fec2b1
- Intermediate changes
- Cosmetic for Cypress tx mirroring 1d447641f9f45024e30a81903e439513a3a8847f
- Intermediate changes
- Update contrib/restricted/boost/icl to 1.85.0 e3b51e8a149cffe12a67d165773110b46f10a354
- Use common and directory templates from generator toml, cut off constants with tempalte and result file names from generator
- Avoid passing columnPresenceBuffer around ed3889fb0e8fb71a059686f7c4133e9058935718
- New version of the tld SKIP_CHECK SKIP_REVIEW ba564ebebc1f8959e21428666934e394db040489
- Update contrib/restricted/boost/algorithm to 1.85.0 35d23344de6c4673b906b88a4875c021daf0e664
- Remove ya:nofuse from build/; devtools/ya/ and sandbox/projects/devtools/YaTestParent2/ 497515ebe29440247c5e801fc33d8bce80f2f3ff
- yolint: enable riskyimports with config
- Intermediate changes
- Update contrib/libs/opentelemetry-proto to 1.2.0 4fbfc3522cdaab1bcd214af84464870e6dd59977
- Enable MarkAsIntentionallyLeaked API for --sanitize=leak builds f660faa016f3549719f718b14125e02327fc02b2
- Intermediate changes
- Update contrib/restricted/boost/endian to 1.85.0 a17658872904373716627897dd61354cee0dcf0b
- Update contrib/restricted/boost/crc to 1.85.0 2f34ef14ba79b52dc615c096f767bc5ae0308249
- Update contrib/restricted/boost/functional to 1.85.0 e70a691d7a4e0843a341010c6df20fa088abad9d
- Update contrib/restricted/boost/iostreams to 1.85.0 69e328573266391c3c49f7c846e9169e6203f681
- Update contrib/restricted/boost/ratio to 1.85.0 2c13f07c2528cdc127f9bcd3c5c1c0e5ee13644a
- Update contrib/restricted/boost/typeof to 1.85.0 fe39fbfe7e2d39b2557ffef9a05d56f5c0a6f9dc
- Intermediate changes
- Update contrib/restricted/boost/thread to 1.85.0 4c8e7963135e7effd7784baaef98aa62c6ca3d11
- Update contrib/restricted/boost/predef to 1.85.0 2352d4d6f47f4e5c37ea86cbbc069abde03b2911
- Intermediate changes
- Update contrib/restricted/boost/multi_index to 1.85.0 bbc7e1131217978f68ebbefbf9f15772e51d1963
- Update contrib/restricted/boost/io to 1.85.0 45e0ee910375f92d754e6c8e7ee12274de632fcd
- Update contrib/restricted/boost/mpl to 1.85.0 f41f7e5d6e8eec827e0d5096fe10ae1f18608527
- Update contrib/restricted/boost/winapi to 1.85.0 26e9dff2b2495390abae72c58c4c1d548b201fdb
- Update contrib/restricted/boost/optional to 1.85.0 ad0271ad14d7bfe0134ee848ca5eaa9b25903e1a
- Fix portions cleaning (#3959)
- correction (#3958)
- Update contrib/restricted/boost/phoenix to 1.85.0 666db8600f94a11c0fa790ae1dfd05cd03fc5ed2
- Update contrib/restricted/boost/tuple to 1.85.0 4ee2c9823fc593167c5775be9a7b05be1869ad50
- Update contrib/restricted/boost/lambda to 1.85.0 395fb0ed7854c06cc720a78bf19cdf9269253c70
- YT-21382: Implement ISequoiaService & ISequoiaServiceContext 9303c9ef0d39f044b047781a42505e79ba4ccbb9
- Move concepts to library/cpp/yt/misc/concepts.h
- [build] Describe licenses in json format 040cc25185d4b7df1610e13db8b9fceb5164a070
- YT-21446: Introduce YQL_PYTHON3_UDF_YDB/CONTRIB ya make module b6f2fcb46dac071094c114405249cc661b268876
- YT-21446: Support py udfs generator is os ydb ab1a950f25a9a5f4a9ca38655f443ff23cece827
- Automatic release build for ymake, os_ymake
- feat(conf): support prebuilder v1 in conf validation (with fallback to v0 logic)
- YDBDOCS-633: continue restructuring (#3919)
- incapsulate sharding logic into special class and remove declaration … (#3964)
- Canonize new SSA runtime version. (#3965)
- Immediate transactions (#3940)
- Better snapshot handling in datashard uncommitted writes (#3826)
- YQ-2068 init InputTransformLookup in YQ (#3954)
- Optimized and MapJoin friendly Q3 (#3951)
- Optimized and MapJoin friendly Q16 (#3962)
- Optimized and MapJoin friendly Q2 (#3950)
- get_metering(): added async support (v2) (#3856)
- YQL-18053: Add block implementation for AsStruct callable (#3485)
- [YQL-15502] Avoid rewriting lazy functions (like If) to blocks if arguments can fail in runtime (#3967)
- Intermediate changes
- HOTFIX copy-paste error in configuration 71fdf13925af658c2bb0b7a7945d54c6e17963d7
- Refactor acceptance_run.yml (use actions directly) (#3942)
- Fix developer documentation (#3836)
- layout construction optimization (#3956)
- [YQ-2738] Do not canonize results (#3982)
- Remove JDK 18 support from Arcadia Tier 0, remove build configuration for JDK 0e989a0fc3519d203e2dbc837a772d2d99808f0b
- Backport a patch to remove sprintf() usage 46445dce23a4a183768eb9318a35baf7a6b3d6ed
- Validate ASYNC REPLICATION settings (#3973)
- YT-18571: Lambda cosmetics 3662fc28ab119b78f1a21d2ee71854328771718c
- [docs] update favicon (#3991)
- [YQL-15502] Recanonize after pr #3485 (#3994)
- QPlayer storage interfaces & in-memory implementation (#3993)
- YQL-18225: Fix sorted output when rewritting reduce in hybrid (#3971)
- Replace remaining bad usages of AsciiCompareIgnoreCase 231a9b4db35ccee7e5a5b716b57d594973adc23b
- [YQL-18194] Prepare to limit builders memory consumption in WideToBlocks (#3996)
- Improve BlobDepot monitoring (#3978)
- Use Y_DEBUG_ABORT macros (#3684)
- Fix possible nullptr deref (#4000)
- {CREATE,ALTER,DROP} ASYNC REPLICATION impl (#3904)
- Increment YDB CLI version to 2.9.0 (#3980)
- Revert commit rXXXXXX, Use lld-link for target-platform windows, fix arc native build 0bd1ab2bb753fb9458cc5f295e94e24cf1115055
- YQL-18277: fix use after move (#4001)
- Move licenses.json into place copied by piglet 54e8cbe2294393e17a54b6485d0f854a254b6c7a
- Change back package name in operation.proto to fix import (#3983)
- Remove recurses to proto libraries to avoid compilation for every possible language (#3949)
- Update github.com/ydb-platform/fq-connector-go to v0.2.20 (#3988)
- Fix accidental recursive dependency (#3974)
- YT-20113: Address review comments. 38fc0bceba87529d2732c38a0904c0ba39c0381a
- Remove final in cpp pb.h/cc by outputs list
- Replace more bad usages of AsciiCompareIgnoreCase
- Move NO_UNIQUE_ADDRESS macro to library/cpp/yt/misc/port.h 8b95cb159efca3d611ef0361a6f53a20b2fb5b37
- Allow to specify directories in CREATE ASYNC REPLICATION (#4011)
- Intermediate changes
- Initial implementation of facade qplayer tests (#4005)
- EvWrite Sink buffer for DataShard (#3966)
- Update contrib/restricted/boost/core to 1.85.0 1bb2acda6377c988e483392dfbb76ef5b0a6adec
- Import libraries 240423-0906
- Fix win build (#4018)
- Refactor utcnow usage in dstool (#4021)
- Topic API changes for split merge (version 2) (#1502)
- Fix serialization of decimal inf/nan in yson format (#4007)
- Introduce helper to make block or scalar type (#3797)
- Fixed YDB hostname in FQ Generic tests (#4033)
- YQ-3129: disable connections in modified queries (#4023)
- YQL-18140 add None check to ResultFormatter (#3845)
- add draft backups interface (#3873)
- Update ydb_query_v1.proto (#3911)
- YQ-2068 input transforms may not implement checkpoints (#3999)
- improve topic docs (#3315)
- YDBDOCS-633: continue restructuring (#4036)
- Introduce basic s [...]

2024-05-02 09:54 UTC, uzhastik commented on ydb/tests/tools/kqprun/src/kqp_runner.cpp
> +                    Cerr << CerrColors_.Red() << "Failed to convert query result rows to JSON, reason:\n" <<  CurrentExceptionMessage() << "\nTry to use --result-format full-proto" << CerrColors_.Def
не проще ли выбросить исключение вместо пробрасывания bool результата?

2024-05-03 10:05 UTC, gridnevvvit commented on ydb/core/kqp/common/kqp_yql.h
> +#include <ydb/library/yql/dq/integration/yql_dq_integration.h>
forward declaration must be used here, i guess.

2024-05-03 10:24 UTC, rvu1024 commented on ydb/core/kqp/common/kqp_yql.cpp
> +std::unordered_set<IDqIntegration*> GetUniqueIntegrations(TTypeAnnotationContext& typesCtx) {
Стоит вынести в yql/providers/common или в yql/dq, потому что аналогичный код есть в DQ провайдере

2024-05-03 10:24 UTC, rvu1024 commented on ydb/core/kqp/host/kqp_runner.cpp
> +
Нет второй части для `ConfigurePeepholePipeline(false, ...)`. Потом опять править?

2024-05-03 10:24 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +        }
Зачем кидать exception? Можно просто по флагу добавлять Error вместо Info. В методе IsDqRead проверять, что CanRead() вернул false - это будет аналогично отлову exception

2024-05-04 08:11 UTC, GrigoriyPA commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +        }
В функции IsDqRead надо как-то отделить ситуации когда CanRead возвращает false из-за того что вызвана от ноды из которой нельзя читать и когда CanRead возвращает false из-за неправильных настроек в ноде TYtReadNode, во втором случае надо остановить оптимизацию, иначе запрос завершится с ошибкой INTERNAL_ERROR и issues:
`<main>: Fatal: ydb/library/yql/providers/yt/provider/yql_yt_datasource_exec.cpp:81  HandleResOrPull(): requirement fillSettings.Format == IDataProvider::EResultFormat::Yson || fillSettings.Format == IDataProvider::EResultFormat::Skiff failed, code: 1`

По этому добавил проброс exception

2024-05-13 10:08 UTC, rvu1024 requested changes

2024-05-13 10:08 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                std::string_view message = DqFallbackErrorMessageWrap("too big table with erasure codec");
здесь обращение к уже разрушенной строке

2024-05-13 10:26 UTC, rvu1024 submitted a review, later dismissed

2024-05-13 21:48 UTC, gridnevvvit submitted a review, later dismissed

2024-05-15 07:45 UTC, uzhastik approved these changes

2024-05-15 08:54 UTC, rvu1024 approved these changes

2024-05-15 08:56 UTC, merged