Add type white-list for supported types on blockreader
ydb-platform/ydb pull request #4268
Opened 2024-05-03 09:25 UTC by MrLolthe1st

2024-05-03 09:55 UTC, rvu1024 requested changes

2024-05-03 09:55 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +                supported.emplace(ETypeAnnotationKind::Tuple);
`EDataSlot GetDataSlot(TStringBuf str)`

2024-05-03 09:55 UTC, rvu1024 commented on ydb/library/yql/providers/yt/common/yql_yt_settings.h
> +    NCommon::TConfSetting<TSet<TString>, true> BlockReaderSupportedTypes;
Я бы разделил на две прагмы - одна для типов и вторая для слотов data-типа. Тогда проще парсер написать для прагмы сразу в нужных энумах, а не строках. Для `yql_expr_types.h` стоит тогда еще добавить генерацию сроковых преобразований через GENERATE_ENUM_SERIALIZATION

2024-05-03 09:55 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +        }
В текущем виде любое расширение типов потребует изменять еще и код. Какой смысл тогда в прагме? Нужно уже написать универсальную функцию с поддержкой любых типов

2024-05-07 15:55 UTC, vitstn commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +            BlockReaderAddInfo(ctx.GetPosition(node.Pos()), "arrow resolver don't support these types");
а где здесь типы в ошибке?

2024-05-08 06:34 UTC, MrLolthe1st commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
> +            BlockReaderAddInfo(ctx.GetPosition(node.Pos()), "arrow resolver don't support these types");
Он не возвращает на чем споткнулся

2024-05-24 10:26 UTC, rvu1024 approved these changes

2024-05-24 12:20 UTC, merged