YQ-2824: add basis for type inference in KQP metadata loader
ydb-platform/ydb pull request #4273
Opened 2024-05-03 10:34 UTC by EgorkaZ

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-03 11:28 UTC, uzhastik commented on ydb/core/kqp/gateway/kqp_metadata_loader.cpp
> +                            promise.SetValue(std::move(externalTableMetadata));
сюда не надо передать newMetadata ?

2024-05-03 11:28 UTC, uzhastik commented on ydb/core/kqp/provider/yql_kikimr_datasource.cpp
> +    } else if (node.IsCallable()) {
избыточный else

2024-05-03 11:28 UTC, uzhastik commented on ydb/core/kqp/provider/yql_kikimr_gateway.h
> +        NKikimr::NExternalSource::IExternalSourceFactory::TPtr ExternalSourceFactory = nullptr;
инициализация избыточна. у объекта же есть конструктор

2024-05-03 11:28 UTC, uzhastik commented on ydb/library/yql/providers/s3/provider/yql_s3_datasource_type_ann.cpp
> +                if (name == "infer") {
по аналогии с параметрами выше дописал бы sv

2024-05-24 08:23 UTC, dorooleg requested changes

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/kqp/provider/yql_kikimr_datasource.cpp
> +class IAstAttributesVisitor {
Давай тесты сделаем на визиторы и Gathering. Их можно как отдельные ut оформить

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/kqp/gateway/kqp_metadata_loader.cpp
> +NExternalSource::TAuth MakeAuth(const NYql::TExternalSource& metadata) {
Для этих тоже ребят бы тесты сделать: MakeAuth, ConvertToExternalSourceMetadata, EnrichMetadata

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/kqp/provider/yql_kikimr_datasource.cpp
> +        auto readAttributes = GatherReadAttributes(*input, ctx);
Давай не делать gather если нету source с external data source is dynamic load. Чтобы overhead не добавлять

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +#include <ydb/core/kqp/gateway/actors/kqp_ic_gateway_actors.h>
Предлагаю изменения в object_storage.cpp/object_storage.h вынести в отдельное ревью где будет добавляться вывод схему. Доброс actor system в external source factory можно в этом ревью оставить

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/tx/schemeshard/schemeshard_impl.cpp
>              std::vector<TString>(hostnamePatterns.begin(), hostnamePatterns.end()),
Еще во viewer не хватает nullptr: https://a.yandex-team.ru/arcadia/contrib/ydb/core/viewer/json_describe.h?rev=14081345#L293

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/external_sources/external_data_source.cpp
> +    virtual NThreading::TFuture<std::shared_ptr<TMetadata>> LoadDynamicMetadata(std::shared_ptr<TMetadata> meta) override {
А точно этот TMetadata нужно шарить? unique_ptr не подойдет или он где-то проблемы создает?

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/external_sources/external_source.h
> +    TString Type;
Давай SourceType назовем по аналогии с KikimrMetadata

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/kqp/gateway/kqp_metadata_loader.cpp
> +    tableMetadata.Attributes = dynamicMetadata.Attributes;
а SourceType и Location где будут заполняться?

2024-05-24 08:23 UTC, dorooleg commented on ydb/core/kqp/gateway/kqp_metadata_loader.cpp
> +                                        if (result.HasValue() && (!result.GetValue()->Changed || EnrichMetadata(*externalDataSourceMetadata.Metadata, *result.GetValue()))) {
GetValue ... нужно завернуть в try catch и проставить текст ошибки из LoadDynamicMetadata

2024-05-24 11:57 UTC, EgorkaZ commented on ydb/core/external_sources/external_source.h
> +    TString Type;
Оно мимикрирует как раз под поле `Type`

2024-05-24 15:36 UTC, EgorkaZ commented on ydb/core/tx/schemeshard/schemeshard_impl.cpp
>              std::vector<TString>(hostnamePatterns.begin(), hostnamePatterns.end()),
(Наверное, не надо ссылку светить)
Там `nullptr` в аргументах по умолчанию. Явно нужно прописывать, если указан следующий аргумент

2024-05-27 12:26 UTC, EgorkaZ commented on ydb/core/external_sources/external_data_source.cpp
> +    virtual NThreading::TFuture<std::shared_ptr<TMetadata>> LoadDynamicMetadata(std::shared_ptr<TMetadata> meta) override {
Мы тут `TFuture` отдаём. НЯПП всякие `Apply`/`Subscribe` принимают `const&` (и они есть в имплементации для object_storage). Из этого мувать проблемно. Если принципиально `unique_ptr`, можно обложиться `const_cast`'ами

2024-05-28 06:26 UTC, uzhastik commented on ydb/core/external_sources/external_data_source.cpp
> +    virtual NThreading::TFuture<std::shared_ptr<TMetadata>> LoadDynamicMetadata(std::shared_ptr<TMetadata> meta) override {
Давайте без const_cast ;)

2024-05-30 07:45 UTC, dorooleg approved these changes

2024-05-30 07:48 UTC, merged