Block channels flag
ydb-platform/ydb pull request #4321
Opened 2024-05-06 12:28 UTC by nikvas0

### Changelog entry 

Add flag for Block channels

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-06 17:26 UTC, nepal requested changes

2024-05-06 17:26 UTC, nepal commented on ydb/library/yql/dq/type_ann/dq_type_ann.h
> +    TDqStageSettings& SetScalarChanels() { WideChannels = false; OutputNarrowType = nullptr; BlockStatus = EBlockStatus::None; return *this; }
Зачем нужна эта функция?
Широкость и блочность каналов включается независимо.

2024-05-07 09:27 UTC, nikvas0 commented on ydb/library/yql/dq/type_ann/dq_type_ann.h
> +    TDqStageSettings& SetScalarChanels() { WideChannels = false; OutputNarrowType = nullptr; BlockStatus = EBlockStatus::None; return *this; }
Убрал функцию, перенес выставление нужных параметров в сборку транзакций ydb.
Зачем это нужно: прямо сейчас ydb не умеет в финальной выдаче результата работать с чем-то, кроме скалярных данных (wide или block каналы там приведут к ошибке), поэтому в качестве временного решения для форсированных блочных вычислений мы добавляем в конец стадию, где происходит конвертация в скаляры.

2024-05-07 12:25 UTC, nepal approved these changes

2024-05-07 12:26 UTC, merged