YQL-16355: Improve timeout settting for literal requests
ydb-platform/ydb pull request #4347
Opened 2024-05-07 09:52 UTC by mxkovalev

2024-05-08 16:33 UTC, rvu1024 requested changes

2024-05-08 16:33 UTC, rvu1024 commented on ydb/library/yql/providers/dq/actors/executer_actor.cpp
> +        Timeout = TDuration::MilliSeconds(ExecutionTimeout > 0 ? ExecutionTimeout : TDqSettings::TDefault::TableTimeout);
Давай сразу в конструкторе проинициализируем `Timeout`. Он теперь не зависит ни от каких динамических значений. `ExecutionTimeout` тогда лишний

2024-05-08 16:33 UTC, rvu1024 commented on ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
> +        State->ExecutionTimeout = State->Settings->_LiteralTimeout.Get().GetOrElse(TDqSettings::TDefault::LiteralTimeout);
Это не должно храниться в стейте. Это локальное значение конкретного запроса. Стейт может одновременно использоваться в нескольких параллельных запросах

2024-05-13 12:59 UTC, mxkovalev commented on ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
> +        State->ExecutionTimeout = State->Settings->_LiteralTimeout.Get().GetOrElse(TDqSettings::TDefault::LiteralTimeout);
поправил

2024-05-20 11:16 UTC, mxkovalev commented on ydb/library/yql/providers/dq/actors/executer_actor.cpp
> +        Timeout = TDuration::MilliSeconds(ExecutionTimeout > 0 ? ExecutionTimeout : TDqSettings::TDefault::TableTimeout);
Перенес  в список инициализации

2024-05-23 08:22 UTC, rvu1024 approved these changes

2024-05-23 10:45 UTC, uzhastik approved these changes

2024-05-23 10:45 UTC, merged