[docs]: YDBDOCS-165 - describe ydb tools restore --import-data
ydb-platform/ydb pull request #436
Opened 2023-11-14 06:17 UTC by blinkov

2023-11-17 13:18 UTC, capcom6 commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с расслабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
Не корректней ли будет вместо "расслабленными" использовать "ослабленными"?

2023-11-23 01:04 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с расслабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
```suggestion
`--import-data`: более эффективный способ загрузки данных с ослабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
```

2024-03-23 20:06 UTC, fomichev3000 requested changes

2024-03-23 20:06 UTC, fomichev3000 commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с ослабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
Что означает "ослабленные"? Я бы пояснил. Просто не построятся вторичные индексы? Т.е. загрузятся только оригинальные таблицы?

2024-03-25 02:46 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с ослабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
насколько я понял/помню там просто за сценой не одна большая транзакция, а данные прозрачно мелко режутся на много транзакций и, как следствие, можно оказаться в промежуточном состоянии, @CyberROFL — можешь уточнить?

2024-04-22 11:30 UTC, CyberROFL commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с ослабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
Фраза про "ослабленные" появилась в help-е из (уже устаревшей) опции `--bulk-upsert`. ImportData (как и BulkUpsert) в сравнении с YQL работают с ослабленными гарантиями. Но возможно для восстановления из резервной копии это вообще неважно и можно об этом не упоминать.

2024-04-22 11:34 UTC, CyberROFL commented on ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
> +`--import-data`: более эффективный способ загрузки данных с ослабленными гарантиями консистентности. В данном режиме не поддерживаются глобальные вторичные индексы.
> В данном режиме не поддерживаются глобальные вторичные индексы.

Эту фразу можно понять как "опция несовместима с `--restore-indexes`", но это не так.

2024-10-24 02:15 UTC, closed without merging