Refactoring to perform cardinality estimation specifically for YT.
ydb-platform/ydb pull request #4482
Opened 2024-05-13 22:24 UTC by alephonea

Reviewed in 
https://github.com/ydb-platform/ydb/pull/3866

but accidentally closed that PR - reopening.

2024-05-14 11:55 UTC, pavelvelikhov submitted a review, later dismissed

2024-05-15 15:49 UTC, rvu1024 requested changes

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/yql_statistics.h
> +    TOptimizerStatistics(EStatisticsType type, double nrows, int ncols, double byteSize, double cost, const TVector<TString>& keyColumns, IProviderStatistics* specific)
Почему нельзя все сделать одним конструктором с дефолтными значениями аргументов?

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.h
> +    StreamLookupJoin //Right part can be updated during an operation. Used mainly for joining streams with lookup tables. Currently impplemented in Dq by LookupInputTransform
Здесь перечислены только DQ-специфичные алгоритмы. В YT провайдере есть другие реализации. Что с ними предполагается делать? Как будет расширяться этот enum?

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.h
>          AttributeName(attributeName) {}
std::move()

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.cpp
> +TString ConvertToJoinAlgoString(EJoinAlgoType joinAlgo) {
Используй GENERATE_ENUM_SERIALIZATION в ya.make

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/cbo/cbo_optimizer_new.h
> +    static const TBaseProviderContext& instance();
Style: Instance

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
> +    if (stats.KeyColumns.size()==0) {
Style: пробелы вокруг ==

2024-05-15 15:49 UTC, rvu1024 commented on ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
> +    for(size_t i=0; i<stats.KeyColumns.size(); i++){
Style: пробелы вокруг =, < и ()

2024-05-15 21:25 UTC, alephonea commented on ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
> +    for(size_t i=0; i<stats.KeyColumns.size(); i++){
Done

2024-05-15 21:31 UTC, alephonea commented on ydb/library/yql/core/yql_cost_function.cpp
> +TString ConvertToJoinAlgoString(EJoinAlgoType joinAlgo) {
Эта функция используется для вывода в std::stringstream (как и ConvertToJoinString) который не поддерживается GENERATE_ENUM_SERIALIZATION

2024-05-15 21:32 UTC, alephonea commented on ydb/library/yql/core/yql_cost_function.h
>          AttributeName(attributeName) {}
Done

2024-05-15 21:53 UTC, alephonea commented on ydb/library/yql/core/yql_statistics.h
> +    TOptimizerStatistics(EStatisticsType type, double nrows, int ncols, double byteSize, double cost, const TVector<TString>& keyColumns, IProviderStatistics* specific)
Done

2024-05-15 21:55 UTC, alephonea commented on ydb/library/yql/core/yql_cost_function.h
> +    StreamLookupJoin //Right part can be updated during an operation. Used mainly for joining streams with lookup tables. Currently impplemented in Dq by LookupInputTransform
Предполагается что enum будет общим для DQ и YT. Если YT понадобится алгоритм джойна, который здесь не перечислен, то для DQ IsJoinApplicable() должен вернуть false для этого алгоритма.

Сейчас YT делает либо Map join, либо merge join (GraceJoin в этом енуме).

2024-05-15 21:55 UTC, alephonea commented on ydb/library/yql/core/cbo/cbo_optimizer_new.h
> +    static const TBaseProviderContext& instance();
Done.

2024-05-17 16:46 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.cpp
> +TString ConvertToJoinAlgoString(EJoinAlgoType joinAlgo) {
Не понял про поддержку. Ты будешь просто писать ToString(joinAlgo) вместо ConvertToJoinAlgoString(joinAlgo). И ToString() тебе сгенерит GENERATE_ENUM_SERIALIZATION, а не руками перечислять все константы

2024-05-17 16:48 UTC, rvu1024 commented on ydb/library/yql/core/yql_cost_function.h
> +    StreamLookupJoin //Right part can be updated during an operation. Used mainly for joining streams with lookup tables. Currently impplemented in Dq by LookupInputTransform
GraceJoin больше соответствует Common стратегии. Не понятно, как тут различать merge и common

2024-05-21 21:56 UTC, alephonea commented on ydb/library/yql/core/yql_cost_function.cpp
> +TString ConvertToJoinAlgoString(EJoinAlgoType joinAlgo) {
OK, done.

2024-05-21 22:03 UTC, alephonea commented on ydb/library/yql/core/yql_cost_function.h
> +    StreamLookupJoin //Right part can be updated during an operation. Used mainly for joining streams with lookup tables. Currently impplemented in Dq by LookupInputTransform
Добавил MergeJoin

В качестве альтернативы, можно привязать алгоритмы все джойна к системе, в которой они выполняются:

 DqLookupJoin,
 DqMapJoin,
 ..
 YtMapJoin,
 YtMergeJoin

чтобы было понятно из значения enum-а как конкретно он будет исполняться. Но мне кажется, это излишнее усложнение.

2024-05-24 11:08 UTC, rvu1024 approved these changes

2024-05-24 15:49 UTC, uzhastik approved these changes

2024-05-24 18:41 UTC, merged