YDBDOCS-188 FluentBit - not just K8s
ydb-platform/ydb pull request #4635
Opened 2024-05-17 08:46 UTC by zinal

### Changelog entry 

FluentBit support documentation extended to cover non-Kubernetes setup

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-05-17 15:11 UTC, blinkov requested changes, later dismissed

2024-05-17 15:11 UTC, blinkov commented on ydb/docs/en/core/integrations/fluent-bit.md
> +To remove FluentBit it is sufficient to delete the Kubernetes namespace which was used for the installation:
```suggestion
To remove FluentBit, it is sufficient to delete the Kubernetes namespace which was used for the installation:
```

2024-05-17 15:11 UTC, blinkov commented on ydb/docs/en/core/integrations/fluent-bit.md
> +After uninstalling FluentBit, log storage table can be dropped from the {{ ydb-short-name }} database:
```suggestion
After uninstalling FluentBit, the log storage table can be dropped from the {{ ydb-short-name }} database:
```

2024-05-18 10:30 UTC, zinal commented on ydb/docs/en/core/integrations/fluent-bit.md
> +         `timestamp`, `hostname`, `input`, `datahash`
Да, спасибо, что заметил. Вношу соответствующие исправления.

2024-05-18 10:32 UTC, zinal commented on ydb/docs/en/core/integrations/fluent-bit.md
> +It is necessary to replace the repository and image version of the FluentBit container:
Добавляю фразу "See below the example content for the FluentBit deployment configuration file."

2024-05-18 10:41 UTC, zinal commented on ydb/docs/en/core/integrations/fluent-bit.md
> +* `kubernetes` – information about the pod, for example: name, namespace, logs and annotations.
Чуть переписал, надеюсь, что станет более понятно

2024-05-18 10:45 UTC, zinal commented on ydb/docs/en/core/integrations/fluent-bit.md
> +{{ ydb-short-name }} tables must have primary key, which uniquely identifies the specific row in the table. Timestamp does not always uniquely identify the message coming from the particular source.
Кажется, в данном конкретном случае это не важно - требуется сделать близкой к нулю вероятность коллизий записей с одной меткой времени, пересчет хеш-кода (и его последующее использование как данных) тут не требуется

2024-05-24 07:09 UTC, fomichev3000 approved these changes

2024-05-24 07:09 UTC, merged