Add check for type serializability for spilling to Sort compute nodes
ydb-platform/ydb pull request #4636
Opened 2024-05-17 08:52 UTC by Darych

### Changelog entry 

Add check for type serializability for spilling to Sort compute nodes

### Changelog category 

* Bugfix 

### Additional information

...

2024-05-17 08:54 UTC, lll-phill-lll approved these changes

2024-05-23 12:56 UTC, nepal requested changes

2024-05-23 12:56 UTC, nepal commented on ydb/library/yql/minikql/mkql_node.h
> +        return ! (IsResource() || IsType() || IsStream() || IsCallable()
Тут нужен switch чтобы при расширении типов оно не компилилось

2024-05-23 12:56 UTC, nepal commented on ydb/library/yql/minikql/mkql_node.h
> +        return ! (IsResource() || IsType() || IsStream() || IsCallable()
И что должно на блочных типов происходить?

2024-05-23 12:57 UTC, nepal commented on ydb/library/yql/minikql/mkql_node.h
> +        return ! (IsResource() || IsType() || IsStream() || IsCallable()
Эта функция должна быть рекурсивной

2024-05-27 18:15 UTC, closed without merging