Convert OWNER to SUBSCRIBER in ya.make
ydb-platform/ydb pull request #4742
Opened 2024-05-22 08:59 UTC by thevery

### Changelog entry
Convert deprecated OWNER to SUBSCRIBER in ya.make

### Changelog category
* Not for changelog (changelog entry is not required)

2024-05-23 15:39 UTC, uzhastik approved these changes, later dismissed

2024-05-23 15:55 UTC, vitstn requested changes

2024-05-23 15:55 UTC, vitstn commented on ydb/tests/olap/scenario/helpers/ya.make
> -    SUBSCRIBER(iddqd)
а что с SUBSCRIBER ?

2024-05-23 16:41 UTC, uzhastik commented on ydb/tests/olap/scenario/helpers/ya.make
> -    SUBSCRIBER(iddqd)
да то же самое, это же синоним для OWNER

2024-05-24 09:06 UTC, thevery commented on ydb/tests/olap/scenario/helpers/ya.make
> -    SUBSCRIBER(iddqd)
для гитхаба ни OWNER, ни SUBSCRIBER никакого явного смысла не имеют

2024-05-24 18:15 UTC, uzhastik approved these changes

2024-05-27 10:26 UTC, vitstn approved these changes

2024-05-27 10:33 UTC, alexnick88 approved these changes

2024-05-27 10:53 UTC, merged