[cms.proto] increase default DisabledNodesRatioLimit
ydb-platform/ydb pull request #4770
Opened 2024-05-23 08:58 UTC by blinkov

With the current limit it is not possible to properly restart a minimal 8 or 9 nodes cluster as taking out even one node will lead to more than 10% of the cluster being down.

Example error:
```
May 23 08:46:16 static-node-3 ydbd[5559]: 2024-05-23T08:46:16.186419Z :CMS NOTICE: [AuditLog] [CMS tablet] Reply: request# NKikimr::NCms::TEvCms::TEvCheckRequest { User: "root" RequestId: "root-r-1" AvailabilityMode: MODE_MAX_AVAILABILITY }, response# NKikimr::NCms::TEvCms::TEvPermissionResponse { Status { Code: DISALLOW_TEMP Reason: "Cannot lock node \'5\' of tenant \'/Root\': too many unavailable nodes. Locked: 1, down: 0, total: 9, limit: 10%" } RequestId: "root-r-1" Deadline: 1716454276175013 }
```

### Changelog category 

* Not for changelog (changelog entry is not required)

2024-05-23 09:03 UTC, CyberROFL submitted a review, later dismissed

2024-05-23 10:39 UTC, pixcc requested changes
Надо еще поапдейтить доку

https://ydb.tech/docs/ru/devops/manual/maintenance-without-downtime#unavailable-node-limits

https://ydb.tech/docs/en/devops/manual/maintenance-without-downtime#unavailable-node-limits

2024-05-24 02:36 UTC, blinkov commented
@pixcc done

2024-05-24 06:19 UTC, pixcc approved these changes

2024-05-24 07:10 UTC, fomichev3000 approved these changes

2024-05-24 07:10 UTC, merged