YDB FQ: docs for YDB as an external datasource
ydb-platform/ydb pull request #4790
Opened 2024-05-23 15:32 UTC by vitalyisaev2

### Changelog entry 

* Docs for YDB as an external datasource for YDB FQ

### Changelog category 

* Documentation (changelog entry is not required)

2024-05-23 15:50 UTC, blinkov requested changes

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +# Работа с базами данных YDB
```suggestion
# Работа с базами данных {{ ydb-short-name }}
```

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [секрет](../datamodel/secrets.md), содержащий пароль для подключения к внешней базе данных.
хорошо б рассмотреть и остальные виды аутентификации тоже

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую базу данных в составе внешнего кластера {{ ydb-short-name }}. Параметр `DATABASE_NAME` содержит им
тут почему-то большой акцент делается на том, что это «внешний» кластер, но наверное для двух баз в рамках одного кластера будет то же самое?

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую базу данных в составе внешнего кластера {{ ydb-short-name }}. Параметр `DATABASE_NAME` содержит им
из этого текста не понятно будут ли они проверять доверенность TLS сертификатов и если да, то как это отключить или подложить дополнительный CA файл

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Для корректного выполнения запроса необходимо [развернуть коннектор](../../deploy/manual/deploy-ydb-federated-query.md) и обеспечить сетевой доступ с динамических узлов {{ ydb-full-name }} к класт
наверное не всего кластера, а именно динамических узлов той базы, с которой работаем?

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +SELECT * FROM ydb_datasource.<table_name>
пример по-реслистичнее сюда бы, в table_name же наверное полный путь ожидается и примерно всегда будут слеши, ради которых придётся заворачивать его в бектики? или нет и таблица в корне целевой базы с простым именем может обойтись без бектиков?

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Поддерживаются только запросы чтения данных - `SELECT`, остальные виды запросов не поддерживаются.
не однозначно читается: имеется ввиду, что даже условно `INSERT ... SELECT ...` из федеративной в локальную таблицу нельзя? или только что федеративная таблица по сути read-only?

2024-05-23 15:50 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +|Простой тип данных|Опциональный тип данных|
Если я правильно помню соседние статьи, то там в подобных таблицах был маппинг между двумя системами типов данных и можно подумать, что эта таблица такая же, что вроде не так. Я б прямым текстом написал, что преобразований типов данных не происходит, а вот плоский список поддерживаемых типов данных. Или таблицей из одной колонки или в списке с буллетами.

2024-05-24 14:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [секрет](../datamodel/secrets.md), содержащий пароль для подключения к внешней базе данных.
Из 4 упоминаемых методов аутентификации мы поддерживаем только один (base auth) - сослался на соотв. раздел доки.  Есть ещё второй, через IAM, но он работает только в инфраструктуре Я.Облака (через сервисные аккаунты), поэтому oss пользователям он вряд ли пригодится.

2024-05-24 14:32 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую базу данных в составе внешнего кластера {{ ydb-short-name }}. Параметр `DATABASE_NAME` содержит им
Да, убрал слово "кластер" отовсюду.

2024-05-24 14:33 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую базу данных в составе внешнего кластера {{ ydb-short-name }}. Параметр `DATABASE_NAME` содержит им
Убрал эту ремарку о сертификатах TLS в отдельный инклюд и добавил его также в документацию по PG/CH. Ссылаюсь на страницу с инструкцией по разворачиванию коннектора, там эта тема рассматривается.

2024-05-24 14:34 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +SELECT * FROM ydb_datasource.<table_name>
Согласен, сделал

2024-05-24 14:35 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Для корректного выполнения запроса необходимо [развернуть коннектор](../../deploy/manual/deploy-ydb-federated-query.md) и обеспечить сетевой доступ с динамических узлов {{ ydb-full-name }} к класт
Теперь это тоже отдельный инклюд, который используется на всех трёх страницах YDB / CH / PG. Пишу более обтекаемо, что нужно просто обеспечить сетевой доступ к внешнему источнику данных по адресу, указанному в `Location`

2024-05-24 14:38 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Поддерживаются только запросы чтения данных - `SELECT`, остальные виды запросов не поддерживаются.
Да, здесь имелось в виду второе. Постарался расписать

2024-05-24 14:38 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +|Простой тип данных|Опциональный тип данных|
Сделал просто таблицу из одной колонки

2024-06-03 09:43 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [секрет](../datamodel/secrets.md), содержащий пароль для подключения к внешней базе данных.
@vitalyisaev2 да, давай

2024-06-03 10:02 UTC, blinkov requested changes, later dismissed

2024-06-03 10:02 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +SELECT * FROM ydb_datasource.<table_name>
думаю тут было б логичнее вместо плэйсхолдера какой-то конкретный пример привести

2024-06-03 10:02 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +В случае, если таблица находится на верхнем уровне иерархии (не принадлежит ни одному из каталогов), допускается не заключать имя таблицы в обратные апострофы "\`":
кстати, а сами data source небось же тоже можно не в корень, а в директории складывать?

2024-06-03 13:27 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/_includes/datetime_limits.md
> +Если значение даты, хранящейся во внешнем источнике данных, находится вне допустимого для {{ ydb-short-name }} диапазона (все используемые даты должны быть позднее 1970-01-01, но ранее 2105-12-31), т
Да, всё так. Убрал "в интерфейсе".

2024-06-03 13:47 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +        LOCATION="<host>:<port>",
Добавил эту информацию. Хотел сослаться на какую-нибудь страничку, в которой рассказывается про то, сколько и каких портов есть у YDB, но ничего кроме [этого](https://ydb.tech/docs/ru/concepts/connect#endpoint) не нашёл (кажется, не очень релевантно).

2024-06-03 13:53 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Создать [секрет](../datamodel/secrets.md), содержащий пароль для подключения к внешней базе данных.
добавил

2024-06-03 14:01 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +В случае, если таблица находится на верхнем уровне иерархии (не принадлежит ни одному из каталогов), допускается не заключать имя таблицы в обратные апострофы "\`":
Мне подсказали, что да - такая возможность есть, data source можно создавать в директориях, как и таблицы.

Но я бы не стал добавлять сюда эту информацию, кмк, более подходящее место - https://ydb.tech/docs/ru/concepts/datamodel/external_data_source, и лучше отдельным PR.

2024-06-04 07:37 UTC, fomichev3000 approved these changes, later dismissed

2024-06-04 07:37 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Подготовить аутентфикационные данные для доступа к удалённой базе {{ ydb-short-name }}. В настоящее время в федеративных запросах к {{ ydb-short-name }} доступен метод аутентификации по [логину и
"Подготовить аутентфикационные данные" -- ошибка в слове "аутентфикационные"

2024-06-04 08:07 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/ydb.md
> +1. Подготовить аутентфикационные данные для доступа к удалённой базе {{ ydb-short-name }}. В настоящее время в федеративных запросах к {{ ydb-short-name }} доступен метод аутентификации по [логину и
fixed

2024-06-04 08:48 UTC, blinkov approved these changes

2024-06-04 19:20 UTC, merged