allow alter config in replication
ydb-platform/ydb pull request #4850
Opened 2024-05-24 16:21 UTC by VPolka

add alter params for async replication

### Changelog category 

* Improvement

### Additional information

...

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/tx/replication/controller/tx_alter_replication.cpp
> +        case NKikimrReplication::TReplicationState::kPaused:
Добавь TODO, потому что переход в эти состояния не имплементирован.

2024-05-27 12:26 UTC, CyberROFL commented on ydb/library/yql/sql/v1/sql_query.cpp
> +    } else if (!alter && !it->second) {
Не очень понял смысл этих изменений.

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/kqp/provider/yql_kikimr_exec.cpp
> +            if (settings.Settings.ConnectionString && (settings.Settings.Endpoint || settings.Settings.Database)) {
Лучше бы вынести это в общие функции и не копи-пастить.

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_replication.cpp
> +                "It is not allowed to change both settings and the state of the rplication in the same query. Please submit separate queries for each action");
```suggestion
                "It is not allowed to change both settings and the state of the replication in the same query. Please submit separate queries for each action");
```

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/tx/replication/controller/tx_alter_replication.cpp
>          switch (record.GetSwitchState().GetStateCase()) {
А где ветка для применения изменений конфига?

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
> +            UNIT_ASSERT(result.GetIssues().ToOneLineString().Contains("Check failed: path: '/Root/replication', error: path hasn't been resolved, nearest resolved path: '/Root'"));
Есть `UNIT_ASSERT_STRING_CONTAINS`, тогда сообщение об ошибке будет более понятным.

2024-05-27 12:26 UTC, CyberROFL commented on ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
> -    Y_UNIT_TEST(Decimal) {
Кажется, не нужно удалять этот тест.

2024-05-30 14:48 UTC, VPolka commented on ydb/core/tx/replication/controller/tx_alter_replication.cpp
> +        case NKikimrReplication::TReplicationState::kPaused:
пока удалила эти изменения, в этом пр они не нужны

2024-05-30 14:48 UTC, VPolka commented on ydb/library/yql/sql/v1/sql_query.cpp
> +    } else if (!alter && !it->second) {
Сделала немного понятнее. По сути сейчас разрешаю для alter любые настройки менять, а для create не разрешаю менять state

2024-05-30 14:50 UTC, VPolka commented on ydb/core/tx/replication/controller/tx_alter_replication.cpp
>          switch (record.GetSwitchState().GetStateCase()) {
Правильно ли я понимаю, что действия тут нужны, только если меняется state? как будто в контроллере при изменении конфига ничего не нужно делать, так как считается, что репликация на паузе и при старте оно все новые значения перечитает

сейчас выставляю SwitchState, если в alterData он отличается от предыдущего значения, и если он не выставлен, то в контроллере ничего не делаю

2024-06-03 15:16 UTC, CyberROFL requested changes

2024-06-03 15:16 UTC, CyberROFL commented on ydb/core/tx/replication/controller/replication.h
> +    void SetConfig(const NKikimrReplication::TReplicationConfig& config, TString issue = {});
Конфиг можно сразу перемещать.

2024-06-03 15:16 UTC, CyberROFL commented on ydb/core/tx/replication/controller/replication.h
> +    void SetConfig(const NKikimrReplication::TReplicationConfig& config, TString issue = {});
Не очень понял, для чего тут issue?

2024-06-03 15:16 UTC, CyberROFL commented on ydb/library/yql/sql/v1/sql_query.cpp
> +    TSet<TString> stateSettings = {"state", "failover_mode"};
Пусть каждая настройка будет на отдельной строке: 1) однообразие; 2) легче расширять (меньше дифф). И не забудь `,` на последней строке.

2024-06-03 15:16 UTC, CyberROFL commented on ydb/library/yql/sql/v1/sql_query.cpp
> +        "password_secret_name"
```suggestion
        "password_secret_name",
```

2024-06-03 15:16 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_replication.cpp
> +            auto& confRes = *(alterData->Description.MutableConfig());
Что-нибудь типа newConf, oldConf было бы понятнее.

2024-06-03 15:16 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_replication.cpp
> +                        paramRes.MutableStaticCredentials()->SetPasswordSecretName({});
Тут можно делать Clear.
Более того, далее по коду в коде контроллера проверяется существование поля через Has, так что здесь точно должен быть Clear.

2024-06-03 19:10 UTC, nepal approved these changes

2024-06-03 20:02 UTC, CyberROFL approved these changes

2024-06-04 09:56 UTC, merged