add ms sql server
ydb-platform/ydb pull request #4862
Opened 2024-05-25 21:27 UTC by Glebbs

### Changelog entry 
Add Microsoft SQL Server Support
...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-27 08:00 UTC, vitalyisaev2 requested changes

2024-05-27 08:00 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        break;
У меня есть ощущение, что этот свитч - легаси, и его не надо развивать. Давай удалим новый case и проверим через kqprun ещё раз, всё ли работает

2024-05-28 12:12 UTC, uzhastik commented on ydb/core/external_sources/external_source_factory.cpp
> +            ToString(NYql::EDatabaseType::MicrosoftSqlServer),
давайте сократим название: вместо microsoft предлагаю написать ms

2024-05-28 12:12 UTC, uzhastik commented on ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
> +  MicrosoftSqlServer
давай назовем MSSQL

2024-06-03 14:36 UTC, closed without merging