Yq 3224: Add Greenplum connector to YDB
ydb-platform/ydb pull request #4907
Opened 2024-05-27 19:58 UTC by skywalker-jpg

### Changelog entry 

Add Greenplum as new connect to YDB

### Changelog category 

* New feature

2024-05-28 11:01 UTC, vitalyisaev2 requested changes

2024-05-28 11:01 UTC, vitalyisaev2 commented on ydb/tests/tools/kqprun/app_conf.txt
> +}
В репозитории YDB все эти файлы не стоит хранить. Можешь их сложить в scripts/debug коннектора.

2024-05-28 11:21 UTC, skywalker-jpg commented on ydb/tests/tools/kqprun/app_conf.txt
> +}
да, я их удалю как можно будет мерить

2024-05-28 11:31 UTC, skywalker-jpg commented on ydb/tests/tools/kqprun/app_conf.txt
> +}
да, я их уберу как можно будет мерить

2024-05-28 16:37 UTC, skywalker-jpg commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls", "schema"}, hostnamePatternsRegEx)
1)если убрать протокол он пишет вот такое Failed to execute scheme query, reason:
Request finished with status: SCHEME_ERROR
Issues:
<main>: Error: Execution, code: 1060
    <main>:10:14: Error: Executing CREATE OBJECT EXTERNAL_DATA_SOURCE
        <main>: Error: <main>: Error: (NKikimr::NExternalSource::TExternalSourceException) ydb/core/external_sources/external_data_source.cpp:49: Unsupported property: protocol, code: 2003
, code: 2003
2) добавил

2024-05-28 16:48 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls", "schema"}, hostnamePatternsRegEx)
Убери protocol из запроса

2024-05-29 10:16 UTC, vitalyisaev2 requested changes

2024-05-29 10:16 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/api/common/data_source.proto
> +
Перемести его под `TS3DataSourceOptions` плз. Чтобы была консистентность в последовательности объявления типов и полйе

2024-05-29 10:53 UTC, vitalyisaev2 approved these changes

2024-05-29 11:07 UTC, vitalyisaev2 requested changes

2024-05-29 11:07 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
> +        if (clusterConfig.GetKind() == EDataSourceKind::YDB || clusterConfig.GetKind() == EDataSourceKind::GREENPLUM) {
Вот тут воспользуйся конструкцией ` IsIn({1,2,3}, x)` и перепиши этот код более компактно. Захвати ещё сюда MySQL (отдельный if снизу)

2024-05-29 12:01 UTC, vitalyisaev2 submitted a review, later dismissed

2024-05-29 12:06 UTC, dorooleg submitted a review, later dismissed

2024-05-29 12:23 UTC, uzhastik submitted a review, later dismissed

2024-05-29 12:39 UTC, rvu1024 approved these changes, later dismissed

2024-05-29 19:18 UTC, vitalyisaev2 approved these changes

2024-05-29 20:28 UTC, rvu1024 approved these changes

2024-05-29 20:48 UTC, merged