Translation of documentation
ydb-platform/ydb pull request #4918
Opened 2024-05-28 08:44 UTC by Alek5andr-Kotov

### Changelog entry 

Documentation on reading from topics in a transaction.

### Changelog category 

* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-28 09:29 UTC, blinkov requested changes, later dismissed

2024-05-28 09:29 UTC, blinkov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +You can use [transactions](#read-tx). In this case, the reading offset will change only when the transaction is commited. When you connect again, all uncommited messages will be read.
```suggestion
Data from topics can be read in the context of [transactions](#read-tx). In this case, the reading offset will only advance when the transaction is committed. On reconnect, all uncommitted messages will be read again.
```

2024-05-28 09:29 UTC, blinkov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +  Before reading messages, the client code must pass a reference to the transaction object to the settings of the reading session.
```suggestion
  Before reading messages, the client code must pass a transaction object reference to the reading session settings.
```

2024-05-28 09:29 UTC, blinkov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +  When processing `events`, you do not need to explicitly confirm processing for events of the `TDataReceivedEvent`.
```suggestion
  When processing `events`, you do not need to confirm processing for `TDataReceivedEvent` events explicitly.
```

2024-05-30 08:46 UTC, Alek5andr-Kotov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +You can use [transactions](#read-tx). In this case, the reading offset will change only when the transaction is commited. When you connect again, all uncommited messages will be read.
fixed
https://github.com/ydb-platform/ydb/pull/4918/commits/2884b64e8c40cd192b9ea61db595b75a08017044

2024-05-30 08:47 UTC, Alek5andr-Kotov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +  Before reading messages, the client code must pass a reference to the transaction object to the settings of the reading session.
fixed
https://github.com/ydb-platform/ydb/pull/4918/commits/2884b64e8c40cd192b9ea61db595b75a08017044

2024-05-30 08:47 UTC, Alek5andr-Kotov commented on ydb/docs/en/core/reference/ydb-sdk/topic.md
> +  When processing `events`, you do not need to explicitly confirm processing for events of the `TDataReceivedEvent`.
fixed
https://github.com/ydb-platform/ydb/pull/4918/commits/2884b64e8c40cd192b9ea61db595b75a08017044

2024-06-04 07:32 UTC, fomichev3000 approved these changes, later dismissed

2024-08-28 06:54 UTC, blinkov approved these changes

2024-08-28 07:01 UTC, merged