add techinternals ydb vs. tpcc presentation
ydb-platform/ydb pull request #4934
Opened 2024-05-28 12:14 UTC by eivanov89

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-05-28 12:51 UTC, blinkov requested changes, later dismissed

2024-05-28 12:51 UTC, blinkov commented on ydb/docs/en/core/public-materials/_includes/conferences/2024/TechInternals.md
> +Modern distributed databases scale horizontally with great efficiency, making them almost limitless in capacity. This implies that benchmarks should be able to run on multiple machines and be very ef
```suggestion
Modern distributed databases scale horizontally with great efficiency, making them almost limitless in capacity. This implies that benchmarks should be able to run on multiple machines and be very efficient to minimize the number of machines required. This talk will focus on benchmarking high-performance databases, particularly emphasizing YDB and our implementation of the TPC-C benchmark, the de facto gold standard in the database field.
```

2024-05-28 12:51 UTC, blinkov commented on ydb/docs/en/core/public-materials/_includes/conferences/2024/TechInternals.md
> +Next, we’ll briefly discuss the popular key-value benchmark YCSB, which we believe is a prerequisite for robust performance in distributed transactions. Following this, we'll explore the TPC-C benchm
```suggestion
Next, we'll briefly discuss the popular key-value benchmark YCSB, which is a prerequisite for robust performance in distributed transactions. We'll then explore the TPC-C benchmark in greater detail, sharing valuable insights derived from our own implementation.
```

2024-05-28 12:51 UTC, blinkov commented on ydb/docs/en/core/public-materials/_includes/conferences/2024/TechInternals.md
> +[{{ team.ivanov.name }}]({{ team.ivanov.profile }}) ({{ team.ivanov.position }}) discussed best high performance benchmarking practices and some pitfalls found during TPC-C implementation, then demon
```suggestion
We'll conclude our talk by presenting performance results from the TPC-C benchmark, comparing YDB and CockroachDB with PostgreSQL to illustrate situations where PostgreSQL might not be enough and when you might want to consider a distributed DBMS instead.

[{{ team.ivanov.name }}]({{ team.ivanov.profile }}) ({{ team.ivanov.position }}) discussed best high-performance benchmarking practices and some pitfalls found during TPC-C implementation, then demonstrated TPC-C results of PostgreSQL, CockroachDB, and YDB.
```

2024-06-01 04:54 UTC, fomichev3000 approved these changes

2024-06-01 04:54 UTC, merged