feat: add MySQL to list of supported external sources
ydb-platform/ydb pull request #4951
Opened 2024-05-28 19:09 UTC by mkls6

### Changelog entry 
This PR adds MySQL to list of supported external data sources.

### Changelog category 

* New feature

2024-05-28 21:02 UTC, uzhastik commented on ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
> +    MySQL,
Рекомендую в енумы добавлять новые значения исключительно в конец

2024-05-29 06:35 UTC, vitalyisaev2 requested changes

2024-05-29 06:35 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
1. Protocol можно отсюда убрать, т. к. он всегда будет Native. Также его надо убрать и из SQL запроса
2. https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L195 вот в этот if надо добавить новую базу, чтобы проставлялся дефолтный протокол.

2024-05-29 06:35 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +#include "ydb/library/yql/providers/generic/connector/api/common/data_source.pb.h"
этот инклюд точно нужен? раньше без него работало же

2024-05-29 07:13 UTC, mkls6 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +#include "ydb/library/yql/providers/generic/connector/api/common/data_source.pb.h"
Не нужен, добавился (как и ещё в одном месте такой же) редактором автоматически :)

2024-05-29 07:14 UTC, mkls6 commented on ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
> +    MySQL,
Поменял, чтобы был в конце (5fd9bbe)

2024-05-29 07:15 UTC, mkls6 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
Сделал в 2dab57d и 332ab68

2024-05-29 07:21 UTC, vitalyisaev2 approved these changes

2024-05-29 07:49 UTC, uzhastik approved these changes

2024-05-29 08:40 UTC, rvu1024 approved these changes

2024-05-29 10:17 UTC, merged