YQ-2068 integrate stream lookup(no cache)
ydb-platform/ydb pull request #5002
Opened 2024-05-30 07:55 UTC by zverevgeny

2024-05-30 08:19 UTC, vitalyisaev2 requested changes

2024-05-30 08:19 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
> +                        break;
CH / PG выглядят лишними для функциональности лукапов в YDB. Но раз уж на то пошло - может, обобщить эту функцию с той, из которой эта была копирована?

2024-05-30 09:15 UTC, rvu1024 commented on ydb/library/yql/providers/yt/actors/yql_yt_provider_factories.h
> +#include <ydb/library/yql/providers/common/token_accessor/client/factory.h>
не все есть в PEERDIR-ах

2024-05-30 09:15 UTC, rvu1024 commented on ydb/library/yql/providers/yt/actors/yql_yt_provider_factories.cpp
> +#include <ydb/library/yql/providers/yt/proto/source.pb.h>
нет в PEERDIR-ах

2024-05-30 09:15 UTC, rvu1024 commented on ydb/library/yql/providers/dq/opt/logical_optimize.cpp
> +            auto ytTable = ytReadTable.Raw()->Child(2)->Child(0)->Child(0)->Child(0)->Child(0);
Это какое-то невалидируемое знание про внутренее устройство коллабла

2024-05-30 09:15 UTC, rvu1024 commented on ydb/library/yql/providers/dq/opt/logical_optimize.cpp
> +    }
Эти функции стоит унести в IDqOptimization

2024-05-30 09:51 UTC, uzhastik commented
давай тесты еще писать. очень много кода без тестов

2024-05-30 09:51 UTC, uzhastik commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        Cerr << "TEvNewAsyncInputDataArrived sent\n";
дебажный принт

2024-05-30 09:51 UTC, uzhastik commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        while(!ReadyQueue.empty()) {
нужен пробел после while

2024-05-30 09:51 UTC, uzhastik commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        issues.AddIssue(std::move(issue));
напоминаю, что TIssue не мувается, а копируется

2024-06-01 05:36 UTC, zverevgeny commented on ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
> +                        break;
done

2024-06-01 05:36 UTC, zverevgeny commented on ydb/library/yql/providers/yt/actors/yql_yt_provider_factories.h
> +#include <ydb/library/yql/providers/common/token_accessor/client/factory.h>
fixed

2024-06-01 05:36 UTC, zverevgeny commented on ydb/library/yql/providers/yt/actors/yql_yt_provider_factories.cpp
> +#include <ydb/library/yql/providers/yt/proto/source.pb.h>
fixed

2024-06-01 05:37 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        Cerr << "TEvNewAsyncInputDataArrived sent\n";
fixed

2024-06-01 05:37 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        issues.AddIssue(std::move(issue));
fixed

2024-06-08 15:22 UTC, uzhastik commented on ydb/library/yql/providers/common/dq/yql_dq_integration_impl.cpp
> +    Y_ABORT("Unimplemented");
не сможет ли юзер завалить сервис, если попытается сджойнить какие-то источники, которые не поддерживают лукап джойн? может, лучше просто ошибку выдать?

2024-06-11 09:15 UTC, zverevgeny commented on ydb/library/yql/providers/dq/opt/logical_optimize.cpp
> +    }
Вторую унёс. Первая, на мой взгляд, довольно общая и не имеет специфики провайдера.

2024-06-11 09:15 UTC, zverevgeny commented on ydb/library/yql/providers/dq/opt/logical_optimize.cpp
> +            auto ytTable = ytReadTable.Raw()->Child(2)->Child(0)->Child(0)->Child(0)->Child(0);
fixed

2024-06-11 15:06 UTC, zverevgeny commented on ydb/library/yql/providers/common/dq/yql_dq_integration_impl.cpp
> +    Y_ABORT("Unimplemented");
fixed

2024-06-11 15:14 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +            .DataSource(readTable.Raw()->Child(1))
readTable.DataSource()

2024-06-11 15:14 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +            .RowType(ExpandType(read->Pos(), *GetSeqItemType(typeAnn), ctx))
Тип можно взять из read. Зачем его извне тащить?

2024-06-11 15:17 UTC, vitalyisaev2 requested changes

2024-06-11 15:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
> +                }
Поскольку `LookupSourceSettings` используется только для YDB, а поддержка YDB появилась относительно недавно, кмк, этот код можно упростить, поскольку поддержка обратной совместимости тут не нужна. 

Можно принять, что у нас все запросы выглядят как `SELECT * FROM ext_data_source.table`, поэтому точки и бектиков в названии таблицы не будет, соответственно и сплитить таблицу по точке не нужно.

2024-06-12 07:00 UTC, zverevgeny commented on ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
> +                }
fixed

2024-06-12 07:00 UTC, zverevgeny commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +            .RowType(ExpandType(read->Pos(), *GetSeqItemType(typeAnn), ctx))
fixed

2024-06-12 07:00 UTC, zverevgeny commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +            .DataSource(readTable.Raw()->Child(1))
fixed

2024-06-13 08:15 UTC, vitalyisaev2 submitted a review, later dismissed

2024-06-13 11:53 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
>          const NMiniKQL::TMultiType* const inputRowType,
Который из двух? На мой взгляд, оба нужны

2024-06-13 11:56 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +                LookupSource.first->AsyncLookup(keysForLookup);
Переделаю это место в отдельном PR. Тут нужно поменять вектор на мапу

2024-06-13 15:24 UTC, uzhastik commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
>          const NMiniKQL::TMultiType* const inputRowType,
второй. вот так достаточно же: ``const NMiniKQL::TMultiType* inputRowType,``

2024-06-13 15:27 UTC, uzhastik commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +    TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr& reader, TExprContext& ctx) override {
почему узел назвал reader? вроде прежнее название read было лучше, мы часто его используем. и callable тоже скорее read, нежели reader

2024-06-13 16:38 UTC, zverevgeny commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +    TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr& reader, TExprContext& ctx) override {
для единообразия с имеющимся кодом

2024-06-13 16:41 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
> +        > Map(
fixed

2024-06-13 16:41 UTC, zverevgeny commented on ydb/library/yql/dq/integration/yql_dq_optimization.h
> +    virtual TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr read, TExprContext& ctx) = 0;
fixed

2024-06-13 16:41 UTC, zverevgeny commented on ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
> +                source.mutable_data_source_instance()->CopyFrom(tableMeta.value()->DataSourceInstance);
fixed

2024-06-13 16:41 UTC, zverevgeny commented on ydb/library/yql/tools/dqrun/dqrun.cpp
> +                CreateAsyncIoFactory(driver, httpGateway, ytFileServices, genericClient, credentialsFactory, *funcRegistry.Get(), requestTimeout, maxRetries), threads,
fixed

2024-06-13 16:43 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
>          const NMiniKQL::TMultiType* const inputRowType,
Разная семантика. У тебя изменяемый мембер на константный тип. У меня константный мембер(который можно только через список инициализации в конструкторе задать) на константный тип

2024-06-13 17:12 UTC, uzhastik commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +    TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr& reader, TExprContext& ctx) override {
блин, я бы наверху как раз переименовал в read
@rvu1024 как считаешь?

2024-06-13 17:15 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +    TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr& reader, TExprContext& ctx) override {
можно переименовать

2024-06-14 07:33 UTC, zverevgeny commented on ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
> +    TExprNode::TPtr RewriteLookupRead(const TExprNode::TPtr& reader, TExprContext& ctx) override {
И я не против. Сделаю отдельный PR

2024-06-14 08:17 UTC, uzhastik commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
>          const NMiniKQL::TMultiType* const inputRowType,
семантика одинаковая, тут вообще нет мемберов, это же аргументы конструктора.
рассмотрим более простой эквивалент твоей текущей сигнатуры
```
int sqr(const int x) {
  return x * x;
}
```
я же предлагаю убрать const:
```
int sqr(int x) {
  return x * x;
}

```

2024-06-14 08:19 UTC, uzhastik submitted a review, later dismissed

2024-06-14 10:06 UTC, zverevgeny commented on ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
>          const NMiniKQL::TMultiType* const inputRowType,
сори, туплю. поправил

2024-06-14 10:09 UTC, uzhastik approved these changes

2024-06-14 13:18 UTC, gridnevvvit approved these changes

2024-06-14 14:03 UTC, rvu1024 approved these changes

2024-06-14 14:05 UTC, merged