Speedup and Cleanup
ydb-platform/ydb pull request #5101
Opened 2024-06-01 22:43 UTC by Hor911

2024-06-03 10:28 UTC, resetius submitted a review, later dismissed

2024-06-03 12:38 UTC, iddqdex requested changes

2024-06-07 15:25 UTC, Hor911 commented on ydb/library/benchmarks/queries/tpch/ydb/q22.sql
> +    cntrycode = '31' or cntrycode = '29' or cntrycode = '30' or cntrycode = '26' or cntrycode = '28' or cntrycode = '25' or cntrycode = '15'
Сейчас IN плохо пушдаунится или не пушдаунится совсем

2024-06-08 06:05 UTC, iddqdex approved these changes

2024-06-08 06:36 UTC, merged