Ms sql
ydb-platform/ydb pull request #5131
Opened 2024-06-03 13:54 UTC by Glebbs

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-06-03 13:58 UTC, vitalyisaev2 requested changes

2024-06-03 13:58 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"BASIC"}, {"database_name", "protocol", "use_tls"}, hostnamePatternsRegEx)
1. protocol давай уберём, поскольку он только один и возможен - это `Native` протокол
2. https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L195 а сюда добавим твою базу

2024-06-03 14:34 UTC, vitalyisaev2 approved these changes

2024-06-03 14:39 UTC, vitalyisaev2 requested changes

2024-06-03 14:39 UTC, vitalyisaev2 commented on ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
> +    MsSqlServer
просим переименовать в `MsSQLServer`

2024-06-03 14:43 UTC, uzhastik commented on ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
> +    MsSqlServer
давайте три буквы SQL писать одинаково в этом енуме. см. имена PostgreSQL, MySQL

2024-06-03 15:22 UTC, vitalyisaev2 approved these changes

2024-06-04 08:12 UTC, uzhastik approved these changes

2024-06-04 09:08 UTC, MrLolthe1st approved these changes

2024-06-04 09:17 UTC, merged