Feature test
ydb-platform/ydb pull request #5151
Opened 2024-06-04 07:55 UTC by lifthelm

### Changelog category 

* Connector Json postgresql support tests

2024-06-06 11:17 UTC, vitalyisaev2 requested changes

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/run/dqrun.py
> +            with open(artifacts.make_path(test_name, "dprun.out"), "w") as f:
dqrun

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/run/runners.py
> +            return DqRunner(dqrun_path=yat.build_path("ydb/library/yql/tools/dqrun/dqrun"), settings=settings, udfs_dir=yat.build_path("ydb/library/yql/udfs/common/json2"))
Тут что-то не так с неймингом. `udfs_dir` , в моём понимании, это путь до папки, где много udf-ок. А мы прокидываем сюда только одну. То есть либо `udfs_dir` переименовать, либо прокидывать туда какую-то более общую папку, где и другие udf-ки могут находиться.

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/run/kqprun.py
> +# import yql_utils
удоли

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/select_positive.py
> +                # maybe col_26_time?
на мой вкус, лучше сделать `col_27_json` и переместить его пониже

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/ya.make
> +    ydb/library/yql/udfs/common/json2
отсортируй плз этот список в алфавитном порядке

2024-06-06 11:17 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/run/kqprun.py
> +        udfs_dir = self.udfs_dir
вроде как можно этого и не делать, ведь udfs_dir используются только в этом методе

2024-06-06 23:13 UTC, lifthelm commented on ydb/library/yql/providers/generic/connector/tests/utils/run/dqrun.py
> +            with open(artifacts.make_path(test_name, "dprun.out"), "w") as f:
исправил

2024-06-07 10:44 UTC, vitalyisaev2 requested changes

2024-06-07 10:44 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/ydb/select_positive.py
> +                    name='col_16_json',
17

2024-06-07 10:44 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/ydb/select_positive.py
> +                    name='col_16_json',
col_17

2024-06-07 10:44 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/ydb/select_positive.py
> +    # def _json(self) -> Sequence[TestCase]:
не забыл раскомментировать?

2024-06-07 10:44 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
> +        time.sleep(15)
Всё ещё вижу здесь слип. Договаривались сделать цикл же

2024-06-10 08:11 UTC, vitalyisaev2 requested changes

2024-06-10 08:11 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/run/dqrun.py
> +            with open(artifacts.make_path(test_name, "dprun.out"), "w") as f:
недоехало

2024-06-10 09:58 UTC, vitalyisaev2 approved these changes

2024-06-10 09:59 UTC, merged