SQL hints map() and grace()
ydb-platform/ydb pull request #5252
Opened 2024-06-06 00:37 UTC by Hor911

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-06-06 14:59 UTC, nepal requested changes

2024-06-06 14:59 UTC, nepal commented on ydb/library/yql/dq/opt/dq_opt_join.cpp
> -TExprBase DqBuildHashJoin(const TDqJoin& join, EHashJoinMode mode, bool useCBO, TExprContext& ctx, IOptimizationContext& optCtx) {
Почему в этом PR есть какие-то изменения связанные с CBO?
И почему канонизация поменялась?

2024-06-06 14:59 UTC, nepal commented on ydb/library/yql/sql/v1/join.cpp
> +                linkOptions = L(linkOptions, Q(Y(Q("join_algo"), Q("MapJoin"))));
По хорошему, MapJoin должен уметь параметризироваться - типа по какой таблице делается Map.

Т.е. это должно выглядеть так: A join /* map(left) */ B - тут таблица B идет в словарь
а просто /* map() */ означает "выбрать словарь автоматически"

2024-06-09 22:38 UTC, Hor911 commented on ydb/library/yql/dq/opt/dq_opt_join.cpp
> -TExprBase DqBuildHashJoin(const TDqJoin& join, EHashJoinMode mode, bool useCBO, TExprContext& ctx, IOptimizationContext& optCtx) {
useCBO там означал только то что надо принять во внимание содержимое TDqJoin::JoinAlgo
Раньше он приезжал только от CBO, я обобщаю это поведение, это же может быть выведено из хинта
Поэтому флаг не нужен, JoinAlgo используется всегда кода не пустой и имеет приоритет над HashJoinMode

2024-06-09 22:40 UTC, Hor911 commented on ydb/library/yql/sql/v1/join.cpp
> +                linkOptions = L(linkOptions, Q(Y(Q("join_algo"), Q("MapJoin"))));
Выглядит сложным в реализации. Сейчас в AST нет признака про словарь и всегда выбирается правая часть. Боюсь на пустом месте наделать ошибок. Текущая конвенция - управлять лево/право непосредственно в коде запроса выглядит вполне приемлимой

2024-06-10 08:17 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_select.cpp
> +                } else if (canonizedName == "map") {
map_left/map_right

2024-06-13 10:29 UTC, nepal requested changes

2024-06-13 11:00 UTC, Hor911 commented on ydb/library/yql/sql/v1/join.cpp
> +                linkOptions = L(linkOptions, Q(Y(Q("join_algo"), Q("MapJoin"))));
Это не входит в скоуп данной задачи, join_algo уже был и как-то работал без валидации. Если потребовалась валидация - ОК, можно делать, но давай отдельно чтобы не блокировать текущий PR

2024-06-13 11:01 UTC, Hor911 commented on ydb/library/yql/sql/v1/sql_select.cpp
> +                } else if (canonizedName == "map") {
Моя позиция - отложить это до так называемых "пользовательских хинтов"
Сейчас объем доработок (по расстановке и валидации left/right) выглядт очень большим по сравнению с пользой

2024-06-13 12:42 UTC, nepal approved these changes
parser part LGTM

2024-06-13 18:02 UTC, resetius approved these changes

2024-06-13 18:48 UTC, merged