Add OLAP to YQL MAIN SYNTAX
ydb-platform/ydb pull request #5323
Opened 2024-06-07 13:14 UTC by Pseudolukian

### Changelog category 

* Documentation (changelog entry is not required)

2024-06-10 02:09 UTC, blinkov requested changes

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +Добавляет строки в строковую таблицу. {% if feature_bulk_tables %} Если целевая таблица уже существует и не является сортированной, операция `INSERT INTO` дописывает строки в конец таблицы. В случае
В отличии от большинства соседних статей в этом PR, эта точно используется и в YQL over YT. Так как это отдельный сервис, там совсем другая реализация таблиц, но они тоже бывают и колоночными и строчными. `INSERT INTO` в колоночные таблицы там работал ещё лет 8 назад, так что это изменение явно не должно попасть в ту доку.

Также похоже в сам `not_allow_for_olap.md` стоит добавить `if`, который бы не рисовал этот блок в документациях, отличных от самого YDB.

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/replace_into.md
> +Сохраняет данные в строчную таблицу с перезаписью строк по первичному ключу.{% if feature_mapreduce %}  Таблица по имени ищется в базе данных, заданной оператором [USE](../use.md).{% endif %} Если за
Похоже тут проблема, аналогичная описанному выше в комментариях к `insert_into.md`.

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/unique_distinct_hints.md
> +Непосредственно после `SELECT` возможно добавить [SQL хинты](../lexer.md#sql-hints) `unique` или `distinct` которые заявляют, что эта проекция порождает данные, содержащие уникальные значения в указа
Исправление опечаток полезно, но выглядит не связанным с этим PR — давай вынесем в отдельный.

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/update.md
> +Изменяет данные в строковой таблице.{% if feature_mapreduce %}  Таблица по имени ищется в базе данных, заданной оператором [USE](../use.md).{% endif %} После ключевого слова `SET` указываются столбцы
Похоже тут проблема, аналогичная описанному выше в комментариях к `insert_into.md`.

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/upsert_into.md
> +UPSERT (расшифровывается как UPDATE or INSERT) обновляет или добавляет множество строк в строчной таблице на основании сравнения по первичному ключу. Отсутствующие строки добавляются. В присутствующи
Похоже тут проблема, аналогичная описанному выше в комментариях к `insert_into.md`.

Плюс надо определиться «строковые» они или «строчные».

2024-06-10 02:09 UTC, blinkov commented on ydb/docs/ru/core/_includes/not_allow_for_olap.md
> +Не поддерживается для колоночных таблиц.
также возможно стоит начать эту фразу с менее негативного, что мол поддерживается только для строчных таблиц, а текущий текст сделать уже вторым предложением

2024-06-10 02:23 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
> +Удалить данные из колоночной таблицы можно с помощью [TTL](../../../../concepts/ttl.md), который можно задать при [создании таблицы](../create_table.md) (`CREATE TABLE`) или при [изменении таблицы](.
Также см. в `insert_into.md` про то, как избежать лишнего `{% note %}`

2024-06-10 06:51 UTC, Pseudolukian commented on ydb/docs/ru/core/_includes/not_allow_for_olap.md
> +Не поддерживается для колоночных таблиц.
Поправил.

2024-06-10 06:51 UTC, Pseudolukian commented on ydb/docs/ru/core/_includes/not_allow_for_olap.md
> +Не поддерживается для колоночных таблиц.
Добавил.

2024-06-10 06:58 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +```ADD FAMILY``` — создаёт новую группу колонок в строковой или колоночной таблице. Приведенный ниже код создаст в таблице ```series_with_families``` группу колонок ```family_small```.
Верить табличке. Не поддерживается.

2024-06-10 06:59 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +```ADD FAMILY``` — создаёт новую группу колонок в строковой или колоночной таблице. Приведенный ниже код создаст в таблице ```series_with_families``` группу колонок ```family_small```.
Поправил.

2024-06-10 07:17 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +{% include [OLAP_not_allow](../../../../_includes/not_allow_for_olap.md) %}
Описание привёл, ссылку дал. Вопрос "В каких случаях надо использовать строковые таблицы с группами колонок, а не колоночные таблицы?" задал Звереву.

2024-06-10 07:26 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +Большинство параметров строчных и колоночных таблиц в {{ ydb-short-name }}, приведенных на странице [описания таблицы]({{ concept_table }}), можно изменить командой ```ALTER```.
Да, о нём :)

2024-06-10 07:31 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create_table.md
> +Также в блоке `WITH` можно задать TTL (Time to Live) — время жизни строки. [TTL](../../../../concepts/ttl.md) автоматически удаляет из строковой таблицы строки, когда проходит указанное количество се
Нет, кусок не лишний. Мы ведь можем при создании таблицы указать TTL? Можем! Вот я и дополнил доку.

2024-06-10 07:33 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/unique_distinct_hints.md
> +Непосредственно после `SELECT` возможно добавить [SQL хинты](../lexer.md#sql-hints) `unique` или `distinct` которые заявляют, что эта проекция порождает данные, содержащие уникальные значения в указа
Я увидел опечатки и поправил :) Предлагаю сохранить эти правки, чтобы уже были исправлены опечатки, а дальше можно править опечатки отдельными PR.

2024-06-10 08:09 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create_table.md
> +*  `TTL` — автоматическое фоновое удаление устаревших данных. Код ниже создаст колоночную таблицу с TTL:
Опять же нет. Это умышленное нанесение пользы -- дополнение CREATE TABLE.

2024-06-14 04:23 UTC, blinkov commented on ydb/docs/redirects.yaml
> +    to: /yql/reference/syntax/create_table/index.md
This is probably not necessary as `foo.md` and `foo/index.md` leads to the same URL.

2024-06-14 04:25 UTC, blinkov commented on ydb/docs/redirects.yaml
> +    to: /yql/reference/syntax/create_table/index.md
It is even harmful:
![Screenshot 2024-06-14 at 11 25 33](https://github.com/ydb-platform/ydb/assets/623861/932668db-ccac-4109-8c0f-fc333c058781)

2024-06-19 02:43 UTC, blinkov requested changes

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +При помощи команды ```ALTER TABLE``` можно изменить состав колонок и дополнительные параметры строковых и колоночных таблиц. В одной команде можно указать несколько действий. В общем случае команда `
давай при первом упоминании дадим тут ссылки про них в концепциях, правда вероятно под `{% if oss %}` придётся

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +При помощи команды ```ALTER TABLE``` можно изменить состав колонок и дополнительные параметры строковых и колоночных таблиц. В одной команде можно указать несколько действий. В общем случае команда `
точно ли этот контент не пролезет в YQL over YT? судя по `{{ backend_name }}` ниже может, а там строчные и колоночные таблицы устроены совсем по-другому

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +{% include [OLAP_not_allow](../../../../_includes/not_allow_for_olap.md) %}
Насколько я вижу тут получится совсем без `{% note %}`. В предыдущих итерациях ревью я предлагал сделать две версии этого include: одну просто с текстом, а вторую — с оборачиванием его в `{% note warning %}`. В этом кейсе потребовалась бы вторая версия, а первая — для случаев, если к стандартному тексту надо ещё подробностей приписать.

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
> +Механизм [групп](../../../../concepts/datamodel/table.md#column-groups) колонок позволяет увеличить производительность операций неполного чтения строк путем разделения хранения колонок строковой табл
```suggestion
Механизм [групп колонок](../../../../concepts/datamodel/table.md#column-groups) позволяет увеличить производительность операций неполного чтения строк путем разделения хранения колонок строковой таблицы на несколько групп. Наиболее часто используемый сценарий — организация хранения редко используемых атрибутов в отдельной группе колонок.
```

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/family.md
> +Колонки одной таблицы можно объединять в группы, для того чтобы задать следующие параметры:
строковой таблицы?

кстати, нам бы с предпочитаемой терминологией определиться бы, в соседнем https://github.com/ydb-platform/ydb/pull/5537 она несколько другая — наверное лучше голосом обсудить в следующий раз

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/secondary_index.md
> +Конструкция INDEX используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} на таблице:
```suggestion
Конструкция `INDEX` используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} на таблице:
```

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/secondary_index.md
> +Конструкция INDEX используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} на таблице:
ниже похоже про строчные таблицы, а в колоночных я слышал есть/будут как минимум skipping index, которые скорее всего похожим образом управляются

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/with.md
> +Например, такой код создаст таблицу с включенным автоматическим партиционированием по размеру партиции и предпочитаемым размером каждой партиции 512 мегабайт:
строковую

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/with.md
> +Также в блоке `WITH` можно задать TTL (Time to Live) — время жизни строки. [TTL](../../../../../concepts/ttl.md) автоматически удаляет из строковой таблицы строки, когда проходит указанное количество
вероятно это только в YDB работает и может зря просочиться в другие бекенды YQL

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
> +Изменение состояния строковой таблицы не отслеживается в рамках одной транзакции. Если таблица уже была изменена, для удаления данных в той же транзакции используйте [`DELETE ON`](#delete-on).
мне казалось это уже не актуально, недавно удаляли в https://github.com/ydb-platform/ydb/pull/5245/files — перепроверь, что рефакторингом ещё каких-нибудь изменений в main не откатишь

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +{% if feature_olap_tables %}
давай подвинем это куда-то ниже, уже после основного синтаксиса

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +{%endif%}
```suggestion
{% endif %}
```

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +  columns
плэйсхолдеры в угловые скобки

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +    PRIMARY KEY (a, b)
выше primary key был под if, вероятно тут тоже надо

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +- Создание колоночной таблицы
тоже вероятно зря пролезет как минимум в YQL over YT

2024-06-19 02:43 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +* [Группы колонок](family.md) (поддерживается только в строковых таблицах).
лучше сделать отдельные списки для строковых, колоночных и обоих видов таблиц, а не так уточнять

2024-06-25 02:13 UTC, blinkov commented on ydb/docs/ru/core/_includes/not_allow_for_olap_note.md
> +Поддерживается только для [строчных](../concepts/datamodel/table.md#strokovye-tablicy) таблиц. Поддержка функциональности для [колоночных](../concepts/datamodel/table.md#column-tables) таблиц находит
```suggestion
{% include [not_allow_for_olap](not_allow_for_olap.md) %}
```

2024-06-25 02:16 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/secondary_index.md
> +Конструкция `INDEX` используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} {% if backend_name == "YDB"
мне казалось колоночные таблицы так ещё не умеют?

2024-06-25 02:17 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/family.md
> +Доступные типы устройств хранения зависят от конфигурации кластера {{ ydb-short-name }}.
если сейчас некуда сослаться отсюда, то давай сделаем тикет описать как именно это конфигурируется

2024-06-25 02:18 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/temporary.md
> +{% if backend_name == "YDB" %}
а остальные бекенды разве это вообще умеют?

2024-06-25 02:20 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create/with.md
> +{% if backend_name == "YDB" %}
этот if вероятно должен быть выше, т.к. `AUTO_PARTITIONING_***` — тоже YDB-специфичные настройки

2024-06-25 02:24 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
> +Удалить данные из строковой и колоночной таблицы можно с помощью [TTL](../../../../concepts/ttl.md), который можно задать при [создании таблицы](../create_table/index.md) (`CREATE TABLE`) или при [из
хоть формально оно поддерживается в обоих видах таблиц, тут по идее первым делом стоит сделать акцент на колоночных — мол т.к. DELETE FROM пока не поддерживается, на правах временной замены используйте TTL

2024-06-25 02:26 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/discard.md
> +Вычисляет {% if select_command == "SELECT STREAM" %}[`SELECT STREAM`](../select_stream.md){% else %}[`SELECT`](../select/index.md){% endif %}{% if feature_mapreduce %}{% if reduce_command %}, [`{{ re
есть давнишняя проблема, что DISCARD в YDB совсем не поддерживается, что скорее всего до сих пор не починено — давай заодно под if уберём, если до сих пор оно так

2024-06-25 02:28 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/assume_order_by.md
> +Проверка сортированности результата `SELECT` по значению в указанном столбце или нескольких столбцах строковой или колоночной таблиц. Результат такого `SELECT`-а будет считаться сортированным, но без
```suggestion
Проверка сортированности результата `SELECT` по значению в указанном столбце или нескольких столбцах строковых или колоночных таблиц. Результат такого `SELECT`-а будет считаться сортированным, но без выполнения фактической сортировки. Проверка сортированности осуществляется на этапе исполнения запроса.
```

2024-06-25 02:29 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/distinct.md
> +Выбор уникальных строк из строковой или колоночной таблиц.
```suggestion
Выбор уникальных строк из строковой или колоночной таблицы.
```

2024-06-25 02:34 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/union.md
> +{% if backend_name == "YDB" %}
вероятно этот if стоит внести внутрь include, чтоб где-нибудь его не потерять случайно

2024-06-25 02:35 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/unique_distinct_hints.md
> +Непосредственно после `SELECT` возможно добавить [SQL хинты](../lexer.md#sql-hints) `unique` или `distinct` которые заявляют, что эта проекция порождает данные, содержащие уникальные значения в указа
почему тут кастомное уточнение, а не include?

2024-06-25 02:37 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/view.md
> +{% endnote %}
Второй вид view (12 строка ниже) разве тоже для колоночных не поддерживается?

2024-06-25 02:39 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/with.md
> +Задается после источника данных во `FROM` и используется для указания дополнительных подсказок использования строковых и колоночных таблиц. Подсказки нельзя задать для подзапросов и [именованных выра
в этой странице явно не хватает if'ов — большинство настроек ниже специфичны для YQL over YT, а эта правка скорее для YDB

2024-06-25 02:40 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/without.md
> +Исключение столбцов из результата запроса `SELECT *` к строковой или колоночной таблице.
похоже тут специально таблицы не упоминались — оно не привязано к конкретному источнику данных, например для подзапроса тоже работает

2024-06-25 02:41 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/update.md
> +{% include [OLAP_not_allow_text](../../../../_includes/not_allow_for_olap_text.md) %}
почему text, а не note?

2024-06-25 02:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/cdc.md
> +`ADD CHANGEFEED <name> WITH (option = value[, ...])` — добавляет [поток изменений (changefeed)](../../../../concepts/cdc) с указанным именем и параметрами.
`concepts/cdc` -> `concepts/cdc.md` здесь и ниже, иначе не понятно не вылезет ли тут где-то 404

2024-06-25 02:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/columns.md
> +{{ backend_name }} поддерживает возможность добавлять столбцы в {% if backend_name == "YDB" %} строковые и колоночные таблицы{% else %} таблицы {% endif %}, а также удалять неключевые колонки из табл
точно ли оно поддерживается в остальных бэкендах? раньше не было

2024-06-25 02:45 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +{% if backend_name == "YDB" %}
по идее вся эта фича YDB-only

2024-06-25 02:46 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/rename.md
> +Если в YQL запросе содержится несколько команд `ALTER TABLE ... RENAME TO ...`, то каждая будет выполнена в режиме автокоммита в отдельной транзакции. С точки зрения внешнего процесса, таблицы будут
звучит достойно `{% note warning %}`

2024-06-25 02:50 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +Тип таблицы при создании задается параметром `STORE` в блоке `WITH`, где `ROW` означает [строковую таблицу](../../../../concepts/datamodel/table.md), а `COLUMN` — [колоночную](../../../../concepts/da
тут по последнему предложению звучит как-будто пример далее будет про строковую таблицу, а он на самом деле про колоночную

2024-06-25 02:53 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +### Пример создания таблицы
текст ниже — описание каких-то особенностей под ифами, а не пример
видимо этот заголовок должен был быть ниже

2024-06-25 02:53 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +* [Группы колонок](family.md).
вторичных индексов и групп колонок в колоночных нет

2024-06-25 02:55 UTC, blinkov commented on ydb/docs/ru/core/_includes/not_allow_for_olap.md
> +Поддерживается только для [строчных](../concepts/datamodel/table.md#strokovye-tablicy) таблиц. Поддержка функциональности для [колоночных](../concepts/datamodel/table.md#column-tables) таблиц находит
выглядит полным дублем not_allow_for_olap_text.md — оставить только один

2024-06-25 23:44 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +Добавляет строки в {% if backend_name == "YDB" %}строковую таблицу{% else %}таблицу{% endif %}. {% if feature_bulk_tables %} Если целевая таблица уже существует и не является сортированной, операция
можно было б вынести слово «таблицу» за пределы if, тогда можно было б обойтись без else

2024-06-25 23:45 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/assume_order_by.md
> +Проверка сортированности результата `SELECT` по значению в указанном столбце или нескольких столбцах строковых или колоночных таблиц. Результат такого `SELECT`-а будет считаться сортированным, но без
по идее тут тоже специально не упоминались таблицы т.к. условно для подзапросов тоже актуально

2024-06-25 23:45 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/distinct.md
> +Выбор уникальных строк из строковой или колоночной таблицы.
тоже не важно откуда

2024-06-26 08:17 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +Добавляет строки в {% if backend_name == "YDB" %}строковую таблицу{% else %}таблицу{% endif %}. {% if feature_bulk_tables %} Если целевая таблица уже существует и не является сортированной, операция
Да, можно. Вынес.

2024-06-26 08:31 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/assume_order_by.md
> +Проверка сортированности результата `SELECT` по значению в указанном столбце или нескольких столбцах строковых или колоночных таблиц. Результат такого `SELECT`-а будет считаться сортированным, но без
Откатил

2024-06-26 08:32 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/distinct.md
> +Выбор уникальных строк из строковой или колоночной таблицы.
Откатил

2024-06-26 10:47 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/discard.md
> +Вычисляет {% if select_command == "SELECT STREAM" %}[`SELECT STREAM`](../select_stream.md){% else %}[`SELECT`](../select/index.md){% endif %}{% if feature_mapreduce %}{% if reduce_command %}, [`{{ re
видимо да + входящие ссылки тоже

2024-06-26 10:49 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +{% if backend_name == "YDB" %}
в теории есть ещё YQL over RTMR — если там тоже скрыто, то наверное и этот if не обязателен

хотя вообще я где-то предлагал его убрать внутрь not_allow_for_olap_note.md

2024-06-26 10:53 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/view.md
> +{% endnote %}
в YDB в этот синтаксис запихано явное использование вторичных индексов — странно, что совсем скрыто, но контент должен был бы быть и правда другой

2024-06-26 10:57 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/columns.md
> +{{ backend_name }} поддерживает возможность добавлять столбцы в {% if backend_name == "YDB" %} строковые и колоночные таблицы{% else %} таблицы {% endif %}, а также удалять неключевые колонки из табл
я бы ожидал, что в том месте откуда оно переехало были какие-нибудь if'ы вокруг этого текста — прошу перепроверить, но для надёжности уточнить у команды YQL тоже не помешает

2024-06-26 11:27 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/union.md
> +{% if backend_name == "YDB" %}
внутри include он точно так же приводил к тому, что note не показывается — просто проинклудилась бы пустота

2024-06-26 13:47 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/with.md
> +Задается после источника данных во `FROM` и используется для указания дополнительных подсказок использования строковых и колоночных таблиц. Подсказки нельзя задать для подзапросов и [именованных выра
Поправил

2024-06-26 13:56 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/columns.md
> +{{ backend_name }} поддерживает возможность добавлять столбцы в {% if backend_name == "YDB" %} строковые и колоночные таблицы{% else %} таблицы {% endif %}, а также удалять неключевые колонки из табл
В оригинале никаких ifов там нет, а в YT и RTMR ALTER TABLE вообще не представлен в доке.

2024-06-26 14:05 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +{% if backend_name == "YDB" %}
ALTER TABLE скрыт в YT и RTMR доках. Унести if backend в include мне не кажется хорошей идеей, условия как по мне должны быть наружи, чтобы сразу их видеть.

2024-06-26 14:08 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/select/union.md
> +{% if backend_name == "YDB" %}
Я пока оставлю так. Когда разобью на мелкие PR тогда поправлю. Сейчас объем правок ifо вокруг include кажется большим и не то чтобы критичным.

2024-06-26 17:46 UTC, Pseudolukian commented
Вынес SELECT отдельным PR: https://github.com/ydb-platform/ydb/pull/5995

2024-07-01 09:57 UTC, Pseudolukian commented
Вынес CREATE отдельным PR: https://github.com/ydb-platform/ydb/pull/6120

2024-07-02 07:38 UTC, Pseudolukian commented
EN версия SELECT: https://github.com/ydb-platform/ydb/pull/6090

2024-07-05 13:36 UTC, Pseudolukian commented
RU версия ALTER TABLE: https://github.com/ydb-platform/ydb/pull/6340

2024-07-09 11:24 UTC, Pseudolukian commented
Вынес INSERT, UPSERT, DELETE и другие DML в PR: https://github.com/ydb-platform/ydb/pull/6470

2024-07-17 15:32 UTC, closed without merging