Greenplum: fq proxy
ydb-platform/ydb pull request #5384
Opened 2024-06-10 09:57 UTC by skywalker-jpg

### Changelog entry 

...

### Changelog category 

* New feature

### Additional information

...

2024-06-10 13:25 UTC, vitalyisaev2 requested changes

2024-06-10 13:25 UTC, vitalyisaev2 commented on ydb/public/api/protos/draft/fq.proto
> +    bool secure = 7;
1. вот эти три строчки можно убрать
2. в предыдущих 6 строчках можно выстроить правильную порядковую нумерацию

2024-06-10 13:25 UTC, vitalyisaev2 commented on ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
> +                    PROTOCOL="NATIVE",
насколько я помню, в параметрах  GP нет протокола, проверь свой предыдущий PR

2024-06-10 13:26 UTC, skywalker-jpg commented on ydb/public/api/protos/draft/fq.proto
> +    bool secure = 7;
2. Точно ли, ибо я это у постарела взял, а у него она поломана почему-то

2024-06-10 13:41 UTC, vitalyisaev2 commented on ydb/public/api/protos/draft/fq.proto
> +    bool secure = 7;
точно

2024-06-10 14:12 UTC, uzhastik commented on ydb/public/api/protos/draft/fq.proto
> +    string database_name = 2 [(Ydb.length).le = 1024];
зачем нужно поле database_name ?

2024-06-10 14:31 UTC, vitalyisaev2 commented on ydb/public/api/protos/draft/fq.proto
> +    string database_name = 2 [(Ydb.length).le = 1024];
Имя базы данных внутри кластера. Всё по аналогии с PG

2024-06-10 14:44 UTC, uzhastik submitted a review, later dismissed

2024-06-10 15:01 UTC, dorooleg commented on ydb/core/fq/libs/common/util.cpp
> +            return GetBasicAuthMethod(setting.postgresql_cluster().auth());
почему тут pg auth?

2024-06-10 15:03 UTC, dorooleg commented on ydb/core/fq/libs/common/util.cpp
> +            return GetBasicAuthMethod(setting.postgresql_cluster().auth());
И в других местах тоже подозрительно

2024-06-11 09:43 UTC, dorooleg approved these changes

2024-06-11 09:54 UTC, uzhastik approved these changes

2024-06-14 08:14 UTC, vitalyisaev2 approved these changes

2024-06-14 08:14 UTC, merged