json hc metadata cache
ydb-platform/ydb pull request #5465
Opened 2024-06-11 22:36 UTC by StekPerepolnen

- YDB Import 597 2221b5c9d4887055279d8e5e336b944948a706cc
- Intermediate changes
- turn on ALL_SRCS in module if STYLE_CPP is called c4c2b0bd42afcef4a1f68be92e80e4e952970f69
- Intermediate changes
- contrib/libs/libpcap: generate bison headers by the means of ya.make ac109264a78f20e65d62068d51cb06c22ab43847
- Intermediate changes
- Add missing sysincl fe551e9e6b1b285dbbc3a9defbdc865a6fdc1112
- add implicit HEADERS(.) in STYLE_CPP 8c9a525df4a872daca7813c8ff82b140d749593c
- YT: Fix unused lock template parameter in SyncMap
- more cpp extensions 04b8e856256b5792e211be9506aba1c1d21f0181
- fix CLANG_TYDY for GTEST 539f9fa5134a084cd4e71512b2f08cc257bf4426
- temporary fix 1d65ab0a1fe5bec1cf34e97c16e4babc53be0c21
- Enable new UIDs for all sanitizer builds (build/conf/settings.conf)
- Automatic release build for ya_bin3, os_ya, ya_bin, test_tool, os_test_tool
- feat(nots/cli, builder): copy patches to `pnpm install` directory e71f3730f57e720d6efb18f42adbd2006606844e
- Update contrib/restricted/boost/serialization to 1.85.0 2806d67a9477e3d51376cd3e16a9b5d6b785806b
- YT-21502, YT-21634: AresDNSResolver refactor
- Update contrib/restricted/boost/function to 1.85.0 e0f2ba4eb69ee69baef77b3eccd7b950eb95c58a
- Cosmetics d1095d949cece50ea82a07a544cf10ef08a02583
- In yson struct, prefer iterating over SortedParameters_ for determinism. 0032b463de1c82891fd7b26ae5b2f538c88e0d01
- Normalize 'WITH Bison-exception' spelling 8b2fb6d45dd388298c3677e8c0c91486fdb94061
- Improve support for DontSerializeDefault; Add DontSerializeDefault to fix snapshot divergence when rolling 23.2 964925e3330bb2bc336b4c2721370bbd33f05f34
- YT: Add join expression to query builder ef0cf75a2639c295e45bcb66c3af27554dc3586c
- New eslint suite: remove unneeded old references bb11084ac0472d18fb06fe65a35363f2e704e1ab
- YT-21434: Make sure system invokers are active before shutdown 1d45d044e90ad310e6e002f8446320e56dcdf6fb
- Intermediate changes
- CMake generator based on Jinja generator 99902937b544f5d8150a5c6132861e1bb52d3ced
- Fix TCP connection tag e9195292698f6465508db3182b20619c915c1d84
- apply clang-format to build/scripts/c_templates/svn_interface.c 81235399e4c6e917bcabe929f3897deeb2232bbc
- External build system generator release 90
- Update contrib/libs/backtrace to 2024-05-01 dce1a2d8375df9b3baf32973ca156e03dd52cdd0
- Intermediate changes
- Intermediate changes
- [build/scripts/link_exe.py] Do not output warnings when creating `.a` files d9beae52f9300e65eddec8c2b865f132ea6b5833
- YT-20429: Increase maximum number of key columns in dyntables to 128 872de8f38d12966355d1a44327a80fb6ede7e34e
- Fallback to a regular reshard from reshard with slicing if too many chunks have been found 47942740235036bf82beafb3cfbb952d098b4f9b
- Intermediate changes
- Simplify licenses.json layout
- Intermediate changes
- [util] Implement TryGetEnv and UnsetEnv functions
- Fix patching cpp proto
- Update contrib/restricted/boost/property_tree to 1.85.0 d063d388d6659a94f4c78cf5de3275260939bb62
- Revert commit rXXXXXX, Enable new UIDs for all sanitizer builds (build/conf/settings.conf) 869037e1c5f3c8bb6468e9d636b044f167bba6dc
- New version of the tld SKIP_CHECK SKIP_REVIEW 00e7d577abb2a5bc75795293bf112baa41fcad78
- YT-21453: Add request proxing a89e46aed68565a4410b7f1354505ffaeb92536d
- Remove unused vector.h in library/cpp/http/io/headers.h 3a95ba7ea18b67eb6bd8d04631814456f4881138
- Sync contrib/tools/bison layout with upstream 59379f119eb5f2fd036edea64923ff53b96c9028
- Update contrib/libs/apache/orc to 2.0.1 855bd01a1b384d08c59ee86c6b493ea32190ef19
- Support cross-platform building on host macOS arm64 to target macOS x86_64. 1ee76574376bb2910f9e1b91f9b527b13bb392d3
- YT-21642: Fix and improve attribute based access control
- YT-21547: Cosmetics d7289b88c1b52abc27589ed0480714656864f213
- Move bison/m4 and bison/induced out of contrib/tools/bison 520961d4315ab4738f60613278b7e63765341b85
- YT-21558: Allow config unregistered methods 4738445240b36d24604dbf9955309608fc9568df
- Flatten bison/gnulib/src to bison/lib to match upstream layout 2f47b5eab59c8031971bd995b703c854fd6f106d
- Intermediate changes
- Intermediate changes
- YT-21744: Early draft of kafka proxy af83e035a87a6ca819fd272695041701f3639768
- Intermediate changes
- YT-21613: Add path in permission error for queue/consumer 924b35169e93d0a6cf268fa4bd556a12e3477762
- minor fix in util path
- Automatic release build for ymake, os_ymake
- Intermediate changes
- Update contrib/restricted/uriparser to 0.9.8 13a17d4e90a208dbf899efe8b92134d3ae98631d
- Update contrib/python/Jinja2/py3 to 3.1.4 264ae85f13f4a11226be8b846079da1aece08b50
- Remove unnecessary patch 1e746c21e253120adc9124771d9fb797a8c44da0
- Remove licenses listings from license.conf 5a8f5276e9eecbb6ee7525fa40643bc16ce21c5d
- Intermediate changes
- Switch to std::format to fix -Wformat e2d3a54377ea6268a39c35989c259720c10edefa
- YT-21402: Fibers refactoring pt.2: Slightly better encapsulation of fiber introspection part and moved fls back to switch handler
- Intermediate changes
- Update contrib/libs/libgit2 to 1.8.0 7e13d287e0e8354abf4ae4c2ff885ddd4cc2dc74
- YT: Add FormatValue for std::source_location
- Duplicate bison/lib (gnulib) to m4/lib as they actually need to be different 597ee3bf4ec17244e6ef615a1ec10491798e18fe
- Intermediate changes
- Don't use per-TLS anchor counters 85eb5ffdc79771c842f049e9392902ac6868cece
- Upgrade to `checkstyle-10.16.0` 5133d8ef6a9b0e4932c8a5606ed4d396db05bcf1
- Add darwin-x86_64 profile to generator.toml. 797a63585c218caba357e08ce955ea4e944e1e1c
- [kafka] YT-21789: Support authentication
- Drop unused gnulib srcs from contrib/tools/bison 231e84067197fe69ac80bee1f6cd14648ba7f18c
- Phoenix v2
- Fix patch e871e4c16da73fb080536ac9b70a5086517e67bf
- Remove more of unused gnulib sources from contrib/tools/bison 6f612070e58cd7e6c16b0d090a809077b0a454ff
- Intermediate changes
- YT-21446: Remove OS part of python UDFs from arcadia d587f95edf5636edfae6672d36f57c8a15f5f3e0
- Intermediate changes
- Use protoc_old for py2 and only for it b33d3a4c9adc28d2a9f5af78d52ed54fcc6df41b
- Intermediate changes
- [kafka] YT-21744: Remove useless protocol methods
- Intermediate changes
- Automatic release build for ya_bin3, os_ya, ya_bin, test_tool, os_test_tool
- remove redundant fields from dart for custom linters
- split onadd_ytest plugin
- Add contrib/python/prettytable 8db8e29fdff582b08a53f0952a29362e0c760185
- YDB Import 599 45e316d94adcc8bf10259ec56968193d86f2947f
- split add_check plugin
- Apply to global loggers in yt/yt 2099bd8ce11fc2c9e0566ebafbb9fddf4dad5141
- split pytestbin and exectest
- YT-21581: Force rack awareness for erasure parts d2f0532819445a37171ba0e411651086bbf6fd66
- Intermediate changes
- YT-21692: Decrease probing requests in replication reader f0710477546e5c8f2c1675d5065bf403e0bc6e86
- Add EProcessErrorCode::CannotStartProcess
- Remove more unused gnulib sources 7dedc56d9c3dca7ed4ff1387f800c2f60338c0ee
- New version of the tld SKIP_CHECK SKIP_REVIEW 39cfa31a7e313cc0a2b62e3c4836db4b6bf04dde
- test d394e1d4a37d8c9b93bc4c1feab8362a3488f41e
- Do not refer to a non-existent credits 727107e24b3466896fcd6ce175edb00df2723786
- Use mirrored Cypress tx in tests 447630a98133ef6f60263ea998721a86e0affead
- Fix account metrics breaking when adding a new account 92e7904dddf33b5b8ec117a73c0bfdf1b774441b
- YDB Import 600 58488ba7bf42f414ab6c282a2aee26d5e26211f5
- Integrated checks (#4800)
- Make max commit size configurable with icb (#4774)
- Fix ReadLogContinue race on stop (#4791)
- Drop sysincls for non-standard <unlocked-io.h> 64e562813ca05442ab1345644308a7bb37a4f3b7
- YQL-18464: Fix Remove UDFs for NonASCII input (#4789)
- Automatic release build for ymake, os_ymake
- YDBDOCS-188 FluentBit - not just K8s (#4635)
- [cms.proto] increase default DisabledNodesRatioLimit (#4770)
- YDBDOCS-690: introduce the restart article for Ansible clusters (#4807)
- Implement ListTop/ListTopSort builtins (#4231)
- Revert file cycles detection (#4802)
- YQL-18463: Adjust BadFromPythonLong for Python  [...]

2024-06-12 11:21 UTC, vporyadke submitted a review, later dismissed

2024-06-12 11:37 UTC, vporyadke submitted a review, later dismissed

2024-06-13 07:36 UTC, adameat requested changes

2024-06-13 07:36 UTC, adameat commented on ydb/core/viewer/json_healthcheck.h
> +    THolder<NHealthCheck::TEvSelfCheckRequest> MakeSelfCheckRequrest() {
typo

2024-06-13 07:36 UTC, adameat commented on ydb/core/viewer/json_healthcheck.h
> +        request->Request.set_return_verbose_status(FromStringWithDefault<bool>(params.Get("verbose"), false));
I think it would be better to set parameters only when they actually were specified in the call.
but here you force them to some defaults.

2024-06-13 07:36 UTC, adameat commented on ydb/core/viewer/json_healthcheck.h
> +            Send(Event->Sender, new NMon::TEvHttpInfoRes(Viewer->GetHTTPBADREQUEST(Event->Get()), 0, NMon::IEvHttpInfoRes::EContentType::Custom));
maybe some additional diagnostics could be helpful

2024-06-13 12:02 UTC, adameat approved these changes

2024-06-13 13:46 UTC, merged