support state argument in process & dynamic cast to impl
ydb-platform/ydb pull request #5523
Opened 2024-06-13 14:02 UTC by fedor-miron

### Changelog entry 

Support passing UdfKernelState to UDF Arrow kernels.
Allow to pass reader and builder types to UnaryKernelExec and BinaryKernelExec to avoid virtual calls and enable autovectorization.

### Changelog category 

* Performance improvement

2024-06-14 16:27 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
> +    const IValueBuilder& GetValueBuilder() {
и где оно используется? непонятна цель изменений с pgbuilder

2024-06-14 16:28 UTC, vitstn requested changes, later dismissed
valuebuilder

2024-06-14 16:30 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
> +            Process(item, state, [&](auto out) {
зачем в process весь state? это выглядит утечкой имплементации

2024-06-14 16:39 UTC, igormunkin requested changes
@fedor-miron, thanks for the patch! Besides the nits below, I ask you to provide a PR where it's used, if you have one.

2024-06-14 16:39 UTC, igormunkin commented on ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
>  struct TBinaryKernelExec {
It's worth adding `static_assert`s similar to the ones in `TUnaryKernelExec`.

2024-06-14 16:39 UTC, igormunkin commented on ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
> +    const IValueBuilder& GetValueBuilder() {
Discussed offline: let's move these changes to the separate PR.

2024-06-27 15:46 UTC, igormunkin submitted a review, later dismissed
@fedor-miron, thanks for the fixes! LGTM.

2024-06-27 16:06 UTC, igormunkin approved these changes

2024-06-28 14:47 UTC, merged