Yq 3322 row dispatcher
ydb-platform/ydb pull request #5544
Opened 2024-06-14 07:29 UTC by kardymonds

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-29 12:19 UTC, yumkam commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    auto rand = counter++ % RowDispatchers.size();
Hmm. Global (and unsynched) variable. (Well, we accept any random value here, even if somehow counter would duplicate or messed up by MT, so should be ok, and using atomic is overkill, but worth comment?)

2024-08-29 12:23 UTC, yumkam commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    std::advance(it, rand);
nit: either `.begin()`/`.end()`  or `std::begin()` consistently

2024-08-29 12:32 UTC, yumkam commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    }
nit: iterates over array even with logging disabled (... but does not affect complexity, we iterate over it anyway below)

2024-08-29 15:11 UTC, yumkam commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> +                ui64& offset = PartitionToOffset[TPartitionKey{partitionProto.GetCluster(), partitionProto.GetPartition()}];
nit: `.emplace()`?

2024-08-30 06:24 UTC, kardymonds commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> +                ui64& offset = PartitionToOffset[TPartitionKey{partitionProto.GetCluster(), partitionProto.GetPartition()}];
Тут какая то сложная логика (как будто в стейте может быть несколько одинаковых партиций). Я её просто скопировал из [dq_pq_read_actor.cpp](https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp#L206).

2024-08-30 07:38 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    }
Пофиксил, всё пишу в один лог

2024-08-30 07:41 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    auto rand = counter++ % RowDispatchers.size();
Coordinator один на ноду.  Но всё равзно убрал static

2024-09-02 10:07 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    std::advance(it, rand);
fixed

2024-09-02 17:33 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +            continue;
нужны какие-то подсказки, которые указывают на то что этот код не зациклится. например, верифайки

2024-09-02 17:33 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    LOG_ROW_DISPATCHER_DEBUG("Send  TEvCoordinatorResult to " << ev->Sender);
лишний пробел после Send

2024-09-03 06:51 UTC, uzhastik commented on ydb/public/api/protos/draft/fq.proto
> +    bool use_row_dispatcher = 6;
Хотя можно и на коннекшене держать. Важно склеивать схемы для одинаковых стримов и не склеивать схемы для разных стримов

2024-09-03 13:41 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +            continue;
Добавил Y_ENSURE()

2024-09-03 13:41 UTC, kardymonds commented on ydb/library/yql/providers/pq/async_io/ya.make
> +    dq_pq_rd_read_actor.cpp
fixed

2024-09-03 13:41 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    LOG_ROW_DISPATCHER_DEBUG("Send  TEvCoordinatorResult to " << ev->Sender);
fixed

2024-09-03 13:41 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    while(true) {
fixed

2024-09-03 13:41 UTC, kardymonds commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +            ythrow yexception() << "ErrUnimplementedTypedValue";
Добавил

2024-09-03 13:41 UTC, kardymonds commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +    TString FormatValue(Ydb::TypedValue value) ;
fixed

2024-09-04 07:07 UTC, kardymonds commented on ydb/library/yql/providers/common/dq/yql_dq_integration_impl.h
> +    void FillSourceSettings(const TExprNode& node, ::google::protobuf::Any& settings, TString& sourceType, size_t, TExprContext&) override;
Почему это должно развалить билд? Эта же фукнция вызывается только в conrib/ydb (а тут я всё поправил)

2024-09-04 14:01 UTC, kardymonds commented on ydb/public/api/protos/draft/fq.proto
> +    bool use_row_dispatcher = 6;
Разные стримы не пересекаются. В одном коннекшене может быть любое количество топиков и они работают независимо.

2024-09-04 16:55 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +            return NFq::EncloseAndEscapeString(ToString(value.value().bytes_value()), '"');
мне кажется, что в обоих case не нужно вызывать ToString

2024-09-04 17:02 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +            continue;
как-то непонятно все равно. мы ищем по циклическому буферу первый connected диспатчер? то есть будет исключение, если все диспатчеры disconnected? такое возможно? как мы обработаем исключение?

2024-09-04 17:04 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +            ythrow yexception() << "UnimplementedExpression, payload_case " << static_cast<ui64>(expression.payload_case());
рекомендую использовать throw вместо ythrow, чтобы в ошибке не было пути к исходному файлу. юзеру такое показывать не надо

2024-09-04 17:04 UTC, uzhastik commented on ydb/library/yql/dq/actors/common/ya.make
> +    ydb/library/yql/dq/actors/protos
sort plz

2024-09-06 11:33 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/events/data_plane.h
> +            Record.MutableSource()->CopyFrom(sourceParams);
если типы протобуфов совпадают, то лучше присваивание использовать. CopyFrom принимает Message&, то есть типы не проверяет в момент компиляции

2024-09-06 11:33 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/events/ya.make
> +    ydb/core/fq/libs/events
sort plz

2024-09-06 11:34 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +static const char* OffsetFieldName = "_offset";
используй анонимные неймспейсы и не используй static

2024-09-06 11:34 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +    explicit TFilterInputConsumer(
explicit избыточен

2024-09-06 11:39 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +    [[maybe_unused]]    NYql::NPureCalc::IWorker* Worker;
аннотация как будто лишняя

2024-09-06 11:40 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +        : LogPrefix("JsonFilter: ")
у тебя этот префикс в нескольких местах задается. давай поменьше таких констант ;)

2024-09-06 11:41 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +static const ui64 TimeoutDurationSec = 3;
static старайся не использовать. он тут лишний

2024-09-06 11:42 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +        INIT,
в enum class нормально использовать PascalCasing

2024-09-06 11:45 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +    LogPrefix = LogPrefix + " " + SelfId().ToString() + " ";
какие-то танцы вокруг LogPrefix, давай попроще сделаем. в бутстрапе задаем префикс:
```
LogPrefix = TStringBuilder() << "TLeaderElection " << SelfId() << " ";
```

2024-09-06 11:48 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/protos/ya.make
> +    ydb/library/yql/dq/actors/protos
sort plz

2024-09-06 11:48 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    TRowDispatcherMetrics(const ::NMonitoring::TDynamicCounterPtr& counters)
вот тут полезен explicit

2024-09-06 11:49 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        bool AddBearerToToken;
старайся инициализировать все скалярные поля класса

2024-09-06 11:50 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        TMap<TActorId, SessionInfo> Sessions;                         // key - TopicSessionId
в ключе actorId, а в комменте sessionId. тут нет ошибки?

2024-09-06 11:50 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    void Handle(NActors::TEvents::TEvUndelivered::TPtr &ev) ;
амперсанд прижимаем влево к типу

2024-09-06 11:51 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    LOG_ROW_DISPATCHER_DEBUG("Coordinator changed, new leader " << ev->Get()->CoordinatorActorId);
давай старый id напишем в лог? и точно ли он сменился? он может остаться старым? ни к каким проблемам это не приведет?

2024-09-06 11:52 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    LOG_ROW_DISPATCHER_DEBUG("TEvUndelivered, Reason: " << ev->Get()->Reason);
может, лучше в одну строчку лога записать. а не в две?

2024-09-06 11:53 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    Schedule(TDuration::Seconds(1), new NActors::TEvents::TEvWakeup());
тротлить wakeup не надо? много же может нагенериться таких ивентов. можно в полете только один разрешать

2024-09-06 11:54 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        ev->Get()->Record.GetSource().GetEndpoint(),
положи GetSource() в переменную, тогда копипастить меньше придется, код компактнее будет

2024-09-06 11:54 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        LOG_ROW_DISPATCHER_ERROR("Сonsumer already exist, ignore StartSession");
exists

2024-09-06 11:55 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        LOG_ROW_DISPATCHER_ERROR("TEvGetNextBatch: wrong seq num from" << ev->Sender.ToString() << ", seqNo" << seqNo << ", ignore message");
после from нужен пробел

2024-09-06 11:56 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +        LOG_ROW_DISPATCHER_DEBUG("Wrong consumer");
какую полезную инфу надо дописать. скорее всего key надо сдампить

2024-09-06 11:59 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +            , Value(value)
std::move()

2024-09-06 12:02 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    TVector<TString> result;
и функция не связана с классом. можно ее в начале файла в анонимный неймспейс положить

2024-09-06 12:05 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        } catch (const yexception& e) {
лови std::exception. yexception нужен для создания и удобного форматирования сообщения об ошибке

2024-09-06 12:05 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    LOG_ROW_DISPATCHER_TRACE("TEvDataAfterFilteration,  " << ev->Get()->ReadActorId.ToString());
вместо двух пробелов можно написать "details: " с одним пробелом =)

2024-09-06 12:06 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        LOG_ROW_DISPATCHER_ERROR("Wrong ClientSettings");
текст ошибки смущает. он в тему?

2024-09-06 12:08 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +            LOG_ROW_DISPATCHER_TRACE("Too much used memory (" << UsedSize << " bytes), stop reading from yds");
насколько эта ошибка фатальна? она ретраится ?

2024-09-06 12:09 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    TString message = (TStringBuilder() << "Read session to topic \"" << "\" was closed");
скобки избыточны

2024-09-06 12:09 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    TString message = (TStringBuilder() << "Read session to topic \"" << "\" was closed");
пропустил имя топика

2024-09-06 12:10 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    issues.AddIssue(TStringBuilder() << "Read session to topic \"" << "\" was closed: " << ev.DebugString());
имя топика хотел в сообщение добавить
давай копипасту уберем с формированием текста ошибки

2024-09-06 12:12 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    i64 usedSpace = 0;
давай коимпктнее напишем:
```
const i64 usedSpace = data.size();
NYql::NUdf::TUnboxedValuePod item = NKikimr::NMiniKQL::MakeString(NYql::NUdf::TStringRef(data.Data(), data.Size()));
```

2024-09-06 12:14 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        auto& clientInfo = (Clients.emplace(
скобки избыточны
```
auto& clientInfo = Clients.emplace(...)->second;
```

2024-09-06 12:16 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +                GetVector(ev->Get()->Record.GetSource().GetColumns()),
ты же выше уже вызывал GetVector, давай не будем то же самое делать. положи результат в переменные

2024-09-06 12:17 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        FatalError("Adding new client failed");
используй CurrentExceptionMessage(), чтобы хоть какую-то инфу об исключении сообщить

2024-09-06 12:19 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    ythrow yexception() << "FatalError";    // To exit from current stack and call once PassAway() in HandleException().
прямо тут и вызывай PassAway,  зачем же исключение кидать

2024-09-06 12:21 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
> +        if (Filter) {
if избыточен
```
Filter = {};
```

2024-09-06 12:22 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
> +    void MakeFilter(
сложные объекты старайся передавать по const&. и в тестах тоже

2024-09-06 12:23 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/ut/ya.make
> +    coordinator_ut.cpp
sort plz

2024-09-06 12:23 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/ya.make
> +    ydb/library/actors/core
sort plz

2024-09-06 12:25 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/ya.make
> +    events
это избыточно, у тебя же есть peerdir туда

2024-09-06 12:26 UTC, uzhastik commented on ydb/library/services/services.proto
> +    YQ_ROW_DISPATCHER = 3100;
давай префикс YQ_ в коде не использовать. лучше пусть везде будет FQ_

2024-09-06 12:26 UTC, uzhastik commented on ydb/library/yql/dq/actors/common/retry_queue.cpp
> +static const ui64 PingPeriodSeconds = 2;
static не нужен, у констант внутреннее связывание

2024-09-06 12:29 UTC, uzhastik commented on ydb/library/yql/providers/common/dq/yql_dq_integration_impl.h
> +    void FillSourceSettings(const TExprNode& node, ::google::protobuf::Any& settings, TString& sourceType, size_t, TExprContext&) override;
точно, вне contrib/ydb он не вызывается и не реализуется

2024-09-06 12:30 UTC, uzhastik commented on ydb/library/yql/providers/common/pushdown/physical_opt.cpp
> +static TPredicateNode SplitForPartialPushdown(
убирай код в анонимный неймспейс вместо static

2024-09-06 12:35 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +        return left + operation + right;
мне кажется, что важно скобки поставить, иначе приоритет операций может измениться

2024-09-06 14:09 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +        return left + operation + right;
тут тоже скобки могут быть важны

2024-09-06 14:09 UTC, uzhastik commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +                    return {};
со сдвигом проблема

2024-09-06 14:11 UTC, uzhastik commented on ydb/library/yql/providers/pq/proto/dq_io.proto
> +import "ydb/public/api/protos/ydb_value.proto";
импорт как будто не нужен

2024-09-06 14:14 UTC, uzhastik commented on ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
> +        } else {
else избыточен

2024-09-06 14:30 UTC, uzhastik commented on ydb/tests/fq/pq_async_io/ut/ya.make
> +    dq_pq_rd_read_actor_ut.cpp
sort plz

2024-09-09 07:54 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    ythrow yexception() << "FatalError";    // To exit from current stack and call once PassAway() in HandleException().
Мы тут может быть внутри цикла и тогда PassAway вызовется несколько раз и внутри PassAway упадет на ассерте.

2024-09-09 11:55 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    TString message = (TStringBuilder() << "Read session to topic \"" << "\" was closed");
Добавил имя топика

2024-09-09 11:55 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    issues.AddIssue(TStringBuilder() << "Read session to topic \"" << "\" was closed: " << ev.DebugString());
Добавил / убрал

2024-09-09 11:56 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        auto& clientInfo = (Clients.emplace(
Поправил

2024-09-09 11:56 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        FatalError("Adding new client failed");
Добавил CurrentExceptionMessage()

2024-09-09 11:56 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
> +        if (Filter) {
Убрал

2024-09-09 11:56 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/ya.make
> +    ydb/library/actors/core
fixed

2024-09-09 11:57 UTC, kardymonds commented on ydb/library/services/services.proto
> +    YQ_ROW_DISPATCHER = 3100;
поправил на FQ_

2024-09-09 11:57 UTC, kardymonds commented on ydb/library/yql/dq/actors/common/retry_queue.h
> +    TRetryEventsQueue() {};
убрал

2024-09-09 11:58 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    LOG_ROW_DISPATCHER_TRACE("TEvDataAfterFilteration,  " << ev->Get()->ReadActorId.ToString());
убрал проблел

2024-09-09 11:59 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        LOG_ROW_DISPATCHER_ERROR("Wrong ClientSettings");
поправил

2024-09-09 12:26 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +            LOG_ROW_DISPATCHER_TRACE("Too much used memory (" << UsedSize << " bytes), stop reading from yds");
Это не ошибка, это backpressure на стыке TopicApi / TopicSession

2024-09-09 12:28 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +                GetVector(ev->Get()->Record.GetSource().GetColumns()),
сделал через переменную

2024-09-09 12:28 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    } catch (NYql::NPureCalc::TCompileError& e) {
fixed

2024-09-09 12:29 UTC, kardymonds commented on ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
> +        } else {
убрад

2024-09-09 12:29 UTC, kardymonds commented on ydb/library/yql/providers/pq/proto/dq_io.proto
> +import "ydb/public/api/protos/ydb_value.proto";
убрал

2024-09-09 12:29 UTC, kardymonds commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +                    return {};
поправил сдвиг

2024-09-09 12:30 UTC, kardymonds commented on ydb/library/yql/dq/actors/common/retry_queue.cpp
> +static const ui64 PingPeriodSeconds = 2;
убрал static

2024-09-09 12:36 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/ut/ya.make
> +    coordinator_ut.cpp
кажется уже было отсортировано

2024-09-09 13:16 UTC, kardymonds commented on ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
> +        return left + operation + right;
Здесь извне скобки ставит Conjunction / Disjunction / Negation, поэтому тут не нужно. Да и код я в основном скопипастил с коннектора (кусок на go)

2024-09-10 13:00 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +            continue;
тут не вижу изменений

2024-09-10 13:08 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +                std::memcpy(str.Data(), v.data(), v.size());
избегай низкоуровневых функций, лучше воспользуйся конструктором TStringValue, который принимает TStringBuf

2024-09-12 10:05 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +            continue;
Локальный RowDispatcher всегда приконнекчен. До Y_ENSURE не должны никогда дойти

2024-09-12 13:32 UTC, dorooleg requested changes

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    string Token = 3;
Эти же поля есть внутри `TDqPqTopicSource`

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    using ConsumerSessionKey = std::pair<TActorId, ui32>;                   // ReadActorId / PartitionId
Здесь тоже возможно ли в struct завернуть?

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
> +    LOG_ROW_DISPATCHER_DEBUG("TEvUndelivered, Reason: " << ev->Get()->Reason);
Угу, потом грепать будет проще.

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +        if (auto* e = std::get_if<NYdb::NTopic::TReadSessionEvent::TDataReceivedEvent>(&*event)) {
в s3 read_actor был похожий код для разгребания через struct с operator() Может тут аналогичный стиль заиспользовать?

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/topic_session.cpp
> +    ythrow yexception() << "FatalError";    // To exit from current stack and call once PassAway() in HandleException().
Текст ошибки еще exception плохой, нужно str.Str сюда тоже приписать и по месту его запринтить

2024-09-12 13:32 UTC, dorooleg commented on ydb/core/fq/libs/ydb/schema.cpp
> +        SCHEMA_LOG_DEBUG("Schedule next attempt, delay " << delayMaybe->ToString());
Это точно DEBUG, а не TRACE?

2024-09-12 13:32 UTC, dorooleg commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_checkpoints.cpp
> +    return sourceType == "PqSource" || sourceType == "PqRdSource";
А можно как-то не вводить новый SourceType? А где нужно влажок передать, как параметр source

2024-09-12 13:32 UTC, dorooleg commented on ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
> +                ui64& offset = PartitionToOffset[TPartitionKey{partitionProto.GetCluster(), partitionProto.GetPartition()}];
А мы можем задедупить логику на сколько это возможно? Переживаю что мы можем потом фиксить что-то в dq_pq_read_actor, а оно не будет попадать в fq_pq_rd_read_actor и наоборот

2024-09-13 09:14 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +                actorSystem->Send(actorId, new TEvPrivate::TEvAcquireSemaphoreResult(future.GetValue()));
Могу еще порекомендовать в коде проверить или захендлить этот наверняка. Иначе потом сложно искать потерянные exception :(

2024-09-13 09:16 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +    Schedule(TDuration::Seconds(TimeoutDurationSec), new TEvPrivate::TEvTimeout());
На старте же это может добавить тормоза размером с TimeoutDurationSec из-за какого нибудь сетевого затупа. Или мы и так ждем сколько-то врмени пока read_actor подключатся и этот TimeoutDurationSec будет не заметен на их фоне?

2024-09-14 21:48 UTC, kardymonds commented on ydb/core/fq/libs/ydb/schema.cpp
> +        SCHEMA_LOG_DEBUG("Schedule next attempt, delay " << delayMaybe->ToString());
Да, тут все логи DEBUG. (макроса с Trace даже нет )

2024-09-16 10:05 UTC, kardymonds commented on ydb/library/yql/dq/actors/compute/dq_compute_actor_checkpoints.cpp
> +    return sourceType == "PqSource" || sourceType == "PqRdSource";
Да, убрал этот новый sourceType,  добавил флажок в  TDqPqTopicSource

2024-09-16 14:36 UTC, dorooleg requested changes

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/config/protos/row_dispatcher.proto
> +message TRowDispatcherCoordinatorConfig {
У нас уже есть похожий конфиг для kesus: https://a.yandex-team.ru/arcadia/contrib/ydb/core/fq/libs/config/protos/rate_limiter.proto?rev=r14879806#L11-21
Может по аналогии назвать, что думаешь? Database/CoordinationNodePath

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/config/protos/row_dispatcher.proto
> +    uint64 TimeoutBeforeStartSessionSec = 2;
У нас есть еще вариант через строчку задавать таймауты. Можно писать "5m" и т.д. https://a.yandex-team.ru/arcadia/contrib/ydb/core/fq/libs/config/protos/control_plane_storage.proto?rev=r14879806#L36
Тут уже на твое усмотрение, так-как с Sec тоже есть

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
> +        return NActors::TlsActivationContext->ExecutorThread.RegisterActor(actorPtr.release(), NActors::TMailboxType::HTSwap, Max<ui32>());
```
TActivationContext::Register
```

Штука конечно опасная. Если когда нибудь вызовут RegisterTopicSession не из AS, то будет краш

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +        AddField(structMembers, col, "String");
А почему тут всегда тип String, других типов не может быть в RD?

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +            TFilterInputSpec(MakeInputSchema(columns)),
Еще для watermark есть специальные колонки, они здесь в общей схеме колонок будут учтены?

2024-09-16 14:36 UTC, dorooleg commented on ydb/core/fq/libs/row_dispatcher/protos/events.proto
> +    string Token = 3;
Еще же есть addBearerToToken. Почему не использовать эти поля из Source?

2024-09-16 15:56 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
> +        return NActors::TlsActivationContext->ExecutorThread.RegisterActor(actorPtr.release(), NActors::TMailboxType::HTSwap, Max<ui32>());
не лучше ли явным образом сюда передать as? в конструктор или в метод

2024-09-16 15:56 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +        LeaderChangedCount = Counters->GetCounter("LeaderChangedCount");
оба сенсора должны быть deriv?

2024-09-16 16:01 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +    RowDispatchers[actorId].Connected = true;
давай поиск по ключу actorId один раз делать, а не два. еще понятнее будет здесь сделать emplace с нужным value

2024-09-16 16:02 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/coordinator.cpp
> +        info.Connected = false;
тут можно сделать return?

2024-09-16 16:06 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +            TFilterInputSpec(MakeInputSchema(columns)),
это вряд ли, пока вотермарками не занимаемся

2024-09-16 16:07 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_filter.cpp
> +    TString GetSql() {
можно сделать const

2024-09-16 16:09 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_parser.cpp
> +        if (!udfDir.empty()) {
это что-то ненужное. udfs у нас загружены в процесс

2024-09-16 16:09 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_parser.cpp
> +    TString GetSql() {
можно сделать конст

2024-09-16 16:09 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/json_parser.cpp
> +        str << R"($json = SELECT CAST(data AS Json) as `Json`, )" << OffsetFieldName << " FROM Input;";
R" тут не нужен, затрудняет чтение

2024-09-16 16:11 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +        const TString tenant,
тут амперсанд нужен или const лишний

2024-09-16 16:13 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +        LOG_ROW_DISPATCHER_ERROR("Schema created error " << ev->Get()->Result.GetIssues());
created-> creation ?

2024-09-16 16:14 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +        LOG_ROW_DISPATCHER_ERROR("StartSession fail, " << result.GetIssues());
StartSession -> Create session ?

2024-09-16 16:14 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +        LOG_ROW_DISPATCHER_ERROR("Acquired fail " << result.GetIssues());
Semaphore acquire fail

2024-09-16 16:16 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +    Y_ABORT_UNLESS(description.GetOwners().size() == 1, "To many owners");
To -> Too

2024-09-16 16:16 UTC, uzhastik commented on ydb/core/fq/libs/row_dispatcher/leader_election.cpp
> +    Y_ABORT_UNLESS(description.GetOwners().size() == 1, "To many owners");
нормально ли тут падать?

2024-09-16 16:35 UTC, uzhastik commented on ydb/library/yql/providers/pq/async_io/dq_pq_read_actor_base.cpp
> +            ythrow yexception() << "Invalid state version " << data.Version;
предлагаю сделать if и задетектить там проблему. в ошибку поместить обе версии. else не писать. код более плоский будет

2024-09-16 16:36 UTC, uzhastik commented on ydb/library/yql/providers/pq/provider/ya.make
> +    ydb/library/yql/providers/common/pushdown
sort plz

2024-09-17 08:54 UTC, kardymonds commented on ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
> +        return NActors::TlsActivationContext->ExecutorThread.RegisterActor(actorPtr.release(), NActors::TMailboxType::HTSwap, Max<ui32>());
В итоге у меня не получилось переделать (через `TActivationContext::ActorSystem()->Register()`). Предлагаю пока так оставить

2024-09-17 10:50 UTC, dorooleg approved these changes, later dismissed

2024-09-17 10:56 UTC, uzhastik approved these changes, later dismissed

2024-09-17 11:02 UTC, vitstn commented on ydb/library/yql/public/purecalc/common/no_pg_wrapper/ya.make
> +LIBRARY()
я против этой библиотеки

тем более она еще и прибита к no_llvm

2024-09-17 11:02 UTC, vitstn requested changes, later dismissed
!

2024-09-17 14:46 UTC, uzhastik commented on ydb/library/yql/public/purecalc/common/no_pg_wrapper/ya.make
> +LIBRARY()
в каком смысле прибита? тут же не peerdir, а recurse

2024-09-18 14:28 UTC, uzhastik commented on ydb/library/yql/public/purecalc/common/no_pg_wrapper/ya.make
> +LIBRARY()
нам нужна либа purecalc без pg, потому что иначе мы не можем слинковаться с тестовыми либами, куда втащили pg_dummy

2024-09-23 07:15 UTC, dorooleg submitted a review, later dismissed

2024-09-23 07:29 UTC, aakulaga-ydb submitted a review, later dismissed

2024-09-23 07:36 UTC, gridnevvvit submitted a review, later dismissed

2024-09-23 10:59 UTC, dorooleg approved these changes

2024-09-23 11:12 UTC, gridnevvvit approved these changes

2024-09-23 11:30 UTC, aakulaga-ydb approved these changes

2024-09-23 11:35 UTC, uzhastik approved these changes

2024-09-23 11:36 UTC, merged