Refactoring YDB concepts
ydb-platform/ydb pull request #5580
Opened 2024-06-14 15:38 UTC by Pseudolukian

### Changelog category 
* Documentation (changelog entry is not required)

2024-06-24 03:07 UTC, blinkov requested changes

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
> +Визуально представление обоих типов таблиц одинаково, основное отличие между строковыми и колоночными таблицами — в способе хранения данных. Данные в строковых таблицах хранятся построково, а в колон
```suggestion
Логически, с точки зрения пользователя, оба вида таблиц выглядят одинаково. Основное отличие между строковыми и колоночными таблицами заключается в способе хранения данных. В строковых таблицах значения всех колонок каждой строки располагаются рядом, а в колоночных таблицах — наоборот, каждая колонка хранится отдельно, и рядом оказываются ячейки, относящиеся к разным строкам.```

Определения во второй половине звучали как «масло масляное».

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
> +Вне зависимости от типа таблицы, она должна содержать первичный ключ. В первичном ключе колоночных таблиц можно использовать только `NOT NULL` колонки. Данные в таблицах физически сортируются по перв
```suggestion
Независимо от типа таблицы, она должна содержать первичный ключ. В первичном ключе колоночных таблиц можно использовать только колонки с `NOT NULL`. Данные в таблицах физически сортируются по первичному ключу. Строчные таблицы автоматически партицируются по диапазонам первичных ключей в зависимости от нагрузки и объёма данных, а данные в колоночных таблицах партицируются не по первичному ключу, а по хешу от колонок партицирования. Каждый диапазон первичных ключей таблицы обрабатывается определённой [таблеткой](../../cluster/common_scheme_ydb.md#tablets), называемой *data shard* для строчных таблиц и *column shard* — для колоночных.
```

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/index/intro.md
> +В {{ ydb-short-name }} поддерживаются высокопроизводительные распределенные [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science))-транзакции, которые могут затрагивать несколько записей из ра
Это звучит как транзакции между строковыми и колоночными таблицами, которые вроде ещё не были готовы — или и правда уже доступны?

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/index/when_use.md
> +* В проектах, где требуются одновременная работа с OLAP- и OLTP-нагрузками.
```suggestion
* В проектах, где требуются одновременная работа с транзакционными и аналитическими нагрузками. 
```

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/scan_query.md
> +Для работы с OLAP-нагрузками в {{ ydb-short-name }} существуют специализированный тип таблиц — [колоночные](../datamodel/_includes/table.md#кcolumn-tables) таблицы. Они хранят данные каждого столбца
```suggestion
Для работы с OLAP-нагрузками в {{ ydb-short-name }} существует специализированный тип таблиц — [колоночные](../datamodel/_includes/table.md#column-tables) таблицы. Они хранят данные каждого столбца отдельно от других столбцов. Благодаря этому при выполнении запроса считываются только те столбцы, которые непосредственно участвуют в запросе.
```

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/scan_query.md
> +Для работы с OLAP-нагрузками в {{ ydb-short-name }} существуют специализированный тип таблиц — [колоночные](../datamodel/_includes/table.md#кcolumn-tables) таблицы. Они хранят данные каждого столбца
снова ссылка на include

2024-06-24 03:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +## Строковые таблицы {#row-tables}
```suggestion
## Строковые таблицы { #row-oriented-tables }
```

2024-06-25 11:07 UTC, Pseudolukian commented on ydb/docs/ru/core/concepts/_includes/scan_query.md
> +Для работы с OLAP-нагрузками в {{ ydb-short-name }} существуют специализированный тип таблиц — [колоночные](../datamodel/_includes/table.md#кcolumn-tables) таблицы. Они хранят данные каждого столбца
Поправил

2024-06-25 11:09 UTC, Pseudolukian commented on ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
> +* [Колоночные таблицы](../../datamodel/_includes/table.md#column-tables) — предназначены для OLAP-нагрузок.
Поправил

2024-06-26 09:58 UTC, Pseudolukian commented on ydb/docs/ru/core/concepts/_includes/index/intro.md
> +В {{ ydb-short-name }} поддерживаются высокопроизводительные распределенные [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science))-транзакции, которые могут затрагивать несколько записей из ра
Нет. Транзакций между строковыми и колодочными таблицами нет. Поправил описание.

2024-07-18 05:10 UTC, blinkov submitted a review, later dismissed

2024-07-18 05:10 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/expressions/items-access.md
> +{% include [not_allow_for_olap](../../../../../_includes/not_allow_for_olap_note.md) %}
Это не матчится с моим представлением о том, как оно работает — эти операции уже при вычислениях в памяти, когда уже не важно из какой там таблицы эти значения прочитали. Можешь показать пример ошибки как не работает?

2024-07-18 05:10 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/revoke.md
> +* Отозвать право `ydb.generic.read` на [строковую](../../../concepts/datamodel/table.md#row-oriented-tables) или [колоночную](../../../concepts/datamodel/table.md#column-oriented-tables) таблицу `/sh
в этой статье тоже не особо принципиально какой тип таблицы, это про доступы, а проблем в Аркадии явно может создать

2024-07-18 05:10 UTC, blinkov commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-on-premises.md
> +1. Создайте тестовую строковую (`test_row_table`) или колоночную таблицу (`test_column_table`):
давай в табы это завернём вместо списка, тестовой таблицы достаточно одной

2024-07-18 11:51 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/hyperscan.md
> +При вызове напрямую, чтобы избежать компиляции регулярного выражения на каждой строке [строковой](../../../../concepts/datamodel/table.md#row-oriented-tables) или [колоночной](../../../../concepts/da
Вернул

2024-07-18 11:52 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/pire.md
> +Чтобы избежать компиляции регулярного выражения на каждой строке [строковой](../../../../concepts/datamodel/table.md#row-oriented-tables) или [колоночной](../../../../concepts/datamodel/table.md#colu
Вернул

2024-07-18 12:39 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/expressions/items-access.md
> +{% include [not_allow_for_olap](../../../../../_includes/not_allow_for_olap_note.md) %}
Тут штука в том, что контейнерные типы данных не поддерживаются для колоночных таблиц. Ты просто не сможешь её создать, а следовательно и выбрать из неё данные. 

Ошибка при попытке создания колодочной таблицы с контейнерными типами данных:
`Invalid type for column: id. Only YQL data types and PG types are currently supported`


Пример:
```sql
CREATE TABLE my_table
(
    category_id Uint64 NOT NULL,
    id Struct<Name:String,Age:Int32>,
    expire_at Tuple<Int32,Double>,
    updated_on Dict<String,Int32>,
    name List<Int32>,
    attributes JsonDocument,
    PRIMARY KEY (category_id)
)
WITH (
    STORE = COLUMN
);
```

Тестил на Quickstart и Manage YDB в Облаке.

2024-07-18 13:54 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/revoke.md
> +* Отозвать право `ydb.generic.read` на [строковую](../../../concepts/datamodel/table.md#row-oriented-tables) или [колоночную](../../../concepts/datamodel/table.md#column-oriented-tables) таблицу `/sh
Вернул как было.

2024-07-18 13:59 UTC, Pseudolukian commented on ydb/docs/ru/core/deploy/manual/deploy-ydb-on-premises.md
> +1. Создайте тестовую строковую (`test_row_table`) или колоночную таблицу (`test_column_table`):
Завернул в табы.

2024-07-19 09:18 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/expressions/items-access.md
> +{% include [not_allow_for_olap](../../../../../_includes/not_allow_for_olap_note.md) %}
Это понятно, но данный кусок текста не про это же? Всегда можно прочитать из таблицы строку или условный JSON, скастить к контейнеру и затем спокойно пользоваться этим синтаксисом.

2024-07-19 09:36 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/expressions/items-access.md
> +{% include [not_allow_for_olap](../../../../../_includes/not_allow_for_olap_note.md) %}
Ты явно владеешь черной магией.

2024-08-15 09:55 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/expressions/items-access.md
> +{% include [not_allow_for_olap](../../../../../_includes/not_allow_for_olap_note.md) %}
Удалил include

2024-08-16 01:25 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/view.md
> +
```suggestion
```

2024-08-20 06:30 UTC, fomichev3000 approved these changes

2024-08-20 06:30 UTC, merged