Update changelog-server.md with descriptions  of the 23-4 server version
ydb-platform/ydb pull request #5600
Opened 2024-06-16 11:55 UTC by katidisergei

Update changelog-server.md with descriptions  of the 23-4 server version

### Changelog entry 
Update changelog-server.md with descriptions  of the 23-4 server version 

...

### Changelog category 
* Performance improvement
* Bugfix 

### Additional information

...

2024-06-17 07:28 UTC, zinal requested changes
Хотелось бы при описании "исправлена ошибка" видеть хотя бы в минимальном виде возможные ситуации проявления и эффекты этой ошибки. Без этой информации невозможно оценить вносимые правки.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2083) использование ресурсов репликами Schemeboard. Особенно заметно при наличии изменений таблиц с большим числом партиций.
Наибольший эффект заметен при модификации метаданных таблиц с большим количеством партиций.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка, возникавшая в некоторых ситуациях записи в топик с пустым producer_id при выключенной дедупликации.
, и приводившая к аварийному завершению серверного процесса.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сжатия данных.
, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и аварийным завершением серверного процесса.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка частичной фиксации накопленных изменений при использовании  распределенных транзакций.
[Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка возможной неполной фиксации накопленных изменений при использовании  распределенных транзакций.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлены внутренние серверные ошибки BlobStorageController.
* Исправлена ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных.
* Исправлена ошибка в Blob Storage, из-за которой информация о смене состава группы хранения могла не поступать своевременно на узлы кластера.

2024-06-17 07:28 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлены утечки памяти в C++ SDK.
, которые в некоторых сценариях могли проявляться в серверных процессах.

2024-06-17 07:47 UTC, blinkov submitted a review, later dismissed

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +## Версия 23.3 {#23-4}
```suggestion
## Версия 23.4 {#23-4}
```

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка отображения метрики количества партиций в топике.
из этого предложения не понятно: эта метрика совсем не отображалась или выдавала кривые значения?

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена проблема, приводящая к падению процесса YDB из за ошибочного состояния сессии записи в топик.
```suggestion
* Исправлена проблема, приводящая к падению процесса `ydbd` из-за ошибочного состояния сессии записи в топик.
```

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
```suggestion
* Исправлена ошибка `INTERNAL_ERROR (has already committed)` в стриминговых запросах.
```

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлены утечки памяти в C++ SDK.
тогда желательно вместо «в некоторых сценариях» более чётко написать в каких

2024-06-17 07:47 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
что тут имеется ввиду под стриминговыми запросами?

2024-06-17 08:03 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
Это YQ в режиме стриминга, оконные запросы над топиками. Напрямую в YDB эту функцию сейчас сложно задействовать (как минимум инструкций нет).

2024-06-18 14:08 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2083) использование ресурсов репликами Schemeboard. Особенно заметно при наличии изменений таблиц с большим числом партиций.
поменял

2024-06-18 14:09 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка, возникавшая в некоторых ситуациях записи в топик с пустым producer_id при выключенной дедупликации.
добавил

2024-06-18 14:09 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сжатия данных.
добавил

2024-06-18 14:10 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка частичной фиксации накопленных изменений при использовании  распределенных транзакций.
поправил

2024-06-18 14:13 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка отображения метрики количества партиций в топике.
поправил

2024-06-18 14:14 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
не совсем понятно итого надо что то менять или нет, трогать не стал

2024-06-19 03:05 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка, возникавшая в некоторых ситуациях записи в топик с пустым producer_id при выключенной дедупликации, и приводившая к аварийному завершению серверного процесса.
```suggestion
* Исправлена ошибка, возникавшая в некоторых ситуациях записи в топик с пустым `producer_id` при выключенной дедупликации, и приводившая к аварийному завершению серверного процесса.
```

2024-06-19 03:05 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2083) использование ресурсов репликами Schemeboard. Наибольший эффект заметен при модификации метаданных таблиц с большим количеством парти
```suggestion
* Исправлена проблема повышенного потребления вычислительных ресурсов актором топиков `PERSQUEUE_PARTITION_ACTOR`.
* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2083) использование ресурсов репликами SchemeBoard. Наибольший эффект заметен при модификации метаданных таблиц с большим количеством партиций.
```

2024-06-19 11:50 UTC, s-sabitova commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
Предлагаю здесь добавить ссылку на эту страницу про стриминговые запросы: https://ydb.tech/docs/ru/reference/ydb-cli/yql

2024-06-19 12:01 UTC, s-sabitova commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка отображения метрики количества партиций в топике, количестко партиций отображалось некорректно.
Исправлена ошибка, из-за которой метрика количества партиций в топике могла иметь неверное значение

2024-06-19 12:57 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в стриминговых запросах.
Добавил

2024-06-20 12:01 UTC, zinal requested changes

2024-06-20 12:01 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка отображения метрики количества партиций в топике, количество партиций отображалось некорректно.
```suggestion
* Исправлена ошибка отображения метрики количества партиций в топике, ранее количество партиций отображалось некорректно.
```

2024-06-20 12:01 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сжатия данных, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и авари
```suggestion
* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сборки мусора, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и аварийным завершением серверного процесса.
```

2024-06-20 12:08 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в [стриминговых запросах](https://ydb.tech/docs/ru/reference/ydb-cli/yql).
саму ошибку в бэктики ещё

2024-06-20 13:38 UTC, zinal requested changes

2024-06-20 13:38 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3002) ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных. Ошибка проявлялась для систем с явным образом включенной функцией "blob depot" (по умолчанию функция выключена).
```

2024-06-20 13:38 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка в Blob Storage, из-за которой информация о смене состава группы хранения могла не поступать своевременно на узлы кластера.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2696) ошибка в Blob Storage, из-за которой информация о смене состава группы хранения могла не поступать своевременно на отдельные узлы кластера. В результате в редких случаях могли блокироваться операции чтения и записи данных, хранящихся в затронутой группе, и требовалось ручное вмешательство администратора.
```

2024-06-20 14:27 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка, возникавшая в некоторых ситуациях записи в топик с пустым `producer_id` при выключенной дедупликации, и приводившая к аварийному завершению серверного процесса.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2475) ошибка, возникавшая в некоторых ситуациях записи в топик с пустым `producer_id` при выключенной дедупликации. Она могла приводить к аварийному завершению серверного процесса `ydbd`.
```

2024-06-20 14:28 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сжатия данных, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и авари
* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сборки мусора, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и, как следствие, аварийным завершением серверного процесса `ydbd`.

2024-06-20 14:28 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сжатия данных, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и авари
```suggestion
* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сборки мусора, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и, как следствие, аварийным завершением серверного процесса `ydbd`.
```

2024-06-20 14:29 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка возможной неполной фиксации накопленных изменений при использовании распределенных транзакций.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка возможной неполной фиксации накопленных изменений при использовании распределенных транзакций. Данная ошибка возникает при крайне редкой комбинации событий, включающей в себя перезапуск таблеток, обслуживающих вовлеченные в транзакцию партиции таблиц.
```

2024-06-20 14:30 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка отображения метрики количества партиций в топике, количество партиций отображалось некорректно.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3587) ошибка отображения метрики количества партиций в топике, ранее в ней отображалось некорректное значение.
```

2024-06-20 14:31 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3002) ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных. Ошибка проявлялась для систем с явным образом включенной экспериментальной функцией "blob depot" (по умолчанию эта функция выключена).
```

2024-06-20 14:33 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлены ошибки, которые в том числе приводили утечкам памяти и рестартам узлов ydb topics.
```suggestion
* [Устранены](https://github.com/ydb-platform/ydb/pull/2126) утечки памяти, которые проявлялись при копировании данных топиков между кластерами {{ ydb-short-name }}. Они могли приводить к завершению серверных процессов `ydbd`  из-за исчерпания доступной оперативной памяти.
```

2024-06-21 01:53 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Исправлена ошибка  INTERNAL_ERROR (has already committed) в [стриминговых запросах](https://ydb.tech/docs/ru/reference/ydb-cli/yql).
```suggestion
```

2024-06-21 01:55 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранены](https://github.com/ydb-platform/ydb/pull/2126) утечки памяти, которые проявлялись при копировании данных топиков между кластерами {{ ydb-short-name }}. Они могли приводить к завершению
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка возможной неполной фиксации накопленных изменений при использовании распределенных транзакций. Данная ошибка возникает при крайне редкой комбинации событий, включающей в себя перезапуск таблеток, обслуживающих вовлеченные в транзакцию партиции таблиц.
* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сборки мусора, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и, как следствие, аварийным завершением серверного процесса `ydbd`.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2696) ошибка в Blob Storage, из-за которой информация о смене состава группы хранения могла не поступать своевременно на отдельные узлы кластера. В результате в редких случаях могли блокироваться операции чтения и записи данных, хранящихся в затронутой группе, и требовалось ручное вмешательство администратора.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3002) ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных. Ошибка проявлялась для систем с явным образом включенной экспериментальной функцией "blob depot" (по умолчанию эта функция выключена).
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2475) ошибка, возникавшая в некоторых ситуациях записи в топик с пустым `producer_id` при выключенной дедупликации. Она могла приводить к аварийному завершению серверного процесса `ydbd`.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2651) проблема, приводящая к падению процесса `ydbd` из-за ошибочного состояния сессии записи в топик.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3587) ошибка отображения метрики количества партиций в топике, ранее в ней отображалось некорректное значение.
* [Устранены](https://github.com/ydb-platform/ydb/pull/2126) утечки памяти, которые проявлялись при копировании данных топиков между кластерами {{ ydb-short-name }}. Они могли приводить к завершению серверных процессов `ydbd`  из-за исчерпания доступной оперативной памяти.
```

2024-06-21 01:56 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранены](https://github.com/ydb-platform/ydb/pull/2126) утечки памяти, которые проявлялись при копировании данных топиков между кластерами {{ ydb-short-name }}. Они могли приводить к завершению
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка возможной неполной фиксации накопленных изменений при использовании распределенных транзакций. Данная ошибка возникает при крайне редкой комбинации событий, включающей в себя перезапуск таблеток, обслуживающих вовлеченные в транзакцию партиции таблиц.
* [Устранена](https://github.com/ydb-platform/ydb/pull/3165) гонка между процессами слияния таблиц и сборки мусора, из-за которой сборка мусора могла завершиться ошибкой нарушения инвариантов и, как следствие, аварийным завершением серверного процесса `ydbd`.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2696) ошибка в Blob Storage, из-за которой информация о смене состава группы хранения могла не поступать своевременно на отдельные узлы кластера. В результате в редких случаях могли блокироваться операции чтения и записи данных, хранящихся в затронутой группе, и требовалось ручное вмешательство администратора.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3002) ошибка в Blob Storage, из-за которой при корректной конфигурации могли не запускаться узлы хранения данных. Ошибка проявлялась для систем с явным образом включенной экспериментальной функцией "blob depot" (по умолчанию эта функция выключена).
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2475) ошибка, возникавшая в некоторых ситуациях записи в топик с пустым `producer_id` при выключенной дедупликации. Она могла приводить к аварийному завершению серверного процесса `ydbd`.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2651) проблема, приводящая к падению процесса `ydbd` из-за ошибочного состояния сессии записи в топик.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3587) ошибка отображения метрики количества партиций в топике, ранее в ней отображалось некорректное значение.
* [Устранены](https://github.com/ydb-platform/ydb/pull/2126) утечки памяти, которые проявлялись при копировании данных топиков между кластерами {{ ydb-short-name }}. Они могли приводить к завершению серверных процессов `ydbd` из-за исчерпания доступной оперативной памяти.
```

2024-06-21 06:17 UTC, fomichev3000 approved these changes

2024-06-21 06:17 UTC, merged