Connector: Tests: enabling Python style tests only for open source
ydb-platform/ydb pull request #5628
Opened 2024-06-17 10:36 UTC by lifthelm

### Changelog entry 

Enabling Python style tests for connector tests only in open source

### Changelog category 

* Not for changelog (changelog entry is not required)

2024-06-17 11:16 UTC, vitalyisaev2 requested changes

2024-06-17 11:16 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/ya.make
> +    STYLE_PYTHON()
В комментариях укажи, пожалуйста, номера тикетов, из которых будет понятно, почему мы так делаем

2024-07-02 13:51 UTC, vitalyisaev2 approved these changes

2024-07-02 13:55 UTC, uzhastik approved these changes

2024-07-02 13:58 UTC, merged