Add discovery mutator for underlay
ydb-platform/ydb pull request #566
Opened 2023-12-19 06:44 UTC by kardymonds

2023-12-25 15:15 UTC, uzhastik approved these changes

2023-12-25 16:30 UTC, dorooleg requested changes

2023-12-25 16:30 UTC, dorooleg commented on ydb/core/fq/libs/shared_resources/shared_resources.cpp
> +                Ydb::Discovery::EndpointInfo* endpointInfo = proto->Mutableendpoints(i);
Use the common style here:
```
Mutableendpoints(i) => MutableEndpoints(i)
```
```
endpointsSize() => EndpointsSize()
```
...

2023-12-25 16:30 UTC, dorooleg commented on ydb/core/fq/libs/shared_resources/shared_resources.cpp
> +            TString underlayPrefix{"u-"};
`TStringBuf` instead of `TString`

2023-12-26 12:12 UTC, kardymonds commented on ydb/core/fq/libs/shared_resources/shared_resources.cpp
> +            TString underlayPrefix{"u-"};
Replaced

2023-12-26 13:25 UTC, dorooleg approved these changes

2023-12-26 13:44 UTC, merged