YQ-2650 support YT in KQP
ydb-platform/ydb pull request #567
Opened 2023-12-19 08:45 UTC by GrigoriyPA

2023-12-22 19:04 UTC, spuchin requested changes

2023-12-22 19:04 UTC, spuchin commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
Зачем нам в компиляции запроса YtGateway? Для того же S3 я не вижу чтобы мы тут что-то передавали.

2023-12-22 19:04 UTC, spuchin commented on ydb/core/kqp/host/kqp_translate.h
> +    bool isEnablePgConstsToParams, const NYql::TYtGatewayConfig& ytGatewayConfig);
Зачем в трансляции YtGateway?

2023-12-22 19:04 UTC, spuchin commented on ydb/core/kqp/provider/yql_kikimr_opt_build.cpp
> +    if (auto maybeRight = node.Maybe<TCoRight>()) {
Explore делается только по World'ам, зачем мы тут идем в Right?

2023-12-25 08:35 UTC, GrigoriyPA commented on ydb/core/kqp/host/kqp_translate.h
> +    bool isEnablePgConstsToParams, const NYql::TYtGatewayConfig& ytGatewayConfig);
Пока решили в задаче [YQ-2650](https://st.yandex-team.ru/YQ-2650) не делать external data source для YT и задавать кластера YT статически, для этого надо при трансляции добавлять в ClusterMapping кластера YT

2023-12-25 08:36 UTC, GrigoriyPA commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
Это нужно чтобы задавать статические кластера YT (пока нету external data source для этого), нужно их добросить до ClusterMapping в [kqp_translate.cpp](https://github.com/ydb-platform/ydb/pull/567/files/076eef9890a4d6d5fdaf3d56dc38bbbea7a3fda2#diff-d1c88ed9003f1892cbe9cedcbb96729d0b7baf8a31f3cb5bbcd537ae355a087f)

2023-12-25 08:55 UTC, GrigoriyPA commented on ydb/core/kqp/provider/yql_kikimr_opt_build.cpp
> +    if (auto maybeRight = node.Maybe<TCoRight>()) {
В YT не получается сохранить так же как и в S3 сохранить в world ноды ResWrite! информацию об источнике (в ноде Left! Read!) по двум причинам:
1) Нода Left! Read! удаляется для YT при парсинге:
https://a.yandex-team.ru/arcadia/ydb/library/yql/sql/v1/query.cpp?rev=r13065462#L781
2) Далее нода Left! Read! удаляется на стадии RewriteIO:
https://a.yandex-team.ru/arcadia/ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp?rev=r13054503#L193

По этому добавил обход третьего сына для ResWrite, ResPull который ищет YtReadTable! под символом Right! Можно убрать тут обход Right и искать сразу YtReadTable!

2023-12-25 13:34 UTC, spuchin commented on ydb/core/kqp/provider/yql_kikimr_opt_build.cpp
> +    if (auto maybeRight = node.Maybe<TCoRight>()) {
Значит нужно добавить настройку в YT provider, чтобы в случае работы в KQP эти world'ы не удалялись.

2024-01-10 15:26 UTC, rvu1024 requested changes

2024-01-10 15:26 UTC, rvu1024 commented on ydb/library/yql/sql/v1/query.cpp
> +                return false;
Т.е. теперь для YT провайдера запрещено иметь ссылки на таблицы внутри subquery? Зачем такое ограничение?

2024-01-10 15:26 UTC, rvu1024 commented on ydb/library/yql/dq/runtime/dq_compute.cpp
> +        NYql::GetDqYtFactory(),
Общий код DQ не должен зависеть от конкретных провайдеров. Comp factory должна конфигурироваться в кончных бинарях, а не в общих библиотеках. См. например https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/tools/dqrun/dqrun.cpp#L685

2024-01-10 15:26 UTC, rvu1024 commented on ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
> +        AddHandler(0, &TDqReadWrap::Match, HNDL(BuildStageWithReadWrap));
Этого не достаточно. См. GetDqOptCallback в логических оптимизаторах, как он интегрируется с другими провайдерами https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/dq/opt/logical_optimize.cpp#L139

2024-01-10 15:26 UTC, rvu1024 commented on ydb/library/yql/providers/yt/comp_nodes/dq/dq_yt_reader.cpp
> +                        }
Я против этого изменения. В основном сервисе yql это приведет к чтению данных вне транзакции, если транзакция по каким-то причинам протухла, вместо того что бы пофейлить запрос

2024-01-10 15:26 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp
>          }
Мне пока не понятны мотивы таких кардинальных изменений с ворлдами. Они опасны. Как минимум нужен полный чек в аркадии с тяжелыми тестами. И безусловно под отдельным фичефлагом, если объяснишь мотивы

2024-01-31 13:37 UTC, spuchin commented on ydb/core/kqp/query_compiler/kqp_mkql_compiler.cpp
> +    compiler->AddCallable({TDqSourceWideWrap::CallableName(), TDqSourceWideBlockWrap::CallableName(), TDqReadWideWrap::CallableName(), TDqReadBlockWideWrap::CallableName()},
А как у нас чтение оказалось в лямбде? Мы ведь должны читать через механизм DQ Source?

2024-02-01 09:04 UTC, rvu1024 commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
Поддерживаю. Не вижу смысла тащить статически кластера в YDB

2024-02-01 10:10 UTC, rvu1024 requested changes
Некоторые изменения стоит вытащить в отдельные PR - они напрямую не связаны с этим PR. Например изменения kqprun и перенос оптимизаторов из providers/dq в dq

2024-02-01 10:10 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_provider.cpp
> -#include <ydb/library/yql/providers/common/proto/gateways_config.pb.h>
почему удаляешь?

2024-02-01 10:10 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_provider.h
> +    bool KeepSession = false;
Можно все это сделать одним флагом

2024-02-01 10:10 UTC, rvu1024 commented on ydb/tests/tools/kqprun/configuration/app_config.conf
> +      Name: "hahn"
зачем тут внутренний кластер в oss?

2024-02-01 15:15 UTC, uzhastik commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
data source поддержать довольно сложно на данном этапе, много логики находится в sql трансляторе, поэтому кластера мы ему уже готовые подкладываем. так что предлагаю вернуться к этому вопросу после решения более серьезных проблем, которых довольно много

2024-02-02 10:13 UTC, uzhastik commented on ydb/core/kqp/host/kqp_translate.h
> +    bool isEnablePgConstsToParams, const NYql::TYtGatewayConfig& ytGatewayConfig);
переходить на data source будем в отдельной задаче, она не кажется простой. пока мы стараемся зареюзать то, что работает в yql сервисе. в трансляторе много логики, связанной именно с yt кластерами, вытащить это наружу не видится простой задачей

2024-02-09 11:48 UTC, spuchin commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
Ну тем не менее, давайте сразу делать адекватно, ytGatewayConfig в KQP это ненормально.

2024-02-09 12:47 UTC, GrigoriyPA commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
> Ну тем не менее, давайте сразу делать адекватно, ytGatewayConfig в KQP это ненормально.

Вынес зависимость от ytGatewayConfig в [kqp_federated_query_helpers.h](https://github.com/ydb-platform/ydb/pull/567/files#diff-842692cf78053320b9e5a8fb0fbc2ed0395980c7ec62e173562e2e48800680fe)

2024-02-09 13:11 UTC, GrigoriyPA commented on ydb/core/kqp/host/kqp_host.cpp
> +            IYtGateway::TOpenSessionOptions(SessionId)
Тут передаётся SessionId текущего запроса, создаётся тут:
https://github.com/ydb-platform/ydb/blob/17174395fd982b3e1d8787b06228cc529e025be8/ydb/core/kqp/proxy_service/kqp_proxy_service.cpp#L1444

Оно уникальное для каждого запроса и содержит guid как подстроку, это id всегда не пустое, кажется оно подходит

2024-02-09 13:16 UTC, GrigoriyPA commented on ydb/core/kqp/host/kqp_host.cpp
> +            IYtGateway::TOpenSessionOptions(SessionId)
Добавил ENSURE на непустоту, issue можно закрывать?

2024-02-13 08:47 UTC, GrigoriyPA commented on ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp
> +    TExprNode::TPtr InjectUdfRemapperOrView(TYtRead readNode, TExprContext& ctx, bool fromReadSchema, bool buildLeft) {
Добавлять интеграционные тесты решено в отдельном PR, проверена работа с view, запросы из YQL туториала в которых есть view работают правильно. Запросы с чтением из нескольких таблиц тоже работают (CONCAT, RANGE), думаю что можно явно не запрещать эти случаи

2024-02-13 11:26 UTC, GrigoriyPA commented on ydb/library/yql/providers/yt/provider/yql_yt_physical_optimize.cpp
> +
Вызов OptimizeReadWithSettings есть уже после добавления DqReadWrap в [yql_yt_dq_optimize.cpp](https://github.com/ydb-platform/ydb/blob/57cf0e9fb88393283041436ec98578e9599a50f3/ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp#L34), он уже работает предсказуемо, как и в yql пайплайне, по этому мне кажется тут лучше полностью скипнуть оптимизацию

2024-02-15 17:25 UTC, rvu1024 requested changes

2024-02-15 17:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/codec/ya.make
> +    ydb/library/yql/providers/yt/codec/codegen
Кажется эта зависимость должна быть в конечном бинаре. @vitstn поправь, если не так

2024-02-15 17:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/ya.make
> +    ydb/library/yql/providers/yt/comp_nodes/llvm14
Кажется эта зависимость должна быть в конечном бинаре. @vitstn поправь, если не так

2024-02-15 17:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_provider.h
> +#include <ydb/library/yql/providers/common/proto/gateways_config.pb.h>
Используй forward declaration. Тем более, что TYtGatewayConfig по указателю тут используется

2024-02-15 17:25 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_provider.h
> +    bool KikimrProviderExecution = false;
Лучше переименовать во что-то провайдер-нейтранльное. Например PassiveExecution

2024-02-15 17:26 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_provider.h
> +#include <ydb/library/yql/providers/common/proto/gateways_config.pb.h>
Включать генеренный файл в хидер не стоит - это приводит к большим перекомпиляциям

2024-02-16 10:11 UTC, GrigoriyPA commented on ydb/library/yql/providers/yt/gateway/native/ya.make
> +    ydb/library/yql/providers/yt/comp_nodes/llvm14
В файле [yql_yt_lambda_builder.cpp](https://github.com/ydb-platform/ydb/blob/4749b9e5d260714490997e6f5ee1ee8c1c8fc46c/ydb/library/yql/providers/yt/gateway/native/yql_yt_lambda_builder.cpp#L72) используется функция WrapYtTableContent, которая определена в [yql_mkql_table_content.cpp](https://github.com/ydb-platform/ydb/blob/4749b9e5d260714490997e6f5ee1ee8c1c8fc46c/ydb/library/yql/providers/yt/comp_nodes/yql_mkql_table_content.cpp#L52)

2024-02-16 11:03 UTC, rvu1024 commented on ydb/library/yql/providers/yt/gateway/native/ya.make
> +    ydb/library/yql/providers/yt/comp_nodes/llvm14
Есть еще таргет no_llvm. Используемая реализация выбирается не библиотекой, а конечным бинарем

2024-02-16 11:07 UTC, vitstn commented on ydb/library/yql/providers/yt/gateway/native/ya.make
> +    ydb/library/yql/providers/yt/comp_nodes/llvm14
всегда llvm specific таргеты вроде ydb/library/yql/providers/yt/comp_nodes/llvm14 должны быть в конечном бинаре

2024-02-16 11:10 UTC, vitstn commented on ydb/library/yql/providers/yt/codec/ya.make
> +    ydb/library/yql/providers/yt/codec/codegen
точно так же 
есть llvm specific реализации, нельзя добавлять сюда

2024-02-27 15:21 UTC, rvu1024 submitted a review, later dismissed

2024-02-29 11:26 UTC, spuchin commented on ydb/core/kqp/session_actor/kqp_session_actor.cpp
> +        if (isFinal && FederatedQuerySetup && FederatedQuerySetup->YtGateway) {
Как минимум уберите эту логику внутрь FederatedQuerySetup, в session actor не хочется такой кастомный код провайдеров делать.
И я в целом не очень понимаю зачем нам это на уровне сесии, это же можно на уровне ридера сделать?

2024-03-01 15:36 UTC, GrigoriyPA commented on ydb/core/kqp/compile_service/kqp_compile_actor.cpp
> +        auto astResult = ParseQuery(ConvertType(QueryId.Settings.QueryType), QueryId.Settings.Syntax, QueryId.Text, QueryId.QueryParameterTypes, QueryId.IsSql(), cluster, kqpTablePathPrefix, kqpYqlSy
Реализована логика для создания EXTERNAL DATA SOURCE для yt

2024-03-01 15:36 UTC, GrigoriyPA commented on ydb/core/kqp/host/kqp_translate.h
> +    bool isEnablePgConstsToParams, const NYql::TYtGatewayConfig& ytGatewayConfig);
Реализована логика для создания EXTERNAL DATA SOURCE для yt

2024-03-07 10:50 UTC, rvu1024 approved these changes

2024-03-07 12:46 UTC, spuchin approved these changes

2024-03-07 12:54 UTC, merged