Set no-omit-frame-pointer by default
ydb-platform/ydb pull request #5688
Opened 2024-06-18 16:33 UTC by dcherednik

2024-06-19 09:52 UTC, iddqdex requested changes

2024-06-19 09:52 UTC, iddqdex commented on build/internal/ya.conf
> +CXXFLAGS = "-fno-omit-frame-pointer"
CXXFLAGS не нужен, так как входит в CFLAGS

2024-06-19 09:52 UTC, iddqdex commented on build/internal/ya.conf
> +CXXFLAGS = "-fno-omit-frame-pointer"
CXXFLAGS не нужен, так как входит в CFLAGS

2024-06-19 09:52 UTC, iddqdex commented on build/internal/ya.conf
Предлагаю добавить ALLOCATOR = "TCMALLOC_256K", чтобы у нас все бинарники собирались одинаково.

2024-06-19 09:52 UTC, iddqdex commented on build/internal/ya.conf
Предлагаю добавить HARDELING = "yes", так у нас собираются пакеты для прода, там будет лучше кэшхит

2024-06-20 10:16 UTC, snaury commented on build/internal/ya.conf
Я не думаю что это хорошая идея. HARDENING сборки чуть хуже дебажатся и могут быть не совместимы с санитайзерами.

2024-06-20 10:16 UTC, snaury commented on build/internal/ya.conf
Выставлять аллокатор на всё плохо, т.к. не во всех видах сборки можно использовать tcmalloc.

2024-06-20 11:46 UTC, iddqdex commented on build/internal/ya.conf
А если только для релизной сборки?

2024-06-21 10:02 UTC, snaury approved these changes

2024-06-21 10:13 UTC, iddqdex approved these changes

2024-06-21 10:13 UTC, merged