YQ-2628: add connections option for streaming queries
ydb-platform/ydb pull request #579
Opened 2023-12-19 14:07 UTC by EgorkaZ

2023-12-19 14:10 UTC, dorooleg requested changes

2023-12-19 14:10 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
> +                auto connectionCase = connection.content().setting().connection_case();
You need to check the type of query here

2023-12-19 15:07 UTC, uzhastik commented on ydb/core/fq/libs/config/protos/control_plane_storage.proto
> +message TStreamingQueryConfig {
давайте без нового месаджа сделаем. просто коллекцию добавим в существующий месадж

2023-12-19 15:07 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/util.cpp
> +    if (!config.HasStreamingQueryConfig()) {
нужен todo отпилить это после апгрейда кластеров

2023-12-20 10:16 UTC, dorooleg approved these changes

2023-12-22 12:44 UTC, merged