YQ:3368 Add Database validation
ydb-platform/ydb pull request #5984
Opened 2024-06-26 13:56 UTC by skywalker-jpg

### Changelog entry 

### Changelog category 

* Improvement

### Additional information

2024-06-26 14:42 UTC, vitalyisaev2 requested changes

2024-06-26 14:42 UTC, vitalyisaev2 commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +        const FederatedQuery::PostgreSQLCluster database = setting.postgresql_cluster();
`const T&` здесь и в Greenplum

2024-06-26 14:42 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_data_source.cpp
> +        if (sourceType == "Greenplum" || sourceType == "PostgreSQL") {
1. Пользуйся операцией `IsIn`. Пример: https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L195
2. Нужно добавить `MySQL` и `MicrosoftSqlServer` - точные значения не помню, посмотри в соседнем файле.
3. Название `isMdbDataSource` было бы, на мой взгляд, более удачным (стоит уточнить у @dorooleg)

2024-06-26 14:42 UTC, vitalyisaev2 commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
>          ValidateGenericConnectionSetting(setting.postgresql_cluster(), "postgresql", disableCurrentIam, passwordRequired, issues);
1. Перенеси проверку на пустоту `database_name` в `ValidateGenericConnectionSetting`
2. Используй эту же функцию для GP

2024-06-26 15:19 UTC, skywalker-jpg commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
>          ValidateGenericConnectionSetting(setting.postgresql_cluster(), "postgresql", disableCurrentIam, passwordRequired, issues);
1. Вопрос тогда как лучше сделать, мы же для ClickHouse тоже используем ValidateGenericConnectionSetting, но имя базы данных не вальсируем. Занести и в этот класс функцию isMdbDataSource или сделать прямо в ValidateGenericConnectionSetting IsIn()?

2024-06-26 15:24 UTC, vitalyisaev2 commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
>          ValidateGenericConnectionSetting(setting.postgresql_cluster(), "postgresql", disableCurrentIam, passwordRequired, issues);
1. Для ClickHouse тоже нужна валидация (а вот для Ydb нет). 
2. Насчёт `isMdbDataSource` я погорячился - ведь `Ms SQL Server` и в будущем `Oracle` - их нет в MDB. Может, их перенесём в `isRDBMSDataSource`. Не знаю, какое имя получше придумать.

2024-06-28 13:06 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +    if (!connection.database_name() || connection.database_name() == "") {
почему не достаточно !connection.database_name() ?

2024-06-28 13:07 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
>      if (!connection.login()) {
Возможно ли тестом закрепить это?

2024-07-03 12:16 UTC, skywalker-jpg commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +    if (!connection.database_name() || connection.database_name() == "") {
Виталий сказал так сделать

2024-07-05 12:26 UTC, vitalyisaev2 submitted a review, later dismissed

2024-07-05 18:06 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +    if (!connection.database_name() || connection.database_name() == "") {
@vitalyisaev2 можешь уточнить зачем такое сложное правило?

2024-07-05 18:09 UTC, uzhastik commented on ydb/core/external_sources/external_data_source.cpp
> +    bool isRDBMSDataSource(const TProtoStringType& sourceType) const {
Методы начинаются с большой буквы

2024-07-05 18:09 UTC, uzhastik commented on ydb/core/external_sources/external_data_source.cpp
> +        if (IsIn({"Greenplum", "PostgreSQL", "MySQL", "MsSQLServer", "Clickhouse"}, sourceType)) {
Замени if на return IsIn(….)

2024-07-05 18:09 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +        const FederatedQuery::GreenplumCluster& greenplumStorage = setting.greenplum_cluster();
Давай слово storage заменим на cluster

2024-07-08 06:54 UTC, vitalyisaev2 commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +    if (!connection.database_name() || connection.database_name() == "") {
@uzhastik не могу прокомментировать, не припомню, чтобы я говорил так делать.

2024-07-08 06:56 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
> +    if (!connection.database_name() || connection.database_name() == "") {
Сделайте, как Олег предложил. Код эквивалентный будет и без дублирования логики

2024-07-08 11:14 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/request_validators.cpp
>          issues.AddIssue( MakeErrorIssue(TIssuesIds::BAD_REQUEST,msg));
тут лишний пробел после скобки

2024-07-08 11:25 UTC, uzhastik approved these changes

2024-07-08 15:43 UTC, merged