[CBO] Count-min estimation added
ydb-platform/ydb pull request #6029
Opened 2024-06-27 13:18 UTC by pashandor789

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-01 10:57 UTC, resetius requested changes

2024-07-02 10:12 UTC, resetius approved these changes

2024-07-02 10:38 UTC, pavelvelikhov commented on ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
> +    appConfig.MutableTableServiceConfig()->SetCompileTimeoutMs(TDuration::Minutes(10).MilliSeconds());
Why did you increase the timeout to 10 minutes here?

2024-07-02 10:51 UTC, pavelvelikhov approved these changes

2024-07-02 12:33 UTC, merged