Bigdates YT key filter tests
ydb-platform/ydb pull request #6104
Opened 2024-07-01 08:03 UTC by amikish

2024-07-01 11:33 UTC, rvu1024 commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
>          Converters.emplace(TCoTzDate::CallableName(), [](const TExprNode& node) {
Tz-типы тоже нужно

2024-07-01 11:35 UTC, rvu1024 commented
тесты не канонизированы

2024-07-02 05:00 UTC, amikish commented on ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
>          Converters.emplace(TCoTzDate::CallableName(), [](const TExprNode& node) {
добавил

2024-07-02 14:15 UTC, rvu1024 approved these changes

2024-07-02 14:20 UTC, rvu1024 requested changes
тесты пофйелились

2024-07-03 09:25 UTC, rvu1024 approved these changes

2024-07-03 16:42 UTC, merged