Rewrite YQL CREATE
ydb-platform/ydb pull request #6120
Opened 2024-07-01 09:49 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-07-19 14:55 UTC, fomichev3000 requested changes

2024-07-19 14:55 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/secondary_index.md
> +Конструкция `INDEX` используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} {% if backend_name == "YDB"
Для колоночных вторичного индекса нет.

2024-07-19 14:55 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +Колонки одной таблицы можно объединять в группы, для того чтобы задать следующие параметры:
family нет для колоночных таблиц

2024-08-15 14:26 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/secondary_index.md
> +Конструкция `INDEX` используется для определения {% if concept_secondary_index %}[вторичного индекса]({{ concept_secondary_index }}){% else %}вторичного индекса{% endif %} {% if backend_name == "YDB"
Поправил

2024-08-15 14:27 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +Колонки одной таблицы можно объединять в группы, для того чтобы задать следующие параметры:
Поправил

2024-08-16 01:35 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
> +{% include [not_allow_for_olap](../../../../_includes/not_allow_for_olap_note.md) %}
```suggestion
{% if oss == true and backend_name == "YDB" %}

{% include [not_allow_for_olap](../../../../_includes/not_allow_for_olap_note.md) %}

{% endif %}
```

2024-08-16 01:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +{% if backend_name == "YDB" %}
```suggestion
{% if oss == true and backend_name == "YDB" %}
```

2024-08-16 01:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +
```suggestion
```

2024-08-16 01:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +{% endif %}
```suggestion
```

2024-08-16 01:47 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +По умолчанию, если параметр `STORE` не указан, создается строковая таблица.
```suggestion
По умолчанию, если параметр `STORE` не указан, создается строковая таблица.

{% endif %}
```

2024-08-16 01:55 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/with.md
> +Например, такой код создаст таблицу с включенным автоматическим партиционированием по размеру партиции и предпочитаемым размером каждой партиции 512 мегабайт:
```suggestion
Например, такой запрос создаст строковую таблицу с включенным автоматическим партиционированием по размеру партиции и предпочитаемым размером каждой партиции 512 мегабайт:
```

2024-08-20 06:34 UTC, fomichev3000 approved these changes, later dismissed

2024-08-28 07:01 UTC, blinkov commented
Superseded by #8306

2024-08-28 07:01 UTC, closed without merging