Add decimal support to arrow reader
ydb-platform/ydb pull request #6151
Opened 2024-07-01 19:58 UTC by resetius

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-01 20:28 UTC, Hor911 submitted a review, later dismissed

2024-07-05 10:16 UTC, uzhastik commented
можно автотестами закрепить новый функционал?

2024-07-05 13:17 UTC, resetius commented
> можно автотестами закрепить новый функционал?

Да, я сделал автотесты.

2024-08-05 15:21 UTC, vitstn requested changes
see comments

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_agg_minmax.cpp
> +        memcpy(ptr, &state, sizeof(state));
UnalignedWrite

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_agg_minmax.cpp
>          UpdateKey(state, batchNum, columns, row);
непонятно, если был обновлен st, как оно будет отражено в state?

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_agg_state_helper.h
> +    memcpy((void*)&t, buffer->data(), buffer->size());
тут гарантируется корректное выравние, достаточно привести к TDecimal * и прочитать значение

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_agg_sum.cpp
> +        memcpy(state, (void*)&st, sizeof(st));
Все такие memcpy должны быть использованы либо через ReadUnaligned, либо WriteUnaligned

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/minikql/mkql_node.cpp
> -    MKQL_ENSURE(schemeType != NUdf::TDataType<NUdf::TDecimal>::Id, "Can't' create Decimal.");
это нельзя убирать. DataType нельзя создать без значений precision/scale

2024-08-05 15:21 UTC, vitstn commented on ydb/library/yql/public/decimal/yql_decimal.h
> +        } else if (IsNan(l) || IsNan(r) || !a) {
что такое !a?

и почему при этом результат должен быть NaN

2024-08-05 16:17 UTC, resetius commented on ydb/library/yql/minikql/comp_nodes/mkql_block_agg_minmax.cpp
>          UpdateKey(state, batchNum, columns, row);
Он тут не меняется

2024-08-05 16:28 UTC, resetius commented on ydb/library/yql/minikql/mkql_node.cpp
> -    MKQL_ENSURE(schemeType != NUdf::TDataType<NUdf::TDecimal>::Id, "Can't' create Decimal.");
Падать тогда будет

2024-08-05 16:38 UTC, resetius commented on ydb/library/yql/public/decimal/yql_decimal.h
> +        } else if (IsNan(l) || IsNan(r) || !a) {
Не знаю, я этот код скопипастил

2024-08-06 11:19 UTC, resetius commented on ydb/library/yql/minikql/mkql_node.cpp
> -    MKQL_ENSURE(schemeType != NUdf::TDataType<NUdf::TDecimal>::Id, "Can't' create Decimal.");
Fixed

2024-08-07 12:24 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_block_impl.cpp
> +            auto integer = value.GetInt128();
*Cast(Buffer) = value

2024-08-07 12:27 UTC, vitstn commented on ydb/library/yql/public/decimal/yql_decimal.h
> +            Value = a > 0
select Decimal("inf",1,0) + Decimal("-inf",1,0)

nan

2024-08-07 12:29 UTC, vitstn commented on ydb/library/yql/public/decimal/yql_decimal.h
> +
TODO for operator -

2024-08-08 15:53 UTC, vitstn commented on ydb/library/yql/public/udf/arrow/block_io_buffer.h
> +        std::memcpy(&t, Buf_.Data() + Pos_, sizeof(t));
ReadUnaligned

2024-08-08 17:53 UTC, vitstn approved these changes

2024-08-08 19:56 UTC, uzhastik approved these changes

2024-08-08 19:56 UTC, merged