YDB-2321 Refactor IP UDF to use supported ipmath library
ydb-platform/ydb pull request #618
Opened 2023-12-21 07:11 UTC by avevad

2023-12-25 08:53 UTC, vitstn commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
please add more tests that cover this refactor

2023-12-27 15:04 UTC, avevad commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
Там уже были тесты на этот функционал (который я не менял совсем), и после изменений они все прошли)
В любом случае, добавил пару тестов

2024-01-16 17:10 UTC, rvu1024 requested changes

2024-01-16 17:10 UTC, rvu1024 commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        TIpv6Address addr = TIpv6Address::FromString(args[0].AsStringRef());
Здесь нужно использовать `TIpv6Address::FromString(TStringBuf str, bool& ok)` и возвращать TUnboxedValue() на !ok
И тест на невалидную строку добавить

2024-01-16 17:10 UTC, rvu1024 commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        return valueBuilder->NewString(SerializeAddress(beg).GetRef());
Кажется `TIpv6Address LowerBoundForPrefix(TIpv6Address value, ui8 prefixLen)` из ipmatch делает то, что тебе нужно

2024-01-17 13:10 UTC, avevad commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +#include <library/cpp/ipmath/ipmath.h>
Теперь используется)

2024-01-17 13:10 UTC, avevad commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        return res ? valueBuilder->NewString(res.GetRef()) : TUnboxedValue(TUnboxedValuePod());
Поправил

2024-01-17 13:11 UTC, avevad commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +            auto addr6 = TIpv6Address::FromString("::ffff:" + DeserializeAddress(ref).ToString(false));
Переделал нормально

2024-01-17 13:11 UTC, avevad commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        return valueBuilder->NewString(SerializeAddress(beg).GetRef());
Тоже переделал

2024-01-17 16:07 UTC, rvu1024 requested changes

2024-01-17 16:07 UTC, rvu1024 commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        if (addr.Type() != TIpv6Address::Ipv4 && addr.Type() != TIpv6Address::Ipv6) {
addr.IsValid()

2024-01-17 16:25 UTC, rvu1024 approved these changes

2024-01-18 12:28 UTC, merged