Block state valuebuilder
ydb-platform/ydb pull request #6231
Opened 2024-07-03 07:39 UTC by fedor-miron

### Changelog entry 

...

### Changelog category 

### Additional information

...

2024-07-09 13:21 UTC, igormunkin requested changes
@fedor-miron, thanks for the patch! Please, consider my comments below.

2024-07-09 13:21 UTC, igormunkin commented on ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
> +                        builder.Add(out);
Fixup was reverted in scope of bdd9c882ca5512cb5cdf36c39cbb942d20a640eb.

2024-07-10 10:14 UTC, igormunkin approved these changes, later dismissed
@fedor-miron, thanks for the fixes! LGTM, now.

2024-07-10 12:05 UTC, vitstn commented on ydb/library/yql/udfs/common/url_base/lib/url_base_udf.h
> +        static void Process(TBlockItem arg, const IValueBuilder&, const TSink& sink) { \
ValueBuilder должен быть первым аргументом, как в Run

2024-07-10 12:06 UTC, vitstn commented on ydb/library/yql/udfs/common/url_base/lib/url_base_udf.h
> +        static void Process(TBlockItem arg, const IValueBuilder&, const TSink& sink) { \
и указателем

2024-07-10 12:06 UTC, vitstn requested changes
issues

2024-07-11 15:48 UTC, vitstn approved these changes

2024-07-11 15:48 UTC, merged