Yq 3365
ydb-platform/ydb pull request #6257
Opened 2024-07-03 13:05 UTC by skywalker-jpg

### Changelog entry 

### Changelog category 

* New feature

### Additional information

2024-07-03 15:32 UTC, vitalyisaev2 submitted a review, later dismissed

2024-07-03 16:56 UTC, uzhastik commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +                bool alive = true;
давай вместо цикла заюзаем std::any_of

2024-07-04 15:24 UTC, uzhastik commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +            bool alive = std::all_of(
Вытащи контейнер в отдельную переменную, у тебя дублирование и непонятное время жизни результата at().

2024-07-04 15:24 UTC, uzhastik commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +            bool alive = std::all_of(
Давай переменную сделаем const

2024-07-04 16:31 UTC, uzhastik commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +            if (!hostMap.contains("services")) {
с отступами проблема

2024-07-04 17:06 UTC, uzhastik commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +                const bool alive = std::all_of(
почему all_of, а не any_of ?

2024-07-05 12:30 UTC, vitalyisaev2 approved these changes

2024-07-05 12:30 UTC, vitalyisaev2 commented on ydb/core/fq/libs/actors/ut/database_resolver_ut.cpp
> +                },
Почини отступы

2024-07-05 12:30 UTC, vitalyisaev2 commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +                                if (alive) {
Всё ещё проблема с отступами

2024-07-05 12:32 UTC, vitalyisaev2 requested changes
Надо починить отступы

2024-07-08 06:50 UTC, vitalyisaev2 approved these changes

2024-07-08 06:51 UTC, merged