Rewrite YQL ALTER TABLE
ydb-platform/ydb pull request #6340
Opened 2024-07-05 12:50 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-07-18 04:30 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/cdc.md
> +# Добавление или удаление потока изменений
хоть эта фича и правда называется CDC, но т.к. это всё же справка по синтаксису, то давай файлики по нему и называть — т.е. переименуем в`changefeed.md`

2024-07-18 04:42 UTC, blinkov requested changes, later dismissed

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/cdc.md
> +{% if backend_name == "YDB" %}
по идее этот if лишний, т.к. такой же уже есть внутри инклуда

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Две предыдущие команды из листингов 8 и 9 можно объединить в один вызов ```ALTER TABLE```. Приведенный ниже код создаст в таблице ```series_with_families``` группу колонок ```family_small``` и устано
```suggestion
Две предыдущие команды можно объединить в один вызов ```ALTER TABLE```. Приведенный ниже код создаст в таблице ```series_with_families``` группу колонок ```family_small``` и установит её для колонки ```release_date```.
```

оффтоп для этого PR, но совсем уж странное

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/index.md
> +При помощи команды ```ALTER TABLE``` можно изменить состав колонок и дополнительные параметры{% if backend_name == "YDB" %} [строковых](../../../../concepts/datamodel/table.md#row-tables) и [колоночн
```suggestion
При помощи команды ```ALTER TABLE``` можно изменить состав колонок и дополнительные параметры {% if backend_name == "YDB" %}[строковых](../../../../concepts/datamodel/table.md#row-tables) и [колоночных](../../../../concepts/datamodel/table.md#colums-tables) таблиц{% else %}таблиц {% endif %}. В одной команде можно указать несколько действий. В общем случае команда ```ALTER TABLE``` выглядит так:
```

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/rename.md
> +{% if backend_name == "YDB" %}
тоже лишний if

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/secondary_index.md
> +{% if backend_name == "YDB" %}
лишний if

2024-07-18 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/set.md
> +Большинство параметров строковых и колоночных таблиц в {{ ydb-short-name }}, приведенных на странице [описания таблицы]({{ concept_table }}), можно изменить командой ```ALTER```.
видимо всю эту страницу надо под `when` убрать раз она только про YDB?

2024-07-19 08:10 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/cdc.md
> +{% if backend_name == "YDB" %}
Да, согласен

2024-07-19 08:12 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/rename.md
> +{% if backend_name == "YDB" %}
Удалил

2024-07-19 08:12 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/secondary_index.md
> +{% if backend_name == "YDB" %}
Убрал

2024-07-19 08:15 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/set.md
> +Большинство параметров строковых и колоночных таблиц в {{ ydb-short-name }}, приведенных на странице [описания таблицы]({{ concept_table }}), можно изменить командой ```ALTER```.
Убрал под when.

2024-07-19 08:21 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/cdc.md
> +# Добавление или удаление потока изменений
Переименовал

2024-08-13 09:28 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +{% if backend_name == "YDB" %}
```suggestion
{% if oss == "true" and backend_name == "YDB" %}
```

2024-08-13 09:28 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/rename.md
> +{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}
```suggestion
{% if oss == "true" and backend_name == "YDB" %}

{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}

{% endif %}
```

2024-08-13 09:28 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/secondary_index.md
> +{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}
```suggestion
{% if oss == "true" and backend_name == "YDB" %}

{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}

{% endif %}
```

2024-08-13 09:28 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/secondary_index.md
> +{% if backend_name == YDB %}
```suggestion
{% if backend_name == "YDB" %}
```

2024-08-13 09:32 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}
```suggestion
{% if oss == "true" and backend_name == "YDB" %}

{% include [OLAP_not_allow_note](../../../../_includes/not_allow_for_olap_note.md) %}

{% endif %}
```

2024-08-13 09:40 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/toc_i.yaml
> +- { name: CDC,    href: changefeed.md,      when: feature_changefeed      }
```suggestion
- { name: CHANGEFEED,    href: changefeed.md,      when: feature_changefeed      }
```

2024-08-15 08:05 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +{% if oss == "true" and backend_name == "YDB" %}
```suggestion
{% if oss == true and backend_name == "YDB" %}
```

2024-08-15 08:06 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +{% if oss == "true" and backend_name == "YDB" %}
```suggestion
{% if oss == true and backend_name == "YDB" %}
```

2024-08-15 08:07 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/rename.md
> +{% if oss == "true" and backend_name == "YDB" %}
```suggestion
{% if oss == true and backend_name == "YDB" %}
```

2024-08-15 08:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/secondary_index.md
> +{% if oss == "true" and backend_name == "YDB" %}
```suggestion
{% if oss == true and backend_name == "YDB" %}
```

2024-08-15 08:29 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/set.md
> +* `TTL` — время жизни записи в таблицы:
```suggestion
Пример изменения параметра `TTL`, отвечающего за время жизни записей в таблицы:
```

2024-08-15 08:29 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/set.md
> +Сброс параметров `AUTO_PARTITIONING_BY_SIZE` и `AUTO_PARTITIONING_PARTITION_SIZE_MB` не поддерживается для колоночных таблиц.
```suggestion
```

2024-08-20 06:22 UTC, fomichev3000 approved these changes

2024-08-20 06:22 UTC, merged