Change TEvLocal actorsystem metrics
ydb-platform/ydb pull request #6355
Opened 2024-07-05 16:05 UTC by kruall

### Changelog entry 

...

### Changelog category 

* Bugfix 

### Additional information

...

2024-07-10 06:58 UTC, alexvru approved these changes, later dismissed

2024-07-10 07:17 UTC, vporyadke requested changes

2024-07-10 07:17 UTC, vporyadke commented on ydb/core/protos/local.proto
> +    optional TActorSystemInfo ActorSystemInfo = 9;
TEvStatus is sent when Local first registers in Hive, and when the tenant is altered. If we want this info to be sent regularly, I would put in TabletMetrics message.

2024-07-10 07:17 UTC, vporyadke commented on ydb/core/mind/local.cpp
> +    TInstant LastUpdate;
The name is confusing, last update of what? Also If we change it to use TabletMetrics message, there already is a SendTabletMetricsTime member

2024-07-10 07:17 UTC, vporyadke commented on ydb/core/mind/local.cpp
> +            if (poolId != AppData()->IOPoolId) {
We already have a setting PoolsToMonitorForUsage. I believe it should be used here. But it also excludes Batch pool by default - is there a reason you're including it here?

2024-07-10 07:42 UTC, vporyadke commented on ydb/core/protos/local.proto
> +message TActorSystemInfo {
Currently we send a single number TotalNodeUsage, that is the maximum over pool usages (and mem usage).
What do we expect to gain from sending this detailed info? Just seems like we will simply do the calculate usage + take maximum logic on Hive side instead.

2024-07-11 10:46 UTC, vporyadke approved these changes

2024-07-11 10:55 UTC, alexvru approved these changes

2024-07-11 10:59 UTC, merged