Rewrite YQL DML
ydb-platform/ydb pull request #6470
Opened 2024-07-09 11:06 UTC by Pseudolukian

### Changelog category 
* Documentation (changelog entry is not required)

2024-07-15 09:51 UTC, blinkov requested changes, later dismissed

2024-07-15 09:51 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
> +Вместо `DELETE FROM` для удаления данных из колоночных таблиц можно воспользоваться механизмом удаления строк по времени — [TTL](../../../../concepts/ttl.md). TTL можно задать при [создании](../creat
```suggestion
Вместо `DELETE FROM` для удаления данных из колоночных таблиц можно воспользоваться механизмом удаления строк по времени — [TTL](../../../../concepts/ttl.md). TTL можно задать при [создании](../create_table.md) таблицы через `CREATE TABLE` или [измененить позже](../alter_table.md) через `ALTER TABLE`.
```

2024-07-15 09:51 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +{% cut "Способы загрузки данных в колоночные таблицы" %}
это в каком-то из соседних PR переехало в include, надо не забыть поправить

2024-07-15 09:51 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +{% cut "Способы загрузки данных в колоночные таблицы" %}
или т.к. этот PR по-проще выглядит — можно в этом вынести в include, а в остальных уже заиспользовать

2024-07-15 09:52 UTC, blinkov commented
плюс конфликты зарезловить

2024-07-17 14:08 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/insert_into.md
> +{% cut "Способы загрузки данных в колоночные таблицы" %}
Зачекаутил ydb/docs/ru/core/_includes/not_allow_for_olap_note_main.md из Pseudolukian:ru/dev

2024-07-18 05:13 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/into_result.md
> +Позволяет задать пользовательскую метку для [SELECT](../select/index.md){% if feature_mapreduce and process_command == "PROCESS" %}, [PROCESS](../process.md) или [REDUCE](../reduce.md){% endif %}. Не
```suggestion
Позволяет задать пользовательскую метку для [SELECT](../select/index.md){% if feature_mapreduce and process_command == "PROCESS" %}, [PROCESS](../process.md) или [REDUCE](../reduce.md){% endif %}. {% if backend_name != "YDB" %}Не может быть задано одновременно с [DISCARD](../discard.md) {% endif %}.
```

2024-07-20 14:58 UTC, fomichev3000 approved these changes

2024-07-20 14:59 UTC, merged