Describe work with ldaps scheme and add information about nested groups
ydb-platform/ydb pull request #6489
Opened 2024-07-09 15:02 UTC by molotkov-and

2024-07-15 05:16 UTC, blinkov requested changes, later dismissed

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/concepts/auth.md
> +Для того чтобы {{ ydb-short-name }} автоматически установила зашифрованное соединение с LDAP сервером необходимо в [параметре конфигурации](../deploy/configuration/config.md#ldap-auth-config) **schem
```suggestion
Для того чтобы {{ ydb-short-name }} автоматически установила зашифрованное соединение с LDAP-сервером, необходимо в [параметре конфигурации](../deploy/configuration/config.md#ldap-auth-config) **scheme** установить значение `ldaps`. TLS-диалог будет инициирован на порту, указанном в конфигурации. Если порт не указан, для схемы `ldaps` будет применён порт по умолчанию 636. LDAP-сервер должен быть настроен на приём TLS-соединений на указанных портах.
```

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/concepts/auth.md
> +Другим способом установления защищенного соединения является выполнение запроса `StartTls`. Такой прием позволяет настроить TLS соединение на порту, который может использоваться и без шифрования. Для
Этот абзац (и его спойлер выше) звучит как-будто это пользователю надо отправить некий `StartTls` запрос куда-то, но не указано ни что это запрос, ни через какой API, ни как это делать и т.п. При этом по косвенным признакам в других частях этого патча можно догадаться, что всё же это не пользовать отправляет этот запрос, а YDB в LDAP-сервер. Если эта догадка верна, то я бы переформулировал описание этой фичи с «запроса StartTls» в что-то типа «апгрейд незашифрованного соединения до зашифрованного через StartTls».

Также не помешают рекомендации в каких случаях какую из этих двух опций использовать.

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`host` | Имя хоста, на котором работает LDAP сервер. Это устарелый параметр, вместо него должен использоваться параметр `hosts`
```suggestion
`host` | Имя хоста, на котором работает LDAP-сервер. Это устаревший параметр, вместо него должен использоваться параметр `hosts`.
```

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`host` | Имя хоста, на котором работает LDAP сервер. Это устарелый параметр, вместо него должен использоваться параметр `hosts`
давайте deprecated параметры вниз таблички унесём чтоб глаза не мозолили

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +    host: "ldap-hostname-01.example.net" # DEPRECATED: Use Hosts instead it
```suggestion
```

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`enable` | Определяет будет ли попытка установить TLS соединение с использованием запроса `StartTls`. При выставлении значения параметра в `true`, необходимо отключить использование схемы соединения
```suggestion
`enable` | Определяет, будет ли произведена попытка установить TLS-соединение с использованием запроса `StartTls`. При установке значения этого параметра в `true`, необходимо отключить использование схемы соединения `ldaps`, присвоив параметру `ldap_authentication.scheme` значение `ldap`.
```

2024-07-15 05:16 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`requested_group_attribute` | Атрибут обратного членства в группе. Если значение параметра пусто, то атрибутом обратного членства в группе будет `memberOf`
```suggestion
`scheme` | Схема соединения с LDAP-сервером.<br>Возможные значения:<ul><li>`ldap` — {{ ydb-short-name }} будет выполнять соединение с LDAP-сервером без какого-либо шифрования. Пароли будут отправляться на LDAP-сервер в открытом виде. Это значение установлено по умолчанию.</li><li>`ldaps` — {{ ydb-short-name }} будет выполнять зашифрованное соединение с LDAP-сервером по протоколу TLS с самого первого запроса. Для успешного установления соединения по схеме `ldaps` необходимо отключить использование запроса `StartTls` в секции `ldap_authentication.use_tls.enable: false` и заполнить информацию о сертификате `ldap_authentication.use_tls.ca_cert_file` и уровне требования сертификата `ldap_authentication.use_tls.cert_require`.</li><li>При использовании любого другого значения будет браться значение по умолчанию - `ldap`.</li></ul>
`requested_group_attribute` | Атрибут обратного членства в группе. По умолчанию `memberOf`.
```

2024-08-28 16:09 UTC, molotkov-and commented on ydb/docs/ru/core/concepts/auth.md
> +Другим способом установления защищенного соединения является выполнение запроса `StartTls`. Такой прием позволяет настроить TLS соединение на порту, который может использоваться и без шифрования. Для
Поправил

2024-08-28 16:19 UTC, molotkov-and commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`host` | Имя хоста, на котором работает LDAP сервер. Это устарелый параметр, вместо него должен использоваться параметр `hosts`
Поправил

2024-09-12 06:30 UTC, fomichev3000 requested changes
Прямо очень тяжело читается. 3 раза прочитал, понял приблизительно

2024-09-12 06:30 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/auth.md
> +* Явно выполнив запрос `StartTls`, после которого будет установлено зашифрованное соединение
Что это за запрос `StartTls`? Кто его посылает? Через что? Совсем не понятно

2024-09-17 10:50 UTC, molotkov-and commented on ydb/docs/ru/core/concepts/auth.md
> +* Явно выполнив запрос `StartTls`, после которого будет установлено зашифрованное соединение
Добавил более подробное описание StartTls

2024-09-23 02:55 UTC, blinkov commented on ydb/docs/ru/core/concepts/auth.md
> +#### Расширение LDAP протокола `StartTls`
```suggestion
#### Расширение LDAP протокола `StartTls` {#starttls}
```

2024-09-23 02:55 UTC, blinkov commented on ydb/docs/ru/core/concepts/auth.md
> +* Использование расширения LDAP протокола [`StartTls`](#расширение-ldap-протокола-starttls)
```suggestion
* Использование расширения LDAP протокола [`StartTls`](#starttls)
```

2024-09-23 02:55 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`enable` | Определяет, будет ли произведена попытка установить TLS-соединение с использованием запроса `StartTls`. При установке значения этого параметра в `true`, необходимо отключить использование
```suggestion
`enable` | Определяет, будет ли произведена попытка установить TLS-соединение с [использованием запроса `StartTls`](../../concepts/auth.md#starttls). При установке значения этого параметра в `true`, необходимо отключить использование схемы соединения `ldaps`, присвоив параметру `ldap_authentication.scheme` значение `ldap`.
```

2024-09-23 02:55 UTC, blinkov commented on ydb/docs/ru/core/deploy/configuration/config.md
> +`scheme` | Схема соединения с LDAP-сервером.<br>Возможные значения:<ul><li>`ldap` — {{ ydb-short-name }} будет выполнять соединение с LDAP-сервером без какого-либо шифрования. Пароли будут отправлять
```suggestion
`scheme` | Схема соединения с LDAP-сервером.<br>Возможные значения:<ul><li>`ldap` — {{ ydb-short-name }} будет выполнять соединение с LDAP-сервером без какого-либо шифрования. Пароли будут отправляться на LDAP-сервер в открытом виде. Это значение установлено по умолчанию.</li><li>`ldaps` — {{ ydb-short-name }} будет выполнять зашифрованное соединение с LDAP-сервером по протоколу TLS с самого первого запроса. Для успешного установления соединения по схеме `ldaps` необходимо отключить использование [запроса `StartTls`](../../concepts/auth.md#starttls) в секции `ldap_authentication.use_tls.enable: false` и заполнить информацию о сертификате `ldap_authentication.use_tls.ca_cert_file` и уровне требования сертификата `ldap_authentication.use_tls.cert_require`.</li><li>При использовании любого другого значения будет браться значение по умолчанию - `ldap`.</li></ul>
```

2024-09-23 02:55 UTC, blinkov commented on ydb/docs/ru/core/concepts/auth.md
> +`StartTls` это расширение LDAP протокола, используемое для шифрования сообщений по протоколу TLS. В общем случае, смысл использования расширения `StartTls` заключается в том, что в рамках одного соед
```suggestion
`StartTls` — это расширение протокола LDAP, используемое для шифрования сообщений по протоколу TLS. Оно позволяет передавать в рамках одного соединения с LDAP-сервером одни сообщения в зашифрованном виде, а другие — открыто. Сообщение с этим расширением отправляется от {{ ydb-short-name }} к LDAP-серверу для инициирования TLS-соединения. В случае {{ ydb-short-name }} не предусмотрено включение и выключение TLS-соединения в рамках одного соединения. Поэтому при использовании расширения `StartTls` после установления зашифрованного соединения {{ ydb-short-name }} будет отправлять все дальнейшие сообщения к LDAP-серверу в зашифрованном виде. Одним из преимуществ использования данного расширения вместо схемы `ldaps` (при соответствующей настройке LDAP-сервера) является возможность установить TLS-соединение на нешифрованном порту. Расширение включается в [секции `use_tls`](../deploy/configuration/config.md#ldap-auth-config) файла конфигурации.
```

2024-09-23 06:55 UTC, fomichev3000 approved these changes

2024-09-23 06:55 UTC, merged