Extend DisabledOnSchemeShard FF for column tables on dedicated bases
ydb-platform/ydb pull request #6498
Opened 2024-07-10 04:31 UTC by zverevgeny

2024-07-22 06:16 UTC, ivanmorozov333 approved these changes

2024-07-22 08:40 UTC, ijon requested changes

2024-07-22 08:40 UTC, ijon commented on ydb/core/tx/schemeshard/olap/operations/create_store.cpp
> +        if (AppData()->ColumnShardConfig.GetDisabledOnSchemeShard() && context.SS->OlapStores.empty()) {
Надо бы проверять одновременно и olap-stores, и column-tables?
То же самое в `create_table.cpp`

2024-07-22 08:59 UTC, ijon approved these changes

2024-07-23 05:14 UTC, zverevgeny commented on ydb/core/tx/schemeshard/olap/operations/create_store.cpp
> +        if (AppData()->ColumnShardConfig.GetDisabledOnSchemeShard() && context.SS->OlapStores.empty()) {
Это ослабит запрет. Мы же хотим запретить как можно больше, если клиент ещё не начал этим пользоваться

2024-07-23 05:15 UTC, merged