Add OLAP info to dev section
ydb-platform/ydb pull request #6565
Opened 2024-07-11 12:25 UTC by Pseudolukian

### Changelog category 
* Documentation (changelog entry is not required)

2024-07-15 09:33 UTC, blinkov requested changes

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/example-dotnet.md
> +Для создания строковых таблиц используется метод `session.ExecuteSchemeQuery` с DDL (Data Definition Language) YQL-запросом.
Аналогичный example-cpp.md вопрос: не понятно это про конкретно данный пример, либо в этот метод прямо по каким-то причинам нельзя передавать запросы с `WITH (STORE = COLUMN)`?

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/example-dotnet.md
> +Для создания строковых таблиц используется метод `session.ExecuteSchemeQuery` с DDL (Data Definition Language) YQL-запросом.
Похоже тут в примерах для всех языков эта же история, ниже не буду повторяться.

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/terraform.md
> +* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.html) колонки. Допускается использовать простые типы колонок. Как пример, контейнерные типы не могут быть использованы в ка
```suggestion
* `type` — (обязательный) [тип данных YQL](../yql/reference/types/primitive.md) колонки. Допускается использовать простые типы колонок. Как пример, контейнерные типы не могут быть использованы в качестве типов данных колонок строковых таблиц.
```

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
`PARTITION BY` видимо стоит ещё рекомендовать?

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +Создайте [строковые](../../concepts/datamodel/table.md#row-oriented-tables) или [колоночные](../../concepts/datamodel/table.md#column-oriented-tables) таблицы и задайте для них схемы данных с помощью
Вкратце объяснить в каких случаях что использовать и дать ссылку на подробности в концепциях.

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/yql-tutorial/select_all_columns.md
> +FROM <table_name>; -- Таблица, из которой нужно выбрать данные.
```suggestion
FROM `<table_name>`; -- Таблица, из которой нужно выбрать данные. 
```

2024-07-15 09:33 UTC, blinkov commented on ydb/docs/ru/core/dev/cdc.md
> +При создании потока изменений для строковой таблицы количество партиций его хранилища (топика) определяется на основании текущего количества партиций таблицы. Если количество партиций исходной строко
Прямо подряд N раз уточнять, что таблицы строковые странно читается — в подобных местах, где слово «таблица» часто используется, я б уточнял про строковость только при первом использовании, а не всех N.

Например:
```suggestion
При создании потока изменений для строковой таблицы количество партиций его хранилища (топика) определяется на основании текущего количества партиций таблицы. Если количество партиций исходной таблицы значительно изменяется (например, после загрузки большого объёма данных, или в результате интенсивных обращений), то возникает дисбаланс между партициями таблицы и партициями топика. Такой дисбаланс также может приводить к увеличению времени исполнения запросов на модификацию данных в таблице, либо к излишним накладным расходам на хранение потока изменений. Для устранения дисбаланса можно пересоздать поток изменений.
```

2024-07-15 09:33 UTC, blinkov commented
Плюс ещё конфликт нужно зарезолвить.

2024-07-16 17:22 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +Создайте [строковые](../../concepts/datamodel/table.md#row-oriented-tables) или [колоночные](../../concepts/datamodel/table.md#column-oriented-tables) таблицы и задайте для них схемы данных с помощью
Дополнил.

2024-07-16 17:33 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/auxilary/pragmatablepathprefix.md
> +`PRAGMA TablePathPrefix` добавляет указанный префикс к путям [строковых](../../../../concepts/datamodel/table.md#row-oriented-tables) и [колоночных](../../../../concepts/datamodel/table.md#column-ori
Откатил

2024-07-16 17:37 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
Что-то PARTITION BY не нагуглился в доке :(

2024-07-17 15:29 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
Ты имеешь в виду AUTO_PARTITIONING_BY_XX отсюда -- https://ydb.tech/docs/ru/concepts/datamodel/table ?

2024-07-18 05:25 UTC, blinkov submitted a review, later dismissed

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +Метод `CreateTable` не поддерживает создания колоночных таблиц. Их можно создать с помощью метода `ExecuteDataQuery`, который выполняет YQL-запросы:
```suggestion
Метод `CreateTable` не поддерживает создание колоночных таблиц. Их можно создать с помощью метода `ExecuteDataQuery`, который выполняет произвольные YQL-запросы:
```

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +Подробное использование метода `ExecuteDataQuery` описано в разделе [Запись данных](#write-queries) на примере выполнения YQL-команды `SELECT`.
очень странная фраза: SELECT — чтение данных, а не запись

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +С помощью метода `DescribeTable` можно вывести информацию о структуре строковой таблицы и убедиться, что она успешно создалась:
аналог для колоночных хорошо бы привести, если он существует

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/example-app/_includes/steps/03_write_queries.md
> +{% include [not_allow_for_olap](../../../../_includes/not_allow_for_olap_note_main.md) %}
давай уберём, тут и так вокруг везде написано, что пример только для строковых

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/terraform.md
> +* [индексы](../concepts/secondary_indexes.md) строковых таблиц;
```suggestion
* [вторичные индексы](../concepts/secondary_indexes.md) для строковых таблиц;
```

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +Создайте [строковые](../../concepts/datamodel/table.md#row-oriented-tables) таблицы для OLTP-операций или [колоночные](../../concepts/datamodel/table.md#column-oriented-tables) таблицы для OLAP-нагру
три ссылки на одну и ту же статью в одном абзаце — перебор, достаточно оставить только или в первом или в последнем предложении

2024-07-18 05:25 UTC, blinkov commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
https://ydb.tech/docs/ru/yql/reference/syntax/create_table#olap-tables

2024-07-18 09:33 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
А, понял. Кстати, `PARTITION BY` не обязательная штука и без неё всё взлетает, конечно, не понятно насколько далеко, но взлетает :)

2024-07-18 10:40 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +        PRIMARY KEY (series_id) -- Первичный ключ — это столбец или
Уточнил.

2024-07-18 10:43 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +Подробное использование метода `ExecuteDataQuery` описано в разделе [Запись данных](#write-queries) на примере выполнения YQL-команды `SELECT`.
Да, согласен. Убрал SELECT.

2024-07-18 10:48 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +С помощью метода `DescribeTable` можно вывести информацию о структуре строковой таблицы и убедиться, что она успешно создалась:
Уточню у Зверева или еще у кого, кто умеет в C++.

2024-07-18 10:56 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/steps/03_write_queries.md
> +{% include [not_allow_for_olap](../../../../_includes/not_allow_for_olap_note_main.md) %}
Ладно

2024-07-18 11:21 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +С помощью метода `DescribeTable` можно вывести информацию о структуре строковой таблицы и убедиться, что она успешно создалась:
Спросил у Мясникова. Он говорит, что специально не тестировал, но вроде должно работать с колоночными таблицами, созданными с помощью YQL.

2024-07-18 11:22 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/example-app/_includes/example-cpp.md
> +С помощью метода `DescribeTable` можно вывести информацию о структуре строковой таблицы и убедиться, что она успешно создалась:
Подправил.

2024-07-18 11:23 UTC, Pseudolukian commented on ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
> +Создайте [строковые](../../concepts/datamodel/table.md#row-oriented-tables) таблицы для OLTP-операций или [колоночные](../../concepts/datamodel/table.md#column-oriented-tables) таблицы для OLAP-нагру
Поправил

2024-08-16 00:50 UTC, blinkov commented on ydb/docs/ru/core/dev/query-plans-optimization.md
> +
```suggestion
```

2024-08-20 06:28 UTC, fomichev3000 approved these changes, later dismissed

2024-10-01 06:24 UTC, blinkov approved these changes

2024-10-01 06:24 UTC, merged