YDB_ACCESSORs
ydb-platform/ydb pull request #672
Opened 2023-12-22 14:06 UTC by azevaykin

Add YDB_ACCESSORs to reduce header size

2023-12-22 14:18 UTC, CyberROFL requested changes

2023-12-22 14:18 UTC, CyberROFL commented on ydb/core/tx/datashard/write_unit.cpp
> +        writeOp->SetWriteResult(NEvents::TDataEvents::TEvWriteResult::BuildCommited(self->TabletID(), writeOp->GetTxId()));
Почему не write{Op,Tx}->GetTabletId()?

2023-12-22 18:30 UTC, azevaykin commented on ydb/core/tx/datashard/write_unit.cpp
> +        writeOp->SetWriteResult(NEvents::TDataEvents::TEvWriteResult::BuildCommited(self->TabletID(), writeOp->GetTxId()));
В образце именно из текущей таблетки:
https://github.com/ydb-platform/ydb/blob/62cecf285c847b309e820250768963b70cadf0dc/ydb/core/tx/datashard/execution_unit.cpp#L283-L284

2023-12-22 18:35 UTC, azevaykin commented on ydb/core/tx/datashard/write_unit.cpp
> +        writeOp->SetWriteResult(NEvents::TDataEvents::TEvWriteResult::BuildCommited(self->TabletID(), writeOp->GetTxId()));
И в целом поискал по `new TEvDataShard::TEvProposeTransactionResult` : везде идёт текущая таблетка.

2023-12-22 18:52 UTC, azevaykin commented on ydb/core/tx/datashard/write_unit.cpp
> +        writeOp->SetWriteResult(NEvents::TDataEvents::TEvWriteResult::BuildCommited(self->TabletID(), writeOp->GetTxId()));
И ещё немного подумал, убрал полностью TabletId из WriteOperation. См второй коммит в данном PR.

2023-12-25 12:42 UTC, CyberROFL approved these changes

2023-12-25 12:42 UTC, merged