YDB FQ: Connector new oracle datasource integration
ydb-platform/ydb pull request #6723
Opened 2024-07-16 08:39 UTC by lifthelm

### Changelog entry 

...

### Changelog category 

* New feature

### Additional information

C++ integration of new connector datasource - Oracle

2024-07-16 11:48 UTC, vitalyisaev2 requested changes

2024-07-16 11:48 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
> +            return;
В общем случае SERVICE_NAME является необязательным,  поэтому именно здесь ошибку можно не бросать. 

Но вот уже после парсинга (вот [тут](https://github.com/ydb-platform/ydb/blob/6e66aa6ca4d5118ba7cfdf2ee9e45322431ab4f4/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L402-L416)) у нас есть функция валидации, где я бы проверил, что если тип источника данных - Oracle, значит, service_name должен быть заполнен: https://github.com/ydb-platform/ydb/blob/6e66aa6ca4d5118ba7cfdf2ee9e45322431ab4f4/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L402-L416

Также предлагаю сделать валидацию для Oracle источников и в [Коннекторе](https://github.com/ydb-platform/fq-connector-go/blob/4fe181abaf39aec255aacaa1b18744ee8dc91c9a/app/server/validate.go#L104-L119)

2024-07-16 11:48 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +        void GetServiceName(T& request, const TGenericClusterConfig& clusterConfig) {
1. Наверное, не Get, а Set
2. Шаблон тут не нужен. Тебя, скорее всего, сбила с толку аналогичная функция для схемы (шаблон там из-за разных типов опций у PG/CH, да и то, надо проверить, нельзя ли так обойтись).

2024-07-16 11:48 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                serviceName = it->second;
зачем отдельная переменная? можно же сразу `  request.set_service_name(it->second);`

2024-07-16 16:13 UTC, dorooleg commented on ydb/library/yql/providers/generic/connector/api/common/data_source.proto
> +        TOracleDataSourceOptions ora_options = 11;
а разве для orcacle есть сокращение ora?

2024-07-16 16:15 UTC, dorooleg commented on ydb/core/external_sources/external_source_factory.cpp
> +            ToString(NYql::EDatabaseType::Oracle),
Сюда по хорошему нужна валидация для обязательных параметров

2024-07-17 09:03 UTC, lifthelm commented on ydb/core/external_sources/external_source_factory.cpp
> +            ToString(NYql::EDatabaseType::Oracle),
Валидация на наличие данного поля добавлена в yql_generic_cluster_config.cpp

https://github.com/ydb-platform/ydb/blob/c3d8428f937a4b6ae00de32b1538e0beb5933a4a/ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp#L414-L423

2024-07-17 13:19 UTC, lifthelm commented on ydb/core/external_sources/external_source_factory.cpp
> +            ToString(NYql::EDatabaseType::Oracle),
Добавил проверку

https://github.com/ydb-platform/ydb/blob/376081ca2102a7439671d56d29730915ff8f3eda/ydb/core/external_sources/external_data_source.cpp#L60-L63

2024-07-17 13:20 UTC, lifthelm commented on ydb/library/yql/providers/generic/connector/api/common/data_source.proto
> +        TOracleDataSourceOptions ora_options = 11;
Изменил название на oracle_options

2024-07-17 14:38 UTC, vitalyisaev2 approved these changes

2024-07-17 16:51 UTC, dorooleg approved these changes

2024-07-18 10:00 UTC, vitstn approved these changes

2024-07-18 10:09 UTC, merged