Ability for ydb-cli to write request results as arrow parquet
ydb-platform/ydb pull request #673
Opened 2023-12-22 14:25 UTC by iddqdex

Copy of arcadia PR: https://a.yandex-team.ru/review/4966527/details

2023-12-22 16:30 UTC, CyberROFL requested changes

2023-12-22 16:30 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/format.h
> +#include <ydb/library/arrow_parquet/result_set_parquet_printer.h>
Можно сделать forward declaration и не тащить эту зависимость в заголовочном файле. Тогда и сборка будет чуточку быстрее.

2023-12-22 16:30 UTC, CyberROFL commented on ydb/library/arrow_parquet/result_set_parquet_printer.h
> +#include <ydb/public/sdk/cpp/client/ydb_result/result.h>
Можно сделать forward declaration и не тащить эту зависимость в заголовочном файле. Тогда и сборка будет чуточку быстрее.

2023-12-22 16:30 UTC, CyberROFL commented on ydb/library/arrow_parquet/result_set_parquet_printer.h
> +        explicit TResultSetParquetPrinter(const TString& outputPath, ui64 rowGroupSize = 100000);
Константу `100000` нужно вынести в единое место.

2023-12-22 16:30 UTC, CyberROFL commented on ydb/docs/ru/core/reference/ydb-cli/yql.md
> +`--format` | Формат вывода.<br>Возможные значения:<ul><li>`pretty` (по умолчанию) — человекочитаемый формат;</li><li>`json-unicode` — вывод в формате [JSON]{% if lang == "ru" %}(https://ru.wikipedia.
1. Очень сложно увидеть, где тут дифф.
Может быть стоит предварительно отрефакторить этот абзац, поделив его на строки? \n в документации != <br> (поэтому тут он выписан явно).

2. Копи-паста. +1 к предварительному рефакторингу.

2023-12-23 04:34 UTC, iddqdex commented on ydb/docs/ru/core/reference/ydb-cli/yql.md
> +`--format` | Формат вывода.<br>Возможные значения:<ul><li>`pretty` (по умолчанию) — человекочитаемый формат;</li><li>`json-unicode` — вывод в формате [JSON]{% if lang == "ru" %}(https://ru.wikipedia.
К сожалению, переносы строк тут влияют. 
![image](https://github.com/ydb-platform/ydb/assets/150132506/82104429-0d2c-468e-a750-c6e486213a7e)

2023-12-25 10:04 UTC, CyberROFL commented on ydb/docs/ru/core/reference/ydb-cli/yql.md
> +`--format` | Формат вывода.<br>Возможные значения:<ul><li>`pretty` (по умолчанию) — человекочитаемый формат;</li><li>`json-unicode` — вывод в формате [JSON]{% if lang == "ru" %}(https://ru.wikipedia.
От копи-пасты всё равно нужно избавиться (желательно в отдельном pr с рефакторингом).

2023-12-25 10:09 UTC, CyberROFL commented on ydb/library/arrow_parquet/result_set_parquet_printer.h
> +#include <string>
Между этими строчками не хватает пустой строки.

2023-12-25 10:09 UTC, CyberROFL commented on ydb/library/arrow_parquet/result_set_parquet_printer.h
> +        ~TResultSetParquetPrinter();
`= default;`? Тогда не придется писать пустой деструктор в cpp-файле.

2023-12-25 14:29 UTC, iddqdex commented on ydb/library/arrow_parquet/result_set_parquet_printer.h
> +        ~TResultSetParquetPrinter();
А он там нужен, чтобы Holder работал с forward-декларацией. Иначе он пытается собрать деструктор там, где не знает, что такое TImpl, расстраивается и падает.

2023-12-26 08:47 UTC, spuchin approved these changes

2023-12-26 14:42 UTC, CyberROFL approved these changes

2023-12-26 14:42 UTC, merged