YDB FQ: docs for MySQL as an external datasource
ydb-platform/ydb pull request #6737
Opened 2024-07-16 13:03 UTC by vitalyisaev2

### Changelog entry 

* YDB FQ: docs for MySQL as an external datasource

### Changelog category 

* Documentation (changelog entry is not required)

2024-07-17 02:52 UTC, blinkov requested changes

2024-07-17 02:52 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/mysql.md
> +1. Создать [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую базу данных в составе кластера MySQL. Параметр `LOCATION` содержит сетевой адрес экземпляра MySQL,
```suggestion
1. Создайте [внешний источник данных](../datamodel/external_data_source.md), описывающий определённую MySQL базу данных. Параметр `LOCATION` содержит сетевой адрес экземпляра MySQL, к которому осуществляется подключение. В `DATABASE_NAME` указывается имя базы данных (например, `mysql`). Для аутентификации во внешнюю базу используются значения параметров `LOGIN` и `PASSWORD_SECRET_NAME`. Включить шифрование соединений к внешней базе данных можно с помощью параметра `USE_TLS="TRUE"`.
```

2024-07-17 02:52 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/mysql.md
> +|`varbinary`|`Optional<Utf8>`||
Звучит подозрительно — либо тут должен быть `Optional<String>`, либо пояснение что будет, если в значении окажется мусор вместо UTF-8.

2024-07-17 10:16 UTC, vitalyisaev2 commented on ydb/docs/ru/core/concepts/federated_query/mysql.md
> +|`varbinary`|`Optional<Utf8>`||
Да, согласен. Здесь меня сбил с толку [драйвер](https://github.com/go-mysql-org/go-mysql/issues/770) Go к MySQL: там значения колонок `binary` и `varbinary` значения появляются именно в виде юникодовых строк, а не байтов. Заменил на `Optional<String>` (код коннектора тоже приведу в соответствие в ближайшее время).

2024-07-18 05:31 UTC, blinkov requested changes, later dismissed

2024-07-18 05:31 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +# Working with MySQL Databases
```suggestion
# Working with MySQL databases
```

2024-07-18 05:31 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +1. Create an [external data source](../datamodel/external_data_source.md) that describes a specific MySQL database. The `LOCATION` parameter contains the network address of the MySQL instance to conn
```suggestion
1. Create an [external data source](../datamodel/external_data_source.md) that describes a specific MySQL database. The `LOCATION` parameter contains the network address of the MySQL instance to connect to. The `DATABASE_NAME` specifies the database name (for example, `mysql`). The `LOGIN` and `PASSWORD_SECRET_NAME` parameters are used for authentication to the external database. You can enable encryption for connections to the external database using the `USE_TLS="TRUE"` parameter.
```

2024-07-18 05:31 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +The following SQL query format is used with MySQL:
```suggestion
The following SQL query format is used to work with MySQL:
```

2024-07-18 05:31 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +- `<table_name> - the name of the table within the external data source.
```suggestion
- `mysql_datasource` - the external data source identifier;
- `<table_name> - the table name within the external data source.
```

2024-07-18 05:31 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +In the MySQL database, the optionality of column values (whether the column can contain `NULL` values or not) is not a part of the data type system. The `NOT NULL` constraint for any column of any ta
```suggestion
In the MySQL database, the optionality of column values (whether the column can contain `NULL` values or not) is not a part of the data type system. The `NOT NULL` constraint for any column of any table is stored within the `IS_NULLABLE` column the [INFORMATION_SCHEMA.COLUMNS](https://dev.mysql.com/doc/refman/8.4/en/information-schema-columns-table.html) system table, i.e., at the table metadata level. Therefore, all basic MySQL types can contain `NULL` values by default, and in the {{ ydb-full-name }} type system they should be mapped to [optional](https://ydb.tech/docs/ru/yql/reference/types/optional).
```

2024-07-18 05:32 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/mysql.md
> +## Query Syntax { #query }
```suggestion
## Query syntax { #query }
```

2024-07-20 15:10 UTC, fomichev3000 approved these changes

2024-07-22 09:28 UTC, merged