Added import s3 to directory
ydb-platform/ydb pull request #678
Opened 2023-12-22 17:13 UTC by Gazizonoki

2023-12-22 17:33 UTC, pnv1 approved these changes

2023-12-22 18:14 UTC, CyberROFL requested changes

2023-12-22 18:14 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.cpp
> +    TString Bucket;
const

2023-12-22 18:14 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.cpp
> +        Aws::Vector<Aws::S3::Model::Object> objects = response.GetResult().GetContents();
Для чего нужен этот временный объект?

2023-12-22 18:14 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.cpp
> +        Aws::S3::Model::ListObjectsV2Request request;
Обычно мы пишем так:
```cpp
auto request = Aws::S3::Model::ListObjectsV2Request()
    .WithBucket(Bucket)
    .WithPrefix(prefix);
```

2023-12-22 18:14 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +    const TString suffix = "scheme.pb";
На эту тему есть константа, надо использовать ее.

2023-12-22 18:14 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +    auto s3Client = CreateS3ClientWrapper(settings);
Вроде клиента можно создать позже.

2023-12-25 10:19 UTC, CyberROFL requested changes

2023-12-25 10:19 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.h
> +    virtual std::pair<std::vector<TString>, std::optional<TString>> ListObjectKeys(const TString& prefix, const std::optional<TString>& token) = 0;
Может все-таки структуру тут возвращать? Просто читая код, сходу непонятно что здесь что. Нужно лезть в cpp-файл и там смотреть. Со структурой было бы сразу понятно:
```cpp
struct TListResult {
    std::vector<TString> Keys;
    std::optional<TString> NextToken;
};
```

2023-12-25 10:19 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.h
> +#include <ydb/public/sdk/cpp/client/ydb_import/import.h>
С forward declaration можно не включать этот файл здесь. И сборка будет чуточку быстрее.

2023-12-25 10:19 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.cpp
> +                                   true);
Как будто верстка поехала.

2023-12-25 10:19 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
Зачем?

2023-12-25 10:19 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +                        TString source = key.substr(0, key.Size() - suffixSize);
Не проще здесь использовать `ChopSuffix()`?

2023-12-27 15:20 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/common/aws.h
> +#include <ydb/public/sdk/cpp/client/ydb_import/import.h>
Я файл fwd.h в SDK не нашел. Писать forward declaration будет норм в этом header файле? Просто оно же потом инклюдиться другими файлами будет, по сути ничего же не ломается?

2023-12-27 15:28 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
Ой, это я хотел из h файла инклюд убрать и в cpp файл перенести, а в итоге из хедера убрать его я забыл

2023-12-27 16:13 UTC, CyberROFL requested changes

2023-12-27 16:13 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/common/aws.cpp
> +        return {keys, nextToken};
Нужно либо сразу заполнять поля в ListS3Result, либо перемещать временные объекты.

2023-12-27 16:13 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +                        settings.AppendItem({TString(key), std::move(destination)});
Если итерироваться по ключам, как по TString& (или auto&), то тут можно сразу переместить, вместо копирования.

2023-12-27 16:19 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +                        settings.AppendItem({TString(key), std::move(destination)});
И вообще, тут только при построении destination копирования остались, там их уж не убрать никак

2023-12-27 16:21 UTC, Gazizonoki commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +                        settings.AppendItem({TString(key), std::move(destination)});
И как я key передам, если я key не чистый должен передать, а без суффикса "suffix.pb"

2023-12-27 16:41 UTC, CyberROFL commented on ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
> +                        settings.AppendItem({TString(key), std::move(destination)});
А, ну да. Тут ведь key уже после преобразований.

2023-12-27 16:43 UTC, CyberROFL approved these changes

2023-12-27 19:44 UTC, merged