avoid unsigned integer underflow
ydb-platform/ydb pull request #6787
Opened 2024-07-17 12:49 UTC by eivanov89

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-17 13:04 UTC, maximyurchuk commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
> +    outLastSectorIdx = (offset + size) / sectorPayloadSize;
Ой, они unsigned, соррян

Но все равно не надо ли здесь проверять на переполнение?

2024-07-17 22:47 UTC, maximyurchuk commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
> +    if (offset != 0 || size != 0) {
Ну а точно это все надо? Как мне кажется весь файл в подобных проблемах, не уверен, что качество кода улучшается от исправления одной такой проблемы (смотри например line 395).

Мне кажется если и чинить, то системно, например прикрутить фаззинг. Как мне кажется он должен тут  нормально налезть и найти прилично проблем

2024-07-29 08:05 UTC, alexvru requested changes

2024-07-29 08:05 UTC, alexvru commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
> +    if (offset != 0 || size != 0) {
Вообще говоря, тут size всегда не должен быть равен 0, сдаётся мне. Иначе смысл операции, когда у нас нулевая длина?

2024-09-20 14:53 UTC, closed without merging