YQ-3345 support load cpu threshold (#6360)
ydb-platform/ydb pull request #6790
Opened 2024-07-17 14:04 UTC by GrigoriyPA

- **YQ-3345 support load cpu threshold (#6360)**
- **YQ-3345 fixed WM counters and unit test (#6643)**

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-17 14:29 UTC, maximyurchuk requested changes
Напишите плз, зачем это нужно в 24-3

2024-07-18 07:07 UTC, GrigoriyPA commented
> Напишите плз, зачем это нужно в 24-3

Эти изменения нужны в пределах задачи [YQ-3222](https://st.yandex-team.ru/YQ-3222): workload manager v1 (YDB DWH к скейлу), все фичи которые должны быть к скейлу согласовали с @fomichev3000 в этой дельте:
https://delta.yandex-team.ru/page/epad/page/oq95gk1890527ptp

Ещё нужно будет доделать изменения по этим тикетам:
* [YQ-3442](https://st.yandex-team.ru/YQ-3442): Оптимизировать default pool
* [YQ-3444](https://st.yandex-team.ru/YQ-3444): Пробросить pool id из connection string
* [YQ-3445](https://st.yandex-team.ru/YQ-3445): Добавить фича флаг для sls баз
* [YQ-3446](https://st.yandex-team.ru/YQ-3446): Добавить время ожидания в очереди в статистику 
* [YQ-3447](https://st.yandex-team.ru/YQ-3447): Поддержать ydb scheme ls для resource pool

2024-07-25 10:37 UTC, alexv-smirnov approved these changes

2024-07-25 13:54 UTC, maximyurchuk approved these changes

2024-07-25 13:55 UTC, merged