imporve failsafe on cuttting history
ydb-platform/ydb pull request #6918
Opened 2024-07-22 08:20 UTC by vporyadke

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-05 08:31 UTC, vporyadke commented
https://wiki.yandex-team.ru/users/zalyalov/kak-upravljat-otkljucheniem-ochistki-istorii/

2024-08-08 15:33 UTC, ijon requested changes
Не хватает теста на deny/allow списки -- на парсинг и поведение

2024-08-08 15:33 UTC, ijon commented on ydb/core/mind/hive/hive_impl.h
> +        }
Здесь в `(found != denyList.end())` и `(found == allowList.end())` сравнения не надо ли поменять на противоположные?
Сейчас получается:
- разрешить, если есть в deny-list
- запретить, если нет в allow-list

2024-08-13 10:03 UTC, vporyadke commented
> https://wiki.yandex-team.ru/users/zalyalov/kak-upravljat-otkljucheniem-ochistki-istorii/

тоже чуть-чуть обновил

2024-08-21 15:26 UTC, ijon approved these changes

2024-08-21 19:02 UTC, merged