WideCombiner with spilling better buffer pass
ydb-platform/ydb pull request #7022
Opened 2024-07-23 19:50 UTC by lll-phill-lll

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-24 12:03 UTC, Tony-Romanov requested changes

2024-07-24 12:03 UTC, Tony-Romanov commented on ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
> +        None
Это не None а скорее ReadInput. Только в этом случае мы же читаем вход.

2024-07-24 13:59 UTC, lll-phill-lll commented on ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
> +        None
Да, согласен
Перенес туда еще немного логики, которая за другими ифами пряталась. Спасибо за комментарий

2024-07-24 14:06 UTC, Tony-Romanov approved these changes

2024-07-25 07:58 UTC, Darych approved these changes

2024-07-25 08:34 UTC, merged