Async replication docs
ydb-platform/ydb pull request #7110
Opened 2024-07-25 15:12 UTC by CyberROFL

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-07-26 08:19 UTC, blinkov requested changes
Раздел с синтаксисом сейчас не успеваю доревьюить, публикую комментарии по концепциям.

2024-07-26 08:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Подробнее про классы ошибок и политики их обработки см. в разделе [Обработка ошибок](../reference/ydb-sdk/error_handling.md).
```suggestion
В процессе асинхронной репликации возможно возникновение различных классов ошибок:

* **Временные сбои**. Например, транспортные ошибки, перегрузка системы и т.д. Запросы будут повторяться до успешного выполнения.
* **Критичные ошибки**. Например, ошибки прав доступа, ошибки схемы и т.д. Процесс репликации будет остановлен, и в [описании](../reference/ydb-cli/commands/scheme-describe.md) экземпляра репликации будет указан текст ошибки.

{% note warning %}

Остановленный из-за критичной ошибки процесс асинхронной репликации не может быть перезапущен.

{% endnote %}

Подробнее о классах ошибок и политике их обработки см. в разделе [Обработка ошибок](../reference/ydb-sdk/error_handling.md).
```

2024-07-26 08:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Остановленный из-за ошибки процесс асинхронной репликации не может быть перезапущен.
Звучит фатально... Тут бы какие-то рекомендации что с этим впринципе дальше делать. Запускать всё заново в новую целевую таблицу?

Также видимо нужна отдельная статья про то, как делать алерты на такие события, на которую отсюда сослаться.

2024-07-26 08:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
```suggestion
Процесс асинхронной репликации может быть завершён (например, как один из последних шагов при переносе данных между базами). При завершении:

* В исходных таблицах удаляются потоки изменений.
* В исходных таблицах разблокируется возможность изменения состава столбцов.
* Объекты-реплики становятся доступными как для чтения, так и для записи.

{% note warning %}

На данный момент поддерживается только **принудительное** завершение асинхронной репликации, при котором не производится никаких дополнительных проверок (на консистентность данных, отставание данных и т.д.).

{% endnote %}

Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
```

2024-07-26 08:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +При удалении асинхронной репликации:
Не понятно в чём отличие удаления и завершения, т.к. списки побочных эффектов почти идентичны. Хорошо б прямым текстом эту разницу проговорить. Я б предположил, что удалить = завершить + дропнуть объекты-реплики, но тоже как-будто не сходится.

2024-07-26 09:12 UTC, blinkov requested changes, later dismissed

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +## См. также
Вообще хорошо б ещё соорудить отдельную практическую статью-инструкцию, которая начинается с «вот у меня есть две пустые базы» и заканчивается «вот в каждой из них есть по одинаковой таблице, которые реплицируются, можно проверить вставив строчку в одну и прочитав из другой». 

Можно в отдельном PR, но я б не затягивал и к заявлению о готовности фичи её тоже постарался успеть опубликовать.

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +* `CASCADE` — каскадное удаление объектов-реплик, созданных в рамках данного экземпляра асинхронной репликации.
в концепциях вроде было написано, что ещё удаляются потоки изменений — видимо стоит про них тут тоже явно написать, всегда ли это происходит или только с cascade

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +CREATE ASYNC REPLICATION `my_replication`
выглядит как копипаста из соседней статьи, если это и правда так — лучше вынести в include

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Создание экземпляра асинхронной репликации для таблиц `table1` и `table2`:
```suggestion
Создание экземпляра асинхронной репликации для двух пар таблиц, из `table1` в `replica_table1` и из `table2` в `replica_table2`:
```

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `PASSWORD_SECRET_NAME` — имя [секрета](../../../concepts/datamodel/secrets.md), содержащего пароль.
стоит явно обозначить что тут обязательное, а что — нет

2024-07-26 09:12 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет реплицировать данные между базами данных {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для переноса данных между базами с минимальн
а в одной базе исходные и целевые таблицы могут располагаться?

2024-07-26 09:16 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +3. Репликация изменений.
Из списка понятно, сколько стадий. Зачем указывать их количество перед перечислением? Текущая версия лучше тем, что она порождает меньший дифф при изменении числа стадий.

2024-07-26 09:16 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +3. Репликация изменений.
Ссылки добавлю, спасибо.

2024-07-26 09:17 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Установка соединения с источником.
Нет, шагов может быть сколько угодно. Это сейчас выделены и описаны 2.

2024-07-26 09:18 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Пользователь, от имени которого производится подключение к источнику, должен обладать следующими [правами](../security/short-access-control-notation.md#access-rights):
Нет короткой нотации для создания/изменения/удаления/чтения потоков изменений, поэтому и не стал приводить.

2024-07-26 09:19 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Объекты-реплики создаются от имени пользователя, создавшего экземпляр асинхронной репликации.
Они создаются автоматически. Здесь просто fyi, под каким пользователем они будут созданы.

2024-07-26 09:20 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Первоначальные данные исходных таблиц отгружаются в потоки изменений с использованием [первоначального сканирования](cdc.md#initial-scan). Прогресс первоначального сканирования можно получить из [опи
Нет.

2024-07-26 09:21 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +* `name` — имя экземпляра асинхронной репликации.
https://ydb.tech/docs/ru/yql/reference/syntax/create_table
https://ydb.tech/docs/ru/yql/reference/syntax/alter_table

2024-07-26 09:22 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +* `CASCADE` — каскадное удаление объектов-реплик, созданных в рамках данного экземпляра асинхронной репликации.
Непонятно, зачем дублировать информацию? Если поведение поменяется, нужно будет поправить одно место в документации, а не два.

2024-07-26 09:24 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +CREATE ASYNC REPLICATION `my_replication`
В предыдущей статье конкретные примеры создания репликации и конкретные описания того, что при этом происходит. Здесь более-менее абстрактный пример для демонстрации удаления.

2024-07-26 09:25 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Создание экземпляра асинхронной репликации для таблиц `table1` и `table2`:
Зачем уточнять количество?

2024-07-26 09:26 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет реплицировать данные между базами данных {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для переноса данных между базами с минимальн
Могут, но особого смысла такая конфигурация не имеет, поэтому лучше её не описывать и не продвигать.

2024-07-26 09:28 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `PASSWORD_SECRET_NAME` — имя [секрета](../../../concepts/datamodel/secrets.md), содержащего пароль.
Как это сделать для mutually exclusive параметров?

2024-07-26 09:31 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +3. Репликация изменений.
* «состоит» имхо лучше, чем «можно разделить» т.к. «можно» читается как-будто можно и не разделять, а «разделить» — не понятно кто разделяет
* «трёх» можно было б заменить на «следующих», но короче и для тех кому этот контент сложно читается чуток успокаивает, что всего 3, а не условно 17

2024-07-26 09:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Установка соединения с источником.
тут примерно та же история, что и в https://github.com/ydb-platform/ydb/pull/7110/files#r1692629898

2024-07-26 09:34 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Прочитанные читателями данные записываются в объекты-реплики.
Важно, я дочитал до конца и не понял) Догадываюсь только по каким-то предыдущим встречам, где эта фича обсуждалась, а не этому PR.

2024-07-26 09:35 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Установка соединения с источником.
Вводное предложение добавил.

2024-07-26 09:36 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `PASSWORD_SECRET_NAME` — имя [секрета](../../../concepts/datamodel/secrets.md), содержащего пароль.
возможно есть способ лучше, но как минимум можно просто на 22 строке написать, что это обязательно, а что речь об одном из подпунктов там уже написано

2024-07-26 09:36 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * объекты-реплики (в приемнике).
Вообще это отдельный шаг инициализации, поэтому он в виде продолжения списка.

2024-07-26 09:58 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Во время работы асинхронной репликации объекты-реплики доступны только для чтения.
В какой момент начали писать ё в документации?

2024-07-26 10:04 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +При удалении асинхронной репликации:
Я могу написать, что при удалении асинхронной репликации удаляется экземпляр асинхронной репликации, но это будет масло масляное.

При завершении, очевидно, экземпляр не удаляется.

2024-07-26 10:05 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +* `SET (option = value [, ...])` — [параметры](#params) асинхронной репликации.
Написано так же, как в соседних статьях:
* https://ydb.tech/docs/ru/yql/reference/syntax/create-view
* https://ydb.tech/docs/ru/yql/reference/syntax/create-topic

2024-07-26 10:09 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +FOR remote_path AS local_path [, another_remote_path AS another_local_path]
Во всех соседних статьях по-разному. Где-то `_`, где-то `-`, где-то с `<>`, где-то без. Какой рекомендуемый формат? Есть тикет на приведение к единообразному виду?

2024-07-26 10:10 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +* `CONNECTION_STRING` — [строка соединения](../../../concepts/connect.md#connection_string) c базой-источником.
На кого завести тикет?

2024-07-26 10:40 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `PASSWORD_SECRET_NAME` — имя [секрета](../../../concepts/datamodel/secrets.md), содержащего пароль.
Можешь привести конкретный пример?
> Настройки для аутентификации в базе-источнике одним из способов. Обязательный параметр:

Выглядит так себе.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Из-за противопоставления, звучит так, что синхронная репликация как-то включается и настраивается а-ля Postgres.
Как вариант, я бы вообще убрал отсюда синхронную репликацию.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +2. **Приёмник** — база данных, в которой будут созданы **экземпляр репликации** и **объекты-реплики**.
Я бы пояснил понятия **экземпляр репликации** и **объекты-реплики**.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +При удалении асинхронной репликации:
Присоединюсь к Ивану, тоже заметил, что завершение и удаление это примерно одно и тоже. Так то иначе нужно это описать.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +## Завершение асинхронной репликации {#done}
Если тут не удаляется экземпляр асинхронной репликации, то пользователь наверняка захочет его запустить заново. Как это сделать?

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +* [Создания экземпляра асинхронной репликации](../yql/reference/syntax/create-async-replication.md) в приемнике.
Ниже красиво написано:

> Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](https://ydb-platform--ydb.viewer.diplodoc.com/ru/yql/reference/syntax/alter-async-replication).

Я бы тут ровно такой же стиль бы использовал.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Не хватает более подробного описания, как устроена асинхронная репликация.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +* В качестве исходных объектов поддерживаются:
Я бы вынес это наверх, где вводятся понятия.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +FOR remote_path AS local_path [, another_remote_path AS another_local_path]
> Какой рекомендуемый формат? 

Единообразный вид можно взять отсюда. Везде нижнее подчеркивание. То есть, сейчас соответствует.
https://github.com/azevaykin/ydb/blob/main/ydb/library/yql/sql/v1/SQLv1.g.in

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Перед созданием экземпляра асинхронной репликации [создайте](create-object-type-secret.md) секрет с аутентификационными данными для подключения или убедитесь в его существовании и наличии доступа к н
Есть ссылка, что как создать секрет.
Нет ссылки, откуда брать аутентификационные данные, которые будут положены в секрет. Если это OAuth токен, то об этом явно нужно сказать.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Перед созданием экземпляра асинхронной репликации [создайте](create-object-type-secret.md) секрет с аутентификационными данными для подключения или убедитесь в его существовании и наличии доступа к н
Если нет авторизации на кластере, то секреты не работают.
Ты раньше говорил, что тогда нужно использовать `TOKEN = "root@builtin"`

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +  * `DONE` — [завершение процесса асинхронной репликации](../../../concepts/async-replication.md#done).
А как заново включить процесс репликации?
Экземпляр же не удален.

2024-07-27 17:52 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +## См. также
Присоединяюсь.

И в том, что такая статья нужна.
И в том, что в отдельном PR до анонса фичи.

2024-07-28 11:52 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Перед созданием экземпляра асинхронной репликации [создайте](create-object-type-secret.md) секрет с аутентификационными данными для подключения или убедитесь в его существовании и наличии доступа к н
Выше есть ссылки на способы аутентификации.

2024-07-28 11:53 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +### Репликация изменений {#replication-of-changes}
Потому что больше тут сказать нечего :)

2024-07-28 11:53 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * [директории](datamodel/dir.md) — их cодержимое будет «развёрнуто» до списка строковых таблиц в момент создании экземпляра асинхронной репликации.
Если в директории есть строковые таблицы, то именно они будут реплицироваться.

2024-07-28 11:54 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
Может привести пример?

2024-07-28 11:54 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +## Завершение асинхронной репликации {#done}
Никак, добавлю плашку.

2024-07-28 11:55 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Для начала пока так. Со временем можно дополнять.

2024-07-28 11:56 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* В качестве исходных объектов поддерживаются:
Нелогично получается. Тут оно смотрится органично.

2024-07-28 11:56 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +  * `DONE` — [завершение процесса асинхронной репликации](../../../concepts/async-replication.md#done).
Добавлю плашку.

2024-07-28 12:40 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +### Репликация изменений {#replication-of-changes}
Ну, хоть одно-два предложения, что читатели получают изменения из топиков и складывают в таблицу-приемник.

2024-07-28 12:41 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * [директории](datamodel/dir.md) — их cодержимое будет «развёрнуто» до списка строковых таблиц в момент создании экземпляра асинхронной репликации.
Вот так уже более понятно звучит. Лучше в такой формулировке.

2024-07-28 12:42 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
Именно

2024-07-28 12:52 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
У тебя тут написано, что она позволяет делать, но нет ни слова, как она это делает.

В CDC понятнее написано, что именно делается. Там два абзаца во введении и они хорошие. По их подобию можно.

В идеале, картинка с источником, приемником, топиком посередине хорошо помогла бы.

2024-07-28 12:56 UTC, azevaykin commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Перед созданием экземпляра асинхронной репликации [создайте](create-object-type-secret.md) секрет с аутентификационными данными для подключения или убедитесь в его существовании и наличии доступа к н
Стал внимательно искать, нашел. Сразу в глаза не бросается. Я бы повторил ссылку именно со словами OAuth.

2024-07-28 20:36 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +## См. также
Есть отдельная статья про миграцию — для начала ссылки будут в ней.

2024-07-28 20:37 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * потоки изменений (в источнике);
"Потоки изменений" описаны в разделе CDC.
Объекты-реплики — вроде тут все понятно?

2024-07-29 10:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
в каком-то смысле у нас синхронная тоже как-то включается и настраивается: типовой путь случайного прохожего, зашедшего в доку, зачастую начинается с однонодного quickstart на коленке, а только потом уже предлагают подумать о разворачивании отказоустойчивого production кластера

2024-07-29 10:33 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет реплицировать данные между базами данных {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для переноса данных между базами с минимальн
как-будто не исправлено

2024-07-29 10:34 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +2. **Приёмник** — база данных, в которой будут созданы **экземпляр репликации** и **объекты-реплики**.
+1, для связанности https://github.com/ydb-platform/ydb/pull/7110#discussion_r1692627680

2024-07-29 10:34 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +* База, в которой будут созданы _экземпляр репликации_ и _объекты-реплики_ (база-_приемник_).
@CyberROFL не исправлено

2024-07-29 10:36 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +3. Репликация изменений.
@CyberROFL а почему в итоге заменил на непронумерованный список, а вводное предложение как-будто не поменялось?

2024-07-29 10:39 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Пользователь, от имени которого производится подключение к источнику, должен обладать следующими [правами](../security/short-access-control-notation.md#access-rights):
а зачем тогда на эту нотацию ссылаться?

если перечислить тут конкретные названия прав не получается, то я б пока эту ссылку удалил, но в практическом руководстве по теме они всё равно явно понадобятся, вместе с примерами выдающих их запросов

2024-07-29 10:43 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * объекты-реплики (в приемнике).
тогда давай этот `{% note info %}` выше вынесем из середины списка — из-за него не понятно, что это продолжение того же списка

2024-07-29 10:45 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Объекты-реплики создаются от имени пользователя, создавшего экземпляр асинхронной репликации.
```suggestion
При создании экземпляра асинхронной репликации объекты-реплики создаются автоматически. Это происходит от имени того же пользователя, который создаёт данный экземпляр.
```

2024-07-29 10:47 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * потоки изменений (в источнике);
@CyberROFL в глоссарий всякое такое надо, даже если догадаться не очень сложно

см. https://github.com/ydb-platform/ydb/pull/7110#discussion_r1692635850

2024-07-29 10:47 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * объекты-реплики (в приемнике).
@CyberROFL не сделано

2024-07-29 10:47 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Прочитанные читателями данные записываются в объекты-реплики.
@CyberROFL не вижу что было сделано по этой теме

2024-07-29 10:49 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Во время работы асинхронной репликации объекты-реплики доступны только для чтения.
@CyberROFL наверное когда я начал ей заниматься

2024-07-29 10:49 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Остановленный из-за ошибки процесс асинхронной репликации не может быть перезапущен.
@CyberROFL не вижу что было сделано по этой теме

2024-07-29 10:52 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +При удалении асинхронной репликации:
> Я могу написать, что при удалении асинхронной репликации удаляется экземпляр асинхронной репликации, но это будет масло масляное.
> 
> При завершении, очевидно, экземпляр не удаляется.

Хоть так, но лучше ещё какой-то практический замысел объяснить: в каких случаях пользователю может понадобиться завершенный экземпляр, с которым как-будто мало что можно сделать?

2024-07-29 10:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +* `CONNECTION_STRING` — [строка соединения](../../../concepts/connect.md#connection_string) c базой-источником.
там вроде всего один абзац, я б предложил просто заодно с переводом этого текста его перевести

2024-07-29 10:56 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет реплицировать данные между базами данных {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для переноса данных между базами с минимальн
Да, и "resolve conversation" тоже не нажато.

2024-07-29 10:57 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +* `CASCADE` — каскадное удаление объектов-реплик, созданных в рамках данного экземпляра асинхронной репликации.
@CyberROFL т.к. пользователей мог читать концепции давно и когда пошёл реально писать запрос по этой справке уже забыть, либо вообще мог полениться читать концепции, т.к. они получились длинными

2024-07-29 10:59 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Создание экземпляра асинхронной репликации для таблиц `table1` и `table2`:
@CyberROFL  исходный вариант можно ошибочно проинтерпретировать как «из table1 в table2»

2024-07-29 10:59 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +3. Репликация изменений.
Вводное предложение исправил на 

> Процесс асинхронной репликации состоит из следующих стадий:

Нумерованный список считаю здесь лишним, потому что деление условное.

2024-07-29 11:00 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +    * `PASSWORD_SECRET_NAME` — имя [секрета](../../../concepts/datamodel/secrets.md), содержащего пароль.
> Настройки для аутентификации в базе-источнике одним из способов *(обязательно)*:

2024-07-29 11:00 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Пользователь, от имени которого производится подключение к источнику, должен обладать следующими [правами](../security/short-access-control-notation.md#access-rights):
> а зачем тогда на эту нотацию ссылаться?

Чтобы было понятно, о каких правах вообще речь.

2024-07-29 11:05 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Объекты-реплики создаются от имени пользователя, создавшего экземпляр асинхронной репликации.
Тогда можно подумать, что потоки изменений создаются не автоматически. Сделал так:

> Для заданного набора исходных объектов автоматически создаются:                                                       
> * потоки изменений (в источнике);                                                                                     
> * объекты-реплики (в приемнике).

А плашку оставил как есть.

2024-07-29 11:09 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +* `CONNECTION_STRING` — [строка соединения](../../../concepts/connect.md#connection_string) c базой-источником.
Я точно забуду.

2024-07-29 11:13 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * объекты-реплики (в приемнике).
Эта плашка идет сразу после пункта про установку соединения. Плохо ставить между ними другой абзац.

2024-07-29 11:55 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Прочитанные читателями данные записываются в объекты-реплики.
> Как было выше не хватает какого-то вводного предложения перед этим списком.

Вводное предложение добавлено.

2024-07-29 11:56 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Прочитанные читателями данные записываются в объекты-реплики.
Про "запускаются" и "записываются" по-прежнему не понимаю, что именно ты хочешь увидеть?

2024-07-29 11:58 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Во время работы асинхронной репликации объекты-реплики доступны только для чтения.
Я раньше всегда ставил "ё". Потом все "ё" заменили на "е". Теперь предлагается обратно? Предлагаю отдельно.

2024-07-29 12:01 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Остановленный из-за ошибки процесс асинхронной репликации не может быть перезапущен.
Дополнил плашку.

2024-07-29 12:06 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Создание экземпляра асинхронной репликации для таблиц `table1` и `table2`:
Поправил.

2024-07-29 12:09 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Точно нужно противопоставление, чтобы было понятно, почему нужно два типа репликации.

2024-07-29 12:13 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +### Репликация изменений {#replication-of-changes}
> читатели получают изменения из топиков и складывают в таблицу-приемник

Добавил.

2024-07-29 12:13 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * [директории](datamodel/dir.md) — их cодержимое будет «развёрнуто» до списка строковых таблиц в момент создании экземпляра асинхронной репликации.
Вроде так и написано... "содержимое будет развернуто до списка строковых таблиц"

2024-07-29 12:15 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +Перед созданием экземпляра асинхронной репликации [создайте](create-object-type-secret.md) секрет с аутентификационными данными для подключения или убедитесь в его существовании и наличии доступа к н
Тут нельзя писать OAuth, потому что пользователь мог выбрать другой способ аутентификации.

2024-07-29 13:16 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +* `CASCADE` — каскадное удаление объектов-реплик, созданных в рамках данного экземпляра асинхронной репликации.
Дополнил.

2024-07-29 13:17 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * потоки изменений (в источнике);
Добавил в глоссарий.

2024-07-29 13:19 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +При удалении асинхронной репликации:
Дописал про сценарий миграции.

2024-07-29 13:20 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * объекты-реплики (в приемнике).
Сделано.

2024-07-29 13:21 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +* База, в которой будут созданы _экземпляр репликации_ и _объекты-реплики_ (база-_приемник_).
Исправлено.

2024-07-29 13:21 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет реплицировать данные между базами данных {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для переноса данных между базами с минимальн
Исправлено.

2024-07-29 13:41 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
М?

2024-07-30 02:45 UTC, blinkov commented on ydb/docs/ru/core/concepts/async-replication.md
> +Для завершения асинхронной репликации используйте выражение [ALTER ASYNC REPLICATION](../yql/reference/syntax/alter-async-replication.md).
Полные примеры со всеми параметрами явно не помешали бы, но я бы не запихивал их в концепции — для этого надо как раз написать отдельную практическую статью и обильно на неё ссылаться.

2024-07-30 02:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-async-replication.md
> +* `CONNECTION_STRING` — [строка соединения](../../../concepts/connect.md#connection_string) c базой-источником.
https://github.com/ydb-platform/ydb/pull/7226

2024-07-30 05:57 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +1. **Источник** — база данных с исходными объектами.
объект сделать ссылкой на термин в глоссарии, который ты создал

2024-07-30 05:59 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +После завершения первоначального сканирования читатели получают только данные об изменениях и записывают их в объекты-реплики. Для каждого изменения известно *время его возникновения* ($created\_at$)
```suggestion
После завершения первоначального сканирования читатели получают только данные об изменениях и записывают их в объекты-реплики. 
Для каждого изменения известно *время его возникновения* ($created\_at$). В то же время читатели отслеживают *время получения* изменения ($received\_at$). Таким образом, *отставание репликации* может быть вычислено по формуле:
```

2024-07-30 06:05 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +* Во время работы асинхронной репликации объекты-реплики доступны только для чтения.
Кстати, не упомянуть ли более сложные вещи? 

Что насчет согласованности данных по времени? "Согласованность в конечном счете" ?
Что насчет согласованности данных между разными шардами одной таблицы-приемника?

Использование таблиц-приемников возможно только в режиме [Stale Read Only](https://ydb.tech/docs/ru/concepts/_includes/transactions#modes) ?

2024-07-30 06:06 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +На данный момент остановленный из-за критичной ошибки процесс асинхронной репликации не может быть перезапущен. Его нужно [удалить](../yql/reference/syntax/drop-async-replication.md) и [создать](../y
Как пользователю понять, что процесс репликации остановился с ошибкой?

2024-07-30 06:06 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +Процесс асинхронной репликации можно завершить (остановить без возможности возобновить). Завершение асинхронной репликации используется в конце процедуры миграциии между базами данных. При завершении
```suggestion
Процесс асинхронной репликации можно завершить (без возможности возобновить). Завершение асинхронной репликации используется в конце процедуры миграциии между базами данных. При завершении:
```

2024-07-30 06:14 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * [директории](datamodel/dir.md) — их cодержимое будет «развёрнуто» до списка строковых таблиц в момент создании экземпляра асинхронной репликации.
```suggestion
  * [директории](datamodel/dir.md) — будут реплицироваться все строковые таблицы в данной директории. Список таблиц получается на момент создания асинхронной репликации.
```

2024-07-30 06:14 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +  * [директории](datamodel/dir.md) — их cодержимое будет «развёрнуто» до списка строковых таблиц в момент создании экземпляра асинхронной репликации.
```suggestion
  * [директории](datamodel/dir.md) — будут реплицироваться все строковые таблицы в данной директории. Список таблиц получается на момент создания асинхронной репликации.
```

2024-07-30 06:15 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Поддерживаю вопрос, полезная штука PlantUML.

2024-07-30 06:20 UTC, azevaykin commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
> Тут ведь целый раздел посвящен тому, как оно работает. Называется "Принцип работы".

Поиск по слову "топик" ничего не дал. А это важная архитектурная особенность: захватываешь изменения, кладёшь в топик, вычитываешь и кладешь в таблицу.  Да, это есть в CDC, на который ты сослался, но это повторить тут важные вещи точно не будет лишним.

Именно в этом месте один абзац + картинка напрашиваются.

2024-07-30 08:57 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +На данный момент остановленный из-за критичной ошибки процесс асинхронной репликации не может быть перезапущен. Его нужно [удалить](../yql/reference/syntax/drop-async-replication.md) и [создать](../y
В предыдущем абзаце написано.

2024-07-30 09:09 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Не топики, а потоки изменений — они упомянуты и на них есть ссылка. И ровно так и написано: читаем из потока изменений и пишем в объекты-реплики. Мне не нравится идея запихивать целый раздел в одно-два предложения во вступлении, потому что там вводится целый ряд терминов. С картинкой идея нравится.

2024-08-01 17:19 UTC, fomichev3000 requested changes

2024-08-01 17:19 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +Асинхронная репликация позволяет синхронизировать данные между [базами данных](glossary.md#database) {{ ydb-short-name }} почти в реальном времени. Также она может быть использована для миграции межд
> Также она может быть использована для миграции ДАННЫХ между базами данных

2024-08-01 17:19 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Ой, тут прямо путаница. Если говорим про синхронную репликацию, то надо сказать, что это элемент отказоустойчивости базы/кластера. А асинхронная прямо совсем про другое. Иначе прямо читатель в непонятках

2024-08-01 17:19 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/async-replication.md
> +## Принцип работы {#how-it-works}
я бы сделал картинку. Показал бы, что приемник "тянет" данные из источника, то есть pull, а не push.

2024-08-01 17:19 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +* `FAILOVER_MODE` — режим переключения состояния. Применимо только совместно с параметром `STATE`. Возможные значения:
Не понятна семантика. Я прям не понял, что оно означает. В примере как будто обе опции одновременно надо использовать, по одной смысла нет? confusing

2024-08-27 12:02 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +В отличие от синхронной [репликации](glossary.md#replication), реализованной в [распределенном хранилище](glossary.md#distributed-storage-implementation) и оперирующей бинарными данными, асинхронная
Чтобы не смущать, пока убрал это предложение.

2024-08-27 12:46 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +* `FAILOVER_MODE` — режим переключения состояния. Применимо только совместно с параметром `STATE`. Возможные значения:
Дописал.

2024-08-27 12:46 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +## Принцип работы {#how-it-works}
Готово.

2024-08-29 12:53 UTC, fomichev3000 approved these changes, later dismissed
Я ОК. Но в рамках дополнительного коммита поправил бы указанные замечания

2024-08-29 12:53 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +### Параметры {#params}
Возможно стоит добавить плашку про то, что в будущем планируются дополнительные опции, например чтобы gracefully завершать репликацию. Зачем? Сейчас немного странно выглядит, что для выполнения одного действия (завершения репликации) надо 2 параметра указывать.

2024-08-29 12:53 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +CREATE ASYNC REPLICATION `my_replication`
я бы предпочел без бэктиков. Достаточно только `table` поменять на original_table.

2024-08-29 14:17 UTC, blinkov approved these changes

2024-08-29 14:17 UTC, merged

2024-08-29 20:27 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +### Параметры {#params}
Такая плашка есть в статье об асинхронной репликации в разделе "Завершение асинхронной репликации". Отсюда есть ссылка на этот раздел. Дублировать предупреждение не хотелось бы.

2024-08-29 20:30 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +CREATE ASYNC REPLICATION `my_replication`
Для консистентности могу все примеры переделать без бэктиков, но, кажется, с ними универсальнее — если пользователь скопирует запрос и поменяет имя объекта, запрос отработает даже в случае коллизии с ключевым словом.

2024-08-29 20:43 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/async-replication.md
> +Процесс асинхронной репликации можно завершить, без возможности возобновить. Завершение асинхронной репликации используется в конце процедуры миграциии данных между базами данных. При завершении:
https://github.com/ydb-platform/ydb/pull/8503

2024-08-30 05:48 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-async-replication.md
> +### Параметры {#params}
Это ты знаешь, а пользователь -- не факт :)

2024-08-30 09:57 UTC, CyberROFL commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-async-replication.md
> +CREATE ASYNC REPLICATION `my_replication`
https://github.com/ydb-platform/ydb/pull/8516