Add options deprecation support to dynconfig
ydb-platform/ydb pull request #7162
Opened 2024-07-27 12:43 UTC by Enjection

### Changelog entry 

- fix config apply behavior
- add reserved prefixes generation to plugin
- use deprecated options in dynconfig

### Changelog category 

* New feature

### Additional information

...

2024-07-27 22:03 UTC, maximyurchuk commented on ydb/core/protos/feature_flags.proto
> +    reserved "SomeRemovedFeatureFlagExample";
Если правильно понимаю, то помимо 
`reserved 42`
Можно стало писать 
`reserved "some_value_str"`

Как мне кажется стоит писать их рядом с reserved'ами по чиселкам, а не в отдельном загоне, причем желательно в одной строке, чтобы можно было избавится от коммента, то есть вместо 
```
reserved 62; // EnablePredicateExtractForScanQueries
```
Писать что-то типа 
```
reserved 62, "EnablePredicateExtractForScanQueries"; 
```
Сложно так сделать?

2024-07-27 23:09 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
> +            TMap<TString, std::pair<TString, TString>> deprecatedFields;
На уровне протобафа это не deprecated, а reserved, предлагаю не вносить новые понятия на этом уровне

2024-07-27 23:15 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
> +            bool hasForbiddenUnknown = false;
Какую дополнительную семантику вносит слово forbidden? Мне кажется никакую, предлагаю назвать просто hasUnknown

2024-07-28 14:23 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +            Header->Print(vars, "inline static const std::unordered_set<TString>& GetReservedChildrenPaths() {\n");
Не знаю как принято, но как будто метод должен быть const

2024-07-28 14:38 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
>                      auto cfg = NYamlConfig::YamlToProto(
А почему это логика не на уровне YamlToProto ? (или может быть еще ниже) 

Как мне кажется по смыслу это больше подходит

2024-07-28 14:50 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +                Header->Print(vars, "static const std::unordered_set<TString>& reserved = {\n");
Мне кажется & тут ни к чему

2024-07-28 15:10 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +    using TOnEntryFn = std::function<void(const Descriptor*, const TDeque<const Descriptor*>&, const TDeque<const FieldDescriptor*>&, const FieldDescriptor*, ssize_t)>;
Но это же просто копипаста 
https://github.com/ydb-platform/ydb/blob/474343553b68f5058df323253438c2326dbbf206/ydb/core/config/utils/config_traverse.cpp#L16

2024-07-28 15:18 UTC, maximyurchuk requested changes
Предлагаю обсудить замечания в ПР и по возможности исправить

2024-07-28 16:19 UTC, Enjection commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +    using TOnEntryFn = std::function<void(const Descriptor*, const TDeque<const Descriptor*>&, const TDeque<const FieldDescriptor*>&, const FieldDescriptor*, ssize_t)>;
Это правда, пока предварительно так закинул, там нужно немного порефакторить и переиспользовать.

2024-07-28 16:20 UTC, Enjection commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +                Header->Print(vars, "static const std::unordered_set<TString>& reserved = {\n");
Она нужна -- мы в статической функции возвращаем некий контнейнер, **который нет смысла копировать**, при этом он константный, что бы пользователь с ним ничего не сделал.

2024-07-28 16:21 UTC, Enjection commented on ydb/core/cms/console/console__replace_yaml_config.cpp
>                      auto cfg = NYamlConfig::YamlToProto(
На уровень YamlToProto это будет спускаться позже, когда static и dynamic конфиги окончательно объединятся, сейчас для них несколько разные возможности. StaticConfig сейчас строже.

2024-07-28 16:22 UTC, Enjection commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +            Header->Print(vars, "inline static const std::unordered_set<TString>& GetReservedChildrenPaths() {\n");
так static же. У неё и так нет экзепмляра класса.

2024-07-28 16:23 UTC, Enjection commented on ydb/core/cms/console/console__replace_yaml_config.cpp
> +            bool hasForbiddenUnknown = false;
unknownfields это прорастает из самого unknownFieldsCollector, т.е. они неизвестные, но ещё не рассортированы на те, что потенциально разрешены и те что мы пропустим с warning.

2024-07-28 16:24 UTC, Enjection commented on ydb/core/cms/console/console__replace_yaml_config.cpp
> +            TMap<TString, std::pair<TString, TString>> deprecatedFields;
protobuf в нашем случае по сути dsl. Мы осознанно преименовываем это, что бы пользователю были понятны намерения. Т.е. в коде мы можем писать и reserved, а пользоваться им будем лишь как deprecated (на самом деле там есть ещё один потенциальный use case, но решил начать с малого).

2024-07-28 16:25 UTC, Enjection commented on ydb/core/protos/feature_flags.proto
> +    reserved "SomeRemovedFeatureFlagExample";
Не уверен, что в одной строчке можно писать и цифровой и символьный reserved, попробую. Но в общем смысле делать reserved на цифровой тэг для yaml конфига нет смысла.

2024-07-29 08:36 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +            Header->Print(vars, "inline static const std::unordered_set<TString>& GetReservedChildrenPaths() {\n");
У меня питон головного мозга, сорри

2024-07-29 08:40 UTC, maximyurchuk commented on ydb/core/protos/feature_flags.proto
> +    reserved "SomeRemovedFeatureFlagExample";
Ну хочется чтобы инфа про вырезанные поля была локальной: сейчас же ты позволяешь разбрасывать инфу про резервы по всему файлу, если этого можно было бы избежать было бы круто

2024-07-29 08:41 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +                Header->Print(vars, "static const std::unordered_set<TString>& reserved = {\n");
Если ты в объявлении переменной уберешь амперсанд то вроде поведение останется прежним

2024-07-29 08:42 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
>                      auto cfg = NYamlConfig::YamlToProto(
А статический конфиг не обучится в новые резервы автоматически?

2024-07-29 10:47 UTC, maximyurchuk commented on ydb/core/protos/feature_flags.proto
> +    reserved "SomeRemovedFeatureFlagExample";
Решили отдельно попробовать

2024-07-29 10:47 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
>                      auto cfg = NYamlConfig::YamlToProto(
Нет, решили сделать отдельно

2024-07-29 10:47 UTC, maximyurchuk commented on ydb/core/config/tools/protobuf_plugin/main.cpp
> +                Header->Print(vars, "static const std::unordered_set<TString>& reserved = {\n");
Поправлено

2024-07-29 10:47 UTC, maximyurchuk commented on ydb/core/cms/console/console__replace_yaml_config.cpp
> +            TMap<TString, std::pair<TString, TString>> deprecatedFields;
Решили оставить как есть

2024-07-29 10:48 UTC, maximyurchuk approved these changes

2024-07-29 10:55 UTC, CyberROFL approved these changes

2024-07-29 21:09 UTC, merged