integrations and ide
ydb-platform/ydb pull request #7222
Opened 2024-07-29 18:30 UTC by SloNN

* Documentation (changelog entry is not required)

2024-07-30 03:44 UTC, blinkov requested changes

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +В этом документе описан процесс подключения с помощью DBeaver, но подключение в рамках любой системы, поддерживающей источники данных JDBC, выполняется аналогично.
Тут не стыкуется логика повествования: JDBC и IDE не имеют ничего общего, кроме того, что есть несколько популярных IDE, написанных на Java, и, как следствие, их разработчикам не сложно было поддержать произвольные СУБД через JDBC.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +# Подключение с помощью IDE
Исторически папка integrations имеет плоскую структуру просто т.к. подстраниц было по пальцам пересчитать, но сейчас уже их прилично накопилось и можно начинать создавать структуру. В частности:

* Подобный вводный текст хорошо бы смотрелся в `integrations/ide/index.md`
* Соответственно, остальной текст ниже стал бы `integrations/ide/dbeaver.md`
* В следующих сериях можно будет сделать в понятным образом по аналогии `integrations/ide/datagrip.md`

То же самое касается и добавляемых рядом BI системами — их лучше в `integrations/bi/`.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +[DBeaver](https://dbeaver.com) — бесплатный кроссплатформенный инструмент управления базами данных с открытым исходным кодом, который обеспечивает удобный интерфейс для подключения к различным базам
```suggestion
## DBeaver {#dbeaver}

[DBeaver](https://dbeaver.com) — бесплатный кроссплатформенный инструмент управления базами данных с открытым исходным кодом, обеспечивающий удобный интерфейс для подключения к различным базам данных и выполнения SQL-запросов. Он поддерживает множество баз данных, включая MySQL, PostgreSQL, Oracle, SQLite и другие.
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. Выберите последний релиз (отмечен тегом `Latest`) и сохраните файл `ydb-jdbc-driver-shaded-<driver-version>.jar`.
```suggestion
### Скачивание JDBC-драйвера {#jdbc}

Для подключения к {{ ydb-name }} из DBeaver понадобится JDBC-драйвер.

Для скачивания драйвера выполните следующие шаги:
1. Перейдите в [репозиторий ydb-jdbc-driver](https://github.com/ydb-platform/ydb-jdbc-driver/releases).
2. Выберите последний релиз (отмечен тегом `Latest`) и сохраните файл `ydb-jdbc-driver-shaded-<driver-version>.jar`.
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. В подразделе **Общие**, в поле ввода **JDBC URL**, укажите следующий путь:
```suggestion
1. В подразделе **Общие**, в поле ввода **JDBC URL**, укажите следующую строку соединения:
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +    - `ydb_endpoint` — эндпойнт кластера {{ydb-name}}, к которому будут выполняться подключение.
```suggestion
    - `ydb_endpoint` — [эндпойнт](../concepts/connect.md#endpoint) кластера {{ydb-name}}, к которому будут выполняться подключение.
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +    - `ydb_database` — путь к базе данных в кластере {{ydb-name}}, к которой будут выполняться запросы к {{ ydb-name }}.
```suggestion
    - `ydb_database` — путь к [базе данных](../concepts/glossary.md#database) в кластере {{ydb-name}}, к которой будут выполняться запросы.
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. В поля `Пользователь` и `Пароль` введите логин и пароль для подключения к базе данных. Полный список способов и строк подключения к {{ydb-name}} приведен в описании [JDBC-драйвера](https://github.
```suggestion
1. В поля **Пользователь** и **Пароль** введите логин и пароль для подключения к базе данных. Полный список способов аутентификации и строк подключения к {{ ydb-name }} приведён в описании [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver).
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [FineBI](https://intl.finebi.com) | Через [PostgreSQL-совместимость](https://ydb.tech/docs/ru/postgresql/intro) | [Инструкция](./finebi.md) |
пустые файлы лучше даже под if'ами не коммитить, в репозитории и без того свалка

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| ydb-rs-sdk | Rust |  [Репозиторий](https://github.com/ydb-platform/ydb-rs-sdk) |
Про SDK есть отдельный большой раздел https://ydb.tech/docs/en/reference/ydb-sdk/ — ни к чему это тут дублировать. Максимум можно внизу сделать раздел «See also» и дать там эту ссылку.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [JetBrains DataGrip](https://www.jetbrains.com/ru-ru/datagrip/) |  [Инструкция](connect-from-ide.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
Про DataGrip и прочее я б не писал пока не появится инструкции про них.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +### Работа с {{ ydb-name }} {#dbeaver_ydb_connection}
Наверняка в этой интеграции есть какие-то ограничения — хорошо б их явно перечислить.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| Другие JDBC-совместимые клиенты | [Инструкция](connect-from-ide.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
Доку по тому как настраивать JDBC в общем случае хорошо б вообще перенести из README.md в основной репозиторий, но лучше не в этом PR.

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +{% if ydb-finebi %}
как-будто не то имя переменной

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +## Оркестрация {#scheduling}
почему не `{#orchestration}` тогда?

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [{{ airflow-name }}](https://airflow.apache.org) |   [Инструкция](airflow.md) |
как-будто ячейка от второй колонки потерялась

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [FluentBit](https://fluentbit.io) | [Инструкция](fluent-bit.md) |
это тоже по подпапочкам разложить бы, если возьмёшься за них, но тут ещё redirects.yaml важно не забыть проапдейтить

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +{% endnote %}
```suggestion
{% note info %}

В дополнение к своему нативному протоколу, основанному на gRPC, {{ ydb-name }} позволяет внешним системам подключаться к базам данных по сетевым протоколам [PostgreSQL](../postgresql/intro.md) или [Apache Kafka](../reference/kafka-api/index.md). Благодаря этим слоям совместимости множество инструментов, разработанных для работы с этими системами, могут также взаимодействовать с {{ ydb-name }}. Уровень совместимости каждого конкретного приложения необходимо уточнять отдельно.

{% endnote %}
```

2024-07-30 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +|  Среда | Инструкция | Описание |
Третья колонка не очень похожа на описание, больше выглядит как «Уровень поддержки» ниже.

2024-07-30 08:31 UTC, SloNN commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +В этом документе описан процесс подключения с помощью DBeaver, но подключение в рамках любой системы, поддерживающей источники данных JDBC, выполняется аналогично.
а что именно не стыкуется, не уловил? в YDB есть JDBC. Есть IDE поддерживающие этот протокол. Описано подключение через DBeaver, поддерживающего его

2024-07-30 08:32 UTC, SloNN commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +# Подключение с помощью IDE
Давай я пока оставлю как есть, а когда буду добавить superset/finebi и остальное, то сгруппирую

2024-07-30 08:32 UTC, SloNN commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. Выберите последний релиз (отмечен тегом `Latest`) и сохраните файл `ydb-jdbc-driver-shaded-<driver-version>.jar`.
Тогда уж "установка JDBC-драйвера"

2024-07-30 08:34 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +| [{{ airflow-name }}](https://airflow.apache.org) |   [Инструкция](airflow.md) |
поправил, спасибо. но оно пока не рендерится, поэтому визуально было не заметно

2024-07-30 08:49 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +| [JetBrains DataGrip](https://www.jetbrains.com/ru-ru/datagrip/) |  [Инструкция](connect-from-ide.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
а там все идентично с точностью до UI

2024-07-30 08:55 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +| ydb-rs-sdk | Rust |  [Репозиторий](https://github.com/ydb-platform/ydb-rs-sdk) |
не знал про него.

2024-07-30 09:01 UTC, SloNN commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +### Работа с {{ ydb-name }} {#dbeaver_ydb_connection}
уточнил явно - говорят, что известных ограничений нет. баги есть, которые к скейлу будут поправлены, а ограничений нет

2024-07-30 09:21 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +# Подключение с помощью IDE
хотя б эту статью давай сразу в `integrations/ide/dbeaver.md` положим, чтобы редиректы со старого урла не делать

2024-07-30 09:23 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. Выберите последний релиз (отмечен тегом `Latest`) и сохраните файл `ydb-jdbc-driver-shaded-<driver-version>.jar`.
в моём понимании установка в следующем разделе когда ты его подключаешь к IDE, а тут просто файлик скачивается

2024-07-30 09:24 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [JetBrains DataGrip](https://www.jetbrains.com/ru-ru/datagrip/) |  [Инструкция](connect-from-ide.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
значит не сложно будет сделать аналогичную инструкцию

2024-07-30 09:31 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +### Работа с {{ ydb-name }} {#dbeaver_ydb_connection}
ok

2024-07-30 12:05 UTC, blinkov commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +В этом документе описан процесс подключения с помощью DBeaver, но подключение в рамках любой системы, поддерживающей источники данных JDBC, выполняется аналогично.
@SloNN этот текст звучит как-будто JDBC является чем-то специфическим для IDE, а также нет и никогда не будет IDE, работающими с YDB каким-либо другим способом.

2024-08-06 08:35 UTC, SloNN commented on ydb/docs/ru/core/integrations/connect-from-ide.md
> +1. Выберите последний релиз (отмечен тегом `Latest`) и сохраните файл `ydb-jdbc-driver-shaded-<driver-version>.jar`.
Назвал Подключение JDBC-драйвера

2024-08-07 02:52 UTC, blinkov requested changes, later dismissed

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +[DBeaver](https://dbeaver.com) — бесплатный кроссплатформенный инструмент управления базами данных с открытым исходным кодом, обеспечивающий удобный интерфейс для подключения к различным базам данных
```suggestion
# Подключение к {{ ydb-short-name }} с помощью DBeaver

[DBeaver](https://dbeaver.com) — бесплатный кроссплатформенный инструмент управления базами данных с открытым исходным кодом, обеспечивающий визуальный интерфейс для подключения к различным базам данных и выполнения SQL-запросов. Он поддерживает множество систем управления базами данных, включая MySQL, PostgreSQL, Oracle и SQLite.

DBeaver позволяет работать с {{ ydb-short-name }} по протоколу Java DataBase Connectivity ([JDBC](https://ru.wikipedia.org/wiki/Java_Database_Connectivity)). Данная статья демонстрирует, как настроить такую интеграцию.
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +### Подключение JDBC-драйвера {{ydb-name}} к DBeaver {#dbeaver_ydb}
```suggestion
### Подключение JDBC-драйвера {{ ydb-name }} к DBeaver {#dbeaver_ydb}
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +1. Перейдите в раздел **Библиотеки**, нажмите кнопку **Добавить файл**, укажите путь к скачанному ранее JDBC-драйверу {{ ydb-short-name }} и нажмите кнопку **OK**:
```suggestion
1. Перейдите в раздел **Библиотеки**, нажмите кнопку **Добавить файл**, укажите путь к скачанному ранее JDBC-драйверу {{ ydb-short-name }} (файлу `ydb-jdbc-driver-shaded-<driver-version>.jar`) и нажмите кнопку **OK**:
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +1. В списке драйверов появится драйвер **YDB**. Дважды кликните по новому драйверу и перейдите на вкладку **Библиотеки**, нажмите кнопку **Найти Класс** и в выпадающем списке выберите `tech.ydb.jdbc.
```suggestion
1. В списке драйверов появится пункт **YDB**. Дважды кликните по новому драйверу и перейдите на вкладку **Библиотеки**, нажмите кнопку **Найти Класс** и в выпадающем списке выберите `tech.ydb.jdbc.YdbDriver`.
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +    Если все настройки выполнены правильно, то появится сообщение об успешном тестировании соединения:
```suggestion
    Если все настройки указаны верно, то появится сообщение об успешном тестировании соединения:
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +
```suggestion
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +# Интеграции
```suggestion
# Интеграции {{ ydb-short-name }}
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +{{ydb-name}} содержит [набор SDK](../reference/ydb-sdk/index.md) для различных языков программирования.
```suggestion
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +## GUI Clients {#gui}
```suggestion
## Клиенты с графическим интерфейсом {#gui}
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| Другие JDBC-совместимые клиенты | [Инструкция](ide/dbeaver.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
```suggestion
| Embedded UI | [Справка](../reference/embedded-ui/index.md) | |
| [DBeaver](https://dbeaver.com)  |  [Инструкция](ide/dbeaver.md) | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
| JetBrains Database viewer |  —  | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
| [JetBrains DataGrip](https://www.jetbrains.com/ru-ru/datagrip/) |  — | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
| Другие JDBC-совместимые IDE | — | C помощью [JDBC-драйвера](https://github.com/ydb-platform/ydb-jdbc-driver/releases)|
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +## Визуализация данных {#bi}
```suggestion
## Визуализация данных (Business Intelligence, BI) {#bi}
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +## Потоковый ввод данных {#streaming-ingestion}
```suggestion
### Потоковая поставка данных {#streaming-ingestion}
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [goose](https://github.com/pressly/goose/blob/master/README.md) | [Инструкция](goose.md) |
```suggestion
| [goose](https://github.com/pressly/goose/) | [Инструкция](goose.md) |
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +
```suggestion
## Смотрите также

* [{#T}](../reference/ydb-sdk/index.md)
* [{#T}](../postgresql/intro.md)
* [{#T}](../reference/kafka-api/index.md)
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/toc_i.yaml
> +- name: Подключение из IDE
```suggestion
- name: DBeaver
```

2024-08-07 02:52 UTC, blinkov commented on ydb/docs/ru/core/integrations/toc_i.yaml
> +  href: index.md
```suggestion
```
вместо этого надо вот тут https://github.com/ydb-platform/ydb/blob/2f2468c9898e73284e0dee38ce06f0d399854705/ydb/docs/ru/core/reference/toc_p.yaml#L17 дописать:

```yaml
- name: Интеграции
  href: ../integrations/index.md
  include: 
    mode: link
    path: ../integrations/toc_p.yaml
```

2024-08-07 10:54 UTC, SloNN commented on ydb/docs/ru/core/integrations/toc_i.yaml
> +- name: Подключение из IDE
давай оставим как есть

2024-08-07 10:55 UTC, SloNN commented on ydb/docs/ru/core/integrations/ide/dbeaver.md
> +[DBeaver](https://dbeaver.com) — бесплатный кроссплатформенный инструмент управления базами данных с открытым исходным кодом, обеспечивающий удобный интерфейс для подключения к различным базам данных
считаю, что нужно оставить как было, чтобы описывалось подключение к любому инструменту

2024-08-07 10:57 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +## Потоковый ввод данных {#streaming-ingestion}
поставка это куда-то наружу. а мы вводим данные. stream ingestion

2024-08-07 15:28 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +
а что тут поменялось? не могу понять

2024-08-07 15:28 UTC, SloNN commented on ydb/docs/ru/core/integrations/index.md
> +{{ydb-name}} содержит [набор SDK](../reference/ydb-sdk/index.md) для различных языков программирования.
и здесь тоже

2024-08-07 15:36 UTC, SloNN commented on ydb/docs/ru/core/integrations/toc_i.yaml
> +  href: index.md
так делать нельзя. документация не поддерживает отображения страниц в узлах дерева. оно будет моргать постоянно

2024-08-08 08:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +| [{{ airflow-name }}](https://airflow.apache.org) |   [Инструкция](airflow.md) |
```suggestion
| [{{ airflow-name }}](https://airflow.apache.org) | [Инструкция](airflow.md) |
```

2024-08-08 08:42 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +## Потоковый ввод данных {#streaming-ingestion}
оно вот десятком строк выше так уже переводилось в непотоковом виде, я просто консистентно делал
![Screenshot 2024-08-08 at 15 41 41](https://github.com/user-attachments/assets/8116a9d8-9669-4742-822f-fa2f6ef8e6aa)

2024-08-08 08:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/toc_i.yaml
> +  href: index.md
так уже в большинстве мест сделано и выглядит норм, возможно баг какой-то был раньше

2024-08-09 06:48 UTC, fomichev3000 approved these changes

2024-08-09 06:48 UTC, fomichev3000 commented on ydb/docs/ru/core/integrations/index.md
> +В дополнение к своему собственному нативному протоколу, {{ ydb-name }} обладает слоем совместимости, что позволяет внешним системам подключаться к базам данных по сетевым протоколам [PostgreSQL](../p
Я бы написал, что поддержка PG экспериментальная (или ссылку бы дал на то место, где это описано).
Нам надо разводить -- поддержка kafka в целом хорошая, поддержка pg начальная (или экспериментальная)

2024-08-09 06:48 UTC, merged

2024-08-09 08:01 UTC, blinkov commented on ydb/docs/ru/core/integrations/index.md
> +В дополнение к своему собственному нативному протоколу, {{ ydb-name }} обладает слоем совместимости, что позволяет внешним системам подключаться к базам данных по сетевым протоколам [PostgreSQL](../p
Про это прямо в самом начале этого `../postgresql/intro.md` (куда ссылаемся) и написано:
![Screenshot 2024-08-09 at 14 59 56](https://github.com/user-attachments/assets/7ed6650c-3d1e-437a-a0c3-ab74256343d3)