added a table with environment variables
ydb-platform/ydb pull request #7333
Opened 2024-07-31 17:13 UTC by Nikita-Levuskin

### Changelog entry 

...

### Changelog category 

* Improvement

### Additional information

...

2024-08-06 05:32 UTC, blinkov commented
@Nikita-Levuskin as I wrote in https://github.com/ydb-platform/ydb/pull/7200#discussion_r1696239782, the quickstart article is about getting started with YDB as simply as possible; while these environment variables are for some exotic situations.

Finishing this PR properly will need creating a folder in https://github.com/ydb-platform/ydb/tree/main/ydb/docs/en/core/reference called `docker`, adding it to the docs build system, and adding some introductory words. Do you want to try to do it yourself? Or I could help you with this when I'll have some spare time.

2024-08-06 10:41 UTC, Nikita-Levuskin commented
@blinkov something like this should be done? So far, only the documentation is in Russian

2024-08-06 10:44 UTC, Nikita-Levuskin commented
@blinkov something like this should be done? So far, only the documentation is in Russian

2024-08-13 04:33 UTC, blinkov requested changes

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`YDB_PQ_TOPICS_ARE_FIRST_CLASS_CITIZEN`](https://github.com/ydb-platform/ydb/blob/b1c590828b222c839dedecd8e6e79413ef5b7eec/ydb/tests/library/harness/kikimr_config.py#L77) <br> [`YDB_PQ_CLUSTER_TAB
```suggestion
| Имя                                                                                                                                                                         | Тип        | Значение по умолчанию  | Версия {{ ydb-short-name }}                   | Описание                                                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|------------------------|------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [`POSTGRES_USER`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                             | `string`   | `postgres`             | `≥23.1`                      | Имя пользователя для доступа через [режим совместимости с PostgreSQL](../../postgresql/intro.md).                                                                                                                                                             |
| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''                     | `≥23.1`                      | Пароль пользователя для доступа через [режим совместимости с PostgreSQL](../../postgresql/intro.md).                                                                                                                                                          |
| [`YDB_LOCAL_SURVIVE_RESTART`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L254)                 | `0` или `1`| `1`                    |                              | При значении `1` используются файлы конфигурации, созданные при предыдущих запусках, если таковые имеются. При значении `0` всегда генерируются новые файлы конфигурации.        |
| [`YDB_GRPC_ENABLE_TLS`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L258)                       | `0` или `1`| `1`                    |                              | Включает использование TLS для gRPC соединений.                                                                                                                                                |
| [`YDB_GRPC_TLS_DATA_PATH`](https://github.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L291)                    | `string`   | `/ydb_data`            |                              | Путь до директории с TLS сертификатами для gRPC соединений.                                                                                                                                                               |      
| [`YDB_PQ_CLIENT_SERVICE_TYPES`](https://github.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L297)               | `string`   | `None`                 |                              | Тип клиента persistent queue.                                                                                                                                                                       |
| [`YDB_ENABLE_PQCD`](https://github.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L310)                           | `0` или `1`| `0`                    |                              | Включает использование persistent queue cluster discovery.                                                                                                                                                          |
| [`MON_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L170)                     | `int`      | `8765`                 |                              | Порт для мониторинга.                                                                                                                                                                   |
| [`PUBLIC_HTTP_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L192)             | `int`      | `8766`                 |                              | Публичный HTTP порт.                                                                                                                                                                  |
| [`GRPC_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L174)                    | `int`      | `2135`                 |                              | gRPC порт.                                                                                                                                                                            |
| [`IC_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L179)                      | `int`      | `19001`                |                              | Порт интерконнекта.                                                                                                                                                                    |
| [`GRPC_TLS_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L183)                | `int`      | `2137`                 |                              | gRPCS порт.                                                                                                                                                                        |
| [`GRPC_EXT_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L187)                | `int`      | `2237`                 |                              | Внешний gRPC порт.                                                                                                                                                                        |
| [`YDB_ERASURE`](https://github.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L50)                                | `string`   | `None`                 |                              | Режим работы распределйнного хранилища, см. [{#T}](../../concepts/topology.md).                                                                                                                   |
| [`FQ_CONNECTOR_ENDPOINT`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L261)                     | `string`   | `None`                 | `≥24.1`                      | Строка подключения коннектора к внешним источникам `fq-connector-go`.                                                                                                                     |
| [`YDB_USE_IN_MEMORY_PDISKS`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L230)                  | `0` или `1`| `0`                    |                              | Делает все данные волатильными, хранящимися только в оперативной памяти. В настоящее время сохранение данных путём её отключения поддерживается только на процессорах x86_64.   [...]

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/index.md
> +* [Перемменные окружения](environment.md)
```suggestion
# Справка по работе {{ ydb-short-name }} в Docker

В данном разделе собраны подробносте по работе с {{ ydb-short-name }}, поставляемом в виде Docker контейнера.

Документация по Docker контейнеру содержит следующие разделы:

* [{#T}](install.md)
* [{#T}](start.md)
* [{#T}](environment.md)
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/install.md
> +  - [Windows](https://docs.docker.com/desktop/install/windows-install/)
```suggestion
# Установка Docker для работы с {{ ydb-short-name }}

Прежде чем воспользоваться Docker образом {{ ydb-short-name }}, необходимо установить и настроить Docker окружение. Для этого можно воспользоваться официальной документацией:

- [Linux](https://docs.docker.com/desktop/install/linux-install/)
- [macOS](https://docs.docker.com/desktop/install/mac-install/)
- [Windows](https://docs.docker.com/desktop/install/windows-install/)
  
Альтернативные способы установки вроде [colima](https://github.com/abiosoft/colima) также допустимы.

Установка самого {{ ydb-short-name }} происходит при [первом запуске](start.md).
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +Если вы захотите очистить фаловую систему то можете удалить вашу рабочу директорию с помощью команды `rm -rf ~/ydbd`, при этом все данные внутри локального кластера YDB будут потеряны.
вынести в отдельный файлик, условно cleanup.md и сослаться на него

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +# Работа с {{ ydb-short-name }} в Docker
```suggestion
# Запуск {{ ydb-short-name }} в Docker
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +## Запуск Docker
```suggestion
## Запуск контейнера с {{ ydb-short-name }} в Docker
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +Создайте каталог для тестирования YDB и используйте его в качестве текущего рабочего каталога:
```suggestion
Создайте каталог для тестирования {{ ydb-short-name }} и используйте его в качестве текущего рабочего каталога:
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +Для запуска {{ ydb-short-name }} в Docker необходимо выполнить следующую команду:
```suggestion
Пример команды запуска {{ ydb-short-name }} в Docker с подробными комментариями:
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +```
```suggestion
```bash
docker run \
    -d \ # запуск в фоне
    --rm \ # автоматическое удаление после установки
    --name ydb-local \ # имя контейнера
    -h localhost \ # хостейм
    -p 2135:2135 \ # открытие внешнего доступа к grpcs порту
    -p 2136:2136 \ # открытие внешнего доступа к grpc порту
    -p 8765:8765 \ # открытие внешнего доступа к http порту
    -p 5432:5432 \ # открытие внешнего доступа к порту, обеспечивающему PostgreSQL-совместимость
    -v $(pwd)/ydb_certs:/ydb_certs \ # директория для TLS сертификатов
    -v $(pwd)/ydb_data:/ydb_data \ # рабочая директория
    -e GRPC_TLS_PORT=2135 \ # grpcs порт
    -e GRPC_PORT=2136 \ # grpc порт
    -e MON_PORT=8765 \ # http порт
    -e YDB_USE_IN_MEMORY_PDISKS=1 \ # хранение данных только в оперативной памяти
    ydbplatform/local-ydb:latest # имя и тег образа
```
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +Подробнее про переменные окружения, используемые при запуске Docker контейнера с {{ ydb-short-name }} можно узнать [тут](environment.md)
```suggestion
Подробнее про переменные окружения, используемые при запуске Docker контейнера с {{ ydb-short-name }} можно узнать в разделе [{#T}](environment.md)
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/start.md
> +Веб-интерфейс  {{ ydb-short-name }} доступен на [http://localhost:8765⁠](http://localhost:8765⁠).
```suggestion
При указанных в примере выше параметрах и запуске Docker локально, [Embedded UI](../embedded-ui/index.md)  {{ ydb-short-name }} будет доступен по адресу [http://localhost:8765⁠](http://localhost:8765⁠).
```

2024-08-13 04:33 UTC, blinkov commented on ydb/docs/ru/core/reference/docker/toc_p.yaml
> +    href: index.md
```suggestion
```
при поле href в `ydb/docs/ru/core/reference/toc_p.yaml` это становится лишним

2024-08-13 09:22 UTC, Nikita-Levuskin commented on ydb/docs/ru/core/reference/docker/start.md
> +Если вы захотите очистить фаловую систему то можете удалить вашу рабочу директорию с помощью команды `rm -rf ~/ydbd`, при этом все данные внутри локального кластера YDB будут потеряны.
done

2024-08-19 14:23 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/environment.md
> +| [`POSTGRES_USER`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                             | `string`   | `postgres`
```suggestion
| [`POSTGRES_USER`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                             | `string`   | `postgres`             | `≥24.1`                      | postgres user name                                                                                                                                                                     |
```

2024-08-19 14:24 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/environment.md
> +| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''
```suggestion
| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''                     | `≥24.1`                      | postgres user password                                                                                                                                                                 |
```

2024-08-19 14:25 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`POSTGRES_USER`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                             | `string`   | `postgres`
```suggestion
| [`POSTGRES_USER`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                             | `string`   | `postgres`             | `≥24.1`                      | Имя пользователя для доступа через [режим совместимости с PostgreSQL](../../postgresql/intro.md).                                                                                                                                                             |
```

2024-08-19 14:25 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''
```suggestion
| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''                     | `≥24.1`                      | Пароль пользователя для доступа через [режим совместимости с PostgreSQL](../../postgresql/intro.md).                                                                                                                                                          |
```

2024-08-19 14:29 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   | ''
```suggestion
| [`POSTGRES_PASSWORD`](https://github.com/ydb-platform/ydb/blob/c113fcffa7b1a20ad8dcb1b1760ae5bfa25370ca/ydb/public/tools/lib/cmds/__init__.py#L240)                         | `string`   |                        | `≥24.1`                      | Пароль пользователя для доступа через [режим совместимости с PostgreSQL](../../postgresql/intro.md).                                                                                                                                                          |
```

2024-08-19 17:04 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`GRPC_TLS_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L183)                | `int`      | `2137`
```suggestion
| [`GRPC_TLS_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L183)                | `int`      | `2137`                 |                              | gRPCS порт защищенного соединения.                                                                                                                                                                        |
```

2024-08-19 17:05 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/environment.md
> +| [`GRPC_TLS_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L183)                | `int`      | `2137`
```suggestion
| [`GRPC_TLS_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L183)                | `int`      | `2137`                 |                              | `GPRC` port for secure connection                                                                                                                                                                       |
```

2024-08-19 17:11 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`MON_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L170)                     | `int`      | `8765`
```suggestion
| [`MON_PORT`](https://github.com/ydb-platform/ydb/blob/8dde59cd0af86737d07a1cd8ff19811a2bd2b663/ydb/tests/library/harness/kikimr_port_allocator.py#L170)                     | `int`      | `8765`                 |                              | `HTTP`-порт веб-интерфейса YDB.                                                                                                                                                                   |
```

2024-09-19 11:21 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/naming.md
> +* **latest** - corresponds to the *stable* version of YDB that was tested on well-known YDB production clusters. The **latest** tag is rebuilt when an entry about a new YDB release appears in [GitHub
```suggestion
* **latest** - corresponds to the *stable* version of YDB that was tested on well-known YDB production clusters. The **latest** tag is rebuilt when an entry about a new YDB release appears in [github.com/ydb-platform/ydb](https://github.com/ydb-platform/ydb/releases) project.
```

2024-09-19 11:22 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/naming.md
> +* **latest** - соответствует *stable*-версии YDB, проверенной на известных продакшен-кластерах YDB. Тег **latest** пересобирается, когда в [GitHub.com/ydb-platform/ydb](https://github.com/ydb-platfor
```suggestion
* **latest** - соответствует *stable*-версии YDB, проверенной на известных продакшен-кластерах YDB. Тег **latest** пересобирается, когда в проекте [github.com/ydb-platform/ydb](https://github.com/ydb-platform/ydb/releases) появляется запись о новом релизе YDB.
```

2024-09-19 11:22 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/naming.md
> +* **trunk,** **main, nightly** - the latest version of YDB from the code in the main YDB development branch. Contains the most recent changes. The image is reassembled every night.
```suggestion
* **trunk,** **main**, **nightly** - the latest version of YDB from the code in the main YDB development branch. Contains the most recent changes. The image is reassembled every night.
```

2024-09-19 11:23 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/naming.md
> +* **trunk,** **main, nightly** - последняя версия YDB из кода в основной ветке разработки YDB. Содержит самые последние изменения. Образ пересобирается каждую ночь.
```suggestion
* **trunk,** **main**, **nightly** - последняя версия YDB из кода в основной ветке разработки YDB. Содержит самые последние изменения. Образ пересобирается каждую ночь.
```

2024-09-19 11:25 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/environment.md
> +| [`YDB_PQ_CLIENT_SERVICE_TYPES`](https://GitHub.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L297)               | `string`   | `None`
```suggestion
```

2024-09-19 11:26 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`YDB_PQ_CLIENT_SERVICE_TYPES`](https://GitHub.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L297)               | `string`   | `None`
```suggestion
```

2024-09-19 11:26 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/environment.md
> +| [`YDB_PQ_TOPICS_ARE_FIRST_CLASS_CITIZEN`](https://GitHub.com/ydb-platform/ydb/blob/b1c590828b222c839dedecd8e6e79413ef5b7eec/ydb/tests/library/harness/kikimr_config.py#L77) |  `0` or `1` | `1` | |
```suggestion
| [`YDB_PQ_CLIENT_SERVICE_TYPES`](https://GitHub.com/ydb-platform/ydb/blob/8fefc809c83829d8d8b886e82534d009de4c8826/ydb/public/tools/lib/cmds/__init__.py#L297)               | `string`   | `None`                 |                              | Тип клиента persistent queue.                                                                                                                                                                       |
| [`YDB_PQ_TOPICS_ARE_FIRST_CLASS_CITIZEN`](https://GitHub.com/ydb-platform/ydb/blob/b1c590828b222c839dedecd8e6e79413ef5b7eec/ydb/tests/library/harness/kikimr_config.py#L77) |  `0` or `1` | `1` | |  Не используются. |
```

2024-09-19 11:43 UTC, asmyasnikov commented on ydb/docs/en/core/reference/docker/naming.md
> +* **latest** - corresponds to the *stable* version of YDB that was tested on well-known YDB production clusters. The **latest** tag is rebuilt when an entry about a new YDB release appears in [github
```suggestion
* **latest** - corresponds to the *stable* version of YDB that was tested on well-known YDB production clusters. The **latest** tag is rebuilt when an entry about a new YDB release appears in [ydb](https://github.com/ydb-platform/ydb/releases) project.
```

2024-09-19 11:44 UTC, asmyasnikov commented on ydb/docs/ru/core/reference/docker/naming.md
> +* **latest** - соответствует *stable*-версии YDB, проверенной на известных продакшен-кластерах YDB. Тег **latest** пересобирается, когда в проекте [github.com/ydb-platform/ydb](https://github.com/ydb
```suggestion
* **latest** - соответствует *stable*-версии YDB, проверенной на известных продакшен-кластерах YDB. Тег **latest** пересобирается, когда в проекте [ydb](https://github.com/ydb-platform/ydb/releases) появляется запись о новом релизе YDB.
```

2024-12-09 10:44 UTC, closed without merging