pg
ydb-platform/ydb pull request #7381
Opened 2024-08-01 17:57 UTC by SloNN

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-06 06:30 UTC, blinkov requested changes

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Использование нативных PostgreSQL-инструментов. {{ydb-name}} обладает сервисом совместимости для поддержки нативного сетевого протокола PostgreSQL - pgwire, поэтому к {{ydb-name}} можно подключать
добавить pgwire в concepts/glossary.md, а отсюда сослаться на глоссарий

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Использование нативных {{ydb-name}} инструментов и явного указания, что запрос выполняется в синтаксисе PostgreSQL. Это указание производится с помощью специального комментария в теле запроса `--!
```suggestion
1. Использование нативных {{ ydb-short-name}} инструментов и явного указания, что запрос выполняется в синтаксисе PostgreSQL. Это указание производится с помощью специального комментария в начале тела запроса `--!syntax_pg`, после чего весь запрос интерпретируется в соответствии с PostgreSQL диалектом вместо YQL.
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +Для подключения необходимо выполнить предварительные шаги:
по идее порт ещё нестандартным может быть?

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +Для подключения к {{ydb-name}} через нативный PostgreSQL-протокол можно использовать стандартные приложения, поддерживающие этот протокол. Ниже приведен пример подключения с помощью приложения `psql`
```suggestion
Для подключения к {{ ydb-name }} через PostgreSQL-протокол можно использовать любые клиентские библиотеки и приложения, поддерживающие этот протокол. Ниже приведен пример подключения с помощью утилиты `psql`, входящей в комплект поставки PostgreSQL.
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +- `database_name` - название базы данных в кластере. Может быть сложным именем, например, `mycluster/tenant1/database/`.
Слэш в конце прям всегда нужен? Или он на что-то влияет?

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +Выполнить запрос в {{ydb-name}}:
```suggestion
Выполнить запрос к {{ ydb-name }}:
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Получить название базы данных в кластере, к которому производится подключение.
```suggestion
Для подключения необходимо выполнить предварительные шаги:
1. Получить адрес [кластера](../concepts/glossary.md#cluster), к которому производится подключение.
1. Получить название [базы данных](../concepts/glossary.md#database) в кластере, к которому производится подключение.
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +Выполнять запросы на PostgreSQL-диалекте можно с помощью любых инструментов {{ydb-name}}, явно указав в теле запроса признак диалекта с помощью специального комментария: `--!syntax_pg`.
```suggestion
Выполнять запросы на PostgreSQL-диалекте можно с помощью любых инструментов {{ydb-name}}, явно указав в начале тела запроса признак диалекта с помощью специального комментария: `--!syntax_pg`.
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +select 1;
```suggestion
SELECT 1;
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +- <user_name> - логин пользователя.
```suggestion
- `<ydb_address>` — адрес кластера ydb, к которому выполняется подключение.
- `<database_name>` — название базы данных в кластере. Может быть сложным именем, например, `mycluster/tenant1/database/`.
- `<user_name>` — логин пользователя.
```

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/interoperability.md
> +## Соответствие типов данных {#supported_types}
Как уже писал выше, вынести рассказ про сравнение/соответствие типов данных в отдельную статью куда ссылаться из релевантных мест.

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/interoperability.md
> +1. Программа отправляет запросы в YDB, где их обрабатывает компонент под названием `pgwire`. Pgwire реализует [сетевой протокол](https://postgrespro.ru/docs/postgresql/14/protocol) PostgreSQL и перед
```suggestion
1. Программа отправляет запросы в {{ ydb-short-name }}, где их обрабатывает компонент под названием `pgwire`. Pgwire реализует [сетевой протокол](https://www.postgresql.org/docs/16/protocol.html) PostgreSQL и передает команды в query processor.
```
плюс см. комментарий к предыдущему упоминанию pgwire

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/interoperability.md
> +Поддерживаются только преобразования типов приведенное выше.
явно написать что будет при использовании других типов данных — видимо ошибка? хорошо б дать её пример, чтоб по тексту гуглилось

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/intro.md
> +Основной текущий сценарий использования интеграции с PostgreSQL - выполнение аналитических запросов к хранимым в {{ydb-name}} данным.
давайте на очередном синке по документации обсудим этот момент

2024-08-06 06:30 UTC, blinkov commented on ydb/docs/ru/core/postgresql/intro.md
> +При выполнении запросов
Тут попытки краткого пересказа части статей + на 27 строке странный обрывок фразы. Предлагаю тут вместо этого просто сделать список-оглавление со всеми статьями в этом разделе по аналогии с https://ydb.tech/docs/en/dev/, например.

2024-08-06 13:48 UTC, SloNN commented on ydb/docs/ru/core/postgresql/intro.md
> +При выполнении запросов
это я начинал с этого, потом понял, что нужно больше описывать и пошел делать новые страницы, а потом потерял. поправил

2024-08-06 19:16 UTC, SloNN commented on ydb/docs/ru/core/postgresql/interoperability.md
> +## Соответствие типов данных {#supported_types}
текст оставил, но вынес в include, полиновал еще в подробное описание

2024-08-06 19:24 UTC, SloNN commented on ydb/docs/ru/core/postgresql/connect.md
> +Для подключения необходимо выполнить предварительные шаги:
технически может быть, но по умолчанию он стандартный.

2024-08-06 19:26 UTC, SloNN commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Использование нативных PostgreSQL-инструментов. {{ydb-name}} обладает сервисом совместимости для поддержки нативного сетевого протокола PostgreSQL - pgwire, поэтому к {{ydb-name}} можно подключать
зачем? просто добавил ссылку на сайт pg

2024-08-06 19:42 UTC, SloNN commented on ydb/docs/ru/core/postgresql/advanced.md
> +## Вызов PostgreSQL функций {#callpgfunction}
вообще весь этот документ живет вот тут https://yql.yandex-team.ru/docs/yt/udf/list/postgres

но боюсь, что обычному человеку будет суперсложно понять про postgresql udf и какое отношение оно имеет к pg вообще. поэтому я ее перенес для ydb в другое место

при импорте в Аркадию нужно будет распилить на include'ы и вставить в правильные места

2024-08-07 09:54 UTC, SloNN commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
давай это делать отдельно

2024-08-07 16:56 UTC, vitstn commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Получить название базы данных в кластере, к которому производится подключение.
два раза 1

2024-08-07 16:57 UTC, vitstn commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Использование нативных {{ ydb-short-name}} инструментов и явного указания, что запрос выполняется в синтаксисе PostgreSQL. Это указание производится с помощью специального комментария в начале тел
в большинстве инструментов должен быть явный способ указать синтаксис

2024-08-07 16:57 UTC, vitstn commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Получить название [базы данных](../concepts/glossary.md#database) в кластере, к которому производится подключение.
два раза 1

2024-08-07 16:59 UTC, vitstn commented on ydb/docs/ru/core/postgresql/interoperability.md
> +| `bool` |`pgbool` |
тут нужна не таблица, а просто правило - для типа foo добавляется префикс pg: pgfoo

для массивов _foo получается _pgfoo

2024-08-07 17:00 UTC, vitstn commented on ydb/docs/ru/core/postgresql/interoperability.md
> +Встроенные функции YQL ориентированы на работу с собственными типами данных, например, `Ip::FromString` получает на вход типы данных `Utf8` или `String`. Поэтому встроенные функции YQL не могут работ
кажется тут можно сказать что с pg типами можно использовать большинство функции PG в виде Pg::func(...)

2024-08-07 17:02 UTC, vitstn commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/postgres.md
> +### Список псевдноимов типов PostgreSQL при их использовании в YQL {#pgyqltypes}
псевдноимов опечатка

2024-08-07 18:20 UTC, SloNN commented on ydb/docs/ru/core/postgresql/connect.md
> +1. Получить название [базы данных](../concepts/glossary.md#database) в кластере, к которому производится подключение.
спасибо за замечание, но так принято в облаке писать документацию. при рендеринге оно само получает правильные порядковые номера. а за счет того, что везде "1" можно не переживать, что нумерация собьется

2024-08-08 09:06 UTC, blinkov commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
@SloNN можно и в отдельном PR, но т.к. тут afaik некорректная информация — в таком виде мёрджить не вариант. Т.е. тогда давай сначала сделаем статью про типы данных, а это повисит открытым пока?

2024-08-08 09:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/_includes/pgliterals.md
> +    1234p, 0x123pb, "тест"pt, 123e-1000pn; -- pgint4, pgint8, pgtext, pgnumeric
```suggestion
SELECT
    1234p,             -- pgint4
    0x123pb,         -- pgint8
    "тест"pt,         -- pgtext
    123e-1000pn; -- pgnumeric
```

2024-08-08 09:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/_includes/pgliterals.md
> +    PgArray(1p,null,2p), -- {1,NULL,2}, тип _int4
```suggestion
    PgArray(1p, NULL ,2p) -- {1,NULL,2}, тип _int4
```

2024-08-08 09:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/postgres.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
см. выше про типы данных

2024-08-12 14:08 UTC, blinkov submitted a review, later dismissed

2024-08-12 14:08 UTC, blinkov commented on ydb/docs/ru/core/postgresql/_includes/alert_preview.md
> +Поддержка синтаксиса PostgreSQL в {{ ydb-name }} находится в стадии **Preview**.
```suggestion
Поддержка синтаксиса PostgreSQL в {{ ydb-name }} **находится в разработке**. Использовать её в production окружениях **не рекомендуется**. Основной сценарий, который можно тестировать — выполнение аналитических запросов к хранимым в {{ ydb-name }} данным. 
```

2024-08-12 14:08 UTC, blinkov commented on ydb/docs/ru/core/postgresql/intro.md
> +{% note info %}
```suggestion
```

2024-08-12 14:08 UTC, blinkov commented on ydb/docs/ru/core/postgresql/intro.md
> +Основной текущий сценарий использования интеграции с PostgreSQL - выполнение аналитических запросов к хранимым в {{ydb-name}} данным.
```suggestion
```

2024-08-12 14:08 UTC, blinkov commented on ydb/docs/ru/core/postgresql/intro.md
> +{% endnote %}
```suggestion
```

2024-08-15 10:22 UTC, SloNN commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
@vitstn Виталий, а ты можешь помочь с этим? я не в курсе про композитные типы PG

2024-08-15 13:34 UTC, vitstn commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
мы поддерживаем тип record и все массивы вида _text. в чем вопрос?

2024-08-15 13:39 UTC, vitstn commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
nullable действительно не часть типа, а runtime constraint, по сути сахар к check column is not null

2024-08-16 06:32 UTC, blinkov commented on ydb/docs/ru/core/postgresql/interoperability.md
> +| `bool` |`pgbool` |
таблица полезна как минимум, чтобы поиск по имени конкретного типа эту страницу находил, но правило рядом описать впринципе тоже можно

2024-08-16 06:33 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +- `<ydb_address>` — адрес кластера ydb, к которому выполняется подключение.
```suggestion
- `<ydb_address>` — адрес кластера {{ ydb-short-name }}, к которому выполняется подключение.
```

2024-08-16 06:34 UTC, blinkov commented on ydb/docs/ru/core/postgresql/connect.md
> +- `user_name` - логин пользователя.
```suggestion
- `<ydb_address>` - адрес кластера {{ ydb-short-name }}, к которому выполняется подключение.
- `<database_name>` - название базы данных в кластере. Может быть сложным именем, например, `mycluster/tenant1/database`.
- `<user_name>` - логин пользователя.
```

2024-08-16 06:37 UTC, blinkov commented on ydb/docs/ru/core/postgresql/interoperability.md
> +    - `user_name` - логин пользователя.
```suggestion
    - `<ydb_address>` - адрес кластера ydb, к которому выполняется подключение.
    - `<database_name>` - название базы данных в кластере. Может быть сложным именем, например, `mycluster/tenant1/database`.
    - `<user_name>` - логин пользователя.
```

2024-08-16 06:51 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/_includes/pgliterals.md
> +Для некоторых типов в функции `PgConst` можно указать дополнительные модификаторы. Возможные модификаторы для типа `pginterval` перечислены в [документации](https://www.postgresql.org/docs/16/datatyp
```suggestion
Для некоторых типов в функции `PgConst` можно указать дополнительные модификаторы. Возможные модификаторы для типа `pginterval` перечислены в [документации PostgreSQL](https://www.postgresql.org/docs/16/datatype-datetime.html).
```

2024-08-16 06:52 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/_includes/topg.md
> +| YQL | PostgreSQL | Название PostgreSQL-типа в YDB|
```suggestion
| YQL | PostgreSQL | Название PostgreSQL-типа в {{ ydb-short-name }} |
```

2024-08-16 06:53 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/postgres.md
> +[YQL](../../index.md) предоставляет возможность доступа из YQL к [функциям](https://www.postgresql.org/docs/16/functions.html) и [типам данных](https://www.postgresql.org/docs/16/datatype.html) Postg
```suggestion
[YQL](../../index.md) предоставляет возможность доступа к [функциям](https://www.postgresql.org/docs/16/functions.html) и [типам данных](https://www.postgresql.org/docs/16/datatype.html) PostgreSQL.
```

2024-08-16 07:05 UTC, blinkov commented
@SloNN ещё конфликт надо разрулить
![Screenshot 2024-08-16 at 14 03 49](https://github.com/user-attachments/assets/f6e43aec-e956-487d-9e55-4896148a2241)

2024-08-19 11:47 UTC, SloNN commented on ydb/docs/ru/core/postgresql/advanced.md
> +На данный момент поддерживаются все простые типы данных из PostgreSQL, включая массивы.
удалил блок, как обсудили на встрече

2024-08-19 12:36 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/postgres.md
> +Например `PgVarchar`, `PgInt4`, `PgText`. Имена pg типов (как и вообще всех типов) в YQL являются case-insensitive. На данный момент поддерживаются все простые типы данных из PostgreSQL, включая масс
```suggestion
Например `PgVarchar`, `PgInt4`, `PgText`. Имена pg типов (как и вообще всех типов) в YQL являются case-insensitive. На данный момент поддерживаются все простые типы данных из PostgreSQL, а также массивы.
```

2024-08-21 03:17 UTC, blinkov commented on ydb/docs/ru/core/postgresql/_includes/alert_preview.md
> +Поддержка синтаксиса PostgreSQL в {{ ydb-name }} **находится в разработке**. Использовать её в production окружениях **не рекомендуется**. Основной сценарий, который можно тестировать — выполнение ан
```suggestion
Поддержка синтаксиса PostgreSQL в {{ ydb-name }} **находится в разработке**. Использовать её в production окружениях **не рекомендуется**. Запросы в PostgreSQL могут исполняться до нескольких раз медленнее по сравнению с аналогичными запросами на YQL.

Основной сценарий, который можно тестировать — выполнение аналитических запросов к хранимым в {{ ydb-name }} данным. 
```

2024-08-22 05:58 UTC, fomichev3000 approved these changes

2024-08-22 05:58 UTC, merged

2024-08-29 06:46 UTC, makorne commented
> ### ✅ Documentation build
> Revision built successfully Revision preview [link](https://ydb-platform--ydb.viewer.diplodoc.com?revision=pr-7381-1b7e63fe27c2b82ea68c93f88623a927b4aa03e3)

[Connection via PostgreSQL protocol](https://ydb-platform--ydb.viewer.diplodoc.com/en/postgresql/connect?revision=pr-7381-1b7e63fe27c2b82ea68c93f88623a927b4aa03e3)      Error 404