Add sample k collect for first level of vector index table
ydb-platform/ydb pull request #7412
Opened 2024-08-02 11:13 UTC by MBkkt

2024-08-12 10:16 UTC, jepett0 reviewed
I would suggest you combine all the refactoring in one commit, or at least separate the main commit with meaningful changes (is it [wip commit](ddfde4016e4471499929cc4818f070c96c5f57b4)?) from refactoring and make it more visible among the refactoring commits.

2024-08-12 10:20 UTC, MBkkt commented on ydb/core/tx/datashard/build_index.cpp
> +            progress->Record.SetLastKeyAck(LastUploadedKey.GetBuffer());
I remove extra serialization because we already have serialized key.
My new comment here is about why do we need copy it instead of move.

2024-08-12 10:21 UTC, MBkkt commented on ydb/core/tx/schemeshard/schemeshard_info_types.h
> -        TBillingStats Billed;
It was always zero https://github.com/ydb-platform/ydb/pull/7412/commits/feff3a1668e15a4b17b94535e63cf9435a68566a

2024-08-12 11:00 UTC, MBkkt commented on ydb/core/tx/schemeshard/schemeshard_build_index.cpp
> +        handle(buildInfo.LockTxId);
Done https://github.com/ydb-platform/ydb/pull/7412/commits/6fd04832c4f31fa304a118850d1683526e21ccc4

2024-08-12 11:00 UTC, MBkkt commented on ydb/core/tx/schemeshard/schemeshard__init.cpp
> +                        Y_ABORT_UNLESS(emplaced);
Reverted https://github.com/ydb-platform/ydb/pull/7412/commits/6fd04832c4f31fa304a118850d1683526e21ccc4

2024-08-12 11:06 UTC, MBkkt commented on ydb/core/tx/datashard/build_index.cpp
> +            progress->Record.SetLastKeyAck(LastUploadedKey.GetBuffer());
> How is the reported LastKeyAck going to change?

There should be no changes.

2024-08-12 12:22 UTC, MBkkt commented
Will be merged only after this PR: https://github.com/ydb-platform/ydb/pull/7658

2024-08-13 08:12 UTC, azevaykin commented on ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
> +inline void Out<Ydb::Table::IndexBuildState_State>(IOutputStream& o, Ydb::Table::IndexBuildState_State info) {
Usually it placed here
[ydb/core/protos/out/out.cpp](https://github.com/ydb-platform/ydb/blob/main/ydb/core/protos/out/out.cpp)

2024-08-13 08:15 UTC, azevaykin commented on ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
> +        runtime.SetObserverFunc([&](TAutoPtr<IEventHandle>& ev) {
SetObserver is [deprecated](https://github.com/ydb-platform/ydb/blob/5ccb8183a3926fca9bb3bdf96408c9314102cef1/ydb/library/actors/testlib/test_runtime.h#L239C74-L239C101), use [AddObserver](https://github.com/ydb-platform/ydb/blob/main/ydb/library/actors/testlib/test_runtime.h#L362)

2024-08-30 11:15 UTC, ijon requested changes

2024-08-30 11:15 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +        LOG_D("Retry upload " << Debug());
More common context should be on the left side of the logging message.
Here LogPrefix is not actually used as a prefix.

2024-08-30 11:15 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +              << Debug()
LogPrefix is not a prefix here.

2024-08-30 11:15 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +            LOG_N("Got retriable error, " << Debug());
LogPrefix is not a prefix here.

2024-08-30 11:15 UTC, ijon commented on ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
> +                       "Mismatch"
Consider adding a bit more context here. It would be hard to find this exact place on the message text that brief.

2024-08-30 11:47 UTC, ijon submitted a review, later dismissed

2024-08-30 12:07 UTC, azevaykin commented on ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
> +        const TString meteringData = R"({"usage":{"start":0,"quantity":292,"finish":0,"unit":"request_unit","type":"delta"},"tags":{},"id":"106-72075186233409549-2-328-5075-328-5075","cloud_id":"CLOU
```suggestion
        const TString meteringData = R"({"usage":{"start":0,"quantity":292,"finish":0,"unit":"request_unit","type":"delta"},"tags":{},"id":"106-72075186233409549-2-328-5075-328-5075","cloud_id":"CLOUD_ID_VAL","source_wt":0,"source_id":"sless-docapi-ydb-ss","resource_id":"DATABASE_ID_VAL","schema":"ydb.serverless.requests.v1","folder_id":"FOLDER_ID_VAL","version":"1.0.0"})\n";
```

2024-08-30 12:07 UTC, azevaykin commented on ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
> +        UNIT_ASSERT_NO_DIFF(meteringMessages, meteringData + "\n");
```suggestion
        UNIT_ASSERT_NO_DIFF(meteringMessages, meteringData);
```

2024-08-30 12:11 UTC, azevaykin approved these changes, later dismissed

2024-08-30 17:50 UTC, azevaykin approved these changes

2024-08-30 17:50 UTC, merged