[wip] hive docs
ydb-platform/ydb pull request #7413
Opened 2024-08-02 11:22 UTC by vporyadke

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-10-24 07:40 UTC, blinkov commented
@vporyadke when do you plan to mark it as non-draft?

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/general-schema.md
> +Для системных таблеток кластера узел, на котором запускается таблетка, выбирается с помощью механизма Bootstrapper, реализующего [распределённый консенсус](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%
> каналы таблеток

Выше по тексту такой термин отсуствует. Наверно, стоит его внести и/или добавить в глоссарий.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/general-schema.md
> +Для системных таблеток кластера узел, на котором запускается таблетка, выбирается с помощью механизма Bootstrapper, реализующего [распределённый консенсус](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%
> Для системных таблеток
> Пользовательскими таблетками

Аналогично, стоит ввести классификацию таблеток или сослаться на неё.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Hive — таблетка, отвечающая за управление другими таблетками. В кластере {{ ydb-short-name }} есть корневой Hive, который отвечает за системные таблетки всех баз данных кластера. Hive конкретной базы
> отвечает за системные таблетки

Нужна ссылка.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Создание и удаление таблеток инициируется таблеткой SchemeShard. При создании таблетки Hive присваивает ей уникальный TabletId, заполняет [TabletStorageInfo](general-schema.md#history), выбирает наиб
> SchemeShard

Добавь ссылку.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/general-schema.md
>  На каждом узле выполняются специальные микросервисы, которые называются *таблетками*. Каждая таблетка имеет определённый тип и идентификатор и является singleton'ом, что означает, что в каждый момент
Понятия "таблетка", "поколение", "канал" стоит добавить в глоссарий и сослаться на них.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +1. *Network* — генерируемый таблеткой объём траффика. Подсчёт этого ресурса поддержан не во всех типах таблеток.
```suggestion
1. *Network* — генерируемый таблеткой объём трафика. Подсчёт этого ресурса поддержан не во всех типах таблеток.
```

Уточнение по имплементации, наверно, должно быть рядом с описанием конкретного типа таблетки, а не тут.

2024-12-03 10:57 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Для оценки сбалансированности потребления используется метрика *Scatter*, вычисляемая отдельно для каждого ресурса по формуле
```suggestion
Для оценки сбалансированности потребления используется метрика *Scatter*, вычисляемая отдельно для каждого ресурса по формуле:
```

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/general-schema.md
> +Для [системных таблеток](../concepts/glossary.md#tablet-types) кластера узел, на котором запускается таблетка, выбирается с помощью механизма Bootstrapper, реализующего [распределённый консенсус](htt
> Hive следит за тем, что акутальное поколение каждой таблетки запущено ровно на одном узле

Разве? Выше написано, что такую гарантию дает сторадж.

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Создание и удаление таблеток инициируется таблеткой [SchemeShard](../concepts/glossary.md#scheme-shard). При создании таблетки Hive присваивает ей уникальный TabletId, заполняет [TabletStorageInfo](g
```suggestion
Создание и удаление таблеток инициируется таблеткой [SchemeShard](../concepts/glossary.md#scheme-shard). При создании таблетки Hive присваивает ей уникальный идентификатор (TabletId), заполняет [TabletStorageInfo](general-schema.md#history), выбирает наиболее подходящий узел и отправляет на него команду поднятия таблетки. В некоторых нестандартных ситуациях отдельная таблетка может прервать работу, тогда узел, на котором она была запущена, отправляет сообщение в Hive. Также Hive предполагает, что если связь с некоторым узлом потеряна, то запущенные на нём таблетки прекратили работу. В таких ситуациях Hive запускает таблетки на других узалах с увеличением поколения.
```

Возможно, еще стоит добавить ссылку на TabletId.

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Для распределения таблеток по узлам Hive учитывает потребление ресурсов. Для каждой таблетки учитываются потребления 4 ресурсов:
```suggestion
Для распределения таблеток по узлам Hive учитывает потребление ресурсов. Для каждой таблетки учитывается потребление 4 типов ресурсов:
```

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +1. *Counter* — фиктивный ресурс, используемый для реализации равномерного распределения в штуках. Применяется для любых таблеток, для которых нет данных по трём другим ресурсам, а также для таблеток
Нужна ссылка на колоночные таблицы.

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Дополнительно для определения перегруженных узлов используются метрики потребления ресурсов узла целиком: потребление оперативной памяти, и ресурсов процессора в пулах акторной системы. Эти значения
```suggestion
Дополнительно для определения перегруженных узлов используются метрики потребления ресурсов узла целиком: потребление оперативной памяти и ресурсов процессора в пулах акторной системы. Эти значения переводятся в относительную величину (число от 0 до 1), и их максимум используется как значение общего потребления ресурсов узла — *Node usage*. Также для всех метрик на стороне Hive используется аггрегация на окне, чтобы учитывать всплески нагрузки.
```

2024-12-28 10:38 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Для таблеток, которые используют ресурс Counter, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы), с помощью метрики *ObjectImbalance*, аналогичной описанной
```suggestion
Для таблеток, которые используют ресурс Counter, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы) с помощью метрики *ObjectImbalance*, аналогичной описанной выше Scatter. При рестартах узлов равномерность может нарушаться, и тогда запускается балансировка.
```

2025-01-10 11:47 UTC, CyberROFL reviewed
В целом, для начала достаточно.

2025-01-10 11:47 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/glossary.md
>  #### Scheme shard {#scheme-shard}
Хайв тоже просится в глоссарий. И сразу можно сослаться на новую статью.

2025-01-10 12:06 UTC, CyberROFL commented on ydb/docs/ru/core/contributor/hive.md
> +Hive — таблетка, отвечающая за управление другими таблетками. В кластере {{ ydb-short-name }} есть корневой Hive, который отвечает за системные таблетки всех баз данных кластера. Hive конкретной базы
Добавь в глоссарий и сделай кросс-ссылку (оттуда-сюда, отсюда-туда).

2025-01-20 06:43 UTC, anton-bobkov commented on ydb/docs/ru/core/contributor/hive.md
> +1. *Counter* — фиктивный ресурс, используемый для реализации равномерного распределения в штуках. Применяется для любых таблеток, для которых нет данных по трём другим ресурсам, а также для таблеток
```suggestion
1. *Count* — фиктивный ресурс, используемый для реализации равномерного распределения таблеток одного типа между узлами. Применяется для любых таблеток, для которых нет данных по трём другим ресурсам, а также для таблеток [колоночных таблиц](../concepts/datamodel/table.md#column-oriented-tables).
```
Предложение "Если у таблетки есть этот ресурс, то его значение всегда равно 1" звучит непонятно.

2025-01-20 06:43 UTC, anton-bobkov commented on ydb/docs/ru/core/contributor/hive.md
> +Дополнительно для определения перегруженных узлов используются метрики потребления ресурсов узла целиком: потребление оперативной памяти, и ресурсов процессора в пулах акторной системы. Эти значения
```suggestion
Дополнительно для определения перегруженных узлов используются метрики потребления ресурсов узла целиком: потребление оперативной памяти, и ресурсов процессора в пулах акторной системы. Эти значения переводятся в относительную величину (число от 0 до 1), и их максимум используется как значение общего потребления ресурсов узла — *Node usage*. Также для всех метрик на стороне Hive используется агрегация на окне, чтобы учитывать всплески нагрузки.
```

2025-01-20 06:43 UTC, anton-bobkov commented on ydb/docs/ru/core/contributor/hive.md
> +Для таблеток, которые используют ресурс Counter, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы) с помощью метрики *ObjectImbalance*, аналогичной описанной в
```suggestion
Для таблеток, которые используют ресурс Count, также отслеживается равномерность распределения таблеток каждого объекта (каждой таблицы) с помощью метрики *ObjectImbalance*, аналогичной описанной выше Scatter. При рестартах узлов равномерность может нарушаться, и тогда запускается балансировка.
```

2025-01-20 11:25 UTC, vporyadke commented on ydb/docs/ru/core/contributor/hive.md
> +1. *Counter* — фиктивный ресурс, используемый для реализации равномерного распределения в штуках. Применяется для любых таблеток, для которых нет данных по трём другим ресурсам, а также для таблеток
Тут предложения фактически неверные :(
Ресурс называется именно Counter во всех протобуфах, и в developer ui. Он не связан напрямую с конкретным типом - в теории можно настроить, чтобы у тебя все таблетки были с ним, и будут считаться вместе а не отдельно по типам.

Звучит непонятно - а что непонятно? Можно написать просто "значение у таблетки 0 или 1" - но это будет непонятно, а почему это может быть 0. Просто убрать чтобы не грузить?

2025-01-27 17:54 UTC, fomichev3000 requested changes
В целом статья читаемая. Особенно, если поправить комментарии.

Однако не очень понятна аудитория. Для контрибьютора она слишком высокоуровневая, для концепции чуть более сложная, особенно, если с порога про глобальный/тенантный hive.

Что надо еще написать. Можно отдельным коммитом?
1. Как управлять Хайвом и зачем. Для этого есть UI
2. Как настраивать Хайд, какие параметры
3. Возможно рецепты (уж не знаю в каком разделе), про то, какие проблемы с балансировкой таблеток могут возникнуть, и как их решать

2025-01-27 17:54 UTC, fomichev3000 commented on ydb/docs/ru/core/contributor/hive.md
> +Hive — таблетка, отвечающая за управление другими таблетками. В кластере {{ ydb-short-name }} есть корневой Hive, который отвечает за [системные таблетки](../concepts/glossary.md#tablet-types) всех б
```suggestion
Hive — таблетка, отвечающая за управление другими таблетками, а именно, за выбор, на каких узлах базы запускать таблетку, принимает решение о необходимости перебалансировать таблетки и т.п. В кластере {{ ydb-short-name }} есть корневой Hive, который отвечает за [системные таблетки](../concepts/glossary.md#tablet-types) всех баз данных кластера. Hive конкретной базы данных в свою очередь отвечает за таблетки, обслуживающие пользовательскую нагрузку этой базы данных. Все узлы кластера регистрируются в корневом Hive, а в Hive конкретной базы регистрируются только вычислительные узлы этой базы. При регистрации узел сообщает в Hive, таблетки каких типов и в каких количествах могут быть на нём запущены.
```

2025-01-27 17:54 UTC, fomichev3000 commented on ydb/docs/ru/core/contributor/hive.md
> +### Дисбаланс потребления ресурсов
Я бы сделал ссылку на метрики и дашборды, которые можно мониторить

2025-01-27 17:54 UTC, fomichev3000 commented on ydb/docs/ru/core/contributor/hive.md
> +## Автобалансировка
Забавно, нигде не описан алгоритм, по которому осуществляется балансировка. В целом у нас балансировка по доминантному ресурсу, возможно с модификациями.

2025-01-31 09:00 UTC, blinkov requested changes, later dismissed

2025-01-31 09:00 UTC, blinkov commented on ydb/docs/ru/core/concepts/glossary.md
>  #### Scheme shard {#scheme-shard}
он вон ниже есть на 394 строке

2025-02-06 05:03 UTC, blinkov commented on ydb/docs/ru/core/contributor/hive.md
> +### Дисбаланс потребления ресурсов
в чатике выяснили, что их пока нет, но планируются

2025-02-06 05:08 UTC, blinkov commented on ydb/docs/ru/core/contributor/hive.md
> +где $\mathrm{MaxUsage}$ и $\mathrm{MinUsage}$ — соответственно максимум и минимум потребления данного ресурса среди всех узлов. Для нормировки потребления на каждом узле используется число доступных
```suggestion
$$\mathrm{Scatter} = \frac{\mathrm{MaxUsage} - \mathrm{MinUsage}}{\mathrm{MaxUsage}}$$

$\mathrm{MaxUsage}$ и $\mathrm{MinUsage}$ — максимум и минимум потребления данного ресурса среди всех узлов, соответственно. Для нормировки потребления на каждом узле используется число доступных ресурсов на узле, которое может различаться между узлами. При низких нагрузках эта величина может сильно колебаться. Чтобы этого избежать, при вычислении $\mathrm{Scatter}$ считается, что потребление ресурса не может быть ниже 30%. Если $Scatter$ превышает порог, запускается балансировка.
```

2025-02-06 06:56 UTC, fomichev3000 approved these changes

2025-02-06 06:56 UTC, merged