First iteration of QueryService documentation
ydb-platform/ydb pull request #7415
Opened 2024-08-02 11:40 UTC by alex268

### Changelog category 

* Documentation (changelog entry is not required)

2024-08-06 07:01 UTC, blinkov requested changes

2024-08-06 07:01 UTC, blinkov commented on ydb/docs/ru/core/dev/toc_p.yaml
> +    path: query-service-app/toc_p.yaml
Сам текст похоже и так уже является форком старого — я тогда пока не буду ревьюить его целиком, лучше потом на дифф посмотрю.

2024-08-08 09:32 UTC, alex268 commented on ydb/docs/ru/core/concepts/query_service.md
> +{% include [query_service.md](_includes/query_service.md) %}
Убрал

2024-08-08 09:37 UTC, alex268 commented on ydb/docs/ru/core/concepts/_includes/query_service.md
> +{% endnote %}
Поправил стилитику, что бы действительно не выглядело как введение в пост. Не совсем уверен, но думаю что будет неверно писать что QueryService заменяет TableService, насколько я понимаю этого и не планируется. Т.е. некакого deprecated для TableService не будет, QueryService лишь альтернатива для одно из его методов. Более того, в будущем ожидается скорее неявное использование QueryService при работае с TableService на уровне SDK

2024-08-08 09:38 UTC, alex268 commented on ydb/docs/ru/core/concepts/_includes/query_service.md
> +# Query service в {{ ydb-short-name }}
Добавил краткое описание всех активно используемых сервисов - table, query и topic

2024-08-08 09:39 UTC, alex268 commented on ydb/docs/ru/core/concepts/_includes/query_service.md
> +- Java [https://github.com/ydb-platform/ydb-java-sdk](https://github.com/ydb-platform/ydb-java-sdk)
Строчку в feature-parity тоже добавил, но тут проблема что на нее нельзя сделать ссылку. Я тут планирую все таки разместить ссылки не на SDK а на конкретные примеры использования, просто этот пример существуюет пока только для Java

2024-08-08 09:46 UTC, alex268 commented on ydb/docs/ru/core/concepts/_includes/query_service.md
> +## Как воспользоваться {#how-use}
Не думаю что отдельный гайд будет иметь смысл. Если как мы планируем - QueryService начнет использоваться под капотом SDK даже для TableService, то вся миграция будет выполнена уже там, клиентам ничего дополнитльено мигрировать не нужно будет. Но тем не менее, использование TableService будет накладывать свои ограничения, и кому то из клиентов воможно надо будет использовать QueryService напрямую, вот для них этот раздел и предназначен

2024-09-23 03:01 UTC, blinkov commented
The decision has been made to take a different approach to documenting this.

2024-09-23 03:01 UTC, closed without merging