Add feature flag for exclusive dynamic nodes KIKIMR-20562
ydb-platform/ydb pull request #748
Opened 2023-12-27 12:36 UTC by pixcc

2023-12-27 16:40 UTC, CyberROFL requested changes

2023-12-27 16:40 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard__operation_alter_extsubdomain.cpp
> +            return paramError("Unsupported: feature flag EnableExclusiveDynamicNodes is off");
Если я правильно понимаю, то ошибка будет со статусом InvalidParameter? Если так, то это не совсем то, что ожидается — PreconditionFailed.

2023-12-27 16:40 UTC, CyberROFL commented on ydb/core/tx/schemeshard/schemeshard_impl.cpp
> +    EnableExclusiveDynamicNodes= appData->FeatureFlags.GetEnableExclusiveDynamicNodes();
Верстка поехала.

2023-12-28 10:09 UTC, CyberROFL approved these changes, later dismissed

2023-12-28 23:16 UTC, ijon requested changes

2023-12-29 10:41 UTC, ijon approved these changes

2023-12-29 10:53 UTC, merged