Small fixes in LLVM debug info
ydb-platform/ydb pull request #7527
Opened 2024-08-07 09:09 UTC by avevad

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-07 09:35 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
> +    Y_ENSURE(subprogramAnnotator != nullptr);
к этому моменту уже был вызван SubprogramAnnotator.MakeDIFile(location)

перенеси это после ensure

2024-08-07 11:37 UTC, vitstn requested changes
comments

2024-08-07 13:23 UTC, avevad commented on ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
> +    Y_ENSURE(subprogramAnnotator != nullptr);
fixed

2024-08-08 09:57 UTC, vitstn approved these changes

2024-08-14 08:58 UTC, merged