YQ-2715: add ydb data source
ydb-platform/ydb pull request #753
Opened 2023-12-27 14:56 UTC by Woodey777

2023-12-27 15:19 UTC, vitalyisaev2 requested changes

2023-12-27 15:19 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
`mdb_cluster_id` не нужно для YDB, так как оно не относится к MDB

@dorooleg правда же?

2023-12-27 15:19 UTC, vitalyisaev2 commented on ydb/core/fq/libs/actors/clusters_from_connections.cpp
> +            break;
Это изменение слегка преждевременное. Без него и так всё должно заработать. Это нужно только для сервиса YQ.

2023-12-27 15:25 UTC, dorooleg commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
1. Тут нужно убрать `MDB_BASIC`, а оставить только `BASIC` и `SERVICE_ACCOUNT`
2. `mdb_cluster_id` действительно не нужен. Я бы еще убрал protocol, у ydb нету выбора на протокол.
3. Нужен еще `database_id` его потом резолвить нужно в endpoint/database_name

2023-12-27 19:20 UTC, dorooleg commented
Еще не понятно почему при не валидных настройках зависает connector. Про это нужно не забыть и в отдельном ревью поправить

2023-12-27 19:48 UTC, Woodey777 commented
> Еще не понятно почему при не валидных настройках зависает connector. Он должен отрепортить ошибку хотя бы. Про это нужно не забыть и в отдельном ревью поправить

да, это похоже из-за того что на соединении не стоит таймаут никакой
надо исправить

2023-12-27 20:10 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
> Я бы еще убрал protocol, у ydb нету выбора на протокол.

Тогда получится небольшая асимметрия. Ведь у PostgreSQL тоже нет права выбора протокола... Тогда и там отпиливать тоже (и менять публичную документацию).

2023-12-28 07:43 UTC, dorooleg commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
Я за то чтобы оставить только используемые поля. Нету смысле передавать не нужные поля, это будет путать пользователя. Давайте выпилим)

2023-12-28 07:49 UTC, dorooleg commented
Еще нужно добавить хотя бы два теста:
1. https://a.yandex-team.ru/arcadia/ydb/core/kqp/ut/federated_query/generic/kqp_generic_plan_ut.cpp?rev=13169068#L22
2. https://a.yandex-team.ru/arcadia/ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp?rev=r13161422#L45

2023-12-28 08:07 UTC, vitalyisaev2 commented on ydb/core/external_sources/external_source_factory.cpp
> +            CreateExternalDataSource(TString{NYql::GenericProviderName}, {"MDB_BASIC", "BASIC"}, {"database_name", "protocol", "mdb_cluster_id", "use_tls"}, hostnamePatternsRegEx)
Завёл https://st.yandex-team.ru/YQ-2746

2024-01-10 15:54 UTC, vitalyisaev2 requested changes

2024-01-10 15:54 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/connector_client_mock.h
> +        // NApi::EProtocol protocol = DEFAULT_YDB_PROTOCOL,
можно удалить

2024-01-10 15:54 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/connector_client_mock.cpp
> +            // "protocol"_a = NYql::NConnector::NApi::EProtocol_Name(protocol),
можно удалить

2024-01-10 15:54 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/actors/yql_generic_source_factory.cpp
> +        for (auto& sourceName : {"ClickHouseGeneric", "PostgreSqlGeneric", "YDBGeneric"}) {
@dorooleg как правильно - `YDBGeneric` или  `YdbGeneric`?... терзают смутные сомнения )

2024-01-10 15:54 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        dbNameTarget = "ydb";
Здесь должно находиться имя дефолтной базы данных для YDB. В CH дефолтная база называется `default`,  в PG - `postgres`. В YDB вообще такая база есть?

2024-01-10 16:42 UTC, Woodey777 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        dbNameTarget = "ydb";
вот 3 варианта запуска ydb и во всех название базы по умолчанию разное

https://ydb.tech/docs/ru/getting_started/self_hosted/ydb_docker#conn
https://ydb.tech/docs/ru/getting_started/self_hosted/ydb_local#conn
https://ydb.tech/docs/ru/getting_started/self_hosted/ydb_minikube#test-ydb

2024-01-10 20:59 UTC, vitalyisaev2 requested changes

2024-01-10 20:59 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        dbNameTarget = "ydb";
Надо спросить у знающих людей. Я подозреваю, что это `/local` (именно со слеша)

2024-01-11 08:44 UTC, dorooleg commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        dbNameTarget = "ydb";
Понятия default базы в ydb нету. Это всегда обязательный параметр в cli и sdk

2024-01-11 08:48 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
> +                        dbNameTarget = "ydb";
Тогда надо:
1. Убрать этот case для YDB
2. Ниже в default поправить текст исключения на что-то типа `"You must provide database name explicitly for data source kind: " << ...`

2024-01-11 08:52 UTC, dorooleg commented on ydb/library/yql/providers/generic/actors/yql_generic_source_factory.cpp
> +        for (auto& sourceName : {"ClickHouseGeneric", "PostgreSqlGeneric", "YDBGeneric"}) {
У меня нету строгого мнения в этом месте. Давайте `YdbGeneric` потому что везде в коде `Ydb` вместо `YDB` и в синтаксисе при создании external table также

2024-01-11 09:21 UTC, dorooleg requested changes

2024-01-11 09:21 UTC, dorooleg commented on ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/connector_client_mock.h
> +        bool useTls = DEFAULT_USE_TLS,
нужно удалить пробел в конце

2024-01-25 07:04 UTC, dorooleg approved these changes

2024-01-25 07:49 UTC, vitalyisaev2 approved these changes

2024-01-25 09:05 UTC, vitstn approved these changes

2024-01-25 11:08 UTC, merged