[CBO] Make optimizer get only columns stats that are used in request
ydb-platform/ydb pull request #7550
Opened 2024-08-07 18:01 UTC by pashandor789

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-15 21:53 UTC, resetius approved these changes, later dismissed

2024-08-16 09:27 UTC, pavelvelikhov requested changes
Все круто, но некоторые названия, особенно те, которые снаружи видны, так себе.

2024-08-16 09:27 UTC, pavelvelikhov commented on ydb/core/kqp/host/kqp_runner.cpp
> +#include <ydb/core/kqp/opt/kqp_columns_getter_transformer.h>
Columns_getter - не очень хорошее название для этого трансформера. Он другим занимается
Подумай как лучше назвать, чтобы понятно было
Например RequiredColumnStatistics

2024-08-16 09:27 UTC, pavelvelikhov commented on ydb/core/kqp/opt/kqp_columns_getter_transformer.cpp
> +            TableByExprNode[lambda.Args().Arg(0).Ptr()] = TableByExprNode[callableInput.Get()];
Тоже так себе название

2024-08-16 13:03 UTC, pavelvelikhov approved these changes

2024-08-16 17:02 UTC, resetius approved these changes

2024-08-16 17:05 UTC, merged