Resource Pools and Resource Classifiers documentation (ru version)
ydb-platform/ydb pull request #7649
Opened 2024-08-12 09:22 UTC by dorooleg

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-09-02 21:46 UTC, gridnevvvit commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool.md
> +    * `QUERY_MEMORY_LIMIT_PERCENT_PER_NODE` (Int) - опциональное поле, которое задает процент доступной памяти на ноде запросом в этом пуле. Если значение -1, то ограничений нет. Допустимые значения:
тут кажется несколько confusing. ограничения есть даже если стоит -1, просто память ограничивается суммарно на ноду всеми запросами во всех пулах.

если указан этот процент, то суммарно запросы в этом пуле могут потребить не более этого процента.

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +    - `GlobalDelayedRequests` - количество запросов ожидающих в очереди на выполнение
Все эти метрики (кроме `AverageLoadPercentage`) отключены фича флагом по умолчанию, это ок?

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Существуют полезные метрики для отслеживания загруженности resource pool, эти метрики находятся в service `resource_pool`:
Тут ошибка, метрики workload manager находятся в service=kqp, subsystem=workload_manager:
https://github.com/ydb-platform/ydb/blob/f759853866bc63ca460a17a8545182280c473f2b/ydb/core/kqp/counters/kqp_counters.cpp#L735

Метрика `AverageLoadPercentage` лежит в subcomponent=CpuQuotaManager:
https://github.com/ydb-platform/ydb/blob/f759853866bc63ca460a17a8545182280c473f2b/ydb/core/kqp/workload_service/kqp_workload_service.cpp#L73

Остальные метрики лежат в pool=\<database name\>/\<pool id\>:
https://github.com/ydb-platform/ydb/blob/f759853866bc63ca460a17a8545182280c473f2b/ydb/core/kqp/workload_service/actors/pool_handlers_acors.cpp#L51
`GlobalDelayedRequests` и `GlobalInFly` репортятся только для пулов с `CONCURRENT_QUERY_LIMIT` или `DATABASE_LOAD_CPU_THRESHOLD`

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +name | Utf8 | имя resource pool classifier
Кажется тут должно быть `resource pool`, а не `resource pool classifier`

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Допустим у нас есть два resource pool classifier которые имеют конфликтующее условия. В этом случае один пользователь `user1@domain` подходит под два resource pool: `olap1`, `olap2`. Если в системе д
Может быть ещё написать, как выбирается классификатор, если пользователь состоит в нескольких группах (в этом случае порядок проверки групп не гарантирован, берётся первая для которой нашёлся рабочий классификатор)? При этом сначала ищется классификатор для UserSID, потом уже для групп

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +* `RANK` (Int) - опциональное поле которое задает порядок выбора resource pool.
Наверное будет понятнее сказать, что RANK задаёт порядок проверки классификаторов (от меньшего к большему), а не порядок выбора resource pool.

Ещё не стоит ли тут уточнить, что это Int64 (или уточнить границы допустимых значений, как это сделано в [alter-resource-pool.md](https://github.com/ydb-platform/ydb/pull/7649/files#diff-a46b53753e0898f8d0e9df3b553b49d49742c3283abfb4aaabdc3991c3fdfd8cR7)) и при этом число должно быть неотрицательное / уникальное?

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +* `RESOURCE_POOL` (String) - обязательное поле задающее имя resource pool в который будут отправлены запросы удовлетворяющие критериям resource pool classifier.
Сейчас это поле не является обязательным, если его не указать, то оно будет равно `default`, то-есть дефолтному пулу:
https://github.com/ydb-platform/ydb/blob/f759853866bc63ca460a17a8545182280c473f2b/ydb/core/resource_pools/resource_pool_classifier_settings.h#L31

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +ALTER RESOURCE POOL olap_classifier SET (MEMBERNAME = "user2@domain");
Тут не хватает ключевого слова `CLASSIFIER` в `ALTER ... SET` команде

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +ALTER RESOURCE POOL <имя> RESET (<key>);
Тут не хватает ключевого слова `CLASSIFIER` в `ALTER ... RESET` команде

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +* `QUERY_CPU_LIMIT_PERCENT_PER_NODE` (Int) - опциональное поле, которое задает процент доступного CPU на запрос в пуле на ноде. Если значение -1, то ограничений нет. Допустимые значения: -1, [0, 100]
Все `PERCENT` параметры, а именно `QUERY_MEMORY_LIMIT_PERCENT_PER_NODE`, `TOTAL_CPU_LIMIT_PERCENT_PER_NODE`, `QUERY_CPU_LIMIT_PERCENT_PER_NODE`, имеют тип double, думаю стоит дать пользователям это знать

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +ALTER RESOURCE POOL olap SET (CONCURRENT_QUERY_LIMIT = -1);
Такая команда не заработает, надо написать:
`ALTER RESOURCE POOL olap SET (CONCURRENT_QUERY_LIMIT = "-1");`

Прописывать можно только положительные целые числа (соответственно сбрасывать через RESET, либо так). Может лучше тут делать пример не для сброса настроек (по аналогии с [alter-resource-pool-classifier.md](https://github.com/ydb-platform/ydb/pull/7649/files#diff-481d42bdec67bf4451478cd4020dac7721e7d92e88eb8db68218880c2c68ba49R24)), ведь пример сброса уже есть?

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +Требуется разрешение `ALTER SCHEMA` на директорию `.metadata/workload_manager/pools`
Тут можно уточнить до `ALTER SCHEMA` на пул который меняет пользователь

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +* `имя` - имя создаваемого resource pool classifier. Должно быть уникально. Не допускается запись в виде пути (т.е. не должно содержать `/`).
Для классификаторов такого ограничения на имя нету, оно может быть любой Utf8 строкой

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +    * `MEMBERNAME` (String) - опциональное поле которое задает какой пользователь или группа должны быть отправлены в описанные классификатор
Думаю стоит поменять описания параметров аналогично [alter-resource-pool-classifier.md](https://github.com/ydb-platform/ydb/pull/7649/files#diff-481d42bdec67bf4451478cd4020dac7721e7d92e88eb8db68218880c2c68ba49R7)

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +В базе данных есть ограничение на максимальное число пулов и оно равно 1000. Это ограничение выбрано специально в целях оптимизации производительности
Ограничения на число пулов нету, есть только ограничение на число классификаторов:
https://github.com/ydb-platform/ydb/blob/f759853866bc63ca460a17a8545182280c473f2b/ydb/core/resource_pools/resource_pool_classifier_settings.h#L11

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +Также возможно иметь resource pool classifer которые ссылаются на не существующий resource pool или те у которых нету доступов к нему, в этом случае они пропускаются.
Кажется `или те у которых нету доступов к нему` может ввести в заблуждение, у классификаторов нету особых доступов для пулов, если пул есть (на который указывает классификатор) то классификатор для каких-то пользователей работает, для каких-то нет (зависит от пользователя)

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool.md
> +    * `RESOURCE_WEIGHT` (Int) - опциональное поле, которое задает веса распределения ресурсов между пулами. Если значение -1, то веса выключены. Допустимые значения: -1, [0, MAX_INT32]
Думаю стоит поменять описания параметров аналогично [alter-resource-pool.md](https://github.com/ydb-platform/ydb/pull/7649/files#diff-a46b53753e0898f8d0e9df3b553b49d49742c3283abfb4aaabdc3991c3fdfd8cR12)

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool.md
> +Запросы всегда выполняются в каком-то resource pool. По умолчанию все запросы отправляются в `default` resource pool, который создается по умолчанию. Этот resource pool нельзя удалить, он всегда суще
Аналогично комментарию для [resource-pools-and-classifiers.md](https://github.com/ydb-platform/ydb/pull/7649/files#diff-3b64a78ef579d1740ec4658fa4541629f9997e8d4db46f6bc3f3a0ea3533ac25R25)

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool.md
> +В примере выше создается resource pool в котором есть ограничение на максимальное число параллельных запросов `20`, максимальный размер очереди ожидания `1000`. В случае достижения загрузки базы данн
Есть опечатка `UVERLOADED` -> `OVERLOADED`

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-resource-pool-classifier.md
> +* `имя` - не должно содержать в себе символ `/`, оно не привязано к иерархии схемы
Особых ограничений для имён классификаторов нету, имя это любая Utf8 строка

2024-09-03 07:59 UTC, GrigoriyPA commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-resource-pool.md
> +Требуется разрешение `REMOVE SCHEMA` на директорию `.metadata/workload_manager/pools`
Можно уточнить до `REMOVE SCHEMA` на пул, который пользователь хочет дропнуть

2024-09-03 15:02 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Это означает что никакие ограничения в этом resource pool не применимы, он живет полностью независимо от других resource pool, а также не имеет ограничений на потребляемые ресурсы. В `default` resour
Это кстати отличный пример для валидации комбинаций параметров. Может тут стоит ошибку выдать в этом случае тоже? Иначе пользователь укажет очередь, а эффекта никакого не будет.

2024-09-03 15:45 UTC, GrigoriyPA commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Это означает что никакие ограничения в этом resource pool не применимы, он живет полностью независимо от других resource pool, а также не имеет ограничений на потребляемые ресурсы. В `default` resour
Можно какой-нибудь warning написать наверное, что `QUEUE_SIZE` который указал пользовать на самом деле не работает

2024-09-09 09:22 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-resource-pool-classifier.md
> +* `имя` - не должно содержать в себе символ `/`, оно не привязано к иерархии схемы
Обсудили и решили сделать как в SS. Чтобы тут не отличаться. Ослаблять гораздо проще правила именования чем закручивать

2024-09-09 09:42 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Даже если ни одного resource pool не было создано, то в системе всегда существует `default` resource pool, который не может быть удален. Любой запрос который выполняется в системе всегда выполняется
Это наша внутренняя деталь. Думаю тут не стоит про это упоминать.

2024-09-09 09:45 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Это означает что никакие ограничения в этом resource pool не применимы, он живет полностью независимо от других resource pool, а также не имеет ограничений на потребляемые ресурсы. В `default` resour
Договорились добавить валидации на не совместимые параметры

2024-09-09 09:57 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +    - `GlobalDelayedRequests` - количество запросов ожидающих в очереди на выполнение
Да, это ок.

2024-09-09 10:10 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Существуют полезные метрики для отслеживания загруженности resource pool, эти метрики находятся в service `resource_pool`:
Договорились перенести в service=resource_pool

2024-09-09 10:23 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Допустим у нас есть два resource pool classifier которые имеют конфликтующее условия. В этом случае один пользователь `user1@domain` подходит под два resource pool: `olap1`, `olap2`. Если в системе д
Договорились поменять реализацию чтобы выбирался первый подходящий классификатор в соответствии с rank

2024-09-09 10:41 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +* `RESOURCE_POOL` (String) - обязательное поле задающее имя resource pool в который будут отправлены запросы удовлетворяющие критериям resource pool classifier.
Договорились сделать обязательным

2024-09-16 12:08 UTC, blinkov submitted a review, later dismissed
В сам текст пока детально не вчитывался, т.к. структурных изменений ещё много предстоит.

2024-09-16 12:08 UTC, blinkov commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +## Создание resource pool
Перед тем как бросатсья в примеры не хватает описания общей картины как оно вообще работает. В идеале с картинками. В целом можно описать её в концепциях, а отсюда сослаться.

Например, не понятны даже базовые вещи в духе это всё глобальное, per-database или per-node, иерархичные ли пулы и т.п.

2024-09-16 12:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +Требуется разрешение `ALTER SCHEMA` на resource pool в директории `.metadata/workload_manager/pools`
не помешал бы пример `GRANT` запроса

2024-09-16 12:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +В базе данных есть ограничение на максимальное число resource pool classifier и оно равно 1000. Это ограничение выбрано специально в целях оптимизации производительности. Ограничение на число resourc
Про это лучше написать в https://ydb.tech/docs/en/concepts/limits-ydb

2024-09-16 12:08 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/toc_i.yaml
> +- { name: ALTER RESOURCE POOL CLASSIFIER,    href: alter-resource-pool.md,   when: feature_resource_pool_classifier }
в presets.yaml как-будто не выставлены эти переменные?

2024-09-16 12:08 UTC, blinkov commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +![resource_pools](../_assets/resource_pools.png)
1. картинка слишком мелкая, вероятно стоит разбить на несколько более крупных
2. рядом с картинкой надо приложить файл с её исходниками на случай, если позже нужны будут правки

либо лучше перерисовать на встроенный механизм диаграмм https://diplodoc.com/docs/ru/tools/mermaid

2024-09-17 17:00 UTC, GrigoriyPA submitted a review, later dismissed

2024-09-23 06:29 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +В базе данных выделяются ресурсы (CPU, disk, RAM, ...) используемые всеми запросами на равных условиях без каких либо ограничений. Если же необходимо разделять ресурсы в одной базе данных, то для это
Перенес в концепции

2024-09-23 06:36 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +В базе данных выделяются ресурсы (CPU, disk, RAM, ...) используемые всеми запросами на равных условиях без каких либо ограничений. Если же необходимо разделять ресурсы в одной базе данных, то для это
Не ожиданно конечно. В OSS есть техническая возможность поднимать dedicated/shared/sls базы данных. Но пока нету такого упоминания в документации, то убираю и здесь, спасибо

2024-09-23 06:42 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +#### Resource Pool {#resource-pool}
Да, звучит хорошо. Переделал на русскую версию

2024-09-23 06:42 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +#### Resource Pool {#resource-pool}
Перенес

2024-09-23 06:44 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +**Resource Pool** - объект схемы который описывает ограничения накладываемые на потребляемые ресурсы (CPU, disk, RAM, ...) запросами в этом resource pool. Запрос всегда выполняется в каком-то resourc
Здесь подразумевался контроль над spilling. Но сейчас этого фактически не реализовано. Убираю упоминание из документации. Перечислил все управляемые ресурсы на текущий момент

2024-09-23 06:51 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Описание этих сущностей может быть найдено в [resource pool](../concepts/glossary#resource-pool) и [resource pool classifier](../concepts/glossary#resource-pool-classifier)
Прошелся по всем файлам и поправил

2024-09-23 07:11 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +### Системные таблицы
Поправил

2024-09-23 07:53 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +### Метрики
Перенес

2024-09-23 07:56 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +```
У нас в плане сейчас содержится статистика. Даже были какие-то мысли красиво рисовать сколько данных было прочитано в каждом узле плана (статус задачи не знаю). Про инструкцию хорошая мысль, попробую поискать в ydb cli наличие такое

2024-09-23 08:02 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +    MEMBERNAME = 'user1@domain'
Уже не первый человек задает этот вопрос. Пока не поздно можем переименовать в коде на `MEMBER_NAME`. Текущее название было взято из sanypse analytics https://learn.microsoft.com/en-us/sql/t-sql/statements/create-workload-classifier-transact-sql?view=azure-sqldw-latest Там аналогичным образом есть названия с _ и без :) Если нужно переименовать, то скажи пожалуйста, это быстро исправить.

2024-09-23 08:19 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +```
Хм, забавно, а в cli это реально в разделе stats сделали. А в embedded UI вместе с планом приходит.

2024-09-23 08:23 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +```
Но все равно в разделе с планом

2024-09-23 08:32 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +```
Нужную команду не нашел. Поэтому сослался сюда https://ydb.tech/docs/ru/yql/query_plans и привел конкретную команду

2024-09-23 08:39 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Ознакомиться с параметрами resource pool можно [здесь](../yql/reference/yql-core/syntax/create-resource-pool#параметры)
Не хорошо получилось, исправил

2024-09-23 08:46 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +ALTER RESOURCE POOL CLASSIFIER <имя> SET (<key> = <value>);
Делал по аналогии с https://github.com/ydb-platform/ydb/blob/main/ydb/docs/ru/core/yql/reference/yql-core/syntax/create-view.md Наверное в других местах тоже нужно поправить. В пулах ресурсов поправил

2024-09-23 08:47 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +```<key>``` — имя параметра, ```<value>``` — его новое значение.
исправил

2024-09-23 08:51 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +* `MEMBERNAME` (String) - опциональное поле которое задает какой пользователь или группа должны быть отправлены в описанные классификатор
поправил

2024-09-23 08:53 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +* `RANK` (Int) - опциональное поле которое задает порядок выбора resource pool classifier. Допустимые значения: уникальное число [0, MAX_INT64]
поправил

2024-09-23 08:58 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Допустим у нас есть два resource pool classifier которые имеют конфликтующее условия. В этом случае один пользователь `user1@domain` подходит под два resource pool: `olap1`, `olap2`. Если в системе д
Поправил

2024-09-23 09:01 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +```sql
Забавно, в других места все еще встречается sql https://cs.yandex-team.ru/#!%60%60%60sql,contrib%2Fydb.*yql,jm,arcadia,,5000

2024-09-23 09:01 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +```sql
поправил

2024-09-23 09:05 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +Требуется разрешение `ALL` на базу данных
добавил

2024-09-23 09:09 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool-classifier.md
> +## См. также
добавил

2024-09-23 09:17 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +### Параметры
вынес

2024-09-23 09:20 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +* `CONCURRENT_QUERY_LIMIT` (Int) - опциональное поле, которое задает число параллельно выполняющихся запросов в resource pool. Если значение -1, то ограничений нет. Допустимые значения: -1, [0, MAX_I
поправил

2024-09-23 09:21 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +* `CONCURRENT_QUERY_LIMIT` (Int) - опциональное поле, которое задает число параллельно выполняющихся запросов в resource pool. Если значение -1, то ограничений нет. Допустимые значения: -1, [0, MAX_I
поправил

2024-09-23 09:21 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +* `CONCURRENT_QUERY_LIMIT` (Int) - опциональное поле, которое задает число параллельно выполняющихся запросов в resource pool. Если значение -1, то ограничений нет. Допустимые значения: -1, [0, MAX_I
поправил

2024-09-23 09:31 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-resource-pool.md
> +Требуется разрешение `ALTER SCHEMA` на resource pool в директории `.metadata/workload_manager/pools`
добавил примеров

2024-09-23 09:38 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/toc_i.yaml
> +- { name: ALTER RESOURCE POOL CLASSIFIER,    href: alter-resource-pool.md,   when: feature_resource_pool_classifier }
поправил

2024-09-23 11:52 UTC, dorooleg commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create-resource-pool-classifier.md
> +В базе данных есть ограничение на максимальное число resource pool classifier и оно равно 1000. Это ограничение выбрано специально в целях оптимизации производительности. Ограничение на число resourc
поправил

2024-09-23 12:35 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +## Создание resource pool
Добавил общее описание. Ниже находится подробное поведения для параметров

2024-09-23 19:14 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +![resource_pools](../_assets/resource_pools.png)
поправил

2024-09-23 19:15 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-pools-and-classifiers.md
> +Рассмотрим на примере выше что же на самом деле означают эти параметры и как они будут влиять на распределение ресурсов. Допустим в базе данных {{ ydb-short-name }} выделено 10 узлов по 10 vCPU. В су
поправил

2024-09-24 06:47 UTC, fomichev3000 requested changes

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/glossary.md
> +**Пул ресурсов** или **resource pool** — объект схемы, который описывает ограничения, накладываемые на потребляемые ресурсы (CPU, RAM, максимальная параллельность выполнения запросов) в этом пуле рес
```suggestion
**Пул ресурсов** или **resource pool** — объект схемы, который описывает ограничения, накладываемые на ресурсы (CPU, RAM и т.п.) доступные для выполнения запросов в этом пуле ресурсов . Запрос всегда выполняется в каком-то пуле ресурсов. По умолчанию все запросы выполняются в пуле ресурсов с именем `default`, который не накладывает каких-либо ограничений. Подробнее об использовании пулов ресурсов можно узнать в статье [{#T}](../dev/resource-consumption-management.md).
```

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +# Управление потреблением ресурсов
```suggestion
# Workload Manager - управление потреблением ресурсов
```

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +[Пулы ресурсов](../concepts/glossary.md#resource-pool) позволяют изолировать ресурсы [баз данных](../concepts/glossary.md#database) между потребителями или же настраивать стратегии распределения ресу
В целом норм, но я бы писал про выполнение запросов. Ибо сейчас только выполнение запросов. Иначе читаешь и думаешь слишком абстрактно

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +## Создание пула ресурсов
Мне кажется, что сразу грузилово начинается. Я бы в разделе выше текстом описал пример. Дескать возьмем сценарий, когда с данными в одной бд работают 2 класса потребителей:
1. регулярный роботный процесс, который раз в сутки строит отчет
2. аналитики, которые задают ad hoc запросы

Это добавит человечности статье.

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +[Пулы ресурсов](../concepts/glossary.md#resource-pool) позволяют изолировать ресурсы [баз данных](../concepts/glossary.md#database) между потребителями или же настраивать стратегии распределения ресу
Я бы добавил, что функциональность в превью

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +В примере ниже приведён [классификатор пула ресурсов](../concepts/glossary.md#resource-pool-classifier), который отправляет запросы от всех пользователей в пул ресурсов с именем `olap`:
Здесь первый раз встречается слово "классификатор пула ресурсов" без объяснения что это такое. Надо бы более мягко и с объяснение ввести это понятие

2024-09-24 06:47 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +Допустим, имеются два классификатора пулов ресурсов с конфликтующими условиями, и пользователь `user1@domain` подходит под оба пула ресурсов: `olap1` и `olap2`. Если до этого в системе не существовал
Про RANK неожиданно. А можно пользователю увидеть RANK? Если да, то надо дописать про это в доке

2024-09-24 07:26 UTC, dorooleg commented on ydb/docs/ru/core/concepts/glossary.md
> +**Пул ресурсов** или **resource pool** — объект схемы, который описывает ограничения, накладываемые на потребляемые ресурсы (CPU, RAM, максимальная параллельность выполнения запросов) в этом пуле рес
Поправил

2024-09-24 07:26 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +[Пулы ресурсов](../concepts/glossary.md#resource-pool) позволяют изолировать ресурсы [баз данных](../concepts/glossary.md#database) между потребителями или же настраивать стратегии распределения ресу
поправил

2024-09-24 07:26 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +## Создание пула ресурсов
Добавил человечности :)

2024-09-24 07:26 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +[Пулы ресурсов](../concepts/glossary.md#resource-pool) позволяют изолировать ресурсы [баз данных](../concepts/glossary.md#database) между потребителями или же настраивать стратегии распределения ресу
добавил

2024-09-24 07:27 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +В примере ниже приведён [классификатор пула ресурсов](../concepts/glossary.md#resource-pool-classifier), который отправляет запросы от всех пользователей в пул ресурсов с именем `olap`:
добавил небольшое объяснение

2024-09-24 07:27 UTC, dorooleg commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +Допустим, имеются два классификатора пулов ресурсов с конфликтующими условиями, и пользователь `user1@domain` подходит под оба пула ресурсов: `olap1` и `olap2`. Если до этого в системе не существовал
Добавил информацию, что `RANK` управляемый параметр пользователем

2024-09-24 08:45 UTC, fomichev3000 approved these changes

2024-09-24 08:45 UTC, merged