YDB FQ: Oracle integration tests
ydb-platform/ydb pull request #7671
Opened 2024-08-12 14:47 UTC by lifthelm

### Changelog entry 

adding integration tests on **Python** for **Oracle** external datasource. And updating version of connector

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-13 11:45 UTC, vitalyisaev2 requested changes

2024-08-13 11:45 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/common_test_cases/select_positive_common.py
> +            raise 'Common test cases are not supported for ORACLE bacause of column lack of Int32 column type'
Int64?

2024-08-13 11:45 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/oracle/collection.py
> +            # + select_positive_common.Factory(ss).make_test_cases(EDataSourceKind.ORACLE), # TODO does not work because of cast to uppercase and lack of Int32 column type
Вот это не совсем понятно. Мне казалось, что я видел вносимые изменения в common тестах выше? Получается, они не нужны?

2024-08-13 11:45 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/datasource/oracle/select_datetime_with_service_name.py
> +import datetime
а почему не назвать тест просто `select_datetime.py`? насколько я вижу, он практически совпадает с аналогичными тестами на другие источники. а `service_name` ты и так уже добавил в состав общих структур.

2024-08-13 11:45 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/database.py
> +                # so we'd better make it upper case for test convinience
Стоит почётче перевести фразу, хотя бы с помощью машинного перевода. "does not is not"

2024-08-15 11:33 UTC, lifthelm commented on ydb/library/yql/providers/generic/connector/tests/common_test_cases/select_positive_common.py
> +            raise 'Common test cases are not supported for ORACLE bacause of column lack of Int32 column type'
Поменял текст ошибки, тут говорится о том, что тесты не выполняются из-за отсутствия `Int32` колонок в конвекторе к `Oracle`

2024-08-15 11:35 UTC, lifthelm commented on ydb/library/yql/providers/generic/connector/tests/datasource/oracle/collection.py
> +            # + select_positive_common.Factory(ss).make_test_cases(EDataSourceKind.ORACLE), # TODO does not work because of cast to uppercase and lack of Int32 column type
Изменения в `select_positive_common` и вправду не нужны. Были добавлены для проверки выполнения тестов, но в последствии не убраны

2024-08-15 11:36 UTC, lifthelm commented on ydb/library/yql/providers/generic/connector/tests/datasource/oracle/select_datetime_with_service_name.py
> +import datetime
Изменения в `select_positive_common` были откачены, теперь в данном файле реализуется свой `TestCase` с полем `service_name`

2024-08-15 11:42 UTC, vitalyisaev2 approved these changes

2024-08-15 11:42 UTC, merged