dev: example-app c# query service
ydb-platform/ydb pull request #7717
Opened 2024-08-13 11:03 UTC by KirillKurdyukov

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-14 07:31 UTC, fomichev3000 requested changes

2024-08-14 07:31 UTC, fomichev3000 commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
> +await _queryClient.Exec(@"
почему подчеркивание?
await _queryClient.Exec("...

2024-08-14 07:31 UTC, fomichev3000 commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
> +    DECLARE $id AS Uint64;
А DECLARE еще нужен?

2024-08-14 07:31 UTC, fomichev3000 commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
>  App code snippet for creating a session:
Еще в тексте есть такая конструкция
PRAGMA TablePathPrefix = "/cluster/database";

она же не нужна и не рекомендуется

2024-08-14 08:29 UTC, KirillKurdyukov commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
>  App code snippet for creating a session:
Ага, проглядел!

2024-08-14 09:20 UTC, KirillKurdyukov commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
> +    DECLARE $id AS Uint64;
fix

2024-08-14 09:20 UTC, KirillKurdyukov commented on ydb/docs/en/core/dev/example-app/_includes/example-dotnet.md
> +await _queryClient.Exec(@"
fix

2024-08-15 06:49 UTC, fomichev3000 approved these changes

2024-08-15 06:49 UTC, merged