Support for parquet file with type inferring
ydb-platform/ydb pull request #7734
Opened 2024-08-13 15:29 UTC by evanevanevanevannnn

### Changelog entry 

https://st.yandex-team.ru/YQ-2830

### Changelog category 

* Improvement

2024-08-14 12:58 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +                    return entry;
А как оно раньше работало. Почему на entry заменилось?

2024-08-14 12:58 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +                Y_ABORT("Invalid format should be unreachable");
ABORT плохо в этом месте, можешь ошибку возвращать по аналогии с default? Мы легко и удобно можешь донести эту проблему выше. Еще case нужно вынести выше default

2024-08-14 12:58 UTC, dorooleg commented on ydb/core/external_sources/object_storage/events.h
> +struct TEvArrowSchema : public NActors::TEventLocal<TEvArrowSchema, EvArrowSchema> {
Может назвать это `TEvInferredArrowSchema` по аналогии с `TEvInferredFileSchema`?

2024-08-14 12:58 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +        Cout << "TArrowInferencinator::HandleFileError" << Endl;
Cout лишний. Либо в логи переносить если это нужно

2024-08-14 12:58 UTC, dorooleg commented on ydb/core/external_sources/object_storage/s3_fetcher.cpp
> +                    response.TryRethrow();
А TryRethrow что делает если HasException = false?

2024-08-15 10:08 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage.cpp
> +                    return entry;
раньше мы скачивали первые 10МБ файла -> размер файла нам был не нужен.
теперь для паркета нам нужно скачать последние N -> нужно знать размер файла, тк S3Fetcher принимает на вход (начало, конец) участка памяти 

соотв я добавил в TEvInferFileSchema размер файла

2024-08-15 12:21 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
> +bool IsMetadataSizeRequest(uint64_t from, uint64_t to) {
это же не надежно, давай нормальный флаг докинем что читаем metadata если это нужно

2024-08-15 12:26 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
> +        CreateGuid(&localRequest.RequestId);
А что за функция такая? Нету более гуманной которая не указатель принимает а refrence или возвращает значение

2024-08-15 12:27 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
> +    std::shared_ptr<arrow::io::RandomAccessFile> CleanupParquetFile(const TString& data, const TRequest& request, const NActors::TActorContext& ctx) {
Почему это cleanup parquet file? Может BuilderParquetFileFromMetadata?

2024-08-15 15:05 UTC, dorooleg requested changes

2024-08-15 15:09 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
> +            if (!buildRes.ok()) {
это условие проверяет и builder.Append и builder.Finish, предлагаешь их по-отдельности проверять?

2024-08-15 15:12 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
> +            if (!buildRes.ok()) {
Скорее да, еще бы разные ошибки написать. Чтобы понимать какое конкретно место сломалось, finish или append

2024-08-15 15:25 UTC, dorooleg approved these changes

2024-08-15 21:15 UTC, merged