Changing the RetryQuery return value
ydb-platform/ydb pull request #7777
Opened 2024-08-14 11:35 UTC by stanislav-shchetinin

### Changelog entry 

Changing the RetryQuery return value: TAsyncExecuteQueryResult -> TAsyncStatus

### Changelog category 

* Backward incompatible change

### Additional information

...

2024-08-15 18:19 UTC, Gazizonoki requested changes

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +#include <ydb/public/sdk/cpp/client/impl/ydb_internal/retry/retry_sync.h>
Это публичный хедер, нельзя отсюда делать инклюды на impl

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    using TQueryStatusFunc = std::function<TAsyncStatus(TSession session)>;
```suggestion
    using TQueryFunc = std::function<TAsyncStatus(TSession session)>;
```
Result мы все равно уберем потом, так что просто на старое название поставим версию со статусом

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
>      using TQueryWithoutSessionFunc = std::function<TAsyncExecuteQueryResult(TQueryClient& client)>;
Эта версия нигде не используется вроде, дропни ее

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    using TQueryWithoutSessionStatusFunc = std::function<TAsyncStatus(TQueryClient& client)>;
Также нет смысла выделять, что это StatusFunc

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    TStatus RetryQuery(const TQuerySyncStatusFunc& queryFunc, TRetryOperationSettings settings = TRetryOperationSettings());
Выше везде rvalue ссылки, неконсистентно получается

2024-08-15 18:19 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.cpp
> +using TRetryContextStatusAsync = NRetry::Async::TRetryContext<TQueryClient, TAsyncStatus>;
```suggestion
using TRetryContextAsync = NRetry::Async::TRetryContext<TQueryClient, TAsyncStatus>;
```

Тоже не имеет смысл писать StatusAsync

2024-08-16 09:24 UTC, stanislav-shchetinin commented on ydb/public/sdk/cpp/client/ydb_query/client.h
> +    TStatus RetryQuery(const TQuerySyncStatusFunc& queryFunc, TRetryOperationSettings settings = TRetryOperationSettings());
NRetry::Async::TRetryWithSession в конструкторе принимает лямбду по rvalue ссылке, а NRetry::Sync::TRetryWithSession по lvalue. Я делал по аналогии с table.cpp - там в асинхронные ретраи передается rvalue ссылка, в синхронные - lvalue

2024-08-16 17:47 UTC, Gazizonoki commented on ydb/public/sdk/cpp/client/ydb_query/client.cpp
> +#include <ydb/public/sdk/cpp/client/impl/ydb_internal/retry/retry_sync.h>
Этот инклюд выше есть

2024-08-17 21:39 UTC, stanislav-shchetinin commented on ydb/public/sdk/cpp/client/ydb_query/client.cpp
> +#include <ydb/public/sdk/cpp/client/impl/ydb_internal/retry/retry_sync.h>
Сделал

2024-08-19 16:28 UTC, Gazizonoki approved these changes

2024-08-19 16:29 UTC, merged