YDB FQ: docs for Microsoft SQL Server as an external data source
ydb-platform/ydb pull request #7786
Opened 2024-08-14 13:29 UTC by vitalyisaev2

### Changelog entry 

* YDB FQ: docs for Microsoft SQL Server as an external data source

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-08-15 08:51 UTC, blinkov requested changes, later dismissed

2024-08-15 08:51 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/ms_sql_server.md
> +- `<table_name> - the table name within the external data source.
```suggestion
- `<table_name>` - the table name within the external data source.
```

2024-08-15 08:51 UTC, blinkov commented on ydb/docs/en/core/concepts/federated_query/ms_sql_server.md
> +In the Microsoft SQL Server database, the optionality of column values (whether the column can contain `NULL` values or not) is not a part of the data type system. The `NOT NULL` constraint for any c
```suggestion
In the Microsoft SQL Server database, the optionality of column values (whether the column can contain `NULL` values or not) is not a part of the data type system. The `NOT NULL` constraint for any column of any table is stored within the `IS_NULLABLE` column the [INFORMATION_SCHEMA.COLUMNS](https://learn.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/columns-transact-sql?view=sql-server-ver16) system table, i.e., at the table metadata level. Therefore, all basic Microsoft SQL Server types can contain `NULL` values by default, and in the {{ ydb-full-name }} type system, they should be mapped to [optional](../yql/reference/yql-core/types/optional.md).
```

2024-08-15 08:51 UTC, blinkov commented on ydb/docs/ru/core/concepts/federated_query/ms_sql_server.md
> +В базе данных Microsoft SQL Server признак опциональности значений колонки (разрешено или запрещено колонке содержать значения `NULL`) не является частью системы типов данных. Ограничение (constraint
```suggestion
В базе данных Microsoft SQL Server признак опциональности значений колонки (разрешено или запрещено колонке содержать значения `NULL`) не является частью системы типов данных. Ограничение (constraint) `NOT NULL` для любой колонки любой таблицы хранится в виде значения столбца `IS_NULLABLE` системной таблицы [INFORMATION_SCHEMA.COLUMNS](https://learn.microsoft.com/ru-ru/sql/relational-databases/system-information-schema-views/columns-transact-sql?view=sql-server-ver16), то есть на уровне метаданных таблицы. Следовательно, все базовые типы Microsoft SQL Server по умолчанию могут содержать значения `NULL`, и в системе типов {{ ydb-full-name }} они должны отображаться в [опциональные](../yql/reference/yql-core/types/optional.md) типы.
```

2024-08-20 06:23 UTC, fomichev3000 approved these changes

2024-08-20 06:23 UTC, merged