Add more introspection into PDisk's ChunkWrite and LogWrite
ydb-platform/ydb pull request #7941
Opened 2024-08-16 16:38 UTC by va-kuznecov

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-16 16:41 UTC, SammyVimes requested changes

2024-08-16 16:41 UTC, SammyVimes commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
> +                    //completionAction->FlushAction->OrbitI;
wip leftovers?

2024-08-16 17:29 UTC, va-kuznecov commented on ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
> +                    //completionAction->FlushAction->OrbitI;
yes, fixed

2024-08-20 17:06 UTC, alexvru approved these changes

2024-08-20 17:14 UTC, SammyVimes approved these changes
LGTM

2024-08-20 17:17 UTC, merged