Allow use DECIMAL(22,9) in EXTERNAL TABLE
ydb-platform/ydb pull request #7945
Opened 2024-08-16 17:13 UTC by Hor911

2024-08-16 18:06 UTC, uzhastik commented on ydb/core/tx/schemeshard/schemeshard__operation_common_external_table.cpp
> +                errStr = Sprintf("Type '%s' specified for column '%s' is not supported by storage FF ", col.GetType().data(), colName.data());
Для чего сюда вписал FF?

2024-08-16 18:07 UTC, uzhastik commented
Нужны тесты для новой логики

2024-08-16 19:27 UTC, Hor911 commented on ydb/core/tx/schemeshard/schemeshard__operation_common_external_table.cpp
> +                errStr = Sprintf("Type '%s' specified for column '%s' is not supported by storage FF ", col.GetType().data(), colName.data());
Забыл почистить после отладки

2024-08-29 07:26 UTC, iddqdex requested changes

2024-08-29 07:34 UTC, iddqdex approved these changes

2024-08-29 07:34 UTC, merged