Description of the parameter AUTO_PARTITIONING_PARTITION_SIZE_MB
ydb-platform/ydb pull request #7975
Opened 2024-08-19 06:30 UTC by andrewstalin

### Changelog entry

Added a description of the AUTO_PARTITIONING_PARTITION_SIZE_MB parameter.

### Changelog category

* Documentation (changelog entry is not required)

### Additional information

2024-08-19 07:57 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Система может производить разделение шарда по своему усмотрению. А может не разделять совсем, даже если этот размер указан.
```suggestion
Данное значение является рекомендацией для партиционирования. Возможны ситуации, когда партиционирование не произойдет, даже если явный размер указан. ```

2024-08-19 07:57 UTC, azevaykin commented on ydb/docs/en/core/concepts/datamodel/_includes/table.md
> +The system may split a shard at its discretion. Or it might not split at all, even if the specific size is requested.
```suggestion
This value is a recommendation for partitioning. There may be situations where partitioning will not occur, even if an explicit size is specified. .
```

2024-08-19 08:11 UTC, azevaykin approved these changes, later dismissed

2024-08-29 11:32 UTC, blinkov submitted a review, later dismissed

2024-08-29 11:32 UTC, blinkov commented on ydb/docs/en/core/concepts/datamodel/_includes/table.md
> +This value is a recommendation for partitioning. There may be situations where partitioning will not occur, even if an explicit size is specified.
```suggestion
The desired partition size threshold in megabytes. Recommended values range from `10 MB` to `2000 MB`. If this threshold is exceeded, a shard may split. This setting takes effect when the [`AUTO_PARTITIONING_BY_SIZE`](#auto_partitioning_by_size) mode is enabled.

This value serves as a recommendation for partitioning. Partitioning may sometimes not occur even if the configured size is exceeded.
```

2024-08-29 11:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Данное значение является рекомендацией для партиционирования. Возможны ситуации, когда партиционирование не произойдет, даже если явный размер указан.
```suggestion
Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда включён режим [`AUTO_PARTITIONING_BY_SIZE`](#auto_partitioning_by_size).

Указанное значение служит лишь рекомендацией для разделения. Возможны ситуации, когда разделение не произойдёт, даже если заданный размер превышен.
```

2024-09-12 01:44 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Указанное значение служит лишь рекомендацией для разделения. Возможны ситуации, когда разделение не произойдёт, даже если заданный размер превышен.
```suggestion
Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда включён режим [`AUTO_PARTITIONING_BY_SIZE`](#auto_partitioning_by_size).

Указанное значение служит лишь рекомендацией для разделения. Возможны ситуации, когда разделение не произойдёт, даже если указанный размер превышен.
```

2024-09-12 06:16 UTC, fomichev3000 requested changes

2024-09-12 06:16 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда
Из интересного. Как я понимаю сейчас _безусловно_ партиция будет сплититься при достижении 2GB. Лучше уточнить у snaury

2024-09-12 07:12 UTC, snaury commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда
Я бы сказал, что независимо от настроек пользователя система сейчас делает сплит по размеру в 2GB, и мерж по размеру в 2GB. Причём она работает именно одновременно с пользовательскими настройками, а не как-то ограничивает пользовательские настройки. Например, пользователь может задать размер партиции 100MB и ограничение в 10 партиций, и когда у таблицы станет 10 партиций по 100MB она перестанет сплититься, и партиции начнут расти в размерах. Когда какая-то партиция превысит размер в 2GB она посплитится, и в таблице станет 11 партиций, и т.д. Если кол-во партиций в таблице превышает максимум, то она форсированно мержится по этому же размеру в 2GB, например если у таблицы 15 партиций (на 5 больше максимума) и два соседних шарда стали меньше 1GB в сумме, то они помержатся, несмотря на пользовательский size to split в 100MB (потому что таблица уже вышла за пользовательские настройки и стремится к ним вернуться).

2024-09-16 07:46 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +При малом объеме данных или небольшой нагрузке таблица может состоять из одного шарда. При росте объема данных, обслуживаемых шардом, или нагрузки на шард, {{ ydb-short-name }} автоматически разбивае
```suggestion
При малом объеме данных или небольшой нагрузке таблица может состоять из одного шарда. При росте объема данных, обслуживаемых шардом, или нагрузки на шард, {{ ydb-short-name }} автоматически разделяет его на два. Разделение происходит по медианному значению первичного ключа, если размер шарда превышает порог в размере [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_partition_size_mb). В случае разделения по нагрузке шард сначала собирает сэмпл запрашиваемых ключей (читаемых, записываемых и удаляемых), и на основании этого сэмпла выбирает для разделения такой ключ, чтоб нагрузка распределилась поровну между новыми шардами. Таким образом в случае разделения по нагрузке новые шарды могут иметь существенно отличающийся размер.
```
В остальной части страницы везде "разделение"

2024-09-16 08:00 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда
```suggestion
Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда включён режим [`AUTO_PARTITIONING_BY_SIZE`](#auto_partitioning_by_size).

Внимание: независимо от настроек пользователя {{ ydb-short-name }} производит разделение и объединение по размеру в 2000 MB!

Например, пользователь может задать размер партиции [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_partition_size_mb) = 100 MB и ограничение в [AUTO_PARTITIONING_MAX_PARTITIONS_COUNT](#auto_partitioning_max_partitions_count) = 10 партиций. Когда у таблицы станет 10 партиций по 100 MB, она перестанет разделяться, и партиции начнут расти в размерах. Когда какая-то партиция превысит размер в 2GB она разделится, и в таблице станет 11 партиций, и т.д.
```

2024-09-16 08:00 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Независимо от значений параметра [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_partition_size_mb), система делает разделения и объединения по размеру в 2GB в случае превышения этого значен
```suggestion

```

2024-09-16 08:27 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +- Если объем данных превышает порог в размере [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_partition_size_mb), то разделение происходит по медианному значению первичного ключа.
```suggestion
- Если объем данных превышает [порог по размеру партиции](#auto_partitioning_by_size), то разделение происходит по медианному значению первичного ключа. 
```

2024-09-16 08:27 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +- Если увеличилась нагрузка, то шард сначала собирает сэмпл запрашиваемых ключей (читаемых, записываемых и удаляемых) и на основании этого сэмпла выбирает для разделения такой ключ, чтоб нагрузка рас
```suggestion
- Если [увеличилась нагрузка](#auto_partitioning_by_load), то шард сначала собирает сэмпл запрашиваемых ключей (читаемых, записываемых и удаляемых) и на основании этого сэмпла выбирает для разделения такой ключ, чтоб нагрузка распределилась поровну между новыми шардами. Таким образом в случае разделения по нагрузке новые шарды могут иметь существенно отличающийся размер.
```

2024-09-16 08:31 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Указанное значение служит лишь рекомендацией для разделения. Возможны ситуации, когда разделение не произойдёт, даже если указанный размер превышен.
```suggestion
```

2024-09-16 08:31 UTC, azevaykin commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. Эта настройка применяется, когда
```suggestion
Желаемый порог размера партиции в мегабайтах. Рекомендуемые значения варьируются от `10 MB` до `2000 MB`. Если этот порог превышается, партиция может быть разделена. 
Указанное значение служит лишь рекомендацией для разделения. Возможны ситуации, когда разделение не произойдёт, даже если указанный размер превышен.
Эта настройка применяется, когда включён режим [`AUTO_PARTITIONING_BY_SIZE`](#auto_partitioning_by_size).
```

2024-09-23 04:17 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Независимо от значения параметра [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_by_size) {{ ydb-short-name }} делает разделение и объединение партиций по размеру в 2000 MB. Причем {{ ydb-sh
```suggestion
Независимо от значения параметра [AUTO_PARTITIONING_PARTITION_SIZE_MB](#auto_partitioning_by_size), {{ ydb-short-name }} выполняет разделение и объединение партиций, ориентируясь на размер в 2000 MB. При этом {{ ydb-short-name }} не ограничивает пользовательские настройки, а работает параллельно с ними. Например, если задать [размер партиции](#auto_partitioning_by_size) 100 MB и [ограничение](#auto_partitioning_max_partitions_count) на 10 партиций, то, когда у таблицы станет 10 партиций по 100 MB, она перестанет делиться, и размер партиций начнет увеличиваться. Когда размер какой-либо партиции превысит 2000 MB, она разделится, и в таблице станет 11 партиций. Если размер двух соседних партиций уменьшится до 1000 MB, они объединятся, и в таблице снова станет 10 партиций.
```

2024-09-23 04:17 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Помимо автоматического разделения предоставляется возможность создать пустую таблицу с предопределенным количеством партиций. При этом можно вручную задать точные границы разделения ключей по партици
```suggestion
Помимо автоматического разделения, предоставляется возможность создать пустую таблицу с заданным количеством партиций. При этом можно вручную задать точные границы разделения ключей по партициям или указать равномерное распределение на заданное количество партиций. В последнем случае границы будут созданы по первой компоненте первичного ключа. Равномерное распределение можно указать для таблиц, у которых первая компонента первичного ключа является целым числом с типом данных `Uint64` или `Uint32`.
```

2024-09-23 04:17 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Параметры партиционирования относятся к самой таблице, но не к построенным на ее данных вторичным индексам. Каждый индекс обслуживается своим набором партиций, и решения о разделении или объединении
```suggestion
Параметры партиционирования относятся только к самой таблице, но не к вторичным индексам, построенным на её данных. Каждый индекс обслуживается своим набором партиций, и решения о разделении или объединении его партиций принимаются независимо, на основании настроек по умолчанию. В будущем эти настройки могут стать доступными пользователям, аналогично настройкам основной таблицы.
```

2024-09-23 04:17 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +Характерное время операции разделения или объединения — порядка 500 мс. На это время вовлеченные в операцию данные становятся кратковременно недоступны для чтения и записи. Специализированные методы-
```suggestion
Характерное время операции разделения или объединения составляет около 500 мс. В течение этого времени данные, вовлечённые в операцию, становятся кратковременно недоступны для чтения и записи. Специализированные методы-обёртки в {{ ydb-short-name }} SDK автоматически выполняют повторные попытки при обнаружении, что партиция находится в состоянии разделения или объединения, не поднимая эту информацию до уровня приложения. Важно отметить, что если система по каким-либо причинам перегружена (например, из-за нехватки CPU или пропускной способности выделенных дисковых ресурсов), операции разделения и объединения могут занимать больше времени.
```

2024-09-25 02:59 UTC, blinkov commented on ydb/docs/ru/core/concepts/datamodel/_includes/table.md
> +При малом объеме данных или небольшой нагрузке таблица может состоять из одной партиции. При росте объема данных партиции или нагрузки на партицию, {{ ydb-short-name }} автоматически разделяет её на
```suggestion
При малом объеме данных или небольшой нагрузке таблица может состоять из одной партиции. При росте объема данных партиции или нагрузки на партицию, {{ ydb-short-name }} автоматически разделяет её на две:

```

2024-10-01 08:32 UTC, fomichev3000 approved these changes

2024-10-01 08:32 UTC, merged