airflow
ydb-platform/ydb pull request #8049
Opened 2024-08-20 11:28 UTC by SloNN

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-20 11:41 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +В примере ниже создается задание `create_pet_table`, создающее таблицу в {{ ydb-full-name }}. После успешного создания таблицы вызывается задание `populate_pet_table`, заполняющее таблицу данными с п
нужна запятая после "UPSERT"

2024-08-20 11:41 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +В примере ниже создается задание `create_pet_table`, создающее таблицу в {{ ydb-full-name }}. После успешного создания таблицы вызывается задание `populate_pet_table`, заполняющее таблицу данными с п
>>задание для параметризованного чтения данных с помощью задания

тут два раза слово "задание", хорошо бы переформулировать

2024-08-20 11:41 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +Для установки необходимо выполнить следующие команды:
тут как-то очень мало чего устанавливается. хорошо бы подробнее описать контекст. например, у юзера уже должен стоять airflow? как его поставить? хорошо бы ссылку дать

2024-08-20 11:41 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +* `params` — словарь параметров
я бы явно указал. что речь про шаблонизацию запросов средствами airflow. это не sql параметры запроса

2024-08-20 11:42 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +Для установки необходимо выполнить следующие команды:
ммм. не уверен. мы же рассказываем, как пользоваться твоим драйверов внутри airflow, а не как airflow поставить

2024-08-20 11:42 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +* `params` — словарь параметров
а как это написать?

2024-08-20 14:25 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +Для установки необходимо выполнить следующие команды:
ну это не очевидно. этот контекст как-то донести бы до читателя. или я фразу какую-то пропустил, где на это намекается?:)

2024-08-20 14:27 UTC, uzhastik commented on ydb/docs/ru/core/integrations/airflow.md
> +* `params` — словарь параметров
можно хотя бы ссылку дать о каких параметрах речь: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html

важно, чтобы юзер не подумал, что это sql параметры, в том же airflow с этим путаница

2024-08-30 03:58 UTC, blinkov requested changes

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +# {{ airflow-name }}
Не хватает вводного абзаца условно в духе «у помощью интеграции Airflow и YDB можно делать то-то». А текущий абзац с третьей строки норм бы был следом вторым.

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +{% cut "Пример" %}
Пример в конец и тогда можно без cut.

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +В примере ниже создается задание `create_pet_table`, создающее таблицу в {{ ydb-full-name }}. После успешного создания таблицы вызывается задание `populate_pet_table`, заполняющее таблицу данными с п
Сюда бы картинку с визуализацией этого DAG. Там вроде прямо в интерфейсе была страница, где такое можно заскриншотить.

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +            PRIMARY KEY (pet_id)
```suggestion
                pet_id INT,
                name TEXT NOT NULL,
                pet_type TEXT NOT NULL,
                birth_date TEXT NOT NULL,
                owner TEXT NOT NULL,
                PRIMARY KEY (pet_id)
```

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +        ydb_conn_id="test_ydb_connection"
как-будто не хватает пояснения откуда это соединение берётся

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +pip install apache-airflow-providers-ydb
а почему `ydb` не сделали зависимостью `apache-airflow-providers-ydb`? может предыдущая строка не нужна на самом деле?

если всё же нужна, то в `pip install` можно несколько пакетов за раз указывать

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +Для корректной работы пакета `apache-airflow-providers-ydb` необходимо на всех хостах {{ airflow-name }} выполнить следующие команды:
тут не хватает уточнения про необходимую версию Python, например на втором оно совсем не устанавливается

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +Для работы под управлением [{{ airflow-name }}](https://airflow.apache.org) {{ ydb-full-name }} предоставляет пакет [провайдера](https://airflow.apache.org/docs/apache-airflow-providers) [apache-airf
Последнее предложение со ссылками на доку по этим классам лучше перенести ниже ,в тот раздел, где про них рассказывается.

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +* `ydb_conn_id` — идентификатор подключения с типом `YDB`, содержащий параметры соединения с {{ ydb-full-name }}. Если не указан, то используется соединение с именем `ydb_default`. Соединение `ydb_de
а как это работает? как это дефолтное подключение ydb_default узнает где находится кластер, с которым человек хочет работать?

также нужна ссылка на описание как создавать подключения с типом YDB

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +ydb_operator = YDBExecuteQueryOperator(task_id="ydb_operator", sql="SELECT 'Hello, world!'")
выше написано, что name — обязательный аргумент, но тут он не указан почему-то

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +hook.bulk_upsert("pet", rows=rows, column_types=column_types)
выше описано только два обязательных аргумента, а тут их три

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +* `rows` — массив строк для вставки.
```suggestion
* `rows` — массив словарей для вставки в качестве строк таблицы.
```

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +* `rows` — массив строк для вставки.
иначе можно подумать, что речь про строки в терминах Python

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Bool` | `bool` | True |
```suggestion
| `Bool` | `bool` | `True` |
```

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Float`, `Double` | `double`<br/>NaN и Inf представляются в виде `None` | `7.88731023`<br/>`None` |
в python вроде не было `double`, только `float`

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Decimal` | `Decimal` | `45.23410083` |
```suggestion
| `Decimal` | `decimal.Decimal` | `45.23410083` |
```
если это правда он имеется ввиду — в отличии от соседних типов Decimal надо импортировать

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `String` | `str` <br/> `bytes`  | `Текст строки` |
Нужен комментарий на тему что имеется ввиду под двумя типами со стороны Python.
Видимо, что в сторону Python->YQL поддерживаются оба, но в сторону YQL->Python по идее кто-то один из них должен возвращаться?

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Date`, `Datetime`, `Timestamp` | `datetime` | `2022-02-09` |
```suggestion
| `Date`, `Datetime`, `Timestamp` | `datetime.datetime` | `2022-02-09` |
```
та же история, что и с Decimal выше

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +Ниже приведены правила преобразования YQL-типов в Python-результаты.
Явно написать, что всё что не перечислено — не поддерживается.

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Date`, `Datetime`, `Timestamp` | `datetime` | `2022-02-09` |
а почему `Date` не `datetime.date` соответствует?

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Optional` | Оригинальный тип или None | ```1``` |
зачем тут и ниже тройные кавычки? для inline кода одинарные используются

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Dict<KeyType, ValueType>` | `dict` | ```{key1: value1, key2: value2}``` |
странноватый пример справа — строки ж в кавычках должны быть

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Tuple<Type1, Type2>` | `tuple` | ```(element1, element2, ..)``` |
из-за двух точек в правом столбце получился не совсем пример

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Struct<Name:Utf8,Age:Int32>`| `dict` | `{ "Name": "John", "Age": 128 }` |
выше в левой колонке были плэйсхолдеры типов элементов, а тут почему-то внезапно стали конкретные примеры — сделать консистентно

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Variant<Type1, Type2>` с tuple | `list` | ```list[64563, 1]``` |
Слово list в правой колонке лишнее + нужно подробнее объяснить как оно работает. В частности, Variant может быть из нескольких похожих типов и надо как-то отличать какая из альтернатив была заполнена. Единичка на втором месте в примере — это как раз индекс альтернативы, начинающийся с нуля?

2024-08-30 03:58 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +| `Variant<value:Int32,error:String>` со структурой | `dict` | ```{key1: value1, key2: value2}``` |
Строкой выше было написано tuple по-английски, а тут структура по-русски — сделать консистентно. Плюс та же проблема с типом элементов как у Struct выше, а также с примером как у Dict.

2024-09-03 17:25 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +        ydb_conn_id="test_ydb_connection"
а что про это написать?

2024-09-03 17:27 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +Для корректной работы пакета `apache-airflow-providers-ydb` необходимо на всех хостах {{ airflow-name }} выполнить следующие команды:
вообще это правила airflow, который не ставится на python2
https://pypi.org/project/apache-airflow/

но дописал

2024-09-03 17:29 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +* `ydb_conn_id` — идентификатор подключения с типом `YDB`, содержащий параметры соединения с {{ ydb-full-name }}. Если не указан, то используется соединение с именем `ydb_default`. Соединение `ydb_de
>а как это работает? как это дефолтное подключение ydb_default узнает где находится кластер, с которым человек хочет работать?

никак. оно создается пустым

2024-09-03 17:39 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +* `ydb_conn_id` — идентификатор подключения с типом `YDB`, содержащий параметры соединения с {{ ydb-full-name }}. Если не указан, то используется соединение с именем `ydb_default`. Соединение `ydb_de
>также нужна ссылка на описание как создавать подключения с типом YDB

а что там написать? в поле адрес введите адрес, в поле порт введите порт?

2024-09-03 17:54 UTC, closed without merging

2024-09-04 03:43 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +        ydb_conn_id="test_ydb_connection"
@SloNN я не помню как они там настраиваются, но как-будто прям шаг в инструкции такой должен быть: мол воспользуйтесь такой-то инструкцией airflow, чтобы создать подключение с именем `test_ydb_connection`, или прям самим расписать как это делается.

2024-09-04 03:44 UTC, blinkov commented on ydb/docs/ru/core/integrations/airflow.md
> +* `ydb_conn_id` — идентификатор подключения с типом `YDB`, содержащий параметры соединения с {{ ydb-full-name }}. Если не указан, то используется соединение с именем `ydb_default`. Соединение `ydb_de
> > а как это работает? как это дефолтное подключение ydb_default узнает где находится кластер, с которым человек хочет работать?
> 
> никак. оно создается пустым

а зачем оно тогда?

2024-09-04 07:42 UTC, SloNN commented on ydb/docs/ru/core/integrations/airflow.md
> +* `ydb_conn_id` — идентификатор подключения с типом `YDB`, содержащий параметры соединения с {{ ydb-full-name }}. Если не указан, то используется соединение с именем `ydb_default`. Соединение `ydb_de
@uzhastik ^^