inference json support
ydb-platform/ydb pull request #8102
Opened 2024-08-21 11:24 UTC by evanevanevanevannnn

### Changelog entry 

Type inference json suppoty 

### Changelog category 

* Improvement

2024-08-22 12:20 UTC, dorooleg requested changes

2024-08-22 12:20 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    arrow::json::ParseOptions ParseOpts = arrow::json::ParseOptions::Defaults();
А ConvertOptions нету для json?

2024-08-22 12:20 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    auto fileSize = static_cast<int32_t>(file->GetSize().ValueOr(1 << 20));
Почему в ValueOr 1 << 20?

2024-08-22 12:20 UTC, dorooleg commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +        return TString{TStringBuilder{} << "couldn't parse json file, check format and compression params: " << tableRes.ToString()};
Давай добавим какую-то инфу чтобы 251 и 244 строчки отличались, потом дебажить будет легче проблемы

2024-08-22 12:21 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +    arrow::json::ParseOptions ParseOpts = arrow::json::ParseOptions::Defaults();
нету

2024-08-22 12:46 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
> +        return TString{TStringBuilder{} << "couldn't parse json file, check format and compression params: " << tableRes.ToString()};
done

2024-08-22 12:47 UTC, dorooleg approved these changes, later dismissed

2024-08-23 09:57 UTC, dorooleg approved these changes

2024-08-23 10:20 UTC, merged