[KQP] ANALYZE retries has been added.
ydb-platform/ydb pull request #8115
Opened 2024-08-21 14:13 UTC by pashandor789

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-22 12:53 UTC, spuchin commented on ydb/core/kqp/gateway/actors/analyze_actor.h
> +    TDuration RetryInterval = TDuration::Seconds(2);
Это мы типа начинаем 2 секунд? Это же очень много.
Посмотри на FastRetry в C++ SDK, кажется тут должно быть что-то похожее.

2024-08-23 06:04 UTC, azevaykin commented on ydb/core/kqp/gateway/actors/analyze_actor.cpp
> +void TAnalyzeActor::Handle(TEvPipeCache::TEvDeliveryProblem::TPtr& ev, const TActorContext& ctx) {
Тут пытаемся решить проблему потери одного сообщения.

А нужно другое: 
1. Есть сообщения EvAnalyze, для которых ожидаем ответа EvAnalyzeResponse
2. StatisticsAggregator перезапустился
3. StatisticsAggregator после перезапуска не знает, куда отправлять EvAnalyzeResponse.
4. Нужно повторить все EvAnalyze.
5. StatisticsAggregator теперь знает, куда отправлять EvAnalyzeResponse.

2024-08-23 06:07 UTC, azevaykin requested changes
-

2024-08-23 06:55 UTC, azevaykin approved these changes

2024-08-23 06:55 UTC, merged