Fixed empty records in TSparsedArray constructor
ydb-platform/ydb pull request #8128
Opened 2024-08-21 16:59 UTC by aavdonkin

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-08-21 17:37 UTC, zverevgeny commented
@aavdonkin добавь, пожалуйста, тест, который бы поймал эту багу

2024-08-22 16:21 UTC, ivanmorozov333 commented on .github/config/muted_ya.txt
> +ydb/core/kqp/ut/olap KqpOlapSparsed::SwitchingSparsedTs
через точку

2024-08-22 16:28 UTC, ivanmorozov333 approved these changes, later dismissed

2024-08-22 16:33 UTC, ivanmorozov333 requested changes

2024-08-22 18:03 UTC, ivanmorozov333 commented on ydb/core/kqp/ut/olap/sparsed_ut.cpp
> +    Y_UNIT_TEST(SwitchingSparsedTs) {
я имел в виду, что тест есть такой, в который можно опцию добавить, чтобы лишнего не проверять. он именно на нормализацию отсутствующих колонок

2025-03-26 10:43 UTC, closed without merging