Traslate YDB concepts
ydb-platform/ydb pull request #8172
Opened 2024-08-22 16:00 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-08-23 08:46 UTC, anton-bobkov reviewed
Мелкие стилистические правки

2024-08-23 08:46 UTC, anton-bobkov commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
> +To work with [row](../../concepts/datamodel/table.md#row-oriented-tables) and [column](../../concepts/datamodel/table.md#column-oriented-tables) oriented tables, you need to create at least one datab
To work with [row-oriented](../../concepts/datamodel/table.md#row-oriented-tables) and [column-oriented](../../concepts/datamodel/table.md#column-oriented-tables) tables

2024-08-30 14:06 UTC, Pseudolukian commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
> +1. Create a testing row (`test_row_table`) or column (`test_column_table`) oriented table:
Учёл

2024-08-30 14:07 UTC, Pseudolukian commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
Учёл

2024-08-30 14:16 UTC, Pseudolukian commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
> +To work with [row](../../concepts/datamodel/table.md#row-oriented-tables) and [column](../../concepts/datamodel/table.md#column-oriented-tables) oriented tables, you need to create at least one datab
Учёл

2024-09-17 05:17 UTC, blinkov requested changes

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/how_it_works.md
> +* [Column tables](../../datamodel/table.md#column-tables) are designed for OLAP workloads.
```suggestion
{{ ydb-short-name }} provides users with a well-known abstraction — tables. In {{ ydb-short-name }}, there are two main types of tables:

* [Row-oriented tables](../../datamodel/table.md#row-tables) are designed for OLTP workloads.
* [Column-oriented tables](../../datamodel/table.md#column-tables) are designed for OLAP workloads.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/how_it_works.md
> +Each range of primary keys in a table is processed by a specific [tablet](../../cluster/common_scheme_ydb.md#tablets), called a data shard for row tables and a column shard for column tables.
```suggestion
Logically, from the user's perspective, both types of tables look the same. The main difference between row-oriented tables and column-oriented tables is in how the data is physically stored. In row-oriented tables, the values of all columns in each row are stored together. In contrast, in column-oriented tables, each column is stored separately, meaning cells related to different rows are stored next to each other.

Regardless of type, each table must have a primary key. Column tables can only use `NOT NULL` columns as primary keys. Table data is physically sorted by the primary key. 

Partitioning works differently in row and column tables:

* Row-oriented tables are automatically partitioned by primary key ranges, depending on the data volume.
* Column-oriented tables are partitioned by the hash of the partitioning columns.

Each partition of a table is processed by a specific [tablet](../../glossary.md#tablets), called a [data shard(../../glossary.md#datashard) for row-oriented tables and a [column shard](../../glossary.md#columnshard) for column-oriented tables.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/intro.md
> +{{ ydb-short-name }} supports a relational [data model](../../../concepts/datamodel/table.md) and manages [row oriented](../../datamodel/table.md#row-oriented-tables) and  [column oriented](../../dat
```suggestion
{{ ydb-short-name }} supports a relational [data model](../../../concepts/datamodel/table.md) and manages [row-oriented](../../datamodel/table.md#row-oriented-tables) and  [column-oriented](../../datamodel/table.md#column-oriented-tables) tables with a predefined schema. To make it easier to organize tables, directories can be created like in the file system. In addition to tables, {{ ydb-short-name }} supports [topics](../../topic.md) as an entity for storing unstructured messages and delivering them to multiple subscribers.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/intro.md
> +{{ ydb-short-name }} supports high-performance distributed [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science)) transactions that may affect multiple records of the same type in different ta
```suggestion
{{ ydb-short-name }} supports high-performance distributed [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science)) transactions that may affect multiple records in different tables. It provides the serializable isolation level, which is the strictest transaction isolation. You can also reduce the level of isolation to raise performance.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/scan_query.md
> +For handling OLAP workloads in {{ ydb-short-name }}, there is a specialized type of table — [column](../datamodel/table.md#column-oriented-tables) tables. They store the data of each column separatel
```suggestion
For handling OLAP workloads in {{ ydb-short-name }}, there is a specialized type of table — [column-oriented](../datamodel/table.md#column-oriented-tables) tables. These tables store the data of each column separately from other columns. This allows only the columns directly involved in the query to be read during execution.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/ttl.md
> +{{ ydb-short-name }} lets you specify a TTL column in a [row-oriented](../datamodel/table.md#row-oriented-tables) and [column-oriented](../datamodel/table.md#column-oriented-tables) table. Values in
```suggestion
{{ ydb-short-name }} allows you to specify a TTL column in both [row-oriented](../datamodel/table.md#row-oriented-tables) and [column-oriented](../datamodel/table.md#column-oriented-tables) tables. Values in TTL columns determine the lifetime of table rows.
```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
> +- Creating a row oriented table
```suggestion
- Creating a row-oriented table

```

2024-09-17 05:17 UTC, blinkov commented on ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
> +- Creating a column oriented table
```suggestion
- Creating a column-oriented table

```

2024-09-17 05:17 UTC, blinkov commented
also, "This branch has conflicts that must be resolved"

2024-09-25 04:41 UTC, blinkov submitted a review, later dismissed

2024-09-25 04:41 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/how_it_works.md
> +Regardless of type, each table must have a primary key. Column tables can only use `NOT NULL` columns as primary keys. Table data is physically sorted by the primary key.
```suggestion
Logically, from the user’s perspective, both types of tables look the same. The main difference between row-oriented and column-oriented tables lies in how the data is physically stored. In row-oriented tables, the values of all columns in each row are stored together. In contrast, in column-oriented tables, each column is stored separately, meaning that cells from different rows are stored next to each other within the same column.

Regardless of the type, each table must have a primary key. Column-oriented tables can only have `NOT NULL` columns in primary keys. Table data is physically sorted by the primary key.
```

2024-09-25 04:41 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/how_it_works.md
> +Each partition of a table is processed by a specific [tablet](../../glossary.md#tablets), called a [data shard(../../glossary.md#datashard) for row-oriented tables and a [column shard](../../glossary
```suggestion
Partitioning works differently in row-oriented and column-oriented tables:

* Row-oriented tables are automatically partitioned by primary key ranges, depending on the data volume.
* Column-oriented tables are partitioned by the hash of the partitioning columns.

Each partition of a table is processed by a specific [tablet](../../glossary.md#tablets), called a [data shard](../../glossary.md#datashard) for row-oriented tables and a [column shard](../../glossary.md#columnshard) for column-oriented tables.
```

2024-09-25 04:41 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/intro.md
> +{{ ydb-short-name }} supports a relational [data model](../../../concepts/datamodel/table.md) and manages [row-oriented](../../datamodel/table.md#row-oriented-tables) and  [column-oriented](../../dat
```suggestion
{{ ydb-short-name }} supports a relational [data model](../../../concepts/datamodel/table.md) and manages [row-oriented](../../datamodel/table.md#row-oriented-tables) and [column-oriented](../../datamodel/table.md#column-oriented-tables) tables with a predefined schema. To make it easier to organize tables, directories can be created like in the file system. In addition to tables, {{ ydb-short-name }} supports [topics](../../topic.md) as an entity for storing unstructured messages and delivering them to multiple subscribers.
```

2024-09-25 04:41 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/index/when_use.md
> +* In projects where simultaneous handling of transactional and analytical workloads is required.
```suggestion
* In projects where the simultaneous handling of transactional and analytical workloads is required.
```

2024-09-25 04:41 UTC, blinkov commented on ydb/docs/en/core/concepts/_includes/ttl.md
> +{{ ydb-short-name }} allows you to specify a TTL column in both [row-oriented](../datamodel/table.md#row-oriented-tables) and [column-oriented](../datamodel/table.md#column-oriented-tables) tables. V
```suggestion
{{ ydb-short-name }} allows you to specify a TTL column in both [row-oriented](../datamodel/table.md#row-oriented-tables) and [column-oriented](../datamodel/table.md#column-oriented-tables) tables. Values in TTL columns determine the table rows lifetime.
```

2024-10-01 08:18 UTC, fomichev3000 approved these changes

2024-10-02 01:24 UTC, merged