inference params support
ydb-platform/ydb pull request #8252
Opened 2024-08-26 07:18 UTC by evanevanevanevannnn

### Changelog entry 

support for `partitioned_by`, `file_pattern` and `csv_delimiter` parameters with schema inference

### Changelog category 

* Improvement

2024-08-26 16:02 UTC, dorooleg requested changes

2024-08-27 06:25 UTC, evanevanevanevannnn commented on ydb/core/kqp/provider/read_attributes_utils.cpp
>      void VisitAttribute(TString key, TString value) override {
да, для случая с одной колонкой

2024-08-27 08:23 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage/events.h
> +struct TEvInferPartitions : public NActors::TEventLocal<TEvInferPartitions, EvInferPartitions> {
мы для колонок используем фиксированный формат и конфиг, нам либо нужно их вместе с message-ем пробрасывать, либо сделать отдельный message для инферринга колонок

2024-08-27 08:24 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage.cpp
> +            NJson::TJsonValue values;
что ты имеешь в виду под невалидным partitionedby? повторяющиеся колонки?

2024-08-28 11:48 UTC, dorooleg requested changes

2024-08-28 12:19 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage.cpp
> +        const TString filePattern = meta->Attributes.Value("filepattern", TString{});
сюда приходит ровно то что указывается в запросе

2024-08-30 10:42 UTC, dorooleg requested changes

2024-08-30 10:46 UTC, dorooleg approved these changes

2024-08-30 10:56 UTC, Hor911 approved these changes

2024-08-30 12:26 UTC, merged