Block decimal multiplication kernels
ydb-platform/ydb pull request #8340
Opened 2024-08-27 11:26 UTC by resetius

### Changelog entry 

...

### Changelog category 

* New feature

### Additional information

...

2024-09-09 22:22 UTC, resetius commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +            if (node->IsCallable({"DecimalMul", "And", "Or", "Xor"}) && funcArgs.size() > 2) {
не нужно

2024-09-09 22:22 UTC, resetius commented on ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
> +            node->IsCallable({"DecimalMul", "And", "Or", "Xor", "Not", "Coalesce", "Exists", "If", "Just", "AsStruct", "Member", "Nth", "ToPg", "FromPg", "PgResolvedCall", "PgResolvedOp"}))
добавить Div, Mod

2024-09-10 09:10 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +                return IGraphTransformer::TStatus::Error;
тут нужно сообщение об ошибке

2024-09-10 09:13 UTC, vitstn commented on ydb/library/yql/core/type_ann/type_ann_core.cpp
> +                return IGraphTransformer::TStatus::Error;
вообще GetBlockItemType не может вернуть nullptr, лучше убрать этот if вообще

2024-09-10 09:24 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        if constexpr(std::is_same_v<TRight, NYql::NDecimal::TInt128>) {
в функции оба аргумента int128
NYql::NDecimal::TInt128 left, NYql::NDecimal::TInt128 right

но при этом мы проверяем тип tright. кто гарантирует что там правильно int32 завернут в int128?

2024-09-10 09:28 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        if constexpr (std::is_same_v<TRight, NYql::NDecimal::TInt128>) {
в nul есть оптимизация для Divider=1, ее можно использовать и тут

2024-09-10 09:29 UTC, vitstn commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        return NYql::NDecimal::Mod(left, NYql::NDecimal::Mul(Divider, right));
делает ли Mul оптимизацию для Divider=1? если нет, то лучше сделать тут

2024-09-10 09:29 UTC, vitstn requested changes
!

2024-09-10 09:35 UTC, resetius commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        if constexpr(std::is_same_v<TRight, NYql::NDecimal::TInt128>) {
А неправильно это как? В оригинале делает приведение правого типа к TInt128

2024-09-10 09:48 UTC, resetius commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +                *resPtr = Do(*val1Ptr, *val2Ptr);
Да

2024-09-10 14:53 UTC, resetius commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        if constexpr (std::is_same_v<TRight, NYql::NDecimal::TInt128>) {
В оригинале её нет. Как должно быть для Divider=1? NYql::NDecimal::Div(left, right); ?

2024-09-10 14:54 UTC, resetius commented on ydb/library/yql/minikql/comp_nodes/mkql_block_decimal.cpp
> +        return NYql::NDecimal::Mod(left, NYql::NDecimal::Mul(Divider, right));
Я не знаю. Этот код был скопирован из скалярной версии. Править тогда надо во всех местах.

2024-09-11 17:27 UTC, vitstn approved these changes

2024-09-11 19:24 UTC, merged