Add fq-connector ansible deployment documentation
ydb-platform/ydb pull request #8476
Opened 2024-08-29 13:41 UTC by VadimZud

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-08-29 13:43 UTC, VadimZud commented
https://github.com/ydb-platform/ydb-ansible-examples/pull/13 and https://github.com/ydb-platform/ydb-ansible/pull/39 are needed

2024-09-02 11:31 UTC, vitalyisaev2 requested changes

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +## Развертывание нового {{ ydb-short-name }} кластера с Federated Query коннектором {#new-cluster}
```suggestion
## Развертывание нового кластера {{ ydb-short-name }} с функцией Federated Query и коннектором {#new-cluster}
```

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +Перед прочтением рекомендуется ознакомиться с [{#T}](./initial-deployment.md). Развертывание {{ ydb-short-name }} кластера с Federated Query коннектором похоже на развертывание любого другого {{ ydb-
```suggestion
Перед прочтением рекомендуется ознакомиться с [{#T}](./initial-deployment.md). Развертывание {{ ydb-short-name }} кластера с функцией Federated Query и коннектором fq-connector-go похоже на развертывание любого другого {{ ydb-short-name }} кластера.
```

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +Эта инструкция описывает развертывание [коннектора fq-connector-go](../../deploy/manual/connector.md#fq-connector-go) в [новом](#new-cluster) или [существующем](#existing-cluster) кластере {{ ydb-sho
```suggestion
Эта инструкция описывает развертывание коннектора [fq-connector-go](../../deploy/manual/connector.md#fq-connector-go) в [новом](#new-cluster) или [существующем](#existing-cluster) кластере {{ ydb-short-name }} с помощью [Ansible](https://www.ansible.com)
```

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +7. Выполните команду `ansible-playbook ydb_platform.ydb.initial_setup`, находясь в директории клонированного шаблона.
В Diplodoc нумерованный список состоит только из цифр 1. 1. 1. (...) https://diplodoc.com/docs/ru/syntax/lists

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +Также в кластере будет развернут fq-connector-go, что позволит работать с [поддерживаемыми внешними источниками данных](../../concepts/federated_query/architecture.md#supported-datasources). Инструкц
```suggestion
Также в кластере будет развернут fq-connector-go, что позволит работать с [поддерживаемыми внешними источниками данных](../../concepts/federated_query/architecture.md#supported-datasources). С примерами синтаксиса запросов для подключения к внешнему источнику можно ознакомиться в [инструкции](../../concepts/federated_query/index.md).
```

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +    ```
Плохо, что фрагмент конфига расползся по двум разным файлам - это тяжело поддерживать (если будут правки, мы обязательно забудем про один из файлов).

 Поэтому я предлагаю один из двух вариантов:
* пункты п. 4.1 и п 4.2 заменить ссылкой на соответствующие пункты уже написанной инструкции https://ydb.tech/docs/ru/deploy/manual/deploy-ydb-federated-query#poshagovoe-rukovodstvo.
* фрагменты yaml вынести в include файлы, и заинклюдить их и в старом, и в новом месте.

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +        enable_script_execution_operations: true
отступы поехали

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +Однако [первоначальное развертывание в Ansible](./initial-deployment.md) поддерживает установку нескольких экземпляров динамических нод на одном хосте. При этом, схема хоста выглядит так:
```suggestion
Однако [первоначальное развертывание в Ansible](./initial-deployment.md) поддерживает установку нескольких экземпляров динамических нод на одном хосте. При этом схема хоста выглядит так:
```

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +                use_ssl: false
Стоит оформить как include, так как в точности повторяется фрагмент несколькими строчками выше. Либо  как-то переписать текст, чтобы фрагмент встречался только однажды

2024-09-02 11:31 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/toc_p.yaml
> +- name: Развертывание кластера с коннектором для функции Federated Query
```suggestion
- name: Развёртывание YDB с функцией Federated Query
```

2024-09-03 14:10 UTC, vitalyisaev2 requested changes

2024-09-03 14:10 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +На момент написания этой инструкции, версия {{ ydb-short-name }} 24.3.3 была недоступна для [загрузки в предсобранном виде](../../downloads/index.md#ydb-server). Вы можете прибегнуть к установке {{ y
```suggestion
На момент написания этой инструкции версия {{ ydb-short-name }} 24.3.3 была недоступна для [загрузки в предсобранном виде](../../downloads/index.md#ydb-server). Вы можете прибегнуть к установке {{ ydb-short-name }} из исходного кода. Для этого в разделе `vars` инвентори-файла `files/50-inventory.yaml`:
```

2024-09-03 14:10 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +По умолчанию, плейбуки разворачивают по одному экземпляру fq-connector-go на каждом хосте с динамическими нодами. Благодаря этому, для каждой динамической ноды существует экземпляр коннектора, доступ
```suggestion
По умолчанию плейбуки разворачивают по одному экземпляру fq-connector-go на каждом хосте с динамическими нодами. Благодаря этому, для каждой динамической ноды существует экземпляр коннектора, доступный по адресу `localhost`.
```

2024-09-03 14:10 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +В простейшем случае, {{ ydb-short-name }} кластер с коннектором описывается схемой:
```suggestion
В простейшем случае {{ ydb-short-name }} кластер с коннектором описывается схемой:
```

2024-09-03 14:10 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +1. Внесите дополнительные изменения в разделе `vars` инвентори-файла `files/50-inventory.yaml`:
```suggestion
1. Внесите дополнительные изменения в раздел `vars` инвентори-файла `files/50-inventory.yaml`:
```

2024-09-03 14:10 UTC, vitalyisaev2 commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +1. Отредактируйте конфигурационный файл {{ ydb-short-name }} `files/config.yaml` по аналогии c п.3 и п.4 [инструкциии](../../deploy/manual/deploy-ydb-federated-query.md#guide)
```suggestion
1. Отредактируйте конфигурационный файл {{ ydb-short-name }} `files/config.yaml` в соответствии с [инструкцией](../../deploy/manual/deploy-ydb-federated-query.md#guide)
```

2024-09-13 04:12 UTC, blinkov requested changes

2024-09-13 04:12 UTC, blinkov commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +# Развертывание {{ ydb-short-name }} кластера с коннектором для функции Federated Query с помощью Ansible
Зачем для этого всего отдельная инструкция? Я бы ожидал просто пункт в https://ydb.tech/docs/en/devops/ansible/initial-deployment#inventory-edit со словами «если вам нужна функциональность федеративных запросов, поменяйте настройку `ydb_install_fq_connector` на true». Плюс ещё надо `ydb_fq_connector_version` / `ydb_fq_connector_git_version` сделать по аналогии с основными бинарниками, чтобы не надо было ничего вручную скачивать.

2024-09-17 10:52 UTC, VadimZud commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +# Развертывание {{ ydb-short-name }} кластера с коннектором для функции Federated Query с помощью Ansible
Как минимум, хотелось бы отдельно держать раздел по добавлению коннектора в существующий кластер. Маловероятно, что в поисках этого, пользователь пойдет в "Первоначальное развертывание".
Согласен, что раздел про установку кластера с коннектором с нуля лучше убрать и дополнить инструкцию про первоначальное развертывание.
Раздел про мультислот развертывание также содержит много подробностей, который уместно держать отдельно от первоначального развертывания, потому что там они потеряются, а сама инструкция про первоначальное развертывание будет перегружена.
Доделка про` ydb_fq_connector_version` / `ydb_fq_connector_git_version` у меня запланирована, я принесу её другим реквестом.

2024-09-18 08:29 UTC, VadimZud commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +# Развертывание {{ ydb-short-name }} кластера с коннектором для функции Federated Query с помощью Ansible
Удалил раздел про создание нового кластера с fq-connector-go, добавил вместо них дополнительные пункты в initial-deployment. Добавление коннектора в существующий кластер и подробности про multislot оставил в отдельной статье.

2024-09-27 07:15 UTC, VadimZud commented on ydb/docs/ru/core/devops/ansible/fq-deployment.md
> +# Развертывание {{ ydb-short-name }} кластера с коннектором для функции Federated Query с помощью Ansible
Добавил `ydb_fq_connector_version` / `ydb_fq_connector_git_version`

2025-12-04 10:03 UTC, closed without merging