Add OLAP in YQL tutors, PSQL, quick start
ydb-platform/ydb pull request #8495
Opened 2024-08-29 16:55 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-08-30 06:02 UTC, blinkov requested changes

2024-08-30 12:46 UTC, Pseudolukian commented on ydb/docs/ru/core/quickstart.md
> +Основная цель существования систем управления базами данных - сохранение данных для последующего извлечения. Как система, базирующаяся на SQL, основной абстракцией {{ ydb-short-name }} для хранения д
И примеры создания таблиц и Алерт о том, что сейчас действуют ограничения тоже?

2024-09-02 09:00 UTC, blinkov commented on ydb/docs/ru/core/quickstart.md
> +Основная цель существования систем управления базами данных - сохранение данных для последующего извлечения. Как система, базирующаяся на SQL, основной абстракцией {{ ydb-short-name }} для хранения д
> И примеры создания таблиц и Алерт о том, что сейчас действуют ограничения тоже удалить?

думаю да, если сразу обозначить, что эта статья только про строковые — они же все будут неактуальными?

2024-09-09 07:40 UTC, Pseudolukian commented on ydb/docs/ru/core/quickstart.md
> +Основная цель существования систем управления базами данных - сохранение данных для последующего извлечения. Как система, базирующаяся на SQL, основной абстракцией {{ ydb-short-name }} для хранения д
Убрал

2024-09-17 05:19 UTC, blinkov commented
@Pseudolukian there're a lot of conflicts that need to be resolved

2024-09-24 08:43 UTC, Pseudolukian commented
Rebase: https://github.com/ydb-platform/ydb/pull/9672

2024-09-24 08:44 UTC, closed without merging