YDBDOCS-743-optimizer: Optimizer documentation
ydb-platform/ydb pull request #8522
Opened 2024-08-30 10:07 UTC by pavelvelikhov

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-09-03 02:19 UTC, blinkov requested changes

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Топология «цепочка» — это когда все таблицы соединены друг с другом последовательно и каждая таблица участвует не более, чем в одном соединении. «Клика» — полностью связанный граф, где каждая таблица
Надо структурировать этот рассказ. Начать с того, что когда в запросе несколько операторов JOIN, то среди них возможны такие-то топологии, дать каждой краткое определение. Возможно ещё каких-то вводных слов сказать типа что происходит, если граф соединений странный и не совсем матчится на типовые. Потом сделать три явно выделенных раздела Цепочка, Звезда, Клика, где дать по каждому пример запроса и картинку, как сейчас есть по звезде, досыпать подробностей.

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +YDB использует модифиуацию известного алгоритма DPHyp для перебора порядка соединений.
дать ссылку на research paper, видимо https://15721.courses.cs.cmu.edu/spring2020/papers/20-optimizer2/p539-moerkotte.pdf ?

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +YDB использует модифиуацию известного алгоритма DPHyp для перебора порядка соединений.
а про «известного» не писать, читатель вряд ли даже слышал

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Сравнение сложностей планов основывается на стоимостной функции, которая оценивает ресурсоёмкость каждой операции плана. Самые главные параметры стоимостной функции — это предсказания размера входных
```suggestion
### Оценка стоимости планов

Сравнение сложности планов основано на стоимостной функции, которая оценивает ресурсоёмкость каждой операции плана. Основные параметры стоимостной функции — это прогнозы размера входных данных для каждого оператора и размера его результата. Эти прогнозы выполняются на основе статистики, собранной по таблицам {{ ydb-short-name }}, а также анализа самого плана.
```

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Сравнение сложностей планов основывается на стоимостной функции, которая оценивает ресурсоёмкость каждой операции плана. Самые главные параметры стоимостной функции — это предсказания размера входных
может тут получится хоть какую-нибудь формулу нарисовать или хотя б на исходники сослаться?

дока по тому, как тут писать формулы: https://www.npmjs.com/package/markdown-it-katex

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +* Count-min sketch по каждому атрибуту таблицы
```suggestion
### Статистики для стоимостного оптимизатора

Стоимостной оптимизатор использует статистики как по таблице целиком, так и по отдельным колонкам. 

Текущий набор статистик по таблицам:

* Количество записей таблицы;
* Размер таблицы в байтах.

Текущий набор статистик по колонкам:

* [Count-min sketch](http://dimacs.rutgers.edu/~graham/pubs/papers/cm-full.pdf).
```

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Стоимостный оптимизатор использует как простые базовые статистики, так и более точные по-колоночные статистики. Текущий набор базовых статистик:
Дописать вводные слова о том, как и когда эти статистики собираютсяж дать ссылку на способ подопнуть их обновление, если он уже существует.

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +| 2 | Cтоимостный оптимизатор включается только для запросов, где есть OLAP таблицы |
```suggestion
| 2 | Cтоимостный оптимизатор включается только для запросов, где участвуют [колоночные таблицы](glossary.md#column-oriented-table) |
```

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +| 3 | Cтоимостный оптимизатор включается для всех запросов, но для строчных таблиц предпочитается LookupJoin |
описать возможные стратегии join и сослаться на описание lookupjoin

2024-09-03 02:19 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +| 4 | Cтоимостный оптимизатор включен в полном виде всегда |
```suggestion
| 4 | Cтоимостный оптимизатор полностью включен |
```

2024-09-03 02:22 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +В YDB используются два вида отпимизатора запросов - оптимизатор основанный на правилах и стоимостной оптимизатор. Изначально YDB разрабатывалась для OLTP нагрузок, то есть для выполнения большого пот
Плюс ещё надо определиться «стоимостн**о**й» vs «стоимостн**ы**й» и сделать консистентно. Лично моё ухо меньше режет первый вариант, но ниже как-будто чаще используется второй.

2024-09-03 05:50 UTC, pavelvelikhov commented on ydb/docs/ru/core/concepts/optimizer.md
> +В YDB используются два вида отпимизатора запросов - оптимизатор основанный на правилах и стоимостной оптимизатор. Изначально YDB разрабатывалась для OLTP нагрузок, то есть для выполнения большого пот
Так, ну на самом деле для OLTP оптимизатор тоже нужен, тут уже неверное утверждение. Переформулирую...

2024-09-03 05:51 UTC, pavelvelikhov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Большое количество оптимизаций в YDB очевидно и не требует анализа альтернатив и их стоимости. Создаются отдельные эвристические правила, которые применяются всегда когда есть такая возможность. Напр
Тут тоже уже не совсем правильно - даже решение пушить фильтр вниз по плану может быть стоимостное, мы просто обычно на это закрываем глаза, так как в 99% оно приносит пользу

2024-09-03 05:54 UTC, pavelvelikhov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Сравнение сложностей планов основывается на стоимостной функции, которая оценивает ресурсоёмкость каждой операции плана. Самые главные параметры стоимостной функции — это предсказания размера входных
Формулу лучше не давать а на исходники пока стыдно ссылаться по этому вопросу - у нас абы как сейчас подобраны функции, по-настоящему зафитить не успели

2024-09-04 02:37 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +YDB использует модифиуацию алгоритма [DPHyp](https://www.researchgate.net/publication/47862092_Dynamic_Programming_Strikes_Back) для перебора порядка соединений.
```suggestion
{{ ydb-short-name }} использует модификацию алгоритма [DPHyp](https://www.researchgate.net/publication/47862092_Dynamic_Programming_Strikes_Back) для перебора порядка соединений.
```

2024-09-04 02:39 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +План запроса представляет из себя граф физических операций, такие как чтения данных из источника, фильтрация потока данных по предикату, и более сложные операции: [JOIN](../yql/reference/syntax/join.
```suggestion
План запроса представляет собой граф операций, таких как чтение данных из источника, фильтрация потока данных по предикату, а также более сложные операции, например [JOIN](../yql/reference/syntax/join.md) и [GROUP BY](../yql/reference/syntax/group_by.md). Оптимизаторы в {{ ydb-short-name }} принимают на вход начальный план запроса и преобразуют его в более эффективный план, эквивалентный начальному с точки зрения возвращаемого результата.
```

2024-09-04 06:17 UTC, fomichev3000 requested changes, later dismissed

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/ydb.md
> +| 3 | Cтоимостный оптимизатор включается для всех запросов, но для строчных таблиц предпочитается алгоритм джоина LookupJoin |
```suggestion
| 3 | Cтоимостный оптимизатор включается для всех запросов, но для строковых таблиц предпочитается алгоритм джоина LookupJoin |
```

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/glossary.md
> +### Отпимизатор запросов {#optimizer}
```suggestion
### Оптимизатор запросов {#optimizer}
```

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/optimizer.md
> +В {{ ydb-short-name }} используются два типа оптимизаторов запросов: оптимизатор, основанный на правилах, и стоимостной оптимизатор. Стоимостной оптимизатор применяется для сложных запросов, как прав
Возникает вопрос к фразе. Rule based для аналитических тоже исползуется, я бы не разделял

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/optimizer.md
> +Топология сильно влияет на количество альтернативных планов, которые требуется рассмотреть оптимизатору. Следовательно, стоимостной оптимизатор ограничивает колчество соединений, которые сравниваются
```suggestion
Топология сильно влияет на количество альтернативных планов, которые требуется рассмотреть оптимизатору. Следовательно, стоимостной оптимизатор ограничивает количество соединений, которые сравниваются полным перебором, в зависимости от топологии исходного плана. Возможности точной оптимизации в {{ ydb-short-name }} приведены в следующей таблице:
```

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/optimizer.md
> +{{ ydb-short-name }} использует модификацию алгоритма [DPHyp](https://www.researchgate.net/publication/47862092_Dynamic_Programming_Strikes_Back) для перебора порядка соединений.
А почему YDB использует этот алгоритм? Я бы явно дописал

2024-09-04 06:17 UTC, fomichev3000 commented on ydb/docs/ru/core/concepts/optimizer.md
> +Стоимостной оптимизатор использует статистики как по таблице целиком, так и по отдельным колонкам. {{ ydb-short-name }} собирает и поддерживает статистку в актуальном состоянии в фоновом режиме. Если
"(еще нет в документации)" - я бы не писал такую фразу... зачем?

2024-09-04 06:23 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +В {{ ydb-short-name }} используются два типа оптимизаторов запросов: оптимизатор, основанный на правилах, и стоимостной оптимизатор. Стоимостной оптимизатор применяется для сложных запросов, как прав
```suggestion
В {{ ydb-short-name }} используются два типа оптимизаторов запросов: оптимизатор, основанный на правилах, и стоимостной оптимизатор. Стоимостной оптимизатор применяется для сложных запросов, как правило, аналитических ([OLAP](https://ru.wikipedia.org/wiki/OLAP)), а оптимизация по правилам работает на всех запросах.
```

2024-09-04 06:23 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Стоимостной оптимизатор использует статистики как по таблице целиком, так и по отдельным колонкам. {{ ydb-short-name }} собирает и поддерживает статистку в актуальном состоянии в фоновом режиме. Если
```suggestion
Стоимостной оптимизатор использует статистики как по таблице целиком, так и по отдельным колонкам. {{ ydb-short-name }} собирает и поддерживает статистку в актуальном состоянии в фоновом режиме.
```

2024-09-04 06:27 UTC, pavelvelikhov commented on ydb/docs/ru/core/concepts/optimizer.md
> +Стоимостной оптимизатор использует статистики как по таблице целиком, так и по отдельным колонкам. {{ ydb-short-name }} собирает и поддерживает статистку в актуальном состоянии в фоновом режиме. Если
Это placeholder, мы шипаем ANALYZE и должна документация появиться по этой команде

2024-09-04 11:54 UTC, blinkov requested changes

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/analyze.md
> +ANALYZE <path_to_table> [ ( column_name [, ...]) ]
```suggestion
ANALYZE <path_to_table> [ (<column_name> [, ...]) ]
```

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +### Статистики для стоимостного оптимизатора
```suggestion
### Статистики для стоимостного оптимизатора {#statistics}
```

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/ydb.md
> +### `ydb.CostBasedOptimizationLevel`
```suggestion
### `ydb.CostBasedOptimizationLevel` {#costbasedoptimizationlevel}
```

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +В {{ ydb-short-name }} можно выставить уровень стоимостной оптимизации через прагму [CostBasedOptimizationLevel](../yql/reference/syntax/pragma.md#ydb.CostBasedOptimizationLevel)
```suggestion
В {{ ydb-short-name }} можно выставить уровень стоимостной оптимизации через прагму [CostBasedOptimizationLevel](../yql/reference/syntax/pragma.md#costbasedoptimizationlevel)
```

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/analyze.md
> +  * `column_name` - форсировать сбор статистики только по определенным колонкам таблицы
```suggestion
В результате выполнения команды будет собрана и актуализирована статистика по указанным таблицам в целом, а также по всем или указанным колонкам.

* `path_to_scheme_object` — путь к объекту схемы
* `path_to_table` — путь к конкретной таблице, для которой требуется форсированный сбор статистики
* `column_name` — форсировать сбор статистики только по определённым колонкам таблицы
```

2024-09-04 11:54 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/analyze.md
> +* [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch).
```suggestion
Текущий набор статистик указан в разделе [{#T}](../../../concepts/optimizer.md#statistics).
```

2024-09-05 02:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +{{ ydb-short-name }} использует модификацию алгоритма [DPHyp](https://www.researchgate.net/publication/47862092_Dynamic_Programming_Strikes_Back) для перебора порядка соединений. Это - самый современ
```suggestion
{{ ydb-short-name }} использует модификацию алгоритма [DPHyp](https://www.researchgate.net/publication/47862092_Dynamic_Programming_Strikes_Back) для перебора порядка соединений. Это самый современный алгоритм динамического программирования для оптимизации запросов. Посредством построения гиперграфов запросов он избегает перебора лишних альтернатив и позволяет оптимизировать планы с операторами `JOIN`, сложными предикатами, а также с операторами `GROUP BY` и `ORDER BY`.
```

2024-09-05 02:09 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/toc_i.yaml
> +- { name: ANALYZE,                      href: analyze.md }
```suggestion
- { name: ANALYZE,                      href: analyze.md, when: backend_name == "YDB" }
```

2024-09-05 02:10 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/analyze.md
> +Текущий набор статистик указан в разделе [{#T}](../../concepts/optimizer.md#statistics).
```suggestion
Текущий набор статистик указан в разделе [{#T}](../../../concepts/optimizer.md#statistics).
```

2024-09-05 02:11 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +* Модуль статистики, на которую опирается оценка стоимости
```suggestion
Стоимостной оптимизатор состоит из трех основных компонент:

* Модуль перебора порядка соединений;
* Модуль оценки стоимости плана;
* Модуль статистики, на которую опирается оценка стоимости.
```

2024-09-05 02:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/ydb.md
> +| 2 | Cтоимостный оптимизатор включается только для запросов, где участвуют [колоночные таблицы](../../../../concepts/glossary.md#column-oriented-table) |
```suggestion
| 2 | Cтоимостный оптимизатор включается только для запросов, где участвуют [колоночные таблицы](../../../../../concepts/glossary.md#column-oriented-table) |
```

2024-09-05 02:20 UTC, blinkov commented on ydb/docs/ru/core/concepts/optimizer.md
> +* [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch).
```suggestion
Текущий набор статистик по таблицам:
* Количество записей таблицы;
* Размер таблицы в байтах.

Текущий набор статистик по колонкам:

* [Count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch).
```

2024-09-05 03:47 UTC, blinkov approved these changes

2024-09-05 03:47 UTC, merged