Docs: resource broker config
ydb-platform/ydb pull request #8694
Opened 2024-09-03 16:16 UTC by CyberROFL

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-09-04 12:28 UTC, fomichev3000 requested changes

2024-09-04 12:28 UTC, fomichev3000 commented on ydb/docs/ru/core/deploy/configuration/config.md
> +Разные виды активностей (фоновые операции, удаление данных по [TTL](../../concepts/ttl.md) и т.д.) запускаются в разных *очередях* брокера ресурсов. Каждая такая очередь имеет лимитированное число ре
Совсем не понятно. Это cpu на одну ноду? Правда 10 cpu?

2024-09-04 12:32 UTC, CyberROFL commented on ydb/docs/ru/core/deploy/configuration/config.md
> +Разные виды активностей (фоновые операции, удаление данных по [TTL](../../concepts/ttl.md) и т.д.) запускаются в разных *очередях* брокера ресурсов. Каждая такая очередь имеет лимитированное число ре
> Это cpu на одну ноду?

Да, в первом предложении:
> контролирующий потребление ресурсов узла YDB

> Правда 10 cpu?

Если вопрос про `queue_build_index`, то значение взято из кода: https://github.com/ydb-platform/ydb/blob/ba7abc4f5a15b40410e277357592dcf6ce19d7b0/ydb/core/tablet/resource_broker.cpp#L1411.

2024-09-04 12:56 UTC, fomichev3000 approved these changes

2024-09-04 12:56 UTC, merged

2024-09-05 06:41 UTC, kunga commented on ydb/docs/ru/core/deploy/configuration/config.md
> +## resource_broker_config — брокер ресурсов {#resource-broker-config}
Должен быть в глоссарии

2024-09-05 06:41 UTC, kunga commented on ydb/docs/ru/core/concepts/_includes/secondary_indexes.md
> +Скорость записи данных выбрана таким образом, чтобы минимизировать влияние процесса записи на пользовательские транзакции. Для управления скоростью настройте лимиты для соответствующей очереди [броке
Должна быть ссылка на глоссарий

2024-09-05 06:41 UTC, kunga commented on ydb/docs/ru/core/deploy/configuration/config.md
> +Название очереди | CPU | Memory | Описание
Давай не писать про настройку памяти через брокер, она сетапится через Контроллер памяти теперь

2024-09-05 06:41 UTC, kunga commented on ydb/docs/ru/core/deploy/configuration/config.md
> +Разные виды активностей (фоновые операции, удаление данных по [TTL](../../concepts/ttl.md) и т.д.) запускаются в разных *очередях* брокера ресурсов. Каждая такая очередь имеет лимитированное число ре
Ничего не написано про какой total cpu в ресурс брокере, от чего он зависит и как настраивается

И как потом разные очереди берут из него ресурс

2024-09-05 06:41 UTC, kunga commented on ydb/docs/ru/core/devops/manual/backup-and-recovery.md
> +Скорость операций резервного копирования и восстановления в/из S3-совместимого хранилища подобрана таким образом, чтобы минимизировать влияние на пользовательскую нагрузку. Для управления скоростью о
Должна быть ссылка на глоссарий

2024-09-05 09:19 UTC, CyberROFL commented on ydb/docs/ru/core/concepts/_includes/secondary_indexes.md
> +Скорость записи данных выбрана таким образом, чтобы минимизировать влияние процесса записи на пользовательские транзакции. Для управления скоростью настройте лимиты для соответствующей очереди [броке
Отсюда сразу ссылка на то, как настраивать. Не нужно заставлять переходить сначала в глоссарий, а потом на статью по настройке.

2024-09-05 09:19 UTC, CyberROFL commented on ydb/docs/ru/core/devops/manual/backup-and-recovery.md
> +Скорость операций резервного копирования и восстановления в/из S3-совместимого хранилища подобрана таким образом, чтобы минимизировать влияние на пользовательскую нагрузку. Для управления скоростью о
Ответил выше.

2024-09-05 09:22 UTC, kunga commented on ydb/docs/ru/core/concepts/_includes/secondary_indexes.md
> +Скорость записи данных выбрана таким образом, чтобы минимизировать влияние процесса записи на пользовательские транзакции. Для управления скоростью настройте лимиты для соответствующей очереди [броке
Можно так:

Для управления скоростью [настройте лимиты](ссылка на конфиг) для соответствующей очереди [брокера ресурсов](ссылка на глоссарий).

2024-09-13 15:01 UTC, CyberROFL commented
https://github.com/ydb-platform/ydb/issues/9215