YQ-3151 added issues for timeout and cancelled
ydb-platform/ydb pull request #8718
Opened 2024-09-04 09:46 UTC by GrigoriyPA

- **Intermediate changes**
- **Remove remaining calls of Container() (fixup rXXXXXX) b2b7d42af6f055ef24e22f69cac6c0f5560f6120**
- **Fix TSAN warning e2f99a0432865120bc478a3fb91956424c374445**
- **Intermediate changes**
- **YT-15939: Chaos replication collocation options e84a94c1998096fe46ef543149e962be083af035**
- **Intermediate changes**
- **Simplify Modules/_sqlite 0fe364013bff008d9bce51cfd54d2810ba54b2a4**
- **YT-21939: Add job resource demand restrictions in tree d30c1f255907581d5b7a9c28ea078c472c56925a**
- **Intermediate changes**
- **Introduce NPhoenix2::_ placeholder type and slightly change the way type arguments are passed to PHOENIX_DEFINE_TEMPLATE_TYPE 9fcd3cb2d6495fa8d8a88b6296d7ef5a33756a52**
- **Cosmetics a9c0dc91b0925dae3bdcefe3c90701148bbdfa9d**
- **YT-21993: Fix static initialization order dependency f9cdbaa70ea7850d25cb28f37597a6b92a1749f6**
- **Cosmetics 6c9a86064c486624465aadb27dd093a72c3ab176**
- **Minor codestyle fixes**
- **New version of the tld SKIP_CHECK SKIP_REVIEW d09193f6d3a62d7b7603c955985d21aae4f7c3e9**
- **Automatic release build for ymake, os_ymake**
- **Set ram drive path in junit scripts**
- **Intermediate changes**
- **Cosmetics 420b182adaa93bc45703bef8d014f1c37391d7da**
- **Upload new jdk-11.0.24+8**
- **Intermediate changes**
- **YT-20462: Introduce TPolymorphicYsonStruct for serialization of polymorphic types 19597a5cbe777b391118536405f7900b779a29c5**
- **Intermediate changes**
- **YT-21709: Introduce IRowBatchReader and IRowBatchWriter in client**
- **Intermediate changes**
- **Update to ErrorProne 2.30.0 cd43ee5c01a1a2452f810d5123c821593501c896**
- **KIKIMR-21908: fix a bug in CPUID/AVX512F call f5e4678c0171915199008af5bb54f47adf0b34d4**
- **Update contrib/libs/cxxsupp/libcxxrt to 2024-08-06 16b02fd8b0ca24af24e8434896fcd078a76d6382**
- **Intermediate changes**
- **feat(conf/ts): set cpu:4 for build nodes but only in autocheck 0f515a62218aa2733c6fa8e3ab4685f0ac96b3e8**
- **Make a script extension OS-dependent e068690950bd30eb1b53ddf8f1e347ff7633f15b**
- **Consider SequoiaMapNode, PortalExit and Scion to be composite node types**
- **Fix issues in rXXXXXX**
- **YT-22672: Fix possible infinite growth of ReplyBus terminate list e56246b87c8b86353a3e08aba21ffa81f2e26817**
- **YT-22603 Improve error message when all replicas are banned 9da49d54d0eb5009874c090d094aac3117ca77b7**
- **Better comment aa8b4c15efdb99c12a4ce5815d0d4f2d70620cb4**
- **Intermediate changes**
- **special ymake release with triple o 3e8f0cae0d8f64fefe745a3b5ec69bcb02e3e9ae**
- **Intermediate changes**
- **mock getpid func 171c556f349e96400867de4937fe0c703849c0c8**
- **Upload new jdk-17.0.12+7**
- **[contrib] unbound mbedtls from openthread**
- **fix segfault in autocomplete handler when redirecting to a database (#8367)**
- **refactor whiteboard info (#8366)**
- **grace_join: redesign to improve LEFT JOIN with short left side (#8146)**
- **Update contrib/libs/c-ares to 1.33.1 989fe7a8375f82c54730928e4590985850c9a72a**
- **YT-22350: Fix and enrich scheduler heartbeat tracing 3befd723187944049c57b374fddcaa76e6f56d7e**
- **[build/plugins]Resolve test srcs fb91f7e8141f1f451bc96d8f60b15867a1c22743**
- **Set YA_TEST_JAVA_TMP_DIR on tag presence**
- **Fix legacy naming: registry -> profiler 4a4f5c7faabad00d120216154e61771eee58dcec**
- **[yt provider] Properly clear constraints in YqlRowSpec (#8350)**
- **ci: add workflow for create github actions runner vm image (#8371)**
- **Intermediate changes**
- **Upload new jdk-21.0.4+7**
- **Get rid of copy-pase of TChangeRecordContainer (#8352)**
- **ydb_topic: schedule SendImpl from OnCompressedImpl instead of calling it directly (#8372)**
- **Randomize order of sessions (#8359)**
- **Randomize semaphore name for tests (#8385)**
- **SQL lang functions in postgis (#8374)**
- **LOGBROKER 8891 add 4 json sqs requests (#8328)**
- **Clearer comments (#8229)**
- **Handle Unordered in Dq (#8357)**
- **sql lang functions [docs] (#8378)**
- **YQ WM fixed cleanup table retries (#8369)**
- **retry requests to statistics table (#8358)**
- **Statistics service metrics (#8322)**
- **Added another cost based optimization level (#8348)**
- **Use cpu limits from resource pool scheme objects (#8370)**
- **Fix test & Sink (#8386)**
- **Disable level triggered compaction in donor VDisks (#8376)**
- **Update github.com/ydb-platform/fq-connector-go to 0.5.6-rc.3 (#8387)**
- **Intermediate changes**
- **LOGBROKER 8891 list dead letter source queues (#8330)**
- **[KQP] Analyze OLAP supported, OLTP unsupported. (#8395)**
- **Add device type in dsproxy put lwprobe (#8381)**
- **Basic example for Query Service (cpp) (#7810)**
- **Enable CMS request priorities by default (#8380)**
- **[LDAP] Add flag to disable search nested groups (#8354)**
- **speed up merging for sparsed columns (#8365)**
- **s3 dqrun has been fixed (#8408)**
- **fix host as default field for sysinfo (#8403)**
- **Remove cmake from nightly (#8416)**
- **Move stability test into manual (because it is a cluster test) (#8419)**
- **Implement security tags passthrough in DQ (#8308)**
- **TEvRecords helpers, little style guide changes (#8421)**
- **Statistics: several analyzes inflight (#8394)**
- **Statistics: status for TEvAnalyzeResponse (#8404)**
- **Automatic release build for ymake, os_ymake**
- **Translate YQL CREATE (#7938)**
- **Edited deploy-ydb-federated-query.md (#8248)**
- **YDBDOCS-803: add ya.make targets for various versions of YQL docs (#8361)**
- **Conan2 fixes in templates**
- **Incarnation fix 2d84c10e22997fd1994648396e108472f378d38f**
- **Intermediate changes**
- **tests/fq: add streamlookup (#7568)**
- **Allow use DECIMAL(22,9) in EXTERNAL TABLE (#7945)**
- **Statistics: reboot columnshard test (#8278)**
- **Upload new jdk-22.0.2+9**
- **Added MaxCommonLogChunks icb parameter (#8001)**
- **Locks for Scan Actor (#8379)**
- **executer & planner changes to potentially improve placing (#8409)**
- **[docs] fix ru text in en article (#8439)**
- **move wardens test to oss (#8130)**
- **change a little how feature flags are returned (#8434)**
- **Put flatc64 into contrib/libs/flatbuffers64/flatc**
- **Test for RW olap tx (#8423)**
- **signals about long_tx writing (#8407)**
- **Move blobstorageproxies actor services to different monitoring shard (#8424)**
- **Sink locks tests + some locks fixes (#8420)**
- **Delete deprecated code (ReadRules,..) (#8405)**
- **Introduce TBlockJoinState (#8368)**
- **Add TotalNodeCpuUsage to local's metrics (#8390)**
- **Support Decimal128/Decimal256 in Arrow parser**
- **Reset traversal for tables with TraversalStarted status (#8441)**
- **Add memory limit to prevent converter to AST get OOM (#8351)**
- **YT-22593: Switch to std::string for user names and co 68d8a9981ffcfca685908dd4e25c3d2171efe6a5**
- **YT-21906: Snapshots accounting in network throttlers 3ddfbca421ccbd9a1c8480a22ccb9019833c4f62**
- **Implement a new tablet administration grpc service (#8400)**
- **Rework filters pushdown with multiusage (#8360)**
- **storage health check fixes (#8291)**
- **Update conan_provider.cmake to latest version**
- **Prepare cpp-protobuf migration (#8443)**
- **Statistics: disable datashard traversal (#8402)**
- **fix segfault in tenantinfo handler (#8449)**
- **logging(ydb): add data integrity logs to grpc and session actor (#6049)**
- **YQ WM improved overload issues (#8437)**
- **fix CORS headers for traces (#8458)**
- **add plan.svg to benchmark report (#8464)**
- **ci: add unified-agent into github runner VM (#8474)**
- **Async replication docs (#7110)**
- **Fix table stats aggregation for OLAP tables (#8417)**
- **Statistics: updated HTML page (#8471)**
- **Apply the last stats received from terminated CAs (#8356)**
- **Fix logger being improperly initialized on windows abi**
- **YT-22593: Switch to std::string in ACLs 377b634e83ecc7bc6ad418afd6c4db77cb7c3a0a**
- **result_format: type parser & builder (#8469)**
- **Properly optimize unordered YtOutput over YtDqProcessWrite (#8411)**
- **support launching tasks in the same dc  [...]

2024-09-04 12:09 UTC, dorooleg requested changes

2024-09-04 12:09 UTC, dorooleg commented on ydb/core/kqp/executer_actor/kqp_executer_impl.h
> +            NYql::IssueToMessage(issue, ResponseEv->Record.MutableResponse()->AddIssues());
[IssuesToMessage](https://a.yandex-team.ru/arcadia/contrib/ydb/library/yql/public/issue/yql_issue_message.h?rev=r14785458#L32)

2024-09-04 12:34 UTC, dorooleg submitted a review, later dismissed

2024-09-05 09:04 UTC, vitstn approved these changes

2024-09-05 10:06 UTC, gridnevvvit approved these changes

2024-09-05 11:16 UTC, merged