Inference projections support
ydb-platform/ydb pull request #8744
Opened 2024-09-04 14:04 UTC by evanevanevanevannnn

### Changelog entry 

Inference projections support

### Changelog category 

* Improvement

2024-09-05 12:16 UTC, dorooleg requested changes

2024-09-05 12:16 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +        bool ignoreEmptyListings = !!projection;
Предлагаю явно написать проверку. `!projection.empty()`

2024-09-05 12:16 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +                        throw yexception() << "invalid partitioned_by parameter, column " << value.GetString() << "mentioned twice";
А точно это не валидный случай? В теории мы могли бы такое хендлить

2024-09-05 12:16 UTC, dorooleg commented on ydb/core/external_sources/object_storage.cpp
> +            pathGenerator = NYql::NPathGenerator::CreatePathGenerator(projection, partitionedBy);
А этот кусок случайно не совпадает с чтением из s3? Тут можно задедупить код?

2024-09-05 12:49 UTC, evanevanevanevannnn commented on ydb/core/external_sources/object_storage.cpp
> +                        throw yexception() << "invalid partitioned_by parameter, column " << value.GetString() << "mentioned twice";
в yql_s3_io_discovery выдается ошибка в таком случае, так будет консистентно

2024-09-06 15:24 UTC, dorooleg approved these changes

2024-09-06 17:43 UTC, merged