Added an article on using YDB with Apache Superset
ydb-platform/ydb pull request #8801
Opened 2024-09-05 12:24 UTC by anton-bobkov

### Changelog category

* Documentation (changelog entry is not required)

### Additional information

Added an article on using YDB with Apache Superset

2024-09-05 13:09 UTC, blinkov requested changes

2024-09-05 13:09 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +   ![](_assets/superset-ydb-connection-details.png =400x)
```suggestion
   * **HOST**. The [endpoint](https://ydb.tech/docs/en/concepts/connect#endpoint) of the {{ ydb-short-name }} cluster to which the connection will be made.

   * **PORT**. The port of the {{ ydb-short-name }} endpoint.

   * **DATABASE NAME**: The path to the [database](../../concepts/glossary.md#database) in the {{ ydb-short-name }} cluster where queries will be executed.

   * **USERNAME**. The login for connecting to the {{ ydb-short-name }} database.

   * **PASSWORD**. The password for connecting to the {{ ydb-short-name }} database.

   * **DISPLAY NAME**. The { ydb-short-name }} connection name in Apache Superset.

   ![](_assets/superset-ydb-connection-details.png =400x)
```

2024-09-05 13:09 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +   {% endnote %}
```suggestion
## Creating a dataset {#create-dataset}

To create a dataset for a {{ ydb-short-name }} table, follow these steps:

1. In the Apache Superset toolbar, hover over **Settings** and select **SQL query**.

2. In the **DATABASE** drop-down list, select the {{ ydb-short-name }} database connection.

3. In the **SCHEMA** drop-down list, select `public`.

   {% note alert %}

  {{ ydb-short-name }} currently does not provide table schema information via the PostgreSQL protocol. You can skip selecting a table in the **SEE TABLE SCHEMA** drop-down list.

   {% endnote %}
```

2024-09-05 13:09 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +   {% endnote %}
The suggestion is not rendering correctly, here's what I meant:
![Screenshot 2024-09-05 at 20 06 39](https://github.com/user-attachments/assets/fac20d1a-6aab-4254-9c5c-3fc20897389a)

```suggestion
4. Enter the SQL query in the right section of the page. For example, `SELECT * FROM <ydb_table_name>`.

   {% note tip %}

   To create a dataset for a table located in a subdirectory of a {{ ydb-short-name }} database, specify the table path in the table name. For example:
   
   ```yql
   SELECT * FROM `<path/to/subdirectory/table_name>`;
   ```

   {% endnote %}
```

2024-09-05 13:09 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +After you create datasets, you can use data from {{ ydb-short-name }} to create charts in Apache Superset. For more information, see the [Apache Superset](https://superset.apache.org/docs/intro/) doc
```suggestion
1. Click **RUN** to test the SQL query.

   ![](_assets/superset-sql-query.png)

1. Click the down arrow next to the **SAVE** button, then click **Save dataset**.

   The **Save or Overwrite Dataset** dialog box appears.

1. In the **Save or Overwrite Dataset** dialog box, select **Save as new**, enter the dataset name, and click **SAVE & EXPLORE**.

After creating datasets, you can use data from {{ ydb-short-name }} to create charts in Apache Superset. For more information, refer to the [Apache Superset](https://superset.apache.org/docs/intro/) documentation.
```

2024-09-05 13:24 UTC, blinkov requested changes, later dismissed

2024-09-05 13:24 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Поддержка [сетевого протокола PostgreSQL](https://ydb.tech/docs/ru/postgresql/intro) в {{ ydb-short-name }} позволяет использовать [Apache Superset](https://superset.apache.org/) для запросов и визуа
```suggestion
# Apache Superset

Apache Superset — это современная платформа для анализа и визуализации данных.

Поддержка [сетевого протокола PostgreSQL](../../postgresql/intro.md) в {{ ydb-short-name }} позволяет использовать [Apache Superset](https://superset.apache.org/) для выполнения запросов и визуализации данных из {{ ydb-short-name }}.
```

2024-09-05 13:24 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +1. На втором шаге мастера, введите данные о подключении к {{ ydb-short-name }} в следующие поля:
```suggestion
## Создание подключения к {{ ydb-short-name }} {#add-database-connection}

Чтобы создать подключение к {{ ydb-short-name }} из Apache Superset с использованием сетевого протокола PostgreSQL, выполните следующие шаги:

1. В верхнем меню Apache Superset наведите курсор на **Settings** и выберите в выпадающем списке пункт **Database Connections**.

1. Нажмите кнопку **+ DATABASE**. 

   Откроется окно мастера **Connect a database**.

1. На первом шаге мастера нажмите кнопку **PostgreSQL**.

1. На втором шаге мастера введите данные для подключения к {{ ydb-short-name }} в следующие поля:
```

2024-09-05 13:24 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +   * **DISPLAY NAME**. Наименование соединения с {{ ydb-short-name }} в Apache Superset.
```suggestion
* **HOST** — [эндпоинт](../../concepts/connect.md#endpoint) кластера {{ ydb-short-name }}, к которому осуществляется подключение.
* **PORT** — порт эндпоинта {{ ydb-short-name }}.
* **DATABASE NAME** — путь к [базе данных](../../concepts/glossary.md#database) в кластере {{ ydb-short-name }}, к которой будут выполняться запросы.
* **USERNAME** — логин для подключения к базе данных {{ ydb-short-name }}.
* **PASSWORD** — пароль для подключения к базе данных {{ ydb-short-name }}.
* **DISPLAY NAME** — наименование соединения с {{ ydb-short-name }} в Apache Superset.
```

2024-09-05 13:24 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +   {% endnote %}
```suggestion
## Создание набора данных (dataset) {#create-dataset}

Чтобы создать набор данных из таблицы {{ ydb-short-name }}, выполните следующие шаги:

1. В верхнем меню Apache Superset наведите курсор на **Settings** и выберите в выпадающем списке пункт **SQL query**.

1. В выпадающем списке **DATABASE** выберите подключение к {{ ydb-short-name }}.

1. В выпадающем меню **SCHEMA** выберите `public`.

   {% note alert %}

   В настоящее время {{ ydb-short-name }} не предоставляет схемы таблиц через сетевой протокол PostgreSQL. Поэтому выбор таблицы в выпадающем списке **SEE TABLE SCHEMA** можно пропустить.

   {% endnote %}
```

2024-09-05 13:50 UTC, SloNN commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +  Следуйте [документации Apache Superset](https://superset.apache.org/docs/configuration/databases#installing-database-drivers), чтобы установить драйвер для PostgreSQL.
он входит в поставку по умолчанию. плюс я попытался поискать тут инструкцию про PG и не нашел

2024-09-05 13:51 UTC, SloNN commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +    Откроется окно мастера **Connect a database**.
вроде у нас принято каждый шаг фотографировать. По крайней мере Ваня Катков так делает

2024-09-05 13:53 UTC, SloNN commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +   Если вы хотите создать набор данных из таблицы, которая расположена в поддиректории {{ ydb-short-name }}, необходимо указать путь к таблице в самом наименовании таблицы. Например, `SELECT * FROM '
тут вроде двойные кавычки...

2024-09-05 13:53 UTC, SloNN commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +После создания наборов данных вы можете использовать данные из {{ ydb-short-name }} для создания диаграмм в Apache Superset. См. документацию [Apache Superset](https://superset.apache.org/docs/intro/
я бы еще добавил инструкцию про визуализацию данных. хотя бы и самую простую

2024-09-12 13:19 UTC, blinkov commented on ydb/docs/en/core/integrations/visualization/superset.md
> +PostgreSQL compatibility mode in {{ ydb-short-name }} enables the use of [Apache Superset](https://superset.apache.org/) to query and visualize data from {{ ydb-short-name }}. In this case Apache Sup
```suggestion
[PostgreSQL compatibility mode in {{ ydb-short-name }}](../../postgresql/intro.md) enables the use of [Apache Superset](https://superset.apache.org/) to query and visualize data from {{ ydb-short-name }}. In this case Apache Superset works with {{ ydb-short-name }} just like with PostgreSQL.
```

2024-09-12 13:19 UTC, blinkov commented on ydb/docs/ru/core/integrations/visualization/superset.md
> +Режим совместимости с PostgreSQL в {{ ydb-short-name }} позволяет использовать [Apache Superset](https://superset.apache.org/) для выполнения запросов и визуализации данных из {{ ydb-short-name }}. В
```suggestion
[Режим совместимости с PostgreSQL в {{ ydb-short-name }}](../../postgresql/intro.md) позволяет использовать [Apache Superset](https://superset.apache.org/) для выполнения запросов и визуализации данных из {{ ydb-short-name }}. В этом случае Apache Superset работает с {{ ydb-short-name }} как с PostgreSQL.
```

2024-09-12 14:28 UTC, fomichev3000 approved these changes
Мне кажется надо добавить большую плашку:
Фунцкционал работает только при условии того, что режим совместимости включен и порт открыть. Настраивать -- ссылка

2024-09-12 14:28 UTC, merged