YQL: Fix lineage for flatten columns
ydb-platform/ydb pull request #8908
Opened 2024-09-08 17:05 UTC by mxkovalev

2024-09-09 11:37 UTC, vitstn commented on ydb/library/yql/core/services/yql_lineage.cpp
> +                    if (value->Head().IsCallable("Member")) {
не хватает проверки member чего, должен быть row

2024-09-09 11:38 UTC, vitstn requested changes
!

2024-09-09 14:01 UTC, rvu1024 commented on ydb/library/yql/core/services/yql_lineage.cpp
> +        const THashMap<const TExprNode*, TString>& flattenColumns = {}) {
Я бы не стал здесь и ниже дать default value для flattenColumns. Есть шанс где-нибудь пропустить

2024-09-10 09:34 UTC, vitstn commented on ydb/library/yql/core/services/yql_lineage.cpp
> +        const THashMap<const TExprNode*, TString>& flattenColumns = {}) {
+1

2024-09-10 14:34 UTC, mxkovalev commented on ydb/library/yql/core/services/yql_lineage.cpp
> +                    if (value->Head().IsCallable("Member")) {
добавил проверку с `arg`

2024-09-10 14:34 UTC, mxkovalev commented on ydb/library/yql/core/services/yql_lineage.cpp
> +        const THashMap<const TExprNode*, TString>& flattenColumns = {}) {
убрал дефолтное значение

2024-09-12 15:23 UTC, vitstn approved these changes

2024-09-13 08:48 UTC, merged