PgTypeDesc is const
ydb-platform/ydb pull request #8913
Opened 2024-09-08 19:14 UTC by azevaykin

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-09 09:48 UTC, alexd65536 approved these changes, later dismissed

2024-09-09 09:53 UTC, vitstn commented on ydb/library/yql/parser/pg_wrapper/interface/type_desc.h
неполный тип значительно безопаснее, чем void*
раз все равно везде меняем, давай на это перейдем

2024-09-10 12:42 UTC, vitstn commented on ydb/library/yql/parser/pg_catalog/catalog.h
> +#include <ydb/core/scheme_types/scheme_type_desc.h>
yql либа не может зависеть от ydb/core

2024-09-10 12:46 UTC, vitstn commented on ydb/core/scheme_types/scheme_type_desc.h
> +struct TTypeDesc
если это именно PgTypeDesc, можно наследоваться/вложить из pg_catalog.cpp TTypeDesc.

Если не обязательно, можно сделать метод вроде 

virtual const NPg::TTypeDesc* GetPgDesc() = 0;

2024-09-10 12:47 UTC, vitstn requested changes
!

2024-09-10 15:13 UTC, vitstn submitted a review, later dismissed

2024-09-12 12:00 UTC, vitstn approved these changes

2024-09-12 12:01 UTC, azevaykin commented on ydb/library/yql/parser/pg_catalog/catalog.h
> +#include <ydb/core/scheme_types/scheme_type_desc.h>
Убрал подобные зависимости

2024-09-12 12:02 UTC, azevaykin commented on ydb/core/scheme_types/scheme_type_desc.h
> +struct TTypeDesc
Сделал через reinterpret_cast

2024-09-12 12:16 UTC, gridnevvvit approved these changes

2024-09-12 14:15 UTC, ildar-khisambeev approved these changes

2024-09-12 14:17 UTC, merged