Add IListBuilder to UDF ABI
ydb-platform/ydb pull request #8914
Opened 2024-09-08 21:08 UTC by avevad

### Changelog entry 

Add IListBuilder to UDF ABI

### Changelog category 

* Improvement

### Additional information

...

2024-09-08 22:23 UTC, vitstn commented on ydb/library/yql/public/udf/udf_value_builder.h
> +    virtual IListValueBuilder::TPtr BuildList() const = 0;
это не Build еще

для словаря метод называется NewDict

т.к. NewList уже есть, чтобы не путать давай назовем NewListBuilder

2024-09-08 22:24 UTC, vitstn commented on ydb/library/yql/public/udf/udf_value_builder.h
> +
нужен UDF_ASSERT_TYPE_SIZE(IValueValueBuilder, 8);

2024-09-08 22:25 UTC, vitstn commented on ydb/library/yql/public/udf/udf_value_builder.h
> +    virtual IListValueBuilder& Add(const NUdf::TUnboxedValue* elements, size_t count) = 0;
AddMany. Разные компиляторы могут методы с одним именем перемешать в VMT, лучше с этим не играть

2024-09-09 06:55 UTC, avevad commented on ydb/library/yql/public/udf/udf_value_builder.h
> +    virtual IListValueBuilder& Add(const NUdf::TUnboxedValue* elements, size_t count) = 0;
А можно ссылку на пояснение этого явления? Я раньше об этом не слышал

2024-09-09 11:39 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_value_builder.cpp
> -        return HolderFactory_.GetEmptyContainerLazy();
оптимизация с empty container важная, оно позволила бы избежать аллокации билдера

2024-09-09 11:41 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +    TVector<NUdf::TUnboxedValue> List_;
для самого TVector стоит использовать temporary page pool mkql allocator, иначе тут не контролируется память на сам вектор

2024-09-09 11:42 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +            auto array = HolderFactory_.CreateDirectArrayHolder(List_.size(), inplace);
это основной путь, там вроде есть способ без копирования превратить вектор в список

2024-09-09 11:43 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +
List_ стоит почистить, иначе при повторном Build возможны разные приколы вроде использования после move
 
 либо добавить защиту на повторный Build

2024-09-09 11:44 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +        List_.reserve(List_.size() + count);
а разве это не может дать N^2 алгоритм?

при обычном push_back есть гарантия экспоненциального расширения, при reserve ее afaik нет.

т.к. ты работаешь через back_inserter имеет смысл вообще не трогать reserve, если он не будет экпоненциальный

2024-09-09 11:45 UTC, vitstn requested changes
!

2024-09-09 12:52 UTC, avevad commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +        List_.reserve(List_.size() + count);
Не понял... std::back_inserter в следующих строчках N раз дернет insert(back()), соответственно мы сразу хотим чтобы было место сразу на все элементы. Вот я и делаю reserve для этого предварительно.

2024-09-09 12:52 UTC, avevad commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +
справедливо

2024-09-09 12:52 UTC, avevad commented on ydb/library/yql/minikql/computation/mkql_value_builder.cpp
> -        return HolderFactory_.GetEmptyContainerLazy();
согласен

2024-09-09 13:39 UTC, avevad commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +            auto array = HolderFactory_.CreateDirectArrayHolder(List_.size(), inplace);
Нашел только THolderFactory::VectorAsArray , но там тоже есть копирование

2024-09-09 14:06 UTC, rvu1024 commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +    explicit TListValueBuilder(const THolderFactory &HolderFactory)
style: & к типу

2024-09-09 14:06 UTC, rvu1024 commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +    const NMiniKQL::THolderFactory &HolderFactory_;
style: & к типу

2024-09-10 09:32 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +        List_.reserve(List_.size() + count);
reserve если точный, то это приведет к N^2 - т.к. будет переаллокация
подумай над добавление +2 элементов N/2 раз

2024-09-10 09:33 UTC, vitstn requested changes

2024-09-10 09:33 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +            auto array = HolderFactory_.CreateDirectArrayHolder(List_.size(), inplace);
NUdf::TUnboxedValuePod VectorAsVectorHolder(TUnboxedValueVector&& list) const;

2024-09-11 15:40 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +        std::copy_n(std::make_move_iterator(elements), count, std::back_inserter(List_));
клиент не очень ожидает разрушенных UV после этой функции.
тем более что копировать UV очень дешево

2024-09-11 15:42 UTC, vitstn commented on ydb/library/yql/public/udf/udf_value_builder.h
> +    virtual IListValueBuilder& AddMany(const NUdf::TUnboxedValue* elements, size_t count) = 0;
давай тут напишем про то, что elements будут разрушены. и то же самое в NewList.

это очень не очевидно из сигнатуры

2024-09-11 15:43 UTC, vitstn commented on ydb/library/yql/minikql/computation/mkql_computation_node_holders.cpp
> +        std::copy_n(std::make_move_iterator(elements), count, std::back_inserter(List_));
т.к. соседний Add тоже разрушающий, то тут не будем трогать, а сделаем комментарий в интерфейсе

2024-09-12 12:19 UTC, vitstn approved these changes

2024-09-12 12:51 UTC, merged