feat: YDB JOOQ extension doc
ydb-platform/ydb pull request #8933
Opened 2024-09-09 09:25 UTC by KirillKurdyukov

### Changelog category 

* Documentation (changelog entry is not required)

2024-09-17 03:30 UTC, blinkov requested changes

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +JOOQ is a Java library that allows you to create type-safe SQL queries by generating Java classes from a database schema and using convenient query builders.
```suggestion
# JOOQ extension for {{ ydb-short-name }}

This guide explains how to use [JOOQ](https://www.jooq.org/) with {{ ydb-short-name }}.

JOOQ is a Java library that allows you to create type-safe SQL queries by generating Java classes from a database schema and providing convenient query builders.
```

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +Let's look at an example of the `maven` plugin:
```suggestion
You can generate Java classes using any of the tools provided on the [official JOOQ website](https://www.jooq.org/doc/latest/manual/code-generation/codegen-configuration/). Two dependencies are required: the [{{ ydb-short-name }} JDBC driver](https://github.com/ydb-platform/ydb-jdbc-driver) and the JOOQ extension for {{ ydb-short-name }}, along with two parameters:

- `database.name`: `tech.ydb.jooq.codegen.YdbDatabase` (mandatory setting)
- `strategy.name`: `tech.ydb.jooq.codegen.YdbGeneratorStrategy` (recommended setting)

An example using the `maven` plugin:
```

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +Example of generated classes from [YQL tutorial](../../dev/yql-tutorial/create_demo_tables.md):
It'd be helpful to post the full classes somewhere on GitHub and give a link to them here.

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +                <!-- исключение системных таблицы -->
```suggestion
                <!-- excluding system tables -->
```

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +    ```
There was a similar example in lines 16-60: why do you give a complete example first and then repeat a small part of it?

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +    </dependency>
This looks like an incorrect copy-paste from a neighboring Spring JDBC article.

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +        implementation "tech.ydb.dialects:spring-data-jdbc-ydb:$ydbDialectVersion"
also Spring JDBC

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +To obtain a `YdbDSLContext` (an extension of `org.jooq.DSLContext`), use the `tech.ydb.jooq.YDB` class. For example:
```suggestion
To obtain a `YdbDSLContext` class instance (an extension of `org.jooq.DSLContext`), use the `tech.ydb.jooq.YDB` class. For example:
```

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +String url = "jdbc:ydb:<grpc/grpcs>://<host>:<2135/2136>/path/to/database[?saFile=file:~/sa_key.json]";
An endpoint has already been specified above at line 43; why is it needed two times?

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +String url = "jdbc:ydb:<grpc/grpcs>://<host>:<2135/2136>/path/to/database[?saFile=file:~/sa_key.json]";
`<...>` in our documentation is usually used just to name a placeholder (not to list all options), then below the example, each placeholder needs to be explained.

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +spring.datasource.url=jdbc:ydb:<grpc/grpcs>://<host>:<2135/2136>/path/to/database[?saFile=file:~/sa_key.json]
If this indeed is intended to be used inside the Spring Framework, let's make separate examples for each scenario and explicitly explain what options are available.

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +`YdbDSLContext` is ready to use. Let's look at examples of specific YQL queries:
```suggestion
`YdbDSLContext` is ready to use.

 ## Examples of specific YQL queries
```

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +The [`UPSERT`](../../yql/reference/syntax/upsert_into.md) command:
Let's add a YQL query corresponding to each of these snippets.

2024-09-17 03:30 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +To specify an index in the VIEW statement, you must use the `useIndex` method on `Table`:
```suggestion
To specify a [secondary index](../../concepts/secondary_indexes.md) in the `VIEW` statement, you must use the `useIndex` method on `Table`:
```

2024-09-18 14:04 UTC, KirillKurdyukov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +String url = "jdbc:ydb:<grpc/grpcs>://<host>:<2135/2136>/path/to/database[?saFile=file:~/sa_key.json]";
Первый URL для генерации Java классов с помощью мавен плагина. Это обычно делается через докер, накатив предварительно схему

2024-09-19 07:40 UTC, blinkov submitted a review, later dismissed

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +In all other respects, the {{ ydb-short-name }} dialect follows the JOOQ documentation.
```suggestion
In all other respects, the {{ ydb-short-name }} dialect follows the [JOOQ documentation](https://www.jooq.org/doc/latest/manual/).
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/en/core/integrations/orm/jooq.md
> +An example of a simple Spring Boot application can be found [here](https://github.com/ydb-platform/ydb-java-examples/tree/master/jdbc/spring-jooq).
```suggestion
A complete example of a simple Spring Boot application can be found [here](https://github.com/ydb-platform/ydb-java-examples/tree/master/jdbc/spring-jooq).
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +JOOQ — это библиотека для Java, которая позволяет создавать типобезопасные SQL-запросы путем генерации Java-классов из схемы базы данных и использования удобных конструкторов запросов.
```suggestion
# Расширение JOOQ для использования с {{ ydb-short-name }}

Это руководство предназначено для использования [JOOQ](https://www.jooq.org/) с {{ ydb-short-name }}.

JOOQ — это библиотека для Java, которая позволяет создавать типобезопасные SQL-запросы путём генерации Java-классов из схемы базы данных и использования удобных конструкторов запросов.
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +- `strategy.name`: `tech.ydb.jooq.codegen.YdbGeneratorStrategy` (рекомендуется к использованию)
```suggestion
## Генерация Java-классов

Генерировать Java-классы можно с помощью любых инструментов, представленных на [официальном сайте JOOQ](https://www.jooq.org/doc/latest/manual/code-generation/codegen-configuration/), используя две зависимости: {{ ydb-short-name }} JDBC Driver и расширение JOOQ для {{ ydb-short-name }}. Также необходимо указать два параметра:

- `database.name`: `tech.ydb.jooq.codegen.YdbDatabase` (обязательная настройка)
- `strategy.name`: `tech.ydb.jooq.codegen.YdbGeneratorStrategy` (рекомендуется к использованию)
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +Пример сгенерированных классов из [туториал по YQL](../../dev/yql-tutorial/create_demo_tables.md) (сгенерированные классы доступны по [ссылке](https://github.com/ydb-platform/ydb-java-examples/tree/m
```suggestion
Пример сгенерированных классов из [туториала по YQL](../../dev/yql-tutorial/create_demo_tables.md) (их полный код [доступен на GitHub](https://github.com/ydb-platform/ydb-java-examples/tree/master/jdbc/spring-jooq/src/main/java/ydb/default_schema)):
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +Примеры для различных систем сборки:
```suggestion
## Использование

Для интеграции {{ ydb-short-name }} с JOOQ в ваш проект потребуется добавить две зависимости: {{ ydb-short-name }} JDBC Driver и расширение JOOQ для {{ ydb-short-name }}.

Примеры для различных систем сборки:
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +Из синтаксиса YQL доступны следующие команды в `YdbDSLContext`:
```suggestion
В `YdbDSLContext` доступны следующие команды, специфичные для синтаксиса YQL:
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +В остальном диалект {{ ydb-short-name }} следует документации JOOQ.
```suggestion
В остальном диалект {{ ydb-short-name }} соответствует [документации JOOQ](https://www.jooq.org/doc/latest/manual/).
```

2024-09-19 07:40 UTC, blinkov commented on ydb/docs/ru/core/integrations/orm/jooq.md
> +Пример простого приложения Spring Boot можно найти по [ссылке](https://github.com/ydb-platform/ydb-java-examples/tree/master/jdbc/spring-jooq).
```suggestion
Полный пример простого приложения Spring Boot можно найти [на GitHub](https://github.com/ydb-platform/ydb-java-examples/tree/master/jdbc/spring-jooq).
```

2024-09-20 07:28 UTC, fomichev3000 approved these changes

2024-09-20 07:29 UTC, merged