Fix backtick matching for antlr4
ydb-platform/ydb pull request #8941
Opened 2024-09-09 10:58 UTC by OrlovPavel

### Changelog entry 

...

### Changelog category 

* New feature
* Experimental feature
* Improvement
* Performance improvement
* Bugfix 
* Backward incompatible change
* Documentation (changelog entry is not required)
* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-09 11:50 UTC, vitstn submitted a review, later dismissed

2024-09-10 21:38 UTC, nepal requested changes

2024-09-10 21:38 UTC, nepal commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment ID_QUOTED_CORE: '\\'. | '``' | ~('`' | '\\');
А ты ведь тут более широкий класс идентификаторов разрешаешь чем в antlr3.
Раньше было так
```
fragment ID_QUOTED_CORE: '``' | '\\`' | ~'`';
```
Т.е. эскейпить через бэкслеш можно только бэктик и бэкслеш. А ты позволяешь любой символ эскейпить. Зачем?

2024-09-10 22:02 UTC, nepal commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment ID_QUOTED_CORE: '\\'. | '``' | ~('`' | '\\');
Так, на счет любого символа я погорячился - семантика эскейпинга определяется не тут, а в с++ коде. Переформатирую вопрос - а что не так было с предыдущей версией? Почему оно работало в v3 и не работало в v4?

2024-09-11 07:19 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment ID_QUOTED_CORE: '\\'. | '``' | ~('`' | '\\');
В запросе 
```
select
    1 as `Schema\ has \`RealCost\``
    -- foo`bar
```
На токен `ID_QUOTED` матчилась строка:
```
`Schema\ has \`RealCost\``
    -- foo`
```
На самом деле регулярка
```
('``' | '\\`' | ~'`')*
```
Действительно матчит то, что в скобочках по формальному определению, разбиение тут такое:
```
Schema has -> (~'`')*
\` -> '\\`'
RealCost\ -> (~'`')*
`` -> '``'
\n    -- foo -> (~'`')*
```
Ну и поскольку матчинг токенов в antlr4 жадный, то он взял самую длинную матчащуюся строку.
И кстати в antlr3 можно любой символ тоже эскейпить, вот пример запроса валидного:
```
select 1 as `a``b`, 2 as ````, 3 as `\x60a\x60`, 4 as ```b```, 5 as `\`c\``
```

2024-09-11 07:54 UTC, vitstn approved these changes

2024-09-11 08:02 UTC, asmyasnikov approved these changes

2024-09-11 09:08 UTC, nepal commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment ID_QUOTED_CORE: '\\'. | '``' | ~('`' | '\\');
Я вот все-таки не очень понял. Рассмотрим запрос
```
select 1 as `aaa \\`; select 2`;
```
На уровне antlr они работают по разному
1) в antlr3 и antlr4 до этих изменений ID_TOKEN матчился на 
```
`aaa \\`; select 2`
```
Запрос правда потом падал уже в yql/ast/yql_ast_escaping.cpp:UnescapeArbitraryAtom()
2) после изменений в PR это конструкция отвергается на уровне antlr - 
```
Error: extraneous input '`' expecting {<EOF>, ';'}
```

Причина падения в пункте 1 - на самом деле UnescapeArbitraryAtom ожидает c-style escaping, а имеющаяся на данный момент грамматика с этой функцией не синхронизирована.

Какие можно сделать выводы
1) парсинг ID_QUOTED этим изменением меняется
2) кажется баг в текущем sql коде позволяет тем менее сделать это изменит

Но я все-таки предлагаю подумать можно ли соорудить такой пример который принимался текущей связкой antlr+sql и отвергается или парится по-другому новым antlr3

2024-09-11 09:42 UTC, OrlovPavel commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment ID_QUOTED_CORE: '\\'. | '``' | ~('`' | '\\');
а тут уже вопрос к тому, что хотим заложить в ID_QUOTED. В текущем PR в antlr4 заложен следующий смысл: это строка из произвольных символов зажатая в бэктики , т.ч. она разбивается на символы вида
```
`` - двойной бэктик
\. - произвольный экранированный символ
~('`' | '\\') - произвольный символ кроме бэктика и слеша
```
В antlr3 матчинг ID_QUOTED судя по всему работает иначе: при последовательном чтении символов строки, если мы встретили '`', то если дальше есть  '`', матчим двойной и идем дальше, иначе останавливаемся, если встретили слеш и дальше идет бэктик, то матчим ескейпленый бэктик, иначе просто матчим слеш сам по себе (~'`'), если встретили символ отличный от перечисленных, то матчим его.
Когда это даст разницу? в случае, если в матченной строке в antlr3 сматчился один слеш, как и произошло выше

2024-09-11 12:54 UTC, nepal approved these changes

2024-09-11 12:54 UTC, merged