YDBDOCS-819: serial types
ydb-platform/ydb pull request #8956
Opened 2024-09-09 12:33 UTC by shnikd

2024-09-17 04:42 UTC, blinkov requested changes, later dismissed

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
> +  Для ключевых и неключевых колонок допускаются только [примитивные](../../types/primitive.md) и [serial](../../types/serial.md) типы данных.
как-будто какая-то несостыковка: в другой ветке if'а serial нельзя было в неключевых колонках — а тут звучит, что можно

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +# Serial типы данных
Звучит как YDB-only фича. Если так, то надо завести переменную feature_serial, которую для YDB выставить в true, а для всего остального вроде YQL over YT получится false. И тогда всю эту страницу и ссылки на неё убрать под if/when feature_serial.

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +```
досыпать пустых строк вокруг блоков с кодом и заголовков

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Эти типы данных используются для создания автоинкрементных колонок, а именно для каждой новой строки, добавляемой в таблицу, будет автоматически генерироваться уникальное значение для такой колонки (
```suggestion
Serial типы данных представляют собой целые числа, но с дополнительным механизмом генерации значений. Эти типы данных используются для создания автоинкрементных колонок, а именно для каждой новой строки, добавляемой в таблицу, будет автоматически генерироваться уникальное значение для такой колонки (подобно типу [SERIAL](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL) в PostgreSQL или свойству [AUTO_INCREMENT](https://dev.mysql.com/doc/refman/9.0/en/example-auto-increment.html) в MySQL).
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +    user_id SERIAL,
```suggestion
    user_id Serial,
```

в YQL типы данных обычно так пишутся, а CAPS LOCK — только для ключевых слов

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Можно самостоятельно указать значение `Serial` колонки при вставке, в этом случае вставка будет выполняться, как с обычной колонкой.
```suggestion
Можно самостоятельно указать значение `Serial` колонки при вставке, в этом случае вставка будет выполняться, как с обычной целочисленной колонкой:
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +UPSERT INTO users (user_id, name, email) VALUES (4, 'Peter', 'peter@example.com');
стоит явно проговорить, что произойдёт с генератором значений при этом — надеюсь сам перескочит на 5, а не выдаст конфликт по pk?

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Только ключевые колонки могут иметь тип `Serial`.
```suggestion
Только колонки, участвующие в первичном ключе таблиц, могут иметь тип `Serial`.
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Только ключевые колонки могут иметь тип `Serial`.
кстати, поддерживаются ли они в колоночных таблицах?

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +При определении такого типа для колонки создается отдельный схемный объект `Sequence`, привязанный к этой колонке, являющийся генератором последовательности, из которого извлекаются значения. Этот об
```suggestion
При определении такого типа для колонки создаётся отдельный схемный объект `Sequence`, привязанный к этой колонке и являющийся генератором последовательности, из которого извлекаются значения. Этот объект является приватным и скрыт от пользователя. `Sequence` будет уничтожен вместе с таблицей.
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Значения последовательности начинаются с единицы, выдаются с шагом равным единице и ограничены в зависимости от используемого типа.
```suggestion
Значения последовательности начинаются с единицы, выдаются с шагом, равным единице, и ограничены в зависимости от используемого типа.
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Тип | Ограничение | Тип значения
```suggestion
Тип | Максимальное значение | Тип значения
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +При переполнении `Sequence` на вставке будет возвращаться ошибка.
добавить пример такой ошибки

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +`BigSerial` | 2<sup>63</sup>–1 | `Int64`
```suggestion
`SmallSerial` | $2^15–1$ | `Int16`
`Serial2` | $2^15–1$ | `Int16`
`Serial` | $2^31–1$ | `Int32`
`Serial4` | $2^31–1$ | `Int32`
`Serial8` | $2^63–1$ | `Int64`
`BigSerial` | $2^63–1$ | `Int64`
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Отметим, что следующее значение выдается генератором до непосредственной вставки в таблицу и будет уже считаться использованным, даже если строка, содержащая данное значение, не была успешно вставлен
```suggestion
Отметим, что следующее значение выдаётся генератором до непосредственной вставки в таблицу и уже будет считаться использованным, даже если строка, содержащая это значение, не была успешно вставлена, например, при откате транзакции. Поэтому множество значений такой колонки может содержать пропуски и состоять из нескольких промежутков.
```

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Для таблиц с автоинкрементными колонками поддержаны операции копирования и `backup`/`restore`.
добавить ссылок на эти операции, видимо речь про cli?

2024-09-17 04:42 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/toc_i.yaml
> +- name: Serial
```suggestion
- name: Серийные
```
может тоже перевести, чтобы не выбивалось из списка?

тогда в остальных местах тоже консистентно надо будет сделать

2024-09-17 13:28 UTC, shnikd commented on ydb/docs/ru/core/yql/reference/yql-core/types/toc_i.yaml
> +- name: Serial
Может все-таки перевести как автоинкрементные?

2024-09-19 10:12 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/toc_i.yaml
> +- name: Serial
@shnikd afaik `serial` — скорее обобщение autoincrement, т.к. низлежащая последовательность не обязана именно инкрементить и может что-нибудь другое делать типа https://en.wikipedia.org/wiki/Snowflake_ID

но пока у нас альтернатив нет я не сильно против и автоинкремента, просто потом придётся переделывать вероятно

2024-09-19 10:20 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +John@example.com | John | 3
```suggestion
`alice@example.com` | Alice | 1
`bob@example.com` | Bob | 2
`john@example.com` | John | 3
```

2024-09-19 18:44 UTC, shnikd commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +Только ключевые колонки могут иметь тип `Serial`.
у нас сейчас в доке написано, что операции insert/upsert/replace поддерживаются только для строковых таблиц, поэтому нет

2024-09-20 03:21 UTC, shnikd commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +При переполнении `Sequence` на вставке будет возвращаться ошибка.
Убрал эту строчку, сейчас ошибки нет, происходит каст и при переполнении Int16 например запишется -1

2024-09-20 15:32 UTC, shnikd commented on ydb/docs/ru/core/yql/reference/yql-core/types/_includes/serial.md
> +При переполнении `Sequence` на вставке будет возвращаться ошибка.
Это не правда, на самом деле будет выдаваться ошибка о переполении sequence, добавил в доку

2024-09-23 06:43 UTC, fomichev3000 approved these changes

2024-09-23 06:43 UTC, merged