fix for YQ-3287
ydb-platform/ydb pull request #8970
Opened 2024-09-09 14:48 UTC by evanevanevanevannnn

### Changelog entry 

fix for [YQ-3287](https://st.yandex-team.ru/YQ-3287)

### Changelog category 

* Bugfix

2024-09-10 13:34 UTC, uzhastik commented on ydb/library/yql/providers/common/mkql/parser.cpp
> +            } catch(const yexception& ex) {
нужен пробел после catch

2024-09-17 14:43 UTC, dorooleg requested changes

2024-09-17 14:43 UTC, dorooleg commented on ydb/core/fq/libs/actors/database_resolver.cpp
> +            } catch (const NYql::TCodeLineException& ex) {
В логи нужно написать полный текст ошибки с именем файла и строчкой кода. А пользователю уже отдать только текст ошибки.

2024-09-17 14:43 UTC, dorooleg commented on ydb/core/fq/libs/config/yq_issue.cpp
> +NYql::TIssue MakeFatalIssue(NYql::TIssueCode id, const TString& message) {
А почему тут перешли на `NYql::TIssueCode`?

2024-09-17 14:43 UTC, dorooleg commented on ydb/core/fq/libs/control_plane_storage/request_actor.h
>              NYql::TIssue internalIssue = MakeErrorIssue(exception.Code, CurrentExceptionMessage());
Вот здесь собирается internalIssue и потом в логи печатается. Нужно в остальных местах аналогичный подход заиспользовать

2024-09-17 14:43 UTC, dorooleg commented on ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
> +                } catch (const TCodeLineException& ex) {
В логи обязательно нуно текст записать с файлом и строчкой

2024-09-17 19:45 UTC, uzhastik commented on ydb/core/fq/libs/control_plane_storage/extractors.h
> +            ythrow NYql::TCodeLineException(TIssuesIds::INTERNAL_ERROR) << "Error parsing proto message. Please contact internal support";
ythrow лучше заменить на throw

2024-09-18 06:13 UTC, evanevanevanevannnn commented on ydb/core/fq/libs/control_plane_storage/extractors.h
> +            ythrow NYql::TCodeLineException(TIssuesIds::INTERNAL_ERROR) << "Error parsing proto message. Please contact internal support";
так TCodeLineException как раз таки ловит этот ythrow и сохраняет строку кода отдельно от сообщения

2024-09-18 08:28 UTC, dorooleg commented on ydb/core/fq/libs/config/yq_issue.cpp
> +NYql::TIssue MakeFatalIssue(NYql::TIssueCode id, const TString& message) {
Они специально разными сделаны, у них разные issue code по задумке. Тут правильно держать именно `NFq::TIssuesIds::EIssueCode`

2024-09-19 14:43 UTC, dorooleg commented
Договорились в отдельном ревью s3_read_actor исключения переделать на TCodeLineException

2024-09-19 14:45 UTC, dorooleg approved these changes

2024-09-19 15:04 UTC, rvu1024 approved these changes

2024-09-19 15:04 UTC, merged