Fix yql doc
ydb-platform/ydb pull request #9007
Opened 2024-09-10 11:20 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-09-12 02:07 UTC, blinkov requested changes

2024-09-12 02:07 UTC, blinkov commented on ydb/docs/ru/core/concepts/glossary.md
> +Реализация распределённых транзакций рассмотрена в отдельной статье [{#T}](../contributor/datashard-distributed-txs.md), а ниже приведён список нескольких связанных терминов.
не выглядит как правильный фикс, там нужна эта ссылка

2024-09-12 02:07 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
> +Механизм {% if oss == true and backend_name == "YDB" %}[групп](../../../../concepts/datamodel/table.md#column-groups){% else %}групп{% endif %} колонок позволяет увеличить производительность операций
по идее вся эта статья только для YDB — зачем ещё раз backend_name?

2024-09-12 02:07 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +`ADD CHANGEFEED <name> WITH (option = value[, ...])` — добавляет {% if oss == true and backend_name == "YDB" %}[поток изменений (changefeed)](../../../../concepts/cdc.md){% else %}поток изменений (ch
по идее вся эта статья только для YDB — зачем ещё раз backend_name тут и ниже?

2024-09-12 02:14 UTC, blinkov commented
плюс конфликты зарезолвить

2024-09-23 08:01 UTC, Pseudolukian commented on ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
> +`ADD CHANGEFEED <name> WITH (option = value[, ...])` — добавляет {% if oss == true and backend_name == "YDB" %}[поток изменений (changefeed)](../../../../concepts/cdc.md){% else %}поток изменений (ch
Убрал под when в TOCе

2024-09-23 11:21 UTC, Pseudolukian commented on ydb/docs/ru/core/concepts/glossary.md
> +Реализация распределённых транзакций рассмотрена в отдельной статье [{#T}](../contributor/datashard-distributed-txs.md), а ниже приведён список нескольких связанных терминов.
Пофиксил

2024-09-23 11:36 UTC, blinkov commented on ydb/docs/ru/core/postgresql/import.md
> +{% endif %}
```suggestion

{% if oss == true %}

- С помощью утилиты [ydb-importer](../integrations/ingestion/import-jdbc.md).

{% endif %}
```

2024-09-25 03:43 UTC, blinkov approved these changes

2024-09-25 03:43 UTC, merged