Add SqlV1Antlr4.g configuration option to fix reserved token name
ydb-platform/ydb pull request #9055
Opened 2024-09-11 07:46 UTC by vityaman

### Changelog entry 

Add configuration option for `SqlV1Antlr4.g.in` to avoid reserved token name usage.

### Changelog category 

* Improvement

### Additional information

- Added configuration option `GRAMMAR_RESERVED_SUFFIX`
- Set `GRAMMAR_RESERVED_SUFFIX` to `""` everywhere
- `GRAMMAR_RESERVED_SUFFIX` will be set to `"_"` when original C++ target is used.

2024-09-11 07:52 UTC, vityaman commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +  | NULL@GRAMMAR_RESERVED_SUFFIX@
Disadvantage is that it makes grammar way less readable. If it is not acceptable, then maybe there is some way to configure this grammar using some regex based replacement?

2024-09-11 07:52 UTC, vityaman commented on ydb/library/yql/sql/v1/format/sql_format.cpp
> +            if (const bool isKeyword = AsciiEqualsIgnoreCase(in->Name, in->Content)) {
After I set `NULL` suffix in any way, tests failed. I spent some time figuring out a cause of it. Added this variable to make it more clear for reader to understand what does this check.

2024-09-11 19:10 UTC, nepal requested changes

2024-09-11 19:10 UTC, nepal commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +  | (ISNULL | NOTNULL | IS NULL@GRAMMAR_RESERVED_SUFFIX@ | (IS)? NOT NULL@GRAMMAR_RESERVED_SUFFIX@)
Я против таких изменений. Не надо корежить грамматику. Дальше у вас сломается ERROR или STRUCT и вы и для них суффиксы будете делать? Надо менять *.stg файлы. Например в Cpp.stg ко всем иментам токенов добавляется TOKEN_  и проблемы с NULL пропадают. Сделайте аналогично.

2024-09-12 06:56 UTC, vityaman commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +  | (ISNULL | NOTNULL | IS NULL@GRAMMAR_RESERVED_SUFFIX@ | (IS)? NOT NULL@GRAMMAR_RESERVED_SUFFIX@)
Согласен, грамматика теперь выглядит так себе, и ситуация будет ухудшаться при коллизиях

2024-09-12 07:02 UTC, vityaman commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +  | (ISNULL | NOTNULL | IS NULL@GRAMMAR_RESERVED_SUFFIX@ | (IS)? NOT NULL@GRAMMAR_RESERVED_SUFFIX@)
@nepal, как думаешь, в какую лучше его папочку сложить? Куда-то по пути `ydb/library/yql/parser/cpp_ast` или в папочку с `ydb_cli`, где чего я этим всем и занимаюсь?

2024-09-13 13:52 UTC, vityaman commented
Closed as an inappropriate solution.

2024-09-13 13:52 UTC, closed without merging