ADD OLAP in YDB-CLI
ydb-platform/ydb pull request #9067
Opened 2024-09-11 09:58 UTC by Pseudolukian

### Changelog category
* Documentation (changelog entry is not required)

2024-09-17 04:12 UTC, blinkov requested changes, later dismissed

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/_includes/commands.md
> +[table read](../commands/readtable.md) | Потоковое чтение строковой таблицы
хм, точно для колоночных не работает? мне казалось должно

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/_includes/index.md
> +Работа с колоночными таблицами поддержана частично.
Не понятно какая польза от этого сообщения — думаю плашек на страницах конкретных команд достаточно. Давай уберём?

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/index.md
> +С помощью команды `workload` вы можете запустить различные виды нагрузки для вашей БД. Во всех нагрузочных тестах используются строковые таблицы.
Это не так и у некоторых был аргумент для выбора типа таблиц, пример:

![Screenshot 2024-09-17 at 11 07 07](https://github.com/user-attachments/assets/2824260b-fcf5-48d0-b585-51fefdd53723)

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
> +```sql
sql -> yql

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
> +Создаются 3 строковые таблицы со следующими DDL:
```suggestion
Создаются 3 строковые таблицы со следующими DDL:

```

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-cli/workload-kv.md
> +* [upsert](#upsert-kv) — при помощи операции `UPSERT` вставляет в заранее созданную командой `init` строковую таблицу строки, которые представляют из себя кортежи (key1, key2, ... keyK, value1, value
```suggestion
* [upsert](#upsert-kv) — при помощи операции `UPSERT` вставляет в заранее созданную командой `init` строковую таблицу строки, которые представляют из себя кортежи `(key1, key2, ... keyK, value1, value2, ... valueN)`, числа K и N задаются в параметрах.
```

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/topic.md
> +          // обработать событие и записать результаты в строковую таблицу
а почему именно строковую? кажется тут можно любой код написать

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +| `W` | (write) запись. Состоит из разрешений на обновление и удаление записей из строковых таблиц, запись атрибутов ACL, создание подкаталогов, создание таблиц, очередей, изменение и удаление объект
а как тогда разрешение на запись в колоночные таблицы выглядит?

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +Например, `+(SR|UR):subject` — разрешение на чтение и обновление записей в строковые таблицы.
какая-то несостыковка: ниже у этих же SR и UR нет приписки про строковые таблицы, а тут — есть

2024-09-17 04:12 UTC, blinkov commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +| `CT` | (create table) создание таблиц
тогда уж надо везде множественное число делать, например тогда строкой ниже будет «очередей»

2024-09-17 09:45 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/_includes/commands.md
> +[table read](../commands/readtable.md) | Потоковое чтение строковой таблицы
Оно просто виснит и всё. Я задал вопрос Звереву, но пока ответа не получил.

2024-09-17 12:37 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/_includes/index.md
> +Работа с колоночными таблицами поддержана частично.
Убрал

2024-09-17 12:38 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/index.md
> +С помощью команды `workload` вы можете запустить различные виды нагрузки для вашей БД. Во всех нагрузочных тестах используются строковые таблицы.
О, чёт я не догадался в help заглянуть.

2024-09-17 12:46 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/index.md
> +С помощью команды `workload` вы можете запустить различные виды нагрузки для вашей БД. Во всех нагрузочных тестах используются строковые таблицы.
Убрал

2024-09-17 12:50 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
> +```sql
Поправил

2024-09-17 12:51 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
> +Создаются 3 строковые таблицы со следующими DDL:
Добавил пустую строку

2024-09-17 13:19 UTC, Pseudolukian commented on ydb/docs/ru/core/reference/ydb-cli/workload-kv.md
> +* [upsert](#upsert-kv) — при помощи операции `UPSERT` вставляет в заранее созданную командой `init` строковую таблицу строки, которые представляют из себя кортежи (key1, key2, ... keyK, value1, value
Правка уже сделана

2024-09-17 14:37 UTC, Pseudolukian commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +| `W` | (write) запись. Состоит из разрешений на обновление и удаление записей из строковых таблиц, запись атрибутов ACL, создание подкаталогов, создание таблиц, очередей, изменение и удаление объект
Тут ты прав. Молотков говорит, что права едины для строковых и колодочных таблиц.

2024-09-17 15:49 UTC, Pseudolukian commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +Например, `+(SR|UR):subject` — разрешение на чтение и обновление записей в строковые таблицы.
Надо оставить просто таблицы. Поправил.

2024-09-17 15:49 UTC, Pseudolukian commented on ydb/docs/ru/core/security/short-access-control-notation.md
> +| `CT` | (create table) создание таблиц
Поправил

2024-09-23 03:53 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/topic.md
> +          // обработать событие и записать результаты в строковую таблицу
```suggestion
          // обработать событие и записать результаты в таблицу
```

2024-09-23 03:55 UTC, blinkov commented on ydb/docs/ru/core/reference/ydb-sdk/topic.md
> +              // обработать событие и записать результаты в строковую таблицу
```suggestion
              // обработать событие и записать результаты в таблицу
```

2024-09-23 07:00 UTC, fomichev3000 approved these changes

2024-09-23 07:01 UTC, merged