Support DISTINCT for aggregation functions over window
ydb-platform/ydb pull request #9090
Opened 2024-09-11 13:22 UTC by loochek

### Changelog entry 

* Support for DISTINCT clause for aggregation functions calculated over window

### Changelog category 

* Experimental feature

### Additional information

Feature flag: `PRAGMA EnableDistinctOverWindow;`

2024-09-11 19:50 UTC, nepal requested changes

2024-09-11 19:50 UTC, nepal commented on ydb/library/yql/sql/v1/sql_query.cpp
> +        } else if (normalizedPragma == "enabledistinctoverwindow") {
Давай назовем прагму DistinctOverWindow. Тут еще надо поддержать DisableDistinctOverWindow. И добавить вот сюда https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/sql/v1/context.cpp#L66

2024-09-12 09:38 UTC, loochek commented on ydb/library/yql/sql/v1/sql_query.cpp
> +        } else if (normalizedPragma == "enabledistinctoverwindow") {
done

2024-09-12 12:02 UTC, vitstn approved these changes

2024-09-12 17:20 UTC, nepal approved these changes

2024-09-12 17:24 UTC, merged