Support ydb dump for tables with serial types
ydb-platform/ydb pull request #9272
Opened 2024-09-16 05:42 UTC by shnikd

2024-09-20 16:28 UTC, spuchin approved these changes

2024-09-20 16:29 UTC, spuchin commented on ydb/public/api/protos/ydb_table.proto
> +    bool include_set_val = 8;
Может include_sequence_positions?

2024-09-20 16:33 UTC, shnikd commented on ydb/public/api/protos/ydb_table.proto
> +    bool include_set_val = 8;
SetVal уже используется в SequenceDescription

2024-09-20 21:44 UTC, pixcc requested changes

2024-09-20 21:44 UTC, pixcc commented on ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
> +    Y_UNIT_TEST(BasicRestoreTableWithSerial) {
minor: В этом файле есть `CreateBackupLambda` и `CreateRestoreLambda` для `dump`/`restore`, так что можно передать их в `TestRestoreTableWithSerial`.

2024-09-20 21:44 UTC, pixcc commented on ydb/library/backup/backup.cpp
> +        break;
Как будто тут какой-то странный цикл получился, максимум из одной итерации

2024-09-22 20:03 UTC, spuchin submitted a review, later dismissed

2024-09-23 08:42 UTC, pixcc approved these changes

2024-09-23 09:49 UTC, spuchin approved these changes

2024-09-23 09:49 UTC, merged