[backups][yql] Implement entries handling for backup collections
ydb-platform/ydb pull request #9338
Opened 2024-09-17 02:10 UTC by Enjection

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-17 11:50 UTC, CyberROFL reviewed
lgtm

2024-09-18 12:51 UTC, nepal requested changes

2024-09-18 12:51 UTC, nepal commented on ydb/library/yql/sql/v1/sql_ut.cpp
> +            "<main>:1:40: Error: local: alternative is not implemented yet: \\d+:\\d+: local_index\\n");
Что это за \\d+? И надо аналогичные тесты добавить в antlr4_ut пока мы antlr3 не выкинули

2024-09-18 19:13 UTC, Enjection commented on ydb/library/yql/sql/v1/sql_ut.cpp
> +            "<main>:1:40: Error: local: alternative is not implemented yet: \\d+:\\d+: local_index\\n");
Эти тесты есть в новых antlr4_ut, но обрезанные, они не проверяют там ошибку целиком. Конкретно это исправление -- fuzzy матчинг, что бы тест при каждом изменении смещения ошибки в сорцах не триггерился. В прошлый раз мы обсуждали, что нужно как-то поправить -- я как раз поправил, но не стал отдельным пуллриком делать.

2024-09-18 20:36 UTC, nepal commented on ydb/library/yql/sql/v1/sql_ut.cpp
> +            "<main>:1:40: Error: local: alternative is not implemented yet: \\d+:\\d+: local_index\\n");
А зачем тут вообще позиция ошибки в сорцах? В этом нет никакого смысла для пользователя. Тем более что имя файла там не указано. Достаточно позиции ошибки в запросе (1:40). Давай удалим позицию в сорцах.

2024-09-19 12:58 UTC, nepal requested changes

2024-09-19 12:58 UTC, nepal commented on ydb/library/yql/sql/v1/sql_ut.cpp
> +            "<main>:1:40: Error: local: alternative is not implemented yet: \\d+:\\d+: local_index\\n");
Решили это сделать отдельным pr

2024-09-19 12:58 UTC, nepal commented on ydb/library/yql/sql/v1/ya.make
> +    library/cpp/regex/pcre
Мне не нравится эта зависимость - давай пока канонизируем как есть, я потом позиции выпилю

2024-09-19 13:01 UTC, nepal commented on ydb/library/yql/sql/v1/ya.make
> +    library/cpp/regex/pcre
Ну или перенеси эту зависимость в ut

2024-09-19 13:04 UTC, Enjection commented on ydb/library/yql/sql/v1/ya.make
> +    library/cpp/regex/pcre
Перенёс.

2024-09-19 14:54 UTC, nepal approved these changes

2024-09-19 15:30 UTC, merged