Adds info about topics transactions
ydb-platform/ydb pull request #9361
Opened 2024-09-17 09:54 UTC by ElenaAfina

### Changelog entry 

Adds documentation about topics transactions (RU)

### Changelog category 

* Documentation 

### Additional information

Adds description about transactions with topics: concept, main principles and constraints.

2024-09-18 09:51 UTC, Alek5andr-Kotov commented on ydb/docs/ru/core/concepts/topic.md
> +
Возможно, не хватает слова `что` после запятой

2024-09-18 09:51 UTC, Alek5andr-Kotov commented on ydb/docs/ru/core/concepts/topic.md
> +Транзакции не вносят дополнительных ограничений на работу с топиками. Внутри транзакции можно писать большие объемы данных в топик, писать в несколько партиций, читать многими консьюмерами. Тем не ме
То, что данные станут видимы после завершения транзакции не зависит от того длинная она или короткая.

2024-09-18 09:51 UTC, Alek5andr-Kotov commented on ydb/docs/ru/core/concepts/topic.md
> +Транзакции не вносят дополнительных ограничений на работу с топиками. Внутри транзакции можно писать большие объемы данных в топик, писать в несколько партиций, читать многими консьюмерами. Тем не ме
Наверное, не принципы, а особенности?

2024-09-20 03:32 UTC, blinkov requested changes, later dismissed

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +Транзакции с участием топиков поддержаны в C++ SDK и Java SDK (см. [Работа с топиками в SDK] (../reference/ydb-sdk/topic.md)).
это уточнение про C++ и Java явно будем забывать апдейтить при появлении этой фичи в других SDK, так что предлагаю сразу его тут не писать

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +{{ ydb-short-name }} поддерживает работу с топиками в рамках транзакции. Операции с топиками в транзакции всегда выполняются с уровнем *Serialazable*.
аналогичный комментарий про serializable + ещё опечатка в нём

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
```suggestion
## Транзакции с участием топиков {#topic-transactions}

{{ ydb-short-name }} поддерживает работу с топиками в рамках [транзакций](./transactions.md). Операции с топиками в транзакции всегда выполняются с уровнем *Serializable*.

### Транзакционное чтение из топика {#topic-transactions-read}

Данные в топиках не изменяются при чтении. Поэтому при чтении из топика в транзакции непосредственно транзакционной операцией является только изменение [смещения](./glossary.md#offset). SDK скрывают от пользователя эти детали, и при транзакционном чтении из топика через SDK одновременно выполняется чтение и изменение смещения. Фактически смещение будет изменено в момент коммита транзакции.
```

Если хотите популяризировать слово «офсет», то тогда надо глоссарий ещё проапдейтить.

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +Тем не менее рекомендовано так подбирать режим работы с транзакциями, чтобы учесть особенности транзакционной работы с топиками: данные публикуются в момент коммита транзакции. То есть если транзакци
```suggestion
### Транзакционная запись в топик {#topic-transactions-write}

При транзакционной записи в топик данные до коммита сохраняются вне партиции, а затем публикуются (становятся видимыми) в момент коммита транзакции. При этом данные будут добавлены в конец партиции в последовательные офсеты. Видимости собственных изменений в транзакциях с топиками не предусмотрено.

### Ограничения при работе с топиками в транзакции {#topic-transactions-constraints}

Транзакции не накладывают дополнительных ограничений на работу с топиками. Внутри транзакции можно записывать большие объёмы данных в топик, писать в несколько партиций и читать несколькими консьюмерами.

Тем не менее рекомендуется выбирать режим работы с транзакциями, учитывая особенности транзакционной работы с топиками: данные публикуются в момент коммита транзакции. То есть если транзакция длительная, данные станут видимыми только спустя значительное время.
```

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +При транзакционной записи в топик данные до коммита сохраняются в топике вне партиции и затем публикуются (становятся видимыми) в момент коммита транзакции. При этом в момент комита транзакции данные
Неоднозначно читается последняя фраза: если в транзакции начал участвовать топик, то и из таблиц видимость собственных изменений перестаёт работать? Надеюсь нет, и речь только про то, что нельзя прочитать именно из топика то, что было в него записано в этой же транзакции — тогда эту фразу надо преформулировать.

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
Тут не очень понятно ожидать ли чего-то типа снэпшота с этими оффсетами, или он всё равно только один на консьюмера. Например:

1. Один и тот же консьюмер открыл две транзакции А и Б.
2. В транзакции А прочитал 1 сообщение, в транзакции Б прочитал 10 сообщений.
3. Закоммитил транзакцию Б.
4. Читает ещё одно сообщение в транзакции А — он прочитает 2-е или 11-е сообщение?

Или другой пример:

1. Один и тот же консьюмер открыл две транзакции А и Б.
2. По очереди прочитал из каждой по 5 сообщений так, что в транзакции А оказались нечётные сообщения, а в транзакции Б — чётные.
3. Закоммитил транзакцию А, а транзакция Б по каким-то причинам откатилась — что произойдёт с оффсетами и чётными сообщениями?

Вероятно параллельная работа с несколькими транзакциями из одного консьюмера является скорее антипаттерном, но это надо явно объяснить.

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
Два последних предложения не стыкуются другом: чтение и коммит могут происходить не одновременно (прочитал, как-то обработал, закоммитил), в предпоследнем предложении написано, что смещение сдвигается одновременно с чтением, а в последнем — что с коммитом. По логике должно быть с коммитом, тогда предпоследнее предложение надо переделать.

2024-09-20 03:32 UTC, blinkov commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
Также пока писал другие комментарии понял, что сам пишу скорее оффсет с двумя ф как в английском — видимо стоит оба варианта в глоссарий добавлять тогда как альтернативные, чтоб поиску было проще находить.

2024-09-20 09:44 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +{{ ydb-short-name }} поддерживает транзакции с участием таблиц и/или топиков. Таким образом, в рамках транзакции можно производить операции чтения и записи как с таблицами, так и с топиками. Операции
Поддержали все возможные комбинации чтений/записей с произвольным ассортиментом обычных таблиц (не колоночных) и топиков. Несколько топиков без таблиц можно.

Допишу, что колоночные пока нет

2024-09-20 09:50 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
я сама бы писала оффсет, как в английском тоже, но взяла отсюда
https://ydb.tech/docs/ru/concepts/topic#offset

получается, разночтение с глоссарием, уберу (оставлю всюду смещение/оффсет)

2024-09-20 09:51 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
"комит" - тоже я бы писала коммит, но Леша упорно всюду с одной м, я подстроилась уже. Соглашусь, что "коммит" лучше, поправлю везде.

2024-09-20 10:06 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
тут имеется в виду не коммит обработанных данных, а коммит оффсета при чтении. Переормулирую

2024-09-20 10:09 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +Транзакции с участием топиков поддержаны в C++ SDK и Java SDK (см. [Работа с топиками в SDK] (../reference/ydb-sdk/topic.md)).
ok

2024-09-20 10:10 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +{{ ydb-short-name }} поддерживает работу с топиками в рамках транзакции. Операции с топиками в транзакции всегда выполняются с уровнем *Serialazable*.
После консультаций с Лешей Н убрала про уровень транхкаций в отпиках serialazable вообще

2024-09-20 10:25 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +{{ ydb-short-name }} поддерживает транзакции с участием таблиц и/или топиков. Таким образом, в рамках транзакции можно производить операции чтения и записи как с таблицами, так и с топиками. Операции
убрала про serialazable вообще по совету Леши Н

2024-09-20 10:40 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +При транзакционной записи в топик данные до коммита сохраняются в топике вне партиции и затем публикуются (становятся видимыми) в момент коммита транзакции. При этом в момент комита транзакции данные
fixed

2024-09-20 10:45 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
Или другой пример:

Один и тот же консьюмер открыл две транзакции А и Б.
По очереди прочитал из каждой по 5 сообщений так, что в транзакции А оказались нечётные сообщения, а в транзакции Б — чётные.
Закоммитил транзакцию А, а транзакция Б по каким-то причинам откатилась — что произойдёт с оффсетами и чётными сообщениями?

коммит оффсета при чтении происходит в момент коммита транзакции, у тебя не получится в одной транзакции прочитать четные, в другой нечетные, обе незакомиченные транзакции считают, что оффсет тот, с которого они начали

2024-09-20 11:05 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
fixed

2024-09-20 11:33 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
Пример 1:

Читатель один, сессия чтения одна.

В транзакции А читает сообщение 1, в транзакции Б читает сообщение с 2 по 10, пытается закоммитить, коммит фейлится, потому что он коммитит не с 1-го)

Пример 2:

При попытке коммита А будет ошибка. Потому что не получается последовательный диапазон оффсетов.

2024-09-20 11:34 UTC, ElenaAfina commented on ydb/docs/ru/core/concepts/topic.md
> +Данные в топиках не меняются при чтении из топика. Поэтому при чтении в транзакции из топика непосредственно транзакционной операцией является только изменение офсета. SDK скрывает от пользователя де
предлагаю сюда это не пихать (тут общеописательная дока про транзакции), после скейла отдельно распишу разные варианты сценариев с транзакциями топики/таблицы, чтобы сделать более наглядные варианты, завела тикет https://st.yandex-team.ru/YDBDOCS-832

2024-09-23 03:44 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +Подробнее о транзакционных операциях при работе с топиками см. в [{#T}] (../topic.md#topic-transactions) и [{#T}] (../reference/ydb-sdk/topic.md).
```suggestion
Подробнее о транзакционных операциях при работе с топиками см. в [{#T}](../topic.md#topic-transactions) и [{#T}](../reference/ydb-sdk/topic.md).
```

2024-09-23 06:17 UTC, blinkov commented on ydb/docs/ru/core/concepts/_includes/transactions.md
> +Подробнее о транзакционных операциях при работе с топиками см. в [{#T}](../topic.md#topic-transactions) и [{#T}](../reference/ydb-sdk/topic.md).
```suggestion
Подробнее о транзакционных операциях при работе с топиками см. в [{#T}](../topic.md#topic-transactions) и [{#T}](../../reference/ydb-sdk/topic.md).
```

2024-09-23 06:59 UTC, fomichev3000 approved these changes
Раздел "Транзакционное чтение из топиков" как-то криво выглядит... вроде по сути понятно, но формулировки сложно читаются

2024-09-23 06:59 UTC, merged