YQ-3617: fix GROUP BY HOP + AS_TABLE
ydb-platform/ydb pull request #9370
Opened 2024-09-17 11:42 UTC by APozdniakov

### Changelog entry 

GROUP BY HOP now supports static inputs like AS_TABLE

### Changelog category 

* New feature

2024-09-23 10:23 UTC, uzhastik approved these changes, later dismissed

2024-09-23 11:16 UTC, uzhastik commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +        if (auto hopping = RewriteAsHoppingWindow(node, ctx); hopping) {
здесь не нужна ;, упрощай условие

2024-09-23 11:17 UTC, uzhastik commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +            YQL_CLOG(DEBUG, Core) << "RewriteAggregate";
тут можно вывести что-то более релевантное? при чем тут RewriteAggregate ?

2024-09-23 11:23 UTC, uzhastik commented on ydb/library/yql/core/yql_opt_hopping.h
> +    ui64 Hop;
можно скалярные поля сразу проинициализировать? не хочется потом сражаться с рандомными багами из-за чтения мусора

2024-09-23 11:42 UTC, APozdniakov commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +            YQL_CLOG(DEBUG, Core) << "RewriteAggregate";
Печатаю название примененной оптимизации с названием как у dq-шной. Мне кажется очень релевантно + строка лога легко ищется по коду

2024-09-23 12:58 UTC, APozdniakov commented on ydb/library/yql/core/yql_opt_hopping.h
> +    ui64 Hop;
Инстанс структуры создается только в ExpandHoppingTraits. Эта функция и определение класса были перемещены без модификаций из dq_opt_hopping.cpp, так что я считаю, что надо оставить так

2024-10-01 09:31 UTC, uzhastik approved these changes, later dismissed

2024-10-01 10:44 UTC, vitstn commented on ydb/library/yql/core/yql_opt_utils.h
> +void ExtractSimpleKeys(const TExprNode* keySelectorBody, const TExprNode* keySelectorArg, std::vector<std::string_view>& columns);
зачем это изменение ради изменения?

2024-10-01 10:44 UTC, vitstn requested changes
!

2024-10-01 11:41 UTC, APozdniakov commented on ydb/library/yql/core/yql_opt_utils.h
> +void ExtractSimpleKeys(const TExprNode* keySelectorBody, const TExprNode* keySelectorArg, std::vector<std::string_view>& columns);
В моих изменениях в `ydb/library/yql/core/yql_expr_constraint.cpp` используются `AddConstraint` и `ExtractSimpleKeys`. Первая функция принимает `std::vector`, а вторая - `TVector`. Не хотелось перекладывать из одного типа вектора в другой, а `ExtractSimpleKeys` нигде не используется в отличие от `AddConstraint`

2024-10-01 12:37 UTC, uzhastik commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +    // if (keysDescription.NeedPickle()) {
напиши разъясняющий коммент к закоменченному фрагменту кода

2024-10-01 15:47 UTC, vitstn commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +            YQL_CLOG(DEBUG, Core) << "RewriteAggregate";
RewriteAsHoppingWindow тут более уместно

2024-10-01 15:50 UTC, rvu1024 commented on ydb/library/yql/core/yql_expr_constraint.cpp
> +        ExtractKeys(*keySelectorLambda, columns);
Посмотри тут https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/core/yql_expr_constraint.cpp#L2709, как извлекать ключи из лямбды. ExtractKeys уже не используется и нужно его выпилить

2024-10-01 15:53 UTC, rvu1024 commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +            YQL_CLOG(DEBUG, Core) << "RewriteAggregate";
Я тоже за более релевантное сообщение. Добавь туда что-нибудь про hopping

2024-10-01 15:55 UTC, rvu1024 commented on ydb/library/yql/core/common_opt/yql_co_simple1.cpp
> +    // if (keysDescription.NeedPickle()) {
Что не так с констрейнтами в TCoMap?
В общем случае они не проносятся через Pickle, но ты можешь в свой код добавить Assume...

2024-10-04 14:16 UTC, rvu1024 commented on ydb/library/yql/core/yql_opt_utils.cpp
> +void ExtractSimpleKeys(const TExprNode* keySelectorBody, const TExprNode* keySelectorArg, std::vector<std::string_view>& columns) {
уже не актуальное изменение

2024-10-07 10:44 UTC, uzhastik approved these changes

2024-10-07 14:05 UTC, rvu1024 approved these changes

2024-10-07 14:20 UTC, vitstn approved these changes

2024-10-07 14:22 UTC, merged