Highlight YQL using common lexer in YDB CLI interactive mode
ydb-platform/ydb pull request #9404
Opened 2024-09-17 17:07 UTC by vityaman

### Changelog entry 

Highlight YQL using common lexer in YDB CLI interactive mode

### Changelog category 

* Improvement

### Additional information

- Added `StartIndex` field to `TParsedToken`.
- Supress ANTLR4 stderr messages on lexer errors
- Migrated syntax highlighting to `ILexer`

2024-09-17 17:12 UTC, vityaman commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +            , Lexer(MakeLexer(/* ansi = */ false, /* antlr4 = */ true))
ANSI is not yet supported, but it is a step forward.

2024-09-17 17:12 UTC, vityaman commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                   token.Name == "ANALYZE" ||
I am not sure what is better: this solution or a huge regex. Huge regex will be more concise, but we can lose some optimizations benefits (but regex is optimized too).

2024-09-17 17:12 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr4/proto_ast_antlr4.h
> +            Lexer.removeErrorListeners(); // supress stderr messages
It prints messages to stderr on invalid inputs.

2024-09-17 17:12 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    ui32 StartIndex;
Need this for highlighting. Can make the performance worse as struct size grows.

2024-09-17 17:17 UTC, vityaman commented
Interesting fact. I tried to use regex from the `rewrapper` instead of `std::regex`, but it compiles for ~60 seconds.

https://github.com/ydb-platform/ydb/tree/main/ydb/library/rewrapper

2024-09-23 19:21 UTC, nepal requested changes

2024-09-23 19:21 UTC, nepal commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    ui32 StartIndex;
StartIndex не очень уместное название - я бы назвал RawPos в стиле LinePos. Т.е. сквозная позиция в тексте запроса (starts from 0).
И еще такой момент - надо убедиться что antlr3/4 ведут себя одинаково. А именно - это позиции в байтах или в символах? Проверить надо на запросе с utf8 символами (например в комментариях)

2024-09-23 19:21 UTC, nepal commented on ydb/library/yql/parser/proto_ast/antlr4/proto_ast_antlr4.h
> +            Lexer.removeErrorListeners(); // supress stderr messages
Мы тут случайно не удаляем лишнего? Дело в том, что (по крайней мере в парсере) мы создаем специальный error listener который формирует TIssue. Надо проверить TIssue собираются

2024-09-23 19:21 UTC, nepal commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                   token.Name == "ANALYZE" ||
Тут предикат на самом деле очень простой - token.Name == to_upper(token.Conent)

2024-09-25 07:51 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +bool IsProbablyKeyword(const TParsedToken& token);
Вынес функцию для проверки ключевого слова в общий модуль лексера, чтобы переиспользовать ее и для подсветки, и для форматирования.

2024-09-25 07:51 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    ui32 StopPos;  // starts from 0
Решил такие позиции прокидывать. Можно избавиться от `StopPos`, вычисляя его по формуле `StopPos = token.StartPos + GetNumberOfUTF8Chars(token.Content)`. Но тогда будем делать эту операцию дважды, так как в лексер все равно проходится по всем симолам, чтобы вычислить `StartPos`.

2024-09-25 07:51 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +
Тут мне не очень нравится код, но в функцию отдельную его как будто не вынести, так как он и читает, и пишет в переменные цикла: `prev`, `pos`. Можно, конечно, сделать их полями класса, тогда получится аккуратнее написать (все равно класс не `Thread-Safe`).

2024-09-25 07:51 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr4/proto_ast_antlr4.h
> +                Lexer.addErrorListener(&listener);
Раньше лексер вообще не выдавал `Issues`. Теперь выдает.

2024-09-25 09:58 UTC, nepal requested changes, later dismissed

2024-09-25 09:58 UTC, nepal commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    // Position of first and last token symbol
Эти добавления вообще не нужны для решения твоей задачи. Ты хочешь раскрасить SQL запрос.
Для этого надо получить список токенов запроса, принять по каждому токену решение каким цветом этот токен должен быть раскрашен, взять его Content, раскрасить его и положить в выходной буфер.
Для корректного запроса есть инвариант - исходный текст запроса может быть получен конкатенацией всех Content у токенов.

Соответственно текущую позицию в байтах можно трекать путем сложения длин всех Content.

Если запрос лексически некорректный, можно все равно раскрасить валидный префикс, а хвост просто оставить нераскрашенным

Для этого все эти изменения в лексерах не нужны.
Что я хочу увидеть 
1) фикс errorListener надо оставить. На это изменение надо написать тест (что появляется ошибка на некорректном запроса типа
```
select "aaaa
```
2) тесты должны быть в parser/lexer_common/ut

2024-09-25 13:28 UTC, vityaman commented on ydb/library/yql/sql/v1/SQLv1Antlr4.g.in
> +fragment BACKTICK:      '`';
Можно считать, что в `YQL` нет таких токенов, так как они не используются в продукциях, а только для составления других токенов. Теперь на строке `"\"` оба парсера ведут себя схожим образом.

2024-09-25 13:28 UTC, vityaman commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                const std::ptrdiff_t stop = Position;
Как же все было просто 🥲

2024-09-25 13:30 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    // Position of first and last token symbol
Реализовал подсветку через накопление количества символов в `Content`. Я почему-то думал, что `WS` скипается...

Фикс `errorListener` оставил, тестики те же оставил, добавил ваш случай.

Тесты переместил.

2024-09-26 12:05 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +    ui32 RawPos = 0;  // starts from 0
Все-таки вернул `RawPos`, но убрал `StopPos`, делегировав его вычисление клиентскому коду.

Сделал я это из-за поведения лексера. Дело в том, что ANTLR при встрече невалидного токена, пытается восстановиться, чтобы продолжить разбор далее и выплюнуть нам как можно больше ошибок, вместо того, чтобы остановиться при первой же ошибке. При этом он просто пропускает невалидные символы, как будто их вовсе не было - это полезно, когда мы используем лексер вместе с парсером, тогда второй сможет выдать побольше диагностики.

Для решения проблемы подхода с накоплением контента, в голову пришли следющие идеи.

1. Совсем отключить стратегию восстановления после ошибок в лексере. С одной стороны, мы сможем быть уверены, что не пропустили ни одного токена на префиксе. С другой стороны, получим меньше сообщений об ошибках и не раскрасим последующие токены вообще никак (в то время, когда при восстановлении мы все-таки имеем шанс раскрасить).

2. В интернетах предлагается добавить специальный токен `UNKNOWN`, который будет матчится со всем в последнюю очередь. Вижу, что в `antlr4` можно переопределить метод `emit` в котором кроме логики из оригинального лексера дергать за какие-нибудь ручки для выставления ошибок, если мы встретили `UNKNOWN`. В `antlr3` не нашел места, куда можно поместить свой фрагмент кода.

Также есть такая интуитивная мысль. Можно приглядеться к способу восстановления в лексере (`recover`) можно в `antlr4`, переопределив метод, а в `antlr3` он не является виртуальным. Именно проблему с пропущеными токенами он не решит, но позволит нам попробовать лучше восстанавливаться от ошибок, чтобы улучшить подсветку в каких-нибудь случаях...

2024-09-26 17:49 UTC, vityaman commented
Сообщения при некоторых синтаксических ошибках теперь выглядят иначе.

2024-10-07 11:17 UTC, vitstn commented on ydb/library/yql/parser/lexer_common/lexer.h
> +bool IsProbablyKeyword(const TParsedToken& token);
такая функция не может жить в папке parser, она прикладная и должна жить в sql

2024-10-07 11:19 UTC, vitstn commented on ydb/library/yql/parser/lexer_common/ut/lexer_ut.cpp
> +    UNIT_ASSERT_EQUAL(lhs.Name, rhs.Name);
такие проверки должны использовать UNIT_ASSERT_VALUES_EQUAL чтобы при сбое вывести оба значения

2024-10-07 11:21 UTC, vitstn commented on ydb/library/yql/parser/lexer_common/ut/lexer_ut.cpp
> +        auto lexer3 = MakeLexer(/* ansi = */ false, /* antlr4 = */ false);
не нужно писать код с antlr3, мы его будет удалять в ближайшем будущем

2024-10-07 11:23 UTC, vitstn commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
почему это нельзя сделать снаружи? line + linepos дает достаточно информации

2024-10-08 08:18 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/lexer.h
> +bool IsProbablyKeyword(const TParsedToken& token);
Перенес эту функцию в `sql/v1/lexer`.

2024-10-08 08:19 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/ut/lexer_ut.cpp
> +    UNIT_ASSERT_EQUAL(lhs.Name, rhs.Name);
Заменил `UNIT_ASSERT_EQUAL` на `UNIT_ASSERT_VALUES_EQUAL` для сравнения `Name` и `Content`.

2024-10-08 08:26 UTC, vityaman commented on ydb/library/yql/parser/lexer_common/ut/lexer_ut.cpp
> +        auto lexer3 = MakeLexer(/* ansi = */ false, /* antlr4 = */ false);
Насколько я понимаю, `antlr4` сейчас работает под feature flag. Получается, что есть ненулевая вероятность, что в какой-то момент мы захотим откатиться на `antlr3`. Если мы перестанем писать тесты на `antlr3` еще до удаления его из кодовой базы, то мы рискуем что-то сломать в `antlr3` и реализуется этот риск только в момент при откате `antlr4`.

Кроме того, данные тесты подразумеваются как сравнительные. С их помощью, я исследовал разницу в поведении двух лексеров. Они, с одной стороны, гарантируют в некоторой степени схожесть поведений (на что полезно надеяться при откате с `antlr4` на `antlr3`), а, с другой стороны, документируют незначительные различия.

Кажется, что при выпиливании `antlr3` не составит большого труда удалить ссылки на него отсюда.

2024-10-08 08:44 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
Если под "снаружи" вы понимаете место применения парсера (то есть разбиение на токены для подсветки синтаксиса), то установить `RawPos` из `(Line, LinePos)` будет проблематично.

Для реализации этой логики на стороне клиента придется брать текст, разбивать его по символам переноса строки при помощи `TLineSplitter`, вычислять префиксные суммы какие-нибудь, чтобы по номеру строки (`Line`) получать количество символов до нее, к которому мы прибавим `LinePos`. Конечно, можно так сделать, построить отображение `f(Text): (Line, LinePos) -> (RawPos)`, теперь даже понятно, как это сделать.

Однако, в то же время наш `RawPos = StartIndex` 4ого антлера. Он и так кладет это значение в токен при парсинге. Таким образом, используя свое отображение, мы сделаем двойную работу.

2024-10-08 09:13 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
Вообще, я не очень понимаю, почему мы так сражаемся за одно поле в структуре.

Я понимаю, что возрастет оверхед по памяти на 4-8 байт (из-за выравнивания, мб) для каждого токена. Например, если к нам поступают запросы на ~128 токенов, количество которых умножаются на 2 из-за пробельных токенов, мы потратим на `128 * 2 * 8 = 2048 = 2KB` больше на каждый запрос. Такой большой запрос будет, наверное, символов на ~1024, из которых почти все ASCII, так что давайте оценим его размер в 1KB. Кажется, что это не очень, но, кстати, все токены мы собираем только для форматирования и подсветки синтаксиса, парсер под нагрузкой использует `onNextToken`.

Еще я понимаю, что мы таким образом усложняем код в `antlr3` лексере (а в `antlr4` все тривиально делается), но иначе мы бы усложнили код где-то в другом месте. У нас есть сгенерированный лексер, который правильно и скрыто от нас решает задачу выставления `RawPos`, но мы хотим отказаться от результата его работы и написать свое решение ровно этой же задачи.

Также я понимаю, что иметь `RawPos` в общем лексере не очень хочется, потому что это значение никому не нужно, кроме CLI с подсветкой. А CLI не очень-то `Line` и `LinePos` нужны, но она ими воспользоваться, чтобы вывести из них `RawPos` простым, но нетривиальным способом.

2024-10-08 09:19 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
Также тут же отвечу на вопрос "зачем тебе RawPos в символах, а не в байтах. По смыслу байтов должно быть достаточно". Для подсветки букв я использую API, в котром нужно установить цвет каждому **символу** по его индексу в тексте. Если я буду получать позицию байта, то мне придется ее конвертировать в позицию символа, для чего также нужно исследовать весь префикс текста, так как мы живем в мире UTF-8.

2024-10-08 09:29 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
Что-то я закопался... 

Ладно. Владея исходным текстом запроса и пары `(Line, LinePos)`, мы действительно можем вывести `RawPos`, потому иметь его полем `TParsedToken` избыточно, а, кроме того, еще и пагубно для производительности системы. 

Предлагаю сделать следующее.

1. Убрать `RawPos` из `TParsedToken`.

2. Где-то реализовать отображение `f(Text, "antlr4") -> (Line, LinePos) -> RawPos`. Отображение будет поддерживать только `antlr4`.

3. Заиспользовать его для подсветки синтаксиса.

Вопросы.

1. Норм план?

2. В какой модуль положить обсуждаемое отображение?

2024-10-09 08:27 UTC, vityaman commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
@vitstn, @nepal, что думаете?

2024-10-14 10:42 UTC, vitstn commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +                    const char* start = reinterpret_cast<const char*>(token->get_startIndex());
нормальный план.
отображение можно вынести в код где выполняется расцветка

2024-10-18 08:52 UTC, vityaman commented
- Вынес `TLineSplitter` в модуль `util/stream`, чтобы разделять его между модулем для подсветки синтаксиса и чем-то про `pg_dump`.
- Удалил `TFixedStringStream` так как он дублирует поведение `TStringStream`. Только пришлось добавить метод для возврата указателя на начальное положение.
- Сделал отображение `(Line, LinePos) -> RawPos` и заиспользовал его для подсветки.

2024-10-21 10:23 UTC, vitstn commented on ydb/library/yql/parser/proto_ast/antlr3/proto_ast_antlr3.h
> +#include <util/charset/utf8.h>
не используется

2024-10-21 10:28 UTC, vitstn commented on ydb/library/yql/udfs/common/file/file_udf.cpp
не надо трогать file udf в том же PR, что и изменения в парсере

они разделены ABI и могут развиваться отдельно

2024-10-21 10:28 UTC, vitstn requested changes
!

2024-10-21 11:36 UTC, vityaman commented
Еще я изменил `util`, а этого делать нельзя, потому унесу `TLineSplitter` куда-нибудь в папку `ydb`.

2024-10-22 09:07 UTC, vityaman commented
@vitstn, внес почти все правки.

1. Убрал неиспользуемую зависимость от `utf8` в `antlr3` парсере.

2. Заменил эмоджи на escape последовательности.

3. Унес `TLineSplitter` из `util` в `ydb/library/yql/utils`. Я настаиваю на том, чтобы все-таки этот класс переиспользовать и для подсветки, и для `udfs`, потому что иначе явная копипаста будет. Не могу же я тянуть этот класс прямо из хэдера `udfs` в подсветку. 

4. Не очень понял аргумент про разделение ABI. Можете его раскрыть, в чем проблема? Вообще, этот MR вообще по-хорошему нужно побить на несколько: багфикс с сообщениями об ошибках от лексера, изменения в грамматике, вынос `TLineSplitter` в коммоны и только потом подсветка.

5. Убрал добавленный в `TStringStream` из пакета `util` метод `Reset`. Вообще, кажется, что можно реализовать `Reset` вне этого класса при помощи очень странных телодвижений.

```cpp
void Reset(TStringStream& stream) {
  TStringStream dummy(std::move(stream.Str()));
  stream = std::move(dummy);
}
```

Я не нашел хорошего места, куда бы можно было пристроить эту процедуру, потому просто вернул `TFixedStringStream`, чтобы меньше с вами спорить в рамках данного MR. Я бы предложил изменение с выпиливанием `TFixedStringStream` и переиспользованием `TStringStream` в другом MR, если вам это нужно. Вам оно нужно?

2024-10-22 15:00 UTC, vitstn commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +    UNIT_ASSERT_EQUAL(lhs.Line, rhs.Line);
UNIT_ASSERT_VALUES_EQUAL

2024-10-22 15:02 UTC, vitstn commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +                "FROM ydb -- главная таблица 数据库 \n"
это yql код, слово ydb тут неуместно, поставьте просто table

2024-10-22 15:02 UTC, vitstn commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +        UNIT_ASSERT_EQUAL(input.size(), expected.size());
UNIT_ASSERT_VALUES_EQUAL

2024-10-23 15:19 UTC, vityaman commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +                "FROM ydb -- главная таблица 数据库 \n"
Заменил `ydb` на `table`

2024-10-23 15:20 UTC, vityaman commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +    UNIT_ASSERT_EQUAL(lhs.size(), rhs.size());
Done

2024-10-23 15:20 UTC, vityaman commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +    UNIT_ASSERT_EQUAL(lhs.Line, rhs.Line);
Done

2024-10-23 15:20 UTC, vityaman commented on ydb/library/yql/sql/v1/lexer/lexer_ut.cpp
> +        UNIT_ASSERT_EQUAL(input.size(), expected.size());
Done

2024-10-23 15:23 UTC, vityaman commented
@vitstn, пофиксил проблемы

- Заменил `UNIT_ASSERT_EQUAL` на `UNIT_ASSERT_VALUES_EQUAL`. А зачем нужен `UNIT_ASSERT_EQUAL`, если `UNIT_ASSERT_VALUES_EQUAL` умеет то же самое, но сообщает об ошибках лучше.

- Таблицу в тесте переименовал.

2024-10-23 17:18 UTC, vitstn commented
> @vitstn, пофиксил проблемы
> 
> * Заменил `UNIT_ASSERT_EQUAL` на `UNIT_ASSERT_VALUES_EQUAL`. А зачем нужен `UNIT_ASSERT_EQUAL`, если `UNIT_ASSERT_VALUES_EQUAL` умеет то же самое, но сообщает об ошибках лучше.

он нужен только тогда, когда объект нельзя вывести в поток, но у него есть оператор ==

2024-10-23 17:20 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        TString a2(R"foo(<main>:1:16: Error: Unknown cluster: edar
тут стала плохая ошибка, раньше было прикладное про unknown cluster

2024-10-23 17:20 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        UNIT_ASSERT_NO_DIFF(Err2Str(res1), "<main>:1:12: Error: mismatched input 'b' expecting {<EOF>, ';'}\n");
тоже самое, раньше указывались варианты продолжений

2024-10-23 19:00 UTC, vityaman commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        TString a2(R"foo(<main>:1:16: Error: Unknown cluster: edar
Не согласен. Раньше лексер не сообщал об ошибках (это был баг) и просто пропускал символы, которые сложились в невалидные токены в процессе error recovery, подавая на вход парсеру стрим токенов на самом деле неправильный. Парсер их разбирал и находил имя кластера, как мы видим, но имя без русской буквы `c`, так как она была пропущена лексером. Это ошибка не синтаксическая, а семантическая. Если бы кластер `edar` существовал (и у него был бы атрибут `Input`), то мы бы этот запрос выполнили бы без ошибок. Теперь тут синтаксическая ошибка, что точно лучше (YQL русские буквы вне строк и комментариев, как я понимаю, не должен поддерживать).

Писал об этом тут: https://github.com/ydb-platform/ydb/pull/9404#issuecomment-2377584967

2024-10-23 19:37 UTC, vityaman commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        UNIT_ASSERT_NO_DIFF(Err2Str(res1), "<main>:1:12: Error: mismatched input 'b' expecting {<EOF>, ';'}\n");
Раньше они указывались неверно, так как `'` считался отдельным токеном, что неверно, так как он может быть ~только началом или конца токена строки. 

YQL в данном месте находится между `foo` `foo(<YQL>)foo`. Я вывел, какие запросы поступают на вход парсеру:

```python
Query: $bar = 'a\\'b';
<DOLLAR, $> <ID_PLAIN, bar> <WS,  > <EQUALS, => <WS,  > <STRING_VALUE, 'a\\'> <ID_PLAIN, b> <EOF, <EOF>> 
Query: $bar = "a\\"b";
<DOLLAR, $> <ID_PLAIN, bar> <WS,  > <EQUALS, => <WS,  > <STRING_VALUE, "a\\"> <ID_PLAIN, b> <EOF, <EOF>> 
```

Таким образом, на самом деле мы пытаемся просто скушать строку, начинающуюся с `';`, но находим `EOF`, так и не достигнув завершающей кавычки, потому и сообщаем об ошибке: "Ой, хотели токен скушать, кушали-кушали-кушали, но не смогли доесть. Вот вам префикс, с которым мы работали.".

Так что тут тоже сообщение об ошибке стало лучше -- она теперь летит от лексера, а не от парсера. 

Прошлое сообщение было неверно, так как составлено парсером, который видит не тот поток токенов, а потому может ввести пользователя в заблуждение -- на самом деле вставка ни `<EOF>`, ни `;` не поможет. Вернее, возможно, поможет, потому что из-за того бага он действительно мог бы принять какой-то неверный инпут. В реальности нам не `EOF` нужен и не `;` -- нам кавычку бы закрыть.

Гипотеза. Раньше парсер получал на вход строку, букву б и незаконченную строку. Незаконченную строку он скипал, потому что recovery, а букву б не ожидал.

2024-10-23 19:37 UTC, vityaman commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        UNIT_ASSERT_NO_DIFF(Err2Str(res1), "<main>:1:12: Error: mismatched input 'b' expecting {<EOF>, ';'}\n");
Если сделать `QUOTE_(SINGLE|DOUBLE)` не фрагментами, то сообщение об ошибке вернется:

```python
<main>:1:(12|13): Error: (mismatched|token) (input|recognition) ('b'|error) (expecting|at:) ({<EOF>, |')';'(}|)
```

Но поток токенов парсер видел совсем другой.

```python
Query: $bar = 'a\\'b';
<DOLLAR, $> <ID_PLAIN, bar> <WS,  > <EQUALS, => <WS,  > <STRING_VALUE, 'a\\'> <ID_PLAIN, b> <QUOTE_SINGLE, '> <SEMICOLON, ;> <EOF, <EOF>> 
Query: $bar = "a\\"b";
<DOLLAR, $> <ID_PLAIN, bar> <WS,  > <EQUALS, => <WS,  > <STRING_VALUE, "a\\"> <ID_PLAIN, b> <QUOTE_DOUBLE, "> <SEMICOLON, ;> <EOF, <EOF>>
```

2024-10-24 17:30 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        TString a2(R"foo(<main>:1:16: Error: Unknown cluster: edar
то, что стрим неправильный это конечно плохо.

тогда конечно лучше ошибка уровня лексера

2024-10-24 17:34 UTC, vitstn approved these changes

2024-10-24 17:38 UTC, vitstn commented on ydb/library/yql/sql/v1/sql_ut_antlr4.cpp
> -        UNIT_ASSERT_NO_DIFF(Err2Str(res1), "<main>:1:12: Error: mismatched input 'b' expecting {<EOF>, ';'}\n");
из доки:

Идентификаторы – это токены, которые идентифицируют имена таблиц, колонок и других объектов в YQL. Идентификаторы в YQL всегда регистрозависимы.
Идентификатор может быть записан в теле программы без специального оформления, если он:

Не является ключевым словом
Начинается с латинской буквы или подчеркивания
Последующими символами могут быть латинская буква, подчеркивание или цифра

так что русские буквы только в комментариях или строках

2024-10-25 06:54 UTC, pnv1 approved these changes

2024-10-25 07:00 UTC, merged