Update changelog server.md RU for 24.1
ydb-platform/ydb pull request #9462
Opened 2024-09-18 17:43 UTC by katidisergei

### Changelog entry 

Update changelog server.md RU for 24.1

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-09-19 18:45 UTC, zinal requested changes

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Улучшена производительность](https://github.com/ydb-platform/ydb/pull/1576) в запросах возвращающих однострочные ответы.
Поскольку мы заявляем появление QueryService, оптимизации производительности в нём можно не упоминать

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Оптимизированы](https://github.com/ydb-platform/ydb/pull/1837) таймауты сессии от сервера до клиента, ранее таймаут составлял 5 секунд, что в худшем случае приводило к определению неработающего кл
```suggestion
* [Оптимизированы](https://github.com/ydb-platform/ydb/pull/1837) таймауты сессий сервиса координации от сервера до клиента. Ранее таймаут составлял 5 секунд, что в худшем случае приводило к определению неработающего клиента (и освобождению удерживаемых им ресурсов) в течение 10 секунд. В новой версии время проверки зависит от времени ожидания сеанса, что приводит к более быстрому реагированию при смене лидера или захвате распределенных блокировок.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2391) потребление CPU schemeshard репликами особенно при обработке быстрых обновлений для таблиц с большим количеством разделов.
```suggestion
* [Оптимизировано](https://github.com/ydb-platform/ydb/pull/2391) потребление CPU SchemeShard репликами, особенно при обработке быстрых обновлений для таблиц с большим количеством разделов. 
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/4105) ошибка приводящая к нарушению порядка передаваемых изменений при асинхронной репликации данных.
Выше мы заявляем асинхронную репликацию как новую функцию. Можно исключить.

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/4597) потенциальная взаимоблокировка между запросом записей и их отправкой.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/4597) потенциальная взаимоблокировка между получением записей CDC и их отправкой.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2056) прблема потери очереди задач медиатора при переподключении медиатора, исправление позволяет обработать очередь задач медиатора при ресинх
Ошибка специфична для 24-1, исправлена для 24-1 же. Можно не упоминать в заметках к выпуску версии 24-1

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2624) проблема, когда при включенных и используемых волатильных транзакциях, возвращался успешный результат коммита транзакции которая на самом
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2624) редко возникающая ошибка, когда при включенных и используемых волатильных транзакциях возвращался успешный результат подтверждения транзакции, которая на самом деле завершилась неудачей.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Устранена](https://github.com/ydb-platform/ydb/pull/2839) проблема с блокировками в итераторе чтения при игнорировании пустых результатов.
```suggestion
* [Устранена](https://github.com/ydb-platform/ydb/pull/2839) редко возникающая ошибка, приводившая к потере установленных блокировок и успешному подтверждению транзакций, которые должны были завершиться ошибкой TLI.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/3074) проблема когда немедленное (но локально обновлённое до повторяемого) чтение вызывало путаницу зависимостей между одновременными записями,
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3074) редкая ошибка, приводящая к возможному нарушению гарантий целостности данных при конкурентном записи и чтении данных по определенному ключу.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/4979) ошибка когда после переименования таблицы могли остаться незафиксированные изменения. В худшем случае постоянные блокировки могли восстан
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/4979) редкая ошибка, которая могла привести к аварийному завершению процессов базы данных при наличии неподтвержденных транзакций над таблицей в момент ее переименования.
```

2024-09-19 18:45 UTC, zinal commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/5081) ошибка когда запрос на обновление таблицы не менял значения в таблице, хотя операция помечена как успешная.
Ошибка специфична для 24-1 и выше. Предлагаю исключить из заметок к выпуску по 24-1.

2024-09-20 08:59 UTC, blinkov requested changes

2024-09-20 08:59 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/3917) ошибка возможного переполнения очереди, CDC резервирует емкость очереди изменений при первоначальном сканировании.
дать ссылку на что такое cdc

2024-09-20 08:59 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2305) проблема, когда shared ноды не возвращались из backend для отображения в Embedded UI для serverless баз.
serverless — облачная специфика, тут ни к чему

2024-09-20 08:59 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/3074) проблема когда немедленное (но локально обновлённое до повторяемого) чтение вызывало путаницу зависимостей между одновременными записями,
про гарантии целостности страшновато звучит — хорошо бы более конкретно сформулировать как оно выглядело с точки зрения пользователя и при каких обстоятельствах

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +**Функциональность:**
Добавил текстом, но описания не смог найти в документации, будет круто если подкинете ссылки

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Реализована](https://ydb.tech/docs/ru/concepts/async-replication) асинхронная репликация между базами данных YDB https://github.com/ydb-platform/ydb/pull/5418
Поправил существующие две

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Улучшена производительность](https://github.com/ydb-platform/ydb/pull/1576) в запросах возвращающих однострочные ответы.
убрал

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/4105) ошибка приводящая к нарушению порядка передаваемых изменений при асинхронной репликации данных.
убрал

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2056) прблема потери очереди задач медиатора при переподключении медиатора, исправление позволяет обработать очередь задач медиатора при ресинх
пока оставлю для количества )

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/5081) ошибка когда запрос на обновление таблицы не менял значения в таблице, хотя операция помечена как успешная.
Все 3 убрать или только https://github.com/ydb-platform/ydb/pull/5081 ?

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены графики для мониторинга основных показателей работы кластера YDB.
уточняю

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/3917) ошибка возможного переполнения очереди, CDC резервирует емкость очереди изменений при первоначальном сканировании.
добавил

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2305) проблема, когда shared ноды не возвращались из backend для отображения в Embedded UI для serverless баз.
убрал

2024-09-24 13:39 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены графики для мониторинга основных показателей работы кластера YDB.
подробностей нет

2024-09-25 02:19 UTC, blinkov submitted a review, later dismissed

2024-09-25 02:19 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлены](https://github.com/ydb-platform/ydb/pull/2374) аномалии с чтением устаревших данных, которые были обнаружены с помощью Jepsen.
```suggestion
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2624) редко возникающая ошибка, когда при включённых и используемых волатильных транзакциях возвращался успешный результат подтверждения транзакции до того, как она была успешно закоммичена.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2839) редко возникающая ошибка, приводившая к потере установленных блокировок и успешному подтверждению транзакций, которые должны были завершиться ошибкой Transaction Locks Invalidated.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3074) редкая ошибка, приводящая к возможному нарушению гарантий целостности данных при конкурентной записи и чтении данных по определённому ключу.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/4343) проблема, из-за которой реплики для чтения переставали обрабатывать запросы.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/4979) редкая ошибка, которая могла привести к аварийному завершению процессов базы данных при наличии неподтверждённых транзакций над таблицей в момент её переименования.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/3632) ошибка в логике определения статуса статической группы, когда статическая группа не помечалась нерабочей, хотя должна была.
* [Исправлена](https://github.com/ydb-platform/ydb/pull/2169) ошибка частичного коммита распределённой транзакции с незакоммиченными изменениями в случае некоторых гонок с рестартами.
* [Исправлены](https://github.com/ydb-platform/ydb/pull/2374) аномалии с чтением устаревших данных, которые были [обнаружены с помощью Jepsen](https://blog.ydb.tech/hardening-ydb-with-jepsen-lessons-learned-e3238a7ef4f2).
```

2024-09-25 02:19 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Реализована поддержка [аутентификации](./concepts/auth.md) и получения перечня групп из внешних LDAP-каталогов.
звучит как-будто аутентификации раньше совсем не было, что явно не так — о чём именно речь?

2024-09-25 02:19 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Разработан сервис QueryService, обеспечивающий возможность выполнения всех типов запросов (DML, DDL) и выборку неограниченных объёмов данных.
```suggestion
* Разработан gRPC сервис QueryService, обеспечивающий возможность выполнения всех типов запросов (DML, DDL) и выборку неограниченных объёмов данных.
```

2024-09-25 02:19 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Реализована поддержка [аутентификации](./concepts/auth.md) и получения перечня групп из внешних LDAP-каталогов.
дока про группы из ldap https://ydb.tech/docs/ru/concepts/auth#poluchenie-grupp

2024-09-25 02:19 UTC, blinkov commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены графики для мониторинга основных показателей работы кластера {{ ydb-short-name }}.
см. в telegram

2024-09-25 17:06 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Реализована поддержка [аутентификации](./concepts/auth.md) и получения перечня групп из внешних LDAP-каталогов.
Поправил формулировку немного

2024-09-25 17:09 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлены графики для мониторинга основных показателей работы кластера {{ ydb-short-name }}.
посмотрел, ниже комент Антона, дописал.

2024-09-25 17:09 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Добавлен дашборд диагностики потребления ресурсов.
Дописал

2024-09-25 17:11 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* Реализована поддержка [аутентификации](./concepts/auth.md) и получения перечня групп из внешних LDAP-каталогов.
Если так добавить, то не на .md  будет заканчиваться + в этой строке есть ссылка на доку где как раз содержится инфа про группы.

2024-09-27 06:08 UTC, fomichev3000 requested changes

2024-09-27 06:08 UTC, fomichev3000 commented on ydb/docs/ru/core/changelog-server.md
> +* [Реализована](https://github.com/ydb-platform/ydb/pull/5418) [асинхронная репликация](./concepts/async-replication.md) между базами данных {{ ydb-short-name }}.
мне кажется, что в 24-1 она нифига не реализвована. Я бы удалил

2024-09-27 06:08 UTC, fomichev3000 commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2624) редко возникающая ошибка, когда при включённых и используемых волатильных транзакциях возвращался успешный результат подтверждения транза
Можно добавить, что волатильные транзакции выключены по умолчанию, находятся в разработке

2024-10-01 07:21 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Реализована](https://github.com/ydb-platform/ydb/pull/5418) [асинхронная репликация](./concepts/async-replication.md) между базами данных {{ ydb-short-name }}.
Убрал. AR появилась  в 24-1-async-replication, затем потребовалось несколько исправлений, анонсировать буду в след версиях.

2024-10-01 07:28 UTC, katidisergei commented on ydb/docs/ru/core/changelog-server.md
> +* [Исправлена](https://github.com/ydb-platform/ydb/pull/2624) редко возникающая ошибка, когда при включённых и используемых волатильных транзакциях возвращался успешный результат подтверждения транза
Поправил

2024-10-02 06:49 UTC, fomichev3000 approved these changes

2024-10-02 06:49 UTC, merged