[backups][yql] add backup-restore statements
ydb-platform/ydb pull request #9473
Opened 2024-09-19 02:51 UTC by Enjection

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-19 16:38 UTC, CyberROFL approved these changes, later dismissed

2024-09-20 10:44 UTC, nepal requested changes

2024-09-20 10:44 UTC, nepal commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                case TOKEN(AT):
А что на счет других добавленных токенов?

2024-09-20 12:16 UTC, Enjection commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                case TOKEN(AT):
Хотел отдельно засинкать + тегнул asmyasnikov, что бы автоматизировали процесс. Если критично могу тут поправить.

2024-09-20 12:33 UTC, nepal approved these changes

2024-09-20 12:33 UTC, nepal commented on ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
> +                case TOKEN(AT):
Ок, можно позже. Этот код собирались переделывать

2024-09-20 12:35 UTC, merged