YQL-17388: fix use-after-free bug in TPgResolvedMultiCall::TListValue::TIterator
ydb-platform/ydb pull request #955
Opened 2024-01-11 20:03 UTC by marsaly79

2024-01-12 17:02 UTC, rvu1024 requested changes

2024-01-12 19:33 UTC, marsaly79 commented on ydb/library/yql/tests/postgresql/cases/aggregates.err
Некоторые - да. Общий подход в плане добавления в прекоммитные тесты работающих регрессионных тестов PG сейчас такой: тесты, которые раньше не работали, могут заработать в результате моих или чьих-то ещё изменений, но, поскольку тему с регрессионными тестами PG веду я и больше никто, в каждом моем pr, который меняет это множество тестов, могут добавляться тесты, которые заработали из-за доработок других участников команды.

2024-01-12 19:35 UTC, marsaly79 commented on ydb/library/yql/tests/postgresql/cases/join.err
> +(TFileError) (File exists) util/system/file.cpp:918: can't open "/tmp/tmp3znkmfbo/a" with mode CreateNew (0x00000003)
Согласен, в отдельном pr можно сделать нормализацию. В данном случае поменялась еще и строка в file.cpp, где возникает ошибка. Пусть будет актуальной

2024-01-15 11:54 UTC, rvu1024 approved these changes

2024-01-15 12:47 UTC, merged