Fix PDisks becoming INACTIVE in normal flow
ydb-platform/ydb pull request #9557
Opened 2024-09-20 10:31 UTC by SammyVimes

### Changelog category 

* Improvement

2024-09-20 10:34 UTC, CyberROFL commented
@SammyVimes will you add any tests?

2024-09-24 09:52 UTC, CyberROFL requested changes

2024-09-24 09:52 UTC, CyberROFL commented on ydb/core/cms/sentinel.cpp
> +    bool isGoodState = IsGoodState(state);
```suggestion
    const bool isGoodState = IsGoodState(state);
```

2024-09-24 09:52 UTC, CyberROFL commented on ydb/core/cms/sentinel.cpp
> +    if (!IsGoodState(state)) {
Почему не:
```suggestion
    if (!isGoodState) {
```
?

2024-09-24 09:52 UTC, CyberROFL commented on ydb/core/cms/sentinel_ut.cpp
> +        auto goodStates = {NKikimrBlobStorage::TPDiskState::InitialFormatRead, NKikimrBlobStorage::TPDiskState::InitialSysLogRead, NKikimrBlobStorage::TPDiskState::InitialCommonLogRead, NKikimrBlobSt
```suggestion
        auto goodStates = {
            NKikimrBlobStorage::TPDiskState::InitialFormatRead,
            NKikimrBlobStorage::TPDiskState::InitialSysLogRead,
            NKikimrBlobStorage::TPDiskState::InitialCommonLogRead,
            NKikimrBlobStorage::TPDiskState::Normal,
        };
```

2024-09-24 09:52 UTC, CyberROFL commented on ydb/core/cms/sentinel_ut.cpp
> +        // If disk is
...?

2024-09-25 15:09 UTC, va-kuznecov submitted a review, later dismissed
LGTM

2024-09-25 16:48 UTC, CyberROFL requested changes

2024-09-25 16:48 UTC, CyberROFL commented on ydb/core/cms/sentinel.cpp
> +    bool IsNodeLocked(ui32 nodeId) {
```suggestion
    bool IsNodeLocked(ui32 nodeId) const {
```

2024-09-25 16:48 UTC, CyberROFL commented on ydb/core/cms/sentinel.cpp
> +        auto& clusterInfo = CmsState->ClusterInfo;
```suggestion
        const auto& clusterInfo = CmsState->ClusterInfo;
```

2024-09-25 16:48 UTC, CyberROFL commented on ydb/core/cms/sentinel.cpp
> +            auto& node = clusterInfo->Node(nodeId);
```suggestion
            const auto& node = clusterInfo->Node(nodeId);
```

2024-09-26 11:38 UTC, CyberROFL submitted a review, later dismissed

2024-09-27 07:56 UTC, va-kuznecov approved these changes

2024-09-27 08:14 UTC, merged