work
ydb-platform/ydb pull request #9624
Opened 2024-09-23 10:24 UTC by andrewstalin

### Changelog entry

...

### Changelog category

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-26 11:48 UTC, azevaykin requested changes
Logic is becoming more complicated.
How about a unit test?

2024-09-27 02:27 UTC, andrewstalin commented
> Logic is becoming more complicated. How about a unit test?

What for? The functionality is used as part of the administrative UI once a year. There's not have anything to test there, just 200 lines of code with no state.

2024-09-30 12:10 UTC, azevaykin commented on ydb/core/statistics/service/ut/ut_http_request.cpp
> +        UNIT_ASSERT(msg->Answer.find("Analyze sent. OperationId:") != TString::npos);
UNIT_ASSERT_STRING_CONTAINS

2024-10-01 07:49 UTC, azevaykin approved these changes

2024-10-01 10:57 UTC, merged