Column Family for CS
ydb-platform/ydb pull request #9657
Opened 2024-09-23 16:03 UTC by vlad-gogov

2024-10-31 08:46 UTC, nikvas0 submitted a review, later dismissed
kqp part looks ok

2024-11-05 08:01 UTC, fexolm commented on ydb/core/tx/schemeshard/olap/columns/update.cpp
> +        errors.AddError("empty field name");
field "name" is empty

2024-11-05 08:07 UTC, fexolm submitted a review, later dismissed

2024-11-13 15:33 UTC, ijon requested changes
Looks ok in general. But please check again error messages.

2024-11-13 15:33 UTC, ijon commented on ydb/core/ydb_convert/table_description.cpp
> +        error = "Field `DATA` is not supported for OLAP tables";
This is the message that will be returned to the user.
So accuracy matters.

I would suggest adding column family name, the same way its done below.

2024-11-13 15:33 UTC, ijon commented on ydb/core/kqp/host/kqp_gateway_proxy.cpp
> +            error = "Field `DATA` is not supported for OLAP tables";
Its worth adding column family name.

2024-11-13 15:33 UTC, ijon commented on ydb/core/kqp/host/kqp_gateway_proxy.cpp
> +                errResult.AddIssue(NYql::TIssue("TableStore is not support Column Family"));
-> "does not support column families"

2024-11-13 15:56 UTC, ijon approved these changes, later dismissed

2024-11-14 08:34 UTC, ivanmorozov333 approved these changes, later dismissed

2024-11-14 08:42 UTC, nikvas0 submitted a review, later dismissed

2024-11-20 13:23 UTC, zverevgeny commented on ydb/core/formats/arrow/serializer/native.cpp
> +                                                        << "`. have to be: [" << levelMin << ":" << levelMax << "]");
minor: 
has to be ...
Но лучше expected:

2024-11-21 09:32 UTC, zverevgeny approved these changes

2024-11-21 10:38 UTC, merged