[CLI] bug fix.
ydb-platform/ydb pull request #9663
Opened 2024-09-23 19:05 UTC by pashandor789

### Changelog category 

* Bugfix

2024-09-23 19:53 UTC, maximyurchuk requested changes
Сделай описание плз зачем это нужно, в чем заключается фикс, ничего не понятно

2024-09-23 20:21 UTC, pashandor789 commented
> Сделай описание плз зачем это нужно, в чем заключается фикс, ничего не понятно



> Сделай описание плз зачем это нужно, в чем заключается фикс, ничего не понятно

Да сделал я сделал

2024-09-24 06:24 UTC, pavelvelikhov approved these changes

2024-09-24 08:15 UTC, maximyurchuk approved these changes

2024-09-24 08:26 UTC, merged