sys views has been added for workload manager documentation
ydb-platform/ydb pull request #9690
Opened 2024-09-24 09:54 UTC by dorooleg

### Changelog entry 

...

### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2025-02-12 07:25 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +Информация о системных таблицах связанных с пулами ресурсов и классификаторами пулов ресурсов можно найти на странице [{#T}](system-views.md#resource_pools).
```suggestion
Информацию о системных таблицах, связанных с пулами ресурсов и классификаторами пулов ресурсов, можно найти на странице [{#T}](system-views.md#resource_pools).
```

2025-02-12 07:25 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +`Owner` | Владеле пула ресурсов.<br/>Тип: `Utf8`.<br/>
```suggestion
`Owner` | Владелец пула ресурсов.<br/>Тип: `Utf8`.<br/>
```

2025-02-12 07:25 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +Получение информации о настройках пула ресурсов с именем `default`
```suggestion
Получение информации о настройках пула ресурсов с именем `default`:

```yql
SELECT
    Name,
    Config,
    Owner,
    Permissions,
    EffectivePermissions
FROM `.sys/resource_pools`
WHERE name = "default";
```


```

2025-02-12 07:25 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +Получение информации о настройках классификатора пула ресурсов с именем `olap`
```suggestion
### Пример

Получение информации о настройках классификатора пула ресурсов с именем `olap`:

```yql
SELECT
    Name,
    Rank,
    Config
FROM `.sys/resource_pools_classifiers`
WHERE name = "olap";
```

```

2025-02-12 07:25 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +`resource_pools` - таблица содержит информацию о настройках пулов ресурсов.
```suggestion
`resource_pools` - таблица содержит информацию о [настройках](../yql/reference/syntax/create-resource-pool.md#parameters) [пулов ресурсов](../concepts/glossary.md#resource-pool).
```

2025-02-14 06:40 UTC, azevaykin requested changes, later dismissed

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`resource_pools_classifiers` - таблица содержит информацию о настройках классификаторов пулов ресурсов.
Нужна ссылка, что вообще такое "классификатор пулов ресурсов"

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`resource_pools` - таблица содержит информацию о настройках пулов ресурсов.
Нужна ссылка, что вообще такое "пул ресурсов"

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`Permissions` | Доступы на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
Почему JSON, а не обычная строка?

Ожидается, что формат выдачи совпадает с https://ydb.tech/docs/ru/reference/ydb-cli/commands/scheme-permissions?version=main#list

Например:
```
ydb.granular.create_directory,ydb.granular.write_attributes
```

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`Permissions` | Доступы на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
Нужно явно указать, что права доступа в формате YDB
https://ydb.tech/docs/ru/yql/reference/syntax/grant?version=main#permissions-list

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`Permissions` | Доступы на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
```suggestion
`Permissions` | Права доступа на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
```

2025-02-14 06:40 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`EffectivePermissions` | Фактический доступ на объект пула ресурсов<br/>Тип: `JsonDocument`.
```suggestion
`EffectivePermissions` | Эффективные права доступа на объект пула ресурсов<br/>Тип: `JsonDocument`.
```

2025-02-14 07:24 UTC, dorooleg commented on ydb/docs/ru/core/dev/system-views.md
> +`Permissions` | Доступы на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
Тут нужны пары (sid, permission). Завернул в json чтобы можно было удобно с этим работать в yql.

2025-02-14 08:05 UTC, azevaykin commented on ydb/docs/ru/core/dev/system-views.md
> +`Permissions` | Доступы на объект пула ресурсов<br/>Тип: `JsonDocument`.<br/>
Тогда нужно с примерами показать необходимость нарушения нормальной формы.

2025-03-07 05:03 UTC, blinkov submitted a review, later dismissed

2025-03-07 06:55 UTC, dorooleg commented on ydb/docs/ru/core/dev/system-views.md
> +`DatabaseLoadCpuThreshold` | Порог загрузки CPU всей базы данных, после которого запросы не отправляются на выполнение и остаются в очереди.<br/>Тип: `Double`.<br/>
Да, проценты

2025-03-07 16:25 UTC, dorooleg commented on ydb/docs/ru/core/dev/system-views.md
> +`ResourceWeight` | Веса для распределения ресурсов между пулами.<br/>Тип: `Double`.<br/>
добавил

2025-03-07 16:25 UTC, dorooleg commented on ydb/docs/ru/core/dev/system-views.md
> +`DatabaseLoadCpuThreshold` | Порог загрузки CPU всей базы данных, после которого запросы не отправляются на выполнение и остаются в очереди.<br/>Тип: `Double`.<br/>
поправил

2025-03-09 09:32 UTC, fomichev3000 submitted a review, later dismissed
Я окнул, но просьба поправить комментарии.

2025-03-09 09:32 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +### Системные таблицы
Переименовали "Системные таблицы" в "Системные представления" (https://ydb.tech/docs/ru/dev/system-views) чтобы соответствовать общепринятым терминам. Так что надо и здесь поправить

2025-03-09 09:32 UTC, fomichev3000 commented on ydb/docs/ru/core/dev/resource-consumption-management.md
> +Информацию о системных таблицах, связанных с пулами ресурсов и классификаторами пулов ресурсов, можно найти на странице [{#T}](system-views.md#resource_pools).
аналогично, системные представления

2025-03-19 07:02 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +`resource_pools_classifiers` — таблица содержит информацию о [настройках](../yql/reference/syntax/create-resource-pool-classifier.md#parameters) [классификаторов пулов ресурсов](../concepts/glossary.
```suggestion
Системное представление `resource_pools_classifiers` содержит информацию о [настройках](../yql/reference/syntax/create-resource-pool-classifier.md#parameters) [классификаторов пулов ресурсов](../concepts/glossary.md#resource-pool-classifier).
```

2025-03-19 07:02 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +Структура таблицы:
```suggestion
Структура системного представления:
```

2025-03-19 07:02 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +Структура таблицы:
```suggestion
Структура системного представления:
```

2025-03-19 07:02 UTC, anton-bobkov commented on ydb/docs/ru/core/dev/system-views.md
> +Получение информации о настройках классификатора пула ресурсов с именем `olap`:
```suggestion
Следующий запрос выводит информацию о настройках классификатора пула ресурсов с именем `olap`:
```

2025-03-19 08:46 UTC, fomichev3000 approved these changes

2025-03-19 08:58 UTC, anton-bobkov approved these changes

2025-03-19 09:11 UTC, merged