Make pragma ForceJobSizeAdjuster public
ydb-platform/ydb pull request #9739
Opened 2024-09-24 22:21 UTC by avevad

### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

2024-09-25 19:25 UTC, nepal requested changes

2024-09-25 19:25 UTC, nepal commented on ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
> +    REGISTER_SETTING(*this, ForceJobSizeAdjuster);
Надо про апгрейд подумать - в конфиге сервиса сейчас вариант с подчеркиванием используется. Как yqlworker будет на такой конфигурации реагировать?

2024-09-30 08:19 UTC, rvu1024 commented on ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
> +    REGISTER_SETTING(*this, ForceJobSizeAdjuster);
Нормально он будет реагировать. Compaitibility тут не нужна. Прагмы с подчеркиванием все равно не видны пользователю, а воркер игнорирует неизвестные прагмы из конфига

2024-10-01 11:10 UTC, rvu1024 approved these changes

2024-10-01 11:12 UTC, nepal approved these changes

2024-10-01 15:57 UTC, merged