use iostream instead of printf
ydb-platform/ydb pull request #977
Opened 2024-01-12 15:52 UTC by va-kuznecov

2024-01-14 09:53 UTC, UgnineSirdis commented on ydb/core/base/logoblob.cpp
> +    o << "["
Maybe printing here `'['` instead of `"["` will be a bit faster?

2024-01-14 09:53 UTC, UgnineSirdis commented on ydb/core/base/traceid.cpp
> +        << "ID: " << RandomID << ", "
It will be a bit faster to output `"["` and `"ID: "` as one string.

2024-01-15 15:18 UTC, alexvru requested changes

2024-01-15 15:18 UTC, alexvru commented on ydb/core/base/logoblob.cpp
> +    o << '['
15 виртуальных вызовов нам для этого нужно :)

2024-01-15 15:26 UTC, alexvru approved these changes

2024-01-15 15:48 UTC, va-kuznecov commented on ydb/core/base/logoblob.cpp
> +    o << '['
ну как мы любим, пусть разработчики компиляторов и процессоров делают свою работу и оптимизируют виртуальные вызовы

2024-01-15 16:45 UTC, va-kuznecov commented on ydb/core/base/logoblob.cpp
> +    o << '['
побенчили с Сашей, получилось, что новая версия строго быстрее

ToString(Sprintf): 5.345924s
Out(snprintf): 5.017919s
ToString(stream): 3.712372s
Out(stream): 3.966677s

2024-01-15 16:49 UTC, merged