YQ-2730: use docker-compose random port mapping in connector integration tests
ydb-platform/ydb pull request #978
Opened 2024-01-12 15:59 UTC by vitalyisaev2

2024-01-14 19:15 UTC, tsmax2004 requested changes

2024-01-14 19:15 UTC, tsmax2004 commented on ydb/library/yql/providers/generic/connector/tests/utils/settings.py
>                  host='localhost',
does connector have access to `localhost` without 
```
network_mode: host
```
in `docker-compose.yml`?

maybe we should use service name (`clickhouse`) as host and internal port (`8123` or `9000`) as port here?

2024-01-14 19:50 UTC, tsmax2004 requested changes

2024-01-14 19:50 UTC, tsmax2004 commented on ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
> +        self.docker_compose_bin = os.path.realpath(
`os.path.realpath` is necessary?

2024-01-14 19:50 UTC, tsmax2004 commented on ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
> +        cmd = ['docker-compose', '-f', self.docker_compose_yml, 'port', service_name, str(internal_port)]
`self.docker_compose_bin` instead of `'docker-compose'`

2024-01-16 10:53 UTC, vitalyisaev2 commented on ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
> +        self.docker_compose_bin = os.path.realpath(
fixed

2024-01-16 15:28 UTC, tsmax2004 approved these changes

2024-01-16 15:37 UTC, tsmax2004 approved these changes

2024-01-16 19:21 UTC, uzhastik approved these changes

2024-01-16 19:24 UTC, merged