YDB-2321 Add subnet operations in IP UDF
ydb-platform/ydb pull request #981
Opened 2024-01-12 17:44 UTC by avevad

2024-01-23 14:34 UTC, blinkov commented on ydb/docs/en/core/yql/reference/yql-core/udf/list/ip.md
> +* ```Ip::GetSubnetByMask(String{Flags:AutoMap}, String{Flags:AutoMap}) -> String```: The second argument is the bit mask of a desired subnet.
what's the first argument?

2024-01-23 15:06 UTC, avevad commented on ydb/docs/en/core/yql/reference/yql-core/udf/list/ip.md
>  **Examples**
done

2024-01-23 15:06 UTC, avevad commented on ydb/docs/en/core/yql/reference/yql-core/udf/list/ip.md
> +* ```Ip::GetSubnetByMask(String{Flags:AutoMap}, String{Flags:AutoMap}) -> String```: The second argument is the bit mask of a desired subnet.
Clarification added

2024-01-24 08:15 UTC, rvu1024 requested changes

2024-01-24 08:15 UTC, rvu1024 commented on ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
> +        TIpAddressRange range = TIpAddressRange::FromCompactString(str);
Здесь лишняя аллокация строки. FromCompactString принимает на вход TStringBuf, а у TStringRef есть оператор приведения к TStringBuf

2024-01-25 08:04 UTC, rvu1024 approved these changes

2024-01-25 14:38 UTC, blinkov approved these changes

2024-01-25 14:38 UTC, blinkov commented on ydb/docs/ru/core/yql/reference/yql-core/udf/list/ip.md
> +* ```Ip::GetSubnetByMask(String{Flags:AutoMap}, String{Flags:AutoMap}) -> String``` - во втором аргументе битовая маска подсети
```suggestion
* ```Ip::GetSubnetByMask(String{Flags:AutoMap}, String{Flags:AutoMap}) -> String``` - в первом аргументе базовый адрес, а во втором — битовая маска подсети
```

2024-01-25 14:39 UTC, merged