Huge defrag smooth linear threshold
ydb-platform/ydb pull request #9825
Opened 2024-09-26 16:22 UTC by robdrynkin

* Not for changelog (changelog entry is not required)

2024-10-16 07:23 UTC, alexvru requested changes

2024-10-16 07:23 UTC, alexvru commented on ydb/core/blobstorage/vdisk/defrag/defrag_actor.cpp
> +        float defragThreshold) {
May be "double" here to make it uniform?

2024-10-18 13:18 UTC, alexvru approved these changes, later dismissed

2024-10-23 09:24 UTC, alexvru submitted a review, later dismissed

2024-11-07 11:35 UTC, va-kuznecov approved these changes

2024-11-07 11:54 UTC, merged