YQ-2356: integration tests for yq through generic provider
ydb-platform/ydb pull request #988
Opened 2024-01-14 20:26 UTC by tsmax2004

Added integration tests for YQ through generic provider using mocked TokenAccessor and Mdb

2024-01-15 09:40 UTC, vitalyisaev2 requested changes

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/fq/generic/docker-compose.yml
> +      - '6432'
Я бы вернул 5432

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/fq/generic/clickhouse/init.sql
> +INSERT INTO db.join_table VALUES (1, 10), (2, 20), (3, 30);
Я бы предложил сделать значения в столбце `data` уникальными для каждого источника. Желательно чтобы это были строки. Иначе можно пропустить ошибку (что-то не так сджойнилось или перепуталось, а мы и не заметили - так как данные во всех источниках одинаковые).

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/fq/generic/ya.make
> +END()
Этот файл надо актуализировать в соответствие с `connector/tests` (вместо LARGE - MEDIUM и прочее)

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/fq/generic/ya.make
> +)
здесь не нужен DEPENDS на `library/recipes/docker-compose/bin`?

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/tools/docker_compose_helpers/ya.make
> +    library/python/testing/yatest_common
интересно. у меня этого не потребовалось.

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/tools/fq_runner/kikimr_utils.py
> +
Мне кажется, что для compute_plane этих настроек query service недостаточно , там же больше полей, те же эндпойнты

2024-01-15 09:40 UTC, vitalyisaev2 commented on ydb/tests/tools/mdb_mock/__main__.py
> +    cluster_id = request.match_info['cluster_id']
а что означает `match_info`? это фреймворк aiohttp такими сущностями оперирует?

2024-01-15 10:14 UTC, tsmax2004 commented on ydb/tests/fq/generic/docker-compose.yml
> +      - '6432'
Зачем? Тогда придется сюда https://github.com/ydb-platform/ydb/blob/3fce1e1d6a5d465511e5dc19dcabed030499ddc4/ydb/core/fq/libs/db_id_async_resolver_impl/mdb_endpoint_generator.cpp#L72 прокидывать 5432 через env

2024-01-15 12:09 UTC, tsmax2004 commented on ydb/tests/fq/generic/ya.make
> +END()
добавил

2024-01-15 12:09 UTC, tsmax2004 commented on ydb/tests/fq/generic/clickhouse/init.sql
> +INSERT INTO db.join_table VALUES (1, 10), (2, 20), (3, 30);
done

2024-01-15 13:13 UTC, vitalyisaev2 commented on ydb/tests/fq/generic/docker-compose.yml
> +      - '6432'
А мы снаружи (из тестов) в PG:5432 и CH:8123/9000 не ходим? Только Коннектор туда ходит через докеровскую сеть? если так, то в docker-compose.yml надо у баз убрать ports, чтобы не было проброса портов наружу

2024-01-15 13:15 UTC, tsmax2004 commented on ydb/tests/fq/generic/docker-compose.yml
> +      - '6432'
не ходим, тк заполняются базы при инициализации. Тогда уберу ports

2024-01-15 13:16 UTC, vitalyisaev2 commented
В отчёте на CI всё ещё не увидел запуска `ydb/tests/fq/generiс`

2024-01-15 13:16 UTC, vitalyisaev2 requested changes
В отчёте на CI всё ещё не увидел запуска ydb/tests/fq/generiс

2024-01-15 13:20 UTC, tsmax2004 commented
> В отчёте на CI всё ещё не увидел запуска ydb/tests/fq/generiс

вот они

https://nebius.testmo.net/automation/runs/results/8290?group_by=automation_run_tests:status_id&group_id=2&filter=eyJtb2RlIjoxLCJjb25kaXRpb25zIjp7ImF1dG9tYXRpb25fcnVuX3Rlc3RzOmZvbGRlcl9pZCI6eyJ2YWx1ZXMiOls2NzEzNDE2XX19fQ

2024-01-16 10:16 UTC, vitalyisaev2 approved these changes, later dismissed

2024-01-18 08:13 UTC, vitalyisaev2 submitted a review, later dismissed

2024-01-19 12:01 UTC, vitalyisaev2 approved these changes

2024-01-19 12:02 UTC, merged