Mute and Test history update
ydb-platform/ydb pull request #9909
Opened 2024-09-30 15:45 UTC by naspirato

### Changelog entry 

Updated doc with info about test history and flaky tests
### Changelog category 

* Documentation (changelog entry is not required)

### Additional information

...

2024-10-01 04:52 UTC, blinkov requested changes
сами формулировки пока почти не вычитывал, в следующей итерации посмотрю детальнее

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +#### Как отключить(mute) тест <a id="how-to-mute"></a>
Это всё выглядит как контент для новой статьи, а не патча в эту — давай вынесем. А отсюда явно стоит тут сослаться.

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +#### Как отключить(mute) тест <a id="how-to-mute"></a>
```suggestion
#### Как отключить тест (mute) {#how-to-mute}
```

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +--Under construction--
удалить все такие фразы

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Ты молодец!
слишком неформальный тон для документации

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +
не хватает какого-то введения, в духе что если тест постоянно сломан или флапает, то его можно скрыть из отчетов CI, и ниже будет подробно объяснено как

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +- Через отчет PR
объяснить в чём разница между этими двумя опциями + оно выглядит как то, что лучше запихать в табы https://diplodoc.com/docs/en/syntax/cuts-tabs#tabs

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Добавьте issue в проект [Mute and Un-mute](https://github.com/orgs/ydb-platform/projects/45/views/6?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C126637100%5D).
это приватный проект, явно написать что делать, если туда нет доступа

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Установите `статус` на `Отключен`
судя по картинке оно Status и Muted — зачем переводить?

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Скопируйте строку под `Добавить строку в muted_ya.txt` (например, как на скриншоте, `ydb/core/kqp/ut/query KqpStats.SysViewClientLost`) и добавьте ее в [muted_ya.txt](https://github.com/ydb-platfor
опять же не понятно зачем переводить то, что в реальности на английском

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Скопируйте строку под `Добавить строку в muted_ya.txt` (например, как на скриншоте, `ydb/core/kqp/ut/query KqpStats.SysViewClientLost`) и добавьте ее в [muted_ya.txt](https://github.com/ydb-platfor
уточнить куда именно в файле добавлять — в конец, в лексикографическом порядке или ещё как-то

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Отредактируйте ветку для слияния, например, замените `{username}-patch-1` на `mute/{username}`.
звучит странно — что делать, если тебе нужно больше одной такой ветки?

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Проверить, что в комментарии появилось сообщение ![Muted new %N% tests](https://storage.yandexcloud.net/ydb-public-images/muted_new.png)
понятно, что не только тут это править, но сама фраза криво звучит: Muted N new tests, а не new N tests

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Получите "OK" от члена команды владельца теста в PR
Approve он на GitHub называется

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Сообщите команде владельца теста о новых отключениях - в личном сообщении или в общем чате (с упоминанием ответственного за команду)
написать где искать ответственных и правильный чат

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Добавьте issue в проект [Mute and Un-mute](https://github.com/orgs/ydb-platform/projects/45/views/6?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C126637100%5D).
Получаются слишком длинные плоские списки буллетов. Во-первых, для пошаговых инструкций лучше нумерованные, т.к. номера позволяют читателю легче запоминать где остановился. Во-вторых, лучше разбить плоский список на какие-нибудь крупные этапы подразделами, иначе за деревьями леса не видно.

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +#### Как включить(un-mute) тест <a id="how-to-unmute"></a>
```suggestion
#### Как включить тест (unmute) {#how-to-unmute}
```

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Отредактируйте имя PR как "Включить {имя теста}"
мы вроде как стараемся не использовать русский в описаниях PR

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Проверить, что в комментарии появилось ![сообщение](https://storage.yandexcloud.net/ydb-public-images/unmuted_tests.png)
слово «сообщение» станет alt'ом к картинке и просто так видно не будет + само сообщение хорошо бы тоже продублировать текстом

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Переместите issue в статус `Unmuted`
А закрывать issue точно не надо после этого всего?

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Ты молодец!
комментарии от предыдущего похожего списка выше тут тоже актуальны

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> + >Если вы хотите получить больше информации о стабильности вашего теста, посетите [dashboard](https://datalens.yandex/4un3zdm0zcnyr?tab=8JQ) (заполните поле `owner`=`{your_team_name}`)
не понятно зачем тут и ниже ` >` в начале строк

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> + >Не все muted тесты имеют issue в проекте GitHub, мы работаем над этим
не понятно какую пользу читателю даёт это замечание

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* кликните по метке с именем вашей команды, например [link to qp](https://GitHub.com/orgs/ydb-platform/projects/45/views/6?filterQuery=owner%3Aqp) отключенные тесты (cgi `?filterQuery=owner%3Aqp`)
зачем тут ссылка и рассказ про её параметры, если людям предлагается тыкать в интерфейсе?

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Выполните [Как включить(un-mute) тест](#how-to-unmute)
этот раздел назывался «найдите тесты» — эти шаги для такой цели явно лишние, вероятно эти два пункта стоит заменить на не входящие в пошаговый список заключительные слова что мол как нашли свои тесты, можете выбрать какие из них размьютить и дальше двигаться по той другой инструкции

либо возможно проще эти разделы местами поменять, тогда логичнее повествование будет без всяких ссылок

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +Дежурный инженер CI (в разработке) проверяет нестабильные тесты один раз в день (только в рабочие дни)
```suggestion
Дежурный инженер по CI проверяет нестабильные тесты один раз в каждый рабочий день.
```

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Нажмите ссылку `Mute`, которая создаст черновик issue в GitHub.
кажется это и так было одним из пунктов в инструкции из следующего пункта, тогда этот лишний

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Отличная работа!
снова слишком неформально для доки

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* Выполните шаги из [Как включить(un-mute) тест ](#how-to-unmute)
```suggestion
* Выполните шаги из [Как включить(un-mute) тест](#how-to-unmute)
```

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +* `Test summary` - считает `succes rate` теста для всех типов workflow и build_type в которых участвовал
```suggestion
* `Test summary` - считает `success rate` теста для всех типов workflow и build_type, в которых он участвовал
```

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +#### История тестов без авторизаций в testmo
сделать эту инструкцию основной, а старый текст перенести в конец, мол «а если у вас есть аккаунт в Testmo, то...»

2024-10-01 04:52 UTC, blinkov commented on ydb/docs/ru/core/contributor/suggest-change.md
> +##### Как читать дашборд
Написать введение что это вообще за дашборд, как устроен, как часто обновляется и т.п.

2024-10-01 14:54 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +  * Для FAIL и MUTE тестов появляется столбец `history` содержащий статус последних 5 запусков этого теста в postcommit проверках
Сейчас просто по сути будет обязательство держать доку сильно синхронизированной с дашбордом, это сложнее чем запихать максимум описания в сам дашборд

2024-10-01 15:02 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +### Как собирается история тестов
Мне кажется, что большинство этого раздела неинтересно пользователям, я бы это не клал сюда. В целом наверное полезно, но я бы предложил куда то рядом с upload_tests_results.py положить

С моей точки зрения этот документ должен быть направлен на пользователей в первую очередь, а не на внутреннюю разработку

2024-10-01 15:04 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +Аналитика (стабильность, срезы по дням, определение owner'a тестов etc) собирается в GitHub Action через workflow [Collect-analytics-run](https://github.com/ydb-platform/ydb/blob/main/.github/workflo
По идее не должно быть ссылки на github, нужно использовать относительные пути

2024-10-01 15:19 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +  * Чат для оповещения - YDV dev in GitHub , канал General, пример оповещения
Ну вот это точно не должно быть в публичных доках, у произвольного человека нет в этот канал доступа

2024-10-01 15:19 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +### Отключение (mute) нестабильных тестов {#mute-flaky}
Мне кажется это инструкция для CI команды, а не общего характера, мне кажется это надо выносить куда то в отдельное место

2024-10-01 15:19 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +# Автотесты и их стабильность
Слово analysis в имени файла написано с ошибкой

2024-10-01 15:19 UTC, maximyurchuk commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +![image.png](https://storage.yandexcloud.net/ydb-public-images/test_analitycs_1.png)
Зачем файлы в сторадж заливать, может лучше в репу просто класть?

2024-10-02 16:33 UTC, naspirato commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +# Автотесты и их стабильность
fixed

2024-10-02 16:34 UTC, naspirato commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +### Отключение (mute) нестабильных тестов {#mute-flaky}
подскажи в какой блок положить.
если пока такого нет то пусть пока тут будет

2024-10-02 16:34 UTC, naspirato commented on ydb/docs/ru/core/contributor/autotests-and-analisys.md
> +  * Чат для оповещения - YDV dev in GitHub , канал General, пример оповещения
fixed

2025-06-02 02:32 UTC, blinkov commented
@naspirato, do you intend to finish this?

2026-05-14 09:05 UTC, closed without merging